### ISSUE TITLE
Why is the fp16 engine file size larger than pt? (yolov5s)

### ISSUE THREAD

**Issue by youngjae-avikus** [wang-xinyu/tensorrtx#1000]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc. **Nano**
- OS, e.g. Ubuntu16.04, Win10, etc. **Jetpack 4.6.1**
- Cuda version **10.2**
- TensorRT version **8.2.3**

## About this repo

- which branch/tag/commit are you using? latest
- which model? yolov5, retinaface? yolov5

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

Why is the size of the fp16 engine file larger than pt?
Doesn't its bigger size affect inference time?
Does layer optimization occur greatly by increasing the size of the max workspace?

Thank you

**Comment by wang-xinyu** [comment]
It's related to the internal implementation of TensorRT.

**Comment by youngjae-avikus** [comment]
Is it normal to be bigger than pt because of various information in the fp16 engine size?

@wang-xinyu

**Comment by wang-xinyu** [comment]
yes
