### ISSUE TITLE
Why change rgbrgbrgb to rrrgggbbb  in yolov5?

### ISSUE THREAD

**Issue by jonbakerfish** [wang-xinyu/tensorrtx#1003]
Why do we need to change `rgbrgbrgb` to `rrrgggbbb` in yolov5?

https://github.com/wang-xinyu/tensorrtx/blob/f80f010ac4dd9aacbbbeb3546fd1eae6ab73bd0a/yolov5/preprocess.cu#L78-L85

**Comment by wang-xinyu** [comment]
@liuqi123123 Can you help?

**Comment by liuqi123123** [comment]
之前用cpu预处理时就是这么做的呀，我只是用gpu换了个做法。至于为啥这么做，是因为yolov5的训练推理都是这么设定的吧？图片必须是rrrgggbbb的形式
