### ISSUE TITLE
nvcc fatal   : Unknown option 'pthread'

### ISSUE THREAD

**Issue by manhtd98** [wang-xinyu/tensorrtx#1005]
## Env

- GPU V100, 
- Ubuntu16.04,
- Cuda version 11.6
- Cmake 3.16.3

## About this repo

- which branch/tag/commit are you using?
/swin-transformer/semantic-segmentation

## Your problem

- what is your command? 
`sudo make`
- what's your output?
[ 12%] Building CUDA object CMakeFiles/swintransformer.dir/UpsampleKernel.cu.o
nvcc fatal   : Unknown option 'pthread'
make[2]: *** [CMakeFiles/swintransformer.dir/build.make:63: CMakeFiles/swintransformer.dir/UpsampleKernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/swintransformer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by wang-xinyu** [comment]
Seems the CUDA is not properly installed,  or not configured properly in the CMakelist.

**Comment by manhtd98** [comment]
which tensorrt docker version you used?

**Comment by manhtd98** [comment]
set(OpenCV_DIR "D:\\opencv\\opencv346\\build")
set(TENSORRT_DIR "D:\\TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6\\TensorRT-7.0.0.11")
 how to set it in docker?

**Comment by manhtd98** [comment]
UpsamplePlugin.h:59:5: error: 'DimsCHW' does not name a type
   59 |     DimsCHW mInputShape;
I always got this error? Do you know how to fix it
