### ISSUE TITLE
yolov5.exe 构建失败

### ISSUE THREAD

**Issue by lefarcen** [wang-xinyu/tensorrtx#1006]
## Env

- GPU **GTX1060 6GB**
- OS, **Win10**
- Cuda version **11.5**
- TensorRT version  **8.2.1.8**
- **vs 2019**
## About this repo

- which branch/tag/commit are you using?
**mastar** 6.0?
- which model? 
**yolov5**

## Your problem
已完成生成项目“myplugins.vcxproj”的操作。
2>LINK : fatal error LNK1104: 无法打开文件“nvinfer.lib”
2>已完成生成项目“myplugins.vcxproj”的操作 - 失败。
3>------ 已启动全部重新生成: 项目: yolov5, 配置: Debug x64 ------
3>Building Custom Rule F:/githubs/tensorrtx/yolov5/CMakeLists.txt
3>cl: 命令行 warning D9025 :正在重写“/Os”(用“/Ot”)
3>cl: 命令行 error D8021 :无效的数值参数“/Wfatal-errors”
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(429,5): error MSB6006: “CL.exe”已退出，代码为 2。
3>已完成生成项目“yolov5.vcxproj”的操作 - 失败。
4>------ 已跳过全部重新生成: 项目: ALL_BUILD, 配置: Debug x64 ------
4>没有为此解决方案配置选中要生成的项目 
========== 全部重新生成: 成功 1 个，失败 2 个，跳过 1 个 ==========

![image](https://user-images.githubusercontent.com/20859779/170973204-fa49725b-22ed-4add-a3f2-84c4323dbdbb.png)

![image](https://user-images.githubusercontent.com/20859779/170968881-66a93a1a-7d2b-414d-b0b8-0487f5838477.png)
![image](https://user-images.githubusercontent.com/20859779/170968952-813538bc-3a93-4b67-a174-b75c004a9052.png)

遇到过跟 #666 一样的问题，然后用了最新的CMakeLists之后，就报以上的错误了

**Comment by Need-an-AwP** [comment]
![image](https://user-images.githubusercontent.com/113933967/196370644-9935ca9e-56f2-4504-9bca-4c465483eec6.png)

已启动生成…
1>------ 已启动生成: 项目: ZERO_CHECK, 配置: Debug x64 ------
2>------ 已启动生成: 项目: myplugins, 配置: Debug x64 ------
2>Building NVCC (Device) object CMakeFiles/myplugins.dir/Debug/myplugins_generated_yololayer.cu.obj
2>yololayer.cu
2>cl : 命令行 warning D9025: 正在重写“/Os”(用“/Ot”)
2>CUSTOMBUILD : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
2>cl : 命令行 error D8021: 无效的数值参数“/Wfatal-errors”
2>CMake Error at myplugins_generated_yololayer.cu.obj.Debug.cmake:220 (message):
2>  Error generating
2>  D:/AIII/test/tensorrtx-master/yolov5/build/CMakeFiles/myplugins.dir//Debug/myplugins_generated_yololayer.cu.obj
2>
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “..\yololayer.cu”的自定义生成已退出，代码为 1。
2>已完成生成项目“myplugins.vcxproj”的操作 - 失败。
3>------ 已启动生成: 项目: yolov5, 配置: Debug x64 ------
3>cl : 命令行 warning D9025: 正在重写“/Os”(用“/Ot”)
3>cl : 命令行 error D8021: 无效的数值参数“/Wfatal-errors”
3>已完成生成项目“yolov5.vcxproj”的操作 - 失败。
4>------ 已跳过生成: 项目: ALL_BUILD, 配置: Debug x64 ------
4>没有为此解决方案配置选中要生成的项目 
========== 生成: 成功 1 个，失败 2 个，最新 0 个，跳过 1 个 ==========


同生成错误，有解决方案吗

**Comment by sctrueew** [comment]
@lefarcen Hi, Have you solved your problem? I got this error:

invalid numeric argument '/Wfatal-errors'
