### ISSUE TITLE
第一次推理时间慢，后面正常

### ISSUE THREAD

**Issue by hnothing2016** [wang-xinyu/tensorrtx#1007]
## Env

- GPU, RTX1660
- OS, Win10
- Cuda version 11.1
- TensorRT 8.2.1

## About this repo

- which branch/tag/commit are you using?   **6.0**
- which model? **yolov5x** 

## Your problem

第一次推理时间要 531ms后面就快了，50ms左右，这个是正常情况吗？

![微信截图_20220531140415](https://user-images.githubusercontent.com/20417103/171103806-23dc4633-fde3-49a4-94bf-ef31354a0a22.png)

**Comment by tang662019** [comment]
> ## Env
> * GPU, RTX1660
> * OS, Win10
> * Cuda version 11.1
> * TensorRT 8.2.1
> 
> ## About this repo
> * which branch/tag/commit are you using?   **6.0**
> * which model? **yolov5x**
> 
> ## Your problem
> 第一次推理时间要 531ms后面就快了，50ms左右，这个是正常情况吗？
> 
> ![微信截图_20220531140415](https://user-images.githubusercontent.com/20417103/171103806-23dc4633-fde3-49a4-94bf-ef31354a0a22.png)

你不要用循环一直连续做图片推理，中间用cvwaitkey(3000)，不连续推理图片试试，推理时间就不稳定了！！！

**Comment by wang-xinyu** [comment]
This is normal,  GPU needs warmup.
