### ISSUE TITLE
GPU memory usage of INT8 model

### ISSUE THREAD

**Issue by xjsxujingsong** [wang-xinyu/tensorrtx#1008]
## Env

- GPU RTX3070 Laptop
- OS,  Win10 
- Cuda version: 11.1
- TensorRT version: TensorRT-8.2.2.1

- which branch/tag/commit are you using?  e7a5f0a
- which model? yolov5

## Your problem
I tried int8 conversion for yolov5 l and compared with s model. 
The speed of Int8 L model is 1.7 faster of fp16 L model. But the GPU memory is similar: 1GB vs 1.1GB. BTW, the fp16 s model costs 900MB GPU memory.

My question is why the GPU memory usage for Int 8 model is not half of the fp16 model?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xjsxu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xjsxu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | 640x640 |  
-- | -- | --
  | GPU memory |  
  | s | l
fp16 | 900M | 1.1G
int8 |   | 1G
  |   |  
  |   |  
  | speed |  
  | s | l
fp16 | 1.56 ms | 5.48 ms
int8 |   | 3.16 ms

</body>

</html>

**Comment by wang-xinyu** [comment]
Yes, it's not half of fp16. This is related to TensorRT internal implementations. You can ask in NV forum.
