### ISSUE TITLE
yololayer.cu:74 System.AccessViolationException

### ISSUE THREAD

**Issue by lefarcen** [wang-xinyu/tensorrtx#1012]
## Env

- GPU, **RTX1060**
- OS, **Win10**
- Cuda version **11.5**
- TensorRT version **8.2.1**

## About this repo

- which branch/tag/commit are you using?

**yolov5-5.0**

## Your problem
在我的电脑上，可以成功构建出wts、engine、yolov5.exe等，并且运行不会报错

但当我把构建出的yolov5.dll放到另一台电脑上使用，会报下面的异常

CUDA error 222 at F:\githubs\tensorrtx\yolov5\yololayer.cu:70CUDA error 222 at F:\githubs\tensorrtx\yolov5\yololayer.cu:74
未经处理的异常:  System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 DetectorTest.lib.Connect.Initialize(StringBuilder model_path, Int32 num)
   在 DetectorTest.Bot..ctor() 位置 C:\Users\93590\Documents\Visual Studio 2019\DetectorTest\DetectorTest\Bot.cs:行号 20
   在 DetectorTest.Form1..ctor() 位置 C:\Users\93590\Documents\Visual Studio 2019\DetectorTest\DetectorTest\Form1.cs:行号 21
   在 DetectorTest.Program.Main() 位置 C:\Users\93590\Documents\Visual Studio 2019\DetectorTest\DetectorTest\Program.cs:行号 19

![image](https://user-images.githubusercontent.com/20859779/172059808-3d396862-bc69-4e9e-9b22-7dedad823f42.png)

可以肯定的是：两台机子的cuda、cudnn、tensorRT版本是相同的。

我想问一下，对于这个报错，我应该如何下手？感谢！

**Comment by mingde510** [comment]
我想问下，你怎么解决atomicAdd未定义标识符 的问题，我这边一直报这个错误。

**Comment by lefarcen** [comment]
> 我想问下，你怎么解决atomicAdd未定义标识符 的问题，我这边一直报这个错误。

加  #include "sm_20_atomic_functions.h"
