### ISSUE TITLE
tensorrtx/yolov5/yololayer.h:6:10: fatal error: NvInfer.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by dailonggang** [wang-xinyu/tensorrtx#1013]
![a24afa0828af994a6717811b16d3fa6](https://user-images.githubusercontent.com/73026617/172301902-30943626-f771-4909-9a55-92a690ad7c3f.png)
Excuse me, how to solve this problem？

**Comment by AmeeraBawazir** [comment]
I faced the same issue with retinaface project. When trying to execute this chunk :
""""
git clone https://github.com/wang-xinyu/tensorrtx.git
cd tensorrtx/retinaface
// put retinaface.wts here
mkdir build
cd build
cmake ..
make
sudo ./retina_r50 -s  // build and serialize model to file i.e. 'retina_r50.engine'
wget https://github.com/Tencent/FaceDetection-DSFD/raw/master/data/worlds-largest-selfie.jpg
sudo ./retina_r50 -d  // deserialize model file and run inference.
""""
in particular when I reach to "make" step. i get the error :
 fatal error: NvInfer.h: No such file or directory
    6 | #include "NvInfer.h"
      |          ^~~~~~~~~~~
compilation terminated.

any idea how to solve this issue?

**Comment by wang-xinyu** [comment]
You need to install tensorrt properly.
And need to set the include path in cmake if you install the tensorrt into a custom path.

**Comment by AmeeraBawazir** [comment]
I installed tensorrt using pip following this guide  https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip , while forcing the tensorrt version to 7.2.2.1 using 
pip install --upgrade nvidia-tensorrt=='7.2.2.1'

any idea have to fix the issue for fatal error: NvInfer.h: No such file or directory  ?

**Comment by viwe-monai** [comment]
如果在build路径下cmake ..，然后make -j16，发现编译报错，缺少了什么文件，可以在build的上一级目录的CMakeLists.txt中，修改cuda、tensorRT、Opencv的路径，然后删除build文件夹生成的文件，重新cmake ..，然后make -j16
![image](https://github.com/user-attachments/assets/e7707dd8-ff52-4e10-a56c-1df93aa0ea30)
