### ISSUE TITLE
Image prediction box related problems

### ISSUE THREAD

**Issue by ZDLLLL** [wang-xinyu/tensorrtx#1014]
When I use tensorrt for prediction, part of the prediction frame on the predicted image exceeds the size of the image, and the complete prediction frame cannot be seen. And I output the coordinates of the prediction box and found that there are negative values, what is the reason for this phenomenon?
![image](https://user-images.githubusercontent.com/44689801/172571813-621de9e4-4d59-4402-bf6a-46a73d93b829.png)

**Comment by ZDLLLL** [comment]
![image](https://user-images.githubusercontent.com/44689801/173004405-d0e1d613-123b-41eb-a2d2-4ed60898bec3.png)
There is also a prediction box at the bottom of the picture, but there is no object, what is the reason?

**Comment by vjsrinivas** [comment]
@ZDLLLL How was your original model trained? This TensorRT port pads the resized input (also called letterbox). If your original model isn't trained like that, it could result in the network detecting objects in the padded location. When the coordinates are scaled back to the original image, you could get boxes in the extreme corners.

To clamp coordinate ranges in the C++ code, look for the `cv::rectangle` function call, and you can probably adjust the box results before that function call.
