### ISSUE TITLE
semantic-segmentation build error 

### ISSUE THREAD

**Issue by avBuffer** [wang-xinyu/tensorrtx#1016]
[100%] Linking CXX executable swintransformer
/usr/bin/ld: CMakeFiles/swintransformer.dir/UpsamplePlugin.cpp.o: in function `UpsamplePlugin::enqueue(int, void const* const*, void* const*, void*, CUstream_st*)':
UpsamplePlugin.cpp:(.text+0x1a4): undefined reference to `UpsampleInference(CUstream_st*, int, int, int, int, int, float, float, void const*, void*)'
/usr/bin/ld: CMakeFiles/swintransformer.dir/trainsform.cpp.o: in function `nvinfer1::PluginRegistrar<nvinfer1::layernormCreator>::~PluginRegistrar()':
trainsform.cpp:(.text._ZN8nvinfer115PluginRegistrarINS_16layernormCreatorEED2Ev[_ZN8nvinfer115PluginRegistrarINS_16layernormCreatorEED5Ev]+0x0): undefined reference to `vtable for nvinfer1::layernormCreator'
/usr/bin/ld: trainsform.cpp:(.text._ZN8nvinfer115PluginRegistrarINS_16layernormCreatorEED2Ev[_ZN8nvinfer115PluginRegistrarINS_16layernormCreatorEED5Ev]+0xc): undefined reference to `vtable for nvinfer1::layernormCreator'
/usr/bin/ld: CMakeFiles/swintransformer.dir/trainsform.cpp.o: in function `_GLOBAL__sub_I__Z15mblobFromImagesRKN2cv11_InputArrayERKNS_12_OutputArrayENS_5Size_IiEERKNS_7Scalar_IdEESB_bb':
trainsform.cpp:(.text.startup+0x28c): undefined reference to `nvinfer1::layernormCreator::layernormCreator()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/swintransformer.dir/build.make:129: swintransformer] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/swintransformer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by avBuffer** [comment]
Cuda11.4  TensorRT8.4.0

**Comment by wang-xinyu** [comment]
Can you try TensorRT 7.x?
@freedenS Do we support TensorRT 8.4?

**Comment by freedenS** [comment]
Swin Transform - Semantic Segmentation, looks like the authors are @wang-xinyu and @wdhao
