### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by Chenxianzhi** [wang-xinyu/tensorrtx#102]
Thank you for your amazing work!
I got a issue when i use the yolov3 in the branch of trt4.

I followed your README.md to run the model.

nvidia@nvidia-desktop:~/Desktop/tensorrtx-trt4/yolov3/build$ ./yolov3 -s
beginning
Loading weights: ../yolov3.wts
0
ERROR: Parameter check failed at: ../builder/Network.cpp::addConvolution::104, condition: kernelWeights.values != nullptr
yolov3: /home/nvidia/Desktop/tensorrtx-trt4/yolov3/yolov3.cpp:205: nvinfer1::ILayer* convBnRelu(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, int, int, int, int, int): Assertion `conv1' failed.
Aborted (core dumped)

**Comment by Chenxianzhi** [comment]
Could you please give me some advise about it?

**Comment by wang-xinyu** [comment]
The trt4 branch of yolov3 is using https://github.com/ayooshkathuria/pytorch-yolo-v3 as pytorch implementation.

**Comment by Chenxianzhi** [comment]
I fix that problem due to your advise. Thank you.
But i got another one when i use the command sudo ./yolov3 -s

nvidia@nvidia-desktop:~/Desktop/tensorrtx-trt4/yolov3/build$ sudo ./yolov3 -s
[sudo] password for nvidia: 
beginning
Loading weights: ../yolov3.wts
0
len 32
1
len 64
2
len 32
3
len 64
5
len 128
6
len 64
7
len 128
9
len 64
10
len 128
12
len 256
13
len 128
14
len 256
16
len 128
17
len 256
19
len 128
20
len 256
22
len 128
23
len 256
25
len 128
26
len 256
28
len 128
29
len 256
31
len 128
32
len 256
34
len 128
35
len 256
37
len 512
38
len 256
39
len 512
41
len 256
42
len 512
44
len 256
45
len 512
47
len 256
48
len 512
50
len 256
51
len 512
53
len 256
54
len 512
56
len 256
57
len 512
59
len 256
60
len 512
62
len 1024
63
len 512
64
len 1024
66
len 512
67
len 1024
69
len 512
70
len 1024
72
len 512
73
len 1024
75
len 512
76
len 1024
77
len 512
78
len 1024
79
len 512
80
len 1024
84
len 256
87
len 256
88
len 512
89
len 256
90
len 512
91
len 256
92
len 512
96
len 128
99
len 128
100
len 256
101
len 128
102
len 256
103
len 128
104
len 256
set name out
ERROR: ../builder/cudnnBuilderWeightConverters.cpp (293) - Misc Error in operator(): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
ERROR: ../builder/cudnnBuilderWeightConverters.cpp (293) - Misc Error in operator(): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
build out
yolov3: /home/nvidia/Desktop/tensorrtx-trt4/yolov3/yolov3.cpp:413: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.

**Comment by Chenxianzhi** [comment]
Could u please tell me how can I fix this problem? thank you.

**Comment by wang-xinyu** [comment]
Never met this error before. Can you provide more details? How did you generate the .wts and did you modify the  https://github.com/ayooshkathuria/pytorch-yolo-v3. And your trt version, etc.

**Comment by Chenxianzhi** [comment]
My platform is TX2, trt version is 5.0.
first i download the .weight file, after that i use the command python3 inference.py. Then i got the .wts file. I put it to the the tensorrtx-trt4/yolov3. After make, When i use the command sudo ./yolov3 -s. I got the problem.

**Comment by Chenxianzhi** [comment]
i do not modify anthing.

**Comment by wang-xinyu** [comment]
Are you using this https://github.com/wang-xinyu/pytorchx/tree/master/pytorch-yolo-v3 to generate .wts file?

Are you running pytorch on TX2?

**Comment by Chenxianzhi** [comment]
both is yes.

**Comment by wang-xinyu** [comment]
@Chenxianzhi what's the pytorch version in TX2? Can you try https://github.com/wang-xinyu/pytorchx/tree/master/pytorch-yolo-v3  on x86 PC, with Python 3.7， PyTorch 1.3.0?

**Comment by Chenxianzhi** [comment]
Pytorch version is 1.3.0, and the python version is 3.6.9. OK, I am going to try to find a PC to run the pytorch-yolo-v3. Thank you

**Comment by Chenxianzhi** [comment]
i remember i comment the module torchsummary

**Comment by wang-xinyu** [comment]
> i remember i comment the module torchsummary

That does not matter.


Or you can try yolov3-spp in branch trt4. https://github.com/wang-xinyu/tensorrtx/tree/trt4/yolov3-spp. Which is using https://github.com/ultralytics/yolov3 as pytorch implementation.

**Comment by Chenxianzhi** [comment]
just now i try generate .wts on PC. After that , i bank to TX2 to build and make again. When i use the sudo ./yolov3 -s, i got a new ERROR.

[100%] Built target yolov3
nvidia@nvidia-desktop:~/Desktop/tensorrtx-trt4/yolov3/build$ sudo ./yolov3 -s
[sudo] password for nvidia: 
beginning
Loading weights: ../yolov3.wts
0
len 32
1
len 64
2
len 32
3
len 64
5
len 128
6
len 64
7
len 128
9
len 64
10
len 128
12
len 256
13
len 128
14
len 256
16
len 128
17
len 256
19
len 128
20
len 256
22
len 128
23
len 256
25
len 128
26
len 256
28
len 128
29
len 256
31
len 128
32
len 256
34
len 128
35
len 256
37
len 512
38
len 256
39
len 512
41
len 256
42
len 0
ERROR: Parameter check failed at: ../builder/Network.cpp::addScale::164, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov3: /home/nvidia/Desktop/tensorrtx-trt4/yolov3/yolov3.cpp:197: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted

**Comment by Chenxianzhi** [comment]
Now i am going to try yolov3-spp. Thank you.
