### ISSUE TITLE
Integration of this project in a ROS code

### ISSUE THREAD

**Issue by sicarioakki** [wang-xinyu/tensorrtx#1026]
Has anyone tried to use this project as a ROS node? I am currently trying one, but facing errors while compiling the whole project with problems related to gcc version.

**Comment by jwrl7** [comment]
Yes. I was using Melodic on Jetson NX with JP 4.6
I was only building the Yolov5 sub director. I made a copy of the main.cpp file and only built the "inference side"
There is a simple topic for subscribing and one for publishing. 
I did not make use of the batch processing but given more thought it would be cool to have it; aggregate many input streams and do a single forward pass.

**Comment by Emiliyan192** [comment]
@jwrl7 Can you please share with me your project(also the ros-part) because I'm trying to do the same but I have multiple errors there and probably I'm missing something there. Thank you very much in advance

**Comment by Emiliyan192** [comment]
Especially I'm interested in how do you use the main function in yolov5.cpp file. Do you use the main function to be a callback for an image ? I've tried to create a subscriber for the camera images and used the main function in yolov5.cpp(which I renamed to objectDetectionCallback) to be a callback for the image topic, but for now I get so many different errors....

**Comment by omerfarukadastec** [comment]
@jwrl7 I'm trying to integrate to ROS. Unlike yours, I am building all the code and whenever I run my ROS node, it is building engine again and again. Which part of code should be built for get rid of "building engine loop"?

**Comment by omerfaruktemiz** [comment]
@jwrl7 I'm trying to integrate to ROS. Unlike yours, I am building all the code and whenever I run my ROS node, it is building engine again and again. Which part of code should be built for get rid of "building engine loop"?
