### ISSUE TITLE
./yolov5: error while loading shared libraries: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by APeiZou** [wang-xinyu/tensorrtx#1028]
## Env

- GPU, P40
- OS, Ubuntu18.04
- Cuda 10.2
- TensorRT 7.2.3.4

## About this repo

- master branch
-  yolov5 

## Your problem

- what is your command? 
sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
- what's your output?
./yolov5: error while loading shared libraries: libcudnn.so.8: cannot open shared object file: No such file or directory
- what output do you expect?

**Comment by wang-xinyu** [comment]
Environment issue, the cudnn, tensorrt, cuda, etc, are not properly installed.

**Comment by Ujs-lj** [comment]
and, you should to link the library, for example:
ln -snf libcudnn.so.8.x.x libcudnn.so.8
ln -snf libcudnn.so.8 libcudnn.so
