### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yuxiaoranyu** [wang-xinyu/tensorrtx#1029]
## Env

- GPU, 3060ti
- OS,Ubuntu18.04
- Cuda 11.3
- TensorRT 8.0.0.3

## Your problem

yolov5，可以正常运行fp16的模型转换和推理
在进行int8的时候，能够转换为int8模型，但是推理时报错Segmentation fault (core dumped)，在context.enqueue(batchSize, buffers, stream, nullptr);处报错
在T4显卡，1080ti显卡，Xavier（cuda均为10.2）上均能进行int8模型的转换和推理，这个报错原因能解答一下吗
万分感谢！

**Comment by Laowai01** [comment]
try building opencv with cuda.

**Comment by yuxiaoranyu** [comment]
I have build opencv with cuda again，but also Segmentation fault (core dumped)

**Comment by ZubairKhan001** [comment]
i guess you are using terminal or command line to run the code. you can try Spyder or any other IDE to check the exact line of error. Also, try commenting some library imports to figure out which library is causing the error.
