### ISSUE TITLE
能否给出Windows上的运行教程

### ISSUE THREAD

**Issue by soloIife** [wang-xinyu/tensorrtx#103]
我尝试在Windows运行例子，但是遇到了很多问题

**Comment by wang-xinyu** [comment]
有很多人在windows都跑通了，和ubuntu区别不大，有什么问题可以提出来。

**Comment by soloIife** [comment]
我跑过了，但是没用cmake，用vs配置了很多，中间遇见很多配置的错误，但最终都解决了

**Comment by wang-xinyu** [comment]
好的，如果愿意的话，可以分享一个windows vs运行教程，放到tutorials目录下，提交PR

**Comment by GesilaA** [comment]
@soloIife 能详细说一下怎么解决吗，我cmake没问题，打开sln生成myplugins时只提示cmd.exe已退出，没有其他错误提示。

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md

A windows tutorial had beed added.
