### ISSUE TITLE
Undefined reference 

### ISSUE THREAD

**Issue by TengjiaoYuanyangguo** [wang-xinyu/tensorrtx#1035]
Hello everyone, I'm trying to embed the yolov5 repository into a catkin workspace which is placed on my jetson-nano. I solved many problems with undefined reference function but a few of them are really hard to understand why they are not recognized. You can see the error that I'm getting from the building process. What I'm trying to do is to create a object_detection_node.cpp file which is gonna be the cuda_executable and all other files and libraries are included into the same directory. You an also find the cmake_list that I'm currently using. Can you at least point me why this problem occur ?  The necessary files are linked using targe_tlink_libraries and so should be recognized ? 

## Env

- GPU Maxwell, JetsonNano
- OS, e.g. Ubuntu18.04
- Cuda version 10.2
- TensorRT version 8.0.1
[cmakelist.txt](https://github.com/wang-xinyu/tensorrtx/files/9042094/cmakelist.txt)
![error](https://user-images.githubusercontent.com/81376600/177218450-014c4768-7ebe-4331-8e35-7669671c3d07.png)

**Comment by wang-xinyu** [comment]
@TengjiaoYuanyangguo This ROS integration is not related to tensorrtx repo. You need to fix the issue by yourself.
