### ISSUE TITLE
Multiple number of object detection problem in Yolov5s

### ISSUE THREAD

**Issue by PiyalGeorge** [wang-xinyu/tensorrtx#104]
Hi @wang-xinyu ,

I have trained a yolov5s for detecting 'Cups'. I converted the trained model to tensor-rt model and was able to run in a nano board by following your repo for yolov5s. The detection is happening really good. But if multiple Cups are shown infront of camera, the bounding boxes are not shown for the new and old, or detection happens very less. That is, The detection is kind of not happening with multiple Cups. My doubt is, have you set some 'maximum detection output' kind of parameter that restrict if multiple objects are detected? Is there a way i can fix this?

**Comment by wang-xinyu** [comment]
In yololayer.h, the `MAX_OUTPUT_BBOX_COUNT` is 1000 by default.

You can also adapt `IGNORE_THRESH ` in yololayer.h. And `NMS_THRESH`,  `CONF_THRESH` in yolov5s.cpp.

**Comment by neethuj95** [comment]
Hi @wang-xinyu , I have a doubt regarding parameters- INPUT_H, INPUT_W in yolov5/yololayer.h .

I have trained a yolov5s model in 640X640. Then to convert to tensorrt model and run, I used your repo, I have changed the input size to INPUT_H = 416, INPUT_W = 416 in yolov5/yololayer.h (with this input size, i'm getting good FPS in Nano board). My camera input is FHD(1980X1080). Now As per my understand this is how things work:

The camera input 1980X1080 is resized to 416X416 by the cpp code. Then this 416X416 input image is fed to Yolov5s model of 640X640. So large image is first resized to small, then this small image is enlarged and given to model [flow:1980X1080->416X416->640X640]. Is my understanding correct?

When a large image is resized to small image and given to detection model with smaller dimensions, we might lose many features, right? and detection of smaller objects might get effected.

So If this is the situation and my original camera input is 1980X1080, will following method be able to give good detection in smaller objects:

I will train a yolov5s model in 1280X1280, Then will give INPUT_H = 416, INPUT_W = 416 in yolov5/yololayer.h . And camera input size is 1980X1080. [flow:1980X1080->416X416->1280X1280] . Will this be able to give good results for smaller objects?

**Comment by wang-xinyu** [comment]
The model size or weight size is not related to input size, it depends on the kernel size and channels in each conv layer.  For 640 or 416 or whatever, the weight size would be same.

But if you train the model with 640, then the weights would fit for 640.

So if you want to use 416 in the end, you'd better train with 416.
