### ISSUE TITLE
Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry

### ISSUE THREAD

**Issue by Cuzny** [wang-xinyu/tensorrtx#1044]
## Env

Jetson NX + Cuda 10.2 + TRT 8.2.1.8

## About this repo

SlowFast （RoI Head）

## Your problem
When I run the code: 
     doInference_slowfast(*context_action, data_fast, data_slow, proposals, prob_data, 1);
It will raise a segmentation fault.
But when I comment it, it shows:
[07/12/2022-13:59:02] [E] [TRT] 1: [pluginV2Runner.cpp::load::290] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[07/12/2022-13:59:02] [E] [TRT] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)

Here is my IPluginCreator:
    ITensor* inputTensors_roi[] = {proposals, avgpool->getOutput(0)};
    auto creator2 = getPluginRegistry()->getPluginCreator("RoiAlign", "1");
    PluginField pField2[1];
    int *s2 = new int[4];
    s2[0] = 8;
    s2[1] = 0;
    s2[2] = MAX_OUTPUT_COUNT;
    s2[3] = avgpool->getOutput(0)->getDimensions().d[0];
    pField2[0].data = s2;
    pField2[0].length = 4;
    pField2[0].type = PluginFieldType::kINT32;
    pField2[0].name = "factor";
    PluginFieldCollection pluginData2;
    pluginData2.nbFields = 1;
    pluginData2.fields = pField2;
    IPluginV2 *pluginObj2 = creator2->createPlugin("RoIAlign", &pluginData2);
    auto roiAlignLayer = network->addPluginV2(inputTensors_roi, 2, *pluginObj2);

#define PLUGIN_NAME "RoiAlign"
#define PLUGIN_VERSION "1"

class API RoiAlignPluginCreator : public IPluginCreator{

    const char *getPluginName() const TRT_NOEXCEPT override {
        return PLUGIN_NAME;
    }

    const char *getPluginVersion() const TRT_NOEXCEPT override {
        return PLUGIN_VERSION;
    }
    IPluginV2Ext *createPlugin(const char *name, const PluginFieldCollection *fc) TRT_NOEXCEPT override {
        
        assert(fc->nbFields == 1);
        int *p_netinfo = (int*)(fc->fields[0].data);
        int pooler_resolution = p_netinfo[0];
        int sampling_ratio = p_netinfo[1];
        int num_proposals = p_netinfo[2];
        int out_channels = p_netinfo[3];
        float spatial_scale = 1.0/16.0;
        return new RoiAlignPlugin(pooler_resolution, spatial_scale, sampling_ratio, num_proposals, out_channels);

    }
}

**Comment by wang-xinyu** [comment]
Does slowfast exist in this repo?
