### ISSUE TITLE
推理时间不稳定

### ISSUE THREAD

**Issue by hengyanchen** [wang-xinyu/tensorrtx#1046]
## Env

- GPU：3050
- OS：Win10
- Cuda version：11.2
- TensorRT version：7.2.3.4

## About this repo

yolov5: 5.0
batch_size:    1

## Your problem
请问大佬，为啥同一张图片推理时间波动很明显，不是前几张！
![test](https://user-images.githubusercontent.com/76552951/178627218-2b70277d-b168-4b4b-bb92-a9204a7b73fb.png)

**Comment by wang-xinyu** [comment]
It's might related to your GPU power mode.

**Comment by hengyanchen** [comment]
ideally i agree with you ,but it's doesn't work when i try to seting Nvidia PowerMizerMode value, ;but setting GPU clock frequency Can solving instability caused by program delay; actually it also solve my application problem. but i still full of doubts
