### ISSUE TITLE
请问yolov5修改了网络结构，还可以直接使用这个来进行推理么？

### ISSUE THREAD

**Issue by qiuchun** [wang-xinyu/tensorrtx#1048]
请问一下，我对yolov5网络结构进行修改，比如增加一个检测层，增加注意力机制等模块，是不是要在yolov5.cpp对应的网络结构部分继续宁增加对应的模块，然后再重新编译生成.exe来进行模型转换与推理，还是有别的方法进行推理？求大佬指教！

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/issues/966#issuecomment-1186742852

**Comment by qiuchun** [comment]
大佬，请问是在yolov5.cpp中的build_engine()函数中构造模型网络结构那里，直接添加自己改造过的网络结构么？就像pytorch中修改网络结构那样？

**Comment by wang-xinyu** [comment]
yes

**Comment by Anoue** [comment]
> 
你好，你这边问题解决了嘛，当我增加一个小目标的检测层时候，虽然能够生成engine文件 ，但是效果特别差

**Comment by Anoue** [comment]
> 请问一下，我对yolov5网络结构进行修改，比如增加一个检测层，增加注意力机制等模块，是不是要在yolov5.cpp对应的网络结构部分继续宁增加对应的模块，然后再重新编译生成.exe来进行模型转换与推理，还是有别的方法进行推理？求大佬指教！

你好你好，请问你有没有成功推理修改后的网络模型啊，可以交流一下吗？

**Comment by 123-Zhao** [comment]
> > 请问一下，我对yolov5网络结构进行修改，比如增加一个检测层，增加注意力机制等模块，是不是要在yolov5.cpp对应的网络结构部分继续宁增加对应的模块，然后再重新编译生成.exe来进行模型转换与推理，还是有别的方法进行推理？求大佬指教！
> 
> 你好你好，请问你有没有成功推理修改后的网络模型啊，可以交流一下吗？

**Comment by 123-Zhao** [comment]
> > 请问一下，我对yolov5网络结构进行修改，比如增加一个检测层，增加注意力机制等模块，是不是要在yolov5.cpp对应的网络结构部分继续宁增加对应的模块，然后再重新编译生成.exe来进行模型转换与推理，还是有别的方法进行推理？求大佬指教！
> 
> 你好你好，请问你有没有成功推理修改后的网络模型啊，可以交流一下吗？

你好，请问你后续推理成功了嘛
