### ISSUE TITLE
 fatal error: cuda_runtime_api.h: No such file or directory when make

### ISSUE THREAD

**Issue by jameslele** [wang-xinyu/tensorrtx#105]
~/tensorrtx/lenet/build$ make 
Scanning dependencies of target lenet
[ 50%] Building CXX object CMakeFiles/lenet.dir/main.cpp.o
/home/jj/**tensorrtx/lenet/main.cpp:2:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include "cuda_runtime_api.h"**
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/lenet.dir/build.make:62: recipe for target 'CMakeFiles/lenet.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/lenet.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/lenet.dir/all' failed
make[1]: *** [CMakeFiles/lenet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

But ~/tensorrtx/lenet/build$ ls /usr/local/cuda/include/cuda_runtime_api.h
/usr/local/cuda/include/cuda_runtime_api.h
and ~/tensorrtx/lenet/build$ $LD_LIBRARY_PATH 
bash: /usr/local/cuda/include:/usr/local/cuda/lib64

Somebody has idea? Thx!

**Comment by wang-xinyu** [comment]
You can adapt the `include_directories` in CMakeLists.txt.

**Comment by jameslele** [comment]
@wang-xinyu thanks for your tips. The problem was resolved after I changed 
"include_directories(/usr/local/cuda-9.0/targets/aarch64-linux/include)
link_directories(/usr/local/cuda-9.0/targets/aarch64-linux/lib)" in CMakeLists.txt to 
"include_directories(/usr/local/cuda/targets/x86_64-linux/include)
link_directories(/usr/local/cuda/targets/x86_64-linux/lib)"
