### ISSUE TITLE
如何定义新的算子

### ISSUE THREAD

**Issue by xuhaohao86** [wang-xinyu/tensorrtx#1052]
## Env

- GPU, 3060.
- OS,Win10.
- Cuda version 11.0
- TensorRT version 7.2.3.4

请教一下作者，针对网络中tensorrt不支持的算子，该如何定义新的算子，然后再构建网络，创建engine？谢谢

**Comment by wang-xinyu** [comment]
You can refer to any plugins in this repo. For example, the yololayer plugin of yolov5.

**Comment by xuhaohao86** [comment]
谢谢，请教一下，为什么在yolov5的工程中，申明在yololayer.h的类和函数，定义为什么要写在yololayer.cu中？为什么不写在yololayer.c中？这两者有什么区别吗？

**Comment by wang-xinyu** [comment]
.cu contains CUDA code, not a pure cpp code.
