### ISSUE TITLE
This error appears when compiling YOLov6 6.0. Can anyone help someone help?

### ISSUE THREAD

**Issue by songjiahao-wq** [wang-xinyu/tensorrtx#1053]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "void __cdecl preprocess_kernel_img(unsigned char *,int,int,float *,int,int,struct CUstream_st *)" (?preprocess_kernel_img@@YAXPEAEHHPEAMHHPEAUCUstream_st@@@Z)，函数 main 中引用了该符号	yolov5	D:\yanyi\project_process\Completed_projects\yolo-deploy\tensorrtx-master\yolov5\build\yolov5.obj	1

**Comment by wang-xinyu** [comment]
Our code doesn't support windows directly, some changes are required.
