### ISSUE TITLE
something wrong after running : python3 gen_wts.py -w yolov5s.pt -o yolov5s.wts

### ISSUE THREAD

**Issue by chengzihencai** [wang-xinyu/tensorrtx#1059]
env:TX2 NX jetpack 4.5.1 
Yolo v5s 5.0
tensorrtx 5.0

I try to generate .wts from pytorch with .pt,  run : python3 gen_wts.py -w yolov5s.pt -o yolov5s.wts
I got yolov5s and :
`Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(gen_wts.py:10240): Gdk-CRITICAL **: 15:27:05.007: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed`

Is there any problem with the code?(I failed in using yolov5s with Deepstream,and I am finding the reason )

**Comment by wang-xinyu** [comment]
The error is from deepstream, not from gen_wts.py.
And deepstream integration is not within the scope of this repo.

**Comment by jo-dean** [comment]
add this in the get_wts.py
```
import matplotlib 
matplotlib.use('Agg') 
```
