### ISSUE TITLE
修改efficientnet输出层

### ISSUE THREAD

**Issue by stealth0414** [wang-xinyu/tensorrtx#1060]
## Env

- GPU, nano
- OS,  Ubuntu18.04
- Cuda version 10.2
- TensorRT version 8.0

## About this repo

- which branch/tag/commit are you using? efficientnet
- which model? yolov5, retinaface?

## Your problem

我训练了一个输出层为7*1280的efficientnet模型，原efficientnet网络的输出层为1000*1280 请问如何修改代码生成我的wts文件

**Comment by wang-xinyu** [comment]
Normally, the gen_wts.py doesn't needs to be modified. But the .cpp code needs, especially the createEngine() function.
