### ISSUE TITLE
while running yolov5s.engine,problems occured:  read ./build/yolov5.engine error!why?Is this version priblem?

### ISSUE THREAD

**Issue by JJYGood** [wang-xinyu/tensorrtx#1061]
## Env

- GPU： Nano4GB.
- OS：Ubuntu 18.04.5 LTS
- Cuda version：10.2
- TensorRT version:7.1.3

## About this repo

- which model: yolov5s

## Your problem

- what is your command? sudo ./yolov5 -d ./build/yolov5.engine ../samples
- what's your output? read ./build/yolov5.engine error!

**Comment by wang-xinyu** [comment]
where is your ./yolov5 and where is your yolov5.engine?
Please check the steps again.
