### ISSUE TITLE
对于修改过结构的模型要如何进行转换？

### ISSUE THREAD

**Issue by chengzihencai** [wang-xinyu/tensorrtx#1066]
如题，我对yolov5的backbone进行了更换，如果向生成基于这个模型的engine文件应该对tensorrtx的哪部分进行调整？

**Comment by wang-xinyu** [comment]
yolov5.cpp build_engine()

**Comment by Anoue** [comment]
你好，请问你有没有成功转换修改后的yolov5呀？

**Comment by Anoue** [comment]
> 如题，我对yolov5的backbone进行了更换，如果向生成基于这个模型的engine文件应该对tensorrtx的哪部分进行调整？

你好，请问你有没有成功转换修改后的模型啊？可以交流一下吗？
