### ISSUE TITLE
Can we use the same libmyplugins.so with any converted model.

### ISSUE THREAD

**Issue by Nuwan1654** [wang-xinyu/tensorrtx#1067]
## Env
- Jetson AGX Orin
- OS: Ubuntu20.04
- branch: main
- model:  yolov5 v6.0

Actually, this is a question, I am working on a project that required to do Object detection on jetson AGX Orin, I have successfully converted a yolov5 model using `tensorrtx` and done the inference, I have 2 questions.

1.  Can we use the same `libmyplugins.so` file for different converted models? 
2.  Confident and NMS thresholds are used in yolov5.cpp and are they only used for inference with c++ or before the conversion (later will be used with python) do I need to change that to the value which Iám hoping to use in python?

**Comment by wang-xinyu** [comment]
1. Yes, you can.
2. These 2 thresholds are also defined in .py. You can change them in py https://github.com/wang-xinyu/tensorrtx/blob/46dccf11eab50f8ae93e95246714d6a0d116c829/yolov5/yolov5_trt.py#L17

**Comment by Nuwan1654** [comment]
Thank you for the information.

> 1. Yes, you can.
> 2. These 2 thresholds are also defined in .py. You can change them in py https://github.com/wang-xinyu/tensorrtx/blob/46dccf11eab50f8ae93e95246714d6a0d116c829/yolov5/yolov5_trt.py#L17
