### ISSUE TITLE
swin-transformer\semantic-segmentation编译报错，error : object of abstract class type "nvinfer1::fillmask" is not allowed

### ISSUE THREAD

**Issue by xinsuinizhuan** [wang-xinyu/tensorrtx#1068]
windows VS2019 cuda11.3 cudnn 8,2  tensorrt 8.2.4
编译的时候，报错，可能是tensorrt8.2.4兼容问题，每个.cu文件编译的时候，里面的 new xxx 报错：
比如：fillmask.cu
xxx\fillmask.cu(112): error : object of abstract class type "nvinfer1::fillmask" is not allowed:
1>            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider
1>
xxx\fillmask.cu(167): error : object of abstract class type "nvinfer1::fillmask" is not allowed:
1>            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider
1>
xxx\fillmask.cu(175): error : object of abstract class type "nvinfer1::fillmask" is not allowed:
1>            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider
1>
1>4 errors detected in the compilation of "xxx/fillmask.cu".

![图片](https://user-images.githubusercontent.com/40679769/183297620-0a0f5b32-4c29-471e-8aef-8ea29f58dfdf.png)

**Comment by wang-xinyu** [comment]
please try 7.x

**Comment by xinsuinizhuan** [comment]
现在tensort7.2.3最高支持到cuda11.2。更换到低版本，整个cuda cudnn，以及所有的库，都得重新编译和替换，有点得不偿失。我尝试其他模型吧。
