### ISSUE TITLE
trt7 yolov4:error: member function declared with "override" does not override a base class member

### ISSUE THREAD

**Issue by cyzcz2** [wang-xinyu/tensorrtx#1074]
Hi,Wang

I try to convert yolov4 on Jetson TX2.but meet below issue.
could you help to check it?
the version of tensorrt is 7.2

home/yolo/yolov4/mish.h(33): error: member function declared with "override" does not override a base class member

/home/yolo/yolov4/mish.h(33): warning: function "nvinfer1::IPluginV2::enqueue(int32_t, const void *const *, void **, void *, cudaStream_t)" is hidden by "nvinfer1::MishPlugin::enqueue" -- virtual function override intended?

/home/yolo/yolov4/mish.h(64): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::MishPlugin::configurePlugin" -- virtual function override intended?

/home/yolo/yolov4/mish.cu(107): error: object of abstract class type "nvinfer1::MishPlugin" is not allowed:
            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider

/home/yolo/yolov4/mish.cu(144): error: declaration is incompatible with "int nvinfer1::MishPlugin::enqueue(int, const void *const *, void **, void *, cudaStream_t) const"
/home/yolo/yolov4/mish.h(33): here

/home/yolo/yolov4/mish.cu(181): error: object of abstract class type "nvinfer1::MishPlugin" is not allowed:
            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider

/home/yolo/yolov4/mish.cu(190): error: object of abstract class type "nvinfer1::MishPlugin" is not allowed:
            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider

5 errors detected in the compilation of "/tmp/tmpxft_000041bb_00000000-6_mish.cpp1.ii".
CMake Error at detector_generated_mish.cu.o.cmake:279 (message):
  Error generating file
  /home/yolo/yolov4/./detector_generated_mish.cu.o

yolov4/CMakeFiles/detector.dir/build.make:492: recipe for target 'yolov4/CMakeFiles/detector.dir/src/detector_generated_mish.cu.o' failed

**Comment by wang-xinyu** [comment]
I doubt you are using tensorrt8.x.
Can you confirm?
