### ISSUE TITLE
Open ended question, based on this code I implemented in a personal project

### ISSUE THREAD

**Issue by rlewkowicz** [wang-xinyu/tensorrtx#1079]
Windows 11/3090ti/2080ti/cuda 11.7, tensort 8.4

All of this worked, until I had to reformat and rebuild. I swear the hardest part about ML is dependencies lol. 

This is a super non specific question, and I'm just out of ideas, and I feel like I'm crazy. No errors, no output, it just crashes. 

```
    string onnx_file = cv::format("C:\\Resources\\5l.onnx");
    string model_file = cv::format("C:\\Resources\\5l.trtmodel");
    int test_batch_size = 1;

    if (!exists(model_file)) {
        SimpleYolo::compile(
            mode, type,                 // FP32?FP16?INT8
            test_batch_size,            // max batch size
            onnx_file,                  // source 
            model_file,                 // save to
            1 << 30,
            "inference"
        );
    }
```

This will be somewhat similar to your simple example. Load some files, if the engine doesn't exist, create it. Here's the crazy part, I can remove both of these, and it still works, it just dies when you first go to do anything to the engine. I don't know. There's not a ton of places I can ask about this. There's no way, that this should be able to continue past this point without these files.

**Comment by wang-xinyu** [comment]
You need to debug inside the SimpleYolo::compile() function.

**Comment by rlewkowicz** [comment]
I'm dumb this is from a different implementation. I'm working through to many and i lose track of where im at
