### ISSUE TITLE
yolov5模型与官方模型结构不一致

### ISSUE THREAD

**Issue by LostThinker** [wang-xinyu/tensorrtx#108]
您好，我发现您的yolov5实现和官方目前的实现不一致，请问能提供您当时的yaml文件吗，我需要训练自己的数据集，非常感谢！

**Comment by wang-xinyu** [comment]
June 22, 2020: PANet updates: new heads, reduced parameters, improved speed and mAP

https://github.com/ultralytics/yolov5/commit/364fcfd7dba53f46edd4f04c037a039c0a287972

试试他的这个commit
