### ISSUE TITLE
yolov5-4.0  failed to compile

### ISSUE THREAD

**Issue by wangmuzhi126** [wang-xinyu/tensorrtx#1083]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/94220579/186057983-cfaccfe7-0872-464a-8a4d-1d9f96801829.png">

**Comment by wang-xinyu** [comment]
4.0 might not support trt8 API. Please try trt7.

**Comment by wangmuzhi126** [comment]
> 4.0 might not support trt8 API. Please try trt7.

think you!
