### ISSUE TITLE
Custom model and detail tutorial

### ISSUE THREAD

**Issue by nguyentrongnhat4869** [wang-xinyu/tensorrtx#1086]
## Env

- GPU, RTX1080
- OS, e.g. Ubuntu18.04
- Cuda version: 11.1
- TensorRT version: 7.2

## About this repo

- master
- arcface

## Your problem

Hi, thanks for your great repo! I have a question what is the method of doing it. Specifically for arcface, how can you create that .cpp file to serve the conversion. If I want to custom model arcface, how do I convert a custom model. Can you give me more detailed blogs or documentation? Thank!

**Comment by wang-xinyu** [comment]
The best documentation is the source code.
You can also check the getting started tutorial.

**Comment by nguyentrongnhat4869** [comment]
thank you!
