### ISSUE TITLE
Feature Request : Swin IR

### ISSUE THREAD

**Issue by lazy-nurd** [wang-xinyu/tensorrtx#1088]
Hey Team,
I wanted to request the Swin IR ( https://github.com/JingyunLiang/SwinIR ) - Large conversion to TensorRT. I have seen that Swin Transformer but I can't understand how to use this for Swin IR - Large conversion. Can you please provide the conversion of Swin IR - Large conversion to tensorrt. This will be highly appreciated.
Thanks

**Comment by lazy-nurd** [comment]
@wang-xinyu Can you please help

**Comment by wang-xinyu** [comment]
We don't have such plan to add this. But PR is welcomed.

**Comment by lazy-nurd** [comment]
@wang-xinyu Ok Sure. Can you look at Swin-IR and tell me that can we use Swin-Transformer provided by you for it's conversion ?
