### ISSUE TITLE
yolov4 

### ISSUE THREAD

**Issue by yishunzhijian** [wang-xinyu/tensorrtx#109]
yolov4 执行make之后出现
warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::MishPlugin::configurePlugin" -- virtual function override intended?
能编译完成。

执行 ./yolov4 -s 出现
[W] [TRT] Half2 support requested on hardware without native FP16 support, performance will be negatively affected.

执行 ./yolov4 -d  ../../yolov3-spp/samples出现
[W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles

最后结果 ：
81ms
58ms
请问这属于正常水平吗

**Comment by wang-xinyu** [comment]
正常，可以多跑几张看看速度，也可以和darknet比较

**Comment by yishunzhijian** [comment]
> 正常，可以多跑几张看看速度，也可以和darknet比较

确实比darknet快，谢谢。
我用生成yolov4.engine放到darknet中测试视频FPS，为什么不出框呢？，感觉没快多少呀
