### ISSUE TITLE
While getting the engine, I met the cuda error 1,failed to get the engine as I expected.

### ISSUE THREAD

**Issue by PatekGao** [wang-xinyu/tensorrtx#1095]
## Env

- GPU, RTX3080laptop
- OS, Ubuntu18.04
- Cuda version :cuda_11.1.TC455_06.29190527_0
- TensorRT version : 7.2.3.4

## About this repo

- which branch/tag/commit are you using?
- I'm using yolov5 release v6.0
- which model? yolov5, retinaface?
- yolov5

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- While doing the command "sudo ./yolov5 -s [.wts] [.engine] [n/s/m/l/x/n6/s6/m6/l6/x6 or c/c6 gd gw]  // serialize model to plan file" I met some problems.
- 
- command "sudo ./yolov5 -s yolov5s.wts start.engine m".
-

- what's your output?

After waiting for a moment, I received as followed

"
CUDA error 1 at /home/stevegao/tensorrtx/yolov5/yololayer.cu:52yolov5: /home/stevegao/tensorrtx/yolov5/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed.
已放弃
"
- what output do you expect?

An engine can be used.

I don't know what's going on with my CUDA, but it seems that my "nvcc -V" and "nvidia-smi" can run succcessfully.
My partner got the engine successfully with the "yolov5s.wts". 
I'm looking forward to your early reply.

**Comment by wang-xinyu** [comment]
can you try the official trained .pt file?

**Comment by PatekGao** [comment]
@wang-xinyu Thanks a lot，every thing runs as expected right now.
