### ISSUE TITLE
Convert .pb file to .wts

### ISSUE THREAD

**Issue by donipologhimire** [wang-xinyu/tensorrtx#1096]
I can easily convert the .pt file to .wts, is there a way I can convert a .pb ( tensorflow) file to .wts . If not, is there a method to convert .pb file to .pt file. Help would be appreciated.

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/tree/master/psenet is from tensorflow,  you can refer to this.

**Comment by donipologhimire** [comment]
Thank you. It works
