### ISSUE TITLE
./yolov5-cls -d yolov5s-cls.engine ../samples not able to detect class_id, and conf

### ISSUE THREAD

**Issue by bahadurthakur** [wang-xinyu/tensorrtx#1097]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
can you try the newest commit?

**Comment by bahadurthakur** [comment]
I am using new commit , here

I am trying to test yolov5-cls classification  model there i am able to build sample and inference as well

but how can I preprocess and  output after inference for 

class label and confidence 

thanks you

**Comment by bahadurthakur** [comment]
> 

thank you
