### ISSUE TITLE
Mobilenet v2  serialize model to plan file Aborted

### ISSUE THREAD

**Issue by donipologhimire** [wang-xinyu/tensorrtx#1098]
## Env

- GPU, e.g. Jetston AGX  Xavier
- OS, e.g. Ubuntu18.04
- Cuda version : 10.2.89
- TensorRT : TensorRT Python 2 support is deprecated, and will be dropped in a future version!

## About this repo

- which branch/tag/commit are you using? master
- which model?  mobilenetv2

## Your problem

- what is your command? e.g. 'sudo ./mobilenet -s
- what's your output? 
-```
 Loading weights: ../mobilenet.wts
len 0
[09/07/2022-23:29:46] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
mobilenet: /media/costar/D8A4F4ECA4F4CDCE/JPL/mobilenet/tensorrtx/mobilenet/mobilenetv2/mobilenet_v2.cpp:107: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted
```



I used mobilenetv1, is there a repo for converting .wts to .engine for mobilenetv1 . I want to convert the mobilenet.wts to mobilnet.engine

**Comment by donipologhimire** [comment]
The mobilienetv1 was not trained in the Jetson AGX Xavier, it was trained in a CPU. Is this the reason why?  I found a repository for mobilenetv1 [](https://github.com/tjuskyzhang/mobilenetv1-ssd-tensorrt), however I am getting the same error

**Comment by wang-xinyu** [comment]
There is no mobilenetv1 in this repo.
You can try ONNX, it should work fine.
