### ISSUE TITLE
output 与prob关系咨询

### ISSUE THREAD

**Issue by ygygyeah** [wang-xinyu/tensorrtx#1099]
您好，请教一下。
在yolov5.cpp中，这里的 &prob[b * OUTPUT_SIZE] 应该是prob数组中某一个元素的地址，在common.hpp中，output应该是&prob[b * OUTPUT_SIZE]的指针变量，但是在下面代码为什么有取output下标的操作呢？
![image](https://user-images.githubusercontent.com/47774299/189154229-6e6a6de4-9b6c-4ea4-bc08-8ea2671719fc.png)

![image](https://user-images.githubusercontent.com/47774299/189153295-c4747f34-8bcb-4f09-8ebc-b1bcda4724ea.png)

**Comment by ausk** [comment]
p[idx] => *(p+idx) ， c 指针基本操作
