### ISSUE TITLE
make error for the new yolov4 directory

### ISSUE THREAD

**Issue by Harryqu123** [wang-xinyu/tensorrtx#11]
Hi, thanks for the excellent work in advance.
When I try to run  the latest yolov4 directory, after I follow the instruction to successfully get the wts file, when I try to make the c++ code, I get the following error.

/usr/bin/ld: warning: libcudart.so.10.2, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libnvinfer.so, may conflict with libcudart.so.10.0
/usr/bin/ld: warning: libzstd.so.1.3.7, needed by //home/student/anaconda3/lib/libtiff.so.5, not found (try using -rpath or -rpath-link)
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_initCStream'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_freeCStream'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_maxCLevel'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFOpen@LIBTIFF_4.0'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_createCStream'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_isError'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_getErrorName'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_endStream'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_createDStream'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_initDStream'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_freeDStream'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFWriteDirectory@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_compressStream'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
//home/student/anaconda3/lib/libtiff.so.5: undefined reference to `ZSTD_decompressStream'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.3.4.9: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov4.dir/build.make:117: recipe for target 'yolov4' failed
make[2]: *** [yolov4] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/yolov4.dir/all' failed
make[1]: *** [CMakeFiles/yolov4.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Is there any suggestion to how to fix that or it is just because the directory is not cleaned up yet?
Thanks for the repo again

**Comment by wang-xinyu** [comment]
It seems you have both cuda10.2 and cuda10.0 installed in your machine.

And your opencv in system dir may conflict with opencv in anaconda.

**Comment by Harryqu123** [comment]
Okay, I will try that.
Thanks for your repo and reply again
