### ISSUE TITLE
The realization principle of function addBatchNorm2d

### ISSUE THREAD

**Issue by persuelx** [wang-xinyu/tensorrtx#110]
hi，There are some questions about the implementation of this function，IScaleLayer* addBatchNorm2d(INetworkDefinition *network, std::map<std::string, Weights>& weightMap, ITensor& input, std::string lname, float eps)。Can you tell me why it is so realized.  thks

**Comment by wang-xinyu** [comment]
The batchnorm in this repo is implemented using scale layer.  You can refer to https://blog.csdn.net/github_28260175/article/details/103515033#TRT_API_35

**Comment by persuelx** [comment]
thk u，yesterday ihave searched the blog




| |
长沙理工大学+刘向
|
|
邮箱：liuxiangxxl@163.com
|

签名由 网易邮箱大师 定制

On 07/31/2020 12:14, Wang Xinyu wrote:

The batchnorm in this repo is implemented using scale layer. You can refer to https://blog.csdn.net/github_28260175/article/details/103515033#TRT_API_35

**Comment by bulingda** [comment]
> hi，There are some questions about the implementation of this function，IScaleLayer* addBatchNorm2d(INetworkDefinition *network, std::map<std::string, Weights>& weightMap, ITensor& input, std::string lname, float eps)。Can you tell me why it is so realized. thks

@persuelx Have you solved this problem?
