### ISSUE TITLE
How use TensorRT API to add conv1d layers?

### ISSUE THREAD

**Issue by zhudongwork** [wang-xinyu/tensorrtx#1103]
There is conv1d in my pytorch model. When converting to tensorRT, how to use the tensorRT API to define the conv1d layer?

**Comment by wang-xinyu** [comment]
Can you check the tensorrt api doc?
I remember the API is called `convNd`.

**Comment by QIANXUNZDL123** [comment]
> There is conv1d in my pytorch model. When converting to tensorRT, how to use the tensorRT API to define the conv1d layer?

TensorRT貌似不支持1维卷积，可以去英伟达论坛看看，有人提到了并且官方也给出了回答
