### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by VanCholen** [wang-xinyu/tensorrtx#1104]
## Env

- GPU, RTX3090
- OS, Ubuntu 20.04
- Cuda, 11.3
- TensorRT version, TensorRT-8.0.1.6

- which branch/tag/commit are you using?
yolov5-5.0

- which model? yolov5, retinaface?
yolov5s   download from **https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt**

## Your problem
I can **successfully** generate **yolov5** and **yolov5s.wts** from source file, but when I try "sudo ./yolov5 -s yolov5s.wts yolov5s.engine s" , I get an error such as follows:
Loading weights: yolov5s.wts
Building engine, please wait for a while...
[09/15/2022-23:33:27] [W] [TRT] Detected invalid timing cache, setup a local cache instead
Segmentation fault (core dumped)

**Comment by wang-xinyu** [comment]
Seems like a bug in TensorRT.
Can you try tensorrt7.x or tensorrt8.2 or 8.4?

**Comment by VanCholen** [comment]
Thanks for your apply, I will try it again.

**Comment by ClydeU420** [comment]
> Thanks for your apply, I will try it again.

hi, have you solve that, I have the same error.

**Comment by VanCholen** [comment]
The TensorRT API have updated in TensorRT 8 , you'd better to  keep the same version of TensorRT with author.
