### ISSUE TITLE
python gen_wts.py weights/yolov3.weights，Operation error report？_pickle.UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by hande6688** [wang-xinyu/tensorrtx#111]
python gen_wts.py weights/yolov3.weights，ultralytics/yolov3
An error is reported when running the above command:
Traceback (most recent call last):
  File "gen_wts.py", line 10, in <module>
    model.load_state_dict(torch.load(weights, map_location=device)['model'])
  File "/home/anaconda3/envs/yolov3/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/anaconda3/envs/yolov3/lib/python3.7/site-packages/torch/serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by wang-xinyu** [comment]
are you using master branch of https://github.com/ultralytics/yolov3,  and master branch of this repo?

**Comment by honghande** [comment]
@wang-xinyu Yes, the yolov3 I used is this version https://github.com/ultralytics/yolov3

**Comment by JensenGao** [comment]
有可能时torch的版本不对
