### ISSUE TITLE
Use gen_wts.py script transform yolov5s-cls.pt to yolov5s-cls.wts, there show an error "no attribute 'anchors'"

### ISSUE THREAD

**Issue by leadercxn** [wang-xinyu/tensorrtx#1110]
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/43691182/191446380-50c7151d-31aa-49e1-8973-dfde2e0bb068.png">
As shown in the attached picture, gen_wts.py script file work well on yolov5s.pt, but didn't work on yolov5s-cls.pt

**Comment by wang-xinyu** [comment]
--type is not specified.

**Comment by leadercxn** [comment]
> 

ok, thanks ~
