### ISSUE TITLE
yolov5编译问题

### ISSUE THREAD

**Issue by ygygyeah** [wang-xinyu/tensorrtx#1111]
## Env

- Xavier NX
- Ubuntu18.04
- Cuda version：10.2
- TensorRT version:8.2.1

## About this repo

 yolov5

## Your problem

我在jetson NX 编译yolov5，没有修改这个cmakelist.txt的内容，也可以编译成功，这是为什么呢？
![image](https://user-images.githubusercontent.com/47774299/191883081-eb60458e-a350-431f-89eb-274a6971f566.png)

**Comment by wang-xinyu** [comment]
因为nx的trt和cuda都在系统路径下了
