### ISSUE TITLE
yolov5 CUDA error 1

### ISSUE THREAD

**Issue by weironggege** [wang-xinyu/tensorrtx#1112]
## Env

- GPU  RTX3060
- OS Ubuntu 18.04
- Cuda version:11.0
- TensorRT version:7.2.1.6

## About this repo

- https://github.com/ultralytics/yolov5  (use default master)
- the model is yolov5s.pt

## Your problem

- the complier is OK, can build excute file yolov5
- then run 'sudo ./yolov5 -s yolov5s.wts yolov5s.engine s' the problem occur 'CUDA error 1 at /home/chengjizh/qc/WR/tensorrtx/yolov5/yololayer.cu:52yolov5: /home/chengjizh/qc/WR/tensorrtx/yolov5/yololayer.cu:52: virtual' nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed. 

- i find the yololayer.cu:52   the bug is located at 'CUDA_CHECK(cudaFreeHost(mAnchor))'  
- How can I sove the problem?

**Comment by yunyouke** [comment]
have you solved this problem?

**Comment by weironggege** [comment]
> have you solved this problem?

yeah, I have solve the problem. you should change the version from yolov5v6.2 to yolov5v6.1. That's OK
