### ISSUE TITLE
Bad results using engine file (YoLov7-tiny)

### ISSUE THREAD

**Issue by LowPower-Center** [wang-xinyu/tensorrtx#1114]
## Env

- Jetson nano  ubuntu18.04LTS

- I build yolov7-tiny.engine following the markdown file using default configs.But when I run engine file  on  test dataset, it cannot show the right results as yolov7-tiny.pt does.
- I donot know why would this happened.How can I got the right results?

**Comment by wang-xinyu** [comment]
Can you try the the pretrained weights first?

cc: @lindsayshuo

**Comment by lindsayshuo** [comment]
> Can you try the the pretrained weights first?
> 
> cc: @lindsayshuo

i tried the tiny engine on the samples dir, the results is right, did you get the right engine ?
try this command: "./yolov7  -s ../yolov7-tiny.wts  ../yolov7-tiny.engine t"

**Comment by lindsayshuo** [comment]
> ## Env
> 
>     * Jetson nano  ubuntu18.04LTS
> 
>     * I build yolov7-tiny.engine following the markdown file using default configs.But when I run engine file  on  test dataset, it cannot show the right results as yolov7-tiny.pt does.
> 
>     * I donot know why would this happened.How can I got the right results?

try this:https://github.com/lindsayshuo/tensorrtx/releases/tag/yolov7

**Comment by timothylimyl** [comment]
@LowPower-Center ensure that you are using v0.1 in the official yolov7 repo

**Comment by LowPower-Center** [comment]
I tried  official methods to convert my yolov7-tiny.pt to yolov7-tiny-nms.trt file, it works well in colab. And  I also trained yolov5 on the same dataset ,using this repo to convert to engine file. The yolov5s.engine works well,too. For me, only yolov7 model can’t work .

**Comment by LowPower-Center** [comment]
> @LowPower-Center ensure that you are using v0.1 in the official yolov7 repo

I think there is no other version of yolov7 release,I did use v0.1

**Comment by LowPower-Center** [comment]
> I tried official methods to convert my yolov7-tiny.pt to yolov7-tiny-nms.trt file, it works well in colab. And I also trained yolov5 on the same dataset ,using this repo to convert to engine file. The yolov5s.engine works well,too. For me, only yolov7 model can’t work .

when using yolov7.engine to infer a image , it often shows many bounding box. I think the NMS method  caused this error, but I did’t know why and how to cope with this error.

**Comment by timothylimyl** [comment]
@LowPower-Center , I did some training and do see the same issue as you on a custom dataset. works for yolov7 v0.1 pytorch (all bounding box makes sense) but the current tensorrt conversion does have more bboxes everywhere together with correct bounding boxes

**Comment by wang-xinyu** [comment]
@timothylimyl @LowPower-Center Need to use the yaml in deploy/ folder to train, not the yaml in training/ folder.
 https://github.com/WongKinYiu/yolov7/blob/main/cfg/deploy/yolov7.yaml

**Comment by wang-xinyu** [comment]
The difference is that the deploy/ yaml is using Detect head, while the training/ yaml has IDetect head.

**Comment by oforomar** [comment]
@wang-xinyu Can you explain please how to use the deploy yaml file, I have the same problem after converting my custom yolov7-tiny to engine file?

**Comment by wang-xinyu** [comment]
@oforomar When you run the train.py, you need to specify --cfg.

**Comment by oforomar** [comment]
So I need to retrain the model?
I thought you were referring to the Re-parameterization script [here](https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb)
