### ISSUE TITLE
yolov7  编译出错  求助

### ISSUE THREAD

**Issue by z13228604287** [wang-xinyu/tensorrtx#1115]
## Env
-VS   2019
- Cuda version  11.4
- TensorRT version  8

## About this repo

[tensorrtx](https://github.com/wang-xinyu/tensorrtx)/yolov7/

## Your problem

编译完成  生成解决方案  就报这错，不知道问题出在哪

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB8066	“..\yololayer.cu”的自定义生成已退出，代码为 1。	myplugins	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB8066	“..\preprocess.cu”的自定义生成已退出，代码为 1。	yolov7	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	

**### 本人的  CMakeLists.txt  文件**
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
`cmake_minimum_required(VERSION 2.6)

project(yolov7)

set(OpenCV_DIR "E:\\OPENCV\\opencv\\build") 
set(OpenCV_INCLUDE_DIRS ${OpenCV_DIR}\\include)
set(OpenCV_LIB_DIRS ${OpenCV_DIR}\\x64\\vc15\\lib) 
set(OpenCV_Debug_LIBS "opencv_world460d.lib")
set(OpenCV_Release_LIBS "opencv_world460.lib") 

add_definitions(-std=c++11)
add_definitions(-DAPI_EXPORTS)
option(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE Debug)

find_package(CUDA REQUIRED)

if(WIN32)
enable_language(CUDA)
endif(WIN32)

include_directories(${PROJECT_SOURCE_DIR}/include)
# include and link dirs of cuda and tensorrt, you need adapt them if yours are different

if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
    message("embed_platform on")
    include_directories(/usr/local/cuda/targets/aarch64-linux/include)
    link_directories(/usr/local/cuda/targets/aarch64-linux/lib)
else()
    message("embed_platform off")
    # cuda
    include_directories(C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\include)
    link_directories(C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\lib\\x64)

    # tensorrt
    include_directories(E:\\OPENCV\\TensorRT\\include)
    link_directories(E:\\OPENCV\\TensorRT\\lib)
endif()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Ofast -g -Wfatal-errors -D_MWAITXINTRIN_H_INCLUDED")
cuda_add_library(myplugins SHARED yololayer.cu)
target_link_libraries(myplugins nvinfer cudart)

find_package(OpenCV)
include_directories(${OpenCV_INCLUDE_DIRS})

cuda_add_executable(yolov7 calibrator.cpp yolov7.cpp preprocess.cu)

target_link_libraries(yolov7 nvinfer)
target_link_libraries(yolov7 cudart)
target_link_libraries(yolov7 myplugins)
target_link_libraries(yolov7 ${OpenCV_LIBS})

if(UNIX)
add_definitions(-O2 -pthread)
endif(UNIX)`
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by z13228604287** [comment]
这是我修改的

- cmake_minimum_required(VERSION 2.6)
- 
- project(yolov7)
- 
- 
- set(OpenCV_DIR "E:\\OPENCV\\opencv\\build") 
- set(OpenCV_INCLUDE_DIRS ${OpenCV_DIR}\\include)
- set(OpenCV_LIB_DIRS ${OpenCV_DIR}\\x64\\vc15\\lib) 
- set(OpenCV_Debug_LIBS "opencv_world460d.lib")
- set(OpenCV_Release_LIBS "opencv_world460.lib") 
- 
- add_definitions(-std=c++11)
- add_definitions(-DAPI_EXPORTS)
- option(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
- set(CMAKE_CXX_STANDARD 11)
- set(CMAKE_BUILD_TYPE Debug)
- 
- find_package(CUDA REQUIRED)
- 
- if(WIN32)
- enable_language(CUDA)
- endif(WIN32)
- 
- include_directories(${PROJECT_SOURCE_DIR}/include)
- # include and link dirs of cuda and tensorrt, you need adapt them if yours are different
- 
- 
- if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
-     message("embed_platform on")
-     include_directories(/usr/local/cuda/targets/aarch64-linux/include)
-     link_directories(/usr/local/cuda/targets/aarch64-linux/lib)
- else()
-     message("embed_platform off")
-     # cuda
-     include_directories(C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\include)
-     link_directories(C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\lib\\x64)
- 
-     # tensorrt
-     include_directories(E:\\OPENCV\\TensorRT\\include)
-     link_directories(E:\\OPENCV\\TensorRT\\lib)
- endif()
- 
- 
- set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Ofast -g -Wfatal-errors -D_MWAITXINTRIN_H_INCLUDED")
- cuda_add_library(myplugins SHARED yololayer.cu)
- target_link_libraries(myplugins nvinfer cudart)
- 
- find_package(OpenCV)
- include_directories(${OpenCV_INCLUDE_DIRS})
- 
- cuda_add_executable(yolov7 calibrator.cpp yolov7.cpp preprocess.cu)
- 
- target_link_libraries(yolov7 nvinfer)
- target_link_libraries(yolov7 cudart)
- target_link_libraries(yolov7 myplugins)
- target_link_libraries(yolov7 ${OpenCV_LIBS})
- 
- if(UNIX)
- add_definitions(-O2 -pthread)
- endif(UNIX)

**Comment by wang-xinyu** [comment]
@z13228604287 Can you try the latest code?
