### ISSUE TITLE
yolov4 LNK1181	无法打开输入文件“Release\myplugins.lib”

### ISSUE THREAD

**Issue by YINYIPENG-EN** [wang-xinyu/tensorrtx#1116]
## Env

- GPU 1650.
- Win10
- Cuda 10.2
- TensorRT 8.2.4.2

## About this repo

- yolov4

## Your problem

无法打开输入文件“Release\myplugins.lib”

**Comment by wang-xinyu** [comment]
This is related to compile CUDA code in VS.  When you install CUDA, you need enable the VS extension.
