### ISSUE TITLE
Cropping of Detected object 裁剪照片功能

### ISSUE THREAD

**Issue by jocelyntehsr** [wang-xinyu/tensorrtx#1118]
## Env

- GPU Nano
- OS, Ubuntu16.0
- Cuda version 10.2
- TensorRT version 8.0

## About this repo

- which model? yolov5

## Your problem

Hi, i am able to run the yolov5 successfully on my nano. However, I have a question, does TensorRTx has the function to save the detected object in a cropped image? Something like https://github.com/ultralytics/yolov5/issues/5412#issuecomment-955672088

This is because I'd like to process the image in OpenCV after it is detected by yolov5. Thank you

您好，我成功执行到了yolov5 engine model。但是，我想请问TensorRTx 有没有功能去把检测到的物体裁剪起来然后另存为图像？如链接所示：https://github.com/ultralytics/yolov5/issues/5412#issuecomment-955672088

我想要把检测到的物体串流进 opencv去处理。谢谢！

**Comment by wang-xinyu** [comment]
This part you need to implement it by yourself. Not difficult.
