### ISSUE TITLE
Why is the batchsize of the tensorrt inference of yolov5 only 1?

### ISSUE THREAD

**Issue by zxz-cc** [wang-xinyu/tensorrtx#1119]
I just found the batchsize of the tensorrt inference of yolov5 only1.Is there any problem in inference code?

**Comment by wang-xinyu** [comment]
It is 1 by default,  it's configurable.

**Comment by zxz-cc** [comment]
> It is 1 by default, it's configurable.

But when i set it to 4, the all results are just the same. Why?

**Comment by wang-xinyu** [comment]
Did you re-build everything after changing batchsize?

**Comment by hch-baobei** [comment]
> Did you re-build everything after changing batchsize?
I set batch_size to 8, re-build, and the h dimension in the result is all 0.

**Comment by hch-baobei** [comment]
> Did you re-build everything after changing batchsize?
I set batch_size to 8, and the h dimension in the result is all 0.

**Comment by wang-xinyu** [comment]
@zxz-cc @hch-baobei Did you mean that only the first output image has bounding box?
