### ISSUE TITLE
./yolov3: error while loading shared libraries: libcublas.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by honghande** [wang-xinyu/tensorrtx#112]
Environment
TensorRT Version: 7.0.0.11
GPU Type: 2080Ti
CUDA Version: 10.0
CUDNN Version: 7.6.5
Operating System + Version: ubuntu 18.04
python3.7
pytorch1.5.0
ultralytics/yolov3 
Model trained with own data pt can be transformed into yolov3.wts，run “ sudo ./yolov3 -s”，The following is the wrong report:
./yolov3: error while loading shared libraries: libcublas.so.10.0: cannot open shared object file: No such file or directory

run “./yolov3 -s”，The following is the wrong report:

![image](https://user-images.githubusercontent.com/29244715/88905011-63cd3700-d288-11ea-9b2e-73cc6e633c79.png)

**Comment by honghande** [comment]
I downloaded yolov3.pt and ran with the following error:
python gen_wts.py weights/yolov3.pt
![image](https://user-images.githubusercontent.com/29244715/88920216-098ba080-d29f-11ea-9aeb-bb35400c632a.png)

**Comment by wang-xinyu** [comment]
@honghande what's the python codes are you using?
For master branch of this repo, the yolov3 is using https://github.com/ultralytics/yolov3

**Comment by honghande** [comment]
@wang-xinyu Yes, the yolov3 I used is this version https://github.com/ultralytics/yolov3

**Comment by wang-xinyu** [comment]
For your yolov3.pt,   how many classes in it?  Is it 80?

**Comment by honghande** [comment]
@wang-xinyu ，是的，ultralytics/yolov3作者提供的pt下载路径：https://drive.google.com/drive/folders/1LezFG5g3BCW6iYaV89B2i64cqEUZD7e0

**Comment by wang-xinyu** [comment]
cfg用的是yolov3.cfg吗，还是yolov3-1cls.cfg?

**Comment by honghande** [comment]
@wang-xinyu 是yolov3.cfg

**Comment by wang-xinyu** [comment]
现在还是这个报错吗？python gen_wts.py weights/yolov3.pt

**Comment by honghande** [comment]
你更新了代码吗

**Comment by wang-xinyu** [comment]
报错那个27，1024，1，1不对劲
应该是255，对应80个class，3x（80+5），
如果是27的话，对应的3x（4+5），4个class，
可能是cfg文件不对

**Comment by wang-xinyu** [comment]
我没更新，这块代码是没问题的，很多人都跑通了

**Comment by honghande** [comment]
我刚刚也发现了，谢谢你，我再试试

**Comment by honghande** [comment]
Darknet('cfg/yolov3.cfg', (608, 608))，我的cfg中高与宽是416

**Comment by wang-xinyu** [comment]
宽高没影响

**Comment by honghande** [comment]
![image](https://user-images.githubusercontent.com/29244715/89100892-8ea4c000-d42d-11ea-96b9-ee7b2bc866b4.png)
cfg是正确的，我的类别是4个，就是27

**Comment by wang-xinyu** [comment]
cfg的class是4，但是.pt的class是80，所以报错了

**Comment by honghande** [comment]
是对的，我再试试自己的数据集
谢谢你，有微信吗，可以交流一下

**Comment by wang-xinyu** [comment]
readme下面有我的微信

**Comment by honghande** [comment]
ok，谢谢你

**Comment by honghande** [comment]
![image](https://user-images.githubusercontent.com/29244715/89101295-38d21700-d431-11ea-8808-60c8303b0366.png)
训练自己的数据报错了，会不会是你的cpp文件设置为类别80呢

**Comment by wang-xinyu** [comment]
refer to the `class num` config in this readme https://github.com/wang-xinyu/tensorrtx/tree/master/yolov3#config
