### ISSUE TITLE
yolov7 int8 3-4 times slower than the fp16

### ISSUE THREAD

**Issue by MyraBaba** [wang-xinyu/tensorrtx#1120]
## Env

- GPU, 2080rtx ti
- OS, uunutu 18.04
- Cuda 11.2
- 8

## About this repo

- latest version 
- which model? yolov7_d6

## Your problem

I create fp16 and int8 engine with your repo help. (coco_calib downloaded to build)

fp16  : inference 17 ms model size: 279 MB
int8.  : inference 57 ms model size : 789 MB

very surprisingly int8 slower and bigger

**Comment by wang-xinyu** [comment]
Might related to GPU internal arch. NVIDIA tensor core supports fp16, but int8 maybe can only use cuda core. 
You can test a simpler model and raise the issue to NV.

**Comment by Lenan22** [comment]
> ## Env
> * GPU, 2080rtx ti
> * OS, uunutu 18.04
> * Cuda 11.2
> * 8
> 
> ## About this repo
> * latest version
> * which model? yolov7_d6
> 
> ## Your problem
> I create fp16 and int8 engine with your repo help. (coco_calib downloaded to build)
> 
> fp16 : inference 17 ms model size: 279 MB int8. : inference 57 ms model size : 789 MB
> 
> very surprisingly int8 slower and bigger

Please use our quantization tool ppq, which currently supports tensorrt, ncnn, openvino, snpe, etc. https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md

**Comment by MyraBaba** [comment]
@Lenan22 did you tested so you are advising ?

**Comment by Lenan22** [comment]
> @Lenan22 did you tested so you are advising ?

Sorry, I misunderstood here, but my tool can solve the problem of  precision drop, as you said, the speed may be related to the GPU internal arch.

**Comment by wang-xinyu** [comment]
@MyraBaba You can enable FP16 and INT8 at the same time.

E.g. add a `config->setFlag(BuilderFlag::kFP16);` after this line

https://github.com/wang-xinyu/tensorrtx/blob/3c0f62e82fba36ff46ffb0f3706f249dce51da21/yolov7/src/model.cpp#L452
