### ISSUE TITLE
jetson nx 生成engine错误

### ISSUE THREAD

**Issue by whaosoft** [wang-xinyu/tensorrtx#1121]
同样的代码 环境 在 x86docker上 没问题
在nx上报错
[E] [TRT] 2: [utils.cpp::checkMemLimit::380] Error Code 2: Internal Error (Assertion upperBound != 0 failed. Unknown embedded device detected. Please update the table with the entry: {{1794, 6, 16}, 12660},)

yolov5/yolov5.cpp:247: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::__cxx11::string&): Assertion `engine != nullptr' failed.

**Comment by whaosoft** [comment]
可能是老外 jetpack的事  待我测试完 回复~~~

**Comment by whaosoft** [comment]
确实硬件的事 直接 onnx==trt都不行....

**Comment by harshraj22** [comment]
@whaosoft  how did you fix it ? Getting the exact same issue.

**Comment by whaosoft** [comment]
@harshraj22  use sdkmanager, update to 4.5.1
