### ISSUE TITLE
yolov7 new version

### ISSUE THREAD

**Issue by timothylimyl** [wang-xinyu/tensorrtx#1122]
hi @lindsayshuo , seems like the yolov7 support for TensorRT conversion only works for [v0.1](https://github.com/WongKinYiu/yolov7/tree/v0.1) which does not have much utility code. 

Any plans to support the current version?

**Comment by wang-xinyu** [comment]
@timothylimyl The only difference is the master branch is using IDetect head, while 0.1 is using Detect head.
If you are interested, welcome a PR for supporting the IDetect.

And we will also be supporting it, but no timeline as of now.
