### ISSUE TITLE
a model with other anchors infers incorrect boxes 

### ISSUE THREAD

**Issue by starry226** [wang-xinyu/tensorrtx#1124]
## Env
- GPU, RTX2080, Xavier NX, etc.
- OS, Ubuntu16.04, Win10, etc.
- Cuda10.2
- TensorRT8

## About this repo
(https://github.com/wang-xinyu/tensorrtx/tree/master/yolov7)

## Your problem
- an yolov7 model trained with anchors (7  15  19  28  21  67, 51  44  39  124  122  100, 63  224  120  253  238  288) different with default.  convert it to tensorrt model with the new anchor definition.
- the tensorrt  model infers out several incorrect boxes for an object. whereas the infer results of the trained yolov7 model are correct.

![_zidane](https://user-images.githubusercontent.com/12859409/197210198-1746f3bf-bf84-4f18-9397-ea1a154f2282.jpg)

**Comment by wang-xinyu** [comment]
@lindsayshuo Any idea about this?

**Comment by QIANXUNZDL123** [comment]
> ## Env
> 
>     * GPU, RTX2080, Xavier NX, etc.
> 
>     * OS, Ubuntu16.04, Win10, etc.
> 
>     * Cuda10.2
> 
>     * TensorRT8
> 
> 
> ## About this repo
> 
> (https://github.com/wang-xinyu/tensorrtx/tree/master/yolov7)
> ## Your problem
> 
>     * an yolov7 model trained with anchors (7  15  19  28  21  67, 51  44  39  124  122  100, 63  224  120  253  238  288) different with default.  convert it to tensorrt model with the new anchor definition.
> 
>     * the tensorrt  model infers out several incorrect boxes for an object. whereas the infer results of the trained yolov7 model are correct.
> 
> 
> ![_zidane](https://user-images.githubusercontent.com/12859409/197210198-1746f3bf-bf84-4f18-9397-ea1a154f2282.jpg)

maybe you should reparameterization for exmple if you train yolov7 with your datasets , you need reparameterization yolov7.pt , you can see https://github.com/WongKinYiu/yolov7

**Comment by QIANXUNZDL123** [comment]
> ## Env
> 
>     * GPU, RTX2080, Xavier NX, etc.
> 
>     * OS, Ubuntu16.04, Win10, etc.
> 
>     * Cuda10.2
> 
>     * TensorRT8
> 
> 
> ## About this repo
> 
> (https://github.com/wang-xinyu/tensorrtx/tree/master/yolov7)
> ## Your problem
> 
>     * an yolov7 model trained with anchors (7  15  19  28  21  67, 51  44  39  124  122  100, 63  224  120  253  238  288) different with default.  convert it to tensorrt model with the new anchor definition.
> 
>     * the tensorrt  model infers out several incorrect boxes for an object. whereas the infer results of the trained yolov7 model are correct.
> 
> 
> ![_zidane](https://user-images.githubusercontent.com/12859409/197210198-1746f3bf-bf84-4f18-9397-ea1a154f2282.jpg)

maybe you should reparameterization for exmple if you train yolov7.pt with your datasets , you need reparameterization yolov7.pt , you can see https://github.com/WongKinYiu/yolov7

**Comment by wang-xinyu** [comment]
@starry226 Please use cfg/deploy/yolov7.yaml to train your own model. We do not support cfg/training/yolov7.yaml yet.
