### ISSUE TITLE
resnet50编译报错

### ISSUE THREAD

**Issue by EmilioKK** [wang-xinyu/tensorrtx#1126]
使用Win10 + VS2022 + CUDA11.0 + TensorRT7.1.3.4
报错为error LNK2001: 无法解析的外部符号 createInferRuntime_INTERNAL
vs里能找到nvinferruntime.h，但是不知道为什么会这样报错
向大神们求助下

**Comment by jsonsocool** [comment]
> 使用Win10 + VS2022 + CUDA11.0 + TensorRT7.1.3.4 报错为error LNK2001: 无法解析的外部符号 createInferRuntime_INTERNAL vs里能找到nvinferruntime.h，但是不知道为什么会这样报错 向大神们求助下

你好，我也碰到一样的问题，你的问题解决了吗？

**Comment by EmilioDD1994** [comment]
> > 使用Win10 + VS2022 + CUDA11.0 + TensorRT7.1.3.4 报错为error LNK2001: 无法解析的外部符号 createInferRuntime_INTERNAL vs里能找到nvinferruntime.h，但是不知道为什么会这样报错 向大神们求助下
> 
> 你好，我也碰到一样的问题，你的问题解决了吗？

把tensorrt的环境在VS里重新配置了一下好了
