### ISSUE TITLE
How to achieve YOLOV7 INT8 quantification?please

### ISSUE THREAD

**Issue by yun9993** [wang-xinyu/tensorrtx#1127]
How to achieve YOLOV7 INT8 quantification?please

**Comment by Lenan22** [comment]
> How to achieve YOLOV7 INT8 quantification?please

Please use our quantization tool ppq, which currently supports tensorrt, ncnn, openvino, snpe, etc.  https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md

**Comment by wang-xinyu** [comment]
Please check https://github.com/wang-xinyu/tensorrtx/tree/master/yolov7#int8-quantization
