### ISSUE TITLE
Error when running an engine with multiple input sources (multithreading)

### ISSUE THREAD

**Issue by TRINHHOANGANH** [wang-xinyu/tensorrtx#1130]
## Description
Hi [wang-xinyu](https://github.com/wang-xinyu),
I use TensorRT engine to detect object but when I run the code using multithreading I get error like this
![image](https://user-images.githubusercontent.com/83366198/197924459-c00d818c-e678-4876-9bb5-24b61a698003.png)

How can i create 1 engine (ex: 1 tensorrt detector engine) that can serve for multiple camera to detect object by using threading without get confused output between these source?

## Env
- GPU : RTX3060
- Ubuntu20.04
- Cuda version 11.6
- TensorRT version 8.4.3.1
- Model: yolov5.engine

**Comment by wang-xinyu** [comment]
You can try to create new cuda stream for each thread.

**Comment by wang-xinyu** [comment]
Maybe you can check this blog https://leimao.github.io/blog/Multi-Thread-Single-Stream-VS-Single-Thread-Multi-Stream-CUDA/

**Comment by TRINHHOANGANH** [comment]
I run the code multithreading by python core. You can see this git: 
https://github.com/TRINHHOANGANH/YoloV7-Tensorrt-MultiThread.git
In this file yolov7_trt_test.py. I use multithreading in line 490. I tried constructor with 8 threads and load one file engine.
You can support python code for multithreading.....

**Comment by wang-xinyu** [comment]
Did you create new cuda stream for each thread? I didn't see that.

**Comment by TRINHHOANGANH** [comment]
I created new cuda stream in line 493 with each thread. 
You can see this git:
https://github.com/TRINHHOANGANH/YoloV7-Tensorrt-MultiThread.git

**Comment by wang-xinyu** [comment]
What's the result of your script? Did it throw error?

**Comment by TRINHHOANGANH** [comment]
Here, the results of my code
![Screenshot from 2022-10-28 16-51-11](https://user-images.githubusercontent.com/83366198/198559467-422618d8-6fc3-4231-9f41-fb1c4b2e8ede.png)

**Comment by wang-xinyu** [comment]
I saw in your script, all the threads are using the same buffers, input buffer, output buffer, host buffer, cuda buffer, etc.
That will cause conflicts.

**Comment by TRINHHOANGANH** [comment]
Thanks for your guide. I fixed it by creating more context in each thread

**Comment by bigbigxing823** [comment]
> Thanks for your guide. I fixed it by creating more context in each thread

hey, could you share your solution, thank you.

**Comment by wang-xinyu** [comment]
@bigbigxing823 Check this PR https://github.com/wang-xinyu/tensorrtx/pull/1279
