### ISSUE TITLE
The converted unet model can not get correct result  on the  jetpack 5.0.2

### ISSUE THREAD

**Issue by feolcn** [wang-xinyu/tensorrtx#1133]
Env
GPU, Jetson Nx L4T 35.1.0
OS, Ubuntu18.04
Cuda version 11.6
TensorRT version 8.4.1.5
OpenCV 4.5.4
CMake 3.16.3

## About this repo
- which branch/tag/commit are you using? yolov5-6.2
- which model?  unet

## Your problem
- what is your command? ./unet -d ../sample
- what's your output? incorrect 
- what output do you expect? correct result as pt model
The output of this model is incorrect， But the pt model is correct.

when i change the env to this：
GPU, Jetson Nx L4T 32.1.0
OS, Ubuntu18.04
Cuda version 11.6
TensorRT version 8.2
OpenCV 4.5.4
CMake 3.16.3
the result is correct。

**Comment by wang-xinyu** [comment]
No idea, can you try other model? Like yolov5

**Comment by dut-lly** [comment]
I have the same problem with yolov7, using pre-trained weights is good, but the detection results of my own trained model are not good

**Comment by wang-xinyu** [comment]
@dut-lly Can you compare the pre-trained model with you own model? Check the model structure layer by layer.

**Comment by wang-xinyu** [comment]
@dut-lly For YOLOv7, we have found that there is a difference between cfg/training/yolov7.yaml, and cfg/deploy/yolov7.yaml.

For YOLOv7 v0.1, there is no cfg/training/yolov7.yaml,  hence we only support cfg/deploy/yolov7.yaml right now. So you need train your model using cfg/deploy/yolov7.yaml.
