### ISSUE TITLE
yolov5s-cls.pt convert yolov5s-cls.wts

### ISSUE THREAD

**Issue by wafaer** [wang-xinyu/tensorrtx#1134]
Hello, @wang-xinyu I am using your gen_wts.py to convert yolov5s-cls.pt, and I get this error: 
Traceback (most recent call last):
   File "gen_wts.py", line 40, in <module>
     anchor_grid = model.model[-1].anchors * \
   File "/home/hermione/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
     raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Classify' object has no attribute 'anchors'. 
May I ask what is the reason?

**Comment by wang-xinyu** [comment]
Pls check this argument https://github.com/wang-xinyu/tensorrtx/blob/c1a803b5255539f65e48bc53e937e69ddc4498f9/yolov5/gen_wts.py#L16

**Comment by tohasi** [comment]
Hello, @wang-xinyu I have the same error when using "python3.6 gen_wts.py -w yolov5n-cls.pt -o yolov5n.wts", and I tried "python3.6 gen_wts.py -w yolov5n-cls.pt -t cls", but it returns nothing,,,
what should I do next?

**Comment by kidach1** [comment]
@tohasi 
You could try `python3.6 gen_wts.py -w yolov5n-cls.pt -o yolov5n.wts -t cls`.
`-t cls` has worked for me.

**Comment by tohasi** [comment]
> @tohasi You could try `python3.6 gen_wts.py -w yolov5n-cls.pt -o yolov5n.wts -t cls`. `-t cls` option has worked for me.

Thanks, that was really helpful
