### ISSUE TITLE
YoloV5 explicit_batch export problem

### ISSUE THREAD

**Issue by ostrowskimarcin** [wang-xinyu/tensorrtx#1135]
## Env

- GPU: RTX3060
- OS: Ubuntu20.04
- CUDA: 11.7
- TensorRT: 8.4.3.1-1

## About this repo

- which branch/tag/commit are you using? https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5
- yolov5m6

## Your problem

Hi, after configuring yolov5.cpp, yololayer.h I successfully compiled yolov5 binary file but after executing last command 
sudo ./yolov5 -s yolov5m6.wts yolov5m6.engine m6 I got output:
```
[W] [TRT] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
Loading weights: yolov5m6.wts
```
I want to export multi batch model, but the error occures event with batch size =1.
I'm using newest .pt model and tensorrtx commit.
I wouldn't like to change my libs versions (trt and cuda).

Does anybody know where can I find solution?

Best regards,
M

**Comment by wang-xinyu** [comment]
This is a warning, not error.

**Comment by ostrowskimarcin** [comment]
Right, I forgot to add that the warning was followed by cuda 222 error. Updating cuda version to 11.8 helped.
