### ISSUE TITLE
What causes CPU to degrade when I load the weight with torch.hub.load()

### ISSUE THREAD

**Issue by TRINHHOANGANH** [wang-xinyu/tensorrtx#1136]
## My problem
 Hi [wang-xinyu](https://github.com/wang-xinyu),
I use TensorRT engine to detect object but when I load weight by **_torch.hub.load()_** then CPU: 16,2%.
On the other hand, I load by **_runtime.deserialize_cuda_engine(f.read())_** then CPU: 78.1%. 
- torch.hub.load()
![Screenshot from 2022-11-04 15-43-55](https://user-images.githubusercontent.com/83366198/199931602-25dbd47d-26c3-44f1-aeef-1fe65100d775.png)

- runtime.deserialize_cuda_engine(f.read()) 
 
![Screenshot from 2022-11-04 15-51-50](https://user-images.githubusercontent.com/83366198/199932821-5232721a-f356-4aba-aef8-4b15093f3fd6.png)

Can you point out what the cause is?

**Comment by wang-xinyu** [comment]
No idea
