### ISSUE TITLE
build yolov5l.engine error: "arguement not right! ./yolov5 -v[.engine] // run inference with camera"

### ISSUE THREAD

**Issue by cxwang** [wang-xinyu/tensorrtx#1137]
## Env

- Jetson nano
- Ubuntu 18.04
- Cuda 10.2
- TensorRT 8.0.1.6

## About this repo

- which branch/tag/commit are you using?    master
- which model? yolov5, retinaface?    yolov5

## Your problem

- what is your command?  `sudo ./yolov5 -s yolov5l.wts yolov5l.engine l`
- what's your output? error: "arguement not right! ./yolov5 -v[.engine] // run inference with camera"
- what output do you expect? build yolov5l.engine success.

**Comment by wang-xinyu** [comment]
Are you using this repo?  We don'e have argument -v.
