### ISSUE TITLE
tensorrt no nn.adaptiveavgpool2d

### ISSUE THREAD

**Issue by Anoue** [wang-xinyu/tensorrtx#1138]
nn. Adaptive avgpool2d (1) ; there is no adaptive pooling in tensorrt. When I pool with a kernel (320,320) and STRIDE = 320 common pool with input (1,32,320,320) and output (1,32,1,1) , it will show that tensorrt does not support such a large pool core.

**Comment by wang-xinyu** [comment]
You can try ReduceLayer.

**Comment by Anoue** [comment]
I still don't understand. If I want to Reduce (1 * 32 * 320 * 320) to (1 * 32 * 1 * 1) , how do I Reduce. Can you give me a heads-up?

**Comment by wang-xinyu** [comment]
Can you check the TensorRT API doc?
