### ISSUE TITLE
yolov5 testing fail by `scale_1` 

### ISSUE THREAD

**Issue by peijason** [wang-xinyu/tensorrtx#114]
ENV:
- **Xavier NX**
- **Ubuntu 18.04.4**
- **Python**
``` console
$ python --version
Python 3.6.9
$ pip show torch
Name: torch
Version: 1.6.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: ~/.local/lib/python3.6/site-packages
Requires: numpy, future
Required-by: torchvision
$ pip show torchvision
Name: torchvision
Version: 0.8.0a0+6db1569
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: ~/.local/lib/python3.6/site-packages/torchvision-0.8.0a0+6db1569-py3.6-linux-aarch64.egg
Requires: numpy, torch, pillow
Required-by: 
```

The **ERROR** message:

```console
[07/31/2020-18:30:22] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5s: ....../tensorrtx/yolov5/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted
```

Any suggestions?

**Comment by wang-xinyu** [comment]
Currently the yolov5s in this repo is corresponding to `June 22, 2020: PANet updates: new heads, reduced parameters, improved speed and mAP 364fcfd.` of https://github.com/ultralytics/yolov5.

Please use the yolov5s model in my google drive, refer to the readme https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5.

**Comment by bulingda** [comment]
> Currently the yolov5s in this repo is corresponding to `June 22, 2020: PANet updates: new heads, reduced parameters, improved speed and mAP 364fcfd.` of https://github.com/ultralytics/yolov5.
> 
> Please use the yolov5s model in my google drive, refer to the readme https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5.

Can you give me some practical advice? I've trained my own model now you want me to use the official one? What else do I train for?

**Comment by wang-xinyu** [comment]
@bulingda  你是什么问题

**Comment by bulingda** [comment]
我使用了yolov5 1.0到2.0之间某个版本的代码（7月14日下载的），训练得到了模型，其中只改变了类别，图像大小，bs，没有改变模型本身，我现在想用tensorrtx（https://github.com/BaofengZan/yolov5_2.0-TensorRt/tree/master/yolov5l）转换我的模型。它总在报错说我修改了模型。我猜测是跟pytorch版本有关系，我单独使用模型时，pytorch版本越高，警告（提示model有改变）越多。

**Comment by wang-xinyu** [comment]
如果是1.0和2.0之间的，那用2.0肯定不行。  跑官方模型是证明我们代码没问题。  然后再自己去对自己的模型和官方模型的差别，做出相应修改。

**Comment by bulingda** [comment]
> 如果是1.0和2.0之间的，那用2.0肯定不行。 跑官方模型是证明我们代码没问题。 然后再自己去对自己的模型和官方模型的差别，做出相应修改。

那我应该使用1.0的吗？我使用官方最新的yolov5l.pt放到里面测试，没有问题。

**Comment by wang-xinyu** [comment]
把自己的模型print出来，和官方release的1.0和2.0都对比看看，是哪里不一样

**Comment by bulingda** [comment]
> > 如果是1.0和2.0之间的，那用2.0肯定不行。 跑官方模型是证明我们代码没问题。 然后再自己去对自己的模型和官方模型的差别，做出相应修改。
> 
> 那我应该使用1.0的吗？我使用官方最新的yolov5l.pt放到里面测试，没有问题。

我对比了一下，没看到有哪里不一样的，会不会是pytorch版本引起的问题呢？
我运行的时候总会出现这两个警告。
D:\anaconda\install\envs\general\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'models.common.Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
D:\anaconda\install\envs\general\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'models.common.Concat' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)

**Comment by wang-xinyu** [comment]
用pytorch代码跑自己的模型结果正常吗？结果正常就不是pytorch版本问题

**Comment by bulingda** [comment]
> 用pytorch代码跑自己的模型结果正常吗？结果正常就不是pytorch版本问题

结果是正确的

**Comment by wang-xinyu** [comment]
那就和pytorch版本没关系，用这个项目的代码再试试，模型肯定还有不一样的地方，再仔细对对
