### ISSUE TITLE
core dump when change INPUT_H to 328 in yolov7

### ISSUE THREAD

**Issue by fjremnav** [wang-xinyu/tensorrtx#1140]
I like to keep aspect ratio to test images which INPUT_H is changed to 328 while INPUT_W is still 640 in  yololayer.h.
It runs OK from wts to trt engine. But when I run inference, it generates a core dump. Any idea why this happened.

CUDA error 700 at /home/user/Projects/git/yolov7_10_26_2022/tensorrtx/yolov7/yolov7.cpp:2224yolov7: /home/user/Projects/git/yolov7_10_26_2022/tensorrtx/yolov7/yolov7.cpp:2224: void doInference(nvinfer1::IExecutionContext&, CUstream_st*&, void**, float*, int): Assertion `0' failed.
Aborted (core dumped)

Thanks,

**Comment by wang-xinyu** [comment]
YOLO's input W&H must by divisible by 32.

**Comment by fjremnav** [comment]
I changed  Input_H=384, but it has core dumped too.

**Comment by wang-xinyu** [comment]
Does the default 640x640 have core dump?

**Comment by fjremnav** [comment]
No, 640x640 runs OK

Thanks,
