### ISSUE TITLE
[pluginV2Runner.cpp::load::292] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)

### ISSUE THREAD

**Issue by HarrySm** [wang-xinyu/tensorrtx#1141]
## Env

- Jetson AGX Orin.
- Ubuntu 20.4 LTS
- Cuda 11.4
- TensorRT 8.4

## About this repo

- branch/tag/commit : v6.2
- yolov5 v6.2

## Your problem
 Hello, I have successfully build a INT8 with calibration yolov5s engine using your repo and yolov5 repo.

Now I would like to use the val.py script from yolov5 repo and put as input the INT8 with calibration yolov5s engine that I have created using your repo.

Now the problem is that it needs the plugin "libmyplugins.so" that you can find it in the ./yolov5/build folder. 

So my question is do you have any idea how to add the plugin "libmyplugins.so" to the val.py yolov5 script [here](https://github.com/ultralytics/yolov5/blob/master/val.py) So I can run successfully the val.py

NOTE: there is [here](https://github.com/ultralytics/yolov5/issues/7603) as well a ticket on yolov5 issue repo as well.

Thank you in advance.

Best regard,
Harry

**Comment by sbmalik** [comment]
@HarrySm have you tried the following code on top of `val.py`

```
import ctypes
ctypes.cdll.LoadLibrary("libmyplugins.so")
```

**Comment by HarrySm** [comment]
Hello @sbmalik ,

Thank you for your reply yes I figured out thank you a lot :)

**Comment by HarrySm** [comment]
@sbmalik 
I am wondering if you have any idea how to solve the next issue please.

So after adding the plugin I am now facing the below issue, I think it has to do when building the engine it was build with a dynamic shapes instead of static (NxHxWxC)
please have a look below:

`bash
File "val.py", line 398, in <module>
    main(opt)
  File "val.py", line 369, in main
    run(**vars(opt))
  File "/venv_yolov5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 140, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/yolov5_6.1/yolov5/models/common.py", line 402, in __init__
    batch_size = bindings['images'].shape[0]  # if dynamic, this is instead max batch size
KeyError: 'images'
`

**Comment by sbmalik** [comment]
@HarrySm can you please check the [infer function from yolov5_trt.py](https://github.com/wang-xinyu/tensorrtx/blob/9410508c84495027f96a2383c778c0a16432c6ab/yolov5/yolov5_trt.py#L124) here, I hope it will help you understand the de-serialization process.

**Comment by HarrySm** [comment]
@sbmalik Yes I will have a look and maybe change the one was used to this. I will keep you updated as well :)

**Comment by HarrySm** [comment]
I figured something interresting,  in `bindings` actually it has two elements:
- `bindings['prob']`
- `bindings['data']`

However, in the common.py script they are using:
- `bindings['images']`
- `bindings['output']`

I am not sure how to solve it. I tried to modifying so `images --> data` and `output --> prob` it has errors.
and the other way `output--> data` and `images--> prob` I will lost the connection and the whole Jetson freezes.

What do you think? 

All what I need is a script that can give me the mAP when running yolov5 INT8 with calibration on COCO validating dataset. So if you have any other suggestion to get the mAP it will be very helpfull to me :)

**Comment by sbmalik** [comment]
I am not sure how to solve it. I tried to modifying so images --> data and output --> prob it has errors.
What errors ?

**Comment by sbmalik** [comment]
@HarrySm kindly chek the [post_process function](https://github.com/wang-xinyu/tensorrtx/blob/9410508c84495027f96a2383c778c0a16432c6ab/yolov5/yolov5_trt.py#L277) because TensorRT gives a flatten array as output, which we have to reshape accordingly

**Comment by HarrySm** [comment]
@sbmalik 
Thank you, I will check it and keep you updated :)

**Comment by HarrySm** [comment]
Hello @sbmalik ,

I cannot find a solution since it is already in shape, the function return 3 arrays.

NOTE: I am using the yolov5 val.py script to get the mAP I am not sure that I can do this using the `yolov5_trt.py`. I only want to get the mAP to se the accuracy, if you have any idea.

Thank you :)

**Comment by HarrySm** [comment]
Hello again @sbmalik ,

I have found another interresting thing here.

The standard yolov5s has (1,25200,85) which is (batch_size, 25200, 85-5 classes) please have a look [here](https://github.com/ultralytics/yolov5/blob/f33718f36f756301b91da6207f1d02f30b3916e1/utils/general.py#L851-L877) 

the `prediction.shape` for standard yolov5s is `(1,25200,85)` which is bs, nc in the link above. However, using the yolov5s from **tensorrtx** I am getting from `prediction.shape` this (6001, 1, 1) and this is why I cannot running the val.py script. 

Now my question is how to get the standard shape, is it by using the [post_process function](https://github.com/wang-xinyu/tensorrtx/blob/9410508c84495027f96a2383c778c0a16432c6ab/yolov5/yolov5_trt.py#L277) as you suggested to me above? if yes could you please tell me how?

Thank you
Harry

**Comment by HarrySm** [comment]
Hello @sbmalik ,

Maybe I should remove some lines [here ](https://github.com/wang-xinyu/tensorrtx/blob/9410508c84495027f96a2383c778c0a16432c6ab/yolov5/yolov5.cpp#L40-L93)to get the standard output shapes?

What do you think?

Thank you in advance
Harry

**Comment by sbmalik** [comment]
@HarrySm sorry for late reply, I am a bit busy in work. I think you have to debug what really does `25200` means in the output and how the TRTX version of yolov5 decoding the output. One point to be noted it's assuming the maximum of `1000 outputs` for each input, where output includes all the classes and bboxes I think so
