### ISSUE TITLE
Arcface demo score only 0.63

### ISSUE THREAD

**Issue by danwanban** [wang-xinyu/tensorrtx#1142]
## Env
runtime Xavier  AGX, JetPack 5.0.2, TRT8.4.1,  Cuda11.4
weight conversion done on amazon (p3)

## About this repo

Latest repo, arcface 

## Your problem

Running the instruction "as-is". all looking good (few compiler warning, but exe is generated). 
BUT
I get different number - was expecting 0.69 (seen on the webpage):    
```
./arcface-r100 -d 
93ms
82ms
similarity score: 0.632514
```
What am I doing wrong ?

**Comment by wang-xinyu** [comment]
Can you try more images? Like a test set. One image is meaningless.

**Comment by danwanban** [comment]
works fine, thanks. 
Another q - is batch>1 supported ? I saw the remark in the code, but also the code contains batch size section - which one is correct ? 

Thanks again for this great project , really helpful !

**Comment by danwanban** [comment]
Works
