### ISSUE TITLE
yolov7 v7 speed between int8 and fp16

### ISSUE THREAD

**Issue by fjremnav** [wang-xinyu/tensorrtx#1143]
I have converted v7 model with int8 and fp16, then run inference. 
The speed delta between these two is very little, fp16 is 4ms and int8 is 3.8ms for one image.
Is this normal? I will expect 2x speed of int8 over fp16

Thanks,

**Comment by wang-xinyu** [comment]
You can try enable fp16 + int8 when you use int8.

**Comment by fjremnav** [comment]
How to enable INT8 and FP16? 
Will INT8+FP16 improve speed?

Thanks,

**Comment by wang-xinyu** [comment]
You can try this
```
    config->setFlag(BuilderFlag::kFP16);
    config->setFlag(BuilderFlag::kINT8);
```

**Comment by fjremnav** [comment]
I will try your suggestion.
One more question, INT8 and FP16 is only used during serialization. For inferencing, can I use a regular yolov7 binary, ie, it is built with INT8 and FP16 flags enabled?

Thanks,
FC
