### ISSUE TITLE
在yolop中的yolop.hpp中doInference()函数有什么作用呢？

### ISSUE THREAD

**Issue by zilong-ding** [wang-xinyu/tensorrtx#1144]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## Your problem

我在看到yolop.hpp时发现有doInference() and doInferenceCpu()，然后替换之后发现doInference()并没有起作用，原因是他并没有输入，我不理解这一个函数该如何使用呢？还是这个本身是一个多余无用的代码？

**Comment by ausk** [comment]
区别在于这句：`CUDA_CHECK(cudaMemcpyAsync(buffers[0], input, batchSize * 3 * INPUT_H * INPUT_W * sizeof(float), cudaMemcpyHostToDevice, stream));`
从 cpu 上输入，input 是在 host 上的，需要拷贝。如果使用 gpu 版的 Mat 就不需要这句，也就是 doInference 函数。

**Comment by zilong-ding** [comment]
如果是GPU版的mat，是直接可以当作buffers[0]来用吗？

**Comment by ausk** [comment]
gpu 版本的 mat 前处理到 buffer[0] 里，就不用再 cudaMemcpyAsync 拷贝了。参考 yolop 官方 : https://github.com/hustvl/YOLOP/blob/main/toolkits/deploy/main.cpp#L115

**Comment by zilong-ding** [comment]
好的，谢谢
