### ISSUE TITLE
retinaface_trt.py killed

### ISSUE THREAD

**Issue by dmayboroda** [wang-xinyu/tensorrtx#1145]
I did all steps described in readme and everything works ok, except the last step
`python3 retinaface_trt.py`

Got this output:
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +197, GPU +0, now: CPU 271, GPU 1891 (MiB)
[TensorRT] INFO: Loaded engine size: 181 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 453 MiB, GPU 2255 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +159, GPU +281, now: CPU 612, GPU 2716 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +240, GPU +412, now: CPU 852, GPU 3128 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 852, GPU 3128 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine end: CPU 852 MiB, GPU 3128 MiB
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation begin: CPU 671 MiB, GPU 2947 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 671, GPU 2947 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 671, GPU 2947 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation end: CPU 673 MiB, GPU 3210 MiB
Killed

**Comment by wang-xinyu** [comment]
What's your GPU?  Is it Nano?

**Comment by dmayboroda** [comment]
Yes, it's Nano

**Comment by wang-xinyu** [comment]
Nano doesn't have enough memory to run python-TRT,  you can try the C++.
