### ISSUE TITLE
pycuda._driver. errer

### ISSUE THREAD

**Issue by 98765mm** [wang-xinyu/tensorrtx#1149]
## Env

- GPU, e.g. V100, RTX2070
- OS, e.g. popos22.04
- Cuda 11.5
- TensorRT 8.4

## About this repo

- which branch/tag/commit are you using?
-  yolov5,-6.0

## Your problem

when i use yolov5_trt.py of  tensorrt8 in “sanic“（A web Framework）, it will report an error：

pycuda._driver.LogicError: cuCtxPopCurrent failed: initialization error

**Comment by wang-xinyu** [comment]
What about run the yolov5_trt.py directly in python?

**Comment by 98765mm** [comment]
> 



> What about run the yolov5_trt.py directly in python?


Using it directly is fine, but when used with the sanic framework, pycuda error occurs


>

**Comment by wang-xinyu** [comment]
I don't have any idea about the sanic.
