### ISSUE TITLE
retinaface生成engine出错

### ISSUE THREAD

**Issue by Glory-Peng** [wang-xinyu/tensorrtx#1151]
执行 ./retina_r50 -s 时出现
 
retina_r50: /home/nvidia/paper/tensorrtx/retinaface/common.hpp:141: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file."' failed.

**Comment by wang-xinyu** [comment]
没找到.wts文件，.wts文件需要放在../路径下

**Comment by Glory-Peng** [comment]
谢谢大佬，已解决
