### ISSUE TITLE
yolov5 转化后的tensorrt文件和原始文件pt模型推理输出形状不同，做了那些优化

### ISSUE THREAD

**Issue by fcqfcq** [wang-xinyu/tensorrtx#1156]
## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- yolov5
- what's your output?
-   
- what output do you expect?
-

**Comment by wang-xinyu** [comment]
You can check this https://github.com/wang-xinyu/tensorrtx/blob/7c66ee03d53026a39992de40b64aed7258cfc684/yolov5/yololayer.cu#L236

**Comment by fcqfcq** [comment]
static constexpr int MAX_OUTPUT_BBOX_COUNT = 1000;

https://github.com/wang-xinyu/tensorrtx/blob/7c66ee03d53026a39992de40b64aed7258cfc684/yolov5/yololayer.cu#L249
和设置MAX_OUTPUT_BBOX_COUNT 这个有关

**Comment by fcqfcq** [comment]
这个是做了什么操作

**Comment by wang-xinyu** [comment]
CUDA kernel, 实现yolo后处理的decoder部分，看代码吧
