### ISSUE TITLE
retinaface_trt.py运行后显示killed

### ISSUE THREAD

**Issue by Glory-Peng** [wang-xinyu/tensorrtx#1157]
我在nano上运行retinaface_trt.py后显示killed，在readme中只有python的实现流程，有没有c++的流程呢？

**Comment by wang-xinyu** [comment]
Step 2 is for c++, step 4 is python:
https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface#run

**Comment by Glory-Peng** [comment]
如果我要从RTSP视频流里获取图片，那应该改哪个文件呢？是不是retinaface_r50.cpp?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-xinyu/tensorrtx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-xinyu/tensorrtx] retinaface_trt.py运行后显示killed (Issue #1157)





 
Step 2 is for c++, step 4 is python:
 https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface#run

**Comment by Glory-Peng** [comment]
我在nx上运行retinaface_trt.py 也会killed，还是性能不够吗？

**Comment by wang-xinyu** [comment]
你可以尝试改一下py，把里面的torch相关的函数替换掉，估计torch需要内存太大
