### ISSUE TITLE
Real-Esrgan does not work with dimensions other than the default size

### ISSUE THREAD

**Issue by HosseinMoazzam** [wang-xinyu/tensorrtx#1158]
## Env

- GPU: GeForce GTX 1660
- OS: Ubuntu 20.04
- Cuda version: 11.4
- TensorRT version: 8

## About this repo
- which model? real-esrgan

## Your problem
Real-Esrgan does not work with dimensions other than the default size of 448 * 640 (width * height), despite of changing corresponding lines in real-esrgan.cpp:

static const int INPUT_H = 640;
static const int INPUT_W = 448;

This is the result of default size (448*640):
https://drive.google.com/file/d/1ugByr7dNU760DD7pjdx_90Z9y0SzJcub/view?usp=sharing

and this is the result of image with size of 455*680 and changing corresponding lines in real-esrgan.cpp:
https://drive.google.com/file/d/1wE7Y3stM6dxs4Zlj2fuNBdDnLB45ixyH/view?usp=sharing

**Comment by wang-xinyu** [comment]
@yester31 Can you please help here?

**Comment by HosseinMoazzam** [comment]
The problem is solved. In addition to change the corresponding line in real-esrgan.cpp, must regenerate engine file.
