### ISSUE TITLE
retinace项目，如果想用c++进行实时推理，应该修改哪个文件呢？

### ISSUE THREAD

**Issue by Glory-Peng** [wang-xinyu/tensorrtx#1159]
你好，我在部署retinaface的时候，Python太慢了，想用c++进行部署推理，获取rtsp视频流中的一帧图片，应该修改哪个程序呢？是retinaface_r50.cpp吗？

**Comment by wang-xinyu** [comment]
对，目前只支持图片，视频需要自己解码，然后逐帧送进去推理
