### ISSUE TITLE
YOLO4

### ISSUE THREAD

**Issue by z13228604287** [wang-xinyu/tensorrtx#1164]
能支持trt8吗？

**Comment by wang-xinyu** [comment]
可以参考yolov5改一下，然后提个PR吗？
1. 替换logging.h
2. 把macros.h复制过来
3. 对照改一下yololayer.h

**Comment by z13228604287** [comment]
好的我试试

**Comment by z13228604287** [comment]
请问是否  能将 IN8 搬运过去  能直接量化吗？

**Comment by z13228604287** [comment]
在我查看 如何运行 的时候
对
使用 yolov4.cfg 和 yolov4.weights 从 pytorch 生成 yolov4.wts
使用如下命令   cfg文件 不需要的，啊！  还是我理解错误
python gen_wts.py yolov4.weights yolov4.wts

**Comment by wang-xinyu** [comment]
gen_wts只读取权重，不读取模型结构，所有不需要cfg文件

**Comment by wang-xinyu** [comment]
> 请问是否 能将 IN8 搬运过去 能直接量化吗？

需要改，可以参考yolov5代码中#ifdef USE_INT8中的部分

**Comment by z13228604287** [comment]
我尝试  将YOLO5 IN8 部分迁移到YOLO4   逐步排查  还是无法正常  迁移期望后期能维护下谢谢！

**Comment by z13228604287** [comment]
我尝试  将YOLO5 IN8 部分迁移到YOLO4   逐步排查  还是无法正常  迁移期望后期能维护下谢谢！

**Comment by z13228604287** [comment]
@wang-xinyu   我在进行  模型转型时 
(yolov3) C:\Users\hanyong\Desktop\YOLOV3>python gen_wts.py yolov4.weights
Traceback (most recent call last):
  File "gen_wts.py", line 6, in <module>
    model = Darknet('yolov4.cfg', (608, 608))
  File "C:\Users\hanyong\Desktop\YOLOV3\models.py", line 231, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "C:\Users\hanyong\Desktop\YOLOV3\utils\parse_config.py", line 50, in parse_model_cfg
    assert not any(u), "Unsupported fields %s in %s. See https://github.com/ultralytics/yolov3/issues/631" % (u, path)
AssertionError: Unsupported fields ['max_delta'] in yolov4.cfg. See https://github.com/ultralytics/yolov3/issues/631

yolov4.weights  yolov4-tiny.weights  我都试过  不知道   到底支持什么模型

**Comment by z13228604287** [comment]
在我转换 模型时  发现  https://github.com/ultralytics/yolov3/tree/archive  项目 已不在支持  新的YOLO4 cfg  

白忙活这么久

**Comment by wang-xinyu** [comment]
用v5或v7吧
