### ISSUE TITLE
Yolov5转int8格式时候报错

### ISSUE THREAD

**Issue by yezechen** [wang-xinyu/tensorrtx#1165]
## Env

- Ubuntu18.04, Win10, etc.
- Cuda 10.1
- TensorRT 6.0

## About this repo
- Yolov5 5.0

## Your problem

- yolov5转换成int8格式时候报错
![image](https://user-images.githubusercontent.com/53908080/206166380-9d5549e5-66fa-4205-9f07-e6c2b4899cde.png)

**Comment by wang-xinyu** [comment]
int8需要calibration过程，再看一下readme
