### ISSUE TITLE
yolov5engine模型在跨设备运行时报错

### ISSUE THREAD

**Issue by Soikie** [wang-xinyu/tensorrtx#1170]
我成功将yolov5输出为engine模型，然后将python_trt.py文件打包，打包后的python_trt.exe在另一台无配置1050Ti电脑上成功运行，我打包所使用的电脑也是1050Ti，python=3.9，cuda=11.3，然后在另一台无配置mx250的电脑成功上运行，但在一台无配置3060的电脑上运行失败，提示以下错误

[runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::37] Error Code 3: API Usage Error (Parameter check failed at: runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::37, condition: (blob) != nullptr)

请问该如何解决？是因为10系列显卡生成的engine模型只能在10系列的电脑上加载吗？如果我想让yolov5模型在任意一台无配置具有n卡的电脑上，或者说大部分电脑上运行，我该做哪些工作呢？

**Comment by wang-xinyu** [comment]
不同显卡要重新生成engine模型，即使能跑也不是最优的

**Comment by Soikie** [comment]
> 不同显卡要重新生成engine模型，即使能跑也不是最优的

我并不追求最优，只是追求能够运行engine模型，这个是无法实现吗？

**Comment by Soikie** [comment]
我不太了解engine模型在大部分显卡上运行是否可能，如果这不可能的话，我会尝试别的路径使得yolov5在不同的显卡上运行，无论如何，感谢你的回答

**Comment by wang-xinyu** [comment]
Check this https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#compatibility-serialized-engines

About compute capability, you can check https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/check_fp16_int8_support.md#1-check-your-gpu-compute-capability

**Comment by Soikie** [comment]
好的，感谢你的回答
