### ISSUE TITLE
hrnet cls make failed

### ISSUE THREAD

**Issue by jo-dean** [wang-xinyu/tensorrtx#1173]
## Env
RTX 3060
Ubuntu20.04
Cuda 11.6
TensorRT 8.4

## About this repo

hrnet-image-classification

## Your problem
when `make` the file, error happend that **`error: ‘nvinfer1::DimensionType’ has not been declared'**
                            {nvinfer1::DimensionType::kCHANNEL,`
`tensorrtx/hrnet/hrnet-image-classification/common.hpp:266:39: error: ‘nvinfer1::DimensionType’ has not been declared
                            {nvinfer1::DimensionType::kCHANNEL,
                                       ^~~~~~~~~~~~~
tensorrtx/hrnet/hrnet-image-classification/common.hpp:267:39: error: ‘nvinfer1::DimensionType’ has not been declared
                             nvinfer1::DimensionType::kSPATIAL,
                                       ^~~~~~~~~~~~~
tensorrtx/hrnet/hrnet-image-classification/common.hpp:268:39: error: ‘nvinfer1::DimensionType’ has not been declared
                             nvinfer1::DimensionType::kSPATIAL} };
                                       ^~~~~~~~~~~~~
tensorrtx/hrnet/hrnet-image-classification/common.hpp:268:64: error: too many initializers for ‘nvinfer1::Dims’ {aka ‘nvinfer1::Dims32’}
                             nvinfer1::DimensionType::kSPATIAL} };
                                                                ^
tensorrtx/hrnet/hrnet-image-classification/common.hpp:300:40: error: ‘nvinfer1::DimensionType’ has not been declared
                             {nvinfer1::DimensionType::kCHANNEL,
                                        ^~~~~~~~~~~~~
tensorrtx/hrnet/hrnet-image-classification/common.hpp:301:40: error: ‘nvinfer1::DimensionType’ has not been declared
                              nvinfer1::DimensionType::kSPATIAL,
                                        ^~~~~~~~~~~~~
tensorrtx/hrnet/hrnet-image-classification/common.hpp:302:40: error: ‘nvinfer1::DimensionType’ has not been declared
                              nvinfer1::DimensionType::kSPATIAL} };
                                        ^~~~~~~~~~~~~
tensorrtx/hrnet/hrnet-image-classification/common.hpp:302:65: error: too many initializers for ‘nvinfer1::Dims’ {aka ‘nvinfer1::Dims32’}
                              nvinfer1::DimensionType::kSPATIAL} };
                                                                 ^
`

**Comment by jo-dean** [comment]
TRT7.x is ok for make.
but when run the cmd `sudo ./hrnet -s`
the **error** is `./hrnet: error while loading shared libraries: libnvrtc.so.11.1: cannot open shared object file: No such file or directory`
run the `ldd hrnet`
it shows
![image](https://user-images.githubusercontent.com/38728358/207766802-1a4088c1-1a05-4fb3-968f-8af5acf929d0.png)

**Comment by jo-dean** [comment]
not add `sudo` is fine.

**Comment by jo-dean** [comment]
TRT7.x is fine.
Thanks.

**Comment by wang-xinyu** [comment]
@jo-dean To migrate to TRT8.x, you can refer to the code of tensorrtx/yolov5
1. replace logging.h
2. copy macros.h

If you are interested to try and make it work, you can raise a PR.
