### ISSUE TITLE
yolov5 cpp code has more than 10 streams, why?

### ISSUE THREAD

**Issue by solaim** [wang-xinyu/tensorrtx#1178]
## Env

- GPU, V100
- OS, Ubuntu 20.04.4 LTS
- Cuda version, 11.7
- TensorRT version, 8.2.5-1+cuda11.4

## About this repo

- using master branch
- model: yolov5s.pt -> yolov5s.wts -> yolov5s.engine

## Your problem

- command: nvprof -o tensorrtx.nvvp ./yolov5 -d yolov5s.engine ../samples
- output: 
```
inference time: 2ms
inference time: 2ms
==571== Generated result file: /app/tensorrtx/yolov5/build/tensorrtx.nvvp
```
![image](https://user-images.githubusercontent.com/29426664/208338201-7b6c2edc-8a59-435a-99de-811f3e18306f.png)

- expect:
```
as graph showed, there is more than 10 streams, why? 
in code:
    // Create stream
    cudaStream_t stream;
    CUDA_CHECK(cudaStreamCreate(&stream));

just call once!

in my opinion, there shoud be 1 or 2((because of default stream)) stream.
```

**Comment by solaim** [comment]
[tensorrtx.nvvp.zip](https://github.com/wang-xinyu/tensorrtx/files/10255571/tensorrtx.nvvp.zip)

this is nvvp profile

**Comment by wang-xinyu** [comment]
This might related to TensorRT internals, we only launch one TensorRT engine and one stream. But TensorRT maybe launchs more streams internally.
