### ISSUE TITLE
生成yolov3.wts错误

### ISSUE THREAD

**Issue by HappyLearningML** [wang-xinyu/tensorrtx#118]
python gen_wts.py yolov3.weights ：
File "gen_wts.py", line 3, in <module>
    from models import *
ModuleNotFoundError: No module named 'models'

  File "gen_wts.py", line 4, in <module>
    from utils.utils import *
ModuleNotFoundError: No module named 'utils'

请问：models和utitls在哪？

**Comment by wang-xinyu** [comment]
@HappyLearningML 再看下readme的步骤，gen_wts.py是运行在https://github.com/ultralytics/yolov3目录下

**Comment by HappyLearningML** [comment]
抱歉抱歉，搞定了，谢谢了。
