### ISSUE TITLE
yolov5 make compilation error

### ISSUE THREAD

**Issue by eladpar** [wang-xinyu/tensorrtx#1180]
## Env

- GPU, NVIDIA GeForce RTX 3050 Ti
- OS, ubuntu 20.04
- CUDA Version: 11.7
- TensorRT 8.5.2.2-1+cuda11.8

## About this repo

- which branch/tag/commit are you using? master
- which model? yolov5, retinaface? yolov5s.pt

## Your problem
im building using this https://wiki.seeedstudio.com/YOLOv5-Object-Detection-Jetson/#inference-on-jetson-device toturial
 when i hit the make command i get this ouput :
![Screenshot from 2022-12-20 16-19-14](https://user-images.githubusercontent.com/53909719/208688252-6b5dd51e-b39f-464b-9780-9b07b7ccc1a1.png)
```bash
Scanning dependencies of target myplugins
[  7%] Building CUDA object CMakeFiles/myplugins.dir/plugin/yololayer.cu.o
/usr/local/cuda/include/cuda_runtime_api.h(13213): error: attribute "__host__" does not apply here

/usr/local/cuda/include/cuda_runtime_api.h(13213): error: expected a ";"

/home/eladpar/tensorrtx/yolov5/plugin/yololayer.h(87): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

2 errors detected in the compilation of "/tmp/tmpxft_000369d4_00000000-6_yololayer.cpp1.ii".
make[2]: *** [CMakeFiles/myplugins.dir/build.make:63: CMakeFiles/myplugins.dir/plugin/yololayer.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:163: CMakeFiles/myplugins.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

**Comment by wang-xinyu** [comment]
Can you check your nvcc?  Try this command `nvcc --version`.

**Comment by eladpar** [comment]
> Can you check your nvcc? Try this command `nvcc --version`.

```shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by wang-xinyu** [comment]
Here the nvcc is 10.1, but your CUDA is 11.8.   You need to use /usr/local/cuda/bin/nvcc.

**Comment by eladpar** [comment]
> * CUDA Version: 11.7

can you elaborate on what needs to be done?
beacuse as seen in this question :
https://stackoverflow.com/a/53504578
the cuda seen in nvidia-smi and nvcc-version don't have to be the same?

**Comment by wang-xinyu** [comment]
Thing is you have two nvcc in your OS.  Can you check your nvcc path by running `which nvcc`?  And also check if `/usr/local/cuda/bin/nvcc` is in your system?

**Comment by eladpar** [comment]
> Thing is you have two nvcc in your OS. Can you check your nvcc path by running `which nvcc`? And also check if `/usr/local/cuda/bin/nvcc` is in your system?

my nvcc is located in ```/usr/bin/nvcc```
there is no nvcc located in ```/usr/local/cuda/bin/nvcc```

**Comment by wang-xinyu** [comment]
Where are your CUDA libs and bins installed?
