### ISSUE TITLE
yolov5s-cls 使用  gen_wts.py  错误

### ISSUE THREAD

**Issue by z13228604287** [wang-xinyu/tensorrtx#1184]
- GPU, 1060
- OS, Win10x64
- Cuda 11.4
- TensorRT 8.0
- 
从：
https://github.com/ultralytics/yolov5/releases/tag/v7.0
yolov5s-cls.pt 

使用  https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v7.0/yolov5
gen_wts.py

命令：
python gen_wts.py -w yolov5s-cls.pt -o yolov5-cls.wts

错误：
Generating .wts for detect model
Loading yolov5s-cls.pt
YOLOv5  2022-12-21 Python-3.7.0 torch-1.12.1+cu116 CPU

Traceback (most recent call last):
  File "gen_wts.py", line 41, in <module>
    anchor_grid = model.model[-1].anchors * model.model[-1].stride[..., None, None]
  File "C:\ProgramData\Anaconda3\envs\yolo5\lib\site-packages\torch\nn\modules\module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'Classify' object has no attribute 'anchors'

**Comment by wang-xinyu** [comment]
Need -t or --type.

python gen_wts.py -w yolov5s-cls.pt -o yolov5-cls.wts -t cls

**Comment by wang-xinyu** [comment]
Can you help raise a PR to remove `default='detect'` in gen_wts.py?  I think this can avoid such issues as you mentioned.

**Comment by z13228604287** [comment]
谢谢

**Comment by z13228604287** [comment]
Thank you for your hard work
