### ISSUE TITLE
Arcface batch > 1

### ISSUE THREAD

**Issue by danwanban** [wang-xinyu/tensorrtx#1189]
Hi,

Does arcface module supports batch > 1 ?
( I saw a remark in the code that it is not, then some code lines with the batch param. used ) 

Thanks for the help !

**Comment by wang-xinyu** [comment]
The preprocessing and postprocessing don't support batch > 1 yet, you need to make some changes.

Preprocessing:
https://github.com/wang-xinyu/tensorrtx/blob/3c0f62e82fba36ff46ffb0f3706f249dce51da21/arcface/arcface-r50.cpp#L374

Postprocessing:
https://github.com/wang-xinyu/tensorrtx/blob/3c0f62e82fba36ff46ffb0f3706f249dce51da21/arcface/arcface-r50.cpp#L386

**Comment by danwanban** [comment]
Clear, thanks .
