### ISSUE TITLE
yolov5l.pt

### ISSUE THREAD

**Issue by KelvinHuang666** [wang-xinyu/tensorrtx#119]
how can i use with my own yolov5l.pt

**Comment by wang-xinyu** [comment]
did you modify the model architecture? is it same as yolov5's v2.0 release?

**Comment by KelvinHuang666** [comment]
I using https://github.com/ultralytics/yolov5/ to train my own dataset without changing anything

**Comment by wang-xinyu** [comment]
follow the readme here https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5

**Comment by wang-xinyu** [comment]
https://github.com/ultralytics/yolov5/  updated the model on 23 July(v2.0 release). Make sure you are using the latest yolov5l model.

**Comment by KelvinHuang666** [comment]
root@db4372e2ab7a:/yolov5/tensorrtx/yolov5/build# ./yolov5 -s
Loading weights: E:\LearningCodes\tensorrtx\yolov5V2\yolov5V2\weights\yolov5lV2.wts
yolov5: /yolov5/tensorrtx/yolov5/common.hpp:128: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file."' failed.
Aborted (core dumped)



I have make and got .wts file,but it didnt work,thanks

**Comment by KelvinHuang666** [comment]
root@db4372e2ab7a:/yolov5/tensorrtx/yolov5/build# ./yolov5 -d  ../samples
[08/04/2020-06:51:03] [E] [TRT] Parameter check failed at: runtime.cpp::deserializeCudaEngine::30, condition: (blob) != nullptr
yolov5: /yolov5/tensorrtx/yolov5/yolov5.cpp:532: int main(int, char**): Assertion `engine != nullptr' failed.
Aborted (core dumped)
I have no idea to solve this bug

**Comment by wang-xinyu** [comment]
loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file.

this means cannot open the wts file

**Comment by KelvinHuang666** [comment]
root@db4372e2ab7a:/yolov5/tensorrtx/yolov5/build# ./yolov5 -s
Loading weights: ../yolov5l.wts
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: kernel weights has count 10752 but 65280 was expected
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: count of 10752 weights in kernel, but kernel dimensions (1,1) with 256 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 256 * 1*1 * 255 / 1 = 65280
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: kernel weights has count 10752 but 65280 was expected
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: count of 10752 weights in kernel, but kernel dimensions (1,1) with 256 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 256 * 1*1 * 255 / 1 = 65280
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: kernel weights has count 10752 but 65280 was expected
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: count of 10752 weights in kernel, but kernel dimensions (1,1) with 256 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 256 * 1*1 * 255 / 1 = 65280
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: kernel weights has count 10752 but 65280 was expected
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: count of 10752 weights in kernel, but kernel dimensions (1,1) with 256 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 256 * 1*1 * 255 / 1 = 65280
Building engine, please wait for a while...
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: kernel weights has count 10752 but 65280 was expected
[08/04/2020-07:35:49] [E] [TRT] (Unnamed Layer* 307) [Convolution]: count of 10752 weights in kernel, but kernel dimensions (1,1) with 256 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 256 * 1*1 * 255 / 1 = 65280
[08/04/2020-07:35:49] [E] [TRT] Could not compute dimensions for (Unnamed Layer* 307) [Convolution]_output, because the network is not valid
[08/04/2020-07:35:49] [E] [TRT] Network validation failed.
Build engine successfully!
yolov5: /yolov5/tensorrtx/yolov5/yolov5.cpp:442: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted (core dumped)

I had done as you said,i think i can read wts file now,but the other bug came.thanks

**Comment by KelvinHuang666** [comment]
Thanks a lot.It works with 23~30ms for each image using one TaitanX GPU.

**Comment by JimEverest** [comment]
Hi @wang-xinyu and @KelvinHuang666  , Which trt version should I install for this yolov5 trt inference?

**Comment by KelvinHuang666** [comment]
我用的7.0

**Comment by JimEverest** [comment]
@KelvinHuang666  It helps, thank you!

**Comment by jubrowon** [comment]
hi, @wang-xinyu 

I trained the yolov5s model with my custom datasets(with cuda11) and I changed nothing but the nc (number of class from 80 to 3) in the yolov5s.yaml file and coco128.yaml. I could create a wts file but I got an segmentation error when I tried to command "make".

below the outputs
1. when I hit cmake ..

![image](https://user-images.githubusercontent.com/26244917/90374220-1e916d80-e0ae-11ea-89ca-837ddb624e35.png)

2. when I hit make
![image](https://user-images.githubusercontent.com/26244917/90374276-34069780-e0ae-11ea-97ab-a7eb0dc2135c.png)

My guess is the change I did could affect this or my CUDA version could be related to it.

Could you help me to figure this out?

Thanks,

**Comment by wang-xinyu** [comment]
The CLASS_NUM can be set in yololayer.h.

The error seems your cuda directories not right.  You can find where your cuda libraries are, and set the link and include directories in CMakeLists.txt

**Comment by jubrowon** [comment]
Thank you so much for your help :)

**Comment by GesilaA** [comment]
@wang-xinyu 你好，我遇到的问题和@JimEverest 很相似，但是我修改了CMakeLists后
![image](https://user-images.githubusercontent.com/19608156/90739618-49273480-e301-11ea-9f91-c56a388f53bc.png)
在make时还是出现错误。
这是cmake .. 的输出
![image](https://user-images.githubusercontent.com/19608156/90739844-58a67d80-e301-11ea-8215-3b68debb0c92.png)
这是出现错误的make的输出
![image](https://user-images.githubusercontent.com/19608156/90739844-58a67d80-e301-11ea-8215-3b68debb0c92.png)
求助/(ㄒoㄒ)/~~

**Comment by wang-xinyu** [comment]
@GesilaA 这是tensorrt版本问题，master用7或6，trt4 branch用4或5

**Comment by GesilaA** [comment]
@wang-xinyu 太谢谢您了，换成trt6成功了

**Comment by Linaom1214** [comment]
> 我用的7.0

您是怎么解决的呢？

**Comment by helloyan** [comment]
I use jetpack 4.4.1, trt 7.1, cuda 10.2 , use the latest v5 now,   i trained 5s with my own data with 2 classes,   i follow the transfer link and can make right,  but when run sudo  ./yolov5s -s  got error


Loading weights: ../yolov5s.wts
[01/22/2021-06:13:05] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/nvidia/AI/tensorrtx/yolov5/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted

**Comment by yajinwuzl** [comment]
this is same error of me. Is there any solution? @helloyan

**Comment by helloyan** [comment]
I will check the code and model after i have learn enough knowledgement about ai

**Comment by wang-xinyu** [comment]
If using your own trained model, read here again https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#config

**Comment by helloyan** [comment]
> this is same error of me. Is there any solution? @helloyan

I sloved, and yes should follow the link https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#config carefully

checklist:
1. you should train the model use the  default s/m/x/l  config file
2. check the marco in  yolov5.cpp and yololayer.h in the link above

**Comment by iliesaya** [comment]
same issue here :


`jetson@jetson-nx:~/git/tensorrtx/yolov5/build$ sudo ./yolov5 -s
Loading weights: ../yolov5s.wts
[02/03/2021-14:11:21] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/jetson/git/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted
`

I generated the file yolov5s.wts , changed the CLASS_NUM in yololayer.h and image size and batch size in yolov5.cpp , always the same error. 

any clue ?

**Comment by wang-xinyu** [comment]
@iliesaya pls try official models first, the model from yolov5 release tag.
Then try your own model.

**Comment by DoDuy147** [comment]
i have same error above 
[02/23/2021-12:32:36] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::494, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/duy/workspace/trt/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted
- I already run official models first, with yolov5s.pt pre-train. This work good. But when i train yolov5 with custom-data, i get best.pt and rename yolov5s.pt. Following guild  [https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#config](url) i convert to yolov5.wts and cmake, make. i get issue like above. 
- I think the reason of issue in my  file custom_yolov5.yaml. 
-# parameters
nc: 3  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, BottleneckCSP, [1024, False]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, BottleneckCSP, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, BottleneckCSP, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
This file totally same yolov5s.yaml in repo source, but i replace C3 by BottleneckCSP. Train still good result, but convert trt not working. How can I fix in yolov5.cpp in repo. I have test by replace :auto bottleneck_CSP2 = C3(network, weightMap, *conv1->getOutput(0), 96, 96, 2, true, 1, 0.5, "model.2"); C3 -> BottleneckCSP but no working and get error.

**Comment by DoDuy147** [comment]
i will fix issue. My mistake i should  replace C3 -> bottleneckCSP  not BottleneckCSP  because in commom.hpp define bottleneckCSP!

**Comment by DoveJH** [comment]
@fire717 I run it on jetson tx2 and have the same problem. have you solved it?

**Comment by zxj-wxj** [comment]
> i have same error above [02/23/2021-12:32:36] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::494, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr) yolov5: /home/duy/workspace/trt/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed. Aborted
> 
> * I already run official models first, with yolov5s.pt pre-train. This work good. But when i train yolov5 with custom-data, i get best.pt and rename yolov5s.pt. Following guild  [https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#config](url) i convert to yolov5.wts and cmake, make. i get issue like above.
> * I think the reason of issue in my  file custom_yolov5.yaml.
>   -# parameters
>   nc: 3  # number of classes
>   depth_multiple: 0.33  # model depth multiple
>   width_multiple: 0.50  # layer channel multiple
> 
> # anchors
> anchors:
> 
> * [10,13, 16,30, 33,23]  # P3/8
> * [30,61, 62,45, 59,119]  # P4/16
> * [116,90, 156,198, 373,326]  # P5/32
> 
> # YOLOv5 backbone
> backbone:
> 
> # [from, number, module, args]
> [[-1, 1, Focus, [64, 3]], # 0-P1/2 [-1, 1, Conv, [128, 3, 2]], # 1-P2/4 [-1, 3, BottleneckCSP, [128]], [-1, 1, Conv, [256, 3, 2]], # 3-P3/8 [-1, 9, BottleneckCSP, [256]], [-1, 1, Conv, [512, 3, 2]], # 5-P4/16 [-1, 9, BottleneckCSP, [512]], [-1, 1, Conv, [1024, 3, 2]], # 7-P5/32 [-1, 1, SPP, [1024, [5, 9, 13]]], [-1, 3, BottleneckCSP, [1024, False]], # 9 ]
> 
> # YOLOv5 head
> head: [[-1, 1, Conv, [512, 1, 1]], [-1, 1, nn.Upsample, [None, 2, 'nearest']], [[-1, 6], 1, Concat, [1]], # cat backbone P4 [-1, 3, BottleneckCSP, [512, False]], # 13
> 
> [-1, 1, Conv, [256, 1, 1]], [-1, 1, nn.Upsample, [None, 2, 'nearest']], [[-1, 4], 1, Concat, [1]], # cat backbone P3 [-1, 3, BottleneckCSP, [256, False]], # 17 (P3/8-small)
> 
> [-1, 1, Conv, [256, 3, 2]], [[-1, 14], 1, Concat, [1]], # cat head P4 [-1, 3, BottleneckCSP, [512, False]], # 20 (P4/16-medium)
> 
> [-1, 1, Conv, [512, 3, 2]], [[-1, 10], 1, Concat, [1]], # cat head P5 [-1, 3, BottleneckCSP, [1024, False]], # 23 (P5/32-large)
> 
> [[17, 20, 23], 1, Detect, [nc, anchors]], # Detect(P3, P4, P5) ] This file totally same yolov5s.yaml in repo source, but i replace C3 by BottleneckCSP. Train still good result, but convert trt not working. How can I fix in yolov5.cpp in repo. I have test by replace :auto bottleneck_CSP2 = C3(network, weightMap, *conv1->getOutput(0), 96, 96, 2, true, 1, 0.5, "model.2"); C3 -> BottleneckCSP but no working and get error.



> 我使用 jetpack 4.4.1, trt 7.1, cuda 10.2 ，现在使用最新的 v5，我用自己的数据训练了 5s 2 个班级，我按照传输链接正确，但当运行 sudo ./yolov5s -s 时错误
> 
> 加载权重：../yolov5s.wts [01/22/2021-06:13:05] [E] [TRT] 参数检查失败：../builder /Network.cpp::addScale::482，条件： shift .count > 0 ? (shift.values != nullptr) : (shift.values == nullptr) yolov5: /home/nvidia/AI/tensorrtx/yolov5/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std ::map<std::__cxx11::basic_string, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): 断言`scale_1'失败。 中止

我也改了yololayer.h但依旧报错怎么解决？有碰到吗？

**Comment by fire717** [comment]
> @fire717 I run it on jetson tx2 and have the same problem. have you solved it?

I have solved, just re-install the enviroment or other package (means you should carefully follow the README step )

**Comment by br0tda** [comment]
> > i already fix issue. My mistake i should replace C3 -> bottleneckCSP not BottleneckCSP because in commom.hpp define bottleneckCSP!
> 
> Had the same issue and the same model claim. Thanks to this reply, I finally fixed the issue. Just to make things clearer. For later readers' information, please replace `C3(...)` in function `build_engine` of `yolov5.cpp` to be `bottleneckCSP(...)`.

It works for me too on Jetson TX2 - Yolov5 v5.0

**Comment by Jeriko3** [comment]
> > i already fix issue. My mistake i should replace C3 -> bottleneckCSP not BottleneckCSP because in commom.hpp define bottleneckCSP!
> 
> Had the same issue and the same model claim. Thanks to this reply, I finally fixed the issue. Just to make things clearer. For later readers' information, please replace `C3(...)` in function `build_engine` of `yolov5.cpp` to be `bottleneckCSP(...)`.

Thanks works on Jetson TX2- Yolov5 v5.0

**Comment by mohamedabdallah1996** [comment]
> > @fire717 I run it on jetson tx2 and have the same problem. have you solved it?
> 
> I have solved, just re-install the enviroment or other package (means you should carefully follow the README step )

please what exactly you have installed to solve this error? I followed the readme and nothing changed, the same error with me.

**Comment by mohamedabdallah1996** [comment]
Finally I solved it. My **custom model** was trained on Yolov5 **V5.0** and I was working on **tensorrtx** related to **V6.0**. this was the conflict. after I cloned **tensorrtx** related to the same version of my custom model and followed the readme steps, it worked well.

**Comment by seungyong0313** [comment]
> 마침내 나는 그것을 해결했다. 내 **커스텀 모델** 은 Yolov5 **V5.0 에서 훈련되었고 나는 ****V6.0** 과 관련된 **tensorrtx** 에서 작업하고 있었습니다 . 이것이 갈등이었다. 내 사용자 지정 모델의 동일한 버전과 관련된 **tensorrtx** 를 복제 하고 추가 정보 단계를 수행한 후 제대로 작동했습니다.********

How did you solve it? I'm learning with 6.0, but I get the same error

**Comment by seungyong0313** [comment]
> Finally I solved it. My **custom model** was trained on Yolov5 **V5.0** and I was working on **tensorrtx** related to **V6.0**. this was the conflict. after I cloned **tensorrtx** related to the same version of my custom model and followed the readme steps, it worked well.

How did you solve it? I'm learning with 6.0, but I get the same error

**Comment by Transigent** [comment]
In my case, before training I had used existing code in my Colab notebook that created a 'custom_yolov5l.yaml' file based on the default 'yolov5l.yaml' file in the repository. This is where you specify the number of classes in the model definition, but the code in the notebook used the old model from V5. Should have checked I guess. Have to retrain now.

**Comment by naan03** [comment]
I got the same error on my Jetson Nano.  Thanks for mohamedabdallah1996's information. I solved it by retraining my .pt based on Yolov5 V6.0. Please read "Different versions of yolov5" carefully and make sure that Yolo, TensorRT and your model have the same version. 
小伙伴们，如果你也遇到这个问题，请把小鼠标滚到上面的"Different versions of yolov5"，严格按照说明操作。不要像我一样因为眼瞎而浪费了一天的时间，好运guys.
