### ISSUE TITLE
Feature extraction from intermediate layers  - yolov5-seg (m,l) 

### ISSUE THREAD

**Issue by danwanban** [wang-xinyu/tensorrtx#1190]
Hello,

Working with the yolov5seg (both m and l) - works great. 

Quick q - i would like to extract the features for each object, to be used later on in a tracking module. Is there way to get them (either for the bounding box OR mask object) ? 

Thanks again for the help, your work is highly appreciated !

## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
You need to know which middler layer you want. Then mark that layer as output layer in the build_engine() function.

Or you can crop the box and extract feature using another model or extracting traditional features like FAST, SIFT, etc.

**Comment by danwanban** [comment]
My question is - which layers are the one to mark (similar to https://github.com/ultralytics/yolov3/issues/1540 first remark) in the segmentation module ?

**Comment by wang-xinyu** [comment]
You should ask this to the yolov5 model designer, not here.

**Comment by danwanban** [comment]
Thank you.

**Comment by mh-ih** [comment]
> You need to know which middler layer you want. Then mark that layer as output layer in the build_engine() function.
> 
> Or you can crop the box and extract feature using another model or extracting traditional features like FAST, SIFT, etc.

@wang-xinyu thank you for your response, but how to mark a arbitrary layer as output? and how to get it in main code?

**Comment by wang-xinyu** [comment]
markOutput ->  https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov5/src/model.cpp#L345

prepare input output buffers -> https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov5/yolov5_seg.cpp#L56

get output -> https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov5/yolov5_seg.cpp#L79

**Comment by mh-ih** [comment]
Grate!
How to implement it for python code, like [yolov5_det_trt.py](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5_det_trt.py)

**Comment by wang-xinyu** [comment]
[yolov5_det_trt.py](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5_det_trt.py) can only get output, it cannot markOutput.

If you want to define the network in python, pls refer to this https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/resnet/resnet50.py#L220

**Comment by mh-ih** [comment]
Yes, that's right, I meant what changes should be made in the Python code to prepare "**_input output buffers_**" and get the new output

**Comment by mh-ih** [comment]
As far as I understand, Python automatically finds the number of inputs and outputs by iterating on the engine object. 
But the model.cpp doesn't make multiple output. I followed the instruction correctly but in no case the second output is produced.
I added below code after [spp9](https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov5/src/model.cpp#L305) as well as after the [main output](https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov5/src/model.cpp#L345)


  ` spp9->getOutput(0)->setName(kOutputTensorName);
  network->markOutput(*spp9->getOutput(0));`

**OR**

  ` spp9->getOutput(0)->setName("SPPF");
  network->markOutput(*spp9->getOutput(0));`

but doesn't work....

**Comment by wang-xinyu** [comment]
Did you re-serialize the trt engine after making this change?

**Comment by mh-ih** [comment]
yes but still `len(host_outputs)=1`. After serializing and making weight.engine, I used `yolov5_det -d weight.engine ../images` to deserialize and then used `python yolov5_det_trt.py`. As I used python code didn't make any change in the yolov5_det.cpp. Is that right??

**Comment by mh-ih** [comment]
Yes!!! that's it
I added the markOutput in [305](https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov5/src/model.cpp#L305) but yolov5s6 is about [396](https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov5/src/model.cpp#L396).
