### ISSUE TITLE
resnet怎么转成int8呢，看工程里没有相关配置

### ISSUE THREAD

**Issue by chyao7** [wang-xinyu/tensorrtx#1191]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
@chyao7 可以参考yolov5，USE_INT8宏定义包裹的代码
