### ISSUE TITLE
Tensorrt加载engine报错Assertion `d == a + length' failed，求指教

### ISSUE THREAD

**Issue by fanyang365** [wang-xinyu/tensorrtx#1192]
## Env

- GPU, RTX3060
- OS, e.g. Ubuntu16.04
- Cuda version 11.2
- TensorRT version 7.2.2.3

## About this repo

- tag yolov5-v6.0
- which model? yolov5

## Your problem
 用tensorrtx v6.0中YOLOV5编译出来的engine，加载的时候报错：src/yololayer.cu:55: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(const void*, size_t): Assertion `d == a + length' failed.，会是什么原因呢？

![5U(B`E5J)K99 W6RLCSJ@LV](https://user-images.githubusercontent.com/36870008/210052647-1cad78d1-3ecc-4eaa-af05-919e8069b53b.png)

![5U(B`E5J)K99 W6RLCSJ@LV](https://user-images.githubusercontent.com/36870008/210051414-a97b2b62-274d-47bf-ba96-9ebd02d3161e.png)
加载报错地方的代码：
![YXMKL`7%GC45)EGWFUOJ042](https://user-images.githubusercontent.com/36870008/210052293-8008d540-a0f3-4caf-a952-72947fd76cbc.png)
堆栈信息：
![3R22C)LEF1N { HNQMVF`T9](https://user-images.githubusercontent.com/36870008/210052354-e33650a3-2178-4e85-86d4-b6d4341c215e.png)

参数设置：
![UZEQWV}$GFSDAVF$CE5PKMG](https://user-images.githubusercontent.com/36870008/210052384-f7ee1797-2966-4680-aa05-8a6682606a83.png)
参数设置：
![BH303%40AJF}}C C1B)T17X](https://user-images.githubusercontent.com/36870008/210052405-097fe409-993f-4484-81c7-0d46877f411f.png)

![Q@WZ))0MJF)VR{P8ZBV$CR](https://user-images.githubusercontent.com/36870008/210052902-4af815fd-f0fd-4112-b3a5-847f53c59a06.png)

**Comment by wang-xinyu** [comment]
@fanyang365 可能是gen_wts.py的步骤出了问题，发一下运行gen_wts.py的命令

**Comment by fanyang365** [comment]
@wang-xinyu 感谢大佬指教！！！
运行命令：python gen_wts.py -w /root/PycharmProjects/yc-yolov5/runs/train/exp6/weights/best.pt -o helmet.wts
gen_wts.py文件：
![1672713651046](https://user-images.githubusercontent.com/36870008/210293731-ac247713-4af1-4757-990f-1e2585805f86.jpg)

**Comment by wang-xinyu** [comment]
这里的YOLODetector也不是tensorrtx的代码啊，你这个.engine是用tensorrtx生成的吗？

![YXMKL`7%GC45)EGWFUOJ042](https://user-images.githubusercontent.com/36870008/210052293-8008d540-a0f3-4caf-a952-72947fd76cbc.png)

**Comment by fanyang365** [comment]
@wang-xinyu 用tensorrtx生成的.engine，用TnesorRT去加载的engine。

我又深入调试了一下，发现getPluginCreator函数报错 could not find plugin YoloLayer_TRT vesion 1

![1672724714888](https://user-images.githubusercontent.com/36870008/210305467-3374122a-098c-4dd9-94e4-4ea6d905a8c0.png)

**Comment by wang-xinyu** [comment]
用自己的程序去加载engine，需要link一下libmyplugins.so

**Comment by fanyang365** [comment]
@wang-xinyu 加上了也还是会报错呢，我再研究一下呢！谢谢
![1672731825529](https://user-images.githubusercontent.com/36870008/210316690-7e554563-33b4-42c6-96d0-5504e8013403.png)

**Comment by wang-xinyu** [comment]
同时#include yololayer.h

**Comment by deepAiCheng** [comment]
Hi，请教一下，我自己转的engine文件，不是用的tensorrtx生成的.engine，然后使用的是tensorrtx推理，报错nvinfer1::YoloLayerPlugin::YoloLayerPlugin(const void*, size_t): Assertion `d == a + length' failed.
