### ISSUE TITLE
problem warming up yolov5-v7.0 segmentation models?

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [wang-xinyu/tensorrtx#1193]
## Env

- GPU, e.g. Orin
- OS, e.g. Ubuntu 20.04
- Cuda version (using NVIDIA container): nvcr.io/nvidia/l4t-pytorch:r34.1.1-pth1.12-py3
- TensorRT version: tensorrt 8.4.0.11

## About this repo

- which branch/tag/commit are you using? 7.0
- which model? yolov5, retinaface? yolov5s-seg

## Your problem

- what is your command? python3 yolov5_seg_trt.py build/yolov5s-seg.engine 
- what's your output?

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov5_seg_trt.py", line 491, in run
    batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros())
  File "yolov5_seg_trt.py", line 184, in infer
    result_masks = self.process_mask(output_proto_mask, result_proto_coef, result_boxes, batch_origin_h[i], batch_origin_w[i])
  File "yolov5_seg_trt.py", line 431, in process_mask
    masks = self.sigmoid((result_proto_coef @ result_proto_masks.astype(np.float32).reshape(c, -1))).reshape(-1, mh, mw)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 32 is different from 0)
```
- what output do you expect?

I think there is a problem when doing the warm up, errors like this one appear and then the inference is done correctly.

```
input->['samples/bus.jpg'], time->10.85ms, saving into output/
input->['samples/zidane.jpg'], time->15.53ms, saving into output/
```

**Comment by wang-xinyu** [comment]
@Rex-LK Can you take a look?

**Comment by Rex-LK** [comment]
> @Rex-LK Can you take a look?

ok

**Comment by Rex-LK** [comment]
> ## Env
> * GPU, e.g. Orin
> * OS, e.g. Ubuntu 20.04
> * Cuda version (using NVIDIA container): nvcr.io/nvidia/l4t-pytorch:r34.1.1-pth1.12-py3
> * TensorRT version: tensorrt 8.4.0.11
> 
> ## About this repo
> * which branch/tag/commit are you using? 7.0
> * which model? yolov5, retinaface? yolov5s-seg
> 
> ## Your problem
> * what is your command? python3 yolov5_seg_trt.py build/yolov5s-seg.engine
> * what's your output?
> 
> ```
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "yolov5_seg_trt.py", line 491, in run
>     batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros())
>   File "yolov5_seg_trt.py", line 184, in infer
>     result_masks = self.process_mask(output_proto_mask, result_proto_coef, result_boxes, batch_origin_h[i], batch_origin_w[i])
>   File "yolov5_seg_trt.py", line 431, in process_mask
>     masks = self.sigmoid((result_proto_coef @ result_proto_masks.astype(np.float32).reshape(c, -1))).reshape(-1, mh, mw)
> ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 32 is different from 0)
> ```
> 
> * what output do you expect?
> 
> I think there is a problem when doing the warm up, errors like this one appear and then the inference is done correctly.
> 
> ```
> input->['samples/bus.jpg'], time->10.85ms, saving into output/
> input->['samples/zidane.jpg'], time->15.53ms, saving into output/
> ```
Int process of warmUp，the pred is None, resulting in the error of "masks = self.sigmoid((result_proto_coef @ result_proto_masks.astype(np.float32).reshape(c, -1))).reshape(-1, mh, mw)"。Now adding a condition before process_mask，it works.

**Comment by Rex-LK** [comment]
> @Rex-LK Can you take a look?
I submitted a PR to solve the problem  @wang-xinyu

**Comment by Rex-LK** [comment]
> > ## Env
> > 
> > * GPU, e.g. Orin
> > * OS, e.g. Ubuntu 20.04
> > * Cuda version (using NVIDIA container): nvcr.io/nvidia/l4t-pytorch:r34.1.1-pth1.12-py3
> > * TensorRT version: tensorrt 8.4.0.11
> > 
> > ## About this repo
> > 
> > * which branch/tag/commit are you using? 7.0
> > * which model? yolov5, retinaface? yolov5s-seg
> > 
> > ## Your problem
> > 
> > * what is your command? python3 yolov5_seg_trt.py build/yolov5s-seg.engine
> > * what's your output?
> > 
> > ```
> > Exception in thread Thread-1:
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> >     self.run()
> >   File "yolov5_seg_trt.py", line 491, in run
> >     batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros())
> >   File "yolov5_seg_trt.py", line 184, in infer
> >     result_masks = self.process_mask(output_proto_mask, result_proto_coef, result_boxes, batch_origin_h[i], batch_origin_w[i])
> >   File "yolov5_seg_trt.py", line 431, in process_mask
> >     masks = self.sigmoid((result_proto_coef @ result_proto_masks.astype(np.float32).reshape(c, -1))).reshape(-1, mh, mw)
> > ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 32 is different from 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * what output do you expect?
> > 
> > I think there is a problem when doing the warm up, errors like this one appear and then the inference is done correctly.
> > ```
> > input->['samples/bus.jpg'], time->10.85ms, saving into output/
> > input->['samples/zidane.jpg'], time->15.53ms, saving into output/
> > ```
> 
> Int process of warmUp，the pred is None, resulting in the error of "masks = self.sigmoid((result_proto_coef @ result_proto_masks.astype(np.float32).reshape(c, -1))).reshape(-1, mh, mw)"。Now adding a condition before process_mask，it works.

@wang-xinyu @JNaranjo-Alcazar

**Comment by wang-xinyu** [comment]
@JNaranjo-Alcazar Can you check this? https://github.com/wang-xinyu/tensorrtx/pull/1194/files

**Comment by JNaranjo-Alcazar** [comment]
@wang-xinyu @Rex-LK I am gonna check this now

**Comment by JNaranjo-Alcazar** [comment]
Yes, it works now! @wang-xinyu @Rex-LK

**Comment by wang-xinyu** [comment]
Merged https://github.com/wang-xinyu/tensorrtx/pull/1194

Thanks @Rex-LK @JNaranjo-Alcazar
