### ISSUE TITLE
yolov7自己训练的权重结果不对，但是官方的权重跑下来没问题，这是什么原因，预处理什么都一样的

### ISSUE THREAD

**Issue by Cute-Yang** [wang-xinyu/tensorrtx#1198]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
是否试过checkout到v0.1分支再训练？

需要用cfg/deploy/中的yaml文件，不支持cfg/training/中的yaml文件

**Comment by xyt2008** [comment]
> 是否试过checkout到v0.1分支再训练？
> 
> 需要用cfg/deploy/中的yaml文件，不支持cfg/training/中的yaml文件

我用最新的yolov7版本训练yolov7 w6，精度和曲线都正常，但是转不了tensorrt模型；
用v0.1版本yolov7 w6同样的数据，精度特别差。官方给的v0.1版本yolov7 w6精度正常。用的是cfg/deploy/中的yaml文件。
最新版本训练曲线：
![image](https://user-images.githubusercontent.com/12556876/211460337-63bf9747-d59a-4586-aaf6-20ac4050b490.png)
v0.1版本训练曲线：
![image](https://user-images.githubusercontent.com/12556876/211460375-b12adc55-cf4d-43fd-a9be-ac11fb4e1aeb.png)
v0.1版本训练参数：
![image](https://user-images.githubusercontent.com/12556876/211460595-2a3b2c7f-c2a1-4f06-9859-353a15d83b98.png)

**Comment by uyolo1314** [comment]
可能是没有重参数化，转wts模型之前需要重参数化（reparameterization），可以参考https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb
