### ISSUE TITLE
Fantastic Repo. Python Question

### ISSUE THREAD

**Issue by marvision-ai** [wang-xinyu/tensorrtx#12]
Hello, I think this repo is great! I am curious... is there any plan on creating a python wrapper to call all your tensorRT models and preform inference with? 

I have lots of code in my python, and I would love to test your models with my python libraries to give you live benchmarks on all the jetson devices :) 

Thank you again!

**Comment by wang-xinyu** [comment]
@mbufi Thanks for your interests. 

This repo is using TensorRT C++ API. And the purpose is to share with the community how to implement popular DL networks with TensorRT C++ network definition API.

So I think python wrapper maybe is not concerned in this repo.

Well you can implement  a python wrapper to call these models :)
