### ISSUE TITLE
编译时遇到的问题

### ISSUE THREAD

**Issue by zhaoguoqing12** [wang-xinyu/tensorrtx#120]
![image](https://user-images.githubusercontent.com/47818312/89273509-3ad6e880-d672-11ea-9b5a-1c750f3d3685.png)
tensorrt7.0.0.11  opencv3.3

**Comment by wang-xinyu** [comment]
nvinfer.h是tensorrt的头文件，如果tensorrt是用tar包安装的，非系统目录，需要修改cmake中tensorrt的include和link路径

**Comment by zhaoguoqing12** [comment]
> nsorrt的

请问具体在哪里修改

**Comment by wang-xinyu** [comment]
@zhaoguoqing12 CMakeLists.txt 添加
include_directories(tensorrt头文件路径)
link_directories(tensorrt so路径)

**Comment by JuZiSYJ** [comment]
您好，我也是tar安装的tensrort，跑官方的minist demo能通过，CmakeList添加后能编译出yolo3，但是运行时报错
./yolov3: error while loading shared libraries: libmyelin.so.1: cannot open shared object file: No such file or directory， 可是我lib添加到  bashrc里面了，不知怎么解决？
