### ISSUE TITLE
Unable to load library: libnvinfer_builder_resource.so.8.4.1

### ISSUE THREAD

**Issue by hujhcv** [wang-xinyu/tensorrtx#1205]
## Env

- GPU,  RTX3090
- OS, Ubuntu20.04
- Cuda 11.1
- TensorRT 8.4.1

## About this repo

- which model? yolov5 v7.0

## Your problem

- what is your command?   `sudo ../yolov5_det -s best.wts best.engine s`
- what's your output?  [01/11/2023-16:33:50] [E] [TRT] 6: [libLoader.h::DynamicLibrary::50] Error Code 6: Internal Error (Unable to load library: libnvinfer_builder_resource.so.8.4.1)
段错误 (核心已转储)

- what output do you expect?  把/opt/TensorRT-8.4.1.5/lib 路径加到了 LD_LIBRARY_PATH 后还是有这个问题。

Thanks!

**Comment by wang-xinyu** [comment]
不加sudo试试

**Comment by hujhcv** [comment]
> 不加sudo试试

不加sudo 也一样的错误哦

**Comment by wang-xinyu** [comment]
参考下这个 https://github.com/NVIDIA/TensorRT/issues/2218#issuecomment-1329813418

**Comment by hujhcv** [comment]
> 参考下这个 [NVIDIA/TensorRT#2218 (comment)](https://github.com/NVIDIA/TensorRT/issues/2218#issuecomment-1329813418)

我把TensorRT的路径/opt/TensorRT-8.4.1.5/lib添加到~/.bashrc中然后执行source ~/.bashrc，然后打印LD_LIBRARY_PATH，可以找到/opt/TensorRT-8.4.1.5/lib，但确实有这个(Unable to load library: libnvinfer_builder_resource.so.8.4.1)问题。

我在终端先执行这一句：export LD_LIBRARY_PATH=/opt/TensorRT-8.4.1.5/lib
再执行：./yolov5_det -s best.wts best.engine s  就没问题了

可能还是环境的问题，谢谢！
