### ISSUE TITLE
Pre-process Speed is way too slow

### ISSUE THREAD

**Issue by danielzhangau** [wang-xinyu/tensorrtx#1208]
## Env

- GPU, A4000
- OS, Ubuntu20.04
- Cuda version, 11.8
- TensorRT version, 8.5.1-1+cuda11.8

## About this repo

- which branch/tag/commit are you using? master [f334a1a](https://github.com/wang-xinyu/tensorrtx/commit/f334a1aa3843ac7c60a481450ea96b868e4f4852) on Jan 11
- which model? yolov5

## Your problem

- what is your command? 
`python yolov5_det_trt.py`
I have modified the [yolov5_det_trt.py](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5_det_trt.py) file to generate the mean inference speed of running the giving dataset including pre-processing, inference, and post-processing.
![Screen Shot 2023-01-16 at 6 24 00 pm](https://user-images.githubusercontent.com/41173132/212631273-0eb598ae-7573-49b6-bf19-1200c8936611.png)

- what's your output?
`Speed: 13.00ms pre-process, 1.61ms inference, 0.68ms NMS per image`
- what output do you expect?
By running YOLOv5 detect.py, I got:
`Speed: 0.4ms pre-process, 5.7ms inference, 0.8ms NMS per image at shape (1, 3, 640, 640)`
I'm expecting the total inference time can be smaller. How should I avoid the long pre-processing time?

**Comment by wang-xinyu** [comment]
Is it possible to call YOLOv5's preprocess in this yolov5_det_trt.py?

And can you please tell what's the difference between there two preprocess function?

BTW, C++ is using CUDA preprocessing, did you try that?

**Comment by danielzhangau** [comment]
Seems like the YOLOv5 did not count the image manipulation steps (convert color, letterbox, etc.) into the preprocess time. And I found out the for loop itself spent a lot of time.

**Comment by wang-xinyu** [comment]
The loop contains many steps, including
- Read image and decode into raw BGR data
- BGR -> RGB
- Letterbox
- Normalize

Please check whether YOLOv5 preprocessing contains all these steps.

And you can also call the CUDA preprocessing in Python by using Pybind or Ctypes.
