### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.utils' when execute gen_wts.py for yolov5

### ISSUE THREAD

**Issue by JimEverest** [wang-xinyu/tensorrtx#121]
I am running the TensorRTx  yolov5 by the readme instruction on Windows 10. however it thrown an error

`D:\git\yolov5> python .\gen_wts.py`

`Traceback (most recent call last):`

`  File ".\gen_wts.py", line 1, in <module>`

`    from utils.utils import *`

`ModuleNotFoundError: No module named 'utils.utils' `

Anyone can help me get out of this? thanks!

**Comment by wang-xinyu** [comment]
gen_wts.py should be put in https://github.com/ultralytics/yolov5 and run.
the utils module is in https://github.com/ultralytics/yolov5.

**Comment by mfruhner** [comment]
Hi, i have the same problem.
I copied the gen_wts.py to the ultralytics folder and ran it, but the utils.utils module is not found, because it is not an installed module but just a local folder...

**Comment by wang-xinyu** [comment]
@mfruhner so you need firstly make https://github.com/ultralytics/yolov5 run.  Please follow its readme and try  its 'detect.py' first.

**Comment by mfruhner** [comment]
I think there is no utils.utils file in the recent commits anymore. The file was renamed to utils/general.py.. could you check that?

**Comment by mfruhner** [comment]
If you change the code to the following, it works with the latest commit of yolov5:

```
from utils.general import *
from utils.torch_utils import *

...

# Initialize
device = select_device('0')
```

**Comment by wang-xinyu** [comment]
@mfruhner Yes! you are right.  The file was renamed to utils/general.py. I just updated the script. https://github.com/wang-xinyu/tensorrtx/commit/f395573bcd92d6e5eaa824b0b67f0968c3390dc0

**Comment by SunnyBoy-GitHub** [comment]
Hi, i have the same problem！！！
ModuleNotFoundError: No module named 'utils.torch_utils'

**Comment by SunnyBoy-GitHub** [comment]
> Hi, i have the same problem. I copied the gen_wts.py to the ultralytics folder and ran it, but the utils.utils module is not found, because it is not an installed module but just a local folder...

ModuleNotFoundError: No module named 'utils.torch_utils'

Did you solve it in the end
