### ISSUE TITLE
The advanced version of reasoning is slower

### ISSUE THREAD

**Issue by M15-3080** [wang-xinyu/tensorrtx#1210]
## Env

- GPU,   RTX3080Ti
- OS,   Win11
- Cuda version，  11.1
- TensorRT version，  7.2.1.6

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5

## Your problem
I used versions 6.0 and 6.2 of YOLOV5 for my reasoning; But I've tried it many times, and the reasoning time for version 6.2 is much slower than 6.0. I hope you can help me, thank you.The left side shows version 6.2 and the right side shows version 6.0.
![image](https://user-images.githubusercontent.com/91411583/212828685-04be55ec-d14c-4fdd-bce4-6ebfe7aa21eb.png)

**Comment by wang-xinyu** [comment]
Are you using the same code for v6.0 and v6.2?

**Comment by M15-3080** [comment]
> 您是否对 v6.0 和 v6.2 使用相同的代码？

Yes, including the test pictures are the same
