### ISSUE TITLE
Conversion to int8

### ISSUE THREAD

**Issue by BenLag2906** [wang-xinyu/tensorrtx#1212]
Hello all,

I try to convert my yoloV5 model to tensorRT. In FP16 and FP32 it's OK. I encountered an issu for int8 conversion, I followed your instruction, change the flag and recompile the yoloV5.exe, I dowloand the calibration dataset as you described.

And I obtained the following error.

Could you please give a piece of advise ?

Ben
![yolo](https://user-images.githubusercontent.com/26578899/213399981-2cc9a5d9-d94f-4b24-9fb8-e9bb75a0b332.png)

**Comment by wang-xinyu** [comment]
Do you have a Linux machine to test this? I doubt this issue is related to Windows.

**Comment by BenLag2906** [comment]
Hi,
It will be difficult, for me, to reproduce on Linux.
Indeed I use cmake to compile on windows, and i think the issue its when on step of calibration, tensorrt try to load images. Unfortunetly this calibration is integrated to tensorRT functions..
Do you think there a way bypass the issue ?

Best regards

**Comment by wang-xinyu** [comment]
Ok, then you need to debug from here https://github.com/wang-xinyu/tensorrtx/blob/c66b8b7e2c471f5eba03df9e39cb2b410041be29/yolov5/src/calibrator.cpp#L80

to check why this error happened.

And did you try to remove the `int8calib.table` file and run again?

**Comment by BenLag2906** [comment]
Hi,

Indeed I try to modify the way to read image file in the classe described, It's OK.

Thanks for your answer an sorry to not see the issue...

Best regards.
