### ISSUE TITLE
Time increases in yolov5 when for loop is big

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [wang-xinyu/tensorrtx#1213]
## Env

- GPU, e.g. Orin
- OS, e.g. Ubuntu20.04
- Cuda version: nvcr.io/nvidia/l4t-pytorch:r34.1.1-pth1.12-py3
- TensorRT version tensorrt 8.4.0.11

## About this repo

- which branch/tag/commit are you using? yolov5
- which model? yolov5,

## Your problem

Making predictions in a for loop, following

```
for batch in image_path_batches:
            # create a new thread to do inference
            thread1 = inferThread(yolov5_wrapper, batch)
            thread1.start()
            thread1.join()
```

I can see that time increases slowly. For example, the first 20 images are predicted in 5ms, and then the time increases to 9ms, 11ms, and so on.

Any idea if this implementation is not efficient for big for loops?

Thanks in advance

**Comment by wang-xinyu** [comment]
Can you please try C++ once?
