### ISSUE TITLE
Is it possible use detection directly on an .engine file without going through serializing it to wts format first ?

### ISSUE THREAD

**Issue by ervgan** [wang-xinyu/tensorrtx#1214]
## Env

- Google Colab

## About this repo

- yolov5

## Your problem

Hello, 
Thanks a lot for your work and this repo! I am finding it very useful. I just wanted to know if it was possible to use detection directly on our own engine file (./yolov5_det -d yolov5s.engine ../images) without having to go through serializing a pt model into wts format first? I basically already exported my pt model from yolov5 into .engine file. Not sure what I should change in the code to make it work. 

Thanks !

**Comment by wang-xinyu** [comment]
Where did you get the TRT .engine file?

**Comment by ervgan** [comment]
Hi! 
I exported my model directly in the .engine format from yolov5 using the following command:

python export.py --weights best.pt --include engine

**Comment by wang-xinyu** [comment]
Got it, you cannot use that .engine directly with (./yolov5_det -d yolov5s.engine ../images) .

Because the .engine file generated from this repo has different output tensor layout from that .engine.

**Comment by ervgan** [comment]
Oh okk I ses, many thanks for your quick answer! 
On a related matter, I took my custom trained model best.pt (trained using the yolov5 small model) and converted it into wts and then when I tried to convert it to best.engine, it has many error messages telling me that the tensor dimensions are different. But since I trained my model using the yolov5s shouldnt it have the same tensor dimensions and it should work the same way if I use the argument -s for small model ?

**Comment by wang-xinyu** [comment]
First you need to check the sub-versions of yolov5, there are more than 7 sub-versions, https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

And then try the pre-trained model, if it works fine but your custom model doesn't, you need compare your model with the pre-trained model layer by layer to find the differences.

**Comment by ervgan** [comment]
Thanks!
