### ISSUE TITLE
Code Understanding: ctypes.CDLL & LEN_ALL_RESULT

### ISSUE THREAD

**Issue by danielzhangau** [wang-xinyu/tensorrtx#1216]
## Env

- GPU, A4000
- OS, Ubuntu20.04
- Cuda version, 11.8
- TensorRT version, 8.5.1-1+cuda11.8

## About this repo

- which branch/tag/commit are you using? master [c66b8b7](https://github.com/wang-xinyu/tensorrtx/commit/c66b8b7e2c471f5eba03df9e39cb2b410041be29) on Jan 17, 2023
- which model? yolov5

## Your problem
There are two parts of the code that I am trying to understand.
- What do the ctypes.CDLL do to the python inference?
- Why we have to set two ENV variables (LEN_ALL_RESULT & LEN_ONE_RESULT)?
Any helps would be appreciated!!

**Comment by wang-xinyu** [comment]
The last layer of the engine is a custom layer, implemented by plugin, we named it as yololayer. https://github.com/wang-xinyu/tensorrtx/blob/c66b8b7e2c471f5eba03df9e39cb2b410041be29/yolov5/src/model.cpp#L343

yololayer is built into a .so, which needs to be loaded by ctypes.CDLL in python.

LEN_ALL_RESULT & LEN_ONE_RESULT are const value, not ENV, there are related to the output layout of yololayer.
