### ISSUE TITLE
Doubt about INT8 quantization

### ISSUE THREAD

**Issue by Alberto1404** [wang-xinyu/tensorrtx#1218]
Hi, I have a question regarding the int8 quantization method. 
For example, in Yolov5. 
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#int8-quantization
It is said to unzip the images inside build/ folder. Does it matter the name of the unzipped folder? When generating the engine, how is it going to know where is the folder with the images?
For instance, in your examples you named them coco_calib. Should I follow that rule for naming it in my custom dataset?

**Comment by wang-xinyu** [comment]
The folder name is hard coded in the code.

**Comment by Alberto1404** [comment]
Could you please let me know where is it hardcoded?

**Comment by Alberto1404** [comment]
Thank you. Solved
