### ISSUE TITLE
关于使用tensorrt之后的推理速度问题

### ISSUE THREAD

**Issue by zhaoguoqing12** [wang-xinyu/tensorrtx#122]
我发现不使用tensorrt之前和之后，速度没有改变，请问我是哪里错误使用了？
yolov5x测试一张图片都在50~70ms
![image](https://user-images.githubusercontent.com/47818312/89411004-43551f00-d757-11ea-89a8-61e8b306fa63.png)
![image](https://user-images.githubusercontent.com/47818312/89411028-4e0fb400-d757-11ea-8c2b-651237716179.png)
![image](https://user-images.githubusercontent.com/47818312/89411050-5831b280-d757-11ea-96a8-e4b17010f2cc.png)

**Comment by wang-xinyu** [comment]
@zhaoguoqing12 你的inference time包括前后处理的时间了吗？

**Comment by wang-xinyu** [comment]
还有pytorch 的640输入，是长边640，短边等比例缩放，实际往往没有640x640
这边就是640x640

**Comment by zhaoguoqing12** [comment]
> 推理时间包括前后处

包括这些,但是推理时间都差不多，不管怎么还是感觉您的贡献

**Comment by wang-xinyu** [comment]
@zhaoguoqing12 单独对比inference时间，不要包括前后处理，尤其前处理，可能没有python那边快，需要优化

**Comment by guyiyifeurach** [comment]
> 

你这个说法有问题吧？Pytorch里的推理代码，是会像你说的那样长边640，短边等比例缩放，但是它会加上pad，使待推理图片还是达到640*640。
