### ISSUE TITLE
为什么要把weights或者pt文件转换成.wts呢？不是可以直接读取吗？

### ISSUE THREAD

**Issue by Joevaen** [wang-xinyu/tensorrtx#1223]
如题，请问是为什么呢？谢谢。

**Comment by wang-xinyu** [comment]
在C++中怎么直接读取呢？调用libtorch？

**Comment by Joevaen** [comment]
对的，这样读取是为了避免使用libtorch吗？

**Comment by wang-xinyu** [comment]
对，C++尽量不依赖TRT以外的第三方库。另外如果是从Tensorfow、mxnet等框架的模型，用libtorch也不行，这个repo也有用到Tensorfow、mxnet模型

**Comment by Joevaen** [comment]
谢谢，明白了，在部署时候的最好选择是直接使用.engine文件对吧。

**Comment by z13228604287** [comment]
c++ 能PT  转  .wts  吗？

**Comment by wang-xinyu** [comment]
转wts在训练的机器上完成就好，wts文件是文本文件，是通用的

wts->engine这一步需要在目标机器上运行，仅生成一次就好，后面就只需要engine文件
