### ISSUE TITLE
real-esrgan推断过程的一些问题

### ISSUE THREAD

**Issue by T0L0ve** [wang-xinyu/tensorrtx#1225]
## Env

- GPU, V100, RTX3070
- OS,Win10
- Cuda version 11.7
- TensorRT version 8.5

## About this repo

- which model? real-esrgan

## Your problem

-首先感谢您的工作，我按照步骤成功在tensorrt上运行了代码并获取了图片结果，但我仍有一些问题想请教一下。
-1.项目只对和test_img ost009.png相同大小的图片生效（640*448）,输入其他大小的图片我无法在cmd命令行中获取结果。如果我想要在不同大小的图片上测试是不是每次都需要在real-esrgan.cpp中更改INPUT_H和INPUT_W的值然后重新生成解决方案，重新生成.engine文件。
-2.关于模型精度问题。如果我想使用半精度测试是仅需要将real-esrgan.cppPRECISION_MODE改为16即可，还是gen_wts.py中的RealESRGANer的half参数改为not args.fp32。
-3. .engine文件一旦生成模型参数就无法改变了吗，比如生成了全精度的engine我可以使用它进行半精度预测吗。

**Comment by wang-xinyu** [comment]
1. 这里生成的.engine是固定input shape的，而且没有对输入的图片进行resize，你可以做resize然后再送入engine。也可以尝试去生成动态input shape的engine，可参考repo中的yolov3-spp代码，但是动态shape会影响性能
2. 修改cpp即可，gen_wts只需要导读fp32的权重
3. 不可以，精度不能动态，可以生成两个engine
