### ISSUE TITLE
code understanding: what are gw and gd and how did you fix them?

### ISSUE THREAD

**Issue by ervgan** [wang-xinyu/tensorrtx#1226]
Hi !

I just wanted to know what gw and gd represent and how you fixed them? for example for the small model, gd = 0.33 and gw = 0.5, where did you find these numbers and what's their use?
I saw these two methods:

`int get_width(int x, float gw, int divisor) {
  return int(ceil((x * gw) / divisor)) * divisor;
}

//  
int get_depth(int x, float gd) {
  if (x == 1) return 1;
  int r = round(x * gd);
  if (x * gd - int(x * gd) == 0.5 && (int(x * gd) % 2) == 0) {
    --r;
  }
  return std::max<int>(r, 1);
}`

but still not sure on what they represents. Any help is appreciated, many thanks!

**Comment by wang-xinyu** [comment]
They are from the yolov5 model https://github.com/ultralytics/yolov5/blob/d02ee60512c50d9573bb7a136d8baade8a0bd332/models/yolo.py#L302
