### ISSUE TITLE
code understanding: C3 and bottleneck c1 and c2 args are always the same?

### ISSUE THREAD

**Issue by ervgan** [wang-xinyu/tensorrtx#1227]
I have another question regarding this line of the C3 function in model.cpp for yolov5

`auto b = bottleneck(network, weight_map, *y1, c_, c_, shortcut, g, 1.0,
                        layer_name + ".m." + std::to_string(i));`

basically c_ is used twice as function arguments here and in the bottleneck method, we have:

`ILayer* bottleneck(INetworkDefinition* network,
                   std::map<std::string, Weights>& weight_map,
                   const ITensor& input, int c1, int c2, bool shortcut, int g,
                   float e, std::string layer_name) {
  auto cv1 = CreateConvoLayer(network, weight_map, input, (int)((float)c2 * e),
                              1, 1, 1, layer_name + ".cv1");
  auto cv2 = CreateConvoLayer(network, weight_map, *cv1->getOutput(0), c2, 3, 1,
                              g, layer_name + ".cv2");
  if (shortcut && c1 == c2) {
    auto ew = network->addElementWise(input, *cv2->getOutput(0),
                                      ElementWiseOperation::kSUM);
    return ew;
  }
  return cv2;
}`

So my question is what is the use of c1 and c2 ? and why compare them if they are always the same anyways since the inputs to c1 and c2 are both c_ from the C3 method.

Thanks!

**Comment by wang-xinyu** [comment]
Refer to the C3 definition https://github.com/ultralytics/yolov5/blob/d02ee60512c50d9573bb7a136d8baade8a0bd332/models/common.py#L159

**Comment by ervgan** [comment]
Thanks !
