### ISSUE TITLE
error: identifier "IPluginV2IOExt" is undefined?

### ISSUE THREAD

**Issue by LevineYang** [wang-xinyu/tensorrtx#123]
编译出现以下问题：

/home/ss/test_model/yolov5/tensorrtx/yolov3/yololayer.h(137): error: member function declared with "override" does not override a base class member

/home/ss/test_model/yolov5/tensorrtx/yolov3/yololayer.cu(99): error: identifier "PluginTensorDesc" is undefined

/home/ss/test_model/yolov5/tensorrtx/yolov3/yololayer.cu(99): error: identifier "PluginTensorDesc" is undefined

/home/ss/test_model/yolov5/tensorrtx/yolov3/yololayer.cu(127): error: identifier "IPluginV2IOExt" is undefined

/home/ss/test_model/yolov5/tensorrtx/yolov3/yololayer.cu(243): error: identifier "IPluginV2IOExt" is undefined

/home/ss/test_model/yolov5/tensorrtx/yolov3/yololayer.cu(250): error: identifier "IPluginV2IOExt" is undefined

当前环境:
RTX2060
cuda 10.2 / cudnn 7.6.5 
pytorch 1.6
tensorrt 7.0

看到之前有人提问，回答是说是tensorrt版本的问题，但是我用的是7.0，大佬知道可能的其他原因吗

**Comment by wang-xinyu** [comment]
@LevineYang 参考下这个问题，https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/faq.md#1-fatal-error-nvinferh-no-such-file-or-directory，看看tensorrt的include和link路径是否正确

**Comment by LevineYang** [comment]
> @LevineYang 参考下这个问题，https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/faq.md#1-fatal-error-nvinferh-no-such-file-or-directory
> 看看tensorrt的include和link路径是否正确

解决了，谢谢！ “If you install tensorrt TAR or ZIP file, the include_directories and link_directories of tensorrt should be added in CMakeLists.txt.” 这句话非常有用，赞！！

**Comment by LevineYang** [comment]
> ### @LevineYang Can you show me your cmakelists.txt ,i meet same question

Sure!
"include_directories(${PROJECT_SOURCE_DIR}/include)
include_directories(/usr/local/cuda-10.2/include)
link_directories(/usr/local/cuda-10.2/lib64)
include_directories(/usr/include/x86_64-linux-gnu/)
link_directories(/usr/lib/x86_64-linux-gnu/)
include_directories(/home/ss/TensorRT-7.0.0.11/include)
link_directories(/home/ss/TensorRT-7.0.0.11/lib)"

Here is the include and lib parts, hope it can help!
