### ISSUE TITLE
关于yolov5和yolov7 trt在Windows上的实现问题 - yolov5 and yolov7 trt implementation issue on Windows

### ISSUE THREAD

**Issue by parker-int64** [wang-xinyu/tensorrtx#1230]
## ENV:
+ GPU: RTX 3060
+ OS: Win 10 (22H2) + Visual Studio 2019 + CMake 3.24
+ CUDA: 11.3
+ TensroRT: 8.x

## General Questions

1. 无法打开包括文件: “dirent.h”: **No such file or directory**

+ Solution
[dirent.h](https://github.com/tronkko/dirent/blob/master/include/dirent.h) 下载Windows兼容dirent.h，添加进入项目文件中，在yolov5项目中，切换了CMakeLists.txt中的CUDA和TensorRT的安装目录信息，即可编译运行成功。

2. yolov7 **identifier 'kIgnoreThresh' is undefined in device code**  ，located in [config.h](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov7/include/config.h), line **31**

+ Solution
这个问题真的非常奇怪，其它变量都能够正常读取，就这个`kIgnoreThresh`显示没有定义在设备代码中。目前解决的方式是参照了[yolov5的config.h](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/src/config.h) line `40`， 将：

```C++
// The bboxes whose confidence is lower than kIgnoreThresh will be ignored in yololayer plugin.
const static float kIgnoreThresh = 0.1f;
```

更改为：

```C++
// The bboxes whose confidence is lower than kIgnoreThresh will be ignored in yololayer plugin.
constexpr static float kIgnoreThresh = 0.1f;
```

3. `std::min/std::max` conflict issue （STL中的min/max在windows上的冲突问题）

出现错误表现：
```
error C2589: '(' : illegal token on right side of '::'
error C2059: syntax error : '::'
```
追查到是opencv使用了stl中的min/max，导致冲突，编译无法通过

+ Solution
可以在头文件中添加`#define NOMINMAX`，解决问题

**Comment by haviduck** [comment]
thanks! what header file did you add NOMINMAX to?
