### ISSUE TITLE
segmentation default

### ISSUE THREAD

**Issue by Solitaryswan** [wang-xinyu/tensorrtx#1236]
在linux_aarch64上，我前面一切正常，但执行./yolov5 -d best.engine images的时候，跑到34张图片之后就报错segmentation default，你有遇见这种问题吗，我没有另外安装TensorRT是否有可能产生了影响

**Comment by wang-xinyu** [comment]
有可能是有图片损坏了，读取了一个空的cv mat，这里加判断试试 https://github.com/wang-xinyu/tensorrtx/blob/f92dcf43dcbe346c357edfa4cc976eb9d0d95470/yolov5/yolov5_det.cpp#L185
