### ISSUE TITLE
tensorrtx/resnet/resnet50.py  quantization to FP32, FP16, Int8

### ISSUE THREAD

**Issue by woonwoon** [wang-xinyu/tensorrtx#1239]
I want resnet50.wts quantization to fp32, fp16, int8 at resnet50.py. How do I modify resnet50.py to do each?

**Comment by wang-xinyu** [comment]
You can call the setFlag API to use fp16 or int8(int8 requires calibration). Here is a c++ code, you can find the corresponding python api in tensorrt doc.

https://github.com/wang-xinyu/tensorrtx/blob/f92dcf43dcbe346c357edfa4cc976eb9d0d95470/yolov5/src/model.cpp#L351

**Comment by woonwoon** [comment]
I just want to quantization resnet in classification problems for each data type(FP32, FP16, Int8). in python code https://github.com/wang-xinyu/tensorrtx/blob/master/resnet/resnet50.py

**Comment by wang-xinyu** [comment]
You need to call the config.setflag(FP16) API before calling build_engine(), the tensort build_engine() function will do the quantization internally.

https://github.com/wang-xinyu/tensorrtx/blob/f92dcf43dcbe346c357edfa4cc976eb9d0d95470/resnet/resnet50.py#L225

The .wts contains the FP32 weights, the tensort build_engine() function will do the quantization internally, you don't need to convert the weights by yourself, just need to setFlag.

**Comment by woonwoon** [comment]
Thanks to that, I converted it to float16. However, the conversion to int8 requires an calibration, but I don't know how to add it. I'd appreciate it if you could tell me.

**Comment by wang-xinyu** [comment]
TenosrRT INT8 PTQ requires calibration, it's a bit tricky to implement, you can refer to the yolov5 in this repo.

In addition to the setFlag(INT8), basically you need to implement a Calibration class. You can also check out the NVIDIA TensorRT doc for this.

**Comment by wang-xinyu** [comment]
Yes, it will use FP32 by default.

**Comment by woonwoon** [comment]
It's not quantized, is it?

**Comment by wang-xinyu** [comment]
It's not quantized
