### ISSUE TITLE
Deepstream integration

### ISSUE THREAD

**Issue by mfruhner** [wang-xinyu/tensorrtx#124]
Hello,
I am trying to make the Yolov5 run inside DeepStream in an Nvidia Jetson TX2.
So far I got your implementation working on the device, but now I want to use it with DeepStream to check the maximum performance.
When loading the engine, I get this error:

``INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1``

This makes sense, as TRT does not know about it. Do you know how i could (globally) register the libyololayer.so file?

Thanks!

**Comment by wang-xinyu** [comment]
can you try move  this line `REGISTER_TENSORRT_PLUGIN(YoloPluginCreator);` from yolov3.cpp to your own application?  or just move it to yololayer.h.

**Comment by mfruhner** [comment]
Wow, adding this line into yololayer.h did it! Thanks! Now I gotta figure out, how to parse the bboxes :)

**Comment by wang-xinyu** [comment]
nice.     you need do nms and decode the bboxes,   you can just reuse these codes in yolov5/common.hpp.

**Comment by hxk11111** [comment]
> Wow, adding this line into yololayer.h did it! Thanks! Now I gotta figure out, how to parse the bboxes :)

@mfruhner Have you integrated YOLO v5 to DeepStream? I'm working on it too. Could you please share some experience or source code?

Thanks

**Comment by yanivnahum** [comment]
> can you try move this line `REGISTER_TENSORRT_PLUGIN(YoloPluginCreator);` from yolov3.cpp to your own application? or just move it to yololayer.h.

Hi @wang-xinyu @mfruhner , 
I'm trying to use the yolov5s on Deepstream Xavier NV and getting:
`ERROR: [TRT]: INVALID_ARGUMENT: getPluginCreator could not find plugin HardSwishLayer_TRT version 1`

I can see the `REGISTER_TENSORRT_PLUGIN(HardSwishPluginCreator);` in hardswish.h

any idea how to solve it?
Thanks

**Comment by wang-xinyu** [comment]
@yanivnahum did you link the libmyplugins.so?

**Comment by mfruhner** [comment]
Hello,
I did not get any further as I was on holiday, but my last problem was to use two .so lib files into DeepStream at the same time. I need to do this to load the custom TRT-Layers and the BBox-Parser for DS. So far I dont know how to do this.
