### ISSUE TITLE
yolop.trt 无法生成

### ISSUE THREAD

**Issue by iceriver97** [wang-xinyu/tensorrtx#1240]
## Env

- GPU RTX2060.
- OS Ubuntu20.04.
- Cuda version 10.2
- TensorRT version 8.5.1.7

## About this repo

- which branch/tag/commit are you using?
-- master
- which model? yolov5, retinaface?
-- yolop

## Your problem

- what is your command? 
-- ./yolop -s yolop.wts yolop.trt
- what's your output?
-- `The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
Loading weights: yolop.wts
Building engine, please wait for a while...
2: [ltWrapper.cpp::setupHeuristic::349] Error Code 2: Internal Error (Assertion cublasStatus == CUBLAS_STATUS_SUCCESS failed. )
Build engine successfully!
段错误 (核心已转储)`
- what output do you expect?
-- 什么原因？实际并未得到 yolop.trt

**Comment by wang-xinyu** [comment]
TRT8.5支持CUDA 10.2吗？

**Comment by iceriver97** [comment]
> TRT8.5支持CUDA 10.2吗？

支持吧，相同环境下我试过 该项目的 yolov5 ，一切正常。

**Comment by wang-xinyu** [comment]
是否用的End-to-end模型？

**Comment by iceriver97** [comment]
> 是否用的End-to-end模型？

是的，gen_wts.py 相关代码如下：
```
YOLOP_BASE_DIR = "/home/ice/pytorch/YOLOP-main/"
sys.path.append(YOLOP_BASE_DIR)
from lib.models import get_net
from lib.config import cfg


# Initialize
device = torch.device('cpu')
# Load model
model = get_net(cfg)
checkpoint = torch.load(YOLOP_BASE_DIR + 'weights/End-to-end.pth', map_location=device)
model.load_state_dict(checkpoint['state_dict'])
```

**Comment by wang-xinyu** [comment]
试下TRT 8.2或者8.4吧

**Comment by iceriver97** [comment]
> 试下TRT 8.2或者8.4吧

8.4.1.5 , 8.2.1.8 两个版本 刚才都试过了，一样的问题。

**Comment by wang-xinyu** [comment]
@ausk 有遇到过这个问题吗？

**Comment by ausk** [comment]
jetson 上没问题：
TensorRT 8.0.1.6
cuDNN 8.2.1.31
CUDA 10.2.300

**Comment by iceriver97** [comment]
> jetson 上没问题： TensorRT 8.0.1.6 cuDNN 8.2.1.31 CUDA 10.2.300

刚才又试了 8.0.1.6，还是没有 trt 生成  :(
![test](https://user-images.githubusercontent.com/24710426/221122779-a63d4c3c-4f37-4ecd-ae48-a17265fb57ee.png)

**Comment by wang-xinyu** [comment]
执行ldd yolop看一下链接的so

**Comment by ausk** [comment]
@iceriver97 @wang-xinyu 不好意思，刚才贴的版本号有问题

**Comment by iceriver97** [comment]
> 执行ldd yolop看一下链接的so

```
libnvinfer.so.8 => /home/ice/TensorRT/TensorRT-8.5.1.7/lib/libnvinfer.so.8 (0x00007fb2ed60b000)
libcudart.so.10.2 => /usr/local/cuda-10.2/lib64/libcudart.so.10.2 (0x00007fb2ed38d000)
```

**Comment by wang-xinyu** [comment]
链接的是8.5的呀，编译和链接8.0的试试

**Comment by iceriver97** [comment]
> 链接的是8.5的呀，编译和链接8.0的试试

我在Cmakelists中指定的8.0，怎么改呢？

**Comment by ausk** [comment]
稍等我更新下代码，兼容下 tensorrt 8.

**Comment by wang-xinyu** [comment]
@ausk tensorrtx/yolop已经兼容8了，有其他人提的PR

**Comment by wang-xinyu** [comment]
@iceriver97 改环境变量LD_LIBRARY_PATH，把8.0的lib路径加进去，并删掉8.5的路径

**Comment by iceriver97** [comment]
> @iceriver97 改环境变量LD_LIBRARY_PATH，把8.0的lib路径加进去，并删掉8.5的路径

试过了，没有解决。
![test2](https://user-images.githubusercontent.com/24710426/221145922-35069691-8436-487b-8e2f-2c3747b319d4.png)

**Comment by ausk** [comment]
兼容 trt 8 后，可以编译通过，生成了文件：
-rwxrwxr-x 1 user user  54K 2月  24 17:27 libmyplugins.so
-rw-rw-r-- 1 user user 5.6K 2月  24 17:26 Makefile
-rwxrwxr-x 1 user user 102K 2月  24 17:27 yolop
-rw-rw-r-- 1 user user  23M 2月  24 17:38 yolop.trt
-rw-rw-r-- 1 user user  69M 2月  24 17:26 yolop.wts

**Comment by wang-xinyu** [comment]
那应该还是环境问题，先试试lenet吧

**Comment by iceriver97** [comment]
> 兼容 trt 8 后，可以编译通过，生成了文件： -rwxrwxr-x 1 user user 54K 2月 24 17:27 libmyplugins.so -rw-rw-r-- 1 user user 5.6K 2月 24 17:26 Makefile -rwxrwxr-x 1 user user 102K 2月 24 17:27 yolop -rw-rw-r-- 1 user user 23M 2月 24 17:38 yolop.trt -rw-rw-r-- 1 user user 69M 2月 24 17:26 yolop.wts
> 
> ![image](https://user-images.githubusercontent.com/4545060/221146967-f1df92a4-c829-46c9-a56d-bd4663303ce7.png)

这还是 jetson 吗？环境方便告知一下吗？

**Comment by ausk** [comment]
jetpack 4.6 默认环境

**Comment by iceriver97** [comment]
> jetpack 4.6 默认环境

TRT8.2 + CUDA10.2 + cuDNN 8.2 对吗？我刚才按照这个试了一下还是不行。
