### ISSUE TITLE
Error Retinaface --savemodel 

### ISSUE THREAD

**Issue by youngjae-avikus** [wang-xinyu/tensorrtx#1241]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc. [RTX3080]
- OS, e.g. Ubuntu16.04, Win10, etc. Ubuntu20
- Cuda version 11.6
- TensorRT version 8.2.2

## About this repo

- which branch/tag/commit are you using? master
- which model? yolov5, retinaface? retinaface

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

1. I downloaded the model.
2. proceeded with the following order.

```bash
Loading pretrained model from ./weights/Resnet50_Final.pth
remove prefix 'module.'
Missing keys:456
Unused checkpoint keys:267
Used keys:0
Traceback (most recent call last):
  File "detect.py", line 76, in <module>
    net = load_model(net, args.trained_model, args.cpu)
  File "detect.py", line 62, in load_model
    check_keys(model, pretrained_dict)
  File "detect.py", line 40, in check_keys
    assert len(used_pretrained_keys) > 0, 'load NONE from pretrained checkpoint'
AssertionError: load NONE from pretrained checkpoint
```

**Comment by wang-xinyu** [comment]
Were you using my fork https://github.com/wang-xinyu/Pytorch_Retinaface ?

**Comment by youngjae-avikus** [comment]
@wang-xinyu 
Yes. Would you like to try again?

**Comment by wang-xinyu** [comment]
What's your pytorch version? Can you try 1.3 or 1.2?

**Comment by youngjae-avikus** [comment]
@wang-xinyu 

I'm currently using **torch >1.10**. I don't think it's possible to lower the version because of the cuda compatibility, is it?

**Comment by wang-xinyu** [comment]
You can install the cpuonly pytorch 1.3 and run the detect.py.

**Comment by youngjae-avikus** [comment]
@wang-xinyu 

I think you're right in the context. Thank you.
