### ISSUE TITLE
When is the yolov8 trt ？

### ISSUE THREAD

**Issue by ZhuJD-China** [wang-xinyu/tensorrtx#1242]
thank you！

**Comment by wang-xinyu** [comment]
有人愿意尝试实现可加我微信交流，可提供指导

**Comment by aniu-du** [comment]
之前在项目上融合过大佬的ufld和yolov4-tiny的代码，我可以试一试嘛

**Comment by BryceWayne** [comment]
I would really appreciate a yolov8 version that works on Jetson nano

**Comment by wang-xinyu** [comment]
Yolov8 is already there.

**Comment by ZhuJD-China** [comment]
> Yolov8 is already there.Yolov8 已经在那里了。

Thank you！
