### ISSUE TITLE
Implementing explicit batch in YOLOv5 

### ISSUE THREAD

**Issue by Shassk** [wang-xinyu/tensorrtx#1246]
Hi everyone.

I'm trying to implement explicit batch in YOLOv5 from this repo to move away from deprecated calls to things like `enqueueV3`, and 
I've figured out runtime stuff, but not what changes I have to implement to actual layers during network+plugin building process. Clearly different dimensions are needed, but where and which ones exactly?

Any help or hint is appreciated.

**Comment by ttdd11** [comment]
Second that!

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/search?q=kEXPLICIT_BATCH

There are 3 models in this repo which is using explicit batch.

For the yololayer plugin, it will be a bit tricky to adapt. You can refer to the plugin of yolov3-spp
