### ISSUE TITLE
[Error] Not Saved in np shape semantic (gen_wts.py)

### ISSUE THREAD

**Issue by cloudlakecho** [wang-xinyu/tensorrtx#1247]
Hello;

Thanks for sharing the code for converting neural network weight. 

My error is related to [ArcFace](https://github.com/wang-xinyu/tensorrtx/tree/master/arcface#run)
I am having error when I try to generate "arcface-r100.wts" file by `python gen_wts.py` with "model-r100-ii.zip" file My guess of the error is different dependent tool version, especially MXNet.  Here is details of my runtime environment and error. 
 
## Env

- GPU: Nvidia AGX Orin (Arm (AArch64) processor)
- OS: Ubuntu 20.04
- Cuda version: 11.4
- TensorRT version: ? 

## About this repo

- which branch/tag/commit are you using?
866cd77a6896c934b51ed39e9651b791d78bb57 (master branch currently not working) [ref](https://github.com/wang-xinyu/tensorrtx/tree/master/arcface#run)
- which model? ArcFace

## Problem

- what is your command? `python gen_wts.py`
- what's your output?
```

(.venv_3_8) isi@D-003:~/project/insightface/deploy$ python gen_wts.py 
loading model-r100-ii/model 0
[16:57:30] /home/isi/project/mxnet/src/nnvm/legacy_json_util.cc:211: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
[16:57:30] /home/isi/project/mxnet/src/nnvm/legacy_json_util.cc:220: Symbol successfully upgraded!
> /home/isi/project/mxnet/python/mxnet/ndarray/utils.py(176)load()
-> handles = ctypes.POINTER(NDArrayHandle)()
(Pdb) c
Traceback (most recent call last):
  File "gen_wts.py", line 19, in <module>
    model = face_model.FaceModel(args)
  File "/home/isi/project/insightface/deploy/face_model.py", line 53, in __init__
    self.model = get_model(ctx, image_size, args.model, 'fc1')
  File "/home/isi/project/insightface/deploy/face_model.py", line 34, in get_model
    sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
  File "/home/isi/project/mxnet/python/mxnet/model.py", line 263, in load_checkpoint
    arg_params, aux_params = load_params(prefix, epoch)
  File "/home/isi/project/mxnet/python/mxnet/model.py", line 224, in load_params
    save_dict = nd.load(f'{prefix}-{epoch:04}.params')
  File "/home/isi/project/mxnet/python/mxnet/ndarray/utils.py", line 176, in load
    handles = ctypes.POINTER(NDArrayHandle)()
  File "/home/isi/project/mxnet/python/mxnet/base.py", line 253, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "/home/isi/project/mxnet/src/ndarray/ndarray.cc", line 2009
MXNetError: Check failed: Imperative: :Get()->is_np_shape() == GlobalOn || !Imperative::Get()->is_np_shape(): ndarray was not saved in np shape semantics, but being loaded in np shape semantics. Please turn off np shape semantics in Python using `with np_shape(False)` to scope the code of loading the ndarray.
```
- what output do you expect?
I expect generation of 'arcface-r100.wts' from pre trained weight, "model-r100-ii.zip"

It looks like suggestion in InsigtFace is MXNet 1.6 ~ 1.8. Should I try again or is there go around?
&nbsp;&nbsp; (ref: [similar problem in MXNet](https://github.com/apache/mxnet/issues/18121) and [InsightFace suggestion](https://github.com/deepinsight/insightface#introduction))

The error message mentioned running the code with  "with np_shape(False)", but I couldn't find how to do that. 

My runtime environment:
&nbsp;&nbsp; Python 3.8
&nbsp;&nbsp; MXNet 2.0.0 (I built from the source because of Arm processor)
&nbsp;&nbsp; Numpy 1.23.0

**Comment by wang-xinyu** [comment]
You can install CPU-only mxnet in your x86 machine. There is no need to run gen_wts on the Jetson.

And use the same version of Mxnet as this commit of insightface:
```
git clone https://github.com/deepinsight/insightface
cd insightface
git checkout 3866cd77a6896c934b51ed39e9651b791d78bb57
```

**Comment by cloudlakecho** [comment]
@wang-xinyu Thanks for the suggestion. 

I have one question before I try it in x86_64. 

I plan to continue following [the step 2](https://github.com/wang-xinyu/tensorrtx/tree/master/arcface#run). The suggestion from the other programmer is that I have to the step 1 and step 2 in my target hardware, Arm. (I am having an error loading the 'arcface-r100.engine' in Jetson ([ref](https://github.com/zhouyuchong/face-recognition-deepstream#pretrained)). This is the reason that I was doing the step 1 in Arm processor)  Will the generated "arcface-r100.wts" file could work for the step 2 in different hardware? 

Or do you think I could still do the step 2 at x86_64 (and load the ENGINE at Jetson)?

**Comment by wang-xinyu** [comment]
Step1 can run on x86, because .wts file is portable.
Step2 must on target hardware, .engine is not portable.

**Comment by cloudlakecho** [comment]
@wang-xinyu Thanks for the guide. I will try the step 1 in x86_64 if I fails again. 

I just built MXNet 1.8 from the source in Arm processor, so I will try the step 1 at that platform.
