### ISSUE TITLE
arcface gen wts param --det

### ISSUE THREAD

**Issue by youngjae-avikus** [wang-xinyu/tensorrtx#1248]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc. //////// RTX3080
- OS, e.g. Ubuntu16.04, Win10, etc. //////// Ubuntu 20.04
- Cuda version 
- TensorRT version ///////// 8.2.2-1+cuda11.4

## About this repo

- which branch/tag/commit are you using? //////// metioned at arcface README // **insightface** 3866cd77a6896c934b51ed39e9651b791d78bb57 // **tensorrtx** master
- which model? yolov5, retinaface?//////// arcface

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

hi, I have a question about the process of making wts in arcface.
If look at the --det in the args option, it looks like face detecting with mtcnn.
By the way, I'm going to input cropped faces that have already been detected by arcface input.
If I want to exclude mtcnn detection, I'm leaving it because I'm curious about what process is right.

**Comment by wang-xinyu** [comment]
The gen_wts.py only needs to get the weights of arcface model, and the final .wts file only contains arcface weight, there is no mtcnn.

And in the cpp code, there is no detection. The input image is a cropped face.
