### ISSUE TITLE
[CMakeFiles/yololayer.dir/build.make:369: CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o

### ISSUE THREAD

**Issue by SwordSing** [wang-xinyu/tensorrtx#125]
Hi，今天我试着编译一下yolov5的tensorrt部署，出现的如题的错误，我本人不擅长c++所以没能排除整个错误，如果可以的话希望您能提供一些建议。

[ 25%] Building NVCC (Device) object CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o
/usr/include/c++/10.1.0/type_traits(1396): error: type name is not allowed

/usr/include/c++/10.1.0/type_traits(1396): error: type name is not allowed

/usr/include/c++/10.1.0/type_traits(1396): error: identifier "__is_same_as" is undefined

/home/swing/Documents/tensorrtx/yolov5/yololayer.h(103): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

/home/swing/Documents/tensorrtx/yolov5/utils.h(45): error: no instance of overloaded function "std::vector<_Tp, _Alloc>::push_back [with _Tp=Tn::Profiler::Record, _Alloc=std::allocator<Tn::Profiler::Record>]" matches the argument list
            argument types are: (std::pair<const char *, float>)
            object type is: std::vector<Tn::Profiler::Record, std::allocator<Tn::Profiler::Record>>

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=char, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6547): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6552): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6557): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6562): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6567): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=char, _Base=<>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6573): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=char, _Base=<>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6577): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=char, _Base=<>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6581): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6678): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6683): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6688): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6693): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6698): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6704): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6708): here

/usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/10.1.0/bits/basic_string.h(6712): here

20 errors detected in the compilation of "/tmp/tmpxft_00002bad_00000000-6_yololayer.cpp1.ii".
CMake Error at yololayer_generated_yololayer.cu.o.Debug.cmake:280 (message):
  Error generating file
  /home/swing/Documents/tensorrtx/yolov5/cmake-build-debug/CMakeFiles/yololayer.dir//./yololayer_generated_yololayer.cu.o

make[3]: *** [CMakeFiles/yololayer.dir/build.make:369: CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:124: CMakeFiles/yololayer.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/yolov5.dir/rule] Error 2
make: *** [Makefile:138: yolov5] Error 2

环境如下：
Tensorrt 7.1
Cuda 10.2
GCC 8.4

**Comment by wang-xinyu** [comment]
系统是什么？

**Comment by SwordSing** [comment]
系统是manjaro linux

**Comment by wang-xinyu** [comment]
。。。是我没见识了，没听过这个系统。

cuda支持这个系统吗？写个cuda测试程序能编译通过吗

**Comment by SwordSing** [comment]
测试了tensorrt的sample是可以的

**Comment by wang-xinyu** [comment]
可能是cuda nvcc编译的问题，可以先找一个简单的cuda代码，编译下试试，确保cuda nvcc可以用

**Comment by SwordSing** [comment]
好的 谢谢 我试试

**Comment by FlyingAnt2018** [comment]
> 好的 谢谢 我试试

请问您解决了吗？

**Comment by FlyingAnt2018** [comment]
> Hi，今天我试着编译一下yolov5的tensorrt部署，出现的如题的错误，我本人不擅长c++所以没能排除整个错误，如果可以的话希望您能提供一些建议。
> 
> [ 25%] Building NVCC (Device) object CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o /usr/include/c++/10.1.0/type_traits(1396): error: type name is not allowed
> 
> /usr/include/c++/10.1.0/type_traits(1396): error: type name is not allowed
> 
> /usr/include/c++/10.1.0/type_traits(1396): error: identifier "__is_same_as" is undefined
> 
> /home/swing/Documents/tensorrtx/yolov5/yololayer.h(103): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?
> 
> /home/swing/Documents/tensorrtx/yolov5/utils.h(45): error: no instance of overloaded function "std::vector<_Tp, _Alloc>::push_back [with _Tp=Tn::Profiler::Record, _Alloc=std::allocatorTn::Profiler::Record]" matches the argument list argument types are: (std::pair<const char *, float>) object type is: std::vector<Tn::Profiler::Record, std::allocatorTn::Profiler::Record>
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long, std::is_same<int, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=char, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6547): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long, std::is_same<long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=char, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6552): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const unsigned long, std::is_same<unsigned long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=char, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6557): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long long, std::is_same<long long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=char, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6562): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const unsigned long long, std::is_same<unsigned long long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=char, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6567): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const float, std::is_same<float, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=char, _Base=<>]" /usr/include/c++/10.1.0/bits/basic_string.h(6573): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const double, std::is_same<double, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=char, _Base=<>]" /usr/include/c++/10.1.0/bits/basic_string.h(6577): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long double, std::is_same<long double, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=char, _Base=<>]" /usr/include/c++/10.1.0/bits/basic_string.h(6581): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long, std::is_same<int, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=wchar_t, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6678): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long, std::is_same<long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=wchar_t, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6683): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const unsigned long, std::is_same<unsigned long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=wchar_t, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6688): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long long, std::is_same<long long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=wchar_t, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6693): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const unsigned long long, std::is_same<unsigned long long, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=wchar_t, _Base=]" /usr/include/c++/10.1.0/bits/basic_string.h(6698): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const float, std::is_same<float, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=wchar_t, _Base=<>]" /usr/include/c++/10.1.0/bits/basic_string.h(6704): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const double, std::is_same<double, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=wchar_t, _Base=<>]" /usr/include/c++/10.1.0/bits/basic_string.h(6708): here
> 
> /usr/include/c++/10.1.0/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list argument types are: (const long double, std::is_same<long double, int>) detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=wchar_t, _Base=<>]" /usr/include/c++/10.1.0/bits/basic_string.h(6712): here
> 
> 20 errors detected in the compilation of "/tmp/tmpxft_00002bad_00000000-6_yololayer.cpp1.ii". CMake Error at yololayer_generated_yololayer.cu.o.Debug.cmake:280 (message): Error generating file /home/swing/Documents/tensorrtx/yolov5/cmake-build-debug/CMakeFiles/yololayer.dir//./yololayer_generated_yololayer.cu.o
> 
> make[3]: *** [CMakeFiles/yololayer.dir/build.make:369: CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o] Error 1 make[2]: *** [CMakeFiles/Makefile2:124: CMakeFiles/yololayer.dir/all] Error 2 make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/yolov5.dir/rule] Error 2 make: *** [Makefile:138: yolov5] Error 2
> 
> 环境如下： Tensorrt 7.1 Cuda 10.2 GCC 8.4



> 。。。是我没见识了，没听过这个系统。
> 
> cuda支持这个系统吗？写个cuda测试程序能编译通过吗

我用ubuntu的官方docker也遇到了这个问题，c++的重写不就是这样的吗？》
