### ISSUE TITLE
yolov7-tiny.yaml中更改depth_multiple和width_multiple后生成engine文件的过程中报错，应该如何更改呢

### ISSUE THREAD

**Issue by hellosuer** [wang-xinyu/tensorrtx#1250]
![微信图片_20230301163205](https://user-images.githubusercontent.com/110160797/222085850-6f6aa4d2-c99b-4f36-a2bd-524365260476.jpg)
报错如上所示，请问需要更改什么配置吗，谢谢

**Comment by wang-xinyu** [comment]
操作过程再描述细一些，最好按照issue模板

**Comment by hellosuer** [comment]
ENV:
GPU: NVIDIA Ampere架构
OS: Nvidia Jetson Orin + Cmake3.16.3
CUDA: 11.4
TensroRT: 8.4.0.11
General Questions
在训练过程中更改了yolov7-tiny.yaml中depth_multiple和width_multiple，将其均改为了0.8
![1](https://user-images.githubusercontent.com/110160797/222091474-be3a68d5-a95f-47e7-aab8-15eb3f43d278.jpg)
然后生成wts文件以及编译过程均正确，在执行sudo ./yolov7 -s yolov7.wts yolov7.engine t后出现如下错误
![2](https://user-images.githubusercontent.com/110160797/222091786-1b394667-b04e-4ff4-9013-c6940947f6ca.jpg)
想请问需要更改其他参数吗，谢谢您

**Comment by wang-xinyu** [comment]
修改模型结构之后，不能直接转换engine，需要改这个函数里面的网络结构定义，https://github.com/wang-xinyu/tensorrtx/blob/ef22b1d03bd2b210fd84f3c7e1db9752d978f599/yolov7/src/model.cpp#L1775

**Comment by wang-xinyu** [comment]
另外，目前只支持cfg/deploy目录下的yaml文件，如果用cfg/train下面的模型训练，暂不支持
