### ISSUE TITLE
Segmentation fault (core dumped)， ./yolov5_det -s ../yolov5s.wts ../yolov5s.engine s

### ISSUE THREAD

**Issue by linClubs** [wang-xinyu/tensorrtx#1251]
Hi，
i run ./yolov5_det -s ../yolov5s.wts ../yolov5s.engine s with FP16 and INT8 ,

Loading weights: ../yolov5s.wts
Building engine, please wait for a while...
[03/01/2023-17:25:30] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.5.1
Segmentation fault (core dumped)

but FP32
Loading weights: ../yolov5s.wts
Building engine, please wait for a while...
[03/01/2023-17:28:57] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.5.1
[03/01/2023-17:29:37] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.3 but loaded cuBLAS/cuBLAS LT 11.5.1
Build engine successfully!

how can i use FP16 and INT8  successfully？
Thanks

**Comment by wang-xinyu** [comment]
Does your GPU support FP16？

**Comment by h904798869** [comment]
> Does your GPU support FP16？
我不确定是否支持FP16. 我显卡是3060TI，我还有一个问题，就是我用FP32检测，
./yolov5_det -d ../yolov5s.engine ../image/

效果很差

**Comment by h904798869** [comment]
![_1](https://user-images.githubusercontent.com/62087085/222102883-4998cb45-888a-4c07-aec2-548e2bd90a9b.png)

**Comment by h904798869** [comment]
不知道哪里出了问题，这检测结果。咦

**Comment by wang-xinyu** [comment]
先按照readme试一下官方模型，版本要匹配

**Comment by h904798869** [comment]
就是官方的readme操作，我用v7.0分支，代码只改了#define USE_FP16这句，16报错。改成32了。
![d40c561158b0337c8bafabf81b3ecc22](https://user-images.githubusercontent.com/62087085/222106415-9540eb4d-6521-4219-9740-d4231f7ed587.png)

这是测试VOC里面部分图片，也是这个效果

**Comment by wang-xinyu** [comment]
是这个吗 https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt

**Comment by h904798869** [comment]
您好，问题已经解决了，应该是cnda，cudnn，tensorrt版本不匹配导致，我昨天用FP16未通过，用FP32通过了，但是FP32的检测效果不能用，今天把cuda换成11.3.0，cudnn8.6.0 ，TensorRT-8.2.1.8，FP16，FP32都通过了。并且检测结果跟原ultralytics/yolov5-v7.0差不多。不过INT8运行报错了，可能是显卡不支持，目前还未解决。不过能用了。谢谢大佬开源的项目

**Comment by h904798869** [comment]
这是FP16效果，速度贼快
![0e09b91236e3004876dbca2b7554e0a6](https://user-images.githubusercontent.com/62087085/222354402-eaa33ab0-49db-47ab-9908-314bbd1b4e02.png)

**Comment by wang-xinyu** [comment]
INT8需要calibration，readme中有说明

**Comment by wxinbeings** [comment]
> 

遇到同样的问题，我使用的是cuda-11.4，tensorrt-8.2.3.0，cudnn-8.4.0和cudnn-8.2.4都不行，这些版本应该都是可以兼容的呀，看来只能多测试一下了

**Comment by h904798869** [comment]
> > 
> 
> 遇到同样的问题，我使用的是cuda-11.4，tensorrt-8.2.3.0，cudnn-8.4.0和cudnn-8.2.4都不行，这些版本应该都是可以兼容的呀，看来只能多测试一下了

你遇到啥问题了

**Comment by h904798869** [comment]
作者您好，目前遇到了一个新问题，我在使用分割时，使用自己的数据集，类别小于80类，采用usb免驱摄像头连续读取视频流进行分割，程序跑着跑着，再某一帧就出现了段错误，可能是数组越界了，在使用自己数据集，并连续视频流操作时，需要注意啥

**Comment by zeng121** [comment]
@h904798869 你好 我用的是WSL-Ubuntu20.04 也遇到了相同的问题 推理结果不对 有很多框

**Comment by h904798869** [comment]
@zeng121 把cuda换成11.3.0，cudnn8.6.0 ，TensorRT-8.2.1.8，我用这个环境没有问题

**Comment by TempleLordAnubies** [comment]
> @h904798869 你好 我用的是WSL-Ubuntu20.04 也遇到了相同的问题 推理结果不对 有很多框

我在wsl-ubuntu18.04上使用题主所说的cuda11.3.0，cudnn8.6.0 ，TensorRT-8.2.1.8，也遇到了这个问题，而去安装正常的linux x86_64的cuda11.3.0是无法安装到wsl上的，感觉应该是wsl版本的cuda和cudnn以及tensorrt本身就有兼容性问题

**Comment by TempleLordAnubies** [comment]
> > @h904798869 你好 我用的是WSL-Ubuntu20.04 也遇到了相同的问题 推理结果不对 有很多框
> 
> 我在wsl-ubuntu18.04上使用题主所说的cuda11.3.0，cudnn8.6.0 ，TensorRT-8.2.1.8，也遇到了这个问题，而去安装正常的linux x86_64的cuda11.3.0是无法安装到wsl上的，感觉应该是wsl版本的cuda和cudnn以及tensorrt本身就有兼容性问题

我在使用2个屏幕时，运行wts转engine操作的话会很快爆出Segmentation fault的问题，但在使用一个屏幕时并不会立马报错，而是卡住很长时间并且无法结束进程，只能关闭wsl
