### ISSUE TITLE
Yolov5 preprocess.cu use a custom cuda WarpAffineKernel function instead of openCV cv::cuda::warpAffine?

### ISSUE THREAD

**Issue by ervgan** [wang-xinyu/tensorrtx#1255]
## Question

HI ! I wanted to know why you used a custom warpAffineKernel cuda instead of the cv::cuda::warpAffine function from openCV in the preprocess.cu file for yolov5? I couldn't find the code for the opencv warpAffine function but is there an extra layer of customization in your implementation?

Thanks!

**Comment by wang-xinyu** [comment]
warpAffine is only for resize the image, the preprocess.cu also includes BGR2RGB, normalize and HWC2CHW.

**Comment by ervgan** [comment]
Oh I see, thanks!
