### ISSUE TITLE
tensorrtx rcnn inference get no result on windows(cuda11.6+tensorrt8.5+opencv4.6.0+windows10)

### ISSUE THREAD

**Issue by konstiantyn** [wang-xinyu/tensorrtx#1257]
## Env

- GPU GTX 1070.
- OS, Win10.
- Cuda version 11.6
- TensorRT version 8.5

## About this repo

- which branch/tag/commit are you using?
   main
- which model? 
  rcnn

## Your problem
I tried rcnn on this link
https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn
so build it on visual studio 2022 on windows 10 and tried run it.
rcnn.exe -s mask.wts mask.engine m
rcnn.exe -d mask.engine images m
To do this, I used this model.
https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x/137259246/model_final_9243eb.pkl
And change configuration on gen_wts.py file.
./configs/COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x.yaml
And run gen_wts.py for generate wts(weight file) from model_final_9243eb.pkl.
![image](https://user-images.githubusercontent.com/33037366/223140449-aef93309-a7a6-4591-894d-1ca218e0aca5.png)

And on c++ code, set BACKBONE_RESNETTYPE = R50(R101) rcnn.cpp line 14, set STRIDE_IN_1X1=true in backbone.hpp

After that, i  tried run rcnn.exe with -s paramter , and make mask.engine file.
![image](https://user-images.githubusercontent.com/33037366/223140677-c75ee27d-fff2-4122-a1f7-e3846df7d15a.png)

finally i tested this mask.engine with sample images on visual studio.
![image](https://user-images.githubusercontent.com/33037366/223140833-47af0bc5-f37f-4f3c-91f9-e50f49db3ab2.png)

but the result is no.
No object detected on result image, only shows time for inference with that engine for images.

I followed github's readme, but no result get.
what is problem? please help me.

**Comment by wang-xinyu** [comment]
Were you testing on this PR https://github.com/wang-xinyu/tensorrtx/pull/1256? Because the master branch might not support TRT 8.

**Comment by konstiantyn** [comment]
> Were you testing on this PR #1256? Because the master branch might not support TRT 8.

Yes. I was tested this PR

**Comment by wang-xinyu** [comment]
@nengwp Can you please take a look?

**Comment by nengwp** [comment]
@konstiantyn Your program looks normally. The problem that causes such a problem may be that you have not entered the image path correctly (I did not see the Images folder on your screenshot), please make sure the folder and its image file exist. In addition, you should use a picture in a similar COCO dataset as a test to avoid failure to detect the target.

**Comment by nengwp** [comment]
@konstiantyn 
![image](https://user-images.githubusercontent.com/44516353/223346581-c209262b-226b-4c33-873e-df2c775b0b21.png)

This PR maskrcnn  works fine on my machine, and I'm comfortable with linux, not windows

**Comment by nengwp** [comment]
There are some errors in this code, which may be caused by failed plugin loading. The error messages indicate that there were issues when attempting to load three parallel backends (ONETBB, OPENMP). Specifically, loading dynamic link libraries named "opencv_core parallel onetbb460 64d.dll", "opencv_core parallel tbb460 64d.dll", and "opencv_core parallel openmp460 64d.dll" all failed. This may be due to the fact that these library files do not exist or cannot be loaded. It is necessary to check whether the file paths are correct and ensure that these library files can be found and loaded in the system.
    
    check you opencv！！！

**Comment by konstiantyn** [comment]
@nengwp 
Thank you for your reply.
But I'm not sure how to fix openCV.
 And I saw your picture, Tensorrt linked cuBLAS
 Should be link with cuBLAS?

**Comment by nengwp** [comment]
@konstiantyn 
Trying Docker is a good choice.

**Comment by konstiantyn** [comment]
Yes. I know, But I'm going to use it on offline mode. So I need to build

**Comment by nengwp** [comment]
@konstiantyn 
This may help you[ docker opencv insatll  ](https://github.com/wang-xinyu/tensorrtx/tree/master/doc)

**Comment by konstiantyn** [comment]
@nengwp 
Thank you. it works.
