### ISSUE TITLE
./yolov5_det -s yolov5s6.wts yolov5s6.engine s

### ISSUE THREAD

**Issue by Kayce001** [wang-xinyu/tensorrtx#1258]
## Env

- GPU RTX3090TI
- OS, Ubuntu20.04
- Cuda version 11.3
- TensorRT version 7.2.3

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5 V6.0

## Your problem

- what is your command? ./yolov5_det -s yolov5s6.wts yolov5s6.engine s
- what's your output?   [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::484, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5_det: /home/tensorrtx/yolov5/src/model.cpp:95: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::string, float): Assertion `scale_1' failed.
- what output do you expect?  successfully create yolovs6.engine.

**Comment by wang-xinyu** [comment]
The cmd should be

./yolov5_det -s yolov5s6.wts yolov5s6.engine s6

**Comment by Kayce001** [comment]
> The cmd should be
> 
> ./yolov5_det -s yolov5s6.wts yolov5s6.engine s6

when i run this cmd,error happened.

/home/tensorrtx/yolov5/src/model.cpp:257: nvinfer1::IPluginV2Layer* addYoLoLayer(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, std::string, std::vector<nvinfer1::IConvolutionLayer*>, bool): Assertion `weightMap.find(lname + ".strides") != weightMap.end() && "Not found `strides`, please check gen_wts.py!!!"' failed.
Aborted (core dumped)

**Comment by wang-xinyu** [comment]
can you re-run the gen_wts with the newest gen_wts.py?

**Comment by Kayce001** [comment]
> can you re-run the gen_wts with the newest gen_wts.py?

thanks, it work.
