### ISSUE TITLE
No detections with yolov5 on Tesla K80, other hardware works ok

### ISSUE THREAD

**Issue by Shassk** [wang-xinyu/tensorrtx#1260]
## Env

- Nvidia Tesla K80
- Ubuntu 18.04
- CUDA 11.4
- TensorRT 8.2.3

## About this repo

Latest release with custom yolov5n model (limited to 1 class).

## Your problem

- Commands were used from the instruction: `./yolov5 -s custom-model.wts custom-model.engine && ./yolov5 -d custom-model.engine ./input-images-dir`
- All output images had no detections despite the code and models working just fine on Jetson Nano (Ubuntu 18.04/CUDA 10.2/TRT 8.2.2) and GTX 1070 (Win8.1x64/CUDA 11.4/TRT 8.5.2).
- Tried building and running tensorrtx on K80 in Windows (same PC, different OS) - no detections again.
- Tried those models on K80 using CUDA-enabled OpenCV dnn module (so no layer plugin obviously) - works fine.
- Older yolov3 models without layer plugin work fine as well.

Our guess so far it might have something to do with a combination of yolo layer plugin and CUDA architectures: K80 has 3.7 while the other two have 5.3 and 6.1 respectively.

**Comment by wang-xinyu** [comment]
You can try to specify the CUDA architectures in the cmakelist, to see if that work.

**Comment by Shassk** [comment]
Got
```
Manually-specified variables were not used by the project:
	CMAKE_CUDA_ARCHITECTURES
```
with no changes.

**Comment by cqzw555** [comment]
I am also facing the same issue where yolov5_det is not giving any detection results using the offical weight 'yolov5s.pt'.

**Comment by cqzw555** [comment]
I just updated my drivers and installed all available updates. My CUDA version is 5.3.0, CUDA 12.1, and TensorRT 8.5.3.1. After recompiling and running the program again, I was able to obtain results.
