### ISSUE TITLE
yolov7 to tensorRT conversion error : opencv2/dnn/dnn.hpp: No such file or directory

### ISSUE THREAD

**Issue by Nuwan1654** [wang-xinyu/tensorrtx#1264]
## Env

- GPU: Jetson AGX Orin GPU
- OS:  Ubuntu 20.04
- Cuda version: 11.4
- TensorRT version : 8.5

## About this repo

- which branch/tag/commit are you using? main
- which model?  yolov7 with the custom dataset 

## Your problem

when `make` got the following error
```
/tensorrtx/yolov7/src/calibrator.cpp:4:10: fatal error: opencv2/dnn/dnn.hpp: No such file or directory
    4 | #include <opencv2/dnn/dnn.hpp>
```
here the error seems to come from an int8 calibration-related script,  but don't know why, I just need fp16. I did this conversion a few months ago then It worked without an error, seems like there are new changes to the repo.

**Comment by wang-xinyu** [comment]
You can remove the dependency of calibrator.h, which is only required by int8.

**Comment by Nuwan1654** [comment]
Thanks for the reply, actually it was an issue with my opencv installation,
