### ISSUE TITLE
Error in `./yolov5_det': free(): invalid pointer

### ISSUE THREAD

**Issue by songyn95** [wang-xinyu/tensorrtx#1269]
## Env

- GPU: Tesla P4
- OS: centos8.
- Cuda version: 10.2
- TensorRT version:7.0.0.11

## About this repo

- [tensorrtx/yolov5-v7.0](https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v7.0/yolov5)
- yolov5s.pt

## Your problem

- ./yolov5_det -s yolov5s.wts yolov5s.engine s
```
 Build engine successfully!
 *** Error in `./yolov5_det': free(): invalid pointer: 0x0000000000642c10 ***
 ======= Backtrace: =========
00400000-00442000 r-xp 00000000 08:10 283656242                              /data1/tensorrtx/yolov5/build/yolov5_det
...
Aborted
```

**Comment by SherlockHolmes221** [comment]
same problems, how to solve? thanks
