### ISSUE TITLE
yolov7模型.wts生成.engine失败

### ISSUE THREAD

**Issue by Eric-Liu-1118** [wang-xinyu/tensorrtx#1271]
## Env

- GPU:jetson nano.
- OS:ubuntu 18.04
- Cuda:10.2.300
- TensorRT:8.1.2.8
- jetpack:4.6.3

## About this repo

- model:yolov7

## Your problem
在利用.wts生成..engine文件过程中，出现以下错误：
yolov7: /home/eric/tensorrtx-master/yolov7/main.cpp:38: void serialize_engine(unsigned int, std::__cxx11::string&, std::__cxx11::string&, std::__cxx11::string&): Assertion `serialized_engine != nullptr' failed.

利用自己的数据利用yolov7训练出.pt文件，后生成.wts文件，根据网络教程，在生成.engine之前需要根据自己训练的模型更改 yololayer.h 中的static constexpr int CLASS_NUM = 80的数值，但我在目录中并未找到yololayer.h文件对应的代码，随后发现在include/config.h文件下，有const static int kNumClass = 80 的代码，遂将此改为自己模型检测的数量，但在执行sudo ./yolov7 -s yolov7.wts yolov7.engine s后出现上述错误，我想请教以下，改如何解决这个问题

**Comment by GuanLong-Zhang** [comment]
同样的问题main.cpp:38: void serialize_engine(unsigned int, std::__cxx11::string&, std::__cxx11::string&, std::__cxx11::string&): Assertion `serialized_engine != nullptr' failed.

**Comment by GuanLong-Zhang** [comment]
是最后的命令不对，需要根据新的要求输入命令。 sudo ./yolov7 -s yolov7.wts yolov7.engine v7
