### ISSUE TITLE
warpaffine_kernel func behavior when Src, Dst sizes are different

### ISSUE THREAD

**Issue by youngjae-avikus** [wang-xinyu/tensorrtx#1273]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface? **yolov5**

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

Hi. My opinion is that in the warpaffine function, dst is the final image size, so it should be the same as the TensorRT model
But if I have an image (1920x1080), I crop it to 256x256, and then I put it in the warpaffine function as Src size=256, dst=640 and it works, but the result seems weird. Can I not use it like this?

https://github.com/wang-xinyu/tensorrtx/blob/f2521a5ffa9b614c4975415224bb901fe6da94e6/yolov7/src/preprocess.cu#L11-L93

**Comment by wang-xinyu** [comment]
Why do you need to crop the image? What is the background?
