### ISSUE TITLE
yolov5-v7.0版本生成wts文件和tensorrt模型存在问题

### ISSUE THREAD

**Issue by songyn95** [wang-xinyu/tensorrtx#1281]
## Env

- GPU： p4
- OS: centos8.
- Cuda version: cuda10.2
- TensorRT version:7.0.0.11

## About this repo

-  yolov5-v7.0
- yolov5s.pt

## Your problem

- `./yolov5_det -s yolov5s.wts yolov5s.engine s`
-  ```  Build engine successfully!   Error in `./yolov5_det': free(): invalid pointer: 0x0000000000642c10```

- 经过验证，我在yolov5 v7.0版本出现此问题；在v6.2版本成功运行

**Comment by wang-xinyu** [comment]
yolov5 v7.0不确定TensorRT version:7.0.0.11是否能work，可以试下TensorRT8.0+
