### ISSUE TITLE
How to quantization to FP16 in YoloV7?

### ISSUE THREAD

**Issue by ZefangYuan** [wang-xinyu/tensorrtx#1282]
I am testing on JetsonNano. I don't know how to change to FP16. Should I change some code to generate a different .wts file?

**Comment by wang-xinyu** [comment]
By default, it is using fp16.
https://github.com/wang-xinyu/tensorrtx/blob/877bb24389f2adafa78d9eeb948bd8b5221bcd5b/yolov7/include/config.h#L10
