### ISSUE TITLE
The acceleration inference results of real-esrgan are problematic.

### ISSUE THREAD

**Issue by awesomecq** [wang-xinyu/tensorrtx#1284]
## Env

- GPU, RTX1650
- OS, Win10
- Cuda version 11.6
- TensorRT version 8.4.1.5

## About this repo

- which branch/tag/commit are you using?
- which model? real-esrgan

## Your problem

I am using TensorRT to accelerate real-esrgan, but the output image is black during inference. Additionally, the following warning is displayed: “[04/17/2023-04:43:06] [W] [TRT] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.4.0”. The inference time was 3438ms.
![_1 jpg](https://user-images.githubusercontent.com/105331730/232342533-e01305aa-f4b4-4ef8-b26f-eeba4e670d66.png)

![image](https://user-images.githubusercontent.com/105331730/232342561-2925a995-30af-4e0f-b131-0e9245f33d89.png)
![_1 png](https://user-images.githubusercontent.com/105331730/232342609-6db280d7-13d1-4f88-9629-496f678aa4c3.png)
![_5 jpg](https://user-images.githubusercontent.com/105331730/232342612-e0a019c3-36d7-462c-b464-f8c939262d2e.png)

**Comment by wang-xinyu** [comment]
The first inference round is slow, please test more images or use a loop.
