### ISSUE TITLE
yolov5-cls的转换问题

### ISSUE THREAD

**Issue by Sarayue00** [wang-xinyu/tensorrtx#1286]
## Env

- NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4
- TensorRT version：7.2.3.4

## About this repo

- Tensorrtx：yolov5-v6.2或yolov5-v7.0
- yolov5-cls

## Your problem

- 当输入尺寸kInputH=832时报错，而kInputH=224时不报错
- 报错行：model.cpp:  ICudaEngine* engine = builder->buildEngineWithConfig(*network, *config);
- 模型信息：engine name : coco；input size : 832；model type : cls ；yolo type : s； class number : 1000
- 报错内容：
[04/17/2023-06:12:27] [E] [TRT] (Unnamed Layer* 140) [Fully Connected]: kernel weights has count 1280000 but 11520000 was expected
[04/17/2023-06:12:27] [E] [TRT] Could not compute dimensions for prob, because the network is not valid.
[04/17/2023-06:12:27] [E] [TRT] Network validation failed.
- 提问：yolov5-cls只支持输入尺寸为224吗？如果不是，请帮忙解决上述问题

**Comment by Sarayue00** [comment]
**已解决：**如果你使用的是tensorrtx-v6.2版本，则需要修改yolov5-cls.cpp文件；如果是tensorrtx-v7.0版本，则需要修改src/model.cpp文件。

你需要将以下代码：

IPoolingLayer* pool2 = network->addPoolingNd(*conv_class->getOutput(0), PoolingType::kAVERAGE, DimsHW{7, 7});

中的{7, 7}改为math.ceil(input_size / 32)，原因是yolov5使用的是自适应平均池化，而tensorrtx使用的是平均池化。因此，你需要修改池化层的filter_size，以确保网络能够正确运行。

具体地，你需要根据输入图像的大小来计算新的filter_size。这里的input_size指的是网络输入图像的大小，你可以使用Python中的math.ceil函数来实现对input_size / 32的上取整运算。例如，如果输入图像的大小为416x416，则你需要将filter_size修改为{13, 13}，因为math.ceil(416 / 32)的结果为13。

总之，通过修改池化层的filter_size，你可以实现对yolov5模型在tensorrtx上的正确运行。

**Comment by wang-xinyu** [comment]
Pls check this pr https://github.com/wang-xinyu/tensorrtx/pull/1369
