### ISSUE TITLE
retinaface 编译错误

### ISSUE THREAD

**Issue by Amanda-Barbara** [wang-xinyu/tensorrtx#129]
@wang-xinyu 你好，我在编译retinaface时报出以下错误：
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: invalid initialization of reference of type ‘decodeplugin::Detection&’ from expression of type ‘const decodeplugin::Detection’
请问这个如何修改呢？谢谢，

**Comment by Amanda-Barbara** [comment]
bool cmp(const decodeplugin::Detection& a, const decodeplugin::Detection& b) {
    return a.class_confidence > b.class_confidence;
}
我对cmp()函数增加了const关键字就可以了，

**Comment by wang-xinyu** [comment]
ok 感谢反馈

**Comment by wang-xinyu** [comment]
fixed it
