### ISSUE TITLE
Custom model along with TRT inference results are not accurate. 

### ISSUE THREAD

**Issue by AMIYAMAITY** [wang-xinyu/tensorrtx#1290]
## Env

- GPU:  NVIDIA GeForce GTX 1050 Ti.
- OS: Ubuntu 18.04.6 LTS
- Cuda version: 12.1
- TensorRT version: 8.6

## Problem

- Custom model wts file generate followed by this commands-
  ` // download https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt`
 `cp {tensorrtx}/yolov7/gen_wts.py {WongKinYiu}/yolov7`
 `cd {WongKinYiu}/yolov7`
 `python gen_wts.py`
 `// a file 'yolov7.wts' will be generated.`

Successfully wts has generated.
- Build and run and test with trt inference command for build and inference-
`cd {tensorrtx}/yolov7/`
`// update kNumClass in config.h if your model is trained on custom dataset`
`mkdir build`
`cd build`
`cp {WongKinYiu}/yolov7/yolov7.wts {tensorrtx}/yolov7/build`
`cmake ..`
`make`
`sudo ./yolov7 -s [.wts] [.engine] [t/v7/x/w6/e6/d6/e6e gd gw]  // serialize model to plan file`
`sudo ./yolov7 -d [.engine] [image folder]  // deserialize and run inference, the images in [image folder] will be processed.`
`// For example yolov7`
`sudo ./yolov7 -s best.wts best.engine v7`
`sudo ./yolov7 -d best.engine ../images`

After executed the last command for inference got two drawn images, when I see results are not correct. Not sure where exactly issue is generated wts file or trt inference. Seem .pt file is fine I verified the results `WongKinYiu/yolov7` repo results were fine.
Problematic image: [_zidane.jpg](https://drive.google.com/file/d/1PUNoJj9f926wq8k_8NUJsiFVKviNI0rh/view?usp=share_link)
**Note: My custom model 9 classes are there along with `person`, also I had changed number of classes in the config.h before build.
There is no issue when I tried with `WongKinYiu/yolov7` released 0.1 yolov7.pt file with same procedure.**

**Comment by wang-xinyu** [comment]
Pls check whether your custom model structure is different from released 0.1 yolov7.pt. Especially the last several layers. 0.1 is using `Detect` head, while the newer version is using `IDetect` head.

**Comment by AMIYAMAITY** [comment]
> Pls check whether your custom model structure is different from released 0.1 yolov7.pt. Especially the last several layers. 0.1 is using `Detect` head, while the newer version is using `IDetect` head.

Thank you @wang-xinyu  for your response, Yes I have verified in the custom model there is `IDetect` head. So, do we need to change anything while the model building or any commands do we need to add?

**Comment by wang-xinyu** [comment]
We don't support IDetect, if you want to implement by yourself, you can check the yololayer.cu.

**Comment by AMIYAMAITY** [comment]
> We don't support IDetect, if you want to implement by yourself, you can check the yololayer.cu.

Yeah, I checked that IDetect that, It's not supported in the current version. But that problem is solved now. After doing reparameterization steps by the given instruction of this script(https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb) the issue is resolved. 

Thank you again @wang-xinyu .
