### ISSUE TITLE
 yolov5 running time increase a lot

### ISSUE THREAD

**Issue by yeLer** [wang-xinyu/tensorrtx#1291]
## Env

- GPU, 1660Ti, NVIDIA-SMI 516.94 tc.
- OS, Win10, etc.
- Cuda version 10.2
- TensorRT version TensorRT-7.2.3.4

## problem
- yolov5 running time increase a lot. 

[console]
>yolov5.exe -d yolov5s.engine ./samples
384ms
8ms
7ms
7ms
7ms
7ms
7ms
7ms
7ms
7ms
7ms
7ms
8ms
8ms
7ms
7ms
7ms
7ms
8ms
7ms
8ms
7ms
7ms
7ms
7ms
7ms
7ms
7ms
9ms
7ms
7ms
7ms
7ms
7ms
43ms
37ms
51ms
41ms
35ms
42ms
41ms
48ms
41ms
37ms
42ms
46ms
65ms

**Comment by wang-xinyu** [comment]
Windows issue maybe.  Please try linux.
