### ISSUE TITLE
A problem which i met is so strange,i just don't understand .can you help me?

### ISSUE THREAD

**Issue by Phoenix8215** [wang-xinyu/tensorrtx#1294]
## Env

[![p9EAzVS.png](https://s1.ax1x.com/2023/04/21/p9EAzVS.png)](https://imgse.com/i/p9EAzVS)

## About this repo

- which branch/tag/commit are you using?which model? yolov5, retinaface?
i used yolov5 7.0version and accelerated the model with tensorrtX 7.0 version.

## Your problem

- i met a strange output ,i was shocked by the result!!!

```shell
builderx@robot-xx-v1-0-0:~/fz/tensorrtx/yolov5/build$ sudo ./yolov5_det -d best.engine ../images
inference time: 40ms
inference time: 34ms
```
if i don't use ```sudo``` to get a super user garantee,an error will happen

```shell
builderx@robot-xx-v1-0-0:~/fz/tensorrtx/yolov5/build$ ./yolov5_det -d best.engine ../images
yolov5_det: /home/builderx/fz/yolov5/yololayer.cu:78: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(const void*, size_t): Assertion `d == a + length' failed.
Aborted (core dumped)
```

could you tell me exactly what caused the difference between two outputs?3Q very much!

**Comment by Phoenix8215** [comment]
/(ㄒoㄒ)/~~

**Comment by wang-xinyu** [comment]
sudo和非sudo，链接到的so可能是不一样的

**Comment by Phoenix8215** [comment]
> sudo和非sudo，链接到的so可能是不一样的

thank you,i got it😙😙😙
