### ISSUE TITLE
Issue found while running files in CRNN  

### ISSUE THREAD

**Issue by Shivashankarar** [wang-xinyu/tensorrtx#1295]
I am facing this issue when i am serializing the engine it gives a assertion failed error...
Please tell how can we fix this issue..
@wang-xinyu Can you help me with issue please!
![image](https://user-images.githubusercontent.com/122434059/234002234-cc1a4f8f-6115-4285-9a88-13ef91fc65dc.png)

**Comment by wang-xinyu** [comment]
Can you try TensorRT 7.x?

**Comment by Shivashankarar** [comment]
Yes , it worked .. Can we run this with custom images ?
