### ISSUE TITLE
为什么自己训练出来的模型转tensorrt后结果不对，用官方提供的pt模型转tensorrt结果是对的？

### ISSUE THREAD

**Issue by Waynepoo** [wang-xinyu/tensorrtx#1296]
请问一下大佬，我训练的是v7tiny版本,训练好模型python detect.py结果是对的，但是转tensorrt后测试结果不对，但是我用官方提供的yolov7-tiny.pt转tensorrt后，官方提供模型推理结果正确，请该问题怎么解决？

**Comment by Waynepoo** [comment]
训练用的是下面命令，其他什么都没改
# train p5 models
python train.py --workers 8 --device 0 --batch-size 32 --data data/coco.yaml --img 640 640 --cfg cfg/training/yolov7.yaml --weights '' --name yolov7 --hyp data/hyp.scratch.p5.yaml

**Comment by Waynepoo** [comment]
训练命令如下，其他没改
python train.py --workers 5 --device 0 --batch-size 5 --epochs 50 --data data/coco.yaml --multi-scale --img 640 640 --cfg cfg/training/yolov7-tiny.yaml --weights yolov7-tiny.pt --name yolov7-tiny --hyp data/hyp.scratch.tiny.yaml

**Comment by wang-xinyu** [comment]
用v0.1分支试试

**Comment by Waynepoo** [comment]
> 用v0.1分支持试

用v1.0训练就不会出现转tensorrt结果对不上的问题，谢谢

**Comment by zzzzzz1112** [comment]
> > 用v0.1分支持试
> 
> 用v1.0训练就不会出现转tensorrt结果对不上的问题，谢谢

您好，我也碰到这个问题了，使用自己的单类别行人数据集训练的yolov7-tiny转tensorrt后检测就有问题，每个行人都有好几个大小不一的检测框，看到您的回答，yolov7不就只有一个版本吗？请问是怎么回事？谢谢
