### ISSUE TITLE
Speed for yolov4 tensorrt engine is slower than original yolov4

### ISSUE THREAD

**Issue by Harryqu123** [wang-xinyu/tensorrtx#13]
Sorry to bother you again. But I just want to ask do you compare the time for the transferred yolov4 engine and the original yolov4 darknet repo?
For my side with Geforce RTX 2080 ti,
the time for the transferred engine on the two test jpg you provided is 38ms per image.
However, when I use the same image to test with the original darknet with the follow simple code
./darknet detector test ./cfg/coco.data ./cfg/yolov4.cfg ./yolov4.weights
The time per same image is only 21ms.
And to avoid the case that the original repo only include model forward time, I also use own video to do the FPS test in the original darknet repo, with following 
include video_capturing + NMS + drawing_bboxes: ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -dont_show -ext_output
exclude video_capturing + NMS + drawing_bboxes: ./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights test.mp4 -benchmark
And either of the above two commands are faster than the 38ms tested here with the transferred engine.
Hence, I just want to ask have you compared the speed by yourself and on outside how much does time boost?
Thanks for the repo again

**Comment by wang-xinyu** [comment]
@Harryqu123  I will compare with darknet today or tomorrow.

Can you check batchsize and input shape?

**Comment by jinfagang** [comment]
@wang-xinyu  I also notice that this tensorrt version not faster as expected in terms of yolov4 with tensorrt accerleration.

**Comment by wang-xinyu** [comment]
@Harryqu123 @jinfagang 

I made a test on my machine, the FPS on batch 1, 4, 8 are tested, also compare with darknet.

https://github.com/AlexeyAB/darknet/pull/5453#issuecomment-623504871

For now there is no big difference for FPS between this tensorrt-yolov4 and darknet-yolov4. I guess the mish layer maybe influence the tensorrt optimization process, as mish is not natively supported in tensorrt.

I will try to optimize mish plugin.  If you guys got any suggestion,  please let me know!

**Comment by wang-xinyu** [comment]
@Harryqu123 @jinfagang 

I have optimized the mish layer. And retested the speed.

Please see this comment https://github.com/AlexeyAB/darknet/pull/5453#issuecomment-624116856

And please kindly update the codes and retest it on your machine.

**Comment by Harryqu123** [comment]
Sorry that I work on some other thing for these two weeks and reply late.
Yeah I have tested the code and it become faster now.
For your reference, on my 2080ti, the time per sample image is 12ms.
Really thanks for your help and sorry for the late reply again
