### ISSUE TITLE
retinaface没有检测出人脸

### ISSUE THREAD

**Issue by Amanda-Barbara** [wang-xinyu/tensorrtx#130]
@wang-xinyu 你好，我使用worlds-largest-selfie.jpg没有检测出人脸，结果显示如下：
383ms
number of detections -> 0
 -> 0
after nms -> 0
请问一下这是什么原因导致的呢？

**Comment by wang-xinyu** [comment]
过程中有没有什么错误或异常

**Comment by Amanda-Barbara** [comment]
啥错误也没有，我也尝试了yolov4，程序都能执行到最后，保存的结果中没有检测到的目标框，

**Comment by wang-xinyu** [comment]
环境是什么？系统，和软件版本

**Comment by Amanda-Barbara** [comment]
我的环境是：
系统：centos7.2
硬件：Tesla k40c
软件：nvidia-driver-450，cuda11.0，cudnn8.0，TensorRT-7.1

**Comment by wang-xinyu** [comment]
有可能和centos的gcc有关系？不清楚。。 我没有在centos测试过

**Comment by Amanda-Barbara** [comment]
好的，多谢指点，
