### ISSUE TITLE
What is the difference between yolov5s. engine?

### ISSUE THREAD

**Issue by nuaasxr** [wang-xinyu/tensorrtx#1303]
What is the difference between yolov5s. engine?
1，./yolov5_det -s yolov5s.wts yolov5s.engine s
2，./trtexec --onnx=yolov5.onnx --saveEngine=yolov5.engine
What are the differences between the engine files generated using these two methods?

**Comment by musend** [comment]
I wanna know too. if you already have answers,please comment me.thank you

**Comment by joaomedeirosr** [comment]
Good Question @nuaasxr

**Comment by wang-xinyu** [comment]
The main difference is the yololayer plugin, which decodes the 3 feature maps into bbox, class id and confidence with one CUDA kernel. The benefits are
 - Fewer decode layers
 - Smaller size of the output tensor, hence faster memcpy from gpu to cpu.

**Comment by musend** [comment]
so these 

> The main difference is the yololayer plugin, which decodes the 3 feature maps into bbox, class id and confidence with one CUDA kernel. The benefits are
> 
> * Fewer decode layers
> * Smaller size of the output tensor, hence faster memcpy from gpu to cpu.

so these two are not interchangeable.right?

**Comment by musend** [comment]
> The main difference is the yololayer plugin, which decodes the 3 feature maps into bbox, class id and confidence with one CUDA kernel. The benefits are
> 
> * Fewer decode layers
> * Smaller size of the output tensor, hence faster memcpy from gpu to cpu.

so these two are not interchangeable.right?

**Comment by wang-xinyu** [comment]
> so these two are not interchangeable.right?

Right.

**Comment by musend** [comment]
> > so these two are not interchangeable.right?
> 
> Right.

thanks for your ans.
