### ISSUE TITLE
yolov5seg，OpenCV(4.6.0) Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at

### ISSUE THREAD

**Issue by Chase2816** [wang-xinyu/tensorrtx#1305]
运行./yolov5_seg -d yolov5s-seg.engine images coco.txt得到报错：
OpenCV(4.6.0) Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at, file E:\libtorch_install\opencv\build\include\opencv2/core/mat.inl.hpp, line 899
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.6.0) Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at, file E:\libtorch_install\opencv\build\include\opencv2/core/mat.inl.hpp, line 899
我该如何处理？

**Comment by QIANXUNZDL123** [comment]
越界了，在后处理那块判断下就可以了

**Comment by QIANXUNZDL123** [comment]
> 运行./yolov5_seg -d yolov5s-seg.engine images coco.txt得到报错： OpenCV(4.6.0) Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at, file E:\libtorch_install\opencv\build\include\opencv2/core/mat.inl.hpp, line 899 OpenCV: terminate handler is called! The last OpenCV error is: OpenCV(4.6.0) Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at, file E:\libtorch_install\opencv\build\include\opencv2/core/mat.inl.hpp, line 899 我该如何处理？



> 

越界了，后处理那块判断下

**Comment by Chase2816** [comment]
谢谢，已解决

**Comment by 0iui0** [comment]
> 

请问一下怎么解决的？

**Comment by 0iui0** [comment]
> 谢谢，已解决


请问一下怎么解决的？
