### ISSUE TITLE
Debug in .cu file in plugins

### ISSUE THREAD

**Issue by osirisFdragon** [wang-xinyu/tensorrtx#1308]
Hi guys,
I'm a newbie in TensorRT framework. I'm trying to run RCNN-model deployment and wanna understand the insight of the code, specificly on the plugins. I'm trying to print some variable in plugin implementation (.cu file), like `rcnn/RpnDecode.cu` but the console doesnt show anything.

I wonder how you guys could debug the plugin module. Can anyone tell me please?
Thanks for reading...

Brgds,

**Comment by wang-xinyu** [comment]
You might need to learn the basics about CUDA.
