### ISSUE TITLE
请问adaptivePooling有没有实现的例子。

### ISSUE THREAD

**Issue by saladjay** [wang-xinyu/tensorrtx#131]
请问adaptivePooling有没有实现的例子。
如果一定要实现是不是只能通过custom layer的方式来实现。

**Comment by wang-xinyu** [comment]
如果输入是固定尺寸，adaptivepooling可以用普通的pooling替代

**Comment by saladjay** [comment]
> 如果输入是固定尺寸，adaptivepooling可以用普通的pooling替代

谢谢，我还有一个关于调试的问题。请问怎么在c++程序获取tensor的shape.
我在编写CBAM的tensorRT模型
在concat tensor的时候遇到
[E] [TRT] (Unnamed Layer* 0) [Convolution]: second input must be provided if kernel weights are empty.
[E] [TRT] (Unnamed Layer* 0) [Convolution]: kernel weights has count 0 but 4096 was expected
 [E] [TRT] (Unnamed Layer* 0) [Convolution]: count of 0 weights in kernel, but kernel dimensions (1,1) with 64 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 64 * 1*1 * 64 / 1 = 4096

**Comment by wang-xinyu** [comment]
可以用ITensor 的getDimensions() API

https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_tensor.html#a9f05f9eb1b9426b3d70eb646ae18961c

例如: avgCat->getOutput(0)->getDimensions()

**Comment by pribadihcr** [comment]
@saladjay ,

How did  you use adaptivePooling? Thanks
