### ISSUE TITLE
SPPCSPC function in Yolov7

### ISSUE THREAD

**Issue by Alex18947** [wang-xinyu/tensorrtx#1312]
Hi, thanks for this repo, it's quite informative. I am studying the Yolov7 code and have one question regarding the following line of code in the SPPCSPC function:

[Code link](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov7/src/block.cpp#L133)

What's the idea here? Does not c_ always end up to be equal to c2?

Thank you.

**Comment by wang-xinyu** [comment]
I guess the code was derived from yolov7 python https://github.com/WongKinYiu/yolov7/blob/84932d70fb9e2932d0a70e4a1f02a1d6dd1dd6ca/models/common.py#L266
