### ISSUE TITLE
multiprocessing mode

### ISSUE THREAD

**Issue by wxthu** [wang-xinyu/tensorrtx#1313]
## Env

- GPU, Tesla T4.
- OS, CentOS 7.3.
- Cuda version: 10.2
- TensorRT version: 7.0.0.11

## About this repo

- which branch/tag/commit are you using? **release 7.0**
- which model? **yolov5x**,

## Your problem
when I launch multiple processes to execute inference, I met the following errors:
-
![image](https://github.com/wang-xinyu/tensorrtx/assets/73052387/b583e0d9-813f-4cfe-aa7e-61dc0bac58a6)

**Comment by wang-xinyu** [comment]
I guess you need create different context for different process.
