### ISSUE TITLE
yolov5-6.0减少一个检测层，在cpp中进行模型更改后，依旧报错

### ISSUE THREAD

**Issue by hellosuer** [wang-xinyu/tensorrtx#1314]
## Env

- GPU, Nvidia orin
- OS, Ubuntu20.04
- Cuda version：11.4
- TensorRT version：8.4.1.5

## About this repo

- yolov5-6.0

## Your problem
在训练过程中更改了yaml文件，删除了一个预测层
![image](https://github.com/wang-xinyu/tensorrtx/assets/110160797/9098f001-3a53-43bb-90fa-9a5c62f423de)
然后在yolov5.cpp中进行了如下更改
![image](https://github.com/wang-xinyu/tensorrtx/assets/110160797/92750bf2-be3b-415e-a162-7b4016445234)
同时在yololayer.h中将check_count改为了2
- 执行`sudo ./yolov5 -s best.wts best.engine s`
- what's your output?
-出现如下错误
![ed0be1373775344e31beb9a72b2fdb0](https://github.com/wang-xinyu/tensorrtx/assets/110160797/b047f6cc-b26a-4b40-be21-54044a39a260)

- 请问是还需要在额外的地方进行修改吗

**Comment by 173770346** [comment]
你好，请问你解决这个问题了吗？这个似乎是由于TensorRt版本导致的问题，我也是Orin，也是这个kernel weights has count 0的问题

**Comment by hellosuer** [comment]
> 你好，请问你解决这个问题了吗？这个似乎是由于TensorRt版本导致的问题，我也是Orin，也是这个kernel weights has count 0的问题

现在还没有，您解决这个问题了嘛
