### ISSUE TITLE
yolov5-tag6可以生成.engine但是推理会报Segmentation fault

### ISSUE THREAD

**Issue by hhitdata** [wang-xinyu/tensorrtx#1323]
- GPU, agx orin
- OS, Ubuntu 20.04.5 LTS (GNU/Linux 5.10.104-tegra aarch64)
- Cuda 11.4
- TensorRT 8.5.2.2

用yolov5-tag6的预训练模型yolov5s.pt，yolov5l6.pt和对应的tensorrtx yolov5-6.2都可以转换为engine，`sudo ./yolov5 -s ../yolov5s.wts yolov5s.engine s`最后会出现一个error：
> [07/06/2023-09:04:30] [W] [TRT] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
> Loading weights: ../yolov5s.wts
> Building engine, please wait for a while...
> [07/06/2023-09:12:21] [W] [TRT] TensorRT encountered issues when converting weights between types and that could affect accuracy.
> [07/06/2023-09:12:21] [W] [TRT] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
> [07/06/2023-09:12:21] [W] [TRT] Check verbose logs for the list of affected weights.
> [07/06/2023-09:12:21] [W] [TRT] - 52 weights are affected by this issue: Detected subnormal FP16 values.
> [07/06/2023-09:12:21] [W] [TRT] - 2 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
> Build engine successfully!
> [07/06/2023-09:12:21] [E] [TRT] 3: [builder.cpp::~Builder::307] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builder.cpp::~Builder::307, condition: mObjectCounter.use_count() == 1. Destroying a builder object before destroying objects it created leads to undefined behavior.
> )
在执行sudo ./yolov5 -d yolov5s.engine ../sample时会报Segmentation fault。
但是用yolov5-tag5和对应的tensorrtx yolov5-5.0也会出现最后的API Usage Error，但是可以进行推理，请问下tag6的问题怎么解决。

**Comment by hhitdata** [comment]
又尝试了yolov5-7.0和对应的tensorrtx yolov5-7.0结果同5.0，现在只有6.0的会报错。。

**Comment by wang-xinyu** [comment]
参考下这里看看，是不是同一个问题，https://github.com/wang-xinyu/tensorrtx/issues/1310#issuecomment-1722243922
