### ISSUE TITLE
我在使用retinaface的过程中出现了下面的问题

### ISSUE THREAD

**Issue by Glory-Peng** [wang-xinyu/tensorrtx#1324]
![image](https://github.com/wang-xinyu/tensorrtx/assets/57623095/9a8c2e00-7f56-4377-83c6-49cf27b1b048)
engine文件可以正常生成，但是使用后python推理，一直会卡在这个地方，不报任何的错误，过会直接killed

**Comment by wang-xinyu** [comment]
内存不够了吧，jetson尽量别用py
