### ISSUE TITLE
Error when convert wts to yolov8 engine for custom class model

### ISSUE THREAD

**Issue by HuynhLongTGG** [wang-xinyu/tensorrtx#1325]
## Env
- GPU RTX 2070
- Use docker tensorrt-20.01: https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/index.html#rel_22-01
## About this repo
- i use branch master 
- With model yolov8 .
- 
## Your problem
- When i convert wts to tensorrt with yolov8n custom class from 80 to 1 class, i saw output like below image
- My model just change number class 80 to 1 class . With custom dataset , not change anything
![image](https://github.com/wang-xinyu/tensorrtx/assets/50861466/72d72727-04d6-4ecd-b572-dc964b8d90d1)

**Comment by wang-xinyu** [comment]
Did you adapt the kNumClass in config.h?

**Comment by whatt-ai** [comment]
@wang-xinyu 
Yes, I am already change the numclass to 7 (in my own model), use the yolov8n, train on RTX2080ti (CUDA 11.5), deploy on Jetson Nano.

**Comment by wang-xinyu** [comment]
I meant here https://github.com/wang-xinyu/tensorrtx/blob/bc4f854dc3a70017b09dd5305a78a15df63741a1/yolov8/include/config.h#L6C18-L6C27, did you adapt it?

**Comment by whatt-ai** [comment]
> I meant here https://github.com/wang-xinyu/tensorrtx/blob/bc4f854dc3a70017b09dd5305a78a15df63741a1/yolov8/include/config.h#L6C18-L6C27, did you adapt it?

YES

**Comment by wang-xinyu** [comment]
@lindsayshuo Please take a loop as the custom num of class issue?

**Comment by lindsayshuo** [comment]
> +1.
> 
> ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)

Please use a version after July 6, 2023, the custom category has been fixed

**Comment by HuynhLongTGG** [comment]
> > +1.
> > ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)
> 
> Please use a version after July 6, 2023, the custom category has been fixed

Hi bro, i'm already  use last version . With my config user kNumClass = 1 i got error like that.

**Comment by lindsayshuo** [comment]
> > > +1.
> > > ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)
> > 
> > 
> > Please use a version after July 6, 2023, the custom category has been fixed
> 
> Hi bro, i'm already use last version . With my config used kNumClass = 1 i got error like that.

Can you provide your PT file ，I can test it

**Comment by HuynhLongTGG** [comment]
> > > > +1.
> > > > ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)
> > > 
> > > 
> > > Please use a version after July 6, 2023, the custom category has been fixed
> > 
> > 
> > Hi bro, i'm already use last version . With my config used kNumClass = 1 i got error like that.
> 
> Can you provide your PT file ，I can test it

can you provide your email, so i can share it for u

**Comment by lindsayshuo** [comment]
> > > > > +1.
> > > > > ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)
> > > > 
> > > > 
> > > > Please use a version after July 6, 2023, the custom category has been fixed
> > > 
> > > 
> > > Hi bro, i'm already use last version . With my config used kNumClass = 1 i got error like that.
> > 
> > 
> > Can you provide your PT file ，I can test it
> 
> can you provide your email, so i can share it for u

lindsayshuo@foxmail.com

**Comment by lindsayshuo** [comment]
> > > > > > +1.
> > > > > > ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)
> > > > > 
> > > > > 
> > > > > Please use a version after July 6, 2023, the custom category has been fixed
> > > > 
> > > > 
> > > > Hi bro, i'm already use last version . With my config used kNumClass = 1 i got error like that.
> > > 
> > > 
> > > Can you provide your PT file ，I can test it
> > 
> > 
> > can you provide your email, so i can share it for u
> 
> [lindsayshuo@foxmail.com](mailto:lindsayshuo@foxmail.com)

The size of the pt model you provided is not consistent with the official model, and the size of the transferred wts is also different. Have you changed the model?

**Comment by HuynhLongTGG** [comment]
> > > > > > > +1.
> > > > > > > ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)
> > > > > > 
> > > > > > 
> > > > > > Please use a version after July 6, 2023, the custom category has been fixed
> > > > > 
> > > > > 
> > > > > Hi bro, i'm already use last version . With my config used kNumClass = 1 i got error like that.
> > > > 
> > > > 
> > > > Can you provide your PT file ，I can test it
> > > 
> > > 
> > > can you provide your email, so i can share it for u
> > 
> > 
> > [lindsayshuo@foxmail.com](mailto:lindsayshuo@foxmail.com)
> 
> The size of the pt model you provided is not consistent with the official model, and the size of the transferred wts is also different. Have you changed the model?

i'm already not changed anything construct model bro . 
My config : 

train: /home/vnptcamera/lpd/train.txt  # train images (relative to 'path') 128 images
val: /home/vnptcamera/lpd/val.txt  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
nc: 1

names: ['lpr']  # class names

and Python train with ultralytics yolov8:
from ultralytics import YOLO

# Load a model
#model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
#model = YOLO('best.pt')  # build from YAML and transfer weights

# Train the model
model.train(data='lpr_data.yaml', epochs=300, imgsz=640)

**Comment by willianLee** [comment]
> > > > > > > > +1.
> > > > > > > > ![image](https://user-images.githubusercontent.com/102944195/252413955-0666f8b5-3991-46d2-912f-c6526d9f3601.png)
> > > > > > > 
> > > > > > > 
> > > > > > > Please use a version after July 6, 2023, the custom category has been fixed
> > > > > > 
> > > > > > 
> > > > > > Hi bro, i'm already use last version . With my config used kNumClass = 1 i got error like that.
> > > > > 
> > > > > 
> > > > > Can you provide your PT file ，I can test it
> > > > 
> > > > 
> > > > can you provide your email, so i can share it for u
> > > 
> > > 
> > > [lindsayshuo@foxmail.com](mailto:lindsayshuo@foxmail.com)
> > 
> > 
> > The size of the pt model you provided is not consistent with the official model, and the size of the transferred wts is also different. Have you changed the model?
> 
> i'm already not changed anything construct model bro . My config :
> 
> train: /home/vnptcamera/lpd/train.txt # train images (relative to 'path') 128 images val: /home/vnptcamera/lpd/val.txt # val images (relative to 'path') 128 images test: # test images (optional)
> # Classes
> 
> nc: 1
> 
> names: ['lpr'] # class names
> 
> and Python train with ultralytics yolov8: from ultralytics import YOLO
> # Load a model
> 
> #model = YOLO('yolov8n.yaml') # build a new model from YAML model = YOLO('yolov8n.pt') # load a pretrained model (recommended for training) #model = YOLO('best.pt') # build from YAML and transfer weights
> # Train the model
> 
> model.train(data='lpr_data.yaml', epochs=300, imgsz=640)

Hi, bro,  i got the same situation， 

Have you solved this problem yet？

**Comment by willianLee** [comment]
same situation,  did not work on  custom class num  ......

**Comment by wang-xinyu** [comment]
Please share the commit-id of ultralytics repo and this repo.

**Comment by willianLee** [comment]
> Please share the commit-id of ultralytics repo and this repo.

tensorrtx   70d0adc9eceb0562e9cafd903b6bc28a8217ce08

v8   fadbef84e160c3c98f0a791d7b45850f1449cb75

thanks for your reply

**Comment by willianLee** [comment]
> Please share the commit-id of ultralytics repo and this repo.

latest version v8 and latest version tensorrtx seems working properly.
maybe i used old version v8 before....

**Comment by duongthanhdong** [comment]
> > Please share the commit-id of ultralytics repo and this repo.
> 
> latest version v8 and latest version tensorrtx seems working properly. maybe i used old version v8 before....

Still facing this error, even though I have been using the latest versions of both projects.

**Comment by a514154639** [comment]
我用最新的v8和 tensorrtx也遇到了这个问题，我的环境是cuda 10.2 tensorrt8.2.1在jetson nx上编译没问题，转化报了类别的错误，我用的yolov8n，数据集的类别从80改到了2
![image](https://github.com/wang-xinyu/tensorrtx/assets/39019284/81d6c434-7705-4796-bdc3-3445c83292cc)

**Comment by wang-xinyu** [comment]
@a514154639 更新config.h了吗

**Comment by a514154639** [comment]
> @a514154639 更新config.h了吗

嗯嗯 改过了

**Comment by wang-xinyu** [comment]
@a514154639 可以试试这个版本的代码训练：pip install ultralytics==8.0.134

**Comment by a514154639** [comment]
> @a514154639 可以试试这个版本的代码训练：pip install ultralytics==8.0.134

嗯嗯 尝试了 但还是有些问题 我正在和lindsayshuo交流具体得原因

**Comment by willianLee** [comment]
8.0.114试试?我之前用的旧版本好像是113?更新之后好像可以了，难道是偶然情况?



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 18, 2023 10:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wang-xinyu/tensorrtx] Error when convert wts to yolov8 enginefor custom class model (Issue #1325)




  
@a514154639 可以试试这个版本的代码训练：pip install ultralytics==8.0.134
  
嗯嗯 尝试了 但还是有些问题 我正在和lindsayshuo交流具体得原因

**Comment by a514154639** [comment]
> > @a514154639 可以试试这个版本的代码训练：pip install ultralytics==8.0.134
> 
> 嗯嗯 尝试了 但还是有些问题 我正在和lindsayshuo交流具体得原因

和lindsayshuo交流之后应该是model.cpp的问题，我使用ultralytics==8.0.134，测试yolov8s没问题但是yolov8n出现了转化错误，稍后他会上传修改后的model.cpp，重新编译之后问题解决

**Comment by whatt-ai** [comment]
是的，我刚刚使用yolov8s转换成功了，但是yolov8n依然不行。

**Comment by lindsayshuo** [comment]
> 是的，我刚刚使用yolov8s转换成功了，但是yolov8n依然不行。

可以用我最新上传的代码，修复了
