### ISSUE TITLE
Error Retinafece engine creation 

### ISSUE THREAD

**Issue by shekarneo** [wang-xinyu/tensorrtx#1327]
## Env

- Xavier NX
- Ubuntu18.04
- Cuda version = 11.4
- TensorRT version = 8.4

## About this repo

- which branch/tag/commit are you using? latest
- which model? retinaface?

## Your problem

- what is your command? e.g. `sudo ./retina_r50 -s`
- what's your output? 
[07/11/2023-20:29:21] [W] [TRT] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
Loading weights: ../retinaface.wts
Your platform support int8: 1
Building engine, please wait for a while...
reading calib cache: r50_int8calib.table
[07/11/2023-20:29:38] [E] [TRT] 1: Unexpected exception _Map_base::at
Build engine successfully!
retina_r50: /home/sensormatic/Neo/tensorrtx/retinaface/retina_r50.cpp:251: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted

- what output do you expect?
i was expecting trt engine file.

**Comment by abdulazizab2** [comment]
As far as I remember it was working with TRT 8. I remember pulling TRT 8 docker image from nvidia. But I am not sure now lol

**Comment by shekarneo** [comment]
@abdulazizab2 i am able to create engine file by changing int8 to fp16/fp32, but accuracy is worst.

**Comment by abdulazizab2** [comment]
@shekarneo 
I think that depends mostly on the input size you select when creating the engine. How did you verify that accuracy is low ? Did you compare it with the PyTorch model ?

**Comment by shekarneo** [comment]
@abdulazizab2  yes i tried with pytorch version and it gave good accuracy.

**Comment by abdulazizab2** [comment]
@shekarneo 
Check that anchor box configs in the C++ files is the same as the one in Python repository. This change the bounding boxes dramatically if its not the same

**Comment by shekarneo** [comment]
@abdulazizab2 i could not see any anchor boxes in cpp files

**Comment by abdulazizab2** [comment]
@shekarneo 
Same, I didn't try measuring the accuracy using this repo. However, I take the weight from the same repo: https://github.com/biubug6/Pytorch_Retinaface and align my C++ configs to the configs in this [code](https://github.com/biubug6/Pytorch_Retinaface/blob/b984b4b775b2c4dced95c1eadd195a5c7d32a60b/data/config.py) and results become good.

I tried to look for anchors I didnt find. However, most of the postprocessing is in common.hpp that should be the same as the model you picked. Hope it helps

**Comment by ridweng** [comment]
Hi, I have the exact same issue. I got my weights from the same repo but I'm not able to find which configurations I need to change in the C++ files.
Any suggestion or guideline to replicate what @abdulazizab2 mentioned would be greatly appreciated.

**Comment by shekarneo** [comment]
@wang-xinyu any help here..

**Comment by wang-xinyu** [comment]
How's the accuracy with fp16/fp32?

**Comment by shekarneo** [comment]
Both FP16 and FP32 giving the same results in xavier nx

**Comment by shekarneo** [comment]
@wang-xinyu  is there any changes needs to do for tensorRT8.4

**Comment by shekarneo** [comment]
here [retinaface](https://github.com/zhouyuchong/retinaface-deepstream-python) they used the same retinaface from this repo with tensorRT 8.x and they got better accuracy.

in my case when i ran `sudo ./retina_r50 -d  // deserialize model file and run inference` this command i got the below results


![](https://user-images.githubusercontent.com/25033310/253508969-fd002640-08a2-4b29-922e-6df26d47c802.jpg)

**Comment by wang-xinyu** [comment]
> here [retinaface](https://github.com/zhouyuchong/retinaface-deepstream-python) they used the same retinaface from this repo with tensorRT 8.x and they got better accuracy.
> 
> in my case when i ran `sudo ./retina_r50 -d // deserialize model file and run inference` this command i got the below results
> 
> ![](https://user-images.githubusercontent.com/25033310/253508969-fd002640-08a2-4b29-922e-6df26d47c802.jpg)

This result looks reasonable. You want the very small faces also be detected?

**Comment by shekarneo** [comment]
but most of the detection like close ups are not detecting and giving more false positives

**Comment by shekarneo** [comment]
@wang-xinyu any help here

**Comment by shekarneo** [comment]
@wang-xinyu Please find the screen shots 
<img width="1139" alt="Screenshot 2023-08-26 at 2 03 55 PM" src="https://github.com/wang-xinyu/tensorrtx/assets/25033310/e173d433-eba7-49f7-8b9b-864139ea0c41">
<img width="1139" alt="Screenshot 2023-08-26 at 2 04 21 PM" src="https://github.com/wang-xinyu/tensorrtx/assets/25033310/64ce085e-bd8a-4686-8229-66f4d4ddf4f4">
