### ISSUE TITLE
yolov8量化时遇到了方法重复定义

### ISSUE THREAD

**Issue by 1145141919** [wang-xinyu/tensorrtx#1328]
[100%] Linking CXX executable yolov8
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:9: multiple definition of `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:9: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:9: multiple definition of `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:9: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::~Int8EntropyCalibrator2()':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:25: multiple definition of `Int8EntropyCalibrator2::~Int8EntropyCalibrator2()'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:25: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::~Int8EntropyCalibrator2()':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:25: multiple definition of `Int8EntropyCalibrator2::~Int8EntropyCalibrator2()'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:25: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::~Int8EntropyCalibrator2()':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:25: multiple definition of `Int8EntropyCalibrator2::~Int8EntropyCalibrator2()'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:25: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::getBatchSize() const':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:31: multiple definition of `Int8EntropyCalibrator2::getBatchSize() const'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:31: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::getBatch(void**, char const**, int)':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:36: multiple definition of `Int8EntropyCalibrator2::getBatch(void**, char const**, int)'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:36: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::readCalibrationCache(unsigned long&)':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:61: multiple definition of `Int8EntropyCalibrator2::readCalibrationCache(unsigned long&)'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:61: first defined here
CMakeFiles/yolov8.dir/src/calibrator.cpp.o: In function `Int8EntropyCalibrator2::writeCalibrationCache(void const*, unsigned long)':
/root/trtx/yolov8/tensorrtx-master/yolov8/src/calibrator.cpp:75: multiple definition of `Int8EntropyCalibrator2::writeCalibrationCache(void const*, unsigned long)'
CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o:/root/trtx/yolov8/tensorrtx-master/yolov8/src/.ipynb_checkpoints/calibrator-checkpoint.cpp:75: first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/yolov8.dir/build.make:211: recipe for target 'yolov8' failed
make[2]: *** [yolov8] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/yolov8.dir/all' failed
make[1]: *** [CMakeFiles/yolov8.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
错误如上

找了一下：
root@autodl-container-8250118952-430d0f77:~/trtx/yolov8/tensorrtx-master/yolov8/bulid# cd ..
root@autodl-container-8250118952-430d0f77:~/trtx/yolov8/tensorrtx-master/yolov8# find ./ -name "*calibrator*"
./include/calibrator.h
./src/calibrator.cpp
./src/.ipynb_checkpoints/calibrator-checkpoint.cpp
./bulid/CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o.d
./bulid/CMakeFiles/yolov8.dir/src/.ipynb_checkpoints/calibrator-checkpoint.cpp.o
./bulid/CMakeFiles/yolov8.dir/src/calibrator.cpp.o.d
./bulid/CMakeFiles/yolov8.dir/src/calibrator.cpp.o

calibrator-checkpoint.cpp和calibrator.cpp要使用哪一个里的方法？

**Comment by lindsayshuo** [comment]
没有calibrator-checkpoint.cpp，是不是跟你之前的项目重复，覆盖了

**Comment by 1145141919** [comment]
> ./src/.ipynb_checkpoints/文件夹下似乎是项目自动生成的ipynb备份·，我刚把他删除了就跑通了，谢谢！！
