### ISSUE TITLE
yolov5-trt-部署设备JetsonNano

### ISSUE THREAD

**Issue by QYJ9202** [wang-xinyu/tensorrtx#133]
1. 问题描述
用yolov5训练自己的数据，网络部分使用自己的上采样（详见2修改部分），在Jetson Nano部署出现问题（详见3问题描述）

2.修改部分
(1). 网络部分添加上采样
----------------“”modles/common.py“”-------------------------------
class Upsample(nn.Module):
    def __init__(self, size, scale, mode, align_corners=None):
        super(Upsample, self).__init__()
        self.size = size
        self.scale = scale
        self.mode = mode
        self.align_corners = align_corners

    def forward(self, x):
        sh = torch.tensor(x.shape)
        return F.interpolate(x, size=(int(sh[2]*self.scale), int(sh[3]*self.scale)), mode=self.mode, align_corners=self.align_corners)
------------------""models/yolov5s.yaml""------------------------------------------
head:
  [[-1, 3, BottleneckCSP, [1024, False]],  # 9

   [-1, 1, Conv, [512, 1, 1]],
   [-1, 1, Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, BottleneckCSP, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, BottleneckCSP, [256, False]],
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 18 (P3/8-small)
(2)-----------yololayer.h------------------------
namespace Yolo
{
    static constexpr int CHECK_COUNT = 3;
    static constexpr float IGNORE_THRESH = 0.1f;
    static constexpr int MAX_OUTPUT_BBOX_COUNT = 1000;
    static constexpr int CLASS_NUM = 2;
    static constexpr int INPUT_H = 640;
    static constexpr int INPUT_W = 640;

3.出现问题
(1). 在运行 sudo ./yolov5 -s时出现错误如下
“”“”
[TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/qyj/yolov5-master/yolov5/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
已放弃
“”“”

**Comment by wang-xinyu** [comment]
如果修改网络结构，需要自己调整yolov5s.cpp中的createEngine_s()函数。

**Comment by QYJ9202** [comment]
好的，我试试，谢谢回复
