### ISSUE TITLE
Yolov8 accuracy is low

### ISSUE THREAD

**Issue by spacewalk01** [wang-xinyu/tensorrtx#1335]
I compared yolov5s.engine and yolov8s.engine. Both are from tensorrtx. Yolov8s detection accuracy is much lower than that of yolov5s.

**Comment by 1145141919** [comment]
Hello! Have you solved this problem? Is it related to post-processing?

**Comment by wang-xinyu** [comment]
Please try the official model first.

**Comment by RockingHorse-L** [comment]
我用的yolov8官方的模型来训练自己的数据集，转为engine后最开始在if categories[int(result_classid[j])] in num_dic.keys():报错索引超出list的索引，并且打印出来的result_boxes, result_scores, result_classid发现也很不对劲，于是我就对比了v5和v8对应的det_trt文件，发现v5里有LEN_ALL_RESULT = 38001、LEN_ONE_RESULT = 38这两个变量，我尝试修改v8的，虽然输出来的结果看起来正常了，但是检测的效果很不好，v5能检测出9个的，v8只能检测出2-3个。

**Comment by wang-xinyu** [comment]
@RockingHorse-L 试过官方训练好的模型吗？
