### ISSUE TITLE
The real esrgan model can't be quantized to 8bit? The 8bit result is very different from the float result.

### ISSUE THREAD

**Issue by Joboing** [wang-xinyu/tensorrtx#1336]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
real-esrgan int8 is not supported.
