### ISSUE TITLE
yolov5_det_cuda_python.py Custom yolo5n6 model Index out of range

### ISSUE THREAD

**Issue by bkh345** [wang-xinyu/tensorrtx#1339]
## Env

- GPU: Tesla T4
- Cuda version: Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
- TensorRT version: 8.5.2.2

## About this repo

- commit: c66b8b7e2c471f5eba03df9e39cb2b410041be29
- model: Yolo5n6

## Your problem

- Command: python3 yolov5_det_cuda_python.py

I am new to Tensorrt and Deepstream and I am trying to use a custom yolo5n6 model. It is trained on COCO, but only using 9 of the 80 classes. I trained the model using 1280 image resolution and I built an engine for several batch sizes. The model seems to work fine when I use the yolo_det.cpp version, but when I went to use it in deepstream I kept getting errors. I went back and tried to make sure the model worked using the python detection scripts in the tensorrtx/yolov5 repo and I get an index stating that the list index is out of range. I thought that this might be due to a mismatch in KNumClasses in the config/yaml files, so I went and changed them to reflect the 9 classes, but I still get the same issue. Does anyone have any idea what the issue could be? 

Here is the output I am getting when running python3 yolov5_det_cuda_python.py:
```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/yolov5n6/tensorrtx/yolov5/yolov5_det_cuda_python.py", line 381, in run
    batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image(self.image_path_batch))
  File "/root/yolov5n6/tensorrtx/yolov5/yolov5_det_cuda_python.py", line 174, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range
```

Another thing that I noticed is that during the reshape process, There seems to be some just data that comes out of it. Here is that reshaping converted to a table for readability sake. 
<img width="599" alt="image" src="https://github.com/wang-xinyu/tensorrtx/assets/139914504/6c7c33c5-97fc-4dce-83a1-235e5ee1e4c2">

Thank you everyone in advance!

**Comment by wang-xinyu** [comment]
Did you try this [yolov5_det_trt.py](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5_det_trt.py)?

**Comment by bkh345** [comment]
Yes. When run with yolov5_det_trt.py, I also get a "list index out of range" error: 
```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/yolov5n6/tensorrtx/yolov5/yolov5_det_trt.py", line 385, in run
    batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image(self.image_path_batch))
  File "/root/yolov5n6/tensorrtx/yolov5/yolov5_det_trt.py", line 170, in infer
    output[i * LEN_ALL_RESULT: (i + 1) * LEN_ALL_RESULT], batch_origin_h[i], batch_origin_w[i]
IndexError: list index out of range
```

**Comment by bkh345** [comment]
Please let me know if there is any other information I can provide to assist in solving this issue. 

Thank you for your time

**Comment by CapBarbossa** [comment]
哥们，请问下：
LEN_ALL_RESULT = 38001
LEN_ONE_RESULT = 38
这两个是什么东东？在 `yolov5/yolov5_det_trt.py` 文件中。

**Comment by bkh345** [comment]
@CapBarbossa @wang-xinyu, 
for my yolov5_det_trt.py, my values are: 
```
CONF_THRESH = 0.5
IOU_THRESHOLD = 0.4
LEN_ALL_RESULT = 38001
LEN_ONE_RESULT = 38
```
They are the same as what you wrote. Do you think this could be the issue when I only have 9 classes?

**Comment by wang-xinyu** [comment]
38 is the size of Detection struct.
```
struct alignas(float) Detection {
  float bbox[4];  // center_x center_y w h
  float conf;  // bbox_conf * cls_conf
  float class_id;
  float mask[32];
};
```

38001 is the size of output tensor.

They don't contain any number of classes info.

For different number of classes, you only need to modify this kNumClass, then rebuild code and .engine.

https://github.com/wang-xinyu/tensorrtx/blob/c997e35710ff0230ae6361d9ba3b9ae82ed3a7d8/yolov5/src/config.h#L18
