### ISSUE TITLE
Yolov4中网络decode操作在哪实现？

### ISSUE THREAD

**Issue by CaptainJohansson** [wang-xinyu/tensorrtx#134]
根据Yolov4分析，网络的3个输出（batch, 255, 19, 19)(batch, 255, 38, 38)（batch， 255， 76， 76）(以输入大小608x608为例）需要进行decode和NMS处理，NMS处理在yolov4.cpp中找到，请问decode在哪实现？同样在进行decode操作前，候选框的生成以及对坐标x,y，物体置信度和confidence的sigmoid操作方便的话也请说明下。。
谢谢！！！

**Comment by wang-xinyu** [comment]
参考这个issue https://github.com/wang-xinyu/tensorrtx/issues/132

**Comment by CaptainJohansson** [comment]
嗯嗯，我了解到网络的输出处理在yoloLayerplugin这个文件中，您能具体指出decode操作实现在哪个函数中吗？

**Comment by wang-xinyu** [comment]
CalDetection() in yololayer.cu

**Comment by CaptainJohansson** [comment]
ok, i got it, Thanks!!
