### ISSUE TITLE
building engine files, 'make' command

### ISSUE THREAD

**Issue by HunterShinobiTitan** [wang-xinyu/tensorrtx#1343]
## Env

- GPU, RTX 3050
- OS, WIn11
- Cuda 11.8
- TensorRT version

## About this repo

- which branch/tag/commit are you using? main branch
- which model? yolop
## Your problem

- what is your command? make
- what's your output? make: *** No targets specified and no makefile found.  Stop.
- what output do you expect? building yolop

**Comment by HunterShinobiTitan** [comment]
Here is the cmake:
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.36.32537.0
-- The CXX compiler identification is MSVC 19.36.32537.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8 (found suitable exact version "11.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Pacz/Downloads/YOLOP/YOLOP-main/toolkits/deploy/build

**Comment by HunterShinobiTitan** [comment]
![image](https://github.com/wang-xinyu/tensorrtx/assets/113270011/788266d6-d1bb-4f9d-b7ce-090ac5eeeff0)
generated files

**Comment by wang-xinyu** [comment]
You need figure out how to build this code on Windows,  the cmakelists.txt is this repo is for Linux.

**Comment by HunterShinobiTitan** [comment]
Hello can you guide me on how to end-to-end training YOLOP. I'm
experiencing bugs with the code

**Comment by wang-xinyu** [comment]
Training is not covered by this repo, we only do deployment.
