### ISSUE TITLE
GUYS, who know why like this  ???????????????????? please help!!

### ISSUE THREAD

**Issue by qxysam** [wang-xinyu/tensorrtx#1346]
Environment
TensorRT Version: 7.2.3.4
GPU Type: RTX4070
CUDA Version: cuda_11.0.2_451.48_win10
CUDNN Version: cudnn-11.0-windows-x64-v8.0.4.30
Operating System: Version: win10
Opencv Version: opencv4.2.0

key issue: Half2 support requested on hardware without native FP16 support, performance will be negatively affected

![f7433cf1376d45dc9326c674f50938f](https://github.com/wang-xinyu/tensorrtx/assets/29799202/feb65f83-ebb8-415a-b108-54194d6c311c)

**Comment by wang-xinyu** [comment]
unsupported sm,  you need newer version of CUDA.
