### ISSUE TITLE
How should I configure yolov8 and yolov5 to be used simultaneously in one project?

### ISSUE THREAD

**Issue by BouncyKnight12** [wang-xinyu/tensorrtx#1348]
## Env

- Xavier AGX 
- Ubuntu20.04
- Cuda version 11.4.315
- TensorRT version 8。5.2.2

## About this repo

- which branch/tag/commit are you using? master
- which model? yolov5, retinaface? yolov5 and yolov8

## Your problem

I used the add_subdirectory() command to generate SHARED libraries for both yolov8 and yolov5.
However, when yolov8 is deserialized, it will always be wrongly linked to the yolov5 plugin, so that the model does not match and reports the error Assertion 'd == a + length' failed.

**Comment by wang-xinyu** [comment]
You can rename the plugin so in cmakelist.
