### ISSUE TITLE
inference speed of networks with deconvolution layer in tensorrt 4

### ISSUE THREAD

**Issue by yaoqi-zd** [wang-xinyu/tensorrtx#135]
Hi, Thanks for your work! 

May I ask whether you have tested the inference speed of networks that contain deconvolution layers with tensorrt 4 optimization?  Since there are several [issues](https://forums.developer.nvidia.com/t/deconvolution-layer-runs-super-slow-in-tensorrt/61894/2) raised to complain the slow inference speed of deconvolution layer.

the following shows a case of layerwise runtime with tensorrt 4, layer 'upscore' is very slow.
```
[TRT]  layer shift - 0.919552 ms
[TRT]  layer conv1 + relu1 - 1.481728 ms
[TRT]  layer pool1 - 0.116832 ms
[TRT]  layer norm1 - 0.056224 ms
[TRT]  layer conv2 + relu2 - 1.145856 ms
[TRT]  layer pool2 - 0.087520 ms
[TRT]  layer norm2 - 0.097824 ms
[TRT]  layer conv3 + relu3 - 0.546816 ms
[TRT]  layer conv4 + relu4 - 0.425984 ms
[TRT]  layer conv5 + relu5 - 0.280576 ms
[TRT]  layer pool5 - 0.027648 ms
[TRT]  layer fc6 + relu6 - 8.728576 ms
[TRT]  layer fc7 + relu7 - 3.900512 ms
[TRT]  layer score_fr - 0.097184 ms
[TRT]  layer upscore - 3986.665527 ms
[TRT]  layer network time - 4004.578369 ms
[TRT]  segNet::Overlay -- s_w 1343  s_h 767  s_c 21  s_x 1.049219  s_y 1.065278
[TRT]  segNet::Overlay -- ignoring class 'void' id=0
```
I see in your readme that yolo with deconvolution layer reaches very high FPS in tensorrt7, so this problem is solved in trt7?

Thanks!
Qi Yao

**Comment by wang-xinyu** [comment]
The deconv used in yolo here should be fast, because it's group deconv, to replace upsample layer in yolo.

For trt4 or trt7, I think it should be similar.

You can test the `trt4` branch of this repo.

**Comment by yaoqi-zd** [comment]
@wang-xinyu thx, I'll try.

**Comment by pribadihcr** [comment]
@yaoqi-zd How did you print the ms time in [TRT]?  thanks

**Comment by yaoqi-zd** [comment]
the picture above is borrowed from another [issue](https://forums.developer.nvidia.com/t/deconvolution-layer-runs-super-slow-in-tensorrt/61894/2). However, tensorrt provide a piece of profiler code in the official sample, you can find that.
