### ISSUE TITLE
In file included from /tensorrtx/yolov5/plugin/yololayer.h:4,

### ISSUE THREAD

**Issue by liguang1026** [wang-xinyu/tensorrtx#1352]
In file included from/tensorrtx/yolov5/plugin/yololayer.h:4,
                 from /tensorrtx/yolov5/plugin/yololayer.cu:1:
/tensorrtx/yolov5/src/macros.h:3:10: fatal error: NvInfer.h: No such file or directory
    3 | #include <NvInfer.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/myplugins.dir/build.make:63: CMakeFiles/myplugins.dir/plugin/yololayer.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/myplugins.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by liguang1026** [comment]
When I run make, I report an error

**Comment by deepAiCheng** [comment]
> When I run make, I report an error

include_directories（/usr/local/TensorRT-8.4.2.4/include/）这样，你在CMakelists文件中没添加吧？或者添加路径不对找不到

**Comment by liguang1026** [comment]
我添加了也不行， 我在另一台电脑上什么都没有配置就直接能用
