### ISSUE TITLE
windows10+yolov4+nullptr

### ISSUE THREAD

**Issue by LionelLeee** [wang-xinyu/tensorrtx#136]
首先感谢您的贡献。但我遇到下面的问题，希望您可以解答。
![image](https://user-images.githubusercontent.com/38831106/89994533-d42d7c80-dcba-11ea-944f-865bd4ad9b97.png)
基本按照指导编译成功的windows版本，但是报了上面的错误。weights是来自于ALexAB的，cfg是ul.../yolov3/.有可能是什么原因造成的？

**Comment by wang-xinyu** [comment]
执行gen_wts.py了吗

**Comment by LionelLeee** [comment]
是的，我事先已经通过gen_wts.py获取到yolov4.wts

**Comment by wang-xinyu** [comment]
看下yolov4.wts的前几行内容

**Comment by LionelLeee** [comment]
![image](https://user-images.githubusercontent.com/38831106/90115292-75cdd000-dd86-11ea-8901-ddb7e7f9ac7c.png)
![image](https://user-images.githubusercontent.com/38831106/90115513-c9d8b480-dd86-11ea-8f7d-1ca113b17f26.png)
我生成了两个不同的wts，测试了两种都不可以

**Comment by wang-xinyu** [comment]
用的是这个cfg文件吗https://github.com/ultralytics/yolov3/blob/master/cfg/yolov4.cfg

还是自己做过修改的？

**Comment by LionelLeee** [comment]
有一个是您指定这个， 另一个是在此基础上将batch=64；subdivisions=8两个修改为1，但两个都没有成功运行

**Comment by wang-xinyu** [comment]
https://github.com/ultralytics/yolov3这个项目用的是最新的commit吗？

还有yolov4.weights是AlexeyAB官方的吗？

**Comment by LionelLeee** [comment]
是的，weights也是来源于官方，是否有可能是编译的问题？

**Comment by wang-xinyu** [comment]
你的pytorch版本是多少

**Comment by wang-xinyu** [comment]
你的yolov4.wts应该放在tensorrtx/yolov4/build目录下，因为是在release目录下执行的，或者改一下代码里面yolov4.wts的路径

**Comment by LionelLeee** [comment]
十分感谢，确实是yolov4.wts放错了位置，现在可以有不同的输出了。但显示出下面的错误，这个cuDNN相关可以在哪里修改吗？
![image](https://user-images.githubusercontent.com/38831106/90207318-86c72180-de18-11ea-812e-cd211452b009.png)

**Comment by wang-xinyu** [comment]
这是warning，应该不影响，直接跑下面的试试

**Comment by LionelLeee** [comment]
已经运行出结果，非常感谢。但这个是否可以测试视频

**Comment by wang-xinyu** [comment]
测试视频需要自己改代码实现
