### ISSUE TITLE
yolov8 .wts trans .engine Error

### ISSUE THREAD

**Issue by albert99zhy** [wang-xinyu/tensorrtx#1367]
## Env

- GPU, Xavier NX, 
- OS, e.g. Ubuntu20.04,
- Cuda version, 11.4
- TensorRT version: 8.5

## About this repo

- which branch/tag/commit are you using?
- latest
- which model? yolov5, retinaface?
- yolov8

## Your problem

- what is your command? 
- sudo ./yolov8 -s yolov8p2.wts yolov8p2.engine n
- what's your output?
- Err: kernel weights has count 0 but 36864 was expected. 
- I used dataset Visdrone to train the model yolov8-p2.yaml. And I searched that it is the kNumClass argument not true. But I changed it conform to the dataset's 10 classes, error still existed.What is the problem and how should it be fixed, please? Looking forward your reply. Please.

**Comment by wang-xinyu** [comment]
@lindsayshuo do we support yolov8-p2?

**Comment by lindsayshuo** [comment]
> not support yet

**Comment by albert99zhy** [comment]
I got it. Thanks.If I want to cater for my changed yolov8 model， which files should i rewrite to make it work perfectly？

**Comment by wang-xinyu** [comment]
yolov8/src/model.cpp

> I got it. Thanks.If I want to cater for my changed yolov8 model， which files should i rewrite to make it work perfectly？

**Comment by albert99zhy** [comment]
I've modified the structure I need based on the code of yolov8n in the models.cpp. WTS files are transferred out via gen-wts.py. Kclassnum has also been modified, but the problem in the picture still occurs. What else I need to do to get the .engine file successfully?
![IMG_2215](https://github.com/wang-xinyu/tensorrtx/assets/126946332/9657d711-3e2b-49b8-864e-0d1f2f688a2c)
![IMG_2216](https://github.com/wang-xinyu/tensorrtx/assets/126946332/259635a6-d5d1-4b6f-9b01-d1587f4aa3ed)

**Comment by wang-xinyu** [comment]
Still, the model structure defined in cpp is not matched with pytorch. You can try to debug layer by layer.
