### ISSUE TITLE
加载生成的权重报错

### ISSUE THREAD

**Issue by zhaoguoqing12** [wang-xinyu/tensorrtx#137]

**Comment by zhaoguoqing12** [comment]
![image](https://user-images.githubusercontent.com/47818312/90090661-2b812a80-dd57-11ea-8c36-c2f33a8b56e0.png)

**Comment by zhaoguoqing12** [comment]
make的时候出现一个警告是否有关系
![image](https://user-images.githubusercontent.com/47818312/90090689-418eeb00-dd57-11ea-96dd-f89b1dd0c0c6.png)

**Comment by wang-xinyu** [comment]
.wts 文件没找到

**Comment by zhaoguoqing12** [comment]
> .wts文件没找到

make之后，但是好像并没有产生.wts文件

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#how-to-run-yolov5s-as-example

看下步骤操作，wts文件是从pytorch项目生成的

**Comment by zhaoguoqing12** [comment]
> https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#how-to-run-yolov5s-as-example
> 
> 看下步骤操作，wts文件是从pytorch项目生成的

谢谢，我是生成了.wts，然后根据步骤操作的。
![image](https://user-images.githubusercontent.com/47818312/90091739-c7ac3100-dd59-11ea-9996-5e7479eb565f.png)
![image](https://user-images.githubusercontent.com/47818312/90091745-cc70e500-dd59-11ea-8934-95f306f9de34.png)
![image](https://user-images.githubusercontent.com/47818312/90091758-d266c600-dd59-11ea-8028-adf1151bc614.png)

**Comment by wang-xinyu** [comment]
wts名字不对，如果过是s，就是yolov5s.wts，  或者改代码里面的名字

**Comment by zhaoguoqing12** [comment]
> wts名字不对，如果过是s，就是yolov5s.wts，或者改码里面的名字
谢谢，明白了
