### ISSUE TITLE
apply confidence threshold on yolov5 and access to result parameters.

### ISSUE THREAD

**Issue by SJavad** [wang-xinyu/tensorrtx#1373]
how can I apply the **confidence threshold** for yolov5 object detection? 
how can I set the **max_detection** like yolov5 on PyTorch to detect only higher confidences? 
how can I access the x, y, w, and h of predicted boxes?

**Comment by wang-xinyu** [comment]
Pls check this function https://github.com/wang-xinyu/tensorrtx/blob/3271725dd45d9597918bfccf4492e667bfda01b9/yolov5/yolov5_det.cpp#L204

**Comment by SJavad** [comment]
> Pls check this function
> 
> https://github.com/wang-xinyu/tensorrtx/blob/3271725dd45d9597918bfccf4492e667bfda01b9/yolov5/yolov5_det.cpp#L204

thank you so much for your help.
