### ISSUE TITLE
yolov8 network structure problem, build engine error

### ISSUE THREAD

**Issue by yupeng-2003** [wang-xinyu/tensorrtx#1375]
Hi, I found some problems while running the code.

In the output section of the model.cpp file, for class branches (such as conv22_cv3_0_0, conv22_cv3_0_1, etc.), the channel number ch should be max(C1,kNumClass), where C1 is the number of channels in the smallest layer (P3) of the feature pyramid. 

The official code for yolov8 is 
`c2, c3 = max((16, ch[0] // 4, self.reg_max * 4)), max(ch[0], min(self.nc, 100)) # channels`

Specifically, for the official yolov8n, the channel number of the smallest layer (P3) of the feature pyramid is 64, and kNumClass is 80, so the output channel of the CBL module of the class branch should be 80, not 64. 

That is, the original code is correct. And if possible, a max function can be added here to adapt the number of output channels for different models.

In addition, the number of input channels in the C2F module of the head layer is incorrect, even though this is not used later.

**Comment by jwee1369** [comment]
i have this issue too, @yupeng-2003 did you manage to fix it?

**Comment by yupeng-2003** [comment]
> i have this issue too, @yupeng-2003 did you manage to fix it?

Follow the formula `max(ch[0], min(self.nc, 100))`  to modify the output channel number of class branch.

I uploaded the modified code to [model.cpp](https://github.com/yupeng-2003/yolo/blob/main/model.cpp).

**Comment by jwee1369** [comment]
@yupeng-2003 thanks for sharing the fix, it's working now! 

I'm pretty new to this, but could you refer me to the part of the implementation of the yolov8n architecture where you mentioned above (c2, c3 = max((16, ch[0] // 4, self.reg_max * 4)), max(ch[0], min(self.nc, 100)) # channels). I'm trying to map the cpp implementation with ultralytics implementation. i could only find the /cfg/models/v8/yolov8.yaml file

thanks again

**Comment by yupeng-2003** [comment]
> @yupeng-2003 thanks for sharing the fix, it's working now!
> 
> I'm pretty new to this, but could you refer me to the part of the implementation of the yolov8n architecture where you mentioned above (c2, c3 = max((16, ch[0] // 4, self.reg_max * 4)), max(ch[0], min(self.nc, 100)) # channels). I'm trying to map the cpp implementation with ultralytics implementation. i could only find the /cfg/models/v8/yolov8.yaml file
> 
> thanks again

**Comment by yupeng-2003** [comment]
It's in nn/modules/head.py.

**Comment by jwee1369** [comment]
> It's in nn/modules/head.py.

thank you!

**Comment by wang-xinyu** [comment]
@yupeng-2003 If this can fix your issue, can  you please raise a PR?  

cc: @lindsayshuo

**Comment by yupeng-2003** [comment]
@wang-xinyu sure, I just submitted it.
