### ISSUE TITLE
Confused about Deformable convolution

### ISSUE THREAD

**Issue by navid-hoseini** [wang-xinyu/tensorrtx#1376]
Hi, 
I am trying to understand the deformable conv plugin. However, I can't find the correspondence between the descriptions in [Deformable ConvNets v2: More Deformable, Better Results](https://arxiv.org/abs/1811.11168) paper and the plugin code in [tensorrtx/centernet/dcnv2Plugin](https://github.com/wang-xinyu/tensorrtx/tree/master/centernet/dcnv2Plugin). As long as I understand, the paper says that a deformable convolution consists of 2 standard convolutions. The 1st convolution computes $\Delta p_k$ and $\Delta m_k$ which are then used to determine the image pixel (deformed) coordinates that will be multiplied with the kernel (2nd convolution). I believe the deform conv implementation should be in [DeformableConvolutionalLayer::enqueue()](https://github.com/wang-xinyu/tensorrtx/blob/master/centernet/dcnv2Plugin/dcnv2Plugin.cpp#L102) method but I don't fully understand the code. I have the following questions:
1. What is the purpose of the second call [cublasSgemm()](https://github.com/wang-xinyu/tensorrtx/blob/master/centernet/dcnv2Plugin/dcnv2Plugin.cpp#L135) in ::enqueue method?
2. What is the purpose of [modulated_deformable_im2col_cuda()](https://github.com/wang-xinyu/tensorrtx/blob/master/centernet/dcnv2Plugin/dcnv2Plugin.cpp#L124) function?
3. Where in the plugin code, $\Delta p_k$ and $\Delta m_k$ (equation 1 of the paper mentioned above) are computed?
My apologies but I'm kind of newbie in Cuda programming. Any hint is highly appreciated. Thanks in advance.

**Comment by wang-xinyu** [comment]
@SsisyphusTao Please help here.
