### ISSUE TITLE
显存释放问题

### ISSUE THREAD

**Issue by wongts44** [wang-xinyu/tensorrtx#138]
您好，我在重复进行初始化，推理，释放，反复运行yoloV3工程时候遇到显存增加的问题，请问如何解决？

**Comment by wang-xinyu** [comment]
是反复运行进程，还是写的循环来重复这几个过程？

**Comment by wongts44** [comment]
只有一个进程，然后通过循环来重复以上过程。

**Comment by wang-xinyu** [comment]
每次循环会涨多少？ 长时间会不会稳定？

**Comment by wongts44** [comment]
yoloV3 linux下每轮涨2M，跑了40轮还是会涨

**Comment by wang-xinyu** [comment]
是yolov3还是yolov3-spp？

**Comment by wongts44** [comment]
yolov3和yolov3-tiny也都有这个情况

**Comment by wang-xinyu** [comment]
我刚看了代码，yolov3和yolov3-tiny没什么问题，   显存如果泄漏也就是在自己写的plugin里面，但是看了没有问题。      

也有可能是cuda问题，不是真泄漏，建议长时间测试看看，比如跑一天。

或者你那边也可以调试看看，也看看代码有什么未释放的bug

**Comment by wongts44** [comment]
好的，我这边按你的建议再测试下，谢谢！

**Comment by ayicherry** [comment]
@wongts44 请问你用的GPU卡的型号是什么，我也遇到了一样的问题，通过调试代码发现是context->executeV2这个函数会占用显存，并且不会释放，导致显存不断增加。但是我只有在1080Ti的卡上会有该问题，同样的代码在2080，2080Ti，1660等GPU卡上都没有问题，不知道你的是不是该情况。

**Comment by wongts44** [comment]
谢谢回复，我们通过升级到RT7.2版本解决了这个问题



---原始邮件---
发件人: "ayicherry"<notifications@github.com&gt;
发送时间: 2021年1月13日(周三) 下午4:54
收件人: "wang-xinyu/tensorrtx"<tensorrtx@noreply.github.com&gt;;
抄送: "wongts44"<wongts44@vip.qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [wang-xinyu/tensorrtx] 显存释放问题 (#138)




 
@wongts44 请问你用的GPU卡的型号是什么，我也遇到了一样的问题，通过调试代码发现是context-&gt;executeV2这个函数会占用显存，并且不会释放，导致显存不断增加。但是我只有在1080Ti的卡上会有该问题，同样的代码在2080，2080Ti，1660等GPU卡上都没有问题，不知道你的是不是该情况。

**Comment by wongts44** [comment]
@ayicherry 谢谢回复，我们通过升级到RT7.2版本解决了这个问题，您说的context->executeV2，我没有使用到

**Comment by ayicherry** [comment]
> @ayicherry 谢谢回复，我们通过升级到RT7.2版本解决了这个问题，您说的context->executeV2，我没有使用到

推断内部用的context->executeV2或者context->enqueueV2，那我也去用RT7.2的版本试一下，谢谢告知。

**Comment by wongts44** [comment]
@ayicherry 推断我这边没有用到这个，用的作者写的方式 enqueue

**Comment by ayicherry** [comment]
> @ayicherry 推断我这边没有用到这个，用的作者写的方式 enqueue

明白，一个是同步方式，一个是异步方式。应该就是TensorRT低版本的Bug，我这边刚才试了一下新版本，也没有问题了。
