### ISSUE TITLE
Unable to load weight file

### ISSUE THREAD

**Issue by WangQingchen123** [wang-xinyu/tensorrtx#1386]
I have trained the resnet50.wts model on a Windows platform and deployed it on the Jetson NX development board. When I run `python3 rennet50.py -s`, I encounter error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte`. When I train the resnet50.wts model on the Jetson development board, I encounter error below.
```shell
Loading weights: ./model.wts
Traceback (most recent call last):
  File "resnet50.py", line 275, in <module>
    APIToModel(BATCH_SIZE)
  File "resnet50.py", line 236, in APIToModel
    engine = create_engine(maxBatchSize, builder, config, trt.float32)
  File "resnet50.py", line 142, in create_engine
    weight_map = load_weights(WEIGHT_PATH)
  File "resnet50.py", line 33, in load_weights
    count = int(lines[0])
ValueError: invalid literal for int() with base 10: b'PK\x03\x04\x00\x00\x08\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x14\x00model/data.pklFB\x10\x00ZZZZZZZZZZZZZZZZ\x80\x02c__builtin__'
wqc@wqc-desktop:~/Desktop/tensorrtx-master/resnet$ 
```

**Comment by wang-xinyu** [comment]
How did you get the wts file?  Did you use [pytorchx](https://github.com/wang-xinyu/pytorchx/tree/master/resnet)?

**Comment by WangQingchen123** [comment]
Thank you, I've solved the problem, I had previously added the code directly to the end of `pytorchx-master\resnet\resnet50\resnet50.py`
```python
save_path='model.wts'
torch.save(net.state_dict(),save_path)
``` 
So the exported wts file is garbled. But the wts file generated using `pytorchx-master\resnet\resnet50\inference.py` is all right!
