### ISSUE TITLE
YOLOv8 后处理的 IOU 计算部分

### ISSUE THREAD

**Issue by emptysoal** [wang-xinyu/tensorrtx#1389]
大佬您好，您的项目让我受益匪浅，但是我在做 YOLOv8 TensorRT 转换时，发现了一点小瑕疵，具体如下：
首先，发现转 TensorRT 后，和官方的 pytorch 推理相比，出现很多漏检；
然后，我发现问题出在后处理 NMS 中的 IOU 计算部分，因为 YOLOv8 输出 bbox 格式为 [left, top, right, bottom]，不同于以往 YOLOv5 的 [center_x, center_y, width, height] 格式，但本项目中 YOLOv8 后处理的 IOU 计算仍然是按以往方式计算的，就导致了 IOU 结果的不准确。

因此，我把 postprocess.cpp 文件中的 iou 函数改写成如下写法：

static float iou(float lbox[4], float rbox[4]) {
    float interBox[] = {
            (std::max)(lbox[0], rbox[0]), //left
            (std::min)(lbox[2], rbox[2]), //right
            (std::max)(lbox[1], rbox[1]), //top
            (std::min)(lbox[3], rbox[3]), //bottom
    };

    if (interBox[2] > interBox[3] || interBox[0] > interBox[1])
        return 0.0f;

    float interBoxS = (interBox[1] - interBox[0]) * (interBox[3] - interBox[2]);
    float unionBoxS = (lbox[2] - lbox[0]) * (lbox[3] - lbox[1]) + (rbox[2] - rbox[0]) * (rbox[3] - rbox[1]) - interBoxS;
    return interBoxS / unionBoxS;
}

改写后，推理结果就没有问题了。

**Comment by wang-xinyu** [comment]
@lindsayshuo 帮忙确认下是否有这个问题？

**Comment by lindsayshuo** [comment]
> YOLOv8 输出 bbox 格式为 [left, top, right, bottom]

是的，我在写gpu后处理https://github.com/wang-xinyu/tensorrtx/blob/c997e35710ff0230ae6361d9ba3b9ae82ed3a7d8/yolov8/src/postprocess.cu#L24中用的是这种格式，cpu的没有修正

**Comment by wang-xinyu** [comment]
@emptysoal 可以提一个PR修复一下吗？
