### ISSUE TITLE
  engine->destroy();   runtime->destroy(); not work

### ISSUE THREAD

**Issue by ReverseSystem001** [wang-xinyu/tensorrtx#1391]
## Env

- GPU RTX1060ti
- OS, ubuntu 20.04  
- Cuda 11.4
- TensorRT version TensorRT-8.0.1.6

## About this repo

- which branch/tag/commit are you using? yolov5-6.0
- which model? yolov5
https://github.com/wang-xinyu/tensorrtx/blob/yolov5-v7.0/yolov5/yolov5_det.cpp
in the 220 line,when I and sleep(10) function to test the cuda memory, the context destroy successfully, but   engine->destroy();   runtime->destroy(); not work

examples:
 sleep(10);  // watch -n 1 nvidia-smi  (to watch the change of GPU memory)
  context->destroy();  // the gpu memory destroyed successfully
 sleep(10);
 engine->destroy();  // not work
sleep(10);  
runtime->destroy();  // not work

**Comment by emptysoal** [comment]
try :
delete context;
delete engine;
delete runtime;
tensorrt 8.0+ recommend to use delete

See official documentation:
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_cuda_engine.html

content is as follow :

Destroy this object;.


    Deprecated in TRT 8.0. Superseded by delete.
Warning
    Calling destroy on a managed pointer will result in a double-free error.

**Comment by ReverseSystem001** [comment]
> try : delete context; delete engine; delete runtime; tensorrt 8.0+ recommend to use delete
> 
> See official documentation: https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_cuda_engine.html
> 
> content is as follow :
> 
> Destroy this object;.
> 
> ```
> Deprecated in TRT 8.0. Superseded by delete.
> ```
> 
> Warning Calling destroy on a managed pointer will result in a double-free error.

I tryed TensorRT-8.2.5.1.Linux.x86_64-gnu.cuda-11.4.cudnn8.2/TensorRT-8.2.5.1 and change the code to delete, still not work, and my yolov5 tag version is v6.0

**Comment by wang-xinyu** [comment]
Pls try yolov5-v7.0

**Comment by ReverseSystem001** [comment]
doesn't work too. tried v5 and v6



---Original---
From: "Wang ***@***.***&gt;
Date: Wed, Jan 3, 2024 18:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wang-xinyu/tensorrtx]   engine-&gt;destroy();   runtime-&gt;destroy();not work (Issue #1391)




 
Pls try yolov5-v7.0
