### ISSUE TITLE
使用yolov8_det_trt.py推理报错

### ISSUE THREAD

**Issue by HouLingLXH** [wang-xinyu/tensorrtx#1394]
我使用yolov8s.pt 作为与训练模型，对自己的数据集进行训练(20分类)， 拿到best.pt之后，按照教程转换得到best.engine

用best.engine，通过yolov8_det.cpp编译的yolov8_det可以进行正常推理
但是使用yolov8_det_trt.py推理的时候，报错：
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_det_trt.py", line 389, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
  File "yolov8_det_trt.py", line 183, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range

然后我打印result_classid： 
            result_boxes, result_scores, result_classid = self.post_process(
                output[i * 6001: (i + 1) * 6001], batch_origin_h[i], batch_origin_w[i]
            )
            print("result_boxes",result_boxes)
结果：
          result_classid [317.14676 288.79666 297.1754  297.7262  287.24265 289.5717  235.54599
           235.45467 235.7982  253.12482   0.     ]
发现里面都是小数，大小也不对

大佬，这里要怎么改啊？

**Comment by HouLingLXH** [comment]
When I change some code, it's working:

from:
```
            result_boxes, result_scores, result_classid = self.post_process(
                output[i * 6001: (i + 1) * 6001], batch_origin_h[i], batch_origin_w[i]
            )
```
to :

```
            LEN_ALL_RESULT = 38001
            result_boxes, result_scores, result_classid = self.post_process(
                output[i * LEN_ALL_RESULT: (i + 1) * LEN_ALL_RESULT], batch_origin_h[i], batch_origin_w[i]
            )
```

And

from
`        pred = np.reshape(output[1:], (-1, 6))[:num, :]`
to 
`        pred = np.reshape(output[1:], (-1, 38))[:num, :]`


Is that right ?

**Comment by wang-xinyu** [comment]
@HouLingLXH 最近支持了yolov8-seg，所以输出tensor尺寸变了，应该是这个问题，帮忙提个PR吧

**Comment by wang-xinyu** [comment]
The issue has been fixed on the master branch.
