### ISSUE TITLE
Where can I modify the confidence calculation logic in yolov5 7.0 detect inference?

### ISSUE THREAD

**Issue by hengyanchen** [wang-xinyu/tensorrtx#1399]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- yolov5 7.0

## My problem

你好大哥，我想把最终置信度计算方式由bbox conf* classify conf 修改为分类的置信度，但是没有找对对映的代码，你能指点下吗

**Comment by wang-xinyu** [comment]
Here:
https://github.com/wang-xinyu/tensorrtx/blob/f39f2c14336768e1dccce0b17a3604c4bbbcd1a2/yolov5/plugin/yololayer.cu#L203

**Comment by hengyanchen** [comment]
Thanks !
