### ISSUE TITLE
fatal error: NvInfer.h: No such file or directory

### ISSUE THREAD

**Issue by z393** [wang-xinyu/tensorrtx#14]
fatal error: NvInfer.h: No such file or directory
 #include "NvInfer.h"
          ^~~~~~~~~~~
compilation terminated.
CMake Error at myplugins_generated_mish.cu.o.Debug.cmake:219 (message):
  Error generating
  /media/tensorrtx/yolov4/build/CMakeFiles/myplugins.dir//./myplugins_generated_mish.cu.o

CMakeFiles/myplugins.dir/build.make:70: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_mish.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_mish.cu.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
Do you have tensorrt installed on your machine?  NvInfer.h is in package libnvinfer-dev
```
user@user-SYS-7048GR:~$ dpkg -L libnvinfer-dev 
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libnvinfer_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_compiler_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_executor_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_pattern_library_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_pattern_runtime_static.a
/usr/include
/usr/include/x86_64-linux-gnu
/usr/include/x86_64-linux-gnu/NvInfer.h
/usr/include/x86_64-linux-gnu/NvInferRuntime.h
/usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h
/usr/include/x86_64-linux-gnu/NvInferVersion.h
/usr/include/x86_64-linux-gnu/NvUtils.h
/usr/share
/usr/share/doc
/usr/share/doc/libnvinfer-dev
/usr/share/doc/libnvinfer-dev/copyright
/usr/share/doc/libnvinfer-dev/changelog.Debian
/usr/lib/x86_64-linux-gnu/libmyelin.so
/usr/lib/x86_64-linux-gnu/libnvinfer.so
```

**Comment by wangtianlong1994** [comment]
@wang-xinyu 

After I installed tensorrt, the same error still occurred

My version of tensorrt is 5.1.5.0

When I input dpkg - L libnvinfer dev

Indicates that libnvinfer dev is not installed

Thank you for your help

**Comment by wang-xinyu** [comment]
@wangtianlong1994 It's `libnvinfer-dev`.

**Comment by Gavin-zsr** [comment]
> Do you have tensorrt installed on your machine? NvInfer.h is in package libnvinfer-dev
> 
> ```
> user@user-SYS-7048GR:~$ dpkg -L libnvinfer-dev 
> /.
> /usr
> /usr/lib
> /usr/lib/x86_64-linux-gnu
> /usr/lib/x86_64-linux-gnu/libnvinfer_static.a
> /usr/lib/x86_64-linux-gnu/libmyelin_compiler_static.a
> /usr/lib/x86_64-linux-gnu/libmyelin_executor_static.a
> /usr/lib/x86_64-linux-gnu/libmyelin_pattern_library_static.a
> /usr/lib/x86_64-linux-gnu/libmyelin_pattern_runtime_static.a
> /usr/include
> /usr/include/x86_64-linux-gnu
> /usr/include/x86_64-linux-gnu/NvInfer.h
> /usr/include/x86_64-linux-gnu/NvInferRuntime.h
> /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h
> /usr/include/x86_64-linux-gnu/NvInferVersion.h
> /usr/include/x86_64-linux-gnu/NvUtils.h
> /usr/share
> /usr/share/doc
> /usr/share/doc/libnvinfer-dev
> /usr/share/doc/libnvinfer-dev/copyright
> /usr/share/doc/libnvinfer-dev/changelog.Debian
> /usr/lib/x86_64-linux-gnu/libmyelin.so
> /usr/lib/x86_64-linux-gnu/libnvinfer.so
> ```

我查找这个包后，显示我没有安装这个包，但是我是安装好TensorRT的，请问这种情况该怎么解决

**Comment by apple2333cream** [comment]
我也遇到这个问题了，在cmakelist文件中添加tensorRT的安装路径之后就不报错了

include_directories(/home/wzp/project/trt/TensorRT-7.0.0.11/include)
link_directories(/home/wzp/project/trt/TensorRT-7.0.0.11/lib)

![Uploading image.png…]()

**Comment by dcdethan** [comment]
> 我也遇到这个问题了，在cmakelist文件中添加tensorRT的安装路径之后就不报错了
> 
> include_directories(/home/wzp/project/trt/TensorRT-7.0.0.11/include)
> link_directories(/home/wzp/project/trt/TensorRT-7.0.0.11/lib)

请问在哪个文件内，如何添加呢？
