### ISSUE TITLE
yolov8s-seg.wts to yolov8s-seg.engine transform error

### ISSUE THREAD

**Issue by HengLoveYi** [wang-xinyu/tensorrtx#1400]
## Env

- RTX4000
- Ubuntu18.04, etc.
- Cuda 11.7
- TensorRT 8.6.0.12
- pytorch 1.12
- torch 0.13.0

## About this repo

- which branch/tag/commit are you using?-->  master
- which model? -->yolov8s-seg.pt

## Your problem

- what is your command?--> ./yolov8_seg -s yolov8s-seg.wts yolov8s-seg.engine s
- what's your output?-->
![Screenshot from 2023-11-07 22-41-50](https://github.com/wang-xinyu/tensorrtx/assets/42888342/312a1da0-fe34-4f29-83d9-4cafc1678777)

- what output do you expect?--> do you have completed yolov8s-seg.pt to tensorrt transform and deply? I have met this problem, hoping to receive your reply, best regards!

**Comment by wang-xinyu** [comment]
Have you tried the official model?

**Comment by HengLoveYi** [comment]
> Have you tried the official model?

Yes, I used the yolov8 official weight pt(yolov8s-seg.pt) to convert

**Comment by wang-xinyu** [comment]
@Rex-LK Please take a look.

**Comment by RaidenCJ** [comment]
我用官方模型（640 X 640）和自己做的模型（640 X 640）不会报这个错误，用自己做的模型（960 X 960）也报这个错误：
[11/20/2023-15:58:28] [E] [TRT] 4: [shapeContext.cpp::nvinfer1::builder::reshapeCanFaultHelper::<lambda_87ad3b929fe52b49c0129bfe558f8fdd>::operator ()::3546] Error Code 4: Shape Error (reshape changes volume. Reshaping [32,120,120] to [32,6400].)
[11/20/2023-15:58:28] [E] [TRT] 4: [network.cpp::nvinfer1::Network::validate::2977] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 317) [Shuffle]_output, because the network is not valid.)

请问是需要修改哪边适配别的模型输入尺寸吗？

**Comment by HengLoveYi** [comment]
> 我用官方模型（640 X 640）和自己做的模型（640 X 640）不会报这个错误，用自己做的模型（960 X 960）也报这个错误： [11/20/2023-15:58:28] [E] [TRT] 4: [shapeContext.cpp::nvinfer1::builder::reshapeCanFaultHelper::<lambda_87ad3b929fe52b49c0129bfe558f8fdd>::operator ()::3546] Error Code 4: Shape Error (reshape changes volume. Reshaping [32,120,120] to [32,6400].) [11/20/2023-15:58:28] [E] [TRT] 4: [network.cpp::nvinfer1::Network::validate::2977] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 317) [Shuffle]_output, because the network is not valid.)
> 
> 请问是需要修改哪边适配别的模型输入尺寸吗？

maybe you can try to modify the config.h file in src directory
![Screenshot from 2023-11-22 16-35-45](https://github.com/wang-xinyu/tensorrtx/assets/42888342/48490a27-350f-4b92-aa6a-07d2b9c56bcc)

**Comment by HengLoveYi** [comment]
> 我用官方模型（640 X 640）和自己做的模型（640 X 640）不会报这个错误，用自己做的模型（960 X 960）也报这个错误： [11/20/2023-15:58:28] [E] [TRT] 4: [shapeContext.cpp::nvinfer1::builder::reshapeCanFaultHelper::<lambda_87ad3b929fe52b49c0129bfe558f8fdd>::operator ()::3546] Error Code 4: Shape Error (reshape changes volume. Reshaping [32,120,120] to [32,6400].) [11/20/2023-15:58:28] [E] [TRT] 4: [network.cpp::nvinfer1::Network::validate::2977] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 317) [Shuffle]_output, because the network is not valid.)
> 
> 请问是需要修改哪边适配别的模型输入尺寸吗？

maybe you can try to modify the config.h file in src directory
![Uploading Screenshot from 2023-11-22 16-35-45.png…]()

**Comment by HengLoveYi** [comment]
> 我用官方模型（640 X 640）和自己做的模型（640 X 640）不会报这个错误，用自己做的模型（960 X 960）也报这个错误： [11/20/2023-15:58:28] [E] [TRT] 4: [shapeContext.cpp::nvinfer1::builder::reshapeCanFaultHelper::<lambda_87ad3b929fe52b49c0129bfe558f8fdd>::operator ()::3546] Error Code 4: Shape Error (reshape changes volume. Reshaping [32,120,120] to [32,6400].) [11/20/2023-15:58:28] [E] [TRT] 4: [network.cpp::nvinfer1::Network::validate::2977] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 317) [Shuffle]_output, because the network is not valid.)
> 
> 请问是需要修改哪边适配别的模型输入尺寸吗？

maybe you can try to modify the config.h file in src directory
![Screenshot from 2023-11-22 16-35-45](https://github.com/wang-xinyu/tensorrtx/assets/42888342/5a713843-aa99-47df-a403-9881016cf284)
