### ISSUE TITLE
cuda nms can't filter some bboxes

### ISSUE THREAD

**Issue by asflower** [wang-xinyu/tensorrtx#1401]
https://github.com/wang-xinyu/tensorrtx/blob/f39f2c14336768e1dccce0b17a3604c4bbbcd1a2/yolov8/src/postprocess.cu#L61

In the above referenced code, change the variable i to start from 0 fix this

**Comment by wang-xinyu** [comment]
@lindsayshuo  Please take a look.

**Comment by lindsayshuo** [comment]
> https://github.com/wang-xinyu/tensorrtx/blob/f39f2c14336768e1dccce0b17a3604c4bbbcd1a2/yolov8/src/postprocess.cu#L61
> 
> In the above referenced code, change the variable i to start from 0 fix this

For speed, changing the loop from index 1 to index 0 will increase the calculation time of the first box, resulting in a slower calculation speed for the entire NMS. However, due to the usually small number of the first box, it has little impact in practical use.
