### ISSUE TITLE
使用程序将wts转成engine时报错，但是engine可以生成也可以使用

### ISSUE THREAD

**Issue by Mr-MoNET** [wang-xinyu/tensorrtx#1405]
## Env
- RTX2070
- Win10
- CUDA 11.6
- TensorRT 8.6.1.6

## About this repo
- yolov5-v6.0

## Your problem
我在使用程序将wts转成engine时报错，但是engine可以生成也可以使用；报错详细信息如下：
(个人感觉这个报错只是提示回收方式不得当，但是对模型本身精度转换没有影响，因此这行ERROR是在转换完成后才提示的。想请教下大佬这个错误是什么原因造成的，希望能学习一下)
[11/13/2023-19:06:28] [E] [TRT] 3: [builder.cpp::nvinfer1::builder::Builder::~Builder::341] Error Code 3: API Usage Error (Parameter check failed at: builder.cpp::nvinfer1::builder::Builder::~Builder::341, condition: mObjectCounter.use_count() == 1. Destroying a builder object before destroying objects it created leads to undefined behavior.)

![1699880749534](https://github.com/wang-xinyu/tensorrtx/assets/48426139/543b126d-4170-4e67-8d5a-355801f31212)

**Comment by wang-xinyu** [comment]
最新的7.0已经修了这个问题，可以试下

**Comment by Mr-MoNET** [comment]
> 最新的7.0已经修了这个问题，可以试下

好的，十分感谢大佬，我去试试

**Comment by nantututu** [comment]
> 最新的7.0已经修了这个问题，可以试下

你好,yolo7也有这个问题

**Comment by nantututu** [comment]
> 最新的7.0已经修了这个问题，可以试下

你好,yolov7也存在相同的问题

**Comment by wang-xinyu** [comment]
@nantututu 试下yolov5-7.0，不是yolov7

**Comment by Zhang-Wen-chao** [comment]
> @nantututu 试下yolov5-7.0，不是yolov7

在tag yolov5-7.0下面的yolov7,我还是遇到了这个问题。请问哪个分支或者tag的yolov7是没有这个错误的？

**Comment by wang-xinyu** [comment]
@Zhang-Wen-chao yolov7，把 delete builder放到delete engine之后试试，如果ok帮忙提个pr吧。

 https://github.com/wang-xinyu/tensorrtx/blob/62050de3e7a6a7d88d93eb40dbea7cef2df777ac/yolov7/main.cpp#L47

**Comment by Zhang-Wen-chao** [comment]
> > 最新的7.0已经修了这个问题，可以试下
> 
> 你好,yolov7也存在相同的问题

依照tag yolov5-7.0 的 yolov5_det.cpp 的文件，把 delete engine; 都改为 engine->destroy();

**Comment by Zhang-Wen-chao** [comment]
> @Zhang-Wen-chao yolov7，把 delete builder放到delete engine之后试试，如果ok帮忙提个pr吧。
> 
> https://github.com/wang-xinyu/tensorrtx/blob/62050de3e7a6a7d88d93eb40dbea7cef2df777ac/yolov7/main.cpp#L47

It works. 我已经提交了pr。
我之前改成下面这样，也work了，原来是歪打正着。
  `config->destroy();
  serialized_engine->destroy();
  builder->destroy();`
