### ISSUE TITLE
Yolov8 wrong output shape and performance

### ISSUE THREAD

**Issue by wq9** [wang-xinyu/tensorrtx#1406]
## Env

- GPU: NVIDIA L4
- OS: Ubuntu 22
- Cuda: V11.8.89
- TensorRT version: 8.6.1.6

## About this repo

- Branch: master, commit: f39f2c14336768e1dccce0b17a3604c4bbbcd1a2
- Model: yolov8x-seg

## Your problem

This model's `output0` is wrong shape and possibly different performance. 

In the official yolov8, the output0 is shape(1, 116, 8400). However, the output0's shape in this repo is 38001 (1000 bboxes).

Also, there is performance differences:
This repo yolov8 (right most person has conf:0.75):
![image](https://github.com/wang-xinyu/tensorrtx/assets/3300313/9b137744-0003-4cc8-85d8-b686bc2972ef)
Official yolov8 (right most person has conf:0.32):
![image](https://github.com/wang-xinyu/tensorrtx/assets/3300313/86135736-f816-4415-a787-54b4663fb2e3)

**Comment by wang-xinyu** [comment]
Not wrong shape, we have an extra layer appended to the model, you can check the yololayer.cu.
