### ISSUE TITLE
long inference time to the first images in the folder 

### ISSUE THREAD

**Issue by SJavad** [wang-xinyu/tensorrtx#1407]
## Env

- GPU, Jetson TX1
- OS, Ubuntu 18.04
- Cuda 10.2
- TensorRT 8.2

## About this repo

- yolov5
- model: Yolov5

## Your problem
@wang-xinyu 
- what is your command? e.g. `sudo ./yolov5 -d model.engine`
- Do you know what your output is? -> inference time 328ms , \n inference time 25ms
- what output do you expect? I expect all photos to take the same amount of time to process
 when I try to infer multiple pictures in the folder, the first and second picture takes a long time to infer but other pictures take the same inference time (35ms)
what's the problem?
all pictures have the same dimension. (640,640,3)
Would anyone be able to help me?

**Comment by SJavad** [comment]
Has anyone encountered this problem yet?!
Please can I ask you to guide me!? @wang-xinyu

**Comment by wang-xinyu** [comment]
@SJavad This is as expected, the trt engine needs to warmup.

**Comment by SJavad** [comment]
> @SJavad This is as expected, the trt engine needs to warmup.

So how can I warm up the model?

**Comment by wang-xinyu** [comment]
By running inference on several images.

If the process started again, it needs to warmup again.
