### ISSUE TITLE
看起来Yolov8代码绑定了640X640的input size,请问如何修改支持别的输入尺寸？

### ISSUE THREAD

**Issue by RaidenCJ** [wang-xinyu/tensorrtx#1408]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
RTX2060
- OS, e.g. Ubuntu16.04, Win10, etc.
windows
- Cuda version
11.4
- TensorRT version
8.6.0.12

## About this repo

- which branch/tag/commit are you using?
Master
- which model? yolov5, retinaface?
Yolov8s

## Your problem

看起来Yolov8代码绑定了640X640的input size,请问如何修改支持别的输入尺寸？

**Comment by Rex-LK** [comment]
include/config.h里面可以修改输入尺寸，可以试一试！

**Comment by RaidenCJ** [comment]
> include/config.h里面可以修改输入尺寸，可以试一试！

你们试过么？config改了960也会报错的，应该是你们在model里面的参数设置（ det0， 1， 2）导致

**Comment by wang-xinyu** [comment]
@RaidenCJ 修改完是否重新编译和重新生成engine了？
