### ISSUE TITLE
In new commit of Yolov5: Unable to load weight file. please check if the .wts file path is right 

### ISSUE THREAD

**Issue by cesarandreslopez** [wang-xinyu/tensorrtx#141]
Hi, just tried your latest commit in yolov5 and get the following while running ./yolov5 -s :

```
yolov5: /app/tensorrtx/yolov5/common.hpp:129: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file. please check if the .wts file path is right!!!!!!"' failed.
```

I've checked and the .wts file is generated and in the right location.

This was not an issue before commit https://github.com/wang-xinyu/tensorrtx/commit/a2056b6bb94ccb4f4774f11ff9d8f6551d963f13

**Comment by cesarandreslopez** [comment]
Nevermind! I failed to define the NET properly in:

```
#define NET s  // s m l x
```

**Comment by muddasar-ali** [comment]
I'm having the same issue, can you please explain how did you fix it?

**Comment by woshichunge12** [comment]
@cesarandreslopez 
Hello, I don’t quite understand how this is solved. Can I talk about it in detail?

**Comment by Transigent** [comment]
The line
`#define NET s  // s m l x`

defines the model size, small, medium, large, extra large. It is used in various places including when loading the .wts file. If you have this set wrong it will look for the wrong .wts file and you will get the error given in the title.
