### ISSUE TITLE
INT8量化问题：最后输出模型时报错，提示"[E] [TRT] 1: Unexpected exception invalid unordered_map<K, T> key"

### ISSUE THREAD

**Issue by Mr-MoNET** [wang-xinyu/tensorrtx#1412]
## Env

- RTX2070
- Win10
- CUDA 11.6
- TensorRT 8.6.1.6

## About this repo

- yolov5-v7.0

## Your problem
大佬，我最近在尝试使用INT8量化yolov5模型的时候报错了，错误信息提示“[E] [TRT] 1: Unexpected exception invalid unordered_map<K, T> key”；但是我切换回FP16或是FP32的推理时，engine文件可以正常生成，使用INT8则不行，麻烦大佬帮忙看下，感谢。
![1701165111676](https://github.com/wang-xinyu/tensorrtx/assets/48426139/9aea6e41-9d94-48c8-b49a-a35e83231dc8)

**Comment by wang-xinyu** [comment]
是否准备校准的图片了？

**Comment by Mr-MoNET** [comment]
> 是否准备校准的图片了？

噢，我好像漏掉这一步了，难怪我说不能转换。但是想请问下大佬，如果是训练自己数据集的情况下，校准图片要准备多少张呢？我现在自己的数据集大概3000张数据。

**Comment by wang-xinyu** [comment]
一般是几百-几千张，可以看下NV官方文档
