### ISSUE TITLE
Are there any plans to implement support for YOLO-NAS?

### ISSUE THREAD

**Issue by Transigent** [wang-xinyu/tensorrtx#1418]
YOLO-NAS is reported to outperform the other SOTA models including Yolov8, v7 etc.  and license is fairly permissive.

https://github.com/Deci-AI/super-gradients/blob/master/YOLONAS.md

Are there any plans to add support for this? Thank you!

**Comment by wang-xinyu** [comment]
No yet, welcome PR.
