### ISSUE TITLE
Error when 'make' in retinaface

### ISSUE THREAD

**Issue by dinhphuong98** [wang-xinyu/tensorrtx#142]
hi Wang-xinyu, thanks for sharing the repo.
I want to build retinaface on my jetson TX2. when i type 'make' in build directory, it show error in bellow
![image](https://user-images.githubusercontent.com/30048503/90232267-9e1d0380-de46-11ea-9612-89ffd173a73a.png)
![image](https://user-images.githubusercontent.com/30048503/90232294-a8d79880-de46-11ea-9fe4-592a620adbff.png)
thanks a lot if you can share solution for me.

**Comment by wang-xinyu** [comment]
master branch is using trt7,   `trt4` branch is using trt4.

Your trt version should be lower than 6.

So please try `trt4` branch of this repo.

**Comment by dinhphuong98** [comment]
thanks for reply, i selected 'trt4' branch, but when i rebuild, it show error like bellow 
![image](https://user-images.githubusercontent.com/30048503/90234704-4d0f0e80-de4a-11ea-9ac6-a320c49b6c25.png)

**Comment by wang-xinyu** [comment]
similar question to https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/faq.md#1-fatal-error-nvinferh-no-such-file-or-directory

**Comment by dinhphuong98** [comment]
hi, thanks a lot
i upgraded env to tensorRT 7 and it worked for me.
