### ISSUE TITLE
Depedency Issue : Mxnet-Numpy

### ISSUE THREAD

**Issue by Athuliva** [wang-xinyu/tensorrtx#1422]
could you please the Mxnet and numpy version that I have to use?

```
File "/usr/local/lib/python3.8/dist-packages/mxnet/numpy/multiarray.py", line 47, in <module>
    from .utils import _get_np_op
  File "/usr/local/lib/python3.8/dist-packages/mxnet/numpy/utils.py", line 37, in <module>
    bool = onp.bool
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by wang-xinyu** [comment]
Which model?

**Comment by Athuliva** [comment]
ArcFace-R100 [Insight Face Google Drive](https://drive.google.com/file/d/1Hc5zUfBATaXUgcU2haUNa7dcaZSw95h2/view)

**Comment by Athuliva** [comment]
i am facing issues in installing Mxnet and converting mxnet model to .wts file. Is there any  mxnet docker image that i can pull?
i saw this on the official webpage  `docker pull mxnet/python:gpu ` but i get this error `Error response from daemon: manifest for mxnet/python:gpu not found: manifest unknown: manifest unknown'

if possible can you share the .wts file?

**Comment by wang-xinyu** [comment]
Did you checkout this commit 3866cd77a6896c934b51ed39e9651b791d78bb57 of insightface?
[3866cd77a6896c934b51ed39e9651b791d78bb57](https://github.com/deepinsight/insightface/tree/3866cd77a6896c934b51ed39e9651b791d78bb57) was using a old version of mxnet
