### ISSUE TITLE
The yolov8n inference and post-processing time increases at the time of processing up to the 20th image and remains

### ISSUE THREAD

**Issue by KY-wwang** [wang-xinyu/tensorrtx#1423]
## Env

- GPU, 1660Ti, laptop
- OS, win11
- Cuda 11.8
- TensorRT 8.6.1.6

## About this repo

- which branch/tag/commit are you using?  yolov5-v7.0
- which model?   yolov8n

## Your problem
In the detection of 72 pictures, in the detection of a certain number of pictures to start reasoning and post-processing time increased significantly, and finally remain in a picture 72ms. should not be a hardware problem, I changed to the server or will have this problem.
在检测72张图片的时候,在检测到某个数量的图片开始推理和后处理时间明显增加,最后保持在一张图片72ms.应该不是硬件的问题,我换成服务器还是会有这个问题

![image](https://github.com/wang-xinyu/tensorrtx/assets/145329847/090d2e76-51ac-42f6-a42b-ec280982b097)
![image](https://github.com/wang-xinyu/tensorrtx/assets/145329847/1919d33f-146c-4f33-853b-bd2b17fd1024)

**Comment by wang-xinyu** [comment]
观测下GPU的频率和功耗有没有变化

**Comment by KY-wwang** [comment]
> 观测下GPU的频率和功耗有没有变化

我在cmd中用nvidia-smi -l 1看了下,整个过程中GPU的功率在4W到24W之间,GPU当前的使用率在1%到17%之间,应该不是gpu的限制引起的
![image](https://github.com/wang-xinyu/tensorrtx/assets/145329847/9fa0ed3e-abda-43b6-b51d-9c0acad93a69)
