### ISSUE TITLE
yolov5s.wts读取时出现报错：Segmentation fault

### ISSUE THREAD

**Issue by chen-del** [wang-xinyu/tensorrtx#1427]
## Env

- GPU, e.g.  RTX3070
- OS, e.g. Ubuntu18.04.
- Cuda version 11.1
- TensorRT version 8.2.1,8
-pycuda 2023.1

## About this repo
所使用的版本为yolov5-7.0

def load_weights(file):
    print(f"Loading weights: {file}")

    assert os.path.exists(file), 'Unable to load weight file.'

    weight_map = {}
    with open(file, "r") as f:
        lines = [line.strip() for line in f]
    count = int(lines[0])
    assert count == len(lines) - 1
    for i in range(1, count + 1):
        splits = lines[i].split(" ")
        name = splits[0]
        cur_count = int(splits[1])
        print("len(splits):", len(splits))  
        print("cur_count:", cur_count)
        
        # assert cur_count + 2 == len(splits)
        assert cur_count +2 == len(splits)
        values = []
        for j in range(2, len(splits)):
            # hex string to bytes to float
            values.append(struct.unpack(">f", bytes.fromhex(splits[j])))
        weight_map[name] = np.array(values, dtype=np.float32)

    return weight_map, 

在使用如下代码读取yolov5-7.0转化的wts, 没有办法正常读取，出现如下
![image](https://github.com/wang-xinyu/tensorrtx/assets/58769772/c0eeaa8b-6285-4a96-aa11-a97617202fd1)

请问需要怎么做才能正常读取使用

**Comment by wang-xinyu** [comment]
yolov5.py是什么文件？你自己写的吗

**Comment by chen-del** [comment]
是的我自己写的，我参照你们提供的模版去转化，发现唯独yolov5读取的时候直接报错了
就是类似使用python去实现这一段读取代码std::map<std::string, Weights> loadWeights(const std::string file)
{
    std::cout << "Loading weights: " << file << std::endl;
    std::map<std::string, Weights> weightMap;

    // Open weights file
    std::ifstream input(file);
    assert(input.is_open() && "Unable to load weight file.");

    // Read number of weight blobs
    int32_t count;
    input >> count;
    assert(count > 0 && "Invalid weight map file.");

    while (count--)
    {
        Weights wt{DataType::kFLOAT, nullptr, 0};
        uint32_t size;

        // Read name and type of blob
        std::string name;
        input >> name >> std::dec >> size;
        wt.type = DataType::kFLOAT;

        // Load blob
        uint32_t* val = reinterpret_cast<uint32_t*>(malloc(sizeof(val) * size));
        for (uint32_t x = 0, y = size; x < y; ++x)
        {
            input >> std::hex >> val[x];
        }
        wt.values = val;
        
        wt.count = size;
        weightMap[name] = wt;
    }

    return weightMap;
}

**Comment by chen-del** [comment]
但是我不知道这个报错怎么去解决，它似乎是读取问题，案例其实就是参照了，yolov5-v7 src 里面的model.cpp 和resnet50.py，然后去实现这些操作
