### ISSUE TITLE
尝试修改输入分辨率后，pt转wts报错

### ISSUE THREAD

**Issue by xjcvip007** [wang-xinyu/tensorrtx#1430]
## Env

- GPU, RTX1060.
- OS, Win10
- Cuda version 11.6
- TensorRT version TensorRT-8.4.1.5.Windows10.x86_64.cuda-11.6.cudnn8.4

## About this repo

- which branch/tag/commit are you using?  master
- which model? yolov5, retinaface?  yolov8

## Your problem
使用Ultralytics工程训练了一个yolov8_seg模型，分辨率为320*320，类别为7类，修改了yolov8的c++工程中的include/config.h文件，分辨率修改从640->320，
![图片](https://github.com/wang-xinyu/tensorrtx/assets/16399125/62eb7cea-b3ae-4f9b-ac41-d6ca6c4a35ac)
重新build工程后，但是在wts转engine时会报错如下图：
![图片](https://github.com/wang-xinyu/tensorrtx/assets/16399125/07bbbbfe-7413-4ae1-be3f-f740fbcf20a4)
请问是不是model.cpp中有一些代码还是有些问题？

**Comment by wang-xinyu** [comment]
@Rex-LK 帮忙看看？

**Comment by Rex-LK** [comment]
> @Rex-LK 帮忙看看？

好的

**Comment by xjcvip007** [comment]
![图片](https://github.com/wang-xinyu/tensorrtx/assets/16399125/ddc5db96-4b56-4a7f-b984-29d990d1b6c3)
应该是head部分没有自适应变化，修改如上后正常了，但是320*320的效果比640*640的差很多

**Comment by Rex-LK** [comment]
> ![图片](https://private-user-images.githubusercontent.com/16399125/299167345-ddc5db96-4b56-4a7f-b984-29d990d1b6c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzM5MjYsIm5iZiI6MTcwNjA3MzYyNiwicGF0aCI6Ii8xNjM5OTEyNS8yOTkxNjczNDUtZGRjNWRiOTYtNGI1Ni00YTdmLWI5ODQtMjlkOTkwZDFiNmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmE4Y2FlODU5ZGI1OWFjN2JlMDA1Y2MxNTZiNDQyZDQxNzg1YTA5YmY4MmY5YWU2NmJkMmMxMWI3MjViNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAw1ziHkAr7PrDinoLOzd9wGz0ClOufvE2lPT4jxkVs) 应该是head部分没有自适应变化，修改如上后正常了，但是320 * 320的效果比640 * 640的差很多

麻烦你这边提个pr让 @wang-xinyu 看看吧

**Comment by wang-xinyu** [comment]
嗯呢， @xjcvip007 帮忙提个PR吧
