### ISSUE TITLE
yolov8模型在1280*1280下出现多检

### ISSUE THREAD

**Issue by BouncyKnight12** [wang-xinyu/tensorrtx#1431]
## Env

- GPU, jetson-agx
- OS, e.g. Ubuntu20.04
- Cuda 11.4
- TensorRT 8.5.2

## About this repo

- which branch/tag/commit are you using?
master
- which model? yolov5, retinaface?
yolov8

## Your problem
使用yolov8n模型在1280*1280分辨率下进行推理，推理结果比pytorch的输出结果多了一个框
pytorch的结果如下
![20240109104200_456_2_131](https://github.com/wang-xinyu/tensorrtx/assets/99583465/b7df27c7-29ac-4df1-b386-8ecbd5d691d8)
tensorrtx的结果如下
![_20240109104200_456_2_131](https://github.com/wang-xinyu/tensorrtx/assets/99583465/1b011d55-2ea6-465e-8e03-8f13a4dd3a1e)

**Comment by wang-xinyu** [comment]
看看confidence是多少？

**Comment by BouncyKnight12** [comment]
在tensorrtx中的confidence是0.566019，使用pytorch设置的confidence是0.25并且打开了half开关

**Comment by BouncyKnight12** [comment]
我使用tensorrt的命令行工具trtexec之间去导出模型也依然存在这样的问题
![20240109104200_456_2_131_trtexec](https://github.com/wang-xinyu/tensorrtx/assets/99583465/c055f194-4117-4040-ab46-b38222f7cd87)

**Comment by wang-xinyu** [comment]
有轻微diff是正常的，可以多跑一些，对比下mAP
