### ISSUE TITLE
yolov8s to engine fault

### ISSUE THREAD

**Issue by lkw052715** [wang-xinyu/tensorrtx#1434]
## Env

- GPU, jetson agx orin
- OS,  Ubuntu20.04
- Cuda version 11.4
- TensorRT version

## About this repo

yolov8s to engine fault

## Your problem

 Error Code 4: Internal Error ((Unnamed Layer* 247) [Convolution]: number of kernel weights does not match tensor dimensions)
[01/24/2024-21:11:18] [E] [TRT] 3: (Unnamed Layer* 247) [Convolution]:kernel weights has count 384 but 1280 was expected

**Comment by a4andromeda** [comment]
Did you correct no. classes in the config.h? That's where i have seen this (or similar) error before.

**Comment by lkw052715** [comment]
> Did you correct no. classes in the config.h? That's where i have seen this (or similar) error before.
I've modified config.h, but the problem persists, kNumClass and kInputH

**Comment by a4andromeda** [comment]
I think height and width should be a multiple of 16 as far as i remember. Could you check that?

**Comment by lkw052715** [comment]
> I think height and width should be a multiple of 16 as far as i remember. Could you check that?

It could be the weights, after retraining by downloading the latest weights from the official website, the conversion was successful, thanks for your help!
