### ISSUE TITLE
YOLOv8 & TensorRT: When building engine file facing  'serialized_engine' faild

### ISSUE THREAD

**Issue by Muthukumar4796** [wang-xinyu/tensorrtx#1439]
## Env

- GPU : GTX 1650
- OS ; Ubuntu 22.04
- Cuda version 12.2
- Cudnn version 8.9.7
- TensorRT version 8.6.1
- Yolo v8 segmentation

Issue: 

When i try to build the engine file using this command **'./yolov8_seg -s best.wts yolov8s-seg.engine s '** it was showing 'serialized_engine' failed.

My custom best.pt file was converted to best.wts. I uploaded my error for your reference. I checked your repository but couldn't find any solutions, so I raised a ticket.
![Screenshot from 2024-02-24 18-41-55](https://github.com/wang-xinyu/tensorrtx/assets/108849611/d78f9773-99e3-434b-ab46-761562626a62)

**Comment by Smartog** [comment]
it seems that  the highest version of cuda  tensorRT support is 12.1？

**Comment by wang-xinyu** [comment]
@Muthukumar4796 Can you try the official pretrained model first?

**Comment by adrianosantospb** [comment]
> ## Env
> 
>     * GPU : GTX 1650
> 
>     * OS ; Ubuntu 22.04
> 
>     * Cuda version 12.2
> 
>     * Cudnn version 8.9.7
> 
>     * TensorRT version 8.6.1
> 
>     * Yolo v8 segmentation
> 
> 
> Issue:
> 
> When i try to build the engine file using this command **'./yolov8_seg -s best.wts yolov8s-seg.engine s '** it was showing 'serialized_engine' failed.
> 
> My custom best.pt file was converted to best.wts. I uploaded my error for your reference. I checked your repository but couldn't find any solutions, so I raised a ticket. ![Screenshot from 2024-02-24 18-41-55](https://private-user-images.githubusercontent.com/108849611/307523821-d78f9773-99e3-434b-ab46-761562626a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDE5MTksIm5iZiI6MTcwOTMwMTYxOSwicGF0aCI6Ii8xMDg4NDk2MTEvMzA3NTIzODIxLWQ3OGY5NzczLTk5ZTMtNDM0Yi1hYjQ2LTc2MTU2MjYyNmE2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxNDAwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmQ2MmNkNGViZDA4OWRmNTU1MDU0ZjEyMzBhYWVmMTgzMTQ3MGM5YzIxMzZhZGFhMTIyNTBlMTdiNzQwZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hL45cw_-bZDTPw8UDiNA2qXMvTXJaVRSdtvJqWDTftc)

Try to use 640x640

**Comment by cimmen** [comment]
> > ## 环境
> > ```
> > * GPU : GTX 1650
> > 
> > * OS ; Ubuntu 22.04
> > 
> > * Cuda version 12.2
> > 
> > * Cudnn version 8.9.7
> > 
> > * TensorRT version 8.6.1
> > 
> > * Yolo v8 segmentation
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 问题：
> > 当我尝试使用此命令**“./yolov8_seg -s best.wts yolov8s-seg.engine s”**构建引擎文件时，它显示“serialized_engine”失败。
> > 我的自定义 best.pt 文件已转换为 best.wts。我上传了我的错误供您参考。我检查了您的存储库，但找不到任何解决方案，所以我提出了一张票。![Screenshot from 2024-02-24 18-41-55](https://private-user-images.githubusercontent.com/108849611/307523821-d78f9773-99e3-434b-ab46-761562626a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDE5MTksIm5iZiI6MTcwOTMwMTYxOSwicGF0aCI6Ii8xMDg4NDk2MTEvMzA3NTIzODIxLWQ3OGY5NzczLTk5ZTMtNDM0Yi1hYjQ2LTc2MTU2MjYyNmE2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxNDAwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmQ2MmNkNGViZDA4OWRmNTU1MDU0ZjEyMzBhYWVmMTgzMTQ3MGM5YzIxMzZhZGFhMTIyNTBlMTdiNzQwZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hL45cw_-bZDTPw8UDiNA2qXMvTXJaVRSdtvJqWDTftc)
> 
> 尝试使用 640x640

请问640x640指的是输入图像大小吗？
