### ISSUE TITLE
yolov8n to engine fault

### ISSUE THREAD

**Issue by qianz11** [wang-xinyu/tensorrtx#1442]
## Env

- nvidia orin xavier, jetpack 5.0.2

## Your problem
我用yolov8n.pt可以顺利的生成.engine，然后用自己训练的best.pt转换一直报错，已经修改config.h和model.cpp，麻烦大佬看一下怎么修改，多谢
![Screenshot from 2024-02-27 15-46-09](https://github.com/wang-xinyu/tensorrtx/assets/45551492/1cd1a35b-bcb8-4852-8404-5e7740f7dc91)
![Screenshot from 2024-02-27 15-57-21](https://github.com/wang-xinyu/tensorrtx/assets/45551492/150f24ef-74a5-47e9-9ea0-f26af5a64391)
![Screenshot from 2024-02-27 15-57-29](https://github.com/wang-xinyu/tensorrtx/assets/45551492/4d8ae1f1-68d4-4417-a39f-87aff69105b0)

**Comment by qianz11** [comment]
it's worked, thanks!

**Comment by adrianosantospb** [comment]
> 试试640x640输入

This is the same problem that I related.
