### ISSUE TITLE
Yolov8 seg， only X model occured error.

### ISSUE THREAD

**Issue by StanleyYake** [wang-xinyu/tensorrtx#1448]
My own dataset Yolov8 seg model, when serialize TensorRT engine，only x model occured error, Below the S model is serialized successfully.
![Snipaste_2024-03-05_15-10-54](https://github.com/wang-xinyu/tensorrtx/assets/7522853/99211a59-fdb6-4f4a-8e84-c907f0370e0c)

![Snipaste_2024-03-05_15-11-18](https://github.com/wang-xinyu/tensorrtx/assets/7522853/150e9f26-3550-4fa1-a618-2bc998fcf69f)

**Comment by wang-xinyu** [comment]
Can you try the official pretrained x model?

**Comment by wang-xinyu** [comment]
@StanleyYake How did you solve your issue? Can you share your findings?

**Comment by StanleyYake** [comment]
Sorry，my X*.wts is generate on my train computer, and it is the biggest file when using disk copyed to the serialize TensorRT engine computer, something wrong, copy again is then solved.
