### ISSUE TITLE
yolov9 小尺寸模型部署

### ISSUE THREAD

**Issue by BaseJiang** [wang-xinyu/tensorrtx#1454]
博主你好，自测V9C 在NX 上batchsize为1，单张640*640尺寸图像推理平均耗时60+ms，请问build 类似 s之类的小尺寸engine程序会更新吗？

**Comment by wang-xinyu** [comment]
@WuxinrongY 看下哈

**Comment by WuxinrongY** [comment]
可以的，但是yolov9的博主没有提供yolov9s的pt模型，我这边也没有训练，你是否可以提供一个pt模型，方便我测试。
