### ISSUE TITLE
Kernel bugs / Deepstream

### ISSUE THREAD

**Issue by krbvroc1** [wang-xinyu/tensorrtx#146]
While things work using the provided yolov5.cpp, it does not work properly when invoked via Deepstream.

 NVIDIA reports that the problem is that the kernel layers do not use the same incoming cuda stream, so out of order execution results.

 To fix, I changed:
 https://github.com/wang-xinyu/tensorrtx/blob/0bbbcbd778c89b22162776ddccbb5d9cd3d6c827/yolov5/yololayer.cu#L215
to
```
CalDetection<<< (yolo.width*yolo.height*batchSize + mThreadCount - 1) / mThreadCount, mThreadCount, 0, stream>>>
```

and 
https://github.com/wang-xinyu/tensorrtx/blob/0bbbcbd778c89b22162776ddccbb5d9cd3d6c827/yolov5/yololayer.cu#L206
changed above cudaMemset() to **cudaMemsetAsync()**

and also in:
https://github.com/wang-xinyu/tensorrtx/blob/0bbbcbd778c89b22162776ddccbb5d9cd3d6c827/yolov5/hardswish.cu#L130-L131
to
```
HardSwishKer<<<(numElem + mThreadCount - 1) / mThreadCount, mThreadCount, 0, stream>>>
        (inputs[0], output, numElem);
```
I imagine these issues are in your other kernels, but I only use yolov5 so far. 

Deepstream must invoke the kernels in some different order or in threads/non default streams unlike yolov5.cpp.

**Comment by wang-xinyu** [comment]
@krbvroc1 Thanks for your info.   After theses changes, does it still work fine in this repo? I mean without deepstream.

**Comment by krbvroc1** [comment]
@wang-xinyu After the changes I got the same results with yolov5.cpp. So same results before and after changes. But only after changes did it work with deepstream. Thanks.

**Comment by wang-xinyu** [comment]
@krbvroc1 thats great,   can you submit a PR to make these changes? so that it can be compatible with deepsteam.

**Comment by hxk11111** [comment]
@krbvroc1 Could the engine file loaded successfully in DeepStream? Do I need to change any DeepStream plugin code? I am working on the same issue, but stucked in loading yolov5 TRT by DS. Hope someone could help, Thanks.

**Comment by wang-xinyu** [comment]
@hxk11111 can you try the latest commit,  your problem may have been solved.

**Comment by hxk11111** [comment]
@wang-xinyu Thanks for your reply. I just tried to use the latest version of tensorrtx and yolov5 to build a yolov5s engine file. When I tried to load the engine by DeepStream, I got this error:
```
ERROR: [TRT]: INVALID_ARGUMENT: getPluginCreator could not find plugin HardSwishLayer_TRT version 1
```
It seems DS could not find this customized plugin. Do you have any idea about this error? 

Many thanks

**Comment by wang-xinyu** [comment]
did you load the libmyplugins.so into deepstream?

**Comment by hxk11111** [comment]
When I compiled the custom_impl_lib, I added the libmyplugins.so into it, as:
```
TARGET_LIB:= libnvdsinfer_custom_impl_Yolo.so

TARGET_OBJS:= $(SRCFILES:.cpp=.o)
TARGET_OBJS:= $(TARGET_OBJS:.cu=.o)

all: $(TARGET_LIB)

%.o: %.cpp $(INCS) Makefile
        $(CC) -c -o $@ $(CFLAGS) $<

%.o: %.cu $(INCS) Makefile
        $(NVCC) -c -o $@ --compiler-options '-fPIC' $<

$(TARGET_LIB) : $(TARGET_OBJS)
        $(CC) -o $@ libmyplugins.so $(TARGET_OBJS) $(LFLAGS)
```
But the same error occured, I am wondering if I did this correctly. 
Thanks for your patience and time

**Comment by wang-xinyu** [comment]
@hxk11111 Then I have no idea. Maybe @krbvroc1 knows.

**Comment by DanaHan** [comment]
> @wang-xinyu Thanks for your reply. I just tried to use the latest version of tensorrtx and yolov5 to build a yolov5s engine file. When I tried to load the engine by DeepStream, I got this error:
> 
> ```
> ERROR: [TRT]: INVALID_ARGUMENT: getPluginCreator could not find plugin HardSwishLayer_TRT version 1
> ERROR: [TRT]: safeDeserializationUtils.cpp (323) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
> ERROR: [TRT]: INVALID_STATE: std::exception
> ERROR: [TRT]: INVALID_CONFIG: Deserialize the cuda engine failed.
> ERROR: Deserialize engine failed from file: yolov5s.engine
> ```
> 
> It seems DS could not find this customized plugin. Do you have any idea about this error?
> 
> Many thanks

Just use LD_PRELOAD=$pwd/libmyplugins.so
