### ISSUE TITLE
showing results empty 

### ISSUE THREAD

**Issue by adinathkale01** [wang-xinyu/tensorrtx#1462]
- GPU, e.g. GTX1650
- OS, e.g. Ubuntu22.04
- Cuda version 12.2
- TensorRT version 8.6.1

## About this repo

.engine file is generating but when i am running inferencing it not detecting and showing results []

**Comment by wang-xinyu** [comment]
which model?

**Comment by adinathkale01** [comment]
I am using yolov5 with tensorrt

**Comment by wang-xinyu** [comment]
Have you try the official pretrained model?

**Comment by adinathkale01** [comment]
yes ,I tried with yolov5s.pt ---> yolov5s.wts ------>yolov5s.engine  yolov5s.engine file is generating but when running inference showing [] empty.

**Comment by wang-xinyu** [comment]
You were using the [yolov5_det_trt.py](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5_det_trt.py)?

Did you try the c++ executable?

And can you try TensorRT 8.4 or 8.5
