### ISSUE TITLE
yolov8 转wts文件（自定义数据集）失败

### ISSUE THREAD

**Issue by pcycccccc** [wang-xinyu/tensorrtx#1464]
## Env

- GPU: RTX 3080. Env

- GPU: RTX 3080.
- OS, Win10.
- Cuda version 11.8
- TensorRT version 8.6.1

我在自己训练好的模型转wts的时候失败了，提示找不到模块 No module named 'ultralytics.utils'，这个pt模型是我用yolov8s.pt进行训练得到的，报错信息如下
![image](https://github.com/wang-xinyu/tensorrtx/assets/108455796/06fba6ea-8434-48a8-a0a1-d7c4e929ddd5)
但是，我试着转官方提供的yolov8n.pt时却能正确转换wts文件，不知道为啥会有这种问题....

自定义数据集的best.pt模型是我正常训练yolov8s得到的，之前搞其他C++部署时，转onnx模型是可以正常使用的。

补充一句：查过说是要pip install这个模块，但是我之前训练、验证、测试过程中是正常的，没有出现过提示找不到ultralytics模块，模快更新该模块也无法解决上述问题。

**Comment by pcycccccc** [comment]
> ## 环境
> * GPU：RTX 3080.Env
> * 显卡：RTX 3080。
> * 操作系统，Win10。
> * CUDA版本11.8
> * TensorRT 版本 8.6.1
> 
> 我在自己训练好的模型转wts的时候失败了，提示找不到模块没有名为'ultralytics.utils'的模块，这个pt模型是我用yolov8s.pt进行训练得到的，报错信息如下但是，我 尝试一下转官方提供的yolov8n.pt时却能正确转换wts文件，不知道啥会有这种问题.... ![图像](https://private-user-images.githubusercontent.com/108455796/315873138-06fba6ea-8434-48a8-a0a1-d7c4e929ddd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzgxMTUsIm5iZiI6MTcxMTA3NzgxNSwicGF0aCI6Ii8xMDg0NTU3OTYvMzE1ODczMTM4LTA2ZmJhNmVhLTg0MzQtNDhhOC1hMGExLWQ3YzRlOTI5ZGRkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMzIzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmU0MzYyY2NhM2E3NTVhOTY0OGM0NDA1YjE1Nzk2YzM2MmE1ZDcxYzIzYzkwNzdjNGQ4NWRiMzQxOWM1MDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p7XuybJ1C5Z9mP7FCHnVXpngqDxGsBnHrk5CwkPgi48)
> 
> 自定义数据集的best.pt模型是我可以正常训练yolov8s得到的，在搞其他C++部署时，转onnx模型是可以正常使用的。

**Comment by pcycccccc** [comment]
另外，yolov8支持转engine模型文件，是否可以用这种方式来转换模型？并用在该项目提供的tensorRT代码来完成部署呢？
![image](https://github.com/wang-xinyu/tensorrtx/assets/108455796/96d92f4d-3f95-45e6-bcef-97cfbcfa14f6)

**Comment by wang-xinyu** [comment]
在https://github.com/ultralytics/ultralytics/tree/main的主目录下执行gen_wts.py

**Comment by seekwind-suck** [comment]
这个不能直接转的么
