### ISSUE TITLE
What is warpaffine in relation to yolov9?

### ISSUE THREAD

**Issue by rlewkowicz** [wang-xinyu/tensorrtx#1469]
I've not done a yolo c++ implementation since 2019. I'm noticing everyone is doing nms and most pre process in cuda kernels which is cool. 

What is warpaffine_kernel? Everyone has some form of it. I don't really understand what it's doing. I read "allowing for or parallel relationships." It's just resizing? If my input and output is the same exact resolution I don't care about this?

I should add, I pre process to a float, bgr->rgb, strip alpha etc already in my own kernels. 

I also want to be opencv free. It's a heavy library, and it's kinda slow. I'm coming from dx11 so I never have to leave the gpu. Everyone uses opencv, I use imgui and render the cuda frame directly to buffers. In any case, everyone uses opencv too.

**Comment by wang-xinyu** [comment]
It's not quite accurate to call `warpaffine_kernel` for this function https://github.com/wang-xinyu/tensorrtx/blob/64297a268e847a6b5a375fd0fadf35b131c99229/yolov9/src/preprocess.cu#L11

This function is actually doing resize + BGR2RGB + normalization + HWC2CHW.
