### ISSUE TITLE
运行yolov5_trt.py出错

### ISSUE THREAD

**Issue by Smile3y** [wang-xinyu/tensorrtx#147]
错误信息如下：       
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin HardSwishLayer_TRT version 1    
[TensorRT] ERROR: safeDeserializationUtils.cpp (293) - Serialization Error in load: 0 (Cannot deserialize plugin since     corresponding IPluginCreator not found in Plugin Registry)     
[TensorRT] ERROR: INVALID_STATE: std::exception    
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.     

模型使用的是./yolov3 -s 生成的'yolov5s.engine'， 采用同样模型./yolov5 -d  ../samples可以正常运行，是什么原因呢？

**Comment by wang-xinyu** [comment]
@Smile3y 我更新了代码https://github.com/wang-xinyu/tensorrtx/commit/379659afa754e1675a736230a2dc505a4b23070f

再试一下

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by Smile3y** [comment]
厉害，可以成功运行了，谢谢～

**Comment by MichaelWU0726** [comment]
> @Smile3y 我更新了代码[379659a](https://github.com/wang-xinyu/tensorrtx/commit/379659afa754e1675a736230a2dc505a4b23070f)
> 
> 重新编译，再试一下

请问改的哪里？我自己的工程也出现这个问题，build引擎没问题也成功推理，但就是序列化保存后反序列化加载出现找不到插件，希望得到你的反馈帮助

**Comment by wang-xinyu** [comment]
1年前的问题没意义，重新提交你的问题，用模版。

**Comment by MichaelWU0726** [comment]
> 1年前的问题没意义，重新提交你的问题，用模版。

你看一下我在你的commit里的评论，和我提交的[tensorRT官方仓库issue](https://github.com/NVIDIA/TensorRT/issues/1451#issuecomment-908272459)
