### ISSUE TITLE
[TRT] 2: [utils.cpp::checkMemLimit::380] Error Code 2: Internal Error (Assertion upperBound != 0 failed. Unknown embedded device

### ISSUE THREAD

**Issue by Zomcxj** [wang-xinyu/tensorrtx#1471]
## Env

- Xavier NX.
- Ubuntu20.04,
- Cuda 11.4 cudnn 8.6
- TensorRT 8.2.4.2

## About this repo

- tensorrtx-yolov5-v7.0

## Your problem
when i use tensorttx yolov5s.wts to yolov5s.engine  or yolov8n.wts to yolov8n.engine
[TRT] 2: [utils.cpp::checkMemLimit::380] Error Code 2: Internal Error (Assertion upperBound != 0 failed. Unknown embedded device Please update the table with the entry：{{2055， 8， 16}， 12418}）
nvidia-jetpack version: 5.1.2-b104

Can be exported on linux x86   not arm

**Comment by wang-xinyu** [comment]
Jetpack 5.1.2 should contain TensorRT 8.5, not 8.2

**Comment by Zomcxj** [comment]
I just tried trt8.5.3.1 and it was the same problem.

**Comment by wang-xinyu** [comment]
Might be environment issue. You can try TensorRT official samples first.
