### ISSUE TITLE
yolov3 Fp16和 FP32 运行速度是一样的？

### ISSUE THREAD

**Issue by smartwell** [wang-xinyu/tensorrtx#148]
您好，感谢您的分享!
我测试了一下，GTX1080ti ubuntu 16.04，驱动450，cuda 10.2，cudnn 7.6，tensorrt 7.0
尺寸 1x608x608 
FP16 运行速度是 19ms 左右吧，引擎文件大小400M.
注释了 USE_FP16,使用FP32，引擎文件369M，运行速度 也是19ms.

**Comment by wang-xinyu** [comment]
参考下tutorial中`Check if Your GPU support FP16/INT8`

gtx1080ti是不支持fp16的，所以一样

**Comment by smartwell** [comment]
> 参考下tutorial中`Check if Your GPU support FP16/INT8`
> 
> gtx1080ti是不支持fp16的，所以一样

好，感谢
