### ISSUE TITLE
yolov5_trt.py更改输入图片大小报错

### ISSUE THREAD

**Issue by wurongyuan** [wang-xinyu/tensorrtx#150]

**Comment by wurongyuan** [comment]
我想将输入尺寸从(608,608)改成(416,416)
想让他变快一点
但是报错了

**Comment by wang-xinyu** [comment]
要先改yololayer.h里面的尺寸

**Comment by wurongyuan** [comment]
推理的时候无论是用c++还是python版本的，output都没有显示检测结果

**Comment by wang-xinyu** [comment]
可以先试试官方模型，再试自己的模型

**Comment by wurongyuan** [comment]
用的是官方2.0版本的yolov5s.pt

**Comment by wang-xinyu** [comment]
2.0要用这个commit，
https://github.com/wang-xinyu/tensorrtx/commit/7cd092d38289123442157cf7defab78e816f4440

**Comment by wurongyuan** [comment]
我下载的代码中common.hpp这一行是已经按照这个commit修改后的

`for (int i = 0; i < output[0] && i < Yolo::MAX_OUTPUT_BBOX_COUNT; i++) `

**Comment by wang-xinyu** [comment]
不是这个意思。。。要checkout到那个commit，版本回退，git先了解下

**Comment by wurongyuan** [comment]
我找到7cd092d这个commit了，然后下载代码。
c++版本可以运行出检测结果，
但是在运行python版本的tensorRT推理时候出现了和这个一样的问题
https://github.com/wang-xinyu/tensorrtx/issues/147
你在下面的回复给出了更新代码
https://github.com/wang-xinyu/tensorrtx/commit/379659afa754e1675a736230a2dc505a4b23070f
里面涉及hardwish的改动。
这是不是意味着yolov5_trt.py只能跑yolov5 v3.0而不能跑v2.0呢？
想跑2.0应该怎么做呀

**Comment by wang-xinyu** [comment]
python wrapper本就是v3.0之后才加的。

对比一下这里v3.0和v2.0的代码

要修改这两个地方：

1. cmakelists.txt加上这句
```
target_link_libraries(myplugins nvinfer cudart)
```

2. 两个`REGISTER_TENSORRT_PLUGIN` 原来在yolov5.cpp, 分别移动到yololayer.h和hardswish.h

**Comment by zhangyilalala** [comment]
@wang-xinyu  你好！我也碰到了类似的问题，更改了默认的分辨率到其它32的倍数以后就没有检测结果了。
修改了yololayer.h里面的尺寸，REGISTER_TENSORRT_PLUGIN 也移动了位置，请问还有别的需要注意的地方吗？

**Comment by wang-xinyu** [comment]
@zhangyilalala 更改之后，清空build目录重新编译了吗
