### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by WSTao** [wang-xinyu/tensorrtx#151]
Hi, When I am running, the cpu usage is greater than 100%, how can I reduce the cpu usage

**Comment by wang-xinyu** [comment]
which one?

**Comment by WSTao** [comment]
> which one?

I tested yolov4 and yolov5, both are the same. Nvidia GTX1060, Intel core i7-8750
![Screenshot from 2020-08-20 13-09-45](https://user-images.githubusercontent.com/30944722/90719257-79ada500-e2e6-11ea-8aff-fc99855bc94b.png)

**Comment by wang-xinyu** [comment]
this is reasonable,   here 122.6% does not mean over 100%.  In this `top` command,  If your CPU has 12 core, the total should be 1200%.

**Comment by WSTao** [comment]
thanks，I understand that  is the total occupancy of multiple cores, but it is still a bit too much. Is there a way to reduce the load on the cpu?

**Comment by wang-xinyu** [comment]
Is it too much?  You can compare with pytorch.  

This demo is already very simple. It's hard to reduce cpu usage.

**Comment by WSTao** [comment]
Okay,  thank you

**Comment by sudapure** [comment]
> Is it too much? You can compare with pytorch.
> 
> This demo is already very simple. It's hard to reduce cpu usage.

@wang-xinyu , i compared it with pytorch implementation but to be honest on my Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, pytorch implementation takes avg. 16% cpu utilization, where as the tensorrt takes around 21%, so tensorrt implementation looks bit cpu intensive as per my observations.

**Comment by wang-xinyu** [comment]
@sudapure that's interesting.    But the memcpy between CPU and GPU will be CPU consuming. So did your pytorch test also copy the input from CPU to GPU,  and the output from GPU to CPU each time?

**Comment by sudapure** [comment]
@wang-xinyu , currently i am referring to yolov5 implementation in both pytorch and tensorrt, not some custom CNN
