### ISSUE TITLE
yolov8-pose似乎 不支持自己训练的模型

### ISSUE THREAD

**Issue by Luluoy** [wang-xinyu/tensorrtx#1511]
实验官方模型通过。
自己的模型，一个类别，4个关键点的，在转换为engine文件的时候失败了，【TRT】【E】报错在层294的参数对不上。
已经更改了config.h中的变量为4，种类为1。
然后将数据集略作更改，强行转换为17个关键点，不存在的关键点置为000，训练成功，转换成功。
我个人才疏学浅，屡经测试，想破头脑，但还是未能成功，想问一下，工程中的yolov8-pose是不是不支持自己的模型呢？

**Comment by V-Giotto** [comment]
您好，我自己的模型是5个类别，4个关键点的，也无法生成engine文件，关键点还好说，但是类别不为1，请问您后续有解决方法吗？

**Comment by lindsayshuo** [comment]
> 实验官方模型通过。 自己的模型，一个类别，4个关键点的，在转换为engine文件的时候失败了，【TRT】【E】报错在层294的参数对不上。 已经更改了config.h中的变量为4，种类为1。 然后将数据集略作更改，强行转换为17个关键点，不存在的关键点置为000，训练成功，转换成功。 我个人才疏学浅，屡经测试，想破头脑，但还是未能成功，想问一下，工程中的yolov8-pose是不是不支持自己的模型呢？

https://github.com/wang-xinyu/tensorrtx/pull/1512

**Comment by lindsayshuo** [comment]
> 您好，我自己的模型是5个类别，4个关键点的，也无法生成engine文件，关键点还好说，但是类别不为1，请问您后续有解决方法吗？

https://github.com/wang-xinyu/tensorrtx/pull/1512

**Comment by Luluoy** [comment]
> > 您好，我自己的模型是5个类别，4个关键点的，也无法生成engine文件，关键点还好说，但是类别不为1，请问您后续有解决方法吗？
> 
> #1512
您好，您指出已经添加了类别的支持，但是测试后似乎还不支持自定义关键点数量这个参数

**Comment by lindsayshuo** [comment]
> > > 您好，我自己的模型是5个类别，4个关键点的，也无法生成engine文件，关键点还好说，但是类别不为1，请问您后续有解决方法吗？
> > 
> > 
> > #1512
> > 您好，您指出已经添加了类别的支持，但是测试后似乎还不支持自定义关键点数量这个参数

you can  refer to https://github.com/wang-xinyu/tensorrtx/pull/1512

**Comment by Luluoy** [comment]
> > > > 您好，我自己的模型是5个类别，4个关键点的，也无法生成engine文件，关键点还好说，但是类别不为1，请问您后续有解决方法吗？
> > > 
> > > 
> > > #1512
> > > 您好，您指出已经添加了类别的支持，但是测试后似乎还不支持自定义关键点数量这个参数
> 
> you can refer to #1512

非常感谢，问题已经解决！再次感谢您的帮助

**Comment by lindsayshuo** [comment]
> > > > > 您好，我自己的模型是5个类别，4个关键点的，也无法生成engine文件，关键点还好说，但是类别不为1，请问您后续有解决方法吗？
> > > > 
> > > > 
> > > > #1512
> > > > 您好，您指出已经添加了类别的支持，但是测试后似乎还不支持自定义关键点数量这个参数
> > 
> > 
> > you can refer to #1512
> 
> 非常感谢，问题已经解决！再次感谢您的帮助

fine ,you can close this issure
