### ISSUE TITLE
googlenet输出不一致？

### ISSUE THREAD

**Issue by CBIR-LL** [wang-xinyu/tensorrtx#152]
pytorch的输出结果：
![image](https://user-images.githubusercontent.com/12853603/90736433-509a0e00-e300-11ea-86c5-9d7408d4e278.png)
TensorRT的输出结果：

![image](https://user-images.githubusercontent.com/12853603/90739119-25fc8500-e301-11ea-9599-61a065b356f3.png)

还有一个地方：RT的代码里面为什么要做这个处理，我看inference.py中没有归一化的操作。
![image](https://user-images.githubusercontent.com/12853603/90736991-8fc85f00-e300-11ea-8676-fdd4ea3a6896.png)
@wang-xinyu

**Comment by wang-xinyu** [comment]
https://github.com/pytorch/vision/blob/master/torchvision/models/googlenet.py

torchvision googlenet forward里面有一个transform input

我当时用的好像是torchvision 0.4.1，可以切换版本试试

**Comment by CBIR-LL** [comment]
@wang-xinyu 好的，谢谢啦。我知道问题的地方了，我是自己加载的googlenet的模型，不是torchvision，所以没有做你说的transform_input的操作。我改了一下，结果确实是一样的。
