### ISSUE TITLE
yolov8-seg, output error

### ISSUE THREAD

**Issue by TianLuluC** [wang-xinyu/tensorrtx#1525]
## Env

- GPU, RTX3060
- OS, Ubuntu 20.04.4 LTS
- Cuda version，12.2
- TensorRT version, 8.2.5.1

## About this repo

- which branch/tag/commit are you using?
   master
- which model?  
   yolov8-seg

## Your problem

> warm_up->(640, 640, 3), time->4.74ms
warm_up->(640, 640, 3), time->3.88ms
yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
result_boxes[j]:[   0.         0.      1391.6953   713.90625]
result_classid[j]:399.013671875
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov8_seg_trt.py", line 483, in run
    batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
  File "yolov8_seg_trt.py", line 201, in infer
    categories[int(result_classid[j])], result_scores[j]
IndexError: list index out of range

- what is your command? 
   python3 yolov8_seg_trt.py
- what's your output?
   
![image](https://github.com/wang-xinyu/tensorrtx/assets/28704536/d6d301e6-bf78-4978-8121-20b3d14ff876)

- what output do you expect?
box and mask

**Comment by wang-xinyu** [comment]
@lindsayshuo pls advice

**Comment by lindsayshuo** [comment]
> ## Env
> * GPU, RTX3060
> * OS, Ubuntu 20.04.4 LTS
> * Cuda version，12.2
> * TensorRT version, 8.2.5.1
> 
> ## About this repo
> * which branch/tag/commit are you using?
>   master
> * which model?
>   yolov8-seg
> 
> ## Your problem
> > warm_up->(640, 640, 3), time->4.74ms
> > warm_up->(640, 640, 3), time->3.88ms
> > yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
> > return 1 / (1 + np.exp(-x))
> > result_boxes[j]:[   0.         0.      1391.6953   713.90625]
> > result_classid[j]:399.013671875
> > Exception in thread Thread-21:
> > Traceback (most recent call last):
> > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > self.run()
> > File "yolov8_seg_trt.py", line 483, in run
> > batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
> > File "yolov8_seg_trt.py", line 201, in infer
> > categories[int(result_classid[j])], result_scores[j]
> > IndexError: list index out of range
> 
> * what is your command?
>   python3 yolov8_seg_trt.py
> * what's your output?
> 
> ![image](https://private-user-images.githubusercontent.com/28704536/330313430-d6d301e6-bf78-4978-8121-20b3d14ff876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzE3MDgsIm5iZiI6MTcxNTY3MTQwOCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMTM0MzAtZDZkMzAxZTYtYmY3OC00OTc4LTgxMjEtMjBiM2QxNGZmODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODlhNWNlMDJmOWQ1NmFlMmRkMGJlNGVmNjc3MzJhODIzZTViZjczZmI4NjE3Yjg1YzU1OWFlZTgzMWUwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITri20NPvImAXbcLbJzJU0yhbbTtkonfc_EuRmCj3rw)
> 
> * what output do you expect?
>   box and mask

是不是官方模型，我看是索引超了

**Comment by TianLuluC** [comment]
> > ## Env
> > 
> > * GPU, RTX3060
> > * OS, Ubuntu 20.04.4 LTS
> > * Cuda version，12.2
> > * TensorRT version, 8.2.5.1
> > 
> > ## About this repo
> > 
> > * which branch/tag/commit are you using?
> >   master
> > * which model?
> >   yolov8-seg
> > 
> > ## Your problem
> > > warm_up->(640, 640, 3), time->4.74ms
> > > warm_up->(640, 640, 3), time->3.88ms
> > > yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
> > > return 1 / (1 + np.exp(-x))
> > > result_boxes[j]:[   0.         0.      1391.6953   713.90625]
> > > result_classid[j]:399.013671875
> > > Exception in thread Thread-21:
> > > Traceback (most recent call last):
> > > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > > self.run()
> > > File "yolov8_seg_trt.py", line 483, in run
> > > batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
> > > File "yolov8_seg_trt.py", line 201, in infer
> > > categories[int(result_classid[j])], result_scores[j]
> > > IndexError: list index out of range
> > 
> > 
> > 
> > * what is your command?
> >   python3 yolov8_seg_trt.py
> > * what's your output?
> > 
> > ![image](https://private-user-images.githubusercontent.com/28704536/330313430-d6d301e6-bf78-4978-8121-20b3d14ff876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzE3MDgsIm5iZiI6MTcxNTY3MTQwOCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMTM0MzAtZDZkMzAxZTYtYmY3OC00OTc4LTgxMjEtMjBiM2QxNGZmODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODlhNWNlMDJmOWQ1NmFlMmRkMGJlNGVmNjc3MzJhODIzZTViZjczZmI4NjE3Yjg1YzU1OWFlZTgzMWUwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITri20NPvImAXbcLbJzJU0yhbbTtkonfc_EuRmCj3rw)
> > 
> > * what output do you expect?
> >   box and mask
> 
> 是不是官方模型，我看是索引超了

不是，custom model, yolov8 训练的自定义模型，3类

**Comment by lindsayshuo** [comment]
> > > ## Env
> > > 
> > > * GPU, RTX3060
> > > * OS, Ubuntu 20.04.4 LTS
> > > * Cuda version，12.2
> > > * TensorRT version, 8.2.5.1
> > > 
> > > ## About this repo
> > > 
> > > * which branch/tag/commit are you using?
> > >   master
> > > * which model?
> > >   yolov8-seg
> > > 
> > > ## Your problem
> > > > warm_up->(640, 640, 3), time->4.74ms
> > > > warm_up->(640, 640, 3), time->3.88ms
> > > > yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
> > > > return 1 / (1 + np.exp(-x))
> > > > result_boxes[j]:[   0.         0.      1391.6953   713.90625]
> > > > result_classid[j]:399.013671875
> > > > Exception in thread Thread-21:
> > > > Traceback (most recent call last):
> > > > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > > > self.run()
> > > > File "yolov8_seg_trt.py", line 483, in run
> > > > batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
> > > > File "yolov8_seg_trt.py", line 201, in infer
> > > > categories[int(result_classid[j])], result_scores[j]
> > > > IndexError: list index out of range
> > > 
> > > 
> > > 
> > > * what is your command?
> > >   python3 yolov8_seg_trt.py
> > > * what's your output?
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/28704536/330313430-d6d301e6-bf78-4978-8121-20b3d14ff876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzE3MDgsIm5iZiI6MTcxNTY3MTQwOCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMTM0MzAtZDZkMzAxZTYtYmY3OC00OTc4LTgxMjEtMjBiM2QxNGZmODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODlhNWNlMDJmOWQ1NmFlMmRkMGJlNGVmNjc3MzJhODIzZTViZjczZmI4NjE3Yjg1YzU1OWFlZTgzMWUwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITri20NPvImAXbcLbJzJU0yhbbTtkonfc_EuRmCj3rw)
> > > 
> > > * what output do you expect?
> > >   box and mask
> > 
> > 
> > 是不是官方模型，我看是索引超了
> 
> 不是，custom dataset, yolov8 训练的自定义模型，3类

是用最新代码的wts导出的吗

**Comment by TianLuluC** [comment]
> > > > ## Env
> > > > 
> > > > * GPU, RTX3060
> > > > * OS, Ubuntu 20.04.4 LTS
> > > > * Cuda version，12.2
> > > > * TensorRT version, 8.2.5.1
> > > > 
> > > > ## About this repo
> > > > 
> > > > * which branch/tag/commit are you using?
> > > >   master
> > > > * which model?
> > > >   yolov8-seg
> > > > 
> > > > ## Your problem
> > > > > warm_up->(640, 640, 3), time->4.74ms
> > > > > warm_up->(640, 640, 3), time->3.88ms
> > > > > yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
> > > > > return 1 / (1 + np.exp(-x))
> > > > > result_boxes[j]:[   0.         0.      1391.6953   713.90625]
> > > > > result_classid[j]:399.013671875
> > > > > Exception in thread Thread-21:
> > > > > Traceback (most recent call last):
> > > > > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > > > > self.run()
> > > > > File "yolov8_seg_trt.py", line 483, in run
> > > > > batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
> > > > > File "yolov8_seg_trt.py", line 201, in infer
> > > > > categories[int(result_classid[j])], result_scores[j]
> > > > > IndexError: list index out of range
> > > > 
> > > > 
> > > > 
> > > > * what is your command?
> > > >   python3 yolov8_seg_trt.py
> > > > * what's your output?
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/28704536/330313430-d6d301e6-bf78-4978-8121-20b3d14ff876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzE3MDgsIm5iZiI6MTcxNTY3MTQwOCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMTM0MzAtZDZkMzAxZTYtYmY3OC00OTc4LTgxMjEtMjBiM2QxNGZmODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODlhNWNlMDJmOWQ1NmFlMmRkMGJlNGVmNjc3MzJhODIzZTViZjczZmI4NjE3Yjg1YzU1OWFlZTgzMWUwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITri20NPvImAXbcLbJzJU0yhbbTtkonfc_EuRmCj3rw)
> > > > 
> > > > * what output do you expect?
> > > >   box and mask
> > > 
> > > 
> > > 是不是官方模型，我看是索引超了
> > 
> > 
> > 不是，custom dataset, yolov8 训练的自定义模型，3类
> 
> 是用最新代码的wts导出的吗

是的，master, 刚pull的

**Comment by lindsayshuo** [comment]
> > > > > ## Env
> > > > > 
> > > > > * GPU, RTX3060
> > > > > * OS, Ubuntu 20.04.4 LTS
> > > > > * Cuda version，12.2
> > > > > * TensorRT version, 8.2.5.1
> > > > > 
> > > > > ## About this repo
> > > > > 
> > > > > * which branch/tag/commit are you using?
> > > > >   master
> > > > > * which model?
> > > > >   yolov8-seg
> > > > > 
> > > > > ## Your problem
> > > > > > warm_up->(640, 640, 3), time->4.74ms
> > > > > > warm_up->(640, 640, 3), time->3.88ms
> > > > > > yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
> > > > > > return 1 / (1 + np.exp(-x))
> > > > > > result_boxes[j]:[   0.         0.      1391.6953   713.90625]
> > > > > > result_classid[j]:399.013671875
> > > > > > Exception in thread Thread-21:
> > > > > > Traceback (most recent call last):
> > > > > > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > > > > > self.run()
> > > > > > File "yolov8_seg_trt.py", line 483, in run
> > > > > > batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
> > > > > > File "yolov8_seg_trt.py", line 201, in infer
> > > > > > categories[int(result_classid[j])], result_scores[j]
> > > > > > IndexError: list index out of range
> > > > > 
> > > > > 
> > > > > 
> > > > > * what is your command?
> > > > >   python3 yolov8_seg_trt.py
> > > > > * what's your output?
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/28704536/330313430-d6d301e6-bf78-4978-8121-20b3d14ff876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzE3MDgsIm5iZiI6MTcxNTY3MTQwOCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMTM0MzAtZDZkMzAxZTYtYmY3OC00OTc4LTgxMjEtMjBiM2QxNGZmODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODlhNWNlMDJmOWQ1NmFlMmRkMGJlNGVmNjc3MzJhODIzZTViZjczZmI4NjE3Yjg1YzU1OWFlZTgzMWUwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITri20NPvImAXbcLbJzJU0yhbbTtkonfc_EuRmCj3rw)
> > > > > 
> > > > > * what output do you expect?
> > > > >   box and mask
> > > > 
> > > > 
> > > > 是不是官方模型，我看是索引超了
> > > 
> > > 
> > > 不是，custom dataset, yolov8 训练的自定义模型，3类
> > 
> > 
> > 是用最新代码的wts导出的吗
> 
> 是的，master, 刚pull的

你用c++试了吗

**Comment by TianLuluC** [comment]
> > > > > > ## Env
> > > > > > 
> > > > > > * GPU, RTX3060
> > > > > > * OS, Ubuntu 20.04.4 LTS
> > > > > > * Cuda version，12.2
> > > > > > * TensorRT version, 8.2.5.1
> > > > > > 
> > > > > > ## About this repo
> > > > > > 
> > > > > > * which branch/tag/commit are you using?
> > > > > >   master
> > > > > > * which model?
> > > > > >   yolov8-seg
> > > > > > 
> > > > > > ## Your problem
> > > > > > > warm_up->(640, 640, 3), time->4.74ms
> > > > > > > warm_up->(640, 640, 3), time->3.88ms
> > > > > > > yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
> > > > > > > return 1 / (1 + np.exp(-x))
> > > > > > > result_boxes[j]:[   0.         0.      1391.6953   713.90625]
> > > > > > > result_classid[j]:399.013671875
> > > > > > > Exception in thread Thread-21:
> > > > > > > Traceback (most recent call last):
> > > > > > > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > > > > > > self.run()
> > > > > > > File "yolov8_seg_trt.py", line 483, in run
> > > > > > > batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
> > > > > > > File "yolov8_seg_trt.py", line 201, in infer
> > > > > > > categories[int(result_classid[j])], result_scores[j]
> > > > > > > IndexError: list index out of range
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > * what is your command?
> > > > > >   python3 yolov8_seg_trt.py
> > > > > > * what's your output?
> > > > > > 
> > > > > > ![image](https://private-user-images.githubusercontent.com/28704536/330313430-d6d301e6-bf78-4978-8121-20b3d14ff876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzE3MDgsIm5iZiI6MTcxNTY3MTQwOCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMTM0MzAtZDZkMzAxZTYtYmY3OC00OTc4LTgxMjEtMjBiM2QxNGZmODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODlhNWNlMDJmOWQ1NmFlMmRkMGJlNGVmNjc3MzJhODIzZTViZjczZmI4NjE3Yjg1YzU1OWFlZTgzMWUwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITri20NPvImAXbcLbJzJU0yhbbTtkonfc_EuRmCj3rw)
> > > > > > 
> > > > > > * what output do you expect?
> > > > > >   box and mask
> > > > > 
> > > > > 
> > > > > 是不是官方模型，我看是索引超了
> > > > 
> > > > 
> > > > 不是，custom dataset, yolov8 训练的自定义模型，3类
> > > 
> > > 
> > > 是用最新代码的wts导出的吗
> > 
> > 
> > 是的，master, 刚pull的
> 
> 你用c++试了吗

没有，只用了python

**Comment by lindsayshuo** [comment]
> > > > > > > ## Env
> > > > > > > 
> > > > > > > * GPU, RTX3060
> > > > > > > * OS, Ubuntu 20.04.4 LTS
> > > > > > > * Cuda version，12.2
> > > > > > > * TensorRT version, 8.2.5.1
> > > > > > > 
> > > > > > > ## About this repo
> > > > > > > 
> > > > > > > * which branch/tag/commit are you using?
> > > > > > >   master
> > > > > > > * which model?
> > > > > > >   yolov8-seg
> > > > > > > 
> > > > > > > ## Your problem
> > > > > > > > warm_up->(640, 640, 3), time->4.74ms
> > > > > > > > warm_up->(640, 640, 3), time->3.88ms
> > > > > > > > yolov8_seg_trt.py:401: RuntimeWarning: overflow encountered in exp
> > > > > > > > return 1 / (1 + np.exp(-x))
> > > > > > > > result_boxes[j]:[   0.         0.      1391.6953   713.90625]
> > > > > > > > result_classid[j]:399.013671875
> > > > > > > > Exception in thread Thread-21:
> > > > > > > > Traceback (most recent call last):
> > > > > > > > File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> > > > > > > > self.run()
> > > > > > > > File "yolov8_seg_trt.py", line 483, in run
> > > > > > > > batch_image_raw, use_time = self.yolov8_wrapper.infer(self.yolov8_wrapper.get_raw_image(self.image_path_batch))
> > > > > > > > File "yolov8_seg_trt.py", line 201, in infer
> > > > > > > > categories[int(result_classid[j])], result_scores[j]
> > > > > > > > IndexError: list index out of range
> > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > * what is your command?
> > > > > > >   python3 yolov8_seg_trt.py
> > > > > > > * what's your output?
> > > > > > > 
> > > > > > > ![image](https://private-user-images.githubusercontent.com/28704536/330313430-d6d301e6-bf78-4978-8121-20b3d14ff876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzE3MDgsIm5iZiI6MTcxNTY3MTQwOCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMTM0MzAtZDZkMzAxZTYtYmY3OC00OTc4LTgxMjEtMjBiM2QxNGZmODc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODlhNWNlMDJmOWQ1NmFlMmRkMGJlNGVmNjc3MzJhODIzZTViZjczZmI4NjE3Yjg1YzU1OWFlZTgzMWUwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITri20NPvImAXbcLbJzJU0yhbbTtkonfc_EuRmCj3rw)
> > > > > > > 
> > > > > > > * what output do you expect?
> > > > > > >   box and mask
> > > > > > 
> > > > > > 
> > > > > > 是不是官方模型，我看是索引超了
> > > > > 
> > > > > 
> > > > > 不是，custom dataset, yolov8 训练的自定义模型，3类
> > > > 
> > > > 
> > > > 是用最新代码的wts导出的吗
> > > 
> > > 
> > > 是的，master, 刚pull的
> > 
> > 
> > 你用c++试了吗
> 
> 没有，只用了python

可以把j打出来看看

**Comment by TianLuluC** [comment]
![image](https://github.com/wang-xinyu/tensorrtx/assets/28704536/6ddab974-410a-4c9b-99db-68361ade5633)

**Comment by lindsayshuo** [comment]
> @lindsayshuo ![image](https://private-user-images.githubusercontent.com/28704536/330331791-6ddab974-410a-4c9b-99db-68361ade5633.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzI4NzQsIm5iZiI6MTcxNTY3MjU3NCwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMzE3OTEtNmRkYWI5NzQtNDEwYS00YzliLTk5ZGItNjgzNjFhZGU1NjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZDgyODYxMWE4NjJlN2ZmM2YyNzY5OTJjMWUzZWQ2NzM5ZmI3YmE4MTUzZGEzMjllNWZlOGFhODdjZDk2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wNACo2fUYir_Vhbwvt19lAhs7aNavb1wLDy_F2MBWAI)

output[i * 38001: (i + 1) * 38001] 看看这个是不是空

**Comment by TianLuluC** [comment]
@lindsayshuo 
![image](https://github.com/wang-xinyu/tensorrtx/assets/28704536/f3ea8318-0808-4980-b54b-c9468e110066)
不为空

**Comment by lindsayshuo** [comment]
> @lindsayshuo ![image](https://private-user-images.githubusercontent.com/28704536/330334941-f3ea8318-0808-4980-b54b-c9468e110066.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzM1MDYsIm5iZiI6MTcxNTY3MzIwNiwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMzQ5NDEtZjNlYTgzMTgtMDgwOC00OTgwLWI1NGItYzk0NjhlMTEwMDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3NTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMDMxMDQwZTFiMzcxZjI2ZGRlODE3ZjFmNDliZDljZTYwMWI1NWMwM2JmMzFhYjkzZDkxZGJlMzZiNjAxOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2-L_9a466xDccto15r6mJt0hz_gW6OsLb6ML7Ts2ugg) 不为空

result_boxes, result_scores, result_classid,result_proto_coef 这几个打印下

**Comment by TianLuluC** [comment]
@lindsayshuo 
![image](https://github.com/wang-xinyu/tensorrtx/assets/28704536/2abdb455-8567-4984-946f-5655c2104f49)

**Comment by lindsayshuo** [comment]
> @lindsayshuo ![image](https://private-user-images.githubusercontent.com/28704536/330337378-2abdb455-8567-4984-946f-5655c2104f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzM3OTEsIm5iZiI6MTcxNTY3MzQ5MSwicGF0aCI6Ii8yODcwNDUzNi8zMzAzMzczNzgtMmFiZGI0NTUtODU2Ny00OTg0LTk0NmYtNTY1NWMyMTA0ZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNWEyYzUyYWIxMjAyYzJmY2M1MTU0MzFhODc1OWYxZDJjZmJmM2E1NWE3ZTk1NzFiZTdjMDIwOGVjNTdlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uThQKqNoSa5Nueev0qOMBUJvwXg3W0nZgw-mW1SwR9c)

打印int(result_classid[j])]这个呢

**Comment by TianLuluC** [comment]
@lindsayshuo 
![image](https://github.com/wang-xinyu/tensorrtx/assets/28704536/4845b350-62f9-4043-8475-968c948434a4)
model有3类，值应该为 <3

**Comment by TianLuluC** [comment]
Looking forward to your reply！

**Comment by lindsayshuo** [comment]
https://github.com/wang-xinyu/tensorrtx/pull/1526

**Comment by lindsayshuo** [comment]
已经提交修复

**Comment by TianLuluC** [comment]
@lindsayshuo @wang-xinyu 谢谢！
