### ISSUE TITLE
Unable to build engine file for Yolov7 Custom model

### ISSUE THREAD

**Issue by Muthukumar4796** [wang-xinyu/tensorrtx#1528]
## Env

- GPU RTX3050
- OS, Ubuntu 22.04
- Cuda & TRT version I have uploaded image
- Yolov7 w6 custom model
- image size H:768 W:1280 and Num of classes : 6

I'm having trouble building the engine file for my custom YOLOv7 model. I've made changes to the config.h file for classes and image size, but I still can't build the engine file. However, when I tried using the YOLOv7 w6 pretrained model, the engine file was created successfully.

![Screenshot from 2024-05-20 12-16-34](https://github.com/wang-xinyu/tensorrtx/assets/108849611/2a911e17-6110-43e6-a284-0f1dfaf6d7db)

![Screenshot from 2024-05-20 15-09-58](https://github.com/wang-xinyu/tensorrtx/assets/108849611/33c20832-f92c-40b7-ae95-64e074df215b)

![Screenshot from 2024-05-20 12-26-17](https://github.com/wang-xinyu/tensorrtx/assets/108849611/35039cd3-38d5-4128-906a-396110457c0a)

**Comment by wang-xinyu** [comment]
TensorRT 10.x is not supported yet.
