### ISSUE TITLE
只有tensorRT5可用，make的时候报错

### ISSUE THREAD

**Issue by sjtulwt0312** [wang-xinyu/tensorrtx#153]
报错内容：
[ 25%] Building NVCC (Device) object CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o
/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(51): error: not a class or struct name

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(59): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(64): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(66): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(68): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(70): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(72): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(74): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(76): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(78): error: identifier "PluginTensorDesc" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(78): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(82): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(84): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(86): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(88): error: identifier "IPluginV2IOExt" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(88): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(90): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(92): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(94): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(96): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(98): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(100): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(103): error: identifier "PluginTensorDesc" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(103): error: identifier "PluginTensorDesc" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(103): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(105): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(79): error: name followed by "::" must be a class or namespace name

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(130): error: identifier "IPluginV2IOExt" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(130): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::createPlugin"

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(130): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(132): error: identifier "IPluginV2IOExt" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(132): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::deserializePlugin"

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.h(132): error: member function declared with "override" does not override a base class member

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.cu(119): error: identifier "PluginTensorDesc" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.cu(119): error: identifier "PluginTensorDesc" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.cu(147): error: identifier "IPluginV2IOExt" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.cu(254): error: identifier "IPluginV2IOExt" is undefined

/home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/yololayer.cu(261): error: identifier "IPluginV2IOExt" is undefined

38 errors detected in the compilation of "/tmp/tmpxft_00002a14_00000000-6_yololayer.cpp1.ii".
CMake Error at yololayer_generated_yololayer.cu.o.Debug.cmake:280 (message):
  Error generating file
  /home/dji/Application/yolov5/tensorrtx-master/tensorrtx/yolov5/build/CMakeFiles/yololayer.dir//./yololayer_generated_yololayer.cu.o

CMakeFiles/yololayer.dir/build.make:334: recipe for target 'CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:80: recipe for target 'CMakeFiles/yololayer.dir/all' failed
make[1]: *** [CMakeFiles/yololayer.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
不知道这个错误是否和tensorRT版本有关系。因为准备在ARM上部署，tensorRT7用不了，只能用tensorRT5。

**Comment by roger707** [comment]
你好，能出一个版本在trt5上运行的yolov5么？
