### ISSUE TITLE
yolov5-7.0，about anchor

### ISSUE THREAD

**Issue by cgreenhand** [wang-xinyu/tensorrtx#1530]
## About this repo
- which model? yolov5-7.0-detect?

## Your problem

博主您好，请教一下，gen_wts.py产生的yolov5_detect 的wts文件里面包含模型的anchor信息吗，使用U版yolov5训练自己的模型，开启autoanchor后anchor就和coco的不一致了，通过wts转换engine里面会包含更新后的anchor吗？还是固定的coco anchor，如果转换是固定的coco-anchor我们又该怎么修改anchor呢？谢谢

**Comment by wang-xinyu** [comment]
包含anchor

**Comment by cgreenhand** [comment]
谢谢博主的解答
