### ISSUE TITLE
the command : ./yolov5_det -s yolov5s.wts yolov5s.engine s,  error!!!

### ISSUE THREAD

**Issue by coding-and-coding** [wang-xinyu/tensorrtx#1532]
## Env

- GPU: RTX3090
- OS: Ubuntu 20.04
- Cuda version: 11.4
- TensorRT version: 8.5.2.2
- torch: 1.12.0

## About this repo

- branch: tensorrtx(yolov5-v7.0)
- model:  yolov5s, v7.0, official weight

## Your problem

- my command: ./yolov5_det -s yolov5s.wts yolov5s.engine s

- output: [E] [TRT] 9: [graphShapeAnalyzer.cpp::addVolumeCheck::739] Error Code 9: Internal Error (prob: dimension 0 never exceeds -5)
[05/24/2024-19:01:38] [E] [TRT] 4: [network.cpp::validate::2980] Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.)

- expect output: yolov5s.engine

**Comment by wang-xinyu** [comment]
This error is weird. Are you sure the yolov5s.wts was generated with the official yolov5s-v7.0.pt

**Comment by coding-and-coding** [comment]
您好：

        还是用中文交流吧，我下载的是官方的预训练pt文件，链接是https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt ，用的tensorrtx也是对应7.0版本的，我后来用yolov5 5.0版本搭配.5.0版本的tensorrtx跑通了。这个问题我考虑是因为7.0版本yolov5模型新增了分割和分类的检测头，我感觉有可能是yolov5s.pt生成yolov5s.wts时产生的问题，即gen_wts.py的脚本可能有bug，不过因为我对yolov5 7.0的模型不是特别清楚，所以暂时没去排查




PS: 官方还发布了分类的权重文件https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s-cls.pt和分割的权重文件

https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s-seg.pt，但我没有用到




     您有空可以分析一下。
















At 2024-05-30 11:15:39, "Wang Xinyu" ***@***.***> wrote:

This error is weird. Are you sure the yolov5s.wts was generated with the official yolov5s-v7.0.pt
