### ISSUE TITLE
ubuntu下yolov5_v5.0的.wts转.engine失败

### ISSUE THREAD

**Issue by silas-yy** [wang-xinyu/tensorrtx#1534]
配置环境：
ubuntu 20.04
cuda v11.2
TensorRT 8.6.1

## About this repo
cmake成功，make成功
yolov5_v5跑的，.pt文件也是从yolov5_v5中下载的yolov5s，.pt转.wts成功

## Your problem
sudo ./yolov5 -s ../yolov5s.wts yolov5s.engine s报错：
[05/31/2024-10:57:10] [E] [TRT] 2: [builder.cpp::createCaskKernelLibraryImpl::169] Error Code 2: Internal Error (Assertion validateCaskKLibSize(buffer.size) failed. )
段错误
![image](https://github.com/wang-xinyu/tensorrtx/assets/125504659/3e09edc9-2032-43c4-bc1b-1a244b0d33ed)
搜出来是版本不兼容，但我之前用trtexec，将onnx模型转为engine模型可以，且测试通过
![image](https://github.com/wang-xinyu/tensorrtx/assets/125504659/06002711-0e70-40c2-a62e-90bc67dea2bf)

**Comment by wang-xinyu** [comment]
这个报错应该是环境有问题，trt版本和依赖cuda等版本不匹配
