### ISSUE TITLE
yolov8 TRT问题

### ISSUE THREAD

**Issue by striving1234** [wang-xinyu/tensorrtx#1537]
## Env

- GPU, Jetson Xavier 
- OS, e.g. Ubuntu18.04
- Jetpack  4.4
- Cuda version: 10.2.89
- Cudnn version: 8.0.0.180
- TensorRT: 7.1.3

## Your problem
请问，tensorrtx/yolov8 是否支持tensorrt7.1.3 呢，我在cmake && make  的时候发现了一个错误
tensorrtx/cable_/src/model.cpp:314:56: error: ‘class nvinfer1::IBuilder’ has no member named ‘buildSerializedNetwork’
     nvinfer1::IHostMemory* serialized_model = builder->buildSerializedNetwork(*network, *config);
                                                        ^~~~~~~~~~~~~~~~~~~~~~
/home/nvidia/Documents/tensorrtx/cable_/src/model.cpp:317:12: error: ‘virtual nvinfer1::INetworkDefinition::~INetworkDefinition()’ is protected within this context
     delete network;

**Comment by wang-xinyu** [comment]
需要trt8.x

**Comment by striving1234** [comment]
> 需要trt8.x
Upgrade the  jetpack:
Env
GPU, Jetson Xavier
OS, e.g. Ubuntu18.04
Jetpack 4.6.1
Cuda version: 10.2.3
Cudnn version: 8.2.1
TensorRT: 8.2.1.8

Problem:
~/Documents/tensorrtx-v8/tensorrtx/v8/build$ ./yolov8_det -s yolov8s.wts yolov8s.engine s
Loading weights: yolov8s.wts
Building engine, please wait for a while...
[06/04/2024-05:20:03] [E] [TRT] 2: [utils.cpp::checkMemLimit::380] Error Code 2: Internal Error (Assertion upperBound != 0 failed. Unknown embedded device detected. Please update the table with the entry: {{1794, 6, 32}, 25535},)
[06/04/2024-05:20:03] [E] [TRT] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
Build engine successfully!
yolov8_det: /home/nvidia/Documents/tensorrtx-v8/tensorrtx/v8/yolov8_det.cpp:30: void serialize_engine(std::__cxx11::string&, std::__cxx11::string&, int&, std::__cxx11::string&, float&, float&, int&): Assertion `serialized_engine' failed.
Aborted (core dumped)

**Comment by striving1234** [comment]
> > Unknown embedded device detected
> > 应该是环境有问题，试试刷一下jetpack5.0+吧

是的，jetpack环境问题，刷机不完整造成。现在解决jetpack4.6.1环境问题了，谢谢。
