### ISSUE TITLE
Yolov8 segmentation mask are not good, no mask found in some bounding boxes.

### ISSUE THREAD

**Issue by rgkannan676** [wang-xinyu/tensorrtx#1547]
I converted a custom-trained model and tested it. In the results, I see that some bounding boxes have no mask and the ones which have are not very good. Has anyone faced this issue?

**Comment by rgkannan676** [comment]
Just so you know, the masks are good when tested using the Python model.  Please advise.

**Comment by rgkannan676** [comment]
left = left < 0 ? 0 : left;
    top = top < 0 ? 0 : top;
    right = right > kInputW ? kInputW : right;
    bottom = bottom > kInputH ? kInputH : bottom;

**Comment by wang-xinyu** [comment]
@rgkannan676 Cool, can you raise a PR?
