### ISSUE TITLE
Platform for converting to .wts file

### ISSUE THREAD

**Issue by eegmnn** [wang-xinyu/tensorrtx#1548]
## Env

- Xavier AGX
- Ubuntu20.04
- Cuda version 11.4
- TensorRT version 8.4.1

## About the repo

- Main branch
- YoloV9 model

Does it matter what platform I am converting my model.pt file into model.wts file? For example, can I convert pt file into wts file on google colab, and then convert the wts file into engine file on xavier agx?

**Comment by wang-xinyu** [comment]
.wts is plain text file, it's not related to the hardware. You can convert it on any device.
