### ISSUE TITLE
What is calib_table_name and input_blob_name?

### ISSUE THREAD

**Issue by Egorundel** [wang-xinyu/tensorrtx#1564]
## Your problem

Hello, what are these files: `calib_table_name` and `input_blob_name` and what are they responsible for?
I am interested in calibration and quantization (for example, yolov8).

## Env

- GPU RTX3060
- OS Ubuntu 20.04
- Cuda version 11.1
- TensorRT version 8.6.1.6

**Comment by wang-xinyu** [comment]
You can check tensorrt docs https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#working-with-int8
