### ISSUE TITLE
Set specific Cuda stream ID in Cpp implimentation code.

### ISSUE THREAD

**Issue by phamthanhdat270198** [wang-xinyu/tensorrtx#1565]
## Env

- Agx Orin 64GB.
-  Ubuntu20.04
- Cuda version 11.4
- TensorRT version 8.5.2

##  Question
Hi,
I want to set specific cudastream ID on Cpp code yolo like --streams=0 or --streams=1, ... in trtexec
Many thanks!!!!!

**Comment by wang-xinyu** [comment]
You need to adapt the inference code, create multiple streams and pass to infer() function.

**Comment by phamthanhdat270198** [comment]
When I create multiple streams It just decrease a little bit infer time. So Does it working in parallel. give me an example about multi streams and multi contexts. Many thanks!!!
Here is my impliment multi streams
![Uploading image.png…]()
