### ISSUE TITLE
WIN10+YOLOV5编译报错求教

### ISSUE THREAD

**Issue by HaoS1985** [wang-xinyu/tensorrtx#157]
折腾了一周时间，还是没有解决，所以求教一下，有没有使用WIN10的大佬指点一下，谢谢
ENV: WIN10 X64; CUDA 10.2; CUDNN 7.6.5;
TensorRT-7.0.0.11 + MinGW-W64 + CMAKE3.18.2

PS:TensorRT-7.0.0.11的SAMPLE在VS2017下编译成功过可以运行，编译YOLOV5没有使用VS2017因为会报nvcc warning : The -c++11 flag is not supported with the configured host compiler. Flag will be ignored

ERROR:
gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

D:\TensorRT-7.0.0.11\samples\tensorrtx\yolov5\build>mingw32-make
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_hardswish.cu.obj
nvcc fatal   : Host compiler targets unsupported OS.
CMake Error at myplugins_generated_hardswish.cu.obj.Debug.cmake:220 (message):
  Error generating
  D:/TensorRT-7.0.0.11/samples/tensorrtx/yolov5/build/CMakeFiles/myplugins.dir//./myplugins_generated_hardswish.cu.obj

mingw32-make[2]: *** [CMakeFiles\myplugins.dir\build.make:90: CMakeFiles/myplugins.dir/myplugins_generated_hardswish.cu.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:95: CMakeFiles/myplugins.dir/all] Error 2
mingw32-make: *** [Makefile:102: all] Error 2

**Comment by Sinray1983** [comment]
I have the same error!

**Comment by wang-xinyu** [comment]
A new tutorial for windows has been added. Please refer it.
