### ISSUE TITLE
Error When Serializing Custom YOLOv8s-seg Model with a Single Label

### ISSUE THREAD

**Issue by felipemasuda** [wang-xinyu/tensorrtx#1589]
## Env

- GPU: RTX4090
- OS: Ubuntu 20.04
- Cuda version: 12.1
- TensorRT version: 8.6.1.6

## About this repo

- which branch/tag/commit are you using? 
   Master
- which model? 
  custom, trained with official yolov8s-seg (v8.3.0)

## Your problem

I am able to serialize and later infer the pre-trained yolov8s-seg model provided by Ultralytics.

When training my custom model (with only one label) based on yolov8s-seg, I can successfully infer my .pt file. However, when I attempt to serialize it using the following command:

```yolov8_seg -s ./yolov8s-seg_custom.wts ./yolov8s-seg_custom.engine s```

And also modify the file /include/config.h to set kNumClass = 1. Despite these changes, I am unable to complete the serialization due to the issues shown in the error log below:

![image](https://github.com/user-attachments/assets/1c1cb5c9-4ddd-4531-83f2-0b8398a5cd66)

**Comment by wang-xinyu** [comment]
@lindsayshuo Please help here.
