### ISSUE TITLE
CMake Error at myplugins_generated_hardswish.cu.o.Debug.cmake:279

### ISSUE THREAD

**Issue by Sinray1983** [wang-xinyu/tensorrtx#159]
The error happened when building tensorrtx/yolov5, Please help me!

ubuntu18.04
cuda11.0
cudnn8.0.2.39
tensorrt7.1.3.4

[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_hardswish.cu.o
/media/r/hs2t/Python/RDL/yolov5/hardswish.h(44): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::HardSwishPlugin::configurePlugin" -- virtual function override intended?

Segmentation fault (core dumped)
CMake Error at myplugins_generated_hardswish.cu.o.Debug.cmake:279 (message):
  Error generating file
  /media/r/hs2t/Python/RDL/yolov5/build/CMakeFiles/myplugins.dir//./myplugins_generated_hardswish.cu.o

CMakeFiles/myplugins.dir/build.make:70: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_hardswish.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_hardswish.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
didn't see any error, only a warning...

**Comment by Sinray1983** [comment]
failed

CMake Error at myplugins_generated_hardswish.cu.o.Debug.cmake:279 (message):
Error generating file
/media/r/hs2t/Python/RDL/yolov5/build/CMakeFiles/myplugins.dir//./myplugins_generated_hardswish.cu.o

> didn't see any error, only a warning...

**Comment by wang-xinyu** [comment]
your cuda nvcc might not setup properly. This error is generated while building .cu

**Comment by Sinray1983** [comment]
I have solved the problem by reinstall cuda, cudnn and tensorrt!
Thanks for help!
