### ISSUE TITLE
.cu plugin files

### ISSUE THREAD

**Issue by adityalohia29** [wang-xinyu/tensorrtx#16]
What is the importance of .cu files and why are they loaded in CUDA? While I was going through the documentation and samples of TensorRT I didn't find such a method. Could you please explain the plugin creation method?

**Comment by aditya-dl** [comment]
Any explanation for this wang-xinyu?

**Comment by wang-xinyu** [comment]
For how to use plugin in tensorrt4, you can refer to https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt_401/tensorrt-developer-guide/index.html#extending

Basically, a plugin need to implement a IPlugin class, and the .cu file implements the IPlugin methods. Some plugins need CUDA to accelerate the process, so it is using .cu as extension.

And for tensorrt7, refer to https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending.

**Comment by persuelx** [comment]
What is your idea of BN algorithm in yolov3 in 
IScaleLayer* addBatchNorm2d(INetworkDefinition *network, std::map<std::string, Weights>& weightMap, ITensor& input, std::string lname, float eps)
?  i have a little feel that the BN algorithm in yolov3 is inconsistent with 
Conventional formula。thank you

**Comment by wang-xinyu** [comment]
@persuelx please open another thread for this question.
