### ISSUE TITLE
yolov5 v3.0 同样的数据、同样的模型，循环推理结果不一致

### ISSUE THREAD

**Issue by knighthappy** [wang-xinyu/tensorrtx#160]
你好，首先感谢你做的非常有意义的工作。

我的应用环境是：
操作系统：ubuntu1604
cuda：10.1
tensorrt：6.0.1.5
模型：yolov5 v3.0的 yolov5s.pt模型

参数：
static constexpr int CHECK_COUNT = 3;
static constexpr float IGNORE_THRESH = 0.3f;
static constexpr int MAX_OUTPUT_BBOX_COUNT = 500;
static constexpr int CLASS_NUM = 80;
static constexpr int INPUT_H = 608;
static constexpr int INPUT_W = 608;

#define USE_FP16  // comment out this if want to use FP32
#define DEVICE 0  // GPU id
#define NMS_THRESH 0.4
#define CONF_THRESH 0.5
#define BATCH_SIZE 8

我首先进行了模型转换，然后修改了您的yolov5.cpp中的代码进行模型的循环推理，如下代码所示：

`
// Run inference
float* prob = new float[BATCH_SIZE * OUTPUT_SIZE];
int index = 0;

while(index < 10)
{
     float everyprob[BATCH_SIZE * OUTPUT_SIZE];
     auto start = std::chrono::system_clock::now();
     doInference(*context, data, everyprob, BATCH_SIZE);
     auto end = std::chrono::system_clock::now();
     std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;

      if(index > 0)
      {
           bool bSame = true;
           for(int i=0;i<BATCH_SIZE * OUTPUT_SIZE;i++)
           {
                if(*(everyprob+i) != *(prob+i))
                {
                    bSame = false;
                    break;
                 }
            }
            std::cout << "bSame : " << bSame << std::endl;
        }

        memcpy(prob,everyprob,BATCH_SIZE * OUTPUT_SIZE*sizeof(float));
        index++;
}
`

结果发现每一次迭代输出都是false，也就意味着同样的IExecutionContext和输入数据下，模型的输出是不一致的。

另外，我查看了每一幅图像的推理结果的数据，设置MAX_OUTPUT_BBOX_COUNT = 500时，每幅图像的输出为3001个浮点数，但结果查看发现每一幅图像推理结果中非0数据个数不是6的整数倍，如下图所示：
![image](https://user-images.githubusercontent.com/28421266/91628171-d3e9ec80-e9ef-11ea-9ca7-f4df3e4e02fc.png)

各位能否给些建议，非常感谢！

**Comment by wang-xinyu** [comment]
为什么是6的整数倍？

**Comment by knighthappy** [comment]
@wang-xinyu 谢谢指导。

第一个问题，同样的模型，同样的输入数据，循环推理结果不一致的问题，请问可以给些问题定位的建议吗？谢谢。
