### ISSUE TITLE
Does yoloV5 support BATCH_SIZE>1?

### ISSUE THREAD

**Issue by Sinray1983** [wang-xinyu/tensorrtx#162]
Does yoloV5 support BATCH_SIZE>1?
If support, how to modify the input and how to parse the output?

Thanks!

**Comment by wang-xinyu** [comment]
refer to the readme -> config of yolov5

**Comment by CF2220160244** [comment]
How can I use BATCH_SIZE>1 in the yolov5_trt.py? @wang-xinyu

**Comment by wang-xinyu** [comment]
the python wrapper does not support batchsize>1, you can adapt it yourself.

**Comment by CF2220160244** [comment]
@wang-xinyu I add the input(batchsize=4) in the python wrapper, and use this pro build the yolov5s.engine, but the output only have the first image result, the output result of the left 3 images is 0.
cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)

**Comment by 1725917163** [comment]
> python 包装不支持批处理大小>1，您可以自己调整它。

大佬您好，我编译的engine模型的batchsize是16的，在yolov5_trt.py中输入的数据的shape是[16,3,640,640], 输出的结果是(96016,)，刚好也是16*6001（6001是单张图片的输出的结果），但是我把（96016，1）reshape成（16,6001）后只有第一个结果是正常的，其余的结果都是0，请问这个有什么办法解决？

**Comment by wang-xinyu** [comment]
@1725917163 可能没把output所有数据从gpu都copy到cpu吧

**Comment by 1725917163** [comment]
大佬，能不能提供一下batch_size>1的Python代码？

**Comment by RocketFlash** [comment]
@wang-xinyu please, could you show how to use yolov5_trt.py with batch_size>1
