### ISSUE TITLE
yolov5在TRT转换后MAP掉点

### ISSUE THREAD

**Issue by zhangyilalala** [wang-xinyu/tensorrtx#164]
在数据集上训练yolov5m的map0.5是0.792，TRT转换后FP32的MAP测出来是0.759，掉了3.3个点，请问一下一些tricky 或者plugins会造成这种情况吗？

**Comment by wang-xinyu** [comment]
可能影响mAP的几个因素：

- FP16
- MAX_OUTPUT_BBOX_COUNT in yololayer.h
- IGNORE_THRESH in yololayer.h

**Comment by zhangyilalala** [comment]
好的，谢谢回复！



---原始邮件---
发件人: "Wang Xinyu"<notifications@github.com&gt;
发送时间: 2020年9月1日(周二) 上午9:29
收件人: "wang-xinyu/tensorrtx"<tensorrtx@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zhangyilalala"<4413153@qq.com&gt;;
主题: Re: [wang-xinyu/tensorrtx] yolov5在TRT转换后MAP掉点 (#164)




 
可能影响mAP的几个因素：
  
FP16 

MAX_OUTPUT_BBOX_COUNT in yololayer.h 

IGNORE_THRESH in yololayer.h

**Comment by ahhhxxx** [comment]
> 好的，谢谢回复！
> […](#)
> ---原始邮件--- 发件人: "Wang Xinyu"<notifications@github.com&gt; 发送时间: 2020年9月1日(周二) 上午9:29 收件人: "wang-xinyu/tensorrtx"<tensorrtx@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"zhangyilalala"<4413153@qq.com&gt;; 主题: Re: [wang-xinyu/tensorrtx] yolov5在TRT转换后MAP掉点 (#164) 可能影响mAP的几个因素： FP16 MAX_OUTPUT_BBOX_COUNT in yololayer.h IGNORE_THRESH in yololayer.h — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬 您有测map 的代码吗？
