### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by ctxqlxs** [wang-xinyu/tensorrtx#165]
您好，我想问下您是如何调试的？我在ubuntu用Clion 调试，看不到tensor的shape呀。。。

**Comment by wang-xinyu** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_tensor.html

ITensor的getDimensions接口获取shape

**Comment by ctxqlxs** [comment]
感谢
