### ISSUE TITLE
yolov3-tiny wrong result

### ISSUE THREAD

**Issue by ilwoonam75** [wang-xinyu/tensorrtx#166]
Thank you for your great project.
Now I am working on a project to inference tiny yolo v3 model.
For better performance, we decided to use tensorrt.

I followed your readme guide, and get the following result.

See the attached.
![_bus](https://user-images.githubusercontent.com/11212680/91834721-6229d100-ec83-11ea-8053-57688bafa76c.jpg)
![_zidane](https://user-images.githubusercontent.com/11212680/91834727-63f39480-ec83-11ea-938b-3aa9e49d5712.jpg)

Please check this result.

Thank you again.

**Comment by wang-xinyu** [comment]
this is normal. please try more images.

**Comment by ilwoonam75** [comment]
This is the result when I run detect.py in https://github.com/ultralytics/yolov3.
command 1 : python detect.py --source ./samples/bus.jpg --cfg cfg/yolov3-tiny.cfg --weights yolov3-tiny.weights --img-size 416 --iou-thres 0.5
command 2 : python detect.py --source ./samples/zidane.jpg --cfg cfg/yolov3-tiny.cfg --weights yolov3-tiny.weights --img-size 416 --iou-thres 0.5
![bus](https://user-images.githubusercontent.com/11212680/91876016-30326200-ecb7-11ea-9227-f3627576f6e4.jpg)
![zidane](https://user-images.githubusercontent.com/11212680/91876021-31638f00-ecb7-11ea-913d-fe4678758e88.jpg)

As you can see, this is somewhat different when I run the same model in tensorrt.

I am trying to analyze the reason, but it is hard to know why there is a difference.

Could you check the reason?

**Comment by wang-xinyu** [comment]
iou/nms thresh and conf thresh might impact the result.

and nms method maybe different from the pytorch.

**Comment by ilwoonam75** [comment]
I know the reason.
The reason is that the anchors you used in the yololayer.h file is different from the anchros in the default yolov3-tiny.cfg.
The anchor from yolov3-tiny.cfg is
10,14,  23,27,  37,58,  81,82,  135,169,  344,319

The anchors from yololayer.h is
{23,27, 37,58, 81,82} {81,82, 135,169, 344,319}

That is the reason the detection results are bigger than expected.

**Comment by ilwoonam75** [comment]
https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg

This is from original cfg.

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=80
num=6
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1

I think the tiny yolo v3 weight is trained based on the mask = 0, 1, 2.
I don't understand why ultralytics change the value mask = 0,1,2 to mask = 1,2,3.
But I can get better result with mask = 0,1,2 value.

**Comment by wang-xinyu** [comment]
You maybe right.

We should confirm from ultralytics.

I downloaded the yolov3-tiny.weights from GD addr provided by ultralytics. We don't know if this one is traind using mask=0,1,2 or mask = 1,2,3.
