### ISSUE TITLE
如何加载两个不同标签数的yolov5模型

### ISSUE THREAD

**Issue by zhongqingyang** [wang-xinyu/tensorrtx#167]
我想加载两个模型,一个模型有80的标签,另一个模型有两个标签,但是他们共用了yololayer.cu中的mClassCount,我该如何在运行时改变他的值

**Comment by wang-xinyu** [comment]
写两个yololayer.cu和.h，或者把class num改为参数传到plugin里面

**Comment by zhongqingyang** [comment]
能指导一下在什么地方传入参数吗

**Comment by mialo-tech** [comment]
I'm also facing the same problem. I have 2 models which run one after the other and both models have different number of classes. 
For the first model I get proper results but second model results will not be accurate always
