### ISSUE TITLE
Where is 'utils'?

### ISSUE THREAD

**Issue by llzhaoshuo** [wang-xinyu/tensorrtx#169]
when I run yolov5/gen_wts.py:
from utils.torch_utils import select_device
ModuleNotFoundError: No module named 'utils'

**Comment by wang-xinyu** [comment]
refer to the readme of yolov5.

```
1. generate yolov5s.wts from pytorch with yolov5s.pt

git clone https://github.com/wang-xinyu/tensorrtx.git
git clone https://github.com/ultralytics/yolov5.git
// download its weights 'yolov5s.pt'
// copy tensorrtx/yolov5/gen_wts.py into ultralytics/yolov5
// ensure the file name is yolov5s.pt and yolov5s.wts in gen_wts.py
// go to ultralytics/yolov5
python gen_wts.py
// a file 'yolov5s.wts' will be generated.
```

go to ultralytics/yolov5 and run gen_wts.py

**Comment by llzhaoshuo** [comment]
> refer to the readme of yolov5.
> 
> ```
> 1. generate yolov5s.wts from pytorch with yolov5s.pt
> 
> git clone https://github.com/wang-xinyu/tensorrtx.git
> git clone https://github.com/ultralytics/yolov5.git
> // download its weights 'yolov5s.pt'
> // copy tensorrtx/yolov5/gen_wts.py into ultralytics/yolov5
> // ensure the file name is yolov5s.pt and yolov5s.wts in gen_wts.py
> // go to ultralytics/yolov5
> python gen_wts.py
> // a file 'yolov5s.wts' will be generated.
> ```
> 
> go to ultralytics/yolov5 and run gen_wts.py

Thanks very much!
