### ISSUE TITLE
yolov4：deserializeCudaEngine failed

### ISSUE THREAD

**Issue by BaofengZan** [wang-xinyu/tensorrtx#17]
Hi, I encountered the following error while running yolo4：
`
Serialization Error in nvinfer1::rt::CoreReadArchive::verifyHeader: 0 (Length in header does not match remaining archive length)

ERROR: INVALID_STATE: Unknown exception

ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
`
How to solve it?  
Thanks in advance !

**Comment by wang-xinyu** [comment]
@BaofengZan I never met this error before.

Can you provide more details? How did you generate .wts? which .cfg and weights you were using? Have you modified the codes?

**Comment by BaofengZan** [comment]
Solved。 The reason is that the engine file format under windows is different form linux。

**Comment by pustar** [comment]
> Solved。 The reason is that the engine file format under windows is different form linux。

Can you tell me which format to use for windows and which for linux?

**Comment by wang-xinyu** [comment]
@pustar this issue already fixed in the code. pls open a new thread and describe your issue.

**Comment by iwanggp** [comment]
Can you tell me which format to use for windows and which for linux?
