### ISSUE TITLE
No bboxes using v0.3.0 yolov5s on Jetson NX

### ISSUE THREAD

**Issue by elepherai** [wang-xinyu/tensorrtx#170]
Hi, I've followed the instructions about yolov5s, but I found that no any bboxes drawed on _zidane.jpg and _bus.jpg.

My device is Jetson NX with Jetpack 4.4 OS.

Best regards

**Comment by wang-xinyu** [comment]
are you using the yolov5 v3.0 model?  download the model from  https://github.com/ultralytics/yolov5/releases/tag/v3.0

**Comment by elepherai** [comment]
@wang-xinyu Thank you, it works.
