### ISSUE TITLE
Can GTX1080 support FP16？

### ISSUE THREAD

**Issue by jiangfeizi** [wang-xinyu/tensorrtx#173]
![微信截图_20200905104924](https://user-images.githubusercontent.com/34883220/92296267-8af0e580-ef65-11ea-98ed-e2eaac8bffca.png)
The CUDA Compute Capability of GTX1080 is 6.1,according to this picture,GTX 1080 cann't support FP16,or my understanding is wrong?
Thank for your reply.-:)

**Comment by wang-xinyu** [comment]
You are right.

1080 does not support fp16.

But the benchmark test still using fp16, which is nearly same as fp32.
