### ISSUE TITLE
yolov5  trt支持可变shape，即输入w和h可变

### ISSUE THREAD

**Issue by mdztravelling** [wang-xinyu/tensorrtx#175]
原始yolov5的输入shape，即w和h是可变的，而这里trt版本是固定的w和h，请教一下，1）这两者在效果上差异会很大么？ 2）trt yolov5实例可变shape需要修改yololayer plugin的实现，这个有计划升级么？

**Comment by wang-xinyu** [comment]
效果上没差别，

部署阶段动态input并不实用，因为用摄像头是固定尺寸，

有计划要做，也欢迎PR

**Comment by mdztravelling** [comment]
> 效果上没差别，
> 
> 部署阶段动态input并不实用，因为用摄像头是固定尺寸，
> 
> 有计划要做，也欢迎PR

感谢！
input的动态shape在一些场景下还是需要的。
