### ISSUE TITLE
how to run yolov5 on trt5

### ISSUE THREAD

**Issue by flyingmrwang** [wang-xinyu/tensorrtx#177]
Hi, thanks for your brilliant work. My current using model is yolov3 running on trt5.1.5. But I wanna upgrade model to yolov5 while keep using trt5. It is good to heard that branch trt4 is also compatible for trt5. However there is no yolov5 under this branch. Is there any difficulty to implement yolov5 under trt4/5? If not, when will you provide implementation? @wang-xinyu

**Comment by flyingmrwang** [comment]
Actually, I really cannot feel the difference between varies versions of trt. But to avoid unknown trouble, I would prefer keep using trt5.1.5. Any hint or suggestion about trt deployment is appreciated.

**Comment by wang-xinyu** [comment]
You can refer to https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/migrating_from_tensorrt_4_to_7.md  and migrate from trt7 to trt4.
