### ISSUE TITLE
yolov5x  trt 性能问题

### ISSUE THREAD

**Issue by mdztravelling** [wang-xinyu/tensorrtx#178]
hello,您 好

    我在nvidia P4 GPU机器上推理yolov5x trt，batch-size=1，2时，FPS只有16 左右 ，请问下，这个性能正常么？感觉并没有加速。
    input shape 为 640 * 640
   若与你的性能存在差异，请求一般应该在哪里有问题？感谢。

**Comment by wang-xinyu** [comment]
我的gtx1080，yolov5x是29fps，可能你的显卡设置有问题，可以试试其他机器
