### ISSUE TITLE
windows yolov3, do not generate lib file

### ISSUE THREAD

**Issue by xjsxujingsong** [wang-xinyu/tensorrtx#179]
Hi, I follow the yolov5 instruction on windows to build yolov3
Here is the error
1>LINK : fatal error LNK1181: cannot open input file 'Release\yololayer.lib'
1>Done building project "yolov3.vcxproj" -- FAILED.
I checked only yololayer.dll generated.

**Comment by cocoyen1995** [comment]
Hi @xjsxujingsong, 

I met the same issue as yours, have you solved the problem?
