### ISSUE TITLE
How to use batchsize in retinaface?

### ISSUE THREAD

**Issue by HHCorp** [wang-xinyu/tensorrtx#18]

**Comment by wang-xinyu** [comment]
@HHCorp   Currently, only `batch=1` is supported retinaface in this repo. You can refer to yolov4 in this repo for multi-batch implementation.

**Comment by HHCorp** [comment]
> @HHCorp Currently, only `batch=1` is supported in retinaface in this repo. You can refer to yolov4 in this repo for multi-batch implementation.
thanks for your reply. I tried to implement multi-batch in retinaface and edited the decode.cu file but always got the incorrect output expect the first image of one batch. can I ask which part should be edited for multi-batch implementation and how?

**Comment by HHCorp** [comment]
@wang-xinyu thanks for your reply. I tried to implement multi-batch in retinaface and edited the decode.cu file but always got the incorrect output expect the first image of one batch. can I ask which part should be edited for multi-batch implementation and how?

**Comment by wang-xinyu** [comment]
@HHCorp 
1. the input, multi-batch should be prepared, and in doInferrence(), multi-batch input buffer should be copied to GPU;
2. the output, in doInferrence(), multi-batch output buffer should be copied from GPU;
3. make sure the plugin is adapted to support multi-batch

**Comment by HHCorp** [comment]
@wang-xinyu thanks a lot. implemented multi-batch. thanks again for this amazing work^ ^. by the way, It looks like that the link in retinaface page for jumping to wang-xinyu/Pytorch_Retinaface havs a problem. it still direct to  biubug6 s repo.

**Comment by wang-xinyu** [comment]
@HHCorp ok, thanks for remind me this.

**Comment by zhouyongxyz** [comment]
> @wang-xinyu thanks a lot. implemented multi-batch. thanks again for this amazing work^ ^. by the way, It looks like that the link in retinaface page for jumping to wang-xinyu/Pytorch_Retinaface havs a problem. it still direct to biubug6 s repo.

@HHCorp have you solved this problem ? i change the multi plugin get the segmentation fault.
