### ISSUE TITLE
yolov4 img_size

### ISSUE THREAD

**Issue by WSTao** [wang-xinyu/tensorrtx#181]
我在生成yolov4 engine的时候，出现 kernel weights has count 13056 but 12288 was expected，我想是不是因为我输入height不等于weight导致的。yolov4官网支持输入宽不等于高，但yolov5官网仅支持输入宽 = 高。

**Comment by wang-xinyu** [comment]
宽高可以不一样，但是需要能被32整除

**Comment by WSTao** [comment]
@wang-xinyu 
我修改了yololayer.h 中的INPUT_H = 544, INPUT_W = 960,都可以被32整除。但我在执行yolov4 -s 时，报错[E] [TRT] (Unnamed Layer* 315) [Convolution]: kernel weights has count 13056 but 12288 was expected，

**Comment by wang-xinyu** [comment]
class num类别数对吗

**Comment by WSTao** [comment]
@wang-xinyu 
我的数据类别是11，修改了

**Comment by wang-xinyu** [comment]
那就是你用的模型和官方的yolov4模型有差别，除了后面3个卷积之外。对照一下createEngine()函数中的网络定义

**Comment by WSTao** [comment]
@wang-xinyu 非常感谢，我对照发现是我类别漏掉了一个，导致第149层卷积核数不一致。

我想再请教您一个问题，tensorrt的engine文件如何获取浅层输出呢，我想提取浅层特征用于特征匹配计算，不知道tensorrt怎么获取中间层输出呢

**Comment by wang-xinyu** [comment]
把中间层mark为output，支持多个output，但是doinference的时候要把多个output copy出来

**Comment by WSTao** [comment]
@wang-xinyu 明白了，非常感谢

**Comment by WSTao** [comment]
@wang-xinyu 您好！
假如我输入为640*640，将bottleneck_csp4层mark为输出（两次下采样），我分配cudamalloc大小为:
batch_size * ( 640 / 4) * ( 640 / 4) * out_channel * sizeof(float), 但在copy结果时，报cuda错误。我想问，中间层的占用的显存大小如何获取或者计算呢？

**Comment by wang-xinyu** [comment]
中间层大小可以通过pytorch print打印
