### ISSUE TITLE
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueueV2::546, condition: !mEngine.hasImplicitBatchDimension()

### ISSUE THREAD

**Issue by Catman155** [wang-xinyu/tensorrtx#185]
This happens during inference in my python script. I read online it could be something with serialization. Is this the case? Any ideas?

**Comment by wang-xinyu** [comment]
is it yolov5? did you try the c++ program?

**Comment by Catman155** [comment]
Yes sorry for the missing context. I used the c++ application to generate the yolov5 engine, which I tried to use with my existing tensorrt application which is in python. I always used the tensorrt-demos to generate the engine for yolov3, but noe that I want to use yolov5, it seems so much more difficult.

**Comment by wang-xinyu** [comment]
firstly  ensure the c++ app can run properly.

Then using the python wrapper to load the .engine and run.

BTW, This repo is mainly for c++ users.

**Comment by Catman155** [comment]
I converted the Yolov5 class in the python script to our own python script. Now it works, The steps are almost the same, I still don't understand what is wrong, but it seems to work alright now.

**Comment by hushunda** [comment]
> I converted the Yolov5 class in the python script to our own python script. Now it works, The steps are almost the same, I still don't understand what is wrong, but it seems to work alright now.

i have meet same problem.can you share you solution?
