### ISSUE TITLE
./arcface-r50 -s  时候报错

### ISSUE THREAD

**Issue by keepdevelopment** [wang-xinyu/tensorrtx#186]
大佬，报错信息如下，
# ./arcface-r50 -s 
Loading weights: ../arcface-r50.wts
[09/13/2020-22:02:54] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
arcface-r50: /home/tensorrtx/arcface/arcface-r50.cpp:107: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::string, float): Assertion `scale_1' failed.
Aborted (core dumped)
，麻烦可以告诉我一下该怎么解决么

**Comment by jiagh2010** [comment]
没生成arcface-r50.wts？@keepdevelopment

**Comment by keepdevelopment** [comment]
> 没生成arcface-r50.wts？@keepdevelopment

不是，我发现我用的是r34.wts,sorry ，我已经closed了，

**Comment by jiagh2010** [comment]
@keepdevelopment  我也是用的r34转的，结果和insightface官网结果不一致，所以问问有没有遇到相同问题的人的

**Comment by keepdevelopment** [comment]
> @keepdevelopment 我也是用的r34转的，结果和insightface官网结果不一致，所以问问有没有遇到相同问题的人的

啊，这个官网提供的是r50，难道这个可以通用，兄弟，加个好友吧，以后一起讨论问题，聊聊天，也好，总会有收获的，wechat 18217106235
