### ISSUE TITLE
yolov4与原版darknet比起来，精度下降有点厉害，尤其是密集场景

### ISSUE THREAD

**Issue by deep-practice** [wang-xinyu/tensorrtx#19]

**Comment by wang-xinyu** [comment]
MAX_OUTPUT_BBOX_COUNT调高，

**Comment by deep-practice** [comment]
有点改善，但总体来说较原版还是有点差别。不过很感谢作者的开源，简直是学习trt的极好教程了。

**Comment by wang-xinyu** [comment]
@deep-practice 原版用的NMS好像是DIoU-NMS，我这里用的普通NMS，如果配置都一样，精度应该没有差别的，因为网络的output是一样的，可以再深入对比一下
