### ISSUE TITLE
关于yolov5.cpp有个疑问

### ISSUE THREAD

**Issue by bulingda** [wang-xinyu/tensorrtx#190]
![1600308970(1)](https://user-images.githubusercontent.com/55130106/93411984-e066b400-f8ce-11ea-941a-d22bc946bcb7.png)
上图左边的tensorrtx中yolov5.cpp（s）中的网络代码，右边是v5官方的yolov5s.xml中的head，为什么层数不一样呢？右边多了3个卷积层。

**Comment by wang-xinyu** [comment]
我不知道xml里面数字怎么来的，我是print model然后按照print出来的结构写的

**Comment by bulingda** [comment]
> 我不知道xml里面数字怎么来的，我是print model然后按照print出来的结构写的

model就是根据xml里的东西来生成的，我打印了1.0的model，也是27层。你打印出来不是27层吗？
![1600330849(1)](https://user-images.githubusercontent.com/55130106/93440026-d4e0b080-f901-11ea-8932-a2f4b5e7e5d8.png)

**Comment by wang-xinyu** [comment]
```

import torch
import struct
from utils.torch_utils import select_device

# Initialize
device = select_device('cpu')
# Load model
model = torch.load('weights/yolov5s.pt', map_location=device)['model'].float()  # load to FP32
model.to(device).eval()
print(model)
```

这样print model 结构

**Comment by bulingda** [comment]
> ```
> 
> import torch
> import struct
> from utils.torch_utils import select_device
> 
> # Initialize
> device = select_device('cpu')
> # Load model
> model = torch.load('weights/yolov5s.pt', map_location=device)['model'].float()  # load to FP32
> model.to(device).eval()
> print(model)
> ```
> 
> 这样print model 结构

我这样打印出来也还是27层啊
![1600332329(1)](https://user-images.githubusercontent.com/55130106/93447670-41a97a00-f905-11ea-8247-a3317f6d5a8a.jpg)

**Comment by wang-xinyu** [comment]
你这个是yolov5 v3.0的模型吗？？？？？

**Comment by bulingda** [comment]
> 你这个是yolov5 v3.0的模型吗？？？？？

1.0的s版本啊。

**Comment by wang-xinyu** [comment]
我的master分支是3.0啊，看readme！

**Comment by bulingda** [comment]
> 我的master分支是3.0啊，看readme！

![image](https://user-images.githubusercontent.com/55130106/93449073-e24c6980-f906-11ea-8ee6-cebf5bcdacae.png)
不支持1.0的s版本？

**Comment by wang-xinyu** [comment]
往下看完

**Comment by bulingda** [comment]
> 往下看完

小弟理解能力不行，为此还特意翻译成中文仔仔细细看了一遍，还是没看懂，还请大佬赐教！这哪里写了只能3.0用啊？
![image](https://user-images.githubusercontent.com/55130106/93451412-baaad080-f909-11ea-9eb0-77f34c6aad0c.png)

**Comment by wang-xinyu** [comment]
如果用1.0，要checkout到0504551那个commit。先了解下git的commit和checkout吧

**Comment by bulingda** [comment]
> 如果用1.0，要checkout到0504551那个commit。先了解下git的commit和checkout吧

又get一个新技能，感谢大佬指点。

**Comment by bulingda** [comment]
@wang-xinyu 非常非常感谢你的解答，我修改了我的tensorrtx代码并且运行成功了。
