### ISSUE TITLE
Serialized version of trained model (non-standard yolov5) doesn't work

### ISSUE THREAD

**Issue by Catman155** [wang-xinyu/tensorrtx#191]
Hi, I've got this issue where a trained model serialized doesn't give good results. If I serialize the default yolov5s model, it works. But if I trained a model based on the weights of the yolov5s model, it doesn't work. Maybe I need to change more in the cpp code? It is not clear what the issue can be.

**Comment by wang-xinyu** [comment]
the anchors, need to adapt

**Comment by Catman155** [comment]
I trained the model with the weights of yolov5s and the config of yolov5s, so it should take the anchors which are declared in yolov5s.yaml. I used --noautoanchors when training to prevent the train script from generating optimized anchors. I looked at the PT files in netron but the only thing that is different is the Detect step.

**Comment by wang-xinyu** [comment]
what is  Detect step?

**Comment by Catman155** [comment]
![image](https://user-images.githubusercontent.com/18446372/93437974-ee1b3a00-f8cc-11ea-971e-54a881c78ac6.png)

**Comment by wang-xinyu** [comment]
17 , 20, 23, is it?

**Comment by Catman155** [comment]
That part is the same as in the standard yolov5s.pt, which does work

**Comment by wang-xinyu** [comment]
what's the  version of your yolov5s trained model? v1, v2 or v3?

**Comment by Catman155** [comment]
v3.0

**Comment by wang-xinyu** [comment]
pls double check the anchor values.   or print the two model and compare.

**Comment by Catman155** [comment]
```
# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```
These are the anchor values in the yolov5s.yaml. those are also the ones used during training.

**Comment by wang-xinyu** [comment]
There must be somewhere different. You need compare the two models.

**Comment by Catman155** [comment]
The only things that are different (as far as I can see in Netron), are the `nc`, `no` and `np` parameters in the Detect part. I'm using 3 classes instead of 80. so the `nc` difference between 80 and 3 is logical. The `no` part went from 85 to 8, I don't know what that value exactly is. And the `np` went from 229245 to 21576. Are those values that need to adapt in the tensorrtx yolov5 code? The only other difference I can find is the grid. But I assume this just contains all the weights for the detection itself.

**Comment by wang-xinyu** [comment]
did you modify the class_num in yololayer.h

**Comment by Catman155** [comment]
Yes, I modified that one to 3.

**Comment by Catman155** [comment]
Ok, I didn't really change anything, I re-ran the whole process and now it seems to be working. I will be reporting back if it really works well after some testing

**Comment by Catman155** [comment]
I figured out the probable cause. the plugin changes too if you change some settings.
