### ISSUE TITLE
fatal error: cuda_runtime_api.h: No such file or directory

### ISSUE THREAD

**Issue by azuryl** [wang-xinyu/tensorrtx#2]
project/resnet/resnext50_32x4d.cpp:2:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include "cuda_runtime_api.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/resnext50.dir/build.make:62: recipe for target 'CMakeFiles/resnext50.dir/resnext50_32x4d.cpp.o' failed
make[2]: *** [CMakeFiles/resnext50.dir/resnext50_32x4d.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/resnext50.dir/all' failed
make[1]: *** [CMakeFiles/resnext50.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
Hi,
pls check your cuda installation, ‘cuda_runtime_api.h’ is in `/usr/local/cuda/include` on my server.

```
user@user-SYS-7048GR:/usr/local/cuda/include$ ll cuda_runtime_api.h 
-rw-r--r-- 1 root root 401316 Sep 13  2018 cuda_runtime_api.h
user@user-SYS-7048GR:/usr/local/cuda/include$ 
```

**Comment by azuryl** [comment]
fixed in CMakeLists.txt 
include_directories(/usr/local/cuda-10.0/targets/aarch64-linux/include)
link_directories(/usr/local/cuda-10.0/targets/aarch64-linux/lib)
