### ISSUE TITLE
change tensorrt engine data type from fp32 to fp16 

### ISSUE THREAD

**Issue by YuzhouPeng** [wang-xinyu/tensorrtx#201]
hello, I would like to improve the infer speed of my Tensorrt engine, how can I change the data type of tensorrt engine from fp32 to fp16(or int32, int8)?
Thanks a lot!

**Comment by wang-xinyu** [comment]
for eample, yolov5,  just set the USE_FP16 macro,  it will use fp16.

**Comment by YuzhouPeng** [comment]
If I use the classification model such as resnet, inception, how can I change the model to use fp16 or int8? thx

**Comment by wang-xinyu** [comment]
refer to the yolov5.cpp, for fp16, just need one line.

for int8, check the nvidia tensorrt docs, int8 needs calibration process.
