### ISSUE TITLE
tensorflow模型怎么转 .wts 文件？

### ISSUE THREAD

**Issue by pengboc** [wang-xinyu/tensorrtx#204]
你好，我用tensorflow框架训练了一个yolov4模型，怎么将这个模型转成 .wts 文件呢

**Comment by wang-xinyu** [comment]
可以参考我提供的gen_wts.py自己导出tf的wts。  或者先把tf模型转成pytorch或者darknet模型，再用https://github.com/ultralytics/yolov3和gen_wts.py导出wts

**Comment by upczww** [comment]
@pengboc 是哪个仓库的，我可以帮忙看看

**Comment by pengboc** [comment]
https://github.com/hunglc007/tensorflow-yolov4-tflite
是用这份代码训练的
谢谢，麻烦你了

**Comment by pengboc** [comment]
解决了模型转换的问题。采用的方法是，先自己写脚本转darknet模型，再用你的脚本转成wts。
自己训练的模型，若类别数与coco数据集不一致的话，记得修改cfg文件中的参数。否则会报参数数量缺少的错误。

**Comment by wang-xinyu** [comment]
@pengboc :thumbsup:

**Comment by pengboc** [comment]
tensorrt预测的结果与tensorflow预测的不一致
发现，是bn层的eps参数的默认值不一致导致的。在tensorflow中，eps值默认为1e-3，在tensorRT中，eps值默认为1e-4。修改后，结果就一致了。
顺便说一下，pytorch中，eps值默认为1e-5。
采用别的框架训练的模型时，记得修改一下该值。由于该值只是一个微小的常量，因此很容易忽略。需要注意点

**Comment by TengFeiHan0** [comment]
@pengboc 怎么转darknet的过程可以 分享一下吗

**Comment by pengboc** [comment]
那个仓库有实现导入yolov4.weights权重的代码。根据那个代码，再反向实现就可以了。贴上我的代码，你参考下，有点乱哈

import core.utils as utils
import tensorflow as tf
from absl import app, flags, logging
from absl.flags import FLAGS
from core.yolov4 import YOLOv4, YOLOv3, YOLOv3_tiny, decode, decode_tiny

from core.config import cfg
import numpy as np

flags.DEFINE_string('weights', './checkpoints/0707/yolov4_96', 'path to weights file')  # ./checkpoints/0707/yolov4_96
flags.DEFINE_string('output', './checkpoints/0707/yolov4_96.weights', 'path to output')   # ./checkpoints/0707/yolov4_96.weights
flags.DEFINE_boolean('tiny', False, 'is yolov3-tiny or not')
flags.DEFINE_integer('input_size_x', 480, 'define input size of export model')
flags.DEFINE_integer('input_size_y', 640, 'define input size of export model')
# flags.DEFINE_string('model', 'yolov4', 'yolov3 or yolov4')


def main(_argv):
    NUM_CLASS = len(utils.read_class_names(cfg.YOLO.CLASSES))
    input_layer = tf.keras.layers.Input([FLAGS.input_size_x, FLAGS.input_size_y, 3])
    XYSCALE = cfg.YOLO.XYSCALE
    ANCHORS = utils.get_anchors(cfg.YOLO.ANCHORS, FLAGS.tiny)
    STRIDES = np.array(cfg.YOLO.STRIDES)

    feature_maps = YOLOv4(input_layer, NUM_CLASS)
    bbox_tensors = []
    for i, fm in enumerate(feature_maps):
        # bbox_tensor = decode(fm, NUM_CLASS, i)
        bbox_tensor = decode_tiny(fm, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE)
        bbox_tensors.append(bbox_tensor)
    model = tf.keras.Model(input_layer, bbox_tensors)
    # utils.load_weights(model, FLAGS.weights)
    model.load_weights(FLAGS.weights)

    wf = open(FLAGS.output, 'wb')
    header_info = np.array([0, 2, 5, 32032000, 0], dtype=np.int32)
    header_info.tofile(wf)

    j = 0
    for i in range(110):
        conv_layer_name = 'conv2d_%d' % i if i > 0 else 'conv2d'
        bn_layer_name = 'batch_normalization_%d' % j if j > 0 else 'batch_normalization'

        conv_weights = model.get_layer(conv_layer_name).get_weights()

        if i not in [93, 101, 109]:
            # tf weights: [gamma, beta, mean, variance], darknet weights: [beta, gamma, mean, variance]
            bn_weights = np.array(model.get_layer(bn_layer_name).get_weights())[[1, 0, 2, 3]]
            bn_weights.tofile(wf)
            j += 1
        else:
            conv_bias = conv_weights[1]
            conv_bias.tofile(wf)

        filter_weights = conv_weights[0].transpose([3, 2, 0, 1])
        filter_weights.tofile(wf)

    wf.close()


if __name__ == '__main__':
    try:
        app.run(main)
    except SystemExit:
        pass

**Comment by pengboc** [comment]
那个仓库有实现导入yolov4.weights权重的代码。根据那个代码，再反向实现就可以了。贴上我的代码，你参考下，有点乱哈
```
import core.utils as utils
import tensorflow as tf
from absl import app, flags, logging
from absl.flags import FLAGS
from core.yolov4 import YOLOv4, YOLOv3, YOLOv3_tiny, decode, decode_tiny

from core.config import cfg
import numpy as np

flags.DEFINE_string('weights', './checkpoints/0707/yolov4_96', 'path to weights file')  
flags.DEFINE_string('output', './checkpoints/0707/yolov4_96.weights', 'path to output') 
flags.DEFINE_boolean('tiny', False, 'is yolov3-tiny or not')
flags.DEFINE_integer('input_size_x', 480, 'define input size of export model')
flags.DEFINE_integer('input_size_y', 640, 'define input size of export model')


def main(_argv):
    NUM_CLASS = len(utils.read_class_names(cfg.YOLO.CLASSES))
    input_layer = tf.keras.layers.Input([FLAGS.input_size_x, FLAGS.input_size_y, 3])
    XYSCALE = cfg.YOLO.XYSCALE
    ANCHORS = utils.get_anchors(cfg.YOLO.ANCHORS, FLAGS.tiny)
    STRIDES = np.array(cfg.YOLO.STRIDES)

    feature_maps = YOLOv4(input_layer, NUM_CLASS)
    bbox_tensors = []
    for i, fm in enumerate(feature_maps):
        bbox_tensor = decode_tiny(fm, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE)
        bbox_tensors.append(bbox_tensor)
    model = tf.keras.Model(input_layer, bbox_tensors)
    model.load_weights(FLAGS.weights)

    wf = open(FLAGS.output, 'wb')
    header_info = np.array([0, 2, 5, 32032000, 0], dtype=np.int32)
    header_info.tofile(wf)

    j = 0
    for i in range(110):
        conv_layer_name = 'conv2d_%d' % i if i > 0 else 'conv2d'
        bn_layer_name = 'batch_normalization_%d' % j if j > 0 else 'batch_normalization'

        conv_weights = model.get_layer(conv_layer_name).get_weights()

        if i not in [93, 101, 109]:
            # tf weights: [gamma, beta, mean, variance], darknet weights: [beta, gamma, mean, variance]
            bn_weights = np.array(model.get_layer(bn_layer_name).get_weights())[[1, 0, 2, 3]]
            bn_weights.tofile(wf)
            j += 1
        else:
            conv_bias = conv_weights[1]
            conv_bias.tofile(wf)

        filter_weights = conv_weights[0].transpose([3, 2, 0, 1])
        filter_weights.tofile(wf)

    wf.close()


if __name__ == '__main__':
    try:
        app.run(main)
    except SystemExit:
        pass
```

**Comment by pengboc** [comment]
使用 pytorch 训练的模型时，注意激活函数 `nn.LeakyReLU()`， 在pytorch中默认为 1e-2

**Comment by Byronnar** [comment]
> 那个仓库有实现导入yolov4.weights权重的代码。根据那个代码，再反向实现就可以了。贴上我的代码，你参考下，有点乱哈
> 
> ```
> import core.utils as utils
> import tensorflow as tf
> from absl import app, flags, logging
> from absl.flags import FLAGS
> from core.yolov4 import YOLOv4, YOLOv3, YOLOv3_tiny, decode, decode_tiny
> 
> from core.config import cfg
> import numpy as np
> 
> flags.DEFINE_string('weights', './checkpoints/0707/yolov4_96', 'path to weights file')  
> flags.DEFINE_string('output', './checkpoints/0707/yolov4_96.weights', 'path to output') 
> flags.DEFINE_boolean('tiny', False, 'is yolov3-tiny or not')
> flags.DEFINE_integer('input_size_x', 480, 'define input size of export model')
> flags.DEFINE_integer('input_size_y', 640, 'define input size of export model')
> 
> 
> def main(_argv):
>     NUM_CLASS = len(utils.read_class_names(cfg.YOLO.CLASSES))
>     input_layer = tf.keras.layers.Input([FLAGS.input_size_x, FLAGS.input_size_y, 3])
>     XYSCALE = cfg.YOLO.XYSCALE
>     ANCHORS = utils.get_anchors(cfg.YOLO.ANCHORS, FLAGS.tiny)
>     STRIDES = np.array(cfg.YOLO.STRIDES)
> 
>     feature_maps = YOLOv4(input_layer, NUM_CLASS)
>     bbox_tensors = []
>     for i, fm in enumerate(feature_maps):
>         bbox_tensor = decode_tiny(fm, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE)
>         bbox_tensors.append(bbox_tensor)
>     model = tf.keras.Model(input_layer, bbox_tensors)
>     model.load_weights(FLAGS.weights)
> 
>     wf = open(FLAGS.output, 'wb')
>     header_info = np.array([0, 2, 5, 32032000, 0], dtype=np.int32)
>     header_info.tofile(wf)
> 
>     j = 0
>     for i in range(110):
>         conv_layer_name = 'conv2d_%d' % i if i > 0 else 'conv2d'
>         bn_layer_name = 'batch_normalization_%d' % j if j > 0 else 'batch_normalization'
> 
>         conv_weights = model.get_layer(conv_layer_name).get_weights()
> 
>         if i not in [93, 101, 109]:
>             # tf weights: [gamma, beta, mean, variance], darknet weights: [beta, gamma, mean, variance]
>             bn_weights = np.array(model.get_layer(bn_layer_name).get_weights())[[1, 0, 2, 3]]
>             bn_weights.tofile(wf)
>             j += 1
>         else:
>             conv_bias = conv_weights[1]
>             conv_bias.tofile(wf)
> 
>         filter_weights = conv_weights[0].transpose([3, 2, 0, 1])
>         filter_weights.tofile(wf)
> 
>     wf.close()
> 
> 
> if __name__ == '__main__':
>     try:
>         app.run(main)
>     except SystemExit:
>         pass
> ```

你好, 请问这个 decode, decode_tiny 在哪呢, 具体是如何实现的, https://github.com/hunglc007/tensorflow-yolov4-tflite这个仓库里面没有啊.

**Comment by pengboc** [comment]
好像是我自己实现的，模仿着decode_tf函数实现的

**Comment by Byronnar** [comment]
> 好像是我自己实现的，模仿着decode_tf函数实现的

那请问能不能提供一下呢?  想学习一下, 谢谢啦, 我看源码里面有 decode_train函数.

**Comment by pengboc** [comment]
![image](https://user-images.githubusercontent.com/28076332/111581698-b302b080-87f4-11eb-8db9-9ffe63a3cbef.png)
源码中decode的代码还是挺多的

```
def decode_tiny(conv_output, NUM_CLASS, STRIDES, ANCHORS, i=0, XYSCALE=[1, 1, 1]):
    conv_shape = tf.shape(conv_output)

    batch_size = conv_shape[0]
    output_size_h = conv_shape[1]
    output_size_w = conv_shape[2]
    output_size_max = output_size_w

    conv_output = tf.reshape(conv_output, (batch_size, output_size_h, output_size_w, 3, 5 + NUM_CLASS))

    conv_raw_dxdy, conv_raw_dwdh, conv_raw_conf, conv_raw_prob = tf.split(conv_output, (2, 2, 1, NUM_CLASS),
                                                                          axis=-1)

    x = tf.tile(tf.expand_dims(tf.range(output_size_max, dtype=tf.int32), axis=0), [output_size_max, 1])
    y = tf.tile(tf.expand_dims(tf.range(output_size_max, dtype=tf.int32), axis=1), [1, output_size_max])
    xy_grid = tf.expand_dims(tf.stack([x, y], axis=-1), axis=2)  # [gx, gy, 1, 2]
    xy_grid = xy_grid[:output_size_h, :output_size_w]

    xy_grid = tf.tile(tf.expand_dims(xy_grid, axis=0), [batch_size, 1, 1, 3, 1])

    xy_grid = tf.cast(xy_grid, tf.float32)

    pred_xy = ((tf.sigmoid(conv_raw_dxdy) * XYSCALE[i]) - 0.5 * (XYSCALE[i] - 1) + xy_grid)# * STRIDES[i]
    pred_wh = (tf.exp(conv_raw_dwdh) * ANCHORS[i]) / STRIDES[i]

    pred_x1y1 = pred_xy - (pred_wh/2)
    pred_x2y2 = pred_xy + (pred_wh/2)

    boxes_yx = tf.stack([
        pred_x1y1[..., 1] / tf.cast(output_size_h, dtype=tf.float32),  # y_min * STRIDES[i]
        pred_x1y1[..., 0] / tf.cast(output_size_w, dtype=tf.float32),  # x_min * STRIDES[i]
        pred_x2y2[..., 1] / tf.cast(output_size_h, dtype=tf.float32),  # y_max * STRIDES[i]
        pred_x2y2[..., 0] / tf.cast(output_size_w, dtype=tf.float32),   # x_max * STRIDES[i]
    ], axis=4)


    pred_conf = tf.sigmoid(conv_raw_conf)
    pred_prob = tf.sigmoid(conv_raw_prob)

    pred_prob = pred_conf * pred_prob
    pred_prob = tf.reshape(pred_prob, (-1, NUM_CLASS))

    boxes_yx = tf.reshape(boxes_yx, (-1, 4))

    return tf.concat([boxes_yx, pred_prob], axis=-1)

```
时间有点久，都不知道是不是这份代码。你将就看看吧，或者，多试试。

**Comment by Byronnar** [comment]
好的, 非常感谢您这么快速的回复! 我也尝试一下!
