### ISSUE TITLE
Have you ever measured the FPS of yolov4 with jetson agx xavier?

### ISSUE THREAD

**Issue by Hiroaki-K4** [wang-xinyu/tensorrtx#205]
Hi! Thank you for your work!
Have you ever measured the FPS of yolov4 with jetson agx xavier?
If so, please let me know.

**Comment by wang-xinyu** [comment]
no, but it can run on xavier. You can test it yourself.

**Comment by Hiroaki-K4** [comment]
ok. Thanks!
