### ISSUE TITLE
能提供一下shufflenet-v2中chunk插件的IPluginV2的实现吗

### ISSUE THREAD

**Issue by CBIR-LL** [wang-xinyu/tensorrtx#206]
感谢您的代码分享。chunk插件是入门的示例插件，很受用。但只有IPluginv1版本，现在的RT推荐使用IPluginv2版本，因为刚接触，自己不太会写RT插件。所以弱弱的一下，大佬能抽空推一个IPluginv2版本的实现吗？这样对比起来，对新手会更加的友好，方便入门。

**Comment by wang-xinyu** [comment]
我可以在交流群里问问看，有没有人想写

**Comment by CBIR-LL** [comment]
> 我可以在交流群里问问看，有没有人想写

好的，非常感谢！
