### ISSUE TITLE
about Ultra

### ISSUE THREAD

**Issue by WSTao** [wang-xinyu/tensorrtx#207]
我看到作者公布了车道线的算法，ultra自身效率已经很高了，作者有没有计划部署Lanenet或者Pinet网络呢，或者华为最近发布的CurveLanes

**Comment by wang-xinyu** [comment]
@hwh-hit

**Comment by hwh-hit** [comment]
@WSTao 你好，是的，ultra自身效率已经比较高了，但tensorrtx下的实现是为了更好的用C++在 nvidia 板子进行部署，至于其他的网络，有效果比现在更好的，会尝试部署。

**Comment by WSTao** [comment]
> @WSTao 你好，是的，ultra自身效率已经比较高了，但tensorrtx下的实现是为了更好的用C++在 nvidia 板子进行部署，至于其他的网络，有效果比现在更好的，会尝试部署。

好的，非常感谢

**Comment by hwh-hit** [comment]
ok
