### ISSUE TITLE
yolov4 Unsupported fields

### ISSUE THREAD

**Issue by sherlockking** [wang-xinyu/tensorrtx#21]
Traceback (most recent call last):
  File "gen_wts.py", line 6, in <module>
    model = Darknet('cfg/yolov4.cfg', (608, 608))
  File "/home/topsci/workspace/yolov3/models.py", line 225, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "/home/topsci/workspace/yolov3/utils/parse_config.py", line 49, in parse_model_cfg
    assert not any(u), "Unsupported fields %s in %s. See https://github.com/ultralytics/yolov3/issues/631" % (u, path)
AssertionError: Unsupported fields ['stopbackward', 'max_delta'] in cfg/yolov4.cfg. See https://github.com/ultralytics/yolov3/issues/631

**Comment by sherlockking** [comment]
I just tried to find solution from darkent and pytorch yolov3 and got that these two parameters may be  are related to training. So I ignored the assertion error. Then I got a wts file.

**Comment by wang-xinyu** [comment]
@sherlockking good,   maybe some updates in yolov4.cfg.
As I said in https://github.com/wang-xinyu/tensorrtx/tree/master/yolov4, you may checkout be87b41aa2fe59be8e62f4b488052b24ad0bd450 if master branch not working.

**Comment by sherlockking** [comment]
The generated engine works well, thx
