### ISSUE TITLE
使用nano tensort5.0跑yolov5-tensorrt，make错误

### ISSUE THREAD

**Issue by Yang-Changhui** [wang-xinyu/tensorrtx#211]
CMakeFiles/myplugins.dir/build.make:63: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
显示这样的错误，是不是说明tensorrt5.0不能用

**Comment by wang-xinyu** [comment]
5不行，至少要6，可以参考教程 [migrating_from_tensorrt_4_to_7](https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/migrating_from_tensorrt_4_to_7.md) 和 trt4分支代码和自己修改，

**Comment by YangChangH** [comment]
好的，谢谢

**Comment by Lixinixn115** [comment]
Jetson TX2，带有tesorrt8.0版，make时也报了这个错误：
CMakeFiles/myplugins.dir/build.make:63: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
不知道如何解决，有解决的或者懂的小伙伴可以回复一下吗？谢谢。
