### ISSUE TITLE
在进行yolov5加速的时候。make之后 ，运行 sudo ./yolov5 -s  这一步的时候，出现了错误； 

### ISSUE THREAD

**Issue by 912338929** [wang-xinyu/tensorrtx#212]
yolov5: /home/boyt/Downloads/tensorrtx/yolov5/common.hpp:197: nvinfer1::ILayer* convBlock(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, int, int, int, int, std::__cxx11::string): Assertion `conv1' failed.

在进行yolov5加速的时候。make之后 ，运行 sudo ./yolov5 -s  这一步的时候，出现了错误；帮忙给看一下！

**Comment by wang-xinyu** [comment]
v1v2v3哪个版本？

**Comment by 912338929** [comment]
V3

**Comment by wang-xinyu** [comment]
wts文件生成了吗，放到哪个目录下了？

**Comment by 912338929** [comment]
/home/boyt/Downloads/tensorrtx/yolov5/

**Comment by wang-xinyu** [comment]
模型和官方release模型有差别吗

**Comment by 912338929** [comment]
没有差别！这个问题是一般是什么原因造成的！

**Comment by wang-xinyu** [comment]
一般是模型不对，和我的代码不匹配

**Comment by 912338929** [comment]
昂，能给个您的模型下载地址吗。我重新下一次试试！

**Comment by wang-xinyu** [comment]
https://github.com/ultralytics/yolov5/releases/tag/v3.0
这里最下面assets

**Comment by 912338929** [comment]
好的，谢谢！

**Comment by 912338929** [comment]
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ../caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ../caffe2/serialize/inline_container.cc:132)
我这是 因为我的torch版本太低了吗？ 我的torch 是1.4.0

**Comment by wang-xinyu** [comment]
要1.6

**Comment by 912338929** [comment]
好的，谢谢！

**Comment by 912338929** [comment]
那我的cuda10.1 是不是不能够进行转换了！这个torch 1.6.0 对应的是cuda10.2吧！

**Comment by wang-xinyu** [comment]
有pytorch1.6-cuda10.1的版本，去官网看下
