### ISSUE TITLE
running"sudo ./yolov5 -s "failed

### ISSUE THREAD

**Issue by JQZhai** [wang-xinyu/tensorrtx#217]
Hi @wang-xinyu ,
Getting the following error running"sudo ./yolov5 -s ":

Loading weights: ../yolov5s.wts
[09/25/2020-14:52:03] [E] [TRT] INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1
段错误

any idea?
Thanks

**Comment by 108356037** [comment]
> Hi @wang-xinyu ,
> Getting the following error running"sudo ./yolov5 -s ":
> 
> Loading weights: ../yolov5s.wts
> [09/25/2020-14:52:03] [E] [TRT] INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1
> 段错误
> 
> any idea?
> Thanks

Same issue here, my hardware is jetson nano

**Comment by wang-xinyu** [comment]
this is a bug from the latest commit.   checkout the commit  on Sep 23, 2020 in temporary. I'll fix it.

**Comment by wang-xinyu** [comment]
fixed at https://github.com/wang-xinyu/tensorrtx/commit/cf63ef000ea6f2f102b2ee756b066cf3560ff792
