### ISSUE TITLE
The inference results is error using TensorRT

### ISSUE THREAD

**Issue by bei91** [wang-xinyu/tensorrtx#218]
hey,
 Thank you for your work. I trained the yolov5 model with my own data.The results are true using pytorch model, but the results are error when convert to the tensorrt engine. the bbox is error.  Do you know why? The example is as follows.
![2020-09-25 17-11-54屏幕截图](https://user-images.githubusercontent.com/16322361/94249541-9f1b7780-ff52-11ea-9410-968103642972.png)

**Comment by wang-xinyu** [comment]
are you using yolov5 v3.0 model?  and can you try the latest commit of this repo?

**Comment by bei91** [comment]
i pull the newest yolov5 master and train the model.

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/commit/cf63ef000ea6f2f102b2ee756b066cf3560ff792

this is the latest commit, which will read the anchor info in .wts. plz try it.

**Comment by bei91** [comment]
the latest commit is good, Thank you for your answer.

**Comment by passion3394** [comment]
@wang-xinyu hello，I use yolov3-spp and yolov4 to convert my custom model, the result is almost the same with @bei91 . Could you give me some advice?

**Comment by passion3394** [comment]
modifying the default anchors is ok.
