### ISSUE TITLE
modify yolov4.cpp, stride=4, don't support?

### ISSUE THREAD

**Issue by passion3394** [wang-xinyu/tensorrtx#220]
I use the https://github.com/AlexeyAB/darknet repo to train my own model

when I try to convert the .weights model to tensorRT .engine. The error comes out.
I found that the cfg file I used is a little bit different with your trt implementation.As following:

(1) deconv layer 128 
[upsample]
stride=4

your implementation is stride=2

(2) layer 141
[convolutional]
batch_normalize=1
size=3
stride=4
pad=1
filters=256
activation=leaky

your implementation is stride=2

I try to modify yolov4.cpp like the following:

(1)
float *deval2 = reinterpret_cast<float*>(malloc(sizeof(float) * 128 * 4 * 4));
    for (int i = 0; i < 128 * 4 * 4; i++) {
        deval2[i] = 1.0;
    }

    Weights deconvwts128{DataType::kFLOAT, deval2, 128 * 4 * 4};
    IDeconvolutionLayer* deconv128 = network->addDeconvolutionNd(*l127->getOutput(0), 128, DimsHW{4, 4}, deconvwts128, emptywts);
    assert(deconv128);
    deconv128->setStrideNd(DimsHW{4, 4});
    deconv128->setNbGroups(128);

(2) 
auto l141 = convBnLeaky(network, weightMap, *l140->getOutput(0), 256, 3, 4, 1, 141);

I successfully convert the model with the path: .weights  -> .wts  -> .engine

I test the .engine with my test samples. But the result is in a mess. Could you please help to check the above code? thanks a lot.

**Comment by passion3394** [comment]
any ideas?

**Comment by wang-xinyu** [comment]
there is a debug trick.  You can set any layer as output, and compare the output values with pytorch output.  If the values are right, it means the model before this layer is fine.    For example, you can set the layer before deconv as output and compare.

**Comment by passion3394** [comment]
thanks. BTW, I try to run tensorRT with specified GPU DEVICE, but it seems that the tensorRT can only run on DEVICE, which lies here  #define DEVICE 4. Any suggetions?

**Comment by wang-xinyu** [comment]
remove this line in yolov4.cpp if you want to set gpu_id outside.

```
cudaSetDevice(DEVICE);
```

**Comment by passion3394** [comment]
thanks a lot.

**Comment by passion3394** [comment]
@wang-xinyu I try to output some layer's feature map, but it failed. Could you give an example ?

**Comment by georgetsu** [comment]
> I use the https://github.com/AlexeyAB/darknet repo to train my own model
> 
> when I try to convert the .weights model to tensorRT .engine. The error comes out. I found that the cfg file I used is a little bit different with your trt implementation.As following:
> 
> (1) deconv layer 128 [upsample] stride=4
> 
> your implementation is stride=2
> 
> (2) layer 141 [convolutional] batch_normalize=1 size=3 stride=4 pad=1 filters=256 activation=leaky
> 
> your implementation is stride=2
> 
> I try to modify yolov4.cpp like the following:
> 
> (1) float _deval2 = reinterpret_cast<float_>(malloc(sizeof(float) * 128 * 4 * 4)); for (int i = 0; i < 128 * 4 * 4; i++) { deval2[i] = 1.0; }
> 
> ```
> Weights deconvwts128{DataType::kFLOAT, deval2, 128 * 4 * 4};
> IDeconvolutionLayer* deconv128 = network->addDeconvolutionNd(*l127->getOutput(0), 128, DimsHW{4, 4}, deconvwts128, emptywts);
> assert(deconv128);
> deconv128->setStrideNd(DimsHW{4, 4});
> deconv128->setNbGroups(128);
> ```
> 
> (2) auto l141 = convBnLeaky(network, weightMap, *l140->getOutput(0), 256, 3, 4, 1, 141);
> 
> I successfully convert the model with the path: .weights -> .wts -> .engine
> 
> I test the .engine with my test samples. But the result is in a mess. Could you please help to check the above code? thanks a lot.

@passion3394, have you resolved this issue?
