### ISSUE TITLE
运行视频帧率

### ISSUE THREAD

**Issue by Yang-Changhui** [wang-xinyu/tensorrtx#221]
想问下，大家yolov5_trt跑视频都是多少帧，我测的时候只有8帧，感觉不太对啊

**Comment by EMJCJP** [comment]
jetson nx设备上5x模型跑摄像头有24帧左右欸

**Comment by clementzhao** [comment]
jetson nano 跑trt只有8帧

**Comment by xiaqing10** [comment]
> jetson nx设备上5x模型跑摄像头有24帧左右欸

精度怎么样，我跑下来5m是50fps, 5x是30fps,但是int8比float16效果还是差多了。

**Comment by sunzhuojun** [comment]
> > jetson nx设备上5x模型跑摄像头有24帧左右欸
> 
> 精度怎么样，我跑下来5m是50fps, 5x是30fps,但是int8比float16效果还是差多了。

yolov5m@50fps是int8下的吗？

**Comment by xiaqing10** [comment]
> > > jetson nx设备上5x模型跑摄像头有24帧左右欸
> > 
> > 
> > 精度怎么样，我跑下来5m是50fps, 5x是30fps,但是int8比float16效果还是差多了。
> 
> yolov5m@50fps是int8下的吗？

再测试一次，yolov5m 4.0 int8和fp16速度没区别。加上前后处理，都是30多fps.
另外，cpu真弱，跑视频然后保存视频，妥妥的就只有几fps了。
