### ISSUE TITLE
ufld使用culane

### ISSUE THREAD

**Issue by lzcchl** [wang-xinyu/tensorrtx#222]
我怎么才能在ufld中检测culane数据集呢，我尝试修改OUTPUT_C、OUTPUT_H，还有网络中22624改成14472，setReshapeDimensions改成201，18，4，然后是vis_h和vis_w，然后是row_anchor，但是检测结果不对，请问我还差哪些位置漏改了呢？

**Comment by lzcchl** [comment]
col_sample_w = 8是什么意思呢？

**Comment by wang-xinyu** [comment]
@hwh-hit

**Comment by hwh-hit** [comment]
@lzcchl col_sample_w在pytorch实现 demo.py 后处理里有提到，我简化了，tusimple中是8，culane是4. 可以对照pytorch源码测试一下，最近我会提交一个culane的版本上去

**Comment by lzcchl** [comment]
改成4就成功了，是我没好好整理源码。。谢谢大佬

**Comment by hwh-hit** [comment]
ok

**Comment by XinnWang** [comment]
@hwh-hit 请问大佬culane的版本有提交么？

**Comment by foxkw** [comment]
> 改成4就成功了，是我没好好整理源码。。谢谢大佬
大佬，我用的culane的权重想去检测数据集， 但是报错显示`(unnamed Layer*73)[constant]:constant weights has count 29638656 but 46333952 was expected` ， 请问有遇到过吗。  是不能直接用culane的权重吗， 但输入输出那些维度我都已经调整了

**Comment by foxkw** [comment]
> @lzcchl col_sample_w在pytorch实现 demo.py 后处理里有提到，我简化了，tusimple中是8，culane是4. 可以对照pytorch源码测试一下，最近我会提交一个culane的版本上去

大佬，如果想用culane的权重怎么改呢，需要改网络里面的结构是吗。 tusimple的权重检测效果比较差
