### ISSUE TITLE
Windows version doesn't compile right

### ISSUE THREAD

**Issue by Catman155** [wang-xinyu/tensorrtx#223]
I am having issues compiling tensorrtx yolov5 on windows. I'm getting these syntax errors:
![image](https://user-images.githubusercontent.com/18446372/94476376-b10a4e00-01d0-11eb-8dad-5dac6c51317a.png)
Did I do something wrong perhaps?

**Comment by BaofengZan** [comment]
Try to change (std::max) in line 76 to std::max. And do the same for the following lines。

**Comment by Catman155** [comment]
Apparently my master version was outdated. Those errors are gone now. But now I have this one 

```2>yolov5.obj : error LNK2019: unresolved external symbol "public: __cdecl nvinfer1::YoloPluginCreator::YoloPluginCreator(void)" (??0YoloPluginCreator@nvinfer1@@QEAA@XZ) referenced in function "public: __cdecl nvinfer1::PluginRegistrar<class nvinfer1::YoloPluginCreator>::PluginRegistrar<class nvinfer1::YoloPluginCreator>(void)" (??0?$PluginRegistrar@VYoloPluginCreator@nvinfer1@@@nvinfer1@@QEAA@XZ)```

**Comment by Catman155** [comment]
Ok if I try to link the myplugins I now get ```Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'Debug\myplugins.lib'	yolov5	C:\Users\Bertus\tensorrtx\yolov5\build\LINK	1	
```

**Comment by wang-xinyu** [comment]
refer to this tutorial https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md
