### ISSUE TITLE
the pre processing time is longer than inference time

### ISSUE THREAD

**Issue by passion3394** [wang-xinyu/tensorrtx#226]
In my custom model testing, the pre-processing time is 30ms, the inference time is 15ms.

how to solve this problem ?

I know darknet use multi-threads to make the pre-processing time nearly zero.

but it's c code, how to migrate it into c++ version? thus we could use in this repo.

**Comment by wang-xinyu** [comment]
Multi-thread pre-processing is in out TODO list, you have to implement it by yourself.

**Comment by passion3394** [comment]
yes, I am trying to do this.
