### ISSUE TITLE
make失败，求帮助

### ISSUE THREAD

**Issue by Buaaailyx** [wang-xinyu/tensorrtx#227]
/usr/bin/ld: warning: libcudart.so.10.1, needed by /home/buaalyx/TensorRT/TensorRT-6.0.1.5.Ubuntu-18.04.x86_64-gnu.cuda-10.1.cudnn7.6/TensorRT-6.0.1.5/lib/libnvinfer.so, may conflict with libcudart.so.9.1
/usr/local/lib/libopencv_core.a(parallel.cpp.o): In function `cv::parallel_for_impl(cv::Range const&, cv::ParallelLoopBody const&, double) [clone ._omp_fn.0]':
parallel.cpp:(.text._ZN2cvL17parallel_for_implERKNS_5RangeERKNS_16ParallelLoopBodyEd._omp_fn.0+0x4b): undefined reference to `GOMP_loop_dynamic_start'
parallel.cpp:(.text._ZN2cvL17parallel_for_implERKNS_5RangeERKNS_16ParallelLoopBodyEd._omp_fn.0+0x1a4): undefined reference to `GOMP_loop_dynamic_next'
parallel.cpp:(.text._ZN2cvL17parallel_for_implERKNS_5RangeERKNS_16ParallelLoopBodyEd._omp_fn.0+0x1b1): undefined reference to `GOMP_loop_end_nowait'
/usr/local/lib/libopencv_core.a(parallel.cpp.o): In function `cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double)':
parallel.cpp:(.text._ZN2cv13parallel_for_ERKNS_5RangeERKNS_16ParallelLoopBodyEd+0x285): undefined reference to `GOMP_parallel'
/usr/local/lib/libopencv_core.a(parallel.cpp.o): In function `cv::getThreadNum()':
parallel.cpp:(.text._ZN2cv12getThreadNumEv+0x1): undefined reference to `omp_get_thread_num'
/usr/local/lib/libopencv_core.a(parallel.cpp.o): In function `cvGetThreadNum':
parallel.cpp:(.text.cvGetThreadNum+0x1): undefined reference to `omp_get_thread_num'
/usr/local/lib/libopencv_core.a(parallel.cpp.o): In function `_GLOBAL__sub_I_parallel.cpp':
parallel.cpp:(.text.startup._GLOBAL__sub_I_parallel.cpp+0x28): undefined reference to `omp_get_max_threads'
parallel.cpp:(.text.startup._GLOBAL__sub_I_parallel.cpp+0x43): undefined reference to `omp_set_dynamic'
CMakeFiles/yolov5s.dir/yolov5.cpp.o: In function `nvinfer1::PluginRegistrar<nvinfer1::YoloPluginCreator>::~PluginRegistrar()':
/home/buaalyx/projects/yolov5/yolov5trt/tensorrtx/yolov5/yololayer.h:107: undefined reference to `vtable for nvinfer1::YoloPluginCreator'
CMakeFiles/yolov5s.dir/yolov5.cpp.o: In function `_GLOBAL__sub_I__Z14preprocess_imgRN2cv3MatE':
/home/buaalyx/TensorRT/TensorRT-6.0.1.5.Ubuntu-18.04.x86_64-gnu.cuda-10.1.cudnn7.6/TensorRT-6.0.1.5/include/NvInferRuntimeCommon.h:1304: undefined reference to `nvinfer1::YoloPluginCreator::YoloPluginCreator()'
CMakeFiles/yolov5s.dir/yolov5.cpp.o: In function `_GLOBAL__sub_I__Z14preprocess_imgRN2cv3MatE':
/home/buaalyx/projects/yolov5/yolov5trt/tensorrtx/yolov5/yololayer.h:107: undefined reference to `vtable for nvinfer1::YoloPluginCreator'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5s.dir/build.make:132: recipe for target '../bin/yolov5s' failed
make[2]: *** [../bin/yolov5s] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5s.dir/all' failed
make[1]: *** [CMakeFiles/yolov5s.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

**Comment by wang-xinyu** [comment]
```
/usr/bin/ld: warning: libcudart.so.10.1, needed by /home/buaalyx/TensorRT/TensorRT-6.0.1.5.Ubuntu-18.04.x86_64-gnu.cuda-10.1.cudnn7.6/TensorRT-6.0.1.5/lib/libnvinfer.so, may conflict with libcudart.so.9.1
```

环境有问题，找一个干净的环境重试一下
