### ISSUE TITLE
yolov5 pytorch版本运行结果 与 tensorRT 有很大差异，精度很低

### ISSUE THREAD

**Issue by liushuan** [wang-xinyu/tensorrtx#228]
使用的是 yolov5s.yaml

yolov5.cpp 设置 如下
//#define USE_FP16  // comment out this if want to use FP32

#define DEVICE 0  // GPU id
#define NMS_THRESH 0.5
#define CONF_THRESH 0.4
#define BATCH_SIZE 1

目前出现的问题是 input_w和h 设置为 608 精度很低，设置为640后，就完全检测不到目标了。

**Comment by wang-xinyu** [comment]
试一下官方模型
