### ISSUE TITLE
error: ‘createPReLUPlugin’ is not a member of ‘nvinfer1::plugin’

### ISSUE THREAD

**Issue by Ashing00** [wang-xinyu/tensorrtx#23]
Hi,Wang

   I try to convert yolov4 on Jetson NX.but meet below issue.
could you help to check it?

//-------------------------------------------------------------
[ 66%] Building CXX object CMakeFiles/yolov4.dir/plugin_factory.cpp.o
In file included from /home/ashing/tensorrtx/yolov4/plugin_factory.cpp:1:0:
/home/ashing/tensorrtx/yolov4/common.h: In function ‘unsigned int samples_common::getElementSize(nvinfer1::DataType)’:
/home/ashing/tensorrtx/yolov4/common.h:271:12: warning: enumeration value ‘kBOOL’ not handled in switch [-Wswitch]
     switch (t)
            ^
/home/ashing/tensorrtx/yolov4/plugin_factory.cpp: In member function ‘virtual nvinfer1::IPlugin* nvinfer1::PluginFactory::createPlugin(const char*, const void*, size_t)’:
/home/ashing/tensorrtx/yolov4/plugin_factory.cpp:13:26: error: ‘createPReLUPlugin’ is not a member of ‘nvinfer1::plugin’
         plugin = plugin::createPReLUPlugin(serialData, serialLength);
                          ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

**Comment by wang-xinyu** [comment]
@Ashing00 what's the tensorrt version on NX? It seems 'createPReLUPlugin' is deprecated in that version.  You can replace the PReLU layer with `addActivation() with ActivationType::kLEAKY_RELU`.

Or you can wait the new branch `trt7` of this repo, the yolov4 in that branch will use tensorrt7 api. It should be open by the end of this month.

**Comment by AshingTsai** [comment]
Hi,Wang
   thank you for your infoemation. Jetson NX use tensorRT 7.1
  I will try your suggestion

**Comment by Ashing00** [comment]
@wang-xinyu 

after overcome  above issue.then when run
./yolov4 -s appear below error.
I have no idea.

//-----------------------------------------------------
.....
ERROR: (Unnamed Layer* 247) [Convolution]: kernel weights has count 4718592 but 9437184 was expected
ERROR: (Unnamed Layer* 247) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 1024 input channels, 1024 output channels and 1 groups were specified. Expected Weights count is 1024 * 3*3 * 1024 / 1 = 9437184
154
len 512
155
len 1024
156
len 512
157
len 1024
158
len 512
159
len 1024
set name out
ERROR: (Unnamed Layer* 247) [Convolution]: kernel weights has count 4718592 but 9437184 was expected
ERROR: (Unnamed Layer* 247) [Convolution]: count of 4718592 weights in kernel, but kernel dimensions (3,3) with 1024 input channels, 1024 output channels and 1 groups were specified. Expected Weights count is 1024 * 3*3 * 1024 / 1 = 9437184
ERROR: Could not compute dimensions for (Unnamed Layer* 247) [Convolution]_output, because the network is not valid.
ERROR: Network validation failed.
build out
yolov4: /home/ashing/tensorrtx/yolov4/yolov4.cpp:516: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
Aborted (core dumped)

**Comment by Ashing00** [comment]
@wang-xinyu

great! I checked your new version for tr7 .It can work on Jetson NX  well.

thank you.

**Comment by wang-xinyu** [comment]
@Ashing00 ok, good to hear!

**Comment by HappyKerry** [comment]
@Ashing00 

> olov4: /home/ashing/tensorrtx/yolov4/yolov4.cpp:516: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
> Aborted (core dumped)

how fix this error?
