### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by hailcpy** [wang-xinyu/tensorrtx#230]
Hey when i am trying to build arcface on Jetson Nano, i am getting the following error. It was working fine on my laptop.
Error:
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFWriteDirectory@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/local/lib/libopencv_imgcodecs.so.4.1.2: undefined reference to `TIFFOpen@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
CMakeFiles/arcface-r50.dir/build.make:157: recipe for target 'arcface-r50' failed
make[2]: *** [arcface-r50] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/arcface-r50.dir/all' failed
make[1]: *** [CMakeFiles/arcface-r50.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can u please help to solve this error. Thank you

**Comment by wang-xinyu** [comment]
Your opencv dependencies may be broken,  you may need try reinstall the OS.

**Comment by hailcpy** [comment]
Thanks. Fixed.
