### ISSUE TITLE
生成retinaface的engine文件报错  `./retina`

### ISSUE THREAD

**Issue by ZongweiZhou1** [wang-xinyu/tensorrtx#236]
你好, @wang-xinyu 

首先谢谢您的分享。

我在使用该项目时，按照readme文件的步骤，生成wts文件以及编译都没问题，但是生成retinaface的engine文件时出现错误
```
Loading weights: ../retinaface.wts
[10/09/2020-19:22:10] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
retina_r50: /home/zwzhou/Code/tensorrtx/retinaface/retina_r50.cpp:206: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted (core dumped)
```

环境：
```
ubuntu 16.04
python  3.6
pytorch 11.0
TensorRT 7.0.0.11
cuda   9.0
cudnn 7.6.5
```
 
单独测试 TensorRT, cuda, cudnn没问题，应该不是版本不一致问题。

感觉是网络addScale层的问题，但是我下载的retinaface参数和源码都是[https://github.com/wang-xinyu/Pytorch_Retinaface](https://github.com/wang-xinyu/Pytorch_Retinaface) 中提供的。

请问这种问题该怎么解决呢？

**Comment by wang-xinyu** [comment]
是按照这个步骤操作的吗 https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface#run

有没有执行python detect.py --save_model

**Comment by ZongweiZhou1** [comment]
是的，按这个步骤生成了retinaface.wts

文件的开头数值：
![image](https://user-images.githubusercontent.com/28044312/95643851-84b1d400-0ae4-11eb-864a-c90dbb59b37a.png)

···
300
body.stage1.0.0.weight 216 3dd6fc07 bc0bcce8 bd6bcfa4 be00a107 3d6d0c1b 3dc22d ...
body.stage1.0.1.weight 8 3ea51bab 3e13c35a 3e9c1517 3f9aab87 3e93e84a 3dfe6654 3f1aba3d 3d651c06
body.stage1.0.1.bias 8 3ef6f9bb bef457e0 3f1dce10 bf15ae6d 3f34b549 3ed33451 bf46ef98 bf29b049
···

**Comment by wang-xinyu** [comment]
300是mobilenet版本，报错的是r50，
mobilenet要用`retina_mnet`

make之后看下build目录

**Comment by ZongweiZhou1** [comment]
是我复制错文件了，目前可以执行了。

谢谢：）
