### ISSUE TITLE
how to output feature map

### ISSUE THREAD

**Issue by passion3394** [wang-xinyu/tensorrtx#237]
@wang-xinyu I try to output some layer's feature map, but it failed. Could you give an example ?

the following is my modification:

//yolo->getOutput(0)->setName(OUTPUT_BLOB_NAME);    
//std::cout << "set name out" << std::endl;
//network->markOutput(*yolo->getOutput(0));

deconv128->getOutput(0)->setName(OUTPUT_BLOB_NAME);
std::cout << "set name out" << std::endl;
network->markOutput(*deconv128->getOutput(0));

**Comment by wang-xinyu** [comment]
what's the error? did you adapt the output size?

**Comment by passion3394** [comment]
Yes, I have modified the OUTPUT_SIZE:

static const int OUTPUT_SIZE = 488 * 264 * 128;

and there is no error.

The attachment is my the whole code, please help, thanks.

[yolov4.cpp.log](https://github.com/wang-xinyu/tensorrtx/files/5358472/yolov4.cpp.log)

**Comment by passion3394** [comment]
BTW, should I add your wechat? I have sent a request, but there is no reply.

**Comment by wang-xinyu** [comment]
add again and also add some notes so that I know you are from tensorrtx

**Comment by wittenator** [comment]
Sorry to revive this thread, but what are the necessary modifications in order to get this to work? As far as I saw in the TensorRT docs we need to mark the tensors as output (for example the SSP and Yololayer output) and somehow specify the dimensions of all  output tensors. Does somebody know how this could work?

**Comment by biel-wangdf3** [comment]
how to markOutput many layers feature map at one time? @wittenator @wang-xinyu 
Looking forward to your reply!
