### ISSUE TITLE
sudo ./yolov5 -s 报错

### ISSUE THREAD

**Issue by zwangZJU** [wang-xinyu/tensorrtx#238]
执行sudo ./yolov5 -s时报错

`Loading weights: ../yolov5s.wts
Building engine, please wait for a while...
nvrtc: error: failed to load builtins for compute_75.
terminate called after throwing an instance of 'pwgen::PwgenException'
  what():  NVRTC error: 
Aborted`

**Comment by wang-xinyu** [comment]
可能是环境问题，试试注释掉USE_FP16

**Comment by zwangZJU** [comment]
> 可能是环境问题，试试注释掉USE_FP16

不行，还是一样的问题
![image](https://user-images.githubusercontent.com/39995709/95648296-b6d52d00-0b08-11eb-83e1-35366c11d7f3.png)

**Comment by wang-xinyu** [comment]
显卡、系统版本、还有各种软件库的版本说一下，另外pytorch cuda能否正常运行
