### ISSUE TITLE
The Input W and H are defined in yololayer.h

### ISSUE THREAD

**Issue by jch-wang** [wang-xinyu/tensorrtx#239]
Can I use any nonsquare network resolution like width=416 height=256, as long as it is divisible by 32？I want to resize my 1080P RTSP  video stream with keeping aspect-ratio.

**Comment by wang-xinyu** [comment]
yes, you can pull the newest commit and try

**Comment by jch-wang** [comment]
> yes, you can pull the newest commit and try

I saw yolov4.wts in your code repository. I've never seen information about .wts files before. What does the .wts file mean? What information does it store?

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/getting_started.md#the-wts-content-format

**Comment by jch-wang** [comment]
> https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/getting_started.md#the-wts-content-format

hhhh,感谢提示，我忽略了这些信息。
