### ISSUE TITLE
实测效果较差

### ISSUE THREAD

**Issue by BarryKCL** [wang-xinyu/tensorrtx#240]
![output_zidane](https://user-images.githubusercontent.com/48039828/95722787-f33e8f80-0ca6-11eb-9122-2e86a42ea0df.jpg)
![output_bus](https://user-images.githubusercontent.com/48039828/95722807-fc2f6100-0ca6-11eb-992b-dcbcfa9956d6.jpg)

环境：
CUDA10.2
python3.6
pytorch1.6
tensorrt7.1.3
请问是什么原因造成了这个现象

**Comment by wang-xinyu** [comment]
yolov5?

**Comment by BarryKCL** [comment]
> yolov5?
对，找到问题了。之前转的模型可能是yolov5 v2.0的模型，换成v3.0就好多了。但是v2.0转换也没报错，效果这么差是什么原因？

**Comment by wang-xinyu** [comment]
v2.0 和 v3.0只把leakyrelu 换成了hardswish，其他结构没变

**Comment by BarryKCL** [comment]
> v2.0 和 v3.0只把leakyrelu 换成了hardswish，其他结构没变

明白了，谢谢解答！
