### ISSUE TITLE
框有点偏移是什么问题？What's the problem with the box a little bit off set?

### ISSUE THREAD

**Issue by isyanan1024** [wang-xinyu/tensorrtx#241]
第一张图是python直接加载的模型测试的，第二张是转成FP32的engine的结果测试的
图片输入的尺寸大小都是608，是什么原因导致的呢？求大神告知
The first figure is tested by the model loaded directly by python, and the second is the result test of engine converted to fp32
The size of image input is 608. What is the reason?
![image](https://user-images.githubusercontent.com/48017269/95730509-ed4dac00-0cb0-11eb-8681-1e43a687020d.png)
![image](https://user-images.githubusercontent.com/48017269/95730531-f3dc2380-0cb0-11eb-84f0-1bd3b9ef0c27.png)

**Comment by wang-xinyu** [comment]
哪个模型

**Comment by isyanan1024** [comment]
s，是什么参数需要改嘛?我只修改了类别和输入的大小

**Comment by isyanan1024** [comment]
yolov5s

**Comment by wang-xinyu** [comment]
用的是最新的commit吗

**Comment by isyanan1024** [comment]
是最新的commit，确认过了，目前只有我遇到这个问题嘛。昨晚又重新拉了遍最新的代码还重新训练了下，结果还是一样，是不是只需要修改yololayer.h里面的类别数就可以了

**Comment by wang-xinyu** [comment]
先用官方的模型跑下试试吧，  如果官方模型没问题就好好对一下训练之后的区别

**Comment by isyanan1024** [comment]
![image](https://user-images.githubusercontent.com/48017269/95820640-00b55180-0d5b-11eb-8bc0-b0eaa5e3a314.png)
![image](https://user-images.githubusercontent.com/48017269/95820694-188cd580-0d5b-11eb-8b35-9ba28f6fbce5.png)
这是官方的m版模型跑出来的对比，还是存在这样的问题

**Comment by isyanan1024** [comment]
![_bus](https://user-images.githubusercontent.com/48017269/95820787-5b4ead80-0d5b-11eb-8f8a-9d43ee059943.jpg)
![_zidane](https://user-images.githubusercontent.com/48017269/95820794-5db10780-0d5b-11eb-91b5-02d57334adf6.jpg)
![bus](https://user-images.githubusercontent.com/48017269/95820799-5f7acb00-0d5b-11eb-9863-69b7065bb413.jpg)
![zidane](https://user-images.githubusercontent.com/48017269/95820806-61448e80-0d5b-11eb-954c-f5ac5706bb75.jpg)
官方的m版模型跑出来的对比图

**Comment by isyanan1024** [comment]
用上面的链接下载的模型测下来没有问题，但是有两个问题：
1：拉的yolov5-3-2.0版本代码无法直接加载运行
2：用yolov5-3-2.0训练出来的模型再用tensorrt加速还是出现框偏移的问题，训练时需要注意什么嘛

**Comment by wang-xinyu** [comment]
yolov5-3-2.0是什么意思啊

**Comment by isyanan1024** [comment]
yolov5 3.0 版本

**Comment by wang-xinyu** [comment]
不明白    ，   yolov5 3.0 版本代码跑v3.0 模型，然后用v3.0模型训练，有什么问题？

**Comment by isyanan1024** [comment]
参考一下这个问题https://github.com/ultralytics/yolov5/issues/938
用v3.0的模型跑tensorrtx是没有问题的，但是用v3.0的代码跑v3.0的代码会出错

**Comment by wang-xinyu** [comment]
用他最新的commit的代码，跑v3.0模型，有问题吗？

**Comment by isyanan1024** [comment]
有问题的，很多人反应有问题，报下面这个错误，现在都是用v3.0的版本下载v2.0的模型来用
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'export'

**Comment by wang-xinyu** [comment]
那就等他修复吧，
我这边也可以跑2.0模型，checkout到原来的commit，参考readme https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5
