### ISSUE TITLE
/usr/bin/ld: cannot find -lnvinfer

### ISSUE THREAD

**Issue by CanshangD** [wang-xinyu/tensorrtx#243]
/usr/bin/ld: cannot find -lnvinfer
collect2: error: ld returned 1 exit status
CMakeFiles/myplugins.dir/build.make:359: recipe for target 'libmyplugins.so' failed
make[3]: *** [libmyplugins.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[2]: *** [CMakeFiles/myplugins.dir/all] Error 2
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/yolov5.dir/rule' failed
make[1]: *** [CMakeFiles/yolov5.dir/rule] Error 2
Makefile:131: recipe for target 'yolov5' failed
make: *** [yolov5] Error 2

make编译的时候报错，是不是找不到nvinfer库？ 我用的是tensorrt7.1, cuda11.0

**Comment by wang-xinyu** [comment]
参考tutorial，FAQ第一个问题

**Comment by CanshangD** [comment]
> 参考tutorial，FAQ第一个问题
@wang-xinyu 
搞定了，非常感谢！
