### ISSUE TITLE
INT8 Inference

### ISSUE THREAD

**Issue by azad96** [wang-xinyu/tensorrtx#246]
Hi, how can I use int8 in TensorRT API? I couldn't get how to use IInt8EntropyCalibrator. Does anyone know how to create a calibration table and use it for int8 inference. I'd also like to know if there are other methods for using int8. Thanks in advance.

**Comment by SyedHamza0196** [comment]
I am also trying to do this similar task and stuck with .table file. :(

**Comment by wang-xinyu** [comment]
You guys can refer to the retinaface, yolov3, yolov5 in this repo, for int8 API.
