### ISSUE TITLE
yolov3-spp  windows tensorRT部署问题

### ISSUE THREAD

**Issue by xyt2008** [wang-xinyu/tensorrtx#25]
您好，我使用下面的流程进行：
git clone https://github.com/wang-xinyu/tensorrtx.git
git clone https://github.com/ultralytics/yolov3.git
// download its weights 'yolov3-spp-ultralytics.pt'
cd yolov3
cp ../tensorrtx/yolov3-spp/gen_wts.py .
python gen_wts.py yolov3-spp-ultralytics.pt
// a file 'yolov3-spp_ultralytics68.wts' will be generated.
// the master branch of yolov3 should work, if not, you can checkout 4ac60018f6e6c1e24b496485f126a660d9c793d8

2. put yolov3-spp_ultralytics68.wts into yolov3-spp, build and run
mv yolov3-spp_ultralytics68.wts ../tensorrtx/yolov3-spp/
生成了yolov3-spp_ultralytics68.wts。
然后进行ICudaEngine* engine = builder->buildCudaEngine(*network);
engine->serialize();生成yolov3.engine文件
------------------------------------------------------------------------------------
ICudaEngine* engine = createEngine(1, builder, DataType::kFLOAT);
		assert(engine != nullptr);

		// Serialize the engine
		IHostMemory* modelStream = engine->serialize();

        assert(modelStream != nullptr);
        std::ofstream p("yolov3-spp.engine");
        if (!p) {
            std::cerr << "could not open plan output file" << std::endl;
            return -1;
        }
		printf("modelStream->size():%d\n", modelStream->size());
        p.write(reinterpret_cast<const char*>(modelStream->data()), modelStream->size());
------------------------------------------------------------------------------------------
发现生成的yolov3.engine每次生成的大小不一样。

生成yolov3.engine使用sudo ./yolov3-spp -d  ../samples进行调用的时候，
载入yolov3.engine文件。
std::ifstream file("yolov3-spp.engine", std::ios::binary);
        if (file.good()) {
            file.seekg(0, file.end);
			size = file.tellg();
            file.seekg(0, file.beg);
            trtModelStream = new char[size];
            assert(trtModelStream);
            file.read(trtModelStream, size);
            file.close();
        }
在这里总会报错： ICudaEngine* engine = runtime->deserializeCudaEngine(trtModelStream, size, &pf);如下所示：
ERROR: C:\source\rtSafe\coreReadArchive.cpp (55) - Serialization Error in nvinfer1::rt::CoreReadArchive::verifyHeader: 0 (Length in header does not match remaining archive length)
ERROR: INVALID_STATE: Unknown exception
ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
这个问题在Windows下有。linux下没有出现？请问这个怎么解决？谢谢！

**Comment by wang-xinyu** [comment]
windows下的换行符和linux不一样，应该是这个原因

**Comment by xyt2008** [comment]
确实发现换行符linux下和windows下不一样。我又尝试不保存engine文件，直接序列化后的IHostMemory* modelStream进行反序列化，及后面的推理操作，都能正常进行。那现在的问题是我们要怎么来存储这个engine文件来保证tensorRT的接口ICudaEngine* engine = runtime->deserializeCudaEngine(trtModelStream, size, &pf);能够正常解析出来？

**Comment by BaofengZan** [comment]
@xyt2008         将保存engine那一句`        std::ofstream p("yolov3-spp.engine");` 改成win下的模式`std::ofstream p("yolov4.engine", std::ios::binary);`

**Comment by xyt2008** [comment]
嗯，我已经解决了，也是做了类似的修改。

**Comment by xyt2008** [comment]
嗯，我已经解决了，也是做了类似的修改。

**Comment by wang-xinyu** [comment]
@BaofengZan 感谢回答，这一句会更新到后面提交的代码中。
