### ISSUE TITLE
关于yolov5 V1.0版本模型的转换问题

### ISSUE THREAD

**Issue by BarryKCL** [wang-xinyu/tensorrtx#251]
Loading weights: ../yolov5s.wts
[10/21/2020-20:17:05] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/tensorrtx/yolov5/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::string, float): Assertion `scale_1' failed.
Aborted (core dumped)

**Comment by wang-xinyu** [comment]
按照readme的说明checkout代码了吗？

**Comment by BarryKCL** [comment]
> 按照readme的说明checkout代码了吗？

checkout之后编译失败：
/home/tensorrtxv1/yolov5/yololayer.h(103): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

/home/tensorrtxv1/yolov5/yololayer.h(103): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

Scanning dependencies of target yololayer
[ 50%] Linking CXX shared library libyololayer.so
[ 50%] Built target yololayer
Scanning dependencies of target yolov5s
[ 75%] Building CXX object CMakeFiles/yolov5s.dir/yolov5s.cpp.o
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /usr/local/include/opencv4/opencv2/core/base.hpp:55,
                 from /usr/local/include/opencv4/opencv2/core.hpp:54,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
                 from /home/tensorrtxv1/yolov5/common.hpp:8,
                 from /home/tensorrtxv1/yolov5/yolov5s.cpp:5:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of '_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Tp = Yolo::Detection; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]':
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from '_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]'
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from 'void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Size = long int; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]'
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from 'void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]'
/home/tensorrtxv1/yolov5/common.hpp:106:48:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: invalid initialization of reference of type 'Yolo::Detection&' from expression of type 'const Yolo::Detection'
    while (__comp(*__first, __pivot))
                                   ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/yolov5s.dir/yolov5s.cpp.o] Error 1
make[1]: *** [CMakeFiles/yolov5s.dir/all] Error 2
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
ubuntu16.04不会报这个错误，

把cmp函数的两个参数加上const，参考最新代码

**Comment by BarryKCL** [comment]
> ubuntu16.04不会报这个错误，
> 
> 把cmp函数的两个参数加上const，参考最新代码

成功生成engine之后想测试一下效果，将yolov5_trt.py里面的”libmyplugins.so“替换成”libyololayer.so“之后：
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (323) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "yolov5s_trt.py", line 309, in <module>
    yolov5_wrapper = YoLov5TRT(engine_file_path)
  File "yolov5s_trt.py", line 77, in __init__
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
Aborted (core dumped)

**Comment by BarryKCL** [comment]
把REGISTER_TENSORRT_PLUGIN(YoloPluginCreator);从yolov5.cpp移到yololayer.h之后：
Traceback (most recent call last):
  File "yolov5s_trt.py", line 293, in <module>
    ctypes.CDLL(PLUGIN_LIBRARY)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: build/libyololayer.so: undefined symbol: getPluginRegistry

**Comment by wang-xinyu** [comment]
the plugin .so should link nvinfer

```
cuda_add_library(myplugins SHARED ${PROJECT_SOURCE_DIR}/yololayer.cu)
target_link_libraries(myplugins nvinfer cudart)
```

**Comment by BarryKCL** [comment]
> the plugin .so should link nvinfer
> 
> ```
> cuda_add_library(myplugins SHARED ${PROJECT_SOURCE_DIR}/yololayer.cu)
> target_link_libraries(myplugins nvinfer cudart)
> ```

为什么V3.0不需要做这一步？

**Comment by wang-xinyu** [comment]
3.0也需要，看看代码

**Comment by BarryKCL** [comment]
> 3.0也需要，看看代码

可以了，非常感谢！
