### ISSUE TITLE
yolov5_trt 连续预测多个图片，有时候需要耗时好几秒

### ISSUE THREAD

**Issue by callmeSir007** [wang-xinyu/tensorrtx#253]
修改yolov5_rtr 添加耗时打印，如下：

        # Do image preprocess
        input_image, image_raw, origin_h, origin_w = self.preprocess_image(
            input_image_path
        )

        **t1 = time.time()**

        # Copy input image to host buffer
        np.copyto(host_inputs[0], input_image.ravel())
        # Transfer input data  to the GPU.
        cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream)
        # Run inference.
        context.execute_async(bindings=bindings, stream_handle=stream.handle)
        # Transfer predictions back from the GPU.
        cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
        # Synchronize the stream
        stream.synchronize()
        # Remove any context from the top of the context stack, deactivating it.
        self.cfx.pop()
        # Here we use the first row of output in that batch_size = 1
        output = host_outputs[0]
        # Do postprocess
        result_boxes, result_scores, result_classid = self.post_process2(
            output, origin_h, origin_w
        )

        **t2 = time.time()
        print("time={}".format(t2-t1))**

结果：

root@123:/workspace/tensorrtx-master/yolov5# python yolov5_trt.py
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
time=6.789810657501221
time=0.00727081298828125
time=0.00680994987487793
time=0.005898475646972656
time=0.004625082015991211
time=0.0059888362884521484
time=0.0059278011322021484
time=0.0046863555908203125
time=0.005875825881958008
time=0.005741119384765625
time=0.0048105716705322266
time=0.005872964859008789
time=0.0058405399322509766
time=0.0055637359619140625
time=0.005488395690917969
time=0.005982875823974609
time=0.006000041961669922
time=0.005204200744628906
time=0.005641937255859375
time=0.00699615478515625
time=0.006791114807128906
time=0.006589651107788086
time=0.00583195686340332
time=0.005879402160644531
time=0.005778789520263672
time=0.005712032318115234
time=0.0059778690338134766
time=0.005751371383666992
time=0.006069660186767578
time=0.005719184875488281
time=0.005802154541015625
time=0.0058135986328125
time=0.005844831466674805
time=0.005738973617553711
time=0.006620883941650391
time=0.00552821159362793
time=0.0058286190032958984
time=0.006460666656494141
time=0.005643129348754883
time=0.00600433349609375
time=0.006018400192260742
time=0.004654645919799805

发现检测时间不是很稳定，尤其前面第一张检测耗时好几秒，具体定位 卡在以下位置：
       # to a torch Tensor
        pred = torch.Tensor(pred).cuda()

这个是什么原因呢？

**Comment by wang-xinyu** [comment]
第一张通常会比较慢，有预热加载一些东西

**Comment by LamboAventador** [comment]
@callmeSir007 老哥，能不能说下你用的backbone，测试图片大小以及显卡型号啊,
