### ISSUE TITLE
检测精度问题

### ISSUE THREAD

**Issue by yankunyin** [wang-xinyu/tensorrtx#254]
请问下，我用yolov5s.pth 直接转yolov5s.wts后，直接编译检测，发现检测结果有很多目标框是多余的，和正确的检测结果差很多，这个需要有可能是什么原因呢？

**Comment by wang-xinyu** [comment]
模型可能不对，去yolov5 release tag assets下载模型试试，注意下v3.0和v2.0的区别是leakyrelu和hardswish

**Comment by yankunyin** [comment]
非常感谢，问题已解决
