### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by AkshayGanesh** [wang-xinyu/tensorrtx#255]
I am trying to convert the pre-trained weights to rt weights and I am getting this error while trying to make:

`[ 25%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
In file included from /home/administrator/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/features.h:356:0,
                 from /usr/local/cuda-10.1/include/crt/host_config.h:206,
                 from /usr/local/cuda-10.1/include/cuda_runtime.h:83,
                 from <command-line>:0:
/usr/include/x86_64-linux-gnu/sys/cdefs.h:467:49: error: missing binary operator before token "("
 #if __GNUC_PREREQ (4,8) || __glibc_clang_prereq (3,5)
                                                 ^
compilation terminated due to -Wfatal-errors.
CMake Error at myplugins_generated_yololayer.cu.o.Debug.cmake:219 (message):
  Error generating
  /home/administrator/akshay/tensor_rt_conversion/tensorrtx/yolov5/build/CMakeFiles/myplugins.dir//./myplugins_generated_yololayer.cu.o

CMakeFiles/myplugins.dir/build.make:63: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by wang-xinyu** [comment]
try not to use the conda env while building c++ program. you can refer to the `install` tutorial in this repo.
