### ISSUE TITLE
YOLOv5 version2(leakyReLU) python inference.

### ISSUE THREAD

**Issue by adityap27** [wang-xinyu/tensorrtx#256]
Hi @wang-xinyu ,

there is python inference script available for yolov5 v3 that use **libmyplugins.so**

how to do python inference for **yolov5 v2** model....that commit doesn't include any python infer script.

**Comment by wang-xinyu** [comment]
libyololayer.so in v2 is same as libmyplugins.so

**Comment by adityap27** [comment]
@wang-xinyu Thank you.

One more doubt,
for v3 can I use common libmyplugins.so generated for all yolov5s,m,large....or I have to **use unique .so** file that was built for that model.
I am not familiar with trt plugins...so asking.

**Comment by wang-xinyu** [comment]
The yololayer/plugin is general. The difference lives in the backbone.

**Comment by adityap27** [comment]
Thanks @wang-xinyu got it.

So regardless of the small, medium, large yolo and regardless of different input shapes 480,608,640,etc....I can use same .so file for all.

**Comment by adityap27** [comment]
@wang-xinyu , I need help.
I want to use yolov5s v2.0 for python inference.
So I am using same python script provided in v3 commit of your repo.
I just changed 
PLUGIN_LIBRARY = "libyololayer.so"
ctypes.CDLL(PLUGIN_LIBRARY)

Still it's not working.
![image](https://user-images.githubusercontent.com/30194525/97662967-6107fb00-1a9e-11eb-89ee-2fa88ad2eae0.png)

Do I need to change anything else int python script of v3 to use for v2 model??

**Comment by wang-xinyu** [comment]
Move this line from yolov5.cpp to yololayer.h, refer to the v3 code
```
REGISTER_TENSORRT_PLUGIN(YoloPluginCreator);
```

**Comment by wang-xinyu** [comment]
And add `target_link_libraries` in CMakeLists.txt

```
cuda_add_library(yololayer SHARED ${PROJECT_SOURCE_DIR}/yololayer.cu)
target_link_libraries(yololayer nvinfer cudart)
```

**Comment by adityap27** [comment]
**Thank you very much**. It works now. :)
Closing this issue now, as I have all things running perfectly.
