### ISSUE TITLE
make失败

### ISSUE THREAD

**Issue by liz821** [wang-xinyu/tensorrtx#259]
执行前操作:
把找不到的头文件cp到usr/..终于到最后一步··但是这次失败没有具体报错了··或者是我看不懂
[100%] Built target yolov5
(lizz) [root@host-10-33-7-17 build]# make -l
[ 50%] Built target myplugins
[ 75%] Linking CXX executable yolov5
/usr/bin/ld: warning: libmyelin.so.1, needed by /usr/local/lib/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libbz2.so.1.0, needed by /root/anaconda3/envs/lizz/lib/libavformat.so.58, not found (try using -rpath or -rpath-link)
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphCreateTensor@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphUnload@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetNumberOfInputs@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorGetType@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetRecurrentCountTensor@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorSetDimension@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorGetMemoryOffset@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_stitching.so.3.4.2: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator              <char> >@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_ccalib.so.3.4.2: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetAllocator@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinErrorGetString@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_datasets.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assig              n(char const*)@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_flann.so.3.4.2: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::b              asic_ostringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTargetSetPropertyMemorySize@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinErrorGetCount@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetInputPlace@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_datasets.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_er              ase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphExecute@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorGetMemory@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetInputAllocate@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_bioinspired.so.3.4.2: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char>               >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphLoadPersistent@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_objdetect.so.3.4.2: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetOutput@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetInputAsynchronous@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_imgcodecs.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_r              eplace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_stitching.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_a              ssign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libavformat.so.58: undefined reference to `BZ2_bzDecompress'
/root/anaconda3/envs/lizz/lib/libopencv_objdetect.so.3.4.2: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete              <std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinBinaryGraphCreate@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphDeserializeBinary@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_objdetect.so.3.4.2: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/root/anaconda3/envs/lizz/lib/libopencv_face.so.3.4.2: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<              char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBC              XX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorSetType@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphDestroy@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetOutputSyncObject@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetOutputAllocate@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_dnn.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(cha              r const*)@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_stitching.so.3.4.2: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >              ::~basic_stringstream()@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTargetInstanceGetPropertyMemorySize@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_dpm.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(ch              ar const*) const@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_surface_matching.so.3.4.2: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std              ::allocator<char> >@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphCreateOp@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_saliency.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_ap              pend(char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetInput@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_ccalib.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(c              har, unsigned long) const@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSerializeBinary@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphCompile@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetInput@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetOutputAsynchronous@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_aruco.so.3.4.2: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorGetStride@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetCopyKind@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetInput@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_face.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(u              nsigned long, unsigned long, char const*) const@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetInputScan@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_face.so.3.4.2: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<cha              r> >@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_imgcodecs.so.3.4.2: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetInputAllocate@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetOutputScan@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_core.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(u              nsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphLoad@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetInputAsynchronous@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_stitching.so.3.4.2: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::alloca              tor<char> >@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorSetValues@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_imgcodecs.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resi              ze(unsigned long, char)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetGraph@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphCreate@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetBuiltin@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_surface_matching.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>               >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetRecurrent@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_dnn.so.3.4.2: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basi              c_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetNumberOfOutputs@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_face.so.3.4.2: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~b              asic_istringstream()@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTargetSetPropertySm@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_core.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate              (unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetOutputAsynchronous@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphCreateTensorName@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinErrorGet@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetNumberOfOutputs@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetOutputAllocate@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_surface_matching.so.3.4.2: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::a              llocator<char> >@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_datasets.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::opera              tor=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetOutput@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorGetDimensionCount@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetOutput@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_ccalib.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_repl              ace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_dnn.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(st              d::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetNumberOfInputs@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_face.so.3.4.2: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<              char> >@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetPointWiseKind@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetNumberOfInputs@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_stitching.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_c              reate(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorSetStride@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorSetMemory@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetKind@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinOpSetNumberOfOutputs@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_face.so.3.4.2: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_syn              c(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libavformat.so.58: undefined reference to `BZ2_bzDecompressInit'
/root/anaconda3/envs/lizz/lib/libopencv_surface_matching.so.3.4.2: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator              <char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorGetDimension@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorGetAlignment@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_imgcodecs.so.3.4.2: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find              (char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetInputPlace@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphUnloadPersistent@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphSetRecurrentControlTensor@libmyelin.so.1'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinGraphGetInputSyncObject@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libavformat.so.58: undefined reference to `BZ2_bzDecompressEnd'
/root/anaconda3/envs/lizz/lib/libopencv_dnn.so.3.4.2: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/root/anaconda3/envs/lizz/lib/libopencv_face.so.3.4.2: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<cha              r>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GL              IBCXX_3.4.21'
/root/anaconda3/envs/lizz/lib/libopencv_stitching.so.3.4.2: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator              <char> >@GLIBCXX_3.4.21'
/usr/local/lib/libnvinfer.so: undefined reference to `myelinTensorSetDimensionCount@libmyelin.so.1'
/root/anaconda3/envs/lizz/lib/libopencv_bioinspired.so.3.4.2: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >:              :str() const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [yolov5] Error 1
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
link路径有问题，好多so没link到，根据自己情况修改cmake，添加link和include路径
或者按照repo的install教程安装

**Comment by liz821** [comment]
> link路径有问题，好多so没link到，根据自己情况修改cmake，添加link和include路径
> 或者按照repo的install教程安装

修改cmake是yolov5下的那个吧？
添加link和include路径 能举个例子吗？抱歉我完全没有这方面经验
我重新用解压的方式安装了opencv  现在make 的报错是这样的,我是前进了吗··还是后退了？
该怎么做？实在没有办法了 都快浏览器搜索坏了

[100%] Linking CXX executable yolov5
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `preprocess_img(cv::Mat&)':
/usr/local/include/opencv2/core/mat.inl.hpp:866: undefined reference to `cv::Mat::create(int, int const*, int)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `preprocess_img(cv::Mat&)':
/data/lwx901434/tensorrtx/yolov5/common.hpp:42: undefined reference to `cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `preprocess_img(cv::Mat&)':
/usr/local/include/opencv2/core/mat.inl.hpp:866: undefined reference to `cv::Mat::create(int, int const*, int)'
/usr/local/include/opencv2/core/mat.inl.hpp:500: undefined reference to `cv::Mat::operator=(cv::Scalar_<double> const&)'
/usr/local/include/opencv2/core/mat.inl.hpp:912: undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `preprocess_img(cv::Mat&)':
/data/lwx901434/tensorrtx/yolov5/common.hpp:44: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `preprocess_img(cv::Mat&)':
/usr/local/include/opencv2/core/mat.inl.hpp:774: undefined reference to `cv::fastFree(void*)'
/usr/local/include/opencv2/core/mat.inl.hpp:774: undefined reference to `cv::fastFree(void*)'
/usr/local/include/opencv2/core/mat.inl.hpp:886: undefined reference to `cv::Mat::deallocate()'
/usr/local/include/opencv2/core/mat.inl.hpp:886: undefined reference to `cv::Mat::deallocate()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `cvflann::anyimpl::big_any_policy<cv::String>::static_delete(void**)':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `cvflann::anyimpl::big_any_policy<cv::String>::move(void* const*, void**)':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
/usr/local/include/opencv2/core/cvstd.hpp:656: undefined reference to `cv::String::deallocate()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `cv::Mat::~Mat()':
/usr/local/include/opencv2/core/mat.inl.hpp:886: undefined reference to `cv::Mat::deallocate()'
/usr/local/include/opencv2/core/mat.inl.hpp:774: undefined reference to `cv::fastFree(void*)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/data/lwx901434/tensorrtx/yolov5/yolov5.cpp:489: undefined reference to `cv::imread(cv::String const&, int)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/data/lwx901434/tensorrtx/yolov5/yolov5.cpp:518: undefined reference to `cv::imread(cv::String const&, int)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/data/lwx901434/tensorrtx/yolov5/yolov5.cpp:522: undefined reference to `cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/data/lwx901434/tensorrtx/yolov5/yolov5.cpp:521: undefined reference to `cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/data/lwx901434/tensorrtx/yolov5/yolov5.cpp:524: undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to `cv::String::allocate(unsigned long)'
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to `cv::String::allocate(unsigned long)'
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `main':
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
/usr/local/include/opencv2/core/cvstd.hpp:648: undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
make[2]: *** [yolov5] Error 1
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
先学一下cmake的知识吧。。。
