### ISSUE TITLE
我使用yolov5，效果奇差。

### ISSUE THREAD

**Issue by prio158** [wang-xinyu/tensorrtx#261]
我用yolov5源码的yolov5s.pt文件，生成yolov5.wts, 然后再借用楼主的代码，生成yolov5.engine, 经过测试效果奇差，想问下啥原因。
![image](https://user-images.githubusercontent.com/72843017/97568229-e600ff00-1a21-11eb-94e9-5d5c6f176454.png)

**Comment by wang-xinyu** [comment]
https://github.com/ultralytics/yolov5/releases/tag/v3.0
从这里最下面assets下载模型试试

**Comment by CaptainJohansson** [comment]
> https://github.com/ultralytics/yolov5/releases/tag/v3.0
> 从这里最下面assets下载模型试试

您好，想问下您这yolov5好像没有实现hardmish激活函数的插件，然后yolov5@v3.0里面的激活函数使用的是hardmish对结果不会有影响吗？请问为什么我是用https://github.com/ultralytics/yolov5/releases/tag/v2.0这个路径下的权重生成的engine检测结果中包含大量的框？

**Comment by wang-xinyu** [comment]
hard_swish = x * hard_sigmoid

@CaptainJohansson 

这里用的hard sigmoid


如果用v2.0，需要checkout到v2.0的commit，看下tensorrtx/yolov5的readme

**Comment by CaptainJohansson** [comment]
好的谢谢，v3确实能用
