### ISSUE TITLE
Increase in Input size, Decreases .engine Size (Weird) (Yolov5_v3 & _v2)

### ISSUE THREAD

**Issue by adityap27** [wang-xinyu/tensorrtx#262]
Hi @wang-xinyu ,
There is some weird results while converting yolov5_v3 medium and large. No issues with small variant.

The size of engine file decreases when I change the inputshape from 480 to 640.
See the image for better idea.
![image](https://user-images.githubusercontent.com/30194525/97772001-8103f100-1b68-11eb-9bcc-4be546dabfad.png)

Is this normal or weird ? (seems weird to me.)
Also tell me if I am doing some wrong conversion. (you can check on your system)
I changed the yololayer.h file for change in input-shape.

**Comment by wang-xinyu** [comment]
You can try run with sudo.

**Comment by adityap27** [comment]
@wang-xinyu , I am already running it with sudo.
Can you confirm this weird/observation issue on your side/system ?
