### ISSUE TITLE
yolov5的推理速度

### ISSUE THREAD

**Issue by prio158** [wang-xinyu/tensorrtx#263]
你好请问一下，在yolov5中，这一段代码是做什么用的，看不太懂。在运行过程中，花在这里的时间比inference还要多。
		for (int row = 0; row < INPUT_H; ++row) {
                uchar* uc_pixel = pr_img.data + row * pr_img.step;
                for (int col = 0; col < INPUT_W; ++col) {
                    data[b * 3 * INPUT_H * INPUT_W + i] = (float)uc_pixel[2] / 255.0;
                    data[b * 3 * INPUT_H * INPUT_W + i + INPUT_H * INPUT_W] = (float)uc_pixel[1] / 255.0;
                    data[b * 3 * INPUT_H * INPUT_W + i + 2 * INPUT_H * INPUT_W] = (float)uc_pixel[0] / 255.0;
                    uc_pixel += 3;
                    ++i;
                }
            }

**Comment by wang-xinyu** [comment]
HWC to CHW and normalize.
