### ISSUE TITLE
Error when make yolov5

### ISSUE THREAD

**Issue by hoangnt2601** [wang-xinyu/tensorrtx#269]
/usr/bin/ld: warning: libcublas.so.10, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSetMathMode@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasGetMathMode@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasGetVersion_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasGemmEx@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSetStream_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasHgemmStridedBatched@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSgemm_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasCreate_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasDestroy_v2@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSgemmEx@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasHgemm@libcublas.so.10'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `cublasSgemmStridedBatched@libcublas.so.10'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5.dir/build.make:137: recipe for target 'yolov5' failed
make[2]: *** [yolov5] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
cuda not installed properly or not in the the right path, 
check the cuda path in cmakelists.txt.

and also refer to the install tutorial in this repo.
