### ISSUE TITLE
YoloV4 not working for different dimensions

### ISSUE THREAD

**Issue by lavinan26** [wang-xinyu/tensorrtx#27]
Hi,
In order to run yolov4 using tensorrt on C++ with a different dimension (I tried both 512 and 416) than the default value 608 I made the following changes.

- In gen_wts.py line 6, changed img_size parameter passed to initialize Darknet object from 608 to 416
- In yololayer.h as mentioned in README.md, INPUT_H and INPUT_W values are changed from 608 to 416
While testing it on the given test images I just got lot of random bounding boxes. I have attached the resulting image for bus.jpg.
Is there anything else I need to change?
![_1bus](https://user-images.githubusercontent.com/48351698/82759740-d47d5080-9e0c-11ea-9b6e-37dba5b68eb8.jpg)

**Comment by wang-xinyu** [comment]
did you regenerate the engine?

**Comment by lavinan26** [comment]
> did you regenerate the engine?

Yes, after making those above mentioned changes in the code, I ran all the steps from beginning.

**Comment by wang-xinyu** [comment]
I just tried 416x416,

it works fine.

1. modify INPUT_W and INPUT_H in yololayer.h
2. clean build dir, and run `cmake ..`,   `make`
3. `./yolov4 -s`
4. `./yolov4 -d IMAGES_DIR`

**Comment by lavinan26** [comment]
> I just tried 416x416,
> 
> it works fine.
> 
> 1. modify INPUT_W and INPUT_H in yololayer.h
> 2. clean build dir, and run `cmake ..`,   `make`
> 3. `./yolov4 -s`
> 4. `./yolov4 -d IMAGES_DIR`

Thanks alot! Now it works fine. The issue was that I didn't clean and redo a `cmake`, instead I was only running a `make` after the changes. Thanks again.
