### ISSUE TITLE
yolov5速度其慢

### ISSUE THREAD

**Issue by ruiming46zrm** [wang-xinyu/tensorrtx#270]
一切安装正常， yolov5推理视频速度及其慢，1frame要300毫秒去了， 请问可能是哪里的原因。

**Comment by wang-xinyu** [comment]
试试我的图片推理速度是否正常

**Comment by ruiming46zrm** [comment]
ok了，ok了，  不过yolov5s模型在gpu上推理时间是8毫秒多，还赶不上作者的python版本0.0

**Comment by wang-xinyu** [comment]
1. 输入大小不一样，pytorch输入是等比例缩放，trt这边是固定的，可以让两边一致试试；
2. cpu-gpu之间的memcpy的操作，两边的逻辑不一样；
3. 大模型的加速效果会更明显。

**Comment by lusi1990** [comment]
> ok了，ok了， 不过yolov5s模型在gpu上推理时间是8毫秒多，还赶不上作者的python版本0.0

我的测试也是这样,环境如下:

* CUDA: 10.2
* CUDNN: 8.0.5
* tensorRT: 7.2.2.3
* GPU: RTX 1080TI

图片大小都缩放成了640*640
模型用的是 `yolov5s.pt`
yolov5 的 detect.py 平均时间是 0.0057s
yolov5_trt.py 的平均时间是  0.0083s

**Comment by simplew2011** [comment]
> ok了，ok了， 不过yolov5s模型在gpu上推理时间是8毫秒多，还赶不上作者的python版本0.0

啥原因导致的，我的python_trt推理也很慢，30ms，但make C++推理正常
2080，cuda10.0，cudnn7.6

(tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5/build$ sudo ./yolov5 -d  ../samples
[03/08/2021-16:39:48] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
5ms
4ms
3ms
3ms

(tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5$ python yolov5_trt.py 
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
===> 2.0595476627349854
===> 0.03826165199279785
===> 0.030884742736816406
===> 0.03745245933532715
===> 0.03125166893005371
===> 0.033860206604003906
===> 0.031084060668945312
===> 0.03644537925720215

python版的时间记录添加在：
def infer(self, input_image_path):
        threading.Thread.__init__(self)
        # Make self the active context, pushing it on top of the context stack.
        self.cfx.push()
        # Restore
        stream = self.stream
        context = self.context
        engine = self.engine
        host_inputs = self.host_inputs
        cuda_inputs = self.cuda_inputs
        host_outputs = self.host_outputs
        cuda_outputs = self.cuda_outputs
        bindings = self.bindings
        #######################################
        t0 = time.time() 
        # Do image preprocess
        input_image, image_raw, origin_h, origin_w = self.preprocess_image(
            input_image_path
        )
        # Copy input image to host buffer
        np.copyto(host_inputs[0], input_image.ravel())
        # Transfer input data  to the GPU.
        cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream)
        # Run inference.
        context.execute_async(bindings=bindings, stream_handle=stream.handle)
        # Transfer predictions back from the GPU.
        cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
        # Synchronize the stream
        stream.synchronize()
        # Remove any context from the top of the context stack, deactivating it.
        self.cfx.pop()
        # Here we use the first row of output in that batch_size = 1
        output = host_outputs[0]
        # Do postprocess
        result_boxes, result_scores, result_classid = self.post_process(
            output, origin_h, origin_w
        )

        #######################################
        print("===>", time.time() - t0)

**Comment by wang-xinyu** [comment]
c++不包括pre和post process时间

**Comment by pengfeidip** [comment]
> ok了，ok了， 不过yolov5s模型在gpu上推理时间是8毫秒多，还赶不上作者的python版本0.0

你后续有解决这个问题吗？
