### ISSUE TITLE
NvInfer.h  and /usr/bin/ld: cannot found -lnvinfer

### ISSUE THREAD

**Issue by yang-gis** [wang-xinyu/tensorrtx#271]
thanks for Mr wang's work.I a new in this field and c++.
Due to use tar file to install TensorRT, it is neccessary to change the cmakelists file of lenet sample.
Here is some change :

include_directories(/home/yjy/TensorRT-7.0.0.11/include) #for NvInfer.h
link_directories(/home/yjy/TensorRT-7.0.0.11/lib/) #for cannot found -lnvinfer

you should use your actual TensorRT path to replace above path.

**Comment by yang-gis** [comment]
> thanks for Mr wang's work.I a new in this field and c++.
> Due to use tar file to install TensorRT, it is neccessary to change the cmakelists file of lenet sample.
> Here is some change :
> 
> include_directories(/home/yjy/TensorRT-7.0.0.11/include) #for NvInfer.h
> link_directories(/home/yjy/TensorRT-7.0.0.11/lib/) #for cannot found -lnvinfer
> 
> you should use your actual TensorRT path to replace above path.

**Comment by viwe-monai** [comment]
如果在build路径下cmake ..，然后make -j16，发现编译报错，缺少了什么文件，可以在build的上一级目录的CMakeLists.txt中，修改cuda、tensorRT、Opencv的路径，然后删除build文件夹生成的文件，重新cmake ..，然后make -j16
![image](https://github.com/user-attachments/assets/ce5f8120-581b-4bda-aac5-86ace0142ca1)
