### ISSUE TITLE
NvInfer.h and /usr/bin/ld: cannot found -lnvinfer

### ISSUE THREAD

**Issue by yang-gis** [wang-xinyu/tensorrtx#272]
thanks for Mr wang's work.I a new in this field and c++.
Due to use tar file to install TensorRT, it is neccessary to change the cmakelists file of lenet sample.
Here is some change :

include_directories(/home/yjy/TensorRT-7.0.0.11/include) #for NvInfer.h
link_directories(/home/yjy/TensorRT-7.0.0.11/lib/) #for cannot found -lnvinfer

you should use your actual TensorRT path to replace above path.
Hope to be able to offer some help to later person!

**Comment by wang-xinyu** [comment]
thanks for feedback, this issue already mentioned in the FAQ tutorial.
