### ISSUE TITLE
pytorch模型与tensorrt结果不一致

### ISSUE THREAD

**Issue by JimmyLauren** [wang-xinyu/tensorrtx#273]
你好，我用pytorch训练了一个resnet18分类模型，转成TRT模型之后，在pytorch和在TRT中的测试结果不一样，请问一下大概是什么原因呢？我查看了一下代码，在pytorch里面是用PIL库加载的图片，在TRT中用的Opencv加载的图片，这可能是两者测试结果不一样的原因吗？

**Comment by wang-xinyu** [comment]
PIL读取的是RGB格式，opencv是BGR

**Comment by JimmyLauren** [comment]
你好，感谢回复，我在resnet18.cpp里面将BGR改成了RGB格式的，TRT的结果和pytorch的结果还是不一样，请问一下是什么原因呀？两种格式都试了，貌似对最终的识别结果没有影响

**Comment by wang-xinyu** [comment]
还有预处理归一化操作，mean和std处理，对一下pytorch模型的输入值，和trt的输入值

**Comment by JimmyLauren** [comment]
我试了一下，发现从transforms.resize和cv::resize出来的结果不一致，请问一下这个是什么原因呢？

**Comment by we0091234** [comment]
> 我试了一下，发现从transforms.resize和cv::resize出来的结果不一致，请问一下这个是什么原因呢？

你训练的时候用opencv 训练不就行了

**Comment by JimmyLauren** [comment]
@we0091234 已经改成OpenCV训练了，谢谢。

**Comment by swithmn1** [comment]
> @we0091234 已经改成OpenCV训练了，谢谢。

hello,用opencv训练后，结果预测是对的么？
