### ISSUE TITLE
about dynamic batchsize

### ISSUE THREAD

**Issue by xavier-xiadia** [wang-xinyu/tensorrtx#274]
你好，感谢你的工作
    // Set formats and data types of inputs
    auto input = network->getInput(0);
    _**//若要设置成支持动态尺寸，需要在pytorch导模型时进行设置。**_
    profile->setDimensions(input->getName(), OptProfileSelector::kMIN, Dims4(1,3,608,608));
    profile->setDimensions(input->getName(), OptProfileSelector::kOPT, Dims4(16,3,608,608));
    profile->setDimensions(input->getName(), OptProfileSelector::kMAX, Dims4(32,3,608,608));
我在yolov5.cpp里这句话不知道如何理解，动态尺寸应该是包括动态batchsize是吗，pytorch模型导出，是指用你的gen_wts,py这个文件生成么，还是训练时torch.save出来的模型？因为之前用pt转onnx转trt时，了解这种方法如何设置dynamic input，但是您的这个步骤如何设置呢，还是不必设置？

**Comment by wang-xinyu** [comment]
动态尺寸和动态batchsize是两件事。
动态尺寸通常说的是H和W动态。
动态尺寸和动态batchsize都是在tensorrt一侧实现的，和pytorch模型导出没关系，gen_wts.py导出的是weights，weights和input shape无关。
