### ISSUE TITLE
Why do you use big-endian here? 

### ISSUE THREAD

**Issue by VCBE123** [wang-xinyu/tensorrtx#277]
https://github.com/wang-xinyu/tensorrtx/blob/983fba2763a764e117f75a882077875735395d57/yolov5/gen_wts.py#L16-L18

**Comment by wang-xinyu** [comment]
struct.pack().hex()  is to convert a float into a hex string, not a value.

For this hex string, the byte with the lowest address is in the front of the string.

For example, vv = 0.34, i.e. 0x3EAE147A,

```
little-endian:
    0x0029f458　　0x7A
    0x0029f459　　0x14
    0x0029f45a　　0xAE
    0x0029f45b　　0x3E
struct.pack('<f',float(vv)).hex() is '7A14AE3E'

big-endian:
    0x0029f458　　0x3E
    0x0029f459　　0xAE
    0x0029f45a　　0x14
    0x0029f45b　　0x7A
struct.pack('>f',float(vv)).hex() is '3EAE147A'

```
