### ISSUE TITLE
Question about trained model conversion

### ISSUE THREAD

**Issue by berkantay** [wang-xinyu/tensorrtx#279]
Hello @wang-xinyu I trained yolov5s with my custom dataset and I have the ```.pt``` file for my dataset. Now I want to see the inference speed difference between with **tensorrt and without tensorrt**. How can I use tensorrt with my trained weights?

I have read your tutorial https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5 but there is a sentence like ```ensure the file name is yolov5s.pt and yolov5s.wts in gen_wts.py```. Can I just change the name with my ```.pt``` file? and utilize it?

**Comment by wang-xinyu** [comment]
yes, you can adapt the file name in gen_wts.py.
