### ISSUE TITLE
parallel inferncing for multiple channels

### ISSUE THREAD

**Issue by sudapure** [wang-xinyu/tensorrtx#28]
I modified yolov3-spp code to read from video streams and infer it, now am trying to parallelize the code, mainly i am trying to share IRuntime, ICudaEngine and IExecutionContext to each spawned thread , am using p_thread to launch new thread and use IExecutionContext for doInference() routine, when i tried it on my 2 GB 1050 GTX card, i got cuda out of memory issue, this is possibly because  IExecutionContext refers to same network builder object which points to serialized network, which takes almost 1.4 GB on GPU memory, but when i tried inferring same on Tesla K80 11 GB, i successfully lunched two threads calling doInference routine on shared ICudaEngine object, but the latency got doubled, for one thread it's about 30 ms but when launched 2 threads it's get doubled around 60 ms, so how can I optimise the code in order to leverage multi-threading for inferring multiple video streams in parallel with almost same latency. Thanks.

**Comment by wang-xinyu** [comment]
@sudapure I understand your requirement.

I think the latency depends on the GPU computation unit, and GPU frequency,  not GPU memory.

So if multi-threads using the same GPU, it would slow down. That's my opinion.

**Comment by philipp-schmidt** [comment]
hey @sudapure 

Try Triton Inference Server. It runs your model distributed and allows you to make concurrent request. It then automatically schedules overlapping GPU calls (even with multiple GPUs).

I have a full example here: https://github.com/isarsoft/yolov4-triton-tensorrt
