### ISSUE TITLE
Could not detect any of the custom dataset objects

### ISSUE THREAD

**Issue by Srija5441** [wang-xinyu/tensorrtx#281]
Thank you so much for the repo , I have a custom dataset and yolov3-tiny.pt weights. The weights have been converted to yolov3-tiny.wts successfully with my customized  yolov3-tiny.cfg file using gen_wts.py

But After completing the conversion process, and changing the network as required,I could not get any detection and bounding box list is empty. Can you guide what I am doing wrong in conversion? I am not getting any errors during the conversion.

**Comment by wang-xinyu** [comment]
you might need to check the anchors defined in yololayer.h

**Comment by Srija5441** [comment]
Thanks for the reply. I have already customised the anchors in yololayer.h according to my cfg file. Can you please suggest me where might I have to debug?

**Comment by wang-xinyu** [comment]
try the official model first, and see if that works well.

then compare your own model with the official one.

**Comment by Srija5441** [comment]
I have tried the coco model, it is perfectly running and giving detections. The problem arises with the customized weights

**Comment by wang-xinyu** [comment]
then you may need to compare your model with the coco model very carefully. to see what's the difference.

**Comment by Srija5441** [comment]
Yes, Thanks for suggesting. On comparing I had to change add one more yolo layer, few convolutional layers, and had to change the anchor box sizes. Can you please elaborate on what is being stored in **prob** variable after **doInference** function?

**Comment by wang-xinyu** [comment]
prob is like:
```
    num_of_detections det1 det2 ... detN
```

The first number means how many detections in `prob`, and following each detection is a struct, which defined in yololayer.h, including bbox, conf, etc.

**Comment by Srija5441** [comment]
Thanks, understood the structure.I get the outputs for yolo layer if given the output of single convolutional layer but if two or more are given, I get an array of zeros.for example if given like the one below I dont get any outputs.
 ITensor* inputTensors_yolo[] = {conv15->getOutput(0),conv22->getOutput(0)};
Can you please guide me on how to debug this?

**Comment by Srija5441** [comment]
Can you please list out the steps that I need to follow to add an extra yolo layer
