### ISSUE TITLE
Comparison of network definition with explicit and implicit batch dimension

### ISSUE THREAD

**Issue by Mirostocles** [wang-xinyu/tensorrtx#282]
Hi thanks for your great work.
I noticed that when you create the definition of networks, you're using createNetworkV2(0U), which means having implicit batch dimension. And you define your maximum batch size using setMaxBatchSize(). 
As far as I learned from the official tensorRT document. Creating network definition with explicit batch dimension in order to use dynamic shape and OptimizationProfile might be a better practice for batch inference.
May I ask you that, have you tried with the latter method and why you choose the former one?
Thank you.

**Comment by wang-xinyu** [comment]
For dynamic input shape, we must set explicit batch dimension, otherwise it will report error while building the model.

For fixed input shape, implicit batch dim works well.

And in my experience, for performance, there is no big difference between implicit and explicit batch.

**Comment by Mirostocles** [comment]
Thanks for your quick response, it helps a lot!
