### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by zpge** [wang-xinyu/tensorrtx#286]
I followed the install.md, but got the following error 
root@6c4f3b2e25d1:/data/zpge/TensorRT/tensorrtx/yolov4/build# cmake ..
embed_platform off
CMake Error at /usr/share/OpenCV/OpenCVModules.cmake:189 (message):
  The imported target "opencv_shape" references the file

     "/usr/lib/x86_64-linux-gnu/libopencv_shape.so.3.3.1"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/share/OpenCV/OpenCVModules.cmake"

  but not all the files it references.
Does anyone have any suggestions?

**Comment by wang-xinyu** [comment]
you could try 

```
sudo apt install libopencv-shape-dev

or 

sudo apt install libopencv-*-dev
``

**Comment by zpge** [comment]
Thanks for your reply. During apt install libopencv-*-dev, it cames with
The following packages have unmet dependencies:
 libopencv-contrib-dev : Depends: libopencv-calib3d-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                         Depends: libopencv-highgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                         Depends: libopencv-ml-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                         Depends: libopencv-video-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                         Depends: libopencv-objdetect-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
 libopencv-gpu-dev : Depends: libopencv-core-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
 libopencv-legacy-dev : Depends: libopencv-video-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                        Depends: libopencv-calib3d-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                        Depends: libopencv-ml-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                        Depends: libopencv-highgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
 libopencv-ocl-dev : Depends: libopencv-calib3d-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                     Depends: libopencv-ml-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                     Depends: libopencv-objdetect-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                     Depends: libopencv-highgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
                     Depends: libopencv-video-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed

What does this mean?
