### ISSUE TITLE
gen_wts.py Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lthbk5919** [wang-xinyu/tensorrtx#289]
I get `Segmentation fault (core dumped)` when run `gen_wts.py`
I use torch 1.7.0 with yolov5 3.1

**Comment by wang-xinyu** [comment]
please paste the complete error messages.

**Comment by lthbk5919** [comment]
Show only `Segmentation fault (core dumped)`
But it's done when used torch 1.6.0 yolov5 3.1
I think there is something wrong with torch 1.7.0?

**Comment by quangsonle** [comment]
I have the same issue with python 3.6 and torch 1.10, the complete error is simple, Segmentation fault (core dumped).

any idea to solve it?
