### ISSUE TITLE
yolov4和retinaface引擎的性能问题

### ISSUE THREAD

**Issue by wulixunhua** [wang-xinyu/tensorrtx#29]
@wang-xinyu 你好，我有两个问题请教。
1，我在jetson agx上测试。yolov4生成引擎，大概性能是20fps，我使用另外一个作者是.weights->onnx->engine，他的引擎性能大概是33fps，输入图片尺寸都是416*416，fp16的引擎。请问这是什么原因？
2，另外，retinaface生成的引擎我测试单张图片是230ms，但是直接使用Pytorch测试.pth模型，单张图片是40ms左右。不知道是哪里出了问题？

**Comment by wang-xinyu** [comment]
yolov4 33fps，有链接吗？

**Comment by wulixunhua** [comment]
@wang-xinyu  https://github.com/CaoWGG/TensorRT-YOLOv4 ，我测试他的每张图片推理速度是30ms。

retinaface pytorch我把尺寸固定到928*1600还是35-40ms一张，你测试的retinaface的engine是多少fps？

**Comment by wang-xinyu** [comment]
我看下他的代码

**Comment by wulixunhua** [comment]
retinaface是我弄错了，重新测试了一下384*640是25fps。你看下yolov4那个性能差异是什么原因

**Comment by wang-xinyu** [comment]
@wulixunhua 他的mish用的fp16实现，我这边没用，所以fp16时，我这边mish也是fp32计算的。 如果都用fp32，速度差多少？

**Comment by wulixunhua** [comment]
重新捋了一毛，你们两个的engine性能是接近的
