### ISSUE TITLE
yolov5 backbone 更改为mobilenetv2, 检测无结果

### ISSUE THREAD

**Issue by kunyao2015** [wang-xinyu/tensorrtx#293]
如题，backbone改成mobilenetv2后，在pytorch下测试是正常的， 改成tensorrt推理，doInference输出为空，没有任何检测结果， 编译执行过程没有任何报错，想请教下，这种情况如何排查问题呢

**Comment by wang-xinyu** [comment]
两边都输入ones tensor，从前往后对比输出数值
tensorrt可以把中间层markOutput

**Comment by kunyao2015** [comment]
感谢，非常棒的项目！
