### ISSUE TITLE
cmake.. 錯誤

### ISSUE THREAD

**Issue by chrisgame1002** [wang-xinyu/tensorrtx#294]
ai@server:~/yolo-v5/tensorrtx/yolov5/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr (found version "9.1") 
-- Found OpenCV: /usr (found version "3.2.0") 
-- Configuring done
CMake Warning at /snap/cmake/619/share/cmake-3.18/Modules/FindCUDA.cmake:1840 (add_library):
  Cannot generate a safe linker search path for target myplugins because
  files in some directories may conflict with libraries in implicit
  directories:

    link library [libcudart.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda-10.0/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:26 (cuda_add_library)

CMake Warning at CMakeLists.txt:32 (add_executable):
  Cannot generate a safe linker search path for target yolov5 because files
  in some directories may conflict with libraries in implicit directories:

    link library [libcudart.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda-10.0/lib64

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/ai/yolo-v5/tensorrtx/yolov5/build

**Comment by wang-xinyu** [comment]
your cuda maybe not installed properly. the same .so both in /usr/lib/x86_64-linux-gnu and /usr/local/cuda-10.0/lib64

please refer to the install tutorial or try the dockerfile.
