### ISSUE TITLE
结果不一致

### ISSUE THREAD

**Issue by 994374821** [wang-xinyu/tensorrtx#296]
tensorrt版本的yolov5s与python版的输出不一致？

**Comment by wang-xinyu** [comment]
试试从yolov5 release tag下载模型
或者试试用项目中modelzoo的wts

**Comment by 994374821** [comment]
请问网络结构一致吗

**Comment by stbidtf** [comment]
我的也是循环推理同样的图像，有些图片完全一样，有些就是每次推理的结果都不一样。顺序不一样，内容有些不一样，有些一样。怎么定位问题？
