### ISSUE TITLE
你好啊，大神，我用YOLOv5m训练自己的模型，tensorRT测出来有问题。

### ISSUE THREAD

**Issue by AIpakchoi** [wang-xinyu/tensorrtx#298]
具体情况是：我把每个YOLO层的anchor换成了4个，三个YOLO层共12个anchor，然后TensorRT测的时候，每个目标上有多个框，但是明显不对。是不是代码哪里写死了，必须是官方yolov5 9anchor(每层3个anchor)才能用该代码tensorRT部署。
我用你上一版的YOLOv5(v3,0)测试，就没有上述问题。

**Comment by AIpakchoi** [comment]
嘿嘿，大神，找到问题的原因了。common.hpp里的addYoLoLayer把YOLO层写死了，写的是官方YOLO层的结构。

**Comment by Linaom1214** [comment]
> 嘿嘿，大神，找到问题的原因了。common.hpp里的addYoLoLayer把YOLO层写死了，写的是官方YOLO层的结构。

您好，是要把cpp文件里的层写成自己修改的吗？

**Comment by Gaoxj2020** [comment]
> 具体情况是：我把每个YOLO层的anchor换成了4个，三个YOLO层共12个anchor，然后TensorRT测的时候，每个目标上有多个框，但是明显不对。是不是代码哪里写死了，必须是官方yolov5 9anchor(每层3个anchor)才能用该代码tensorRT部署。
> 我用你上一版的YOLOv5(v3,0)测试，就没有上述问题。

请问加速效果怎么样
