### ISSUE TITLE
Compile and run on Windows fails due to missing hardswish.cu and hardswish.h

### ISSUE THREAD

**Issue by Transigent** [wang-xinyu/tensorrtx#299]
Hi I am attempting to follow the instructions for compiling and running on Windows, here: 
[https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md](https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md)

I get to the Generate stage for yolov5 and it fails here:

`add_executable(yolov5 ${PROJECT_SOURCE_DIR}/yolov5.cpp ${PROJECT_SOURCE_DIR}/yololayer.cu ${PROJECT_SOURCE_DIR}/yololayer.h 
                ${PROJECT_SOURCE_DIR}/hardswish.cu ${PROJECT_SOURCE_DIR}/hardswish.h)   #4`

due to missing hardswish.cu and presumably will also fail on missing hardswish.h. Should these be in the tensorrtx-master\yolov5 folder? I tried to follow the instructions exactly but I guess I might have missed something.

I used the following packages:

**VS2017
CUDA 11.1.1
TensorRT-7.2.1.6.Windows10.x86_64.cuda-11.1.cudnn8.0
CMake-3.19.0-win64-x64
opencv-4.5.0-vc14_vc15
dirent.h  v1.23.2**

Thanks for any advice! And thanks for your work on this repo.

**Comment by wang-xinyu** [comment]
these two files already been removed. just delete them in cmake.

**Comment by Transigent** [comment]
Thanks that solved the problem.

**Comment by yang-gis** [comment]
> Hi I am attempting to follow the instructions for compiling and running on Windows, here:
> https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md
> 
> I get to the Generate stage for yolov5 and it fails here:
> 
> `add_executable(yolov5 ${PROJECT_SOURCE_DIR}/yolov5.cpp ${PROJECT_SOURCE_DIR}/yololayer.cu ${PROJECT_SOURCE_DIR}/yololayer.h ${PROJECT_SOURCE_DIR}/hardswish.cu ${PROJECT_SOURCE_DIR}/hardswish.h) #4`
> 
> due to missing hardswish.cu and presumably will also fail on missing hardswish.h. Should these be in the tensorrtx-master\yolov5 folder? I tried to follow the instructions exactly but I guess I might have missed something.
> 
> I used the following packages:
> 
> **VS2017 CUDA 11.1.1 TensorRT-7.2.1.6.Windows10.x86_64.cuda-11.1.cudnn8.0 CMake-3.19.0-win64-x64 opencv-4.5.0-vc14_vc15 dirent.h v1.23.2**
> 
> Thanks for any advice! And thanks for your work on this repo.



> Hi I am attempting to follow the instructions for compiling and running on Windows, here:
> https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md
> 
> I get to the Generate stage for yolov5 and it fails here:
> 
> `add_executable(yolov5 ${PROJECT_SOURCE_DIR}/yolov5.cpp ${PROJECT_SOURCE_DIR}/yololayer.cu ${PROJECT_SOURCE_DIR}/yololayer.h ${PROJECT_SOURCE_DIR}/hardswish.cu ${PROJECT_SOURCE_DIR}/hardswish.h) #4`
> 
> due to missing hardswish.cu and presumably will also fail on missing hardswish.h. Should these be in the tensorrtx-master\yolov5 folder? I tried to follow the instructions exactly but I guess I might have missed something.
> 
> I used the following packages:
> 
> **VS2017 CUDA 11.1.1 TensorRT-7.2.1.6.Windows10.x86_64.cuda-11.1.cudnn8.0 CMake-3.19.0-win64-x64 opencv-4.5.0-vc14_vc15 dirent.h v1.23.2**
> 
> Thanks for any advice! And thanks for your work on this repo.

hello guys,can you share your dirent.h file?
