### ISSUE TITLE
Question about usability

### ISSUE THREAD

**Issue by Kmarconi** [wang-xinyu/tensorrtx#3]
HI, 

First thanks for your repo, there is a lot to learn here ! :) I'm working on my Jetson Xavier and with others project, I've been able to go up to 220 FPS with an SSD mobilenet model optimized with TRT and quantized to FP16. With almost the same process, I'm only around 22 FPS with Yolov3. I was looking if there was any way to make it faster and I saw your repo. I've build the wts file and then i run the ./yolov3 -s and -d command, but I was wondering if there was any way to know the performance of this and also if I could use it with a webcam for example. 

Regards ! :) And thanks again for this good repo

**Comment by wang-xinyu** [comment]
@Kmarconi thank for attention.

In [yolov3.cpp](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov3/yolov3.cpp) line 525-539, a timer is used for timing the inference process. This time can be used to estimate FPS.

```
        auto start = std::chrono::system_clock::now();
        ...
        doInference(*context, data, prob, 1);
        ...
        auto end = std::chrono::system_clock::now();
        std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;
```

There are many methods to make yolov3 faster,
 
- the backbone in this repo is darknet53, which is much larger than mobilenet, so changing the backbone can make it fast.
- this repo's yolov3-trt implementation is just demo, not optimized for high FPS, the yolo layer, nms process, etc, can be optimized.
- model pruning, int8, etc. can help increase speed too.

For webcam app, you need coding to integrate this yolov3-trt to your project, which is not concerned in this repo.

regards.

**Comment by Kmarconi** [comment]
Thanks for your quick reply, just so you know if you wanna add this data to your benchmark, i'm around 55 FPS on my Xavier for the moment. About the 3 points you gave me, do you have any advice or link to guide me through these steps ?

Regards

**Comment by Kmarconi** [comment]
Update : Done the modification so that it can run on a camera and i'm arround 55 to 62 FPS on my Xavier

**Comment by wang-xinyu** [comment]
@Kmarconi, glad to hear your progress, you are rich enough to use xavier :)

- for backbone, there are many mobilenet yolov3 implementations in github, but I never try it, so don't know which one is better.
- [lewes6369/TensorRT-Yolov3](https://github.com/lewes6369/TensorRT-Yolov3) is a good trt-yolov3 implementation, which merges three yolo layers into one.   nms can implemented with cuda, refer to [NVIDIA/TensorRT](https://github.com/NVIDIA/TensorRT/tree/master/plugin/nmsPlugin).
- yolov3 pruning I tried [this](https://github.com/tanluren/yolov3-channel-and-layer-pruning), but it's readme is in Chinese.
- int8 can done in tensorrt, but need calibration, can refer to tensorrt docs, etc.

**Comment by Kmarconi** [comment]
Sadly it is not mine, only using it for an internship ^^ Will check your links, thanks

**Comment by ash80** [comment]
Hi @Kmarconi, I'm also trying to implement it for a camera. Could you please provide a sample code or link on how adapt the model to run with camera?
