### ISSUE TITLE
sudo ./yolov4 -s 时的错误问题

### ISSUE THREAD

**Issue by CNSTJiatongLee** [wang-xinyu/tensorrtx#30]
报错：
[05/27/2020-14:34:04] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov4: /media/mrlee/software/document/AI/project/traffic_scene/tensorrtx/yolov4/yolov4.cpp:209: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.

您好，我的yolov4模型经过剪枝，压缩了95%的参数，剪了12个shortcut，出现了这个问题。

**Comment by wang-xinyu** [comment]
剪枝之后，这边tensorrt的代码要自己修改的。

**Comment by CNSTJiatongLee** [comment]
感谢回复，能否说下具体是需要修改哪个文件呢

**Comment by wang-xinyu** [comment]
yolov4.cpp定义了整个网络，要依据剪枝后的结构修改

**Comment by gongdalinux** [comment]
请问你一下yolov4剪枝是参考https://github.com/tanluren/yolov3-channel-and-layer-pruning这个repo么？速度怎样？加快多少？
我的yolov4模型用本repo测试1920×1080图片一次前向推理耗时约110ms

**Comment by wangtianlong1994** [comment]
同问是参考https://github.com/tanluren/yolov3-channel-and-layer-pruning这个吗？如果是 现在您转换成功了吗 能否给一些参考意见呢 @CNSTJiatongLee

**Comment by wang-xinyu** [comment]
剪枝需要重新定义网络
