### ISSUE TITLE
Got Floating point exception (core dumped)

### ISSUE THREAD

**Issue by pribadihcr** [wang-xinyu/tensorrtx#303]
Hi @wang-xinyu, 
when run ./arcface-r50 -d   I got the following error:
Floating  point exception (core dumped)

**Comment by wang-xinyu** [comment]
maybe your environment not right.
you can try other models, or firstly make sure tensorrt can work.

**Comment by weixiu00** [comment]
download joey0.ppm and  joey1.ppm
put them tensorrtx/arcface/ 

it works for me

**Comment by bkhti4** [comment]
I am getting the same error for yolov5 of any type. It seems if I use .weights (yolov4, yolov3, yolov3-tiny) to .wts conversion it works fine but if I use .pt to .wts then the engine throws the Floating point error.
Can anyone check into it.

**Comment by wang-xinyu** [comment]
@bkhti4 can you open a new thread and using the issue template?
