### ISSUE TITLE
INT8 quantization under TensorRT for yolov5

### ISSUE THREAD

**Issue by Hshuqin** [wang-xinyu/tensorrtx#304]
Hello, thank you very much for the code. I have successfully accelerated the yolov5 model using tensorrt. But I want to continue using INT8 quantization, what do I need to do?
I refer to the code in tensorrtx/retinaface, and add calibrator.cpp and calibrator.h to tensorrtx/yolov5, and modify the yolov5 code accordingly, but the make does not pass. The following error is reported.

`tensorrtx/yolov5/calibrator.cpp:4:31: fatal error: opencv2/dnn/dnn.hpp: No such file or directory`

If I download and install opencv2, will it compile and pass?
I noticed that there is an additional piece of code in tensorrtx/retinaface/cmakefile.txt

`if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
    message("embed_platform on")
    include_directories(/usr/local/cuda/targets/aarch64-linux/include)
    link_directories(/usr/local/cuda/targets/aarch64-linux/lib)
else()
    message("embed_platform off")
    include_directories(/usr/local/cuda/include)
    link_directories(/usr/local/cuda/lib64)
endif()`

But I don't have aarch64-linux folder in my environment, and I'm wondering what I should do to compile it successfully, thanks for your advice!
---------------------------------------------
My Environment:
ubuntu: 16.04
CUDA:10.1
CUDNN:7.6.0
TensorRT:6.0.1.5

**Comment by wang-xinyu** [comment]
refer to the install tutorial in this repo.
and also try `sudo apt install libopencv-dnn-dev`

**Comment by Hshuqin** [comment]
> refer to the install tutorial in this repo.
> and also try `sudo apt install libopencv-dnn-dev`

I finished the installation and still get the same error.

**Comment by berkantay** [comment]
hello @Hshuqin , I did not get any acceleration in my inference? Have you got any reference for quick accelerated demo?

**Comment by Hshuqin** [comment]
> hello @Hshuqin , I did not get any acceleration in my inference? Have you got any reference for quick accelerated demo?

I haven't solved the above problem yet, so I don't know if it will work.

**Comment by Hshuqin** [comment]
> refer to the install tutorial in this repo.
> and also try `sudo apt install libopencv-dnn-dev`

I've downloaded libopencv-dnn-dev, but I make keeps reporting the previous error. 
I think it's because my cmakefile is not written correctly. how do I modify the cmakefile? 

`tensorrtx/yolov5/calibrator.cpp:4:31: fatal error: opencv2/dnn/dnn.hpp: No such file or directory`

**Comment by Hshuqin** [comment]
Sorry sorry, I rechecked today and found that the previous installation of libopencv-dnn-dev was not successful, so I still get the same error when I make it later.
I tried using the commands 

`sudo apt-get update`
 and 
`sudo apt-get upgrade`

but it still gives me the error 

`Unable to locate package libopencv-dnn-dev.`

I can't find a solution to this problem. I wonder if you know how to solve this problem, thanks for your reply!

**Comment by wang-xinyu** [comment]
refer to the install tutorial to install opencv,
or compile opencv from source with dnn option,

or just use the dockerfile in this repo...

**Comment by Hshuqin** [comment]
> refer to the install tutorial to install opencv,
> or compile opencv from source with dnn option,
> 
> or just use the dockerfile in this repo...

Thanks for the suggestion, I saw and installed opencv in the install.md file.
However, after installation, I have problems with the command  `cmake .. `  

`CMake Error at /usr/share/OpenCV/OpenCVModules.cmake:189 (message):
  The imported target "opencv_dnn" references the file
     "/usr/lib/x86_64-linux-gnu/libopencv_dnn.so.3.3.1"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/share/OpenCV/OpenCVModules.cmake"
  but not all the files it references.
`

I used the following command via your suggestion under another issue [#286.](https://github.com/wang-xinyu/tensorrtx/issues/286)
`
sudo apt install libopencv-shape-dev
or
sudo apt install libopencv-*-dev
`

However, another problem was reported, which was the version that was too new.
`The following packages have unmet dependencies:
libopencv-contrib-dev : Depends: libopencv-calib3d-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-highgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-ml-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-video-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-objdetect-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
libopencv-gpu-dev : Depends: libopencv-core-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
libopencv-legacy-dev : Depends: libopencv-video-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-calib3d-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-ml-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-highgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
libopencv-ocl-dev : Depends: libopencv-calib3d-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-ml-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-objdetect-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-highgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed
Depends: libopencv-video-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but 3.3.1-xenial1.2 is to be installed`

I reinstalled libopencv-shape-dev and other required packages by installing aptitude, and the cmake passed, but when I make it, I get the same error again, a dead loop!

`fatal error: opencv2/dnn/dnn.hpp: No such file or directory`

Do you know what to do about it? thanks for your reply!

**Comment by Vadbeg** [comment]
Hey! I solved this issue. The points is, that you need to install OpenCV from source with usage of DNN (like the @wang-xinyu said). You can do it using this [tutorial](https://cuda-chen.github.io/image%20processing/programming/2020/02/22/build-opencv-dnn-module-with-nvidia-gpu-support-on-ubuntu-1804.html). I've found an small error in it, you'll need change their cmake command to this one (they had typo in `OPENCV_EXTRA_MODULES_PATH` and forget about `..` in the end).

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D WITH_CUDA=ON \
    -D WITH_CUDNN=ON \
    -D OPENCV_DNN_CUDA=ON \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D CUDA_ARCH_BIN=6.1 \
    -D WITH_CUBLAS=1 \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv/opencv_contrib/modules/ \
    -D HAVE_opencv_python3=ON \
    -D PYTHON_EXECUTABLE=~/.virtualenvs/opencv_cuda/bin/python \
    -D BUILD_EXAMPLES=ON ..
```

I highly recommend you to use docker file from this repo. Run in interactive mode, install OpenCV (it will take a while) and after that you can successfully convert model.

P.S. @wang-xinyu , pls add OpenCV installation to Dockerfile, I think it'll save a lot time for users. And thanks for your excellent work!

**Comment by Hshuqin** [comment]
> Hey! I solved this issue. The points is, that you need to install OpenCV from source with usage of DNN (like the @wang-xinyu said). You can do it using this [tutorial](https://cuda-chen.github.io/image%20processing/programming/2020/02/22/build-opencv-dnn-module-with-nvidia-gpu-support-on-ubuntu-1804.html). I've found an small error in it, you'll need change their cmake command to this one (they had typo in `OPENCV_EXTRA_MODULES_PATH` and forgot about `..` in the end).
> 
> ```
> cmake -D CMAKE_BUILD_TYPE=RELEASE \
>     -D CMAKE_INSTALL_PREFIX=/usr/local \
>     -D INSTALL_PYTHON_EXAMPLES=ON \
>     -D INSTALL_C_EXAMPLES=OFF \
>     -D OPENCV_ENABLE_NONFREE=ON \
>     -D WITH_CUDA=ON \
>     -D WITH_CUDNN=ON \
>     -D OPENCV_DNN_CUDA=ON \
>     -D ENABLE_FAST_MATH=1 \
>     -D CUDA_FAST_MATH=1 \
>     -D CUDA_ARCH_BIN=6.1 \
>     -D WITH_CUBLAS=1 \
>     -D OPENCV_EXTRA_MODULES_PATH=~/opencv/opencv_contrib/modules/ \
>     -D HAVE_opencv_python3=ON \
>     -D PYTHON_EXECUTABLE=~/.virtualenvs/opencv_cuda/bin/python \
>     -D BUILD_EXAMPLES=ON ..
> ```
> 
> I highly recommend you to use docker file from this repo. Run in interactive mode, install OpenCV (it will take a while) and after that you can successfully convert model.
> 
> P.S. @wang-xinyu , pls add OpenCV installation to Dockerfile, I think it'll save a lot time for users. And thanks for your excellent work!

Thanks for the suggestion, I can't access it from the URL you suggested, can you tell me in detail how to recompile opencv or is there any other URL you suggest? Thank you for your reply.

**Comment by yogidosalwar** [comment]
@Hshuqin   I am also trying to convert INT8 quantization, if you have any idea please let me know. 

How to build the table for int8 calibration?

Thank you !!

**Comment by Wulingtian** [comment]
![IMG_20201231_094134](https://user-images.githubusercontent.com/20986422/103390526-cb492480-4b4f-11eb-995c-c695457abeaf.jpg)
我成功把yolov5的onnx模型转化为trt int模型，速度5ms左右，但是不出框，有交流一下的吗？

**Comment by AlfengYuan** [comment]
docker trt7.2_cuda10.2 env had pushed docker-hub. you can follow there steps to build yourself docker container
1. docker push hakuyyf/tensorrtx:trt7.2_cuda10.2
2. docker run -it ...#Create a container and enter in
3. workon opencv_cuda
4. cd ~/opencv/opencv && mkdir build && cd build
5. search  [Your GPU Compute Capability](https://developer.nvidia.com/zh-cn/cuda-gpus#compute) and change -D CUDA_ARCH_BIN=*  in  step6.
6. cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=OFF \
-D OPENCV_ENABLE_NONFREE=ON \
-D WITH_CUDA=ON \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D CUDA_ARCH_BIN=* \
-D WITH_CUBLAS=1 \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv/opencv_contrib/modules/ \
-D HAVE_opencv_python3=ON \
-D PYTHON_EXECUTABLE=~/.virtualenvs/opencv_cuda/bin/python \
-D BUILD_EXAMPLES=ON ..
7. make -j$(nproc)
8. make install
9. ldconfig
# If there is not any error report, it have been build success with opencv dnn modules. 
# opencv build and install reference this [tutories](https://cuda-chen.github.io/image%20processing/programming/2020/02/22/build-opencv-dnn-module-with-nvidia-gpu-support-on-ubuntu-1804.html), thanks for @Hshuqin .
# I test cpp it's ok, python not work, but it's ok, you can just install it by pip opencv_python.

**Comment by chenxyyy** [comment]
> ![IMG_20201231_094134](https://user-images.githubusercontent.com/20986422/103390526-cb492480-4b4f-11eb-995c-c695457abeaf.jpg)
> 我成功把yolov5的onnx模型转化为trt int模型，速度5ms左右，但是不出框，有交流一下的吗？

int8量化需要500-1000张图做校准，才能保证精度

**Comment by sydpan** [comment]
> > ![IMG_20201231_094134](https://user-images.githubusercontent.com/20986422/103390526-cb492480-4b4f-11eb-995c-c695457abeaf.jpg)
> > 我成功把yolov5的onnx模型转化为trt int模型，速度5ms左右，但是不出框，有交流一下的吗？
> 
> int8量化需要500-1000张图做校准，才能保证精度
请教一下你说的“校准”具体是指什么？不太知道具体要怎么做....

**Comment by sydpan** [comment]
@chenxyyy 请教一下你说的“校准”具体是指什么？具体应该怎么做呢？

**Comment by sydpan** [comment]
@Wulingtian 请问可以分享一下代码吗？我参照作者yolov3的做法，编译出错

**Comment by wang-xinyu** [comment]
yolov5 in this repo already supporting int8. pls take a look

**Comment by sydpan** [comment]
> yolov5 in this repo already supporting int8. pls take a look
Thanks a lot. This could be very helpful.
