### ISSUE TITLE
Upsampling layer

### ISSUE THREAD

**Issue by pribadihcr** [wang-xinyu/tensorrtx#305]
Hi @wang-xinyu,

Is there upsampling layer for tensorrt like this https://mxnet.apache.org/versions/1.6/api/r/docs/api/mx.symbol.UpSampling.html ?
Thanks

**Comment by wang-xinyu** [comment]
you can refer to the deconvolution used in yolo, which can replace upsample.
or you can check resizelayer in tensorrt docs.

**Comment by pribadihcr** [comment]
Thanks, I used resizelayer
