### ISSUE TITLE
無法寫入影片檔

### ISSUE THREAD

**Issue by chrisgame1002** [wang-xinyu/tensorrtx#306]
(base) bill@bill-Z390-GAMING-X:~/tensorrtx/yolov5/build$ sudo ./yolov5 -d  ../samples
[sudo] password for bill: 
[11/26/2020-14:42:24] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
3ms
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0-openvino-2020.3.0) ../opencv/modules/imgcodecs/src/loadsave.cpp:734: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

Aborted

想請問sample資料夾裡的照片檔都能使用trt加速，但只要放影片檔就會產生以上的error

**Comment by wang-xinyu** [comment]
what is 影片檔, do you mean video?
the demo can only process pictures, for video you need implement it yourself.

**Comment by berkantay** [comment]
hello @chrisgame1002 did you implement the inference for video?
