### ISSUE TITLE
adaptive pooling

### ISSUE THREAD

**Issue by pribadihcr** [wang-xinyu/tensorrtx#307]
Hi @wang-xinyu ,

Is there adaptive pooling api like in this https://mxnet.apache.org/versions/1.6/api/python/docs/api/symbol/contrib/index.html#mxnet.symbol.contrib.AdaptiveAvgPooling2D? Thanks

**Comment by wang-xinyu** [comment]
no, you can use general poolinglayer or reducelayer.
