### ISSUE TITLE
请问有把YOLOv5的前处理和输出后的nms加入到tensorrt engine的计划吗？

### ISSUE THREAD

**Issue by Wulingtian** [wang-xinyu/tensorrtx#308]
请问有把YOLOv5的前处理和输出后的nms加入到tensorrt engine的计划吗？

**Comment by wang-xinyu** [comment]
没有，我觉得没必要，nms现在很快，因为输出bbox没多少，在yoloplugin里过滤掉了大部分。
预处理除非把input type改为int8，如果是fp32就没必要。

**Comment by xiaohuihui52309** [comment]
想问下把前处理加速的话，可以直接把输入按照下面的代码处理吗，输入图像为torch tensor在cuda device
`for binding in self.engine:
               
                # Append to the appropriate list.
                if self.engine.binding_is_input(binding):
                    input_num += 1
                    print('input binding size', self.engine.get_binding_shape(binding))
                    print('input_image size', input_image.size())
                    bindings.append(input_image.contiguous().data_ptr())
                    
                else:
                    output_num += 1
                    dtype = torch_dtype_from_trt(self.engine.get_binding_dtype(binding))
                    shape = (batch_size,) + tuple(self.engine.get_binding_shape(binding))
                    device = torch_device_from_trt(self.engine.get_location(binding))
                    output = torch.empty(size=shape, dtype=dtype, device=device)
                    outputs.append(output)
#                     idx = self.engine.get_binding_index(binding)
#                     print('idx', idx)
                    bindings.append(output.data_ptr())
                   
            self.context.execute_async(
                batch_size, bindings, torch.cuda.current_stream().cuda_stream
            )`
