### ISSUE TITLE
为什么用了tensorrt没起到加速效果

### ISSUE THREAD

**Issue by Gaoxj2020** [wang-xinyu/tensorrtx#309]
用的yolov5m 模型，转换后用作者提供的python 接口测试速度基本没变化，这是什么原因呢？

**Comment by wrz57661** [comment]
我试过yolov5s，转成tensorrt后甚至比原pytorch更慢

**Comment by wang-xinyu** [comment]
测下c++，python时间包括了imwrite

**Comment by bobby20180331** [comment]
yolov4 -sample . follow the instructions. implemented on AGX Xaiver.
52ms/  img   .the speed is not as good as expectation.
$ sudo ./yolov4 -d ../../yolov3-spp/samples/
686ms
52ms

**Comment by pengfeidip** [comment]
> 我试过yolov5s，转成tensorrt后甚至比原pytorch更慢

我的也是。c++ tensorrt比起pytorch，单纯的前向时间反而变慢了，不知道你有没有解决这一个问题

**Comment by pengfeidip** [comment]
> > > 我试过yolov5s，转成tensorrt后甚至比原pytorch更慢
> > 
> > 
> > 我的也是。c++ tensorrt比起pytorch，单纯的前向时间反而变慢了，不知道你有没有解决这一个问题
> 
> 应该是图片的尺寸问题，yolov5原版的inference中图片是自动放缩的

我不是很明白你的意思。我在原版的pytorch-yolov5中的[detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)中仔细测试了第69行代码，确认了这个时候的图像尺度是预期的。具体的测时间的code如下

```

  # Inference
  t1 = time_synchronized()
  aa = time.time()
  pred = model(img, augment=opt.augment)[0]
  print(pred)
  bb = time.time()
  t3 = time_synchronized()
  print("Time consuming is {}".format(t3-t1))
  print("Time consuming is {}".format(bb-aa))
        
```

```
