### ISSUE TITLE
Inference time slower than expected

### ISSUE THREAD

**Issue by berkantay** [wang-xinyu/tensorrtx#310]
Hello @wang-xinyu, I implemented your yolov5 tutorial on my custom dataset. Everything works fine but I want to ask something. After the ```sudo ./yolov5 -d ../samples``` I get 1089 ms after inference. Is it just building up the engine or engine building + inference?

Best Regards

**Comment by wang-xinyu** [comment]
-s is building the engine,
-d is loading the engine and inference. For inference, the first batch maybe slow, as it may includes some init process. you can test in a loop, and check the latency for each round.

**Comment by berkantay** [comment]
Hello again @wang-xinyu, when I run the the code with in loop, I get exactly what you mentioned, first inference takes longer than the others but in original yolo framework I get 0.080 seconds for inference on average. But with tensorrt engine I get appr. 100 ms for inference. Is something wrong here? Exactly same model is used.

**Comment by wang-xinyu** [comment]
the input shape, here is fixed and defined in yololayer.h, which is 608x608 by default.
while in pytorch, it's dynamic according to the original shape, so it's maybe smaller than 608x608.

**Comment by berkantay** [comment]
my trained network has 1088x1088 input shape. I resize it while generating ```.wts``` file. Is it legit?

**Comment by berkantay** [comment]
Hello again @wang-xinyu there is 20ms difference between ```yolov5_trt.py``` and ```./yolov5 -d ../samples```. C++ code is the fastest one. Is it okay to see difference like that.
