### ISSUE TITLE
error:Jetson nano deployment resnet50 

### ISSUE THREAD

**Issue by lionlu911** [wang-xinyu/tensorrtx#312]
error message：
admin1@admin1:~/tensorrtx/resnet/build$ ./resnet50  -s
Loading weights: ../13.wts
len 64
len 64
len 64
len 256
len 256
len 64
len 64
len 256
len 64
len 64
len 256
len 128
len 128
len 512
len 0
[12/02/2020-15:44:01] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
resnet50: /home/admin1/tensorrtx/resnet/resnet50.cpp:107: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
已放弃 (核心已转储)

Before that, I've tried the example given and it works.
My .wts file is in the same format as the one that generates the engine.
我之前用resnet50,里面的resnet50.py 和 inference.py生成的.wts文件可以生成引擎和推理，但我用自己到权重文件生成的就报上述到错误，请求帮助～

**Comment by wang-xinyu** [comment]
自己的权重和demo的模型有区别，自己对照一下网络结构，尤其最后一层看看

**Comment by lionlu911** [comment]
可以了，我确实多了3个池化，我现在engine生成没问题了，我再看看推理有没有问题，谢谢大佬～

**Comment by lionlu911** [comment]
1.我在生成wts文件时候用torch.ones(1,3,224,224).cuda()送到网络 输出到结果是output:tensor（[[62.3522,-3.7994,-51.3323]])
而我用自己权重生成到引擎推理出来的结果确是-0.1506, -0.127992, 0.102255。这是什么原因呢？
2.我在resnet50 -s的时候，最后提示could not open plan output file。能稍微解释一下嘛，我c++代码不是很溜。
@wang-xinyu

**Comment by lionlu911** [comment]
不知道为什么，我也没改代码，就可以了，也是无语，不过还是要谢谢大佬。

**Comment by python-bookworm** [comment]
> 不知道为什么，我也没改代码，就可以了，也是无语，不过还是要谢谢大佬。

你好，请教下你是在nano上使用tensorrt加速yolov5吗？目前你识别的帧率和准确率可以达到多少？

**Comment by nanhui69** [comment]
> 自己的权重和demo的模型有区别，自己对照一下网络结构，尤其最后一层看看

当不同的时候要怎么修改呢，在哪里修改呢？
