### ISSUE TITLE
onnx to tensorrt

### ISSUE THREAD

**Issue by alicera** [wang-xinyu/tensorrtx#313]
Do you get the problem when you convert the onnx to tensorrt for yolov5?
Do you know how to explain it ? 
thanks you
![image](https://user-images.githubusercontent.com/59388989/100864216-aa4dcf00-34d0-11eb-915a-d29822b519df.png)

**Comment by wang-xinyu** [comment]
This repo not using onnx but defining networks using API.

**Comment by alicera** [comment]
Could you explain it more detail, thanks you .

I try to convert the onnx to tensorrt

**Comment by ariel415el** [comment]
you should probably read the README. 
They built YOLOV5 with TRT API in order to skip the onnx step.
