### ISSUE TITLE
RetinaFace not utilizing more than 1GB of GPU memory!! Any ideas on how to utilize more of GPU??

### ISSUE THREAD

**Issue by makaveli10** [wang-xinyu/tensorrtx#32]
builder->setMaxWorkspaceSize(1 << 20);

I was not able to find much resources on how to change this to increase GPU memory utilization. Any help would be great.

**Comment by wang-xinyu** [comment]
Here `1 << 20` means 1MB, which is the workspace size for tensorrt engine building phase.
This one will not impact the runtime GPU memory utilization.

**Comment by makaveli10** [comment]
Okay! So, I am using RetinaFace for inference on a video. And it utilizes only 1000 MB during inference. As a result of which processes only at 20 fps. Which is very low for the standards of TensorRT. Can we somehow increase the runtime GPU memory utilization or the 20 fps processing speed??

**Comment by wang-xinyu** [comment]
You can try smaller input size to get faster speed.

**Comment by aditya-dl** [comment]
Hey @wang-xinyu 

Is there a way we can allot more GPU memory to the engine or force the engine to use higher memory?

**Comment by wang-xinyu** [comment]
@aditya-dl I didn't see any TensorRT API can do this.
I think tensorrt is merging the layers and channels during building phase, then calling cudnn and cuda functions to do inference during runtime phase. It aims at saving the GPU memory, and get shorter latency at the same time.
If you want to use more GPU memory to get shorter latency, I think it can't.
If you want to use more GPU memory to get more FPS, you can try increasing the batch size to processing multi images a time.
