### ISSUE TITLE
windows平台使用make出错，求助~~

### ISSUE THREAD

**Issue by fetchniches** [wang-xinyu/tensorrtx#320]
D:\RC_Vision\tensorrt\tensorrtx\yolov5\build>cmake ..
-- Building for: Visual Studio 16 2019
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.28.29334.0
-- The CXX compiler identification is MSVC 19.28.29334.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Software/Visual_Studio/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Software/Visual_Studio/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found version "10.1")
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV: D:/Software/opencv/opencv/build (found version "4.5.0")
-- Found OpenCV 4.5.0 in D:/Software/opencv/opencv/build/x64/vc15/lib
-- You might need to add D:\Software\opencv\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/RC_Vision/tensorrt/tensorrtx/yolov5/build

D:\RC_Vision\tensorrt\tensorrtx\yolov5\build>make
make: *** No targets specified and no makefile found.  Stop.

**Comment by BaofengZan** [comment]
你可以用cmake-gui来编译下，tutorial里面有教程

**Comment by fetchniches** [comment]
现在又找不到hardwish文件了...
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
    libraries: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudart.lib
    include path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include
OpenCV library status:
    version: 4.5.0
    libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio;opencv_world
    include path: D:/Software/opencv/opencv/build/include
Configuring done
CMake Error at CMakeLists.txt:51 (add_executable):
  Cannot find source file:

    D:/RC_Vision/tensorrt/tensorrtx/yolov5/hardswish.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at CMakeLists.txt:51 (add_executable):
  No SOURCES given to target: yolov5

**Comment by wang-xinyu** [comment]
hardswish.cu 和.h已经remove了，删掉就行

**Comment by fetchniches** [comment]
谢谢，现在我已经成功弄好yolov5s的模型，但我第一次试验yolov5l的模型一直有如下的显示：
[12/04/2020-19:22:03] [E] [TRT] (Unnamed Layer* 5) [Convolution]: kernel weights has count 6912 but 3456 was expected
[12/04/2020-19:22:03] [E] [TRT] (Unnamed Layer* 5) [Convolution]: count of 6912 weights in kernel, but kernel dimensions (3,3) with 12 input channels, 32 output channels and 1 groups were specified. Expected Weights count is 12 * 3*3 * 32 / 1 = 3456
且最后报错如下，没有生成engine文件，我需要修改common.hpp文件的哪些东西吗？
[12/04/2020-19:22:03] [E] [TRT] Could not compute dimensions for (Unnamed Layer* 5) [Convolution]_output, because the network is not valid.
[12/04/2020-19:22:03] [E] [TRT] Network validation failed.
Build engine successfully!
Assertion failed: engine != nullptr, file D:\RC_Vision\tensorrt\tensorrtx\yolov5\yolov5.cpp, line 396

**Comment by wang-xinyu** [comment]
pls try download yolov5 pytorch model from its release tag.

**Comment by DataXujing** [comment]
大佬 3.1版本的YOLO v5x也出现了相同的错误，怎么解决？

**Comment by wang-xinyu** [comment]
默认是s，m/l/x需要改一下宏定义，看下tensorrtx / yolov5 / readme说明

**Comment by xm0629** [comment]
> 谢谢，现在我已经成功弄好yolov5s的模型，但我第一次试验yolov5l的模型一直有如下的显示：
> [12/04/2020-19:22:03] [E] [TRT] (Unnamed Layer* 5) [Convolution]: kernel weights has count 6912 but 3456 was expected
> [12/04/2020-19:22:03] [E] [TRT] (Unnamed Layer* 5) [Convolution]: count of 6912 weights in kernel, but kernel dimensions (3,3) with 12 input channels, 32 output channels and 1 groups were specified. Expected Weights count is 12 * 3_3 * 32 / 1 = 3456 且最后报错如下，没有生成engine文件，我需要修改common.hpp文件的哪些东西吗？ [12/04/2020-19:22:03] [E] [TRT] Could not compute dimensions for (Unnamed Layer_ 5) [Convolution]_output, because the network is not valid.
> [12/04/2020-19:22:03] [E] [TRT] Network validation failed.
> Build engine successfully!这个个是什么原因啊，我在使用 mb1-ssd 时也出现这个问题

**Comment by wang-xinyu** [comment]
weights没对上一般是wts文件不对，模型不一致，试下项目model zoo里面的wts
