### ISSUE TITLE
[yolov5] Not getting output shown in README with yolov5m

### ISSUE THREAD

**Issue by hp2304** [wang-xinyu/tensorrtx#322]
While following README instructions for yolov5. I was successfully able to generate yolov5m.wts by following step1, after running 
`sudo ./yolov5 -d ../samples` in step2 (Building engine was also successful), it did generate _bus.jpg and _zidane.jpg but there were no bounding boxes in either of them (Not same as shown in README). While running the same in PyTorch (by running detect.py with weights yolov5m.pt from ultralytics/yolov5 repo) does give boxes in output. Also, running yolov5_trt.py confirmed this by giving no bounding boxes in output files. I did make minor changes in some files to make this work. Below are the configs I used to build,

In yololayer.h:

MAX_OUTPUT_BBOX_COUNT = 1000;
CLASS_NUM = 80;
INPUT_H = 608;
INPUT_W = 608;

In yolov5.cpp:

// Thresholds are defaults taken in ultralytics/yolov5/detect.py
// #define USE_FP16  // comment out this if want to use FP32
#define DEVICE 0  // GPU id
#define NMS_THRESH 0.45
#define CONF_THRESH 0.25
#define BATCH_SIZE 1

#define NET m  // s m l x

Am I doing something wrong? Can someone confirm this...

**Comment by wang-xinyu** [comment]
pls try download yolov5 pytorch model from its release tag.

**Comment by hp2304** [comment]
> pls try download yolov5 pytorch model from its release tag.

I downloaded it (yolov5m.pt from assets section) from this [link](https://github.com/ultralytics/yolov5/releases/tag/v3.1), which is the latest release. If this is incorrect can you provide a link for the one you are telling me about? Thanks.

**Comment by wang-xinyu** [comment]
https://github.com/ultralytics/yolov5/releases/download/v3.1/yolov5m.pt

I just tried this one, it works fine.

are you using the latest commit of this repo?

**Comment by hp2304** [comment]
Hi, I tried once again, it's still the same. [Here](https://drive.google.com/file/d/1vbOo7-wymksZACheWyRLShLwq-QSEu8V/view?usp=sharing) is a link to my yolov5 folder.
I have already generated yolov5m.wts, Can you build this and check. You will need to change tensorrt and opencv path in cmakelists (forgot to change it to default).

**Comment by hp2304** [comment]
Also, [this](https://drive.google.com/file/d/1omhUfRG5EsupxxXWBnx1SdAFsexbsy34/view?usp=sharing) is the engine file and results that I got.

**Comment by wang-xinyu** [comment]
your yolov5m.wts is same as mine. 

what's your GPU? and can you try trt7.0?

**Comment by hp2304** [comment]
GPU: Nvidia Geforce 940MX
I will check with trt7.0

**Comment by wang-xinyu** [comment]
940mx so old.... I don't know if that is compatible with cuda10.x. or tensorrt 7.x

**Comment by wang-xinyu** [comment]
and you can try using fp32.

**Comment by hp2304** [comment]
> In yolov5.cpp:
> 
> // Thresholds are defaults taken in ultralytics/yolov5/detect.py
> // #define USE_FP16 // comment out this if want to use FP32
> #define DEVICE 0 // GPU id
> #define NMS_THRESH 0.45
> #define CONF_THRESH 0.25
> #define BATCH_SIZE 1
> 
> #define NET m // s m l x

I have already commented USE_FP16 line to use fp32. And I have checked on Cuda 11.1 Nvidia docs and my GPU is **compatible**. Also, I am successfully able to run _https://github.com/linghu8812/tensorrt_inference/tree/master/yolov5_ on my tensorrt version 7.2.6.1 via Torch->ONNX->TensorRT method.

**Comment by wang-xinyu** [comment]
did you solve this issue?
