### ISSUE TITLE
yolov5s调用后召回率降低明显

### ISSUE THREAD

**Issue by liu2011tao** [wang-xinyu/tensorrtx#324]
我用5s模型训练了大约12000张红绿信号灯图片。分别在yolov5自带的detect.py和调用后的yolov5.cpp测试了相同的3000张测试集，iou阈值和置信度阈值完全一样，采用32位浮点，但最终结果调用后的模型召回率低了百分之10左右，精确率也有降低，请问有人遇到过吗？

**Comment by LevineYang** [comment]
+1
最近训练了自己的custom dataset, 也是用yolov5自带的detect.py测试，测试效果很好。用yolov5.cpp测试，FP32, 效果变差了

**Comment by wang-xinyu** [comment]
调一下yololayer.h里面的IGNORE_THRESH和MAX_OUTPUT_BBOX_COUNT试试

**Comment by LevineYang** [comment]
> 调一下yololayer.h里面的IGNORE_THRESH和MAX_OUTPUT_BBOX_COUNT试试

谢谢，我这儿解决了。转换之后的结果其实是没问题的，我自己在代码里面做了ROI筛选，忘了自己改过代码了，orz...
