### ISSUE TITLE
[YoloV5] Inference time scales linearly with batch size

### ISSUE THREAD

**Issue by fpingham** [wang-xinyu/tensorrtx#326]
Hi @wang-xinyu, first of all thanks for your wonderful work.

I am running inference with `yolov5` using the` yolov5.cpp` variant (not  `yolov5_trt.py`). I understand that the `BATCH_SIZE` parameter sets the batch size so that the number of `forward` equivalents performed in _tensorrt_ is 'n_files/batch_size'. If this is the case, I would expect the inference time of one batch not to scale linearly with its size. However, when I perform the experiment (with `BATCH_SIZE = 1` and `BATCH_SIZE = 100`) the inference time scales linearly with the number of examples in the batch (75ms vs ~7400ms).

Am I missing something? Is my initial assumption that inference time should not scale linearly with the number of examples per batch wrong?

Thanks!

**Comment by mosheliv** [comment]
do you measure the time including loading the images? on some systems the I/O takes most of the time, and unless you do it in parallel (and for the first batch) it will scale linearly

**Comment by fpingham** [comment]
Yes, the time includes loading the images to CUDA Memory. Do you know any source on how I can load in parallel? The code that I am currently using to load the data (yolov5.cpp) is this one:

```
 // DMA input batch data to device, infer on the batch asynchronously, and DMA output back to host
    CHECK(cudaMemcpyAsync(buffers[0], input, batchSize * 3 * INPUT_H * INPUT_W * sizeof(float), cudaM
emcpyHostToDevice, stream));

```
