### ISSUE TITLE
about yolov3 build in windows 10

### ISSUE THREAD

**Issue by leizhu1989** [wang-xinyu/tensorrtx#327]
when I build a yolov3 project in windows 10 ,it has some error like this:
未定义标识符 "threadIdx"	yoloV3	e:\deeplearn\tensorrtx-master\yolov3\yololayer.cu	139	
未定义标识符 "blockIdx"	yoloV3	e:\deeplearn\tensorrtx-master\yolov3\yololayer.cu	139	
未定义标识符 "blockDim"	yoloV3	e:\deeplearn\tensorrtx-master\yolov3\yololayer.cu	139
未定义标识符 "atomicAdd"	yoloV3	e:\deeplearn\tensorrtx-master\yolov3\yololayer.cu	162	

	
I cheak my environment cudnn7.6.5  vs2015  tensorRT 7.0.0  cuda10.0 

I can not find this three variable defined in yololayer.h,where is the error ? could you give some ideas

**Comment by wang-xinyu** [comment]
cuda里面的符号，参考项目的windows教程，或者查查怎么编译cuda代码
