### ISSUE TITLE
how to convert yolov5 to INT8 quantization

### ISSUE THREAD

**Issue by yogidosalwar** [wang-xinyu/tensorrtx#330]
@wang-xinyu   
How to convert yolov5 to INT8 quantization.

TensorRT-6
os: Ubuntu 16.04
torch : 1.6.0+cu101
torchvision : 0.7.0+cu101
cuda : 10.1
python : 3.6

Thank You...

**Comment by yogidosalwar** [comment]
@wang-xinyu 
How can I convert? Can you please guide me. 

Thank you.

**Comment by wang-xinyu** [comment]
refer to the yolov3 int8 in this repo, it is nearly the same.

**Comment by yogidosalwar** [comment]
@wang-xinyu , Thank you so much for the quick response.
Yeah, it is (yolov3 int8) nearly the same. 
I am referring yolov3 int8 for the yolov5 Int8 conversion, but still getting the error. 

Error: 

CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `createEngine_s(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType)':
/Downloads/tensorrtx-master_3/yolov5/yolov5.cpp:121: undefined reference to `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `createEngine_m(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType)':
/Downloads/tensorrtx-master_3/yolov5/yolov5.cpp:218: undefined reference to `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `createEngine_l(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType)':
/Downloads/tensorrtx-master_3/yolov5/yolov5.cpp:314: undefined reference to `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `createEngine_x(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType)':
/Downloads/tensorrtx-master_3/yolov5/yolov5.cpp:411: undefined reference to `Int8EntropyCalibrator2::Int8EntropyCalibrator2(int, int, int, char const*, char const*, char const*, bool)'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5.dir/build.make:114: recipe for target 'yolov5' failed
make[2]: *** [yolov5] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I am using:

TensorRT-6
os: Ubuntu 16.04
torch : 1.6.0+cu101
torchvision : 0.7.0+cu101
cuda : 10.1
python : 3.6

Thank you.

**Comment by lzcchl** [comment]
我昨天还点赞了，结果去试 的时候，发现有问题，在x86 yolov5 的int8是有检测框的，但是在jetson nx上面，就没有检测框了，代码可以运行，就是没有框，我大概定位是tensorrt的版本，我的x86是和gay主一样的7.0，但是jetson上面一刷机就是7.1版本，难道我要降版本，或者gay主测试一下是不是这个问题

**Comment by yogidosalwar** [comment]
Hi @wang-xinyu ,
I am unable to download calibration images from your given link.
https://pan.baidu.com/s/1GOm_-JobpyLMAqZWCDUhKg

showing message This site can’t be reached. 
Please provide me valid link.

Thank you.

**Comment by priteshgohil** [comment]
@wang-xinyu Are you testing INT8 quantization for YOLOv5? It would be great to see this updated in YOLOv5.cpp.

**Comment by yogidosalwar** [comment]
Hey @wang-xinyu ,

I am unable to download calibration images (YoloV3) from your given link.
https://pan.baidu.com/s/1GOm_-JobpyLMAqZWCDUhKg

showing message This site can’t be reached.
Please provide me valid link.

Thank you.

**Comment by wang-xinyu** [comment]
yolov5 is supporting int8 now.
