### ISSUE TITLE
Failed on last step:box drawing in picture .

### ISSUE THREAD

**Issue by bobby20180331** [wang-xinyu/tensorrtx#331]
==============Failed on AGX Xavier TensorRT yolov4.wts --===================================

yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ sudo ./yolov4 -d ../../yolov3-spp/samples/
[12/16/2020-13:50:46] [E] [TRT] ../rtSafe/cuda/cudaPluginV2Runner.cpp (184) - Cuda Error in execute: 209 (no kernel image is available for execution on the device)
[12/16/2020-13:50:46] [E] [TRT] FAILED_EXECUTION: std::exception
13ms
[12/16/2020-13:50:46] [E] [TRT] ../rtSafe/cuda/cudaPluginV2Runner.cpp (184) - Cuda Error in execute: 209 (no kernel image is available for execution on the device)
[12/16/2020-13:50:46] [E] [TRT] FAILED_EXECUTION: std::exception
4ms
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ ls
_bus.jpg  CMakeCache.txt  CMakeFiles  cmake_install.cmake  libmyplugins.so  Makefile  yolov4  yolov4.engine  _zidane.jpg
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ ls
_bus.jpg  CMakeCache.txt  CMakeFiles  cmake_install.cmake  libmyplugins.so  Makefile  yolov4  yolov4.engine  _zidane.jpg
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ ls
_bus.jpg  CMakeCache.txt  CMakeFiles  cmake_install.cmake  libmyplugins.so  Makefile  yolov4  yolov4.engine  _zidane.jpg
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ nvcc -
^C
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ sudo ./yolov4 -d ../../yolov3-spp/samples/
[12/16/2020-13:55:51] [E] [TRT] ../rtSafe/cuda/cudaPluginV2Runner.cpp (184) - Cuda Error in execute: 209 (no kernel image is available for execution on the device)
[12/16/2020-13:55:51] [E] [TRT] FAILED_EXECUTION: std::exception
12ms
[12/16/2020-13:55:51] [E] [TRT] ../rtSafe/cuda/cudaPluginV2Runner.cpp (184) - Cuda Error in execute: 209 (no kernel image is available for execution on the device)
[12/16/2020-13:55:51] [E] [TRT] FAILED_EXECUTION: std::exception
3ms
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_21:14:42_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ uname -a
Linux yunhuax-desktop 4.9.140-tegra #1 SMP PREEMPT Fri Oct 16 12:25:00 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ python3 -V
Python 3.6.9
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ python -V
Python 2.7.17
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ cat /usr/include/cudnn.h |grep CUDNN_MAJOR -A 2
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ ls
_bus.jpg  CMakeCache.txt  CMakeFiles  cmake_install.cmake  libmyplugins.so  Makefile  yolov4  yolov4.engine  _zidane.jpg
yunhuax@yunhuax-desktop:/workspace/yolov4-trt/tensorrtx/yolov4/build$ dpkg -l |grep TensorRT
ii  graphsurgeon-tf                               7.1.3-1+cuda10.2                                 arm64        GraphSurgeon for TensorRT package
ii  libnvinfer-bin                                7.1.3-1+cuda10.2                                 arm64        TensorRT binaries
ii  libnvinfer-dev                                7.1.3-1+cuda10.2                                 arm64        TensorRT development libraries and headers
ii  libnvinfer-doc                                7.1.3-1+cuda10.2                                 all          TensorRT documentation
ii  libnvinfer-plugin-dev                         7.1.3-1+cuda10.2                                 arm64        TensorRT plugin libraries
ii  libnvinfer-plugin7                            7.1.3-1+cuda10.2                                 arm64        TensorRT plugin libraries
ii  libnvinfer-samples                            7.1.3-1+cuda10.2                                 all          TensorRT samples
ii  libnvinfer7                                   7.1.3-1+cuda10.2                                 arm64        TensorRT runtime libraries
ii  libnvonnxparsers-dev                          7.1.3-1+cuda10.2                                 arm64        TensorRT ONNX libraries
ii  libnvonnxparsers7                             7.1.3-1+cuda10.2                                 arm64        TensorRT ONNX libraries
ii  libnvparsers-dev                              7.1.3-1+cuda10.2                                 arm64        TensorRT parsers libraries
ii  libnvparsers7                                 7.1.3-1+cuda10.2                                 arm64        TensorRT parsers libraries
ii  nvidia-container-csv-tensorrt                 7.1.3.0-1+cuda10.2                               arm64        Jetpack TensorRT CSV file
ii  python-libnvinfer                             7.1.3-1+cuda10.2                                 arm64        Python bindings for TensorRT
ii  python-libnvinfer-dev                         7.1.3-1+cuda10.2                                 arm64        Python development package for TensorRT
ii  python3-libnvinfer                            7.1.3-1+cuda10.2                                 arm64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev                        7.1.3-1+cuda10.2                                 arm64        Python 3 development package for TensorRT
ii  tensorrt                                      7.1.3.0-1+cuda10.2                               arm64        Meta package of TensorRT
ii  uff-converter-tf                              7.1.3-1+cuda10.2                                 arm64        UFF converter for TensorRT package

**Comment by wang-xinyu** [comment]
pls pull the latest commit and try again

**Comment by bobby20180331** [comment]
yes.I build the TensorRT yolov4 successful after update the tensorrtx to the following commit.
native buid on AGX Xavier.:
commit 856523789052449c251519105fb220872f470c72

**Comment by bobby20180331** [comment]
"commit  856523789052449c251519105fb220872f470c72"

**Comment by bobby20180331** [comment]
commit "856523789052449c251519105fb220872f470c72"
