### ISSUE TITLE
请问为什么pt模型要转为wts模型，转换的逻辑是什么？

### ISSUE THREAD

**Issue by Yaoxingtian** [wang-xinyu/tensorrtx#337]
您好，我有个疑问如标题，可以麻烦帮我解答一下吗，谢谢！

**Comment by wang-xinyu** [comment]
看下这个教程 https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/getting_started.md

就是为了把权重读进来，传入tensorrt的接口。

**Comment by Yaoxingtian** [comment]
请问这是tensorrt官方的转换方法吗 ？

**Comment by wang-xinyu** [comment]
官方sample有类似的例子
