### ISSUE TITLE
IBuilderConfig* config = builder->createBuilderConfig(); 段错误

### ISSUE THREAD

**Issue by 490163917** [wang-xinyu/tensorrtx#34]
你好，我在执行命令./yolov4 -s，在运行到 IBuilderConfig* config = builder->createBuilderConfig()报段错误，请问是什么原因呢？

**Comment by 490163917** [comment]
Environment
TensorRT Version: 7.0.0.11
GPU Type: 2080Ti
CUDA Version: 10.0
CUDNN Version: 7.6.5
Operating System + Version: ubuntu 18.04

**Comment by wang-xinyu** [comment]
改代码了吗

**Comment by 490163917** [comment]
1.没有改任何代码，yolov4.wts放在指定目录；
2.我试了TensorRT Version: 7.0.0.11和 TensorRT Version: 6.0都是会在IBuilderConfig* config = builder->createBuilderConfig()报段错误。
3.把IBuilderConfig* config = builder->createBuilderConfig()去掉以后，正常执行loadWeights函数，但在network->addConvolutionNd ，conv1->setStrideNd(DimsHW{s, s})，conv1->setPaddingNd(DimsHW{p, p})等语句会报段错误，如果将其替换成network->addConvolution，conv1->setStride(DimsHW{s, s})，conv1->setPadding(DimsHW{p, p})，则不会；
4.我尝试将yolov4中的部分tensorrt接口换成yolov3-spp中的接口，主要是以下几个：
network->addConvolutionNd替换成network->addConvolution，conv1->setStrideNd(DimsHW{s, s})替换成conv1->setStride(DimsHW{s, s})，conv1->setPaddingNd(DimsHW{p, p})替换成conv1->setPadding(DimsHW{p, p})，去掉  IBuilderConfig* config = builder->createBuilderConfig()，将  config->setMaxWorkspaceSize(16 * (1 << 20))替换成 builder->setMaxWorkspaceSize(1 << 20); 
将  config->setMaxWorkspaceSize(16 * (1 << 20))替换成 builder->setMaxWorkspaceSize(1 << 20); 
将config->setFlag(BuilderFlag::kFP16)替换成builder->setFp16Mode(true); 将ICudaEngine* engine = builder->buildEngineWithConfig(*network, *config)替换成ICudaEngine* engine = builder->buildCudaEngine(*network)。执行到ICudaEngine* engine = builder->buildCudaEngine(*network)，会报如下错误：
yolov4: ../builder/cudnnBuilderGraphNodes.cpp:229: virtual nvinfer1::builder::Format::Type nvinfer1::builder::PluginV2Node::getUniformFormats() const: Assertion `f != Format::kNONE && "PluginNode supported formats do not match any expected format."' failed.

**Comment by wang-xinyu** [comment]
这些接口应该没问题的，我这里跑都没问题，我感觉还是路径问题，最开始没有任何改动情况下，报的错我看看

**Comment by 490163917** [comment]
> 这些接口应该没问题的，我这里跑都没问题，我感觉还是路径问题，最开始没有任何改动情况下，报的错我看看
什么都没有改,执行就就报:Segmentation fault。加了打印语句，发现段错误发生在这句IBuilderConfig* config = builder->createBuilderConfig()。路径问题你是指的权重路径吗？我看代码上权重路径是写的："../yolov4.wts"，我确认没有问题。绕过IBuilderConfig* config = builder->createBuilderConfig()，后面也是能正常加载权重。

**Comment by wang-xinyu** [comment]
试试加sudo执行呢

**Comment by 490163917** [comment]
> 试试加sudo执行呢
执行的时候有加sudo,我怀疑是Tensorrt编译有问题。

**Comment by wang-xinyu** [comment]
你这问题挺奇怪，tensorrt装的是ubuntu18.04的版本吗

**Comment by 490163917** [comment]
是ubuntu18.04的版本，我再找找具体是什么原因。

**Comment by wang-xinyu** [comment]
之前有人用xavier nx跑过，tensorrt7.1， cuda10.2，ubuntu18.04，也能跑

**Comment by 490163917** [comment]
我最近也会把这个代码弄到Xavier nx。

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/issues/23
这个人在nx跑通了

**Comment by datouready** [comment]
请问Segmentation fault是什么问题呢？

**Comment by wang-xinyu** [comment]
@datouready 这个问题很老了，你可以开一个新的issue，把具体问题和环境描述一下
