### ISSUE TITLE
YoloV5l giving very bad results on custom dataset.

### ISSUE THREAD

**Issue by yogidosalwar** [wang-xinyu/tensorrtx#340]
@wang-xinyu , 
I have trained model on a single class as per your instructions  and it's giving 90% accuracy, but when the model is converted into TensorRT then it's giving very bad results.
 
Thank you.

**Comment by wang-xinyu** [comment]
pls try the official 3.0 or 3.1 model first,  and compare your model with the official one

**Comment by yogidosalwar** [comment]
@wang-xinyu   Thank you so much for the quick response.
I have tried the official 3.0 and 3.1 model, it is perfectly running and giving good result after tensor conversion. The problem arises  after tensor conversion of  customised model (single class). can you please guide me?

Thank you...

**Comment by yogidosalwar** [comment]
@wang-xinyu 

I have trained other two models and that model giving good results after conversion of tensorrt, but the single class model is not giving good results after Tensorrt conversion.

Thank you...

**Comment by wang-xinyu** [comment]
single class doesn't matter.

you need compare your model with the official ones, especially to check if it is using leakyrelu or hardswish.

**Comment by yogidosalwar** [comment]
Hi @wang-xinyu , Thank yo so much for the quick response.
I have compared my model with official ones, it is using Hardswish. 

Thank you..

**Comment by yogidosalwar** [comment]
@wang-xinyu 
Hi @wang-xinyu , Thank yo so much for the quick response.
I have compared my model with official ones, it is using leakyrelu.

Thank you..

**Comment by wang-xinyu** [comment]
leakyrelu is used by yolov5 2.0,  3.0 is using hardswish.

you need checkout the v2.0 commit of this repo, refer to the readme of tensorrtx/yolov5
