### ISSUE TITLE
请问有人遇到 yolov5s 的onnx模型转trt int8不出框的情况吗？不管是yolov5 3.1的版本还是2.0的，都不出框。。。

### ISSUE THREAD

**Issue by Wulingtian** [wang-xinyu/tensorrtx#342]
![IMG_20201231_094134](https://user-images.githubusercontent.com/20986422/103390355-e9625500-4b4e-11eb-99d8-28deae646289.jpg)

有onnx转trt int8的推理速度还是很快的，5ms左右，就是不出框。。。
有人能一起交流一下吗？

**Comment by lzcchl** [comment]
我也遇到了，我多次实验，发现在jetson会有问题，在x86检测没问题，大概定位可能是tensorrt的版本导致的。

**Comment by Wulingtian** [comment]
> 我也遇到了，我多次实验，发现在jetson会有问题，在x86检测没问题，大概定位可能是tensorrt的版本导致的。

你是做了int8量化导致的吗？

**Comment by Wulingtian** [comment]
> 我也遇到了，我多次实验，发现在jetson会有问题，在x86检测没问题，大概定位可能是tensorrt的版本导致的。

我onnx转trt fp16是正常出框的

**Comment by sonixixi** [comment]
最新的提交可以了

**Comment by Wulingtian** [comment]
> 最新的提交可以了

最新版本的trt可以了？

**Comment by sonixixi** [comment]
up 主不是更新了yolov5 4.0 版本的么，trt7.1 之前不行， 现在可以了，量化。或者你checkout 到 2abc7b837575311db98f8c2e07a0c2057fc51f20 这个提交也是可以的。

**Comment by Wulingtian** [comment]
没看到有int8量化啊

**Comment by Wulingtian** [comment]
> up 主不是更新了yolov5 4.0 版本的么，trt7.1 之前不行， 现在可以了，量化。或者你checkout 到 [2abc7b8](https://github.com/wang-xinyu/tensorrtx/commit/2abc7b837575311db98f8c2e07a0c2057fc51f20) 这个提交也是可以的。

没看到有int8量化啊

**Comment by sonixixi** [comment]
yolov5的得自己加，基本上就是赋值 yolov3的量化代码

**Comment by Wulingtian** [comment]
> yolov5的得自己加，基本上就是赋值 yolov3的量化代码

我的是onnx转trt int8，但是不出框

**Comment by sonixixi** [comment]
直接用这个工程的呗

**Comment by Wulingtian** [comment]
> 直接用这个工程的呗

我已经有一个类似的工程了，int8量化正常出框，现在想知道为啥onnx 转trt int8 不出框

**Comment by Wulingtian** [comment]
> 直接用这个工程的呗
你有试过onnx转trt int8吗？

**Comment by sonixixi** [comment]
没试过

**Comment by Wulingtian** [comment]
> 没试过

老哥加个微信，我的微信号：willer199311

**Comment by abcilike** [comment]
onnx->trt int8  leakyrelu量化不稳定，换成relu就可以用了

**Comment by Wulingtian** [comment]
> onnx->trt int8 leakyrelu量化不稳定，换成relu就可以用了
那4.0的SILU激活函数可以用吗？

**Comment by xiaoche-24** [comment]
> > 没试过
> 
> 老哥加个微信，我的微信号：willer199311

老哥，我从onnx转成engine，采用./yolov5_det -d ../yolov5s.engine ../../yolov3-spp/samples/推理，但是报错了：
`yolov5_det: /home/test/lixiaojun/yolov5-master-vision/tensorrtx-master/yolov5/yolov5_det.cpp:62: void prepare_buffers(nvinfer1::ICudaEngine*, float**, float**, float**): Assertion `inputIndex == 0' failed.`
可以请问你是怎么改的，可以直接在这上面运行嘛

**Comment by FunnyWii** [comment]
> > > 没试过
> > 
> > 
> > 老哥加个微信，我的微信号：willer199311
> 
> 老哥，我从onnx转成engine，采用./yolov5_det -d ../yolov5s.engine ../../yolov3-spp/samples/推理，但是报错了： `yolov5_det: /home/test/lixiaojun/yolov5-master-vision/tensorrtx-master/yolov5/yolov5_det.cpp:62: void prepare_buffers(nvinfer1::ICudaEngine*, float**, float**, float**): Assertion `inputIndex == 0' failed.` 可以请问你是怎么改的，可以直接在这上面运行嘛

一样，请问后来咋解决的啊？我也是 `void prepare_buffers(nvinfer1::ICudaEngine*, float**, float**, float**): Assertion `inputIndex == 0' failed.`
