### ISSUE TITLE
error when convering yolov3

### ISSUE THREAD

**Issue by niuwenju** [wang-xinyu/tensorrtx#347]
when runing `sudo ./yolov3 -s`

got

Loading weights: ../yolov3.wts
[01/05/2021-18:53:08] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov3: /media/nvidia/disk11/tensorrtx/yolov3/yolov3.cpp:170: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted

**Comment by yang-gis** [comment]
> when runing `sudo ./yolov3 -s`
> 
> got
> 
> Loading weights: ../yolov3.wts
> [01/05/2021-18:53:08] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
> yolov3: /media/nvidia/disk11/tensorrtx/yolov3/yolov3.cpp:170: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
> Aborted

same to you. have you sloved this problem?

**Comment by tz3** [comment]
Did you have a luck with this problem?

**Comment by yang-gis** [comment]
> Did you have a luck with this problem?

I have solved it!

**Comment by Kimiaoo** [comment]
> > Did you have a luck with this problem?
> 
> I have solved it!

Could you please give some suggestions? I am still struggling in this problem.

**Comment by ZhangwenguangHikvision** [comment]
> > Did you have a luck with this problem?
> 
> I have solved it!

大佬，怎么解决的啊？我也碰到了。

**Comment by wang-xinyu** [comment]
you might try using yolov3 archive branch

**Comment by yang-gis** [comment]
> > > Did you have a luck with this problem?
> > 
> > 
> > I have solved it!
> 
> 大佬，怎么解决的啊？我也碰到了。

你好这么晚回复你，不知道你解决了没有。我后面解决了，是因为我用错了模型，老版的要用老版的模型

**Comment by SokPhanith** [comment]
Hello, I got thsi too. Who can slove it ?
