### ISSUE TITLE
为什么我训练的crnn模型用up主这个代码，预测结果的和python下预测结果完全不一样，有什么需要注意的地方吗？

### ISSUE THREAD

**Issue by swithmn1** [wang-xinyu/tensorrtx#348]

**Comment by wang-xinyu** [comment]
先运行官方模型，make sure it works, and then compare your own model with the official one.

**Comment by GalSang17** [comment]
> _No description provided._

My python results are completely different from engine inference results, have you solved this problem? @swithmn1 @wang-xinyu
