### ISSUE TITLE
Great job! I have a question about it.

### ISSUE THREAD

**Issue by Byronnar** [wang-xinyu/tensorrtx#35]
真的非常棒的项目,请问这个项目能做成 只加载一次engine模型,然后挂在后台,有图片传进来就开始预测没图片就等待么? 因为我计算了一下时间,加载模型用了7s, 预测一张图片才8ms...
'''
载入模型时间: 7645ms
第几张图片: 1  图片文件名: zidane.jpg
图像处理时间: 109ms
Time compute: 8ms
第几张图片: 2  图片文件名: bus.jpg
图像处理时间: 48ms
加载模型后的推理时间: 8ms
247.561, 168.353, 32.9542, 46.0337, 0.794903, 0, 
'''
c++不太熟悉, 期待您的回复.

**Comment by wang-xinyu** [comment]
可以啊，保留上下文环境（主要是context，engine，runtime），再调用推理接口，就可以了。接口需要自己去封装。这个项目主要目的是跑通tensorrt网络定义和推理流程。

**Comment by Byronnar** [comment]
好的,感谢您这么快的回复!我先自己尝试一下,谢谢!
