### ISSUE TITLE
yolov3 -s

### ISSUE THREAD

**Issue by yang-gis** [wang-xinyu/tensorrtx#351]
yjy@yjy-OptiPlex-7071:~/tensorrtx/yolov3/build$ sudo ./yolov3 -s
Loading weights: ../yolov3.wts
[01/08/2021-14:16:46] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov3: /home/yjy/tensorrtx/yolov3/yolov3.cpp:203: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
已放弃

**Comment by wang-xinyu** [comment]
yolov3.wts 有问题，按照readme重新操作一下，或者从model zoo下载.wts试试

**Comment by yang-gis** [comment]
> yolov3.wts 有问题，按照readme重新操作一下，或者从model zoo下载.wts试试

作者你好，感谢您的回复。我在用你的这个yolov3发现以下问题：
（1）生成wts的py文件与您给的python版本的yolo对应不上了。很蛋疼，原始的是
import struct
import sys
from models import *
from utils.utils import *

model = Darknet('cfg/yolov3.cfg', (608, 608))
weights = sys.argv[1]
device = torch_utils.select_device('0')
if weights.endswith('.pt'):  # pytorch format
    model.load_state_dict(torch.load(weights, map_location=device)['model'])
else:  # darknet format
    load_darknet_weights(model, weights)
model = model.eval()

f = open('yolov3.wts', 'w')
f.write('{}\n'.format(len(model.state_dict().keys())))
for k, v in model.state_dict().items():
    vr = v.reshape(-1).cpu().numpy()
    f.write('{} {} '.format(k, len(vr)))
    for vv in vr:
        f.write(' ')
        f.write(struct.pack('>f',float(vv)).hex())
    f.write('\n')
但现在的repo根本就没有utils.utils，此外也没有model = Darknet('cfg/yolov3.cfg', (608, 608))，因为没有model.py文件了。
然后我又试着用另一个分支achive的老版本yolov3,发现运行gen_wts.py会报找不到mode.yolo的错误，这个model是在新的分支master里面，这个model是一个文件夹了，而不是老版本中的model.py。
总之非常的乱。
（2）然后我实在没办法就把gen_wts.py文件修改了才能顺利生成yolov3.wts，如下：
import struct
import torch
import sys
from models import *
from utils.torch_utils import select_device

weights = sys.argv[1]
device = select_device('0')
model= torch.load(weights, map_location=device)['model']

model = model.eval()

f = open('yolov3.wts', 'w')
f.write('{}\n'.format(len(model.state_dict().keys())))
for k, v in model.state_dict().items():
    vr = v.reshape(-1).cpu().numpy()
    f.write('{} {} '.format(k, len(vr)))
    for vv in vr:
        f.write(' ')
        f.write(struct.pack('>f',float(vv)).hex())
    f.write('\n')

（3）虽然修改后生成了wts文件，但后续转engine时就爆出我提问的错误了。感觉作者您说的有道理应该是wts转的问题，但我不知如何解决，太TM乱了。我脑子都要炸了

**Comment by yang-gis** [comment]
> yolov3.wts 有问题，按照readme重新操作一下，或者从model zoo下载.wts试试

大佬我已經试过了您model zoo中的wts，确信是可以成功运行的。我了一下你给的wts文件大小600多M，我自己生成的wts只有550M，不知道出了什么问题。感觉是生成wts的脚本问题，希望大佬能够给予帮助。谢谢

**Comment by wang-xinyu** [comment]
This was using yolov3 archive branch, which is darknet-style. So use archive branch of yolov3.

Now the yolov3 master branch had been updated to yolov5-style.

**Comment by yang-gis** [comment]
> This was using yolov3 archive branch, which is darknet-style. So use archive branch of yolov3.
> 
> Now the yolov3 master branch had been updated to yolov5-style.

大佬我知道你的意思，关键是你yolov3的gen_wts.py并没有跟着更新，我也是小白修改不好。此外试了用archive分支的gen_wts.py会报错找不到models.yolo，而model.yolo是在master分支里面的，所以很奇怪。

**Comment by wang-xinyu** [comment]
gen_wts.py 不需要models.yolo.....

这里yolov3不会跟着ultralytics更新了，没有意义，ultralytics后面也主要维护yolov5.

如果用v3，就用archive分支。

archive 分支用这里的gen_wts.py肯定没问题，你再试试

**Comment by yang-gis** [comment]
> gen_wts.py 不需要models.yolo.....
> 
> 这里yolov3不会跟着ultralytics更新了，没有意义，ultralytics后面也主要维护yolov5.
> 
> 如果用v3，就用archive分支。
> 
> archive 分支用这里的gen_wts.py肯定没问题，你再试试

谢谢大佬。那我现在怀疑是我下载的yolov3.pt文件有问题，这个yolov3.pt难道是新的master分支的？archive分支的yolov3.pt文件应该是darknet style的

**Comment by wang-xinyu** [comment]
https://github.com/ultralytics/yolov3/releases/tag/v8

从这里下载assets

**Comment by yang-gis** [comment]
> https://github.com/ultralytics/yolov3/releases/tag/v8
> 
> 从这里下载assets

好的非常感谢大佬不厌其烦的回复。大佬。顺便请教一下大佬，如果我只要识别图像中的单类，重新训练的话需要做哪些修改？

**Comment by wang-xinyu** [comment]
训练那边项目有教程

这边只需要改一下class num, readme里面有说明

**Comment by yang-gis** [comment]
> 训练那边项目有教程
> 
> 这边只需要改一下class num, readme里面有说明

谢谢大佬。
