### ISSUE TITLE
YOLOV5在RTX3080上报错

### ISSUE THREAD

**Issue by cyanjustice** [wang-xinyu/tensorrtx#353]
TensorRT版本为7.2.1, 序列化模型时unsupported SM错误。2080TI上没问题，请问是哪边需要配置一下吗？

**Comment by wang-xinyu** [comment]
用最新版本的cuda和trt试试

**Comment by cyanjustice** [comment]
环境问题，解决了

**Comment by shihanyu** [comment]
能具体讲讲吗？我也是这个问题，环境是直接用提供的docker做的，但还是有这个问题。我的是3090

**Comment by wang-xinyu** [comment]
maybe need cuda11.1+ for rtx30xx

**Comment by shihanyu** [comment]
> maybe need cuda11.1+ for rtx30xx

谢谢，我来试一下
