### ISSUE TITLE
关于context->executeV2函数占用显存问题

### ISSUE THREAD

**Issue by ayicherry** [wang-xinyu/tensorrtx#354]
您好：
       有个问题想请教一下，就是TensorRT C++的代码中，执行推断的函数context->executeV2或者context->enqueueV2在2080Ti的GPU卡上会占用一定的显存（我测试yolov5，占用了20M），但是在GTX 1660卡上面不会占用任何显存，两者用的一摸一样的代码，一样的CUDA版本，不知道您有没有遇到过该问题。
       现在在2080Ti上，每推断一次都多占用20M，并且又不会释放，导致程序无法长时间运行。

**Comment by wang-xinyu** [comment]
可能显存没稳定，长时间跑跑试试。应该没有内存泄露。
