### ISSUE TITLE
How to change yolov5 to support int8 calibration?

### ISSUE THREAD

**Issue by BLOO69** [wang-xinyu/tensorrtx#357]
Could i ask what changes are to be made? I placed the 2 files(calibrator.cpp and calibrator.h) in the yolov5 folder and #included both files in yolov5.cpp. I also added my own dataset and placed it in build folder and renamed "coco_calib".  I also added this block of code in yolov5.cpp.
Thank You @wang-xinyu !

#elif defined(USE_INT8)
std::cout << "Your platform support int8: " << (builder->platformHasFastInt8() ? "true" : "false") << std::endl;
assert(builder->platformHasFastInt8());
config->setFlag(BuilderFlag::kINT8);
Int8EntropyCalibrator2 *calibrator = new Int8EntropyCalibrator2(1, INPUT_W, INPUT_H, "./coco_calib/", "int8calib.table", INPUT_BLOB_NAME);
config->setInt8Calibrator(calibrator);

### Error
[ 50%] Built target myplugins
Scanning dependencies of target yolov5
[ 75%] Building CXX object CMakeFiles/yolov5.dir/yolov5.cpp.o
In file included from /home/student/yolov5-tensorrt/tensorrtx/yolov5/yolov5.cpp:7:0:
/home/student/yolov5-tensorrt/tensorrtx/yolov5/calibrator.cpp: In member function ‘virtual bool Int8EntropyCalibrator2::getBatch(void**, const char**, int)’:
/home/student/yolov5-tensorrt/tensorrtx/yolov5/calibrator.cpp:48:65: error: too many arguments to function ‘cv::Mat preprocess_img(cv::Mat&)’
cv::Mat pr_img = preprocess_img(temp, input_w_, input_h_);
^
compilation terminated due to -Wfatal-errors.
CMakeFiles/yolov5.dir/build.make:62: recipe for target 'CMakeFiles/yolov5.dir/yolov5.cpp.o' failed
make[2]: *** [CMakeFiles/yolov5.dir/yolov5.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yogidosalwar** [comment]
Hey @wang-xinyu ,

I am unable to download calibration images (YoloV3) from your given link.
https://pan.baidu.com/s/1GOm_-JobpyLMAqZWCDUhKg

Please provide me valid link.

Thank you.

**Comment by wang-xinyu** [comment]
yolov5 now supporting int8
