### ISSUE TITLE
yolov5 v4.0 .wts generating bug

### ISSUE THREAD

**Issue by Larry-Zheng** [wang-xinyu/tensorrtx#358]
model = torch.load('weights/yolov5s.pt', map_location=device)['model'].float()  # load to FP32
  File "E:\python\lib\site-packages\torch\serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "E:\python\lib\site-packages\torch\serialization.py", line 852, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'

**Comment by wang-xinyu** [comment]
refer to the readme....
gen_wts.py should run under ultralytics/yolov5
