### ISSUE TITLE
Is the conversion effect of yolov4 consistent with darknet?

### ISSUE THREAD

**Issue by ou525** [wang-xinyu/tensorrtx#36]
Thank you very much for your work！

**Comment by wang-xinyu** [comment]
The model output should be same as darknet,  the nms process may have a little difference.
You can try several images and compare the result.

**Comment by ou525** [comment]
Whether the implementation of maxpool is different, will it affect？

**Comment by wang-xinyu** [comment]
The maxpool in tensorrt is same as pytorch's maxpool. I don't know if it's same as darknet's maxpool.

why do you think maxpool is different?

**Comment by ou525** [comment]
The following is the darknet maxpool implementation code

maxpool_layer make_maxpool_layer(int batch, int h, int w, int c, int size, int stride_x, int stride_y, int padding, int maxpool_depth, int out_channels, int antialiasing, int avgpool, int train)
{
    maxpool_layer l = { (LAYER_TYPE)0 };
    l.avgpool = avgpool;
    if (avgpool) l.type = LOCAL_AVGPOOL;
    else l.type = MAXPOOL;
    l.train = train;

    const int blur_stride_x = stride_x;
    const int blur_stride_y = stride_y;
    l.antialiasing = antialiasing;
    if (antialiasing) {
        stride_x = stride_y = l.stride = l.stride_x = l.stride_y = 1; // use stride=1 in host-layer
    }

    l.batch = batch;
    l.h = h;
    l.w = w;
    l.c = c;
    l.pad = padding;
    l.maxpool_depth = maxpool_depth;
    l.out_channels = out_channels;
    if (maxpool_depth) {
        l.out_c = out_channels;
        l.out_w = l.w;
        l.out_h = l.h;
    }
    else {
        l.out_w = (w + padding - size) / stride_x + 1;
        l.out_h = (h + padding - size) / stride_y + 1;
        l.out_c = c;
    }
    l.outputs = l.out_h * l.out_w * l.out_c;
    l.inputs = h*w*c;
    l.size = size;
    l.stride = stride_x;
    l.stride_x = stride_x;
    l.stride_y = stride_y;
    int output_size = l.out_h * l.out_w * l.out_c * batch;

**Comment by wang-xinyu** [comment]
I'm not checking the darknet implementation, you need compare it yourself.
closing this old thread.
