### ISSUE TITLE
 time consuming

### ISSUE THREAD

**Issue by gaooooke** [wang-xinyu/tensorrtx#360]
auto start = std::chrono::system_clock::now();
IRuntime* runtime = createInferRuntime(gLogger);
assert(runtime != nullptr);
ICudaEngine* engine = runtime->deserializeCudaEngine(trtModelStream, size);
assert(engine != nullptr);
IExecutionContext* context = engine->createExecutionContext();
assert(context != nullptr);
delete[] trtModelStream;
auto end = std::chrono::system_clock::now();
std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;

Why is the above code particularly time-consuming ？I test about 200-300ms in gtx1070

**Comment by wang-xinyu** [comment]
Normal...
This is loading and deserializing trt model. which is time consuming.
