### ISSUE TITLE
YOLOV5在RTX3080上batchsize大于1的半精度模式下build engine报错

### ISSUE THREAD

**Issue by cyanjustice** [wang-xinyu/tensorrtx#364]
使用最新版的tensorRT7.2.2，
yolov5经过反复测试，以下情况build engine都OK：
RTX2080TI，batchsize任意值，FP16,FP32情况下OK
RTX3080，batchsize=1，FP16,FP32情况下OK
RTX3080, batchsize任意值，FP32情况下OK。

只有在RTX3080，batchsize>1，FP16的情况下出现以下报错：
![image](https://user-images.githubusercontent.com/46018705/105138792-5a82a000-5b30-11eb-8caa-a5734df57f70.png)

**Comment by wang-xinyu** [comment]
那估计3080驱动或者cuda的bug

**Comment by cyanjustice** [comment]
我仔细查了一下，问题出在C3模块上，yolov5预训练模型使用的是C3_EXPERIMENTAL模块，使用了3*1和1*3的卷积核，在yolov5s以及yolov5l上输出通道为64的倍数不会报错，而yolov5m为96的倍数，yolov5x为160倍数就出现这种报错，而且只会出现在3080，FP16模式下。。。
