### ISSUE TITLE
arcface convert to wrts error

### ISSUE THREAD

**Issue by c7934597** [wang-xinyu/tensorrtx#368]
arcface的地方，第一區塊執行python gen_wts.py時會有錯誤，
貌似insightface原始碼face_model.py有更新

class FaceModel:
    def __init__(self, ctx_id, model_prefix, model_epoch, use_large_detector=False):

這邊有多model_prefix, model_epoch參數，不過現在你的程式gen_wts.py裡面的model = face_model.FaceModel(args)只有一個參數，轉不出wts檔，謝謝。

**Comment by wang-xinyu** [comment]
可以根据我的arcface修改时间，找一下insightface以前的commit记录，checkout回去
