### ISSUE TITLE
resnet18精度损失

### ISSUE THREAD

**Issue by ljh9999** [wang-xinyu/tensorrtx#369]
作者您好，首先非常感谢您开源的代码。我在做二分类任务时，用了你的resnet18工程。但是在序列化转engine的时候，发现自己训练出来的pt模型和engine之间的精度差距比较大，请问这可能是什么原因导致的呢？谢谢

**Comment by ljh9999** [comment]
训练的时候用的pytorch的分布式训练和单GPU训练，效果都有不同程度的精度损失

**Comment by wang-xinyu** [comment]
看一下预处理有没有加

**Comment by ljh9999** [comment]
训练的时候有图像归一化操作：transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])。测试的时候没有

**Comment by wang-xinyu** [comment]
测试的时候肯定也要归一化的，c++这边也需要做

**Comment by ljh9999** [comment]
您提供的代码里只有个除以255的操作，归一化得自己补是吧？

**Comment by wang-xinyu** [comment]
我这里的resnet18，输入是ones，没有除以255，  归一化要自己加

**Comment by jimmyflycv** [comment]
> 我这里的resnet18，输入是ones，没有除以255， 归一化要自己加

how about format of the input data?
we could not find it with only ones.
Any example code here?

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/5332e0e46c3884192b19a6a9b5ee63f209070b44/resnet/resnet18.cpp#L310-L313

@jimmyflycv

**Comment by jimmyflycv** [comment]
> https://github.com/wang-xinyu/tensorrtx/blob/5332e0e46c3884192b19a6a9b5ee63f209070b44/resnet/resnet18.cpp#L310-L313
> 
> @jimmyflycv

Thanks very much for your reply!
I mean when i test a jpg image, the result is different from pytorch model.
Any image file input demo available?
I found pytorch-transforms.ToTensor() could not be implemented with c++/opencv...

**Comment by wang-xinyu** [comment]
yolo, retinafae, arcface, etc. in this repo, all these using image as input.
