### ISSUE TITLE
大神有考虑RepVGG么？最近刚看完论文

### ISSUE THREAD

**Issue by AIpakchoi** [wang-xinyu/tensorrtx#370]

**Comment by wang-xinyu** [comment]
没听说过啊

**Comment by AIpakchoi** [comment]
@wang-xinyu 清华和旷视最近的一篇论文，infer阶段把一些branch和BN融合到卷积层，3*3卷积一卷到底，精度、时间、FLOPs非常不错。
《RepVGG: Making VGG-style ConvNets Great Again》
https://arxiv.org/abs/2101.03697
https://github.com/megvii-model/RepVGG
不过团队好像还在升级优化中。

**Comment by wang-xinyu** [comment]
pls find repvgg in this repo.
