### ISSUE TITLE
   int NetData[4]; 为什么 pluginMultidata[0].length = 3 而不是4呢？

### ISSUE THREAD

**Issue by csyangbinbin** [wang-xinyu/tensorrtx#371]
https://github.com/wang-xinyu/tensorrtx/blob/5332e0e46c3884192b19a6a9b5ee63f209070b44/yolov5/common.hpp#L295

**Comment by wang-xinyu** [comment]
这个字段好像没用到，看下YoloPluginCreator::createPlugin()的实现
