### ISSUE TITLE
about the yolov5 trt memory by python

### ISSUE THREAD

**Issue by ruiming46zrm** [wang-xinyu/tensorrtx#372]
hello ,  I test a lot  using  python to run trt yolov5 model ,   cpu memory rise 3-4 G,  gpu memory rise 2.5G when yolov5s and  3.8G when yolov5x.

it's quite a lot .  cpp do not cost half of it.

have you test the memory in your python code? is there any method to reduce this cost? 

thank you for your replay.

**Comment by wang-xinyu** [comment]
we have checked it, the memory nearly the same for python and c++.

**Comment by isomatical** [comment]
Met the same problem. Fixed it by rewrite the python api by invoking the cpp api with ctypes.
