### ISSUE TITLE
cannot make reinaface

### ISSUE THREAD

**Issue by HoangTienDuc** [wang-xinyu/tensorrtx#373]
hello @wang-xinyu  i follow your installation, but i cannot make retinaface

```
/data/Downloads/tensorrtx/retinaface/calibrator.cpp:4:10: fatal error: opencv2/dnn/dnn.hpp: No such file or directory
 #include <opencv2/dnn/dnn.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/retina_r50.dir/build.make:62: recipe for target 'CMakeFiles/retina_r50.dir/calibrator.cpp.o' failed
make[2]: *** [CMakeFiles/retina_r50.dir/calibrator.cpp.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/retina_r50.dir/all' failed
make[1]: *** [CMakeFiles/retina_r50.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by xxxpsyduck** [comment]
build opencv first

**Comment by 1124676457** [comment]
我也是一样的报错，但我是@xxxpsyduck ，但我安装了opencv了，不过是4.1的。是不是版本太高了

**Comment by xxxpsyduck** [comment]
@1124676457 How do you install opencv? It must be compiled from source and install with `make install`. I use the latest version with no problem

**Comment by 1124676457** [comment]
我是在jetson nano上跑的，本身自带有opencv4.1，是编译过的，也能查看版本信息，不知道为啥会报错 @xxxpsyduck

**Comment by wang-xinyu** [comment]
make sure you have installed the opencv 4.1 dnn module.

**Comment by HoangTienDuc** [comment]
thank for your help. after install opencv freom source, i got another error
```
Loading weights: ../retinaface.wts
Your platform support int8: 1
Building engine, please wait for a while...
reading calib cache: r50_int8calib.table
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
[1]    31344 abort (core dumped)  ./retina_r50 -s
```
Could you guide me how to fix it? What wrong with it?

**Comment by wang-xinyu** [comment]
Most of the models in this repo, including retinaface, are using Dims3 as input, i.e. CHW.  The batch dimension is not fixed.

refer to the readme of retinaface, you can config `BATCH_SIZE` to try multi batch or dynamic batch.

**Comment by constantinfite** [comment]
@wang-xinyu I am encountering the same issue, how do you check that opencv 4.1 dnn module is installed ? Thanks

**Comment by wang-xinyu** [comment]
@constantinfite 
If you were using apt install opencv, you can check with dpkg -l

```
$ dpkg -l | grep dnn
ii  libcudnn7                                                    7.6.5.32-1+cuda10.0                                 amd64        cuDNN runtime libraries
ii  libcudnn7-dev                                                7.6.5.32-1+cuda10.0                                 amd64        cuDNN development libraries and headers
ii  libopencv-dnn-dev:amd64                                      3.3.1-xenial1.4                                     amd64        development files for libopencv-dnn3.3
ii  libopencv-dnn3.3:amd64                                       3.3.1-xenial1.4                                     amd64        computer vision Machine Learning library
```

If compiled opencv from src, then search `dnn.hpp` under your install dir.

**Comment by constantinfite** [comment]
@wang-xinyu I run `apt-get install libopencv-dev -y` and it's working 
But once it's build I don't understand this command `sudo ./yolov5 -s yolov5s.wts yolov5s.engine s`
I don't have any folder yolov5 in my folder build. Only 5 files and 1 repository CmakeFiles

Do you have an idea ?

**Comment by wang-xinyu** [comment]
@constantinfite if you found issues with yolov5, pls start a new thread.

**Comment by wang-xinyu** [comment]
> make sure you have installed the opencv 4.1 dnn module.

**Comment by abuelgasimsaadeldin** [comment]
Hi guys, I am currently facing this issue and ```apt-get install libopencv-dev -y``` did not work to solve the issue in my case, would you mind sharing how you overcame this problem?

**Comment by shliang0603** [comment]
> @constantinfite
> If you were using apt install opencv, you can check with dpkg -l
> 
> ```
> $ dpkg -l | grep dnn
> ii  libcudnn7                                                    7.6.5.32-1+cuda10.0                                 amd64        cuDNN runtime libraries
> ii  libcudnn7-dev                                                7.6.5.32-1+cuda10.0                                 amd64        cuDNN development libraries and headers
> ii  libopencv-dnn-dev:amd64                                      3.3.1-xenial1.4                                     amd64        development files for libopencv-dnn3.3
> ii  libopencv-dnn3.3:amd64                                       3.3.1-xenial1.4                                     amd64        computer vision Machine Learning library
> ```
> 
> If compiled opencv from src, then search `dnn.hpp` under your install dir.


@wang-xinyu My system is Ubuntu18.04, when I add `sudo add-apt-repository ppa:timsc/opencv-3.3`, error: can not add PPA：“'The PPA don't support bionic'”。

**Comment by wang-xinyu** [comment]
@shliang0603 you can try `sudo add-apt-repository -y ppa:timsc/opencv-3.4`
