### ISSUE TITLE
make失败

### ISSUE THREAD

**Issue by 1124676457** [wang-xinyu/tensorrtx#375]
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
In file included from /home/dyli/yolov5/yololayer.cu:3:0:
/home/dyli/yolov5/utils.h:9:10: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at myplugins_generated_yololayer.cu.o.Debug.cmake:219 (message):
  Error generating
  /home/dyli/yolov5/build/CMakeFiles/myplugins.dir//./myplugins_generated_yololayer.cu.o

CMakeFiles/myplugins.dir/build.make:63: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
you need install opencv

**Comment by qiuminghilllittlewan** [comment]
作者你好，我也出现了这个问题，但是我确定我的opencv是装好了的，是不是路径没找到，我需要修改makefile文件之类的吗，如果是的话，怎么添加我的opencv路径呢，谢谢

**Comment by wang-xinyu** [comment]
@qiuminghilllittlewan 学习一下cmake就知道了

**Comment by qiuminghilllittlewan** [comment]
好的，多谢

**Comment by Haruka0522** [comment]
The CMakeLists.txt has a mistake.
It works fine if you change  from `include_directories(OpenCV_INCLUDE_DIRS)` to `include_directories(${OpenCV_INCLUDE_DIRS})`

**Comment by rymzt** [comment]
I sent PullRequest #377.

**Comment by dcdethan** [comment]
Hi,please use this:
sudo apt install libopencv-dev
It works for me.

**Comment by dcdethan** [comment]
> 作者你好，我也出现了这个问题，但是我确定我的opencv是装好了的，是不是路径没找到，我需要修改makefile文件之类的吗，如果是的话，怎么添加我的opencv路径呢，谢谢

Hi,please use this:
sudo apt-get install libopencv-dev
It works for me.
