### ISSUE TITLE
Adding a Custom plugins

### ISSUE THREAD

**Issue by Darshcg** [wang-xinyu/tensorrtx#376]
Hi @wang-xinyu,

Thanks for your wonderful Project. It is very helpful Project.

Actually, I have a custom models built from Pytorch, I have converted .pt to .onnx, but there are two Ops which are not supported in TensorRT. So, I am thinking of adding and custom plugins of those two unsupported Ops in TensorRT. 
As per my Knowledge, there are two ways to implement the custom Layers(through C++ and Python Network Defination API). 
Having said that, As I have a ONNX model, what is the better approach? which one to go for? what are the challenges in adding the custom Plugins?

Thanks in advance,
Darshan

**Comment by wang-xinyu** [comment]
You can add a plugin to onnx_parser, when converting onnx to tensorrt, it will find your plugin. But I never tried this way. You can find the official docs.

Or you can use API to define network and add plugin to network, like this repo did, not using onnx. For this, you can refer to yolo, retinaface, etc, in this repo.

**Comment by Darshcg** [comment]
Hi @wang-xinyu,

Thanks very much for your kind response. I was understanding your Custom Plugin Implementation for Retinaface (https://github.com/wang-xinyu/tensorrtx/blob/master/retinaface/decode.cu and https://github.com/wang-xinyu/tensorrtx/blob/master/retinaface/decode.h), But I wanted to know why exactly you are using the Plugins. Are there any Ops that are not supported or you are using that to speedup the computations? If you are using for Unsupported Ops, then where is the Logic of that Ops Implemented? or If you are using for Speeding up the computations, then where is the Logic of that implementation in the File? I am just trying to understand your implementation, and then I will try to write the Plugins for the Ops which are not supported in my Model.

Thanks in Advance,
Darshan

**Comment by wang-xinyu** [comment]
decode plugin can decode bounding boxes from feature maps,  it is part of the post process of retinaface.

you can go through the decode.cu codes and figure out the logic in it.
