### ISSUE TITLE
tensorrt 部署yolov5 , 执行sudo ./yolov5 -s时报错

### ISSUE THREAD

**Issue by sveits6** [wang-xinyu/tensorrtx#378]
Loading weights: ../yolov5s.wts
[01/27/2021-15:06:29] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/qiuqiongwen/deploy/hanjie/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Wei
ghts>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.Aborted
这个是因为网络不匹配吗？能否本项目单独添加对应的版本呀？yolov5官方一直在更新，很容易出现版本不匹配的问题吧？

**Comment by wang-xinyu** [comment]
对于不同版本，tensorrtx/yolov5/readme有说明

**Comment by bolifeyo** [comment]
I have same problem.
case 1 : original yolov5s.pt weights CLASS_NUM : 80 is Okay.
case 2 : custom yolov5s.pt weights CLASS_NUM : 10 is not Okay.

**Comment by guruzoa** [comment]
I have same problem
yolov5s original weights and CLASS_NUM : 80 --> okay.
custom yolov5s weights and CLASS_NUM : 10 --> fail. (above same issue)

please advice.

**Comment by wang-xinyu** [comment]
@guruzoa  you need compare your custom model with the official one.

**Comment by guruzoa** [comment]
@wang-xinyu thank you. I solve the problem.

**Comment by bertinma** [comment]
@guruzoa @wang-xinyu Hi,  I'm facing the same issue with yolov5l model. How did you solve it please ?

**Comment by wang-xinyu** [comment]
pls use the ultralytics/yolov5 release tag, not master branch.

and read carefully the tensorrtx/yolov5/readme

**Comment by bertinma** [comment]
@wang-xinyu what do you mean with "release tag" ?  where can i find it ? please

**Comment by wang-xinyu** [comment]
@bertinma https://github.com/ultralytics/yolov5/tags, download yolov5 model and code from this. do not use his master branch.

and refer to the tensorrtx/yolov5/readme for different yolov5 versions.
