### ISSUE TITLE
Typo when including OpenCV headers

### ISSUE THREAD

**Issue by AWilco** [wang-xinyu/tensorrtx#381]
https://github.com/wang-xinyu/tensorrtx/blob/5332e0e46c3884192b19a6a9b5ee63f209070b44/yolov5/CMakeLists.txt#L28

I believe this is a typo and the line should be 
```
include_directories(${OpenCV_INCLUDE_DIRS})
```
As you wanted to include the directory the variable points to. The line as written includes a subdirectory named `OpenCV_INCLUDE_DIRS`. I needed to do this to get the yolov5 code to compile. I haven't checked other models.

**Comment by wang-xinyu** [comment]
already merged the PR https://github.com/wang-xinyu/tensorrtx/pull/377
