### ISSUE TITLE
cuda memset problem

### ISSUE THREAD

**Issue by whatlas** [wang-xinyu/tensorrtx#386]
https://github.com/wang-xinyu/tensorrtx/blob/1a828224746816c27dbd357f60bc699f005a307d/yolov5/yololayer.cu#L240

这里是不是少写了数量啊，在sizeof(float)前好像应该乘以一个数的？

**Comment by wang-xinyu** [comment]
只需要把第一个数置0

**Comment by whatlas** [comment]
> 只需要把第一个数置0

明白了，多谢～
