### ISSUE TITLE
sudo ./yolov3 -s出现问题

### ISSUE THREAD

**Issue by Rocccc** [wang-xinyu/tensorrtx#39]
能编译成功，但生成引擎的时候出现错误
![image](https://user-images.githubusercontent.com/30819836/84014056-57291280-a9ac-11ea-8f73-e4bd79d813ef.png)

**Comment by wang-xinyu** [comment]
依赖库的问题，貌似你安装的tensorrt是cuda10的，但是链接到的是cuda7.5

**Comment by Rocccc** [comment]
感谢回复，解决依赖库的问题后，还是报这个错误
![image](https://user-images.githubusercontent.com/30819836/84099793-fd245d80-aa3c-11ea-84d1-0252e8226ddf.png)

**Comment by wang-xinyu** [comment]
yolov3.wts放到指定目录了吗

**Comment by Rocccc** [comment]
我使用您提供的pytorch-yolov3代码库生成的yolov3.wts，已经放到指定目录了

**Comment by wang-xinyu** [comment]
现在项目有两个分支，master分支用的是 ultralytics/yolov3
再看下这个readme？
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov3

**Comment by Rocccc** [comment]
请问您使用的是什么版本的opencv，带cuda和contrib吗，因为我发现带上opencv一起编译就会出现’段错误（核心已转储）‘的报错。

**Comment by wang-xinyu** [comment]
我用的是3.3不带cuda的，那神奇了，调试下看看？是opencv的函数挂的吗

**Comment by Rocccc** [comment]
跑通了，应该是我opencv没编译好（opencv_contrib没编好maybe）的原因，编译好opencv后再跑就跑通了，感谢楼主这么棒的工作。

**Comment by honghande** [comment]
@wang-xinyu Hello, to your advice, I hope you can help answer your busy schedule, thank you! The problems are as follows:
https://github.com/wang-xinyu/tensorrtx/issues/112
