### ISSUE TITLE
Exception handling for custom weight files (Parameter check failed)

### ISSUE THREAD

**Issue by usamatariq70** [wang-xinyu/tensorrtx#392]
When I run `sudo ./yolov5 -s` for the custom weight file. I am getting this error.
`[02/03/2021-17:59:32] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::494, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/omnoai/Desktop/tensorrtx/yolov5/common.hpp:162: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion scale_1' failed.
Aborted
`

When I printed the layer name and scale id it is giving me `model.2.cv2.bn : 0`

When I compared the .wts files of custom weight and yolov5 default weights I see the m missing in the layer name. According to my assumption there is some issue while reading those lines. Correct me if I am wrong. I am attaching the screenshot of those lines of both of my custom weight file and yolov5 default file for your reference.

Custom Weight file

![custom](https://user-images.githubusercontent.com/29803942/106753249-3ef9b800-664d-11eb-822b-8e8503c3a79b.png)

Yolov5x weight file

![yolov5](https://user-images.githubusercontent.com/29803942/106753295-4f119780-664d-11eb-9517-50b560536186.png)

**Comment by wang-xinyu** [comment]
you can try the release tag of yolov5, not the master branch

**Comment by usamatariq70** [comment]
> you can try the release tag of yolov5, not the master branch

Can you please bit elaborate what do you meant by this?

**Comment by wang-xinyu** [comment]
checkout the release tag of yolov5 https://github.com/ultralytics/yolov5/tags

and read the tensorrtx/yolov5/readme carefully about the different version of yolov5.

**Comment by usamatariq70** [comment]
![Screenshot from 2021-02-09 13-26-12](https://user-images.githubusercontent.com/29803942/107336344-cb3b2d80-6ada-11eb-8762-f788ff363c96.png)


I am still getting this issue.

**Comment by usamatariq70** [comment]
Looking forward to hear from you

**Comment by wang-xinyu** [comment]
Hi @usamatariq70, more details pls.

which version of yolov5? what's your procedures? etc.

**Comment by usamatariq70** [comment]
> Hi @usamatariq70, more details pls.
> 
> which version of yolov5? what's your procedures? etc.

I am using my custom weights which I got after training on latest yolov5 4.0 
I changed the macro Net in yolov5.cpp and number of classes in yololayer.h just like mentioned in your instructions.
But when I run command 'sudo ./yolov5 -s' to make the engine file it gives me assertion error. Can you point out what possibly I am doing wrong?

**Comment by wang-xinyu** [comment]
@usamatariq70 can you try the official model first?

**Comment by usamatariq70** [comment]
> @usamatariq70 can you try the official model first?

If by official model you meant official weights of yolov5 I tried both s and x. They worked fine. Facing this issue on my custom weights.

**Comment by wang-xinyu** [comment]
@usamatariq70 yes, this repo can only support official one. For your custom model, you need to adapt the code.

**Comment by usamatariq70** [comment]
> @usamatariq70 yes, this repo can only support official one. For your custom model, you need to adapt the code.
> I think you should first compare your model with the official one to find the difference.

okay I can try this.
@wang-xinyu Thank you for your time. I appreciate your time.

**Comment by vman-tcin** [comment]
@usamatariq70 have you resolved the issue?

**Comment by usamatariq70** [comment]
> @usamatariq70 have you resolved the issue?

Sorry for replying late. No it didnt.

**Comment by vman-tcin** [comment]
> Sorry for replying late. No it didnt.

Hey, I was able to resolve it. Earlier I used different release tags of yolov5 and tensorrtx. When I used the matching release tags, it resolved my issue. Also, make sure the model was also trained using the same release. I used the following -

> For yolov5 v4.0, download .pt from yolov5 release v4.0, git clone -b v4.0 https://github.com/ultralytics/yolov5.git and git clone https://github.com/wang-xinyu/tensorrtx.git.
