### ISSUE TITLE
Reducing initial loading times in the YOLOv5 engine

### ISSUE THREAD

**Issue by andrinmeier** [wang-xinyu/tensorrtx#393]
Hello. I'm using YOLOv5s on a Jetson Nano 2GB and everything works but the initial loading times are very slow. This line takes especially long, over a minute: https://github.com/wang-xinyu/tensorrtx/blob/b15a45da3950a9e5cb4c4bd6c7d6c478d02e8d26/yolov5/yolov5_trt.py#L258. After the first inference is done, everything is very fast. Is there a way to speed up the initial loading perhaps? Is torch.Tensor().cuda() slow because it's waiting for pending CUDA operations to finish?

**Comment by xiaqing10** [comment]
这个算是正常情况，首次需要初始化和载入数据。具体来说不影响使用吧

**Comment by andrinmeier** [comment]
So I've solved this problem by using the engine created in this project, the triton inference server and the client library described in this project: https://github.com/isarsoft/yolov4-triton-tensorrt.

**Comment by leviethung2103** [comment]
> So I've solved this problem by using the engine created in this project, the triton inference server and the client library described in this project: https://github.com/isarsoft/yolov4-triton-tensorrt. On a Jetson Nano 2GB this resulted in initial loading times of 30 seconds for the server, 10 seconds for the first inference and 150ms for all subsequent single batch inferences.

Hello, could I ask you about the inference speed of Yolov5s?. How many FPS you got on Jetson Nano?. Thank you

**Comment by andrinmeier** [comment]
Around 5 FPS with 640x640 images, running the Triton server on localhost and without any quantization.

**Comment by leviethung2103** [comment]
It's quite slow, isn't it ?. Thank you for your feedback.

**Comment by andrinmeier** [comment]
Yes and I'm not sure why. I've ran the Triton performance measurement script and came back with 7 infers/secs. But it's still better than the alternatives. I've tried running the model using pyTorch and it took 50 seconds per request. Tensorflow and an SSD Mobilenet v2 took 40minutes to even load.
