### ISSUE TITLE
Adding one more fpn layer to detection layers error

### ISSUE THREAD

**Issue by taylanates24** [wang-xinyu/tensorrtx#398]
Hello, at first, thank you for the great work.
I am working on converting yolov5 weights to the tensorrt weights.
I want to add one more fpn layer to the detection layer. 
I mean,  I have det0, det1, det2, det3 for "addYoLoLayer" function in yolov5.cpp file. When I create plugin by executing the line,

```IPluginV2 *pluginObj = creator->createPlugin("yololayer", &pluginData);```

I got `corrupted size vs. prev_size` error. I guess `libmyplugins.so` is built with 3 yolo kernels. I want to change it to 4 in order to add one more fpn layer.
How can I increase the number of kernels for 'yololayer' plugin?

**Comment by wang-xinyu** [comment]
Well, you need go through the source code of yololayer plugin, and also refer to the tensorrt documentation.
