### ISSUE TITLE
RetinaFace slow inference time

### ISSUE THREAD

**Issue by thimabru1010** [wang-xinyu/tensorrtx#401]
Hi,

I recently ran retinaface with mobilenet backbone using tensorrt but I didn't see quite difference from the traditional [pytorch implementation](https://github.com/biubug6/Pytorch_Retinaface). The difference was from 6 ms using pytorch and 4 ms tensorrt in cpp implementation. The big difference remains when I am doing batch inference in tensorrt. Setting the parameter at the beginning of retina_mnet.cpp file I can get 8 ms for 8 images(1 ms per image). However, Since I am doing real-time detection I can't wait to gather all the images. 

I thought the problem was the first image inference time, but I repeated the function "doInference" (with the same parameters) and the time was the same thing. 

Am I measuring something wrong? I was expecting much more difference than 2 ms for batch size of 1 using tensorrt. Did someone face this issue doing real-time inference?

**Comment by thimabru1010** [comment]
> Hi,
> 
> I recently ran retinaface with mobilenet backbone using tensorrt but I didn't see quite difference from the traditional [pytorch implementation](https://github.com/biubug6/Pytorch_Retinaface). The difference was from 6 ms using pytorch and 4 ms tensorrt in cpp implementation. The big difference remains when I am doing batch inference in tensorrt. Setting the parameter at the beginning of retina_mnet.cpp file I can get 8 ms for 8 images (1 ms per image). However, Since I am doing real-time detection I can't wait to gather all the images.
> 
> I thought the problem was the first image inference time, but I repeated the function doInference (with the same parameters) and the time was the same thing.
> 
> Did someone face this issue doing real-time inference?

**Comment by wang-xinyu** [comment]
Firstly, 4ms is already fast enough for real-time inference.

And because the retinaface with mobilenet is a very small model, so there will not be much difference of inference latency between pytorch and tensorrt.

**Comment by thimabru1010** [comment]
> Firstly, 4ms is already fast enough for real-time inference.
> 
> And because the retinaface with mobilenet is a very small model, so there will not be much difference of inference latency between pytorch and tensorrt.

It was just an example. But in my application, I can only do inference with a batch size of 1. So I was expecting a much bigger improvement. But yes, this is happening due to the model size.

**Comment by wang-xinyu** [comment]
If you want to implement multi-batch, you need go through the decode plugin and make some adaption.
