### ISSUE TITLE
如何用python进行yolov5的批量推理？

### ISSUE THREAD

**Issue by AsakusaRinne** [wang-xinyu/tensorrtx#405]
您好！首先非常感谢您的贡献，您的开源项目让我受益良多。
出于一些原因我想用python调用引擎的方式来部署到设备上，看到您的例程里只有batchsize=1的情况，我就尝试修改了代码，想要改成batchsize>1来进行批量推理。我修改过yolov5.cpp中的BATCH_SIZE宏定义，也能跑通您的python例程。
我对yolov5_trt.py的修改就是重新定义了一个读取文件的类，每次读取batchsize个文件，按照NCHW排列，然后传进infer函数中，但是推理的输出是一维的，比如（1204，），值的排列特点如下所示。虽然得到了很多的bbox预测结果，但是无法得知哪个bbox属于哪个图（只有一个20代表四张图片一共有20个bbox）。请问能否提示一下想要实现基于python+TensorRT的yolov5批量推理该怎么做呢？我做好之后会共享上来。
再次感谢您的开源项目，祝您新年快乐！
`20.0
190.3418
319.1175
146.61232
116.11872
0.6081433
0.0
192.1998
318.06577
147.05142
113.67797
0.49357978
0.0
189.79987
320.27078
146.07979
118.87334
0.6424214
0.0
191.75493
320.53287
147.14561
115.23795
0.48781264
0.0
190.23547
319.0689
146.885
116.32168
0.6024084
0.0
192.05841
317.97107
146.83887
113.92187
0.48027137
0.0
189.64044
320.2471
145.65082
118.40114
0.6373673
0.0
191.5586
320.25894
147.25449
115.23923
0.48219335
0.0
190.29807
319.51498
146.8571
117.30112
0.5876493
0.0
192.15257
317.99005
147.44855
114.441925
0.47457635
0.0
189.5444
320.28265
145.3865
118.913666
0.63373876
0.0
191.48969
320.27078
147.84386
115.54723
0.4803354
0.0
190.95706
318.82663
148.40147
115.4892
0.4059095
0.0
192.24849
318.2044
151.33377
113.36025
0.40684056
0.0
189.3001
320.01746
147.87576
117.27037
0.4894921
0.0
190.77576
319.6251
151.33377
112.85651
0.3435289
0.0
191.29521
318.72403
148.328
115.875984
0.43219697
0.0
192.04095
318.2243
151.30139
114.44026
0.43314463
0.0
189.66551
320.04095
147.60605
116.74476
0.49153072
0.0
190.5491
319.70477
151.18356
113.18363
0.3407937
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

`

**Comment by henbucuoshanghai** [comment]
py版本的不是已经可以了？为什么用c++版本的？

**Comment by henbucuoshanghai** [comment]
py版本的   输出为什么是那个格式呢？

**Comment by wang-xinyu** [comment]
The c++ can decode multi-batch result. You can refer to it and adapt the .py yourself.
