### ISSUE TITLE
the input data in yolov5.cpp  is batch*3*h*w,           why?

### ISSUE THREAD

**Issue by henbucuoshanghai** [wang-xinyu/tensorrtx#406]
/ prepare input data ---------------------------
    static float data[BATCH_SIZE * 3 * INPUT_H * INPUT_W];

**Comment by BaofengZan** [comment]
The network input image size is 3 * INPUT_H * INPUT_W.  Multiple images need BATCH_SIZE * 3 * INPUT_H * INPUT_W * sizeof(float)  spaces.

**Comment by henbucuoshanghai** [comment]
that is :the input shape is [1,3,h,w]&nbsp; &nbsp; and[batch,3,h,w]&nbsp; &nbsp; ?not 3*h*w ?

**Comment by BaofengZan** [comment]
Yes, your understanding is correct.
