### ISSUE TITLE
Yolo v5: TensorRT slower than PyTorch

### ISSUE THREAD

**Issue by mfoglio** [wang-xinyu/tensorrtx#407]
It looks to me the that the TensorRT implementation of Yolo v5 is slower than the PyTorch implementation.

I am using an AWS instance with a T4 gpu, 16 cores, and 64gb. PyTorch gives me about 154 FPS with batch size equal 8 (batch size equal 64 would give 180 FPS) with a simple code using `results = model(batch)` and the float 16 `model = model.half()`.

When using TensorRT I am struggling to achieve comparable performance. I implemented a pipeline that pre process the images in parallel using CPU but despite that, the model is slow. I am doing about 160 FPS with batch size = 8 if I preprocess the image before launching my pipeline (that is: I am timing without preprocessing). Considering the preprocessing I am doing just 146 FPS. I am using FP16 too. The inference part (from `self.cfx.push()` to `self.cfx.pop()` on this repository) is taking about 0.32 ms but with post processing it reaches about 0.40 ms (I iterate over the results relative to each image of the batch)

I am using Yolo v5 s.

What performance gain should I expect?

**Comment by mfoglio** [comment]
I am thinking that I can improve the throughput by copying the next batch to the GPU while engine is performing inference. However, the performance seems poor according to the results above.

**Comment by wang-xinyu** [comment]
did you try the c++ code?

**Comment by mfoglio** [comment]
Actually by keeping the throughput constant I have been able to increase the frame rate.

I am not experience in the C++ version of TensorRT. Usually, I build the engine directly from the Python API. It looks to me that instead you are building the engine using C++ directly. Is it still important to build it on the target GPU? Is there still a non deterministic optimization involved in the build?

Thank you

**Comment by wang-xinyu** [comment]
It is required to build the trt model on the target GPU.
