### ISSUE TITLE
Inference on a video

### ISSUE THREAD

**Issue by SyedHamza0196** [wang-xinyu/tensorrtx#409]
I am new tensorRT and opencv. Great project btw. Please guide me how I can do inference on a video?

**Comment by BaofengZan** [comment]
You can refet to this URL: [read-write-and-display-a-video-using-opencv-cpp](https://learnopencv.com/read-write-and-display-a-video-using-opencv-cpp-python/).
And modify https://github.com/wang-xinyu/tensorrtx/blob/37f03a77c57b4e80a0afa8f7308ec2348ea0953c/yolov5/yolov5.cpp#L519 for video inference

**Comment by muddasar-ali** [comment]
I'm still not sure where the code to read the video should be put, and what should it be called. also, what do I have to modify in tensorrtx/yolov5/yolov5.cpp?

**Comment by xinhappy1** [comment]
hi, do you know how to inference on a video now?Can you tell me how to do it?

> I'm still not sure where the code to read the video should be put, and what should it be called. also, what do I have to modify in tensorrtx/yolov5/yolov5.cpp?
