### ISSUE TITLE
About nms implementation in yolov3-spp.cpp

### ISSUE THREAD

**Issue by chenzhao17** [wang-xinyu/tensorrtx#41]
Hi, thanks for this wonderful work. I was wondering if the compared target scores during the implementation of nms in yolov3-spp.cpp should be det_confidence * class_confidence?

**Comment by wang-xinyu** [comment]
Usually, when the det_confidence is high, the class_confidence will also be high, so I think det_confidence should be enough.

Is ultralytics/yolov3's nms using det_confidence * class_confidence?

**Comment by chenzhao17** [comment]
> Usually, when the det_confidence is high, the class_confidence will also be high, so I think det_confidence should be enough.
> 
> Is ultralytics/yolov3's nms using det_confidence * class_confidence?

It appears that the boxes are first filtered according to det_confidence only (https://github.com/ultralytics/yolov3/blob/82f653b0f579db97f8908800d45e8f5287f79bd3/utils/utils.py#L487), and then sorted by det_confidence * class_confidence (https://github.com/ultralytics/yolov3/blob/82f653b0f579db97f8908800d45e8f5287f79bd3/utils/utils.py#L495).
