### ISSUE TITLE
ArcFace - Inference speed is quite slow on Jetson Nano 

### ISSUE THREAD

**Issue by leviethung2103** [wang-xinyu/tensorrtx#410]
Hi @wang-xinyu 
I am currently testing the ArcFace model on Jetson Nano. I've followed all the steps and built successfully the arcface engine. 

1/ However, when I am testing with original C++ code, the inference time is quite slow ~ 81 ms (FP32) and 58 ms (FP16). 

2/ Furthermore, I noticed that the weight of ArcFace model after serializing is about 170 MB (quite large) in comparison with other models. Is it normal or not? 

Thank you in advance.

------------------------------------
Here is my system information
```
Jetson Nano 4GB
Increased the SWAP memory to 8GB 
CPU Frequency: 1400 MHZ 
Jetpack 4.4 
TensorRT 7.1.3 
Cuda 10,2
Cudnn 8.0
```

**Comment by wang-xinyu** [comment]
This is normal, arcface(resnet50) is large, you can try to use smaller backbone.

**Comment by leviethung2103** [comment]
Many thanks @wang-xinyu, I will try another backbone based on your suggestion.
