### ISSUE TITLE
ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package

### ISSUE THREAD

**Issue by rocketsfallonrocketfalls** [wang-xinyu/tensorrtx#412]
Hi, 

I am trying to test ultralytics' yolov3 on TensorRT using your repository. Even though I use the exact lines you provided, I get an error:

`ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package
`

If I manually download "models" folder from ultralytics' latest version, I get:
```
Traceback (most recent call last):
  File "gen_wts.py", line 6, in <module>
    model = Darknet('cfg/yolov3.cfg', (608, 608))
NameError: name 'Darknet' is not defined
```

Any ideas?

**Comment by wang-xinyu** [comment]
Hi, pls try the archive branch of ultralytics' yolov3 .

**Comment by zhaoxuejun1234** [comment]
> Hi,
> 
> I am trying to test ultralytics' yolov3 on TensorRT using your repository. Even though I use the exact lines you provided, I get an error:
> 
> `ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package `
> 
> If I manually download "models" folder from ultralytics' latest version, I get:
> 
> ```
> Traceback (most recent call last):
>   File "gen_wts.py", line 6, in <module>
>     model = Darknet('cfg/yolov3.cfg', (608, 608))
> NameError: name 'Darknet' is not defined
> ```
> 
> Any ideas?

Hi, have you solved "ModuleNotFoundError: No module named 'models.yolo'; 'models' is not a package"

**Comment by zhaoxuejun1234** [comment]
> 

using .weights instead of .pt will work

**Comment by Audrey528** [comment]
可以通过此链接下载yolov3.pt[yolov3.pt](https://github.com/ultralytics/yolov3/releases/download/v8/yolov3.pt)，V9版本和V8版本模型存在差别。
