### ISSUE TITLE
yolov5s python 版本trt在jetson nano上加载非常慢

### ISSUE THREAD

**Issue by 1124676457** [wang-xinyu/tensorrtx#413]
yolov5s python 版本trt在jetson nano上加载非常慢，处理第一帧的时候要用将近5分钟；而且使用csi相机流去跑算法的时候跑几帧就会卡死不动，只能杀掉

**Comment by wang-xinyu** [comment]
第一帧比较慢，可以warmup一下；
csi相机跑几帧卡死，和trt没关系，，，可能逻辑问题（可能需要多线程）或者相机bug；
另外nano建议用c++。

**Comment by 1124676457** [comment]
逻辑和相机应该没问题，我用同样的onnx转trt的v5s去跑，第一帧很快，也不会卡死，会不会是内存占用太大了，抢占资源，跑起来的话内存直接满了；项目比较急，目前用的是python
