### ISSUE TITLE
Linking the Custom plugins for the Conversion(while converting from ONNX to TRT Model)

### ISSUE THREAD

**Issue by Darshcg** [wang-xinyu/tensorrtx#414]
Hi @wang-xinyu ,

Thanks for your wonderful work.

I have Implemented two custom Plugins for two unsupported Ops. I want to link those custom Plugins for the conversion(while converting from ONNX to TRT Model). Can you please assist me in doing the same? Would be a great help.

Thanks and Regards,
Darshan

**Comment by wang-xinyu** [comment]
Hi, I never tried onnxparser with plugin. I only use network definition API with plugin. You can check other repos on github.

**Comment by Darshcg** [comment]
Hi @wang-xinyu,

I got to know about the same. It is about including the .so file while conversion.
Example: ./trtexec --onnx=model.onnx --explicitBatch --shapes=input1:1x1x1x1 --plugins=layer.so 

But when I run this I am getting an issue as: **Einsum_194: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions**

The image of the error has been attached below:
![Screenshot from 2021-02-22 01-04-57](https://user-images.githubusercontent.com/48723743/108636269-42dd6500-74aa-11eb-86a9-b65d9d45705a.png)

Can you please help me to resolve this error? Where Exactly I am going wrong?what's the solution for this?

Thanks and Regards,
Darshan C G

**Comment by wang-xinyu** [comment]
It seems you need to use fixed input dimensions.

**Comment by Darshcg** [comment]
Hi @wang-xinyu,
Thanks for your reply.

so my plugin implementation should inherit IPluginV2DynamicExt, instead of IPluginV2Ext(which I had used earlier)?

Thanks

**Comment by Darshcg** [comment]
Hi @wang-xinyu,

I was able to resolve all the Issues. But during the Conversion I am getting an error as Segmentation fault (core dumped). I don't know what is happening. May I know why I am getting that error and how to resolve that? I have attached the Image containing the short Verbose and the error below.
![Screenshot from 2021-02-23 03-12-12](https://user-images.githubusercontent.com/48723743/108774376-94a6ed80-7585-11eb-9743-b6b2edd8fc97.png)


Thanks,
Darshan

**Comment by Darshcg** [comment]
Hi @wang-xinyu,

It would be a great help if you can help me to resolve this issue.
Looking forward to your reply.

Thanks,
Darshan

**Comment by wang-xinyu** [comment]
Hi @Darshcg , segmentation fault usually is memory access issue. Some null ptr might be accessed.

**Comment by Darshcg** [comment]
It is solved.

Thank you
