### ISSUE TITLE
retinaface runtime issue

### ISSUE THREAD

**Issue by tadam98** [wang-xinyu/tensorrtx#415]
Followed successfully all steps. *.wts successfully created,
cmake and buikd were successful.
I have OpenCV 4.2.0 with CUDA(10.2) and CUDNN(7.6.5) support.

`Row 307 of retina_r50.cpp: APIToModel(BATCH_SIZE, &modelStream);`

Getting the below error:
```
$ ./retina_r50 -s
Loading weights: ../retinaface.wts
Your platform support int8: 1
Building engine, please wait for a while...
reading calib cache: r50_int8calib.table
[02/21/2021-12:17:07] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
```

**Comment by jiejie1993** [comment]
遇到了相同的问题，怎么解决的？

**Comment by wang-xinyu** [comment]
Hi, for int8, you need calibration data, pls recap the readme of tensorrtx/retinaface.

**Comment by tadam98** [comment]
Hi, I am unable to download the files. Cannot handle Chinese. It is trying to install a baidu application on my system which I would not allow. Can you advise how or where to get these zip files?

Also, why not consider adding a note that this calibration is needed BEFORE the execution example ?

Thanks,
Mickey

![baidu](https://user-images.githubusercontent.com/21152079/108772301-821cbc00-7565-11eb-8791-ad3ecaae4fec.jpg)

**Comment by tadam98** [comment]
Assuing that train folder was correctly built, 
#define set USE_INT8 in retina_r50.cpp
And now serialize completes but deserialize fails:
```
$ cd data
$ find widerface/train -name *.jpg > train.lst # list all image files in train
$ shuf -n 1000 train.lst > train_random.lst # pick 1000 random names
$ mkdir widerface/train_random_1000 # make a folder for them
$ xargs -a train_random.lst  cp -t widerface/train_random_1000 # copy according to the list from train to new folder.
$ cp widerface/train_random_1000/*.jpg <project path>tensorrtx/retinaface/build # place in build
$ sudo ./retina_r50 -s
[sudo] password for mickey: 
Loading weights: ../retinaface.wts
Building engine, please wait for a while...
Build engine successfully!
(retina_rt) mickey@2080TI:~/Software/Retinaface-RT/tensorrtx/retinaface/build$ sudo ./retina_r50 -d
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) /home/mickey/Downloads/opencv/opencv/modules/core/src/matrix.cpp:235: error: (-215:Assertion failed) s >= 0 in function 'setSize'

Aborted
```

**Comment by wang-xinyu** [comment]
Hi @tadam98, thanks for your feedback. Can you help share the calibration data with a google drive link? As it's not convenient to reach google from China.

**Comment by tadam98** [comment]
I have just downloaded the widerface data which is on gdrive and built the folder structure as advised. And then simply copied 1000 random images as described in my script.

Best,
Mickey
________________________________
