### ISSUE TITLE
Cuda failure: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Darshcg** [wang-xinyu/tensorrtx#417]
Hi @wang-xinyu ,

I have Implemented the Custom plugin for the Einsum operator in TensorRT. But When I am loading the plugin during the Conversion from ONNX to TRT I am getting an issue as Cuda failure: illegal memory access was encountered. It is occuring in enqueue().

Enqueue() code snippet:
```

int EinsumPlugin::enqueue(const nvinfer1::PluginTensorDesc* inputDesc,
    const nvinfer1::PluginTensorDesc* outputDesc, const void* const* inputs, void* const* outputs, void* workspace,
    cudaStream_t stream)
    {
    std::cout<<"In Enqueue \n";
     cublasHandle_t mCublas;
     cublasCreate(&mCublas);
     float onef{1.0f}, zerof{0.0f};
     cublasSetStream(mCublas, stream);
     if(equation=="nct, ncp -> ntp")
       {

           cublasSgemmBatched(mCublas, CUBLAS_OP_N,CUBLAS_OP_T, 
                                  M, K,L,&onef, 
                                  reinterpret_cast<const float *const *>(inputs[1]), M, 
                                  reinterpret_cast<const float *const *>(inputs[0]), K, 
                                  &zerof, 
                                  reinterpret_cast<float *const *>(outputs[0]), 
                                  M,N);


        }

     else if(equation=="ntg, ncg -> nct")
        {
           cublasSgemmBatched(mCublas, CUBLAS_OP_T,CUBLAS_OP_N, 
                                  L, O, K, &onef, 
                                  static_cast<const float*>(inputs[0]), K, 
                                  static_cast<const float*>(inputs[1]), K, 
                                 static_cast<float*>(outputs[0]), L, N);

        
        }
    return 0;
}

```
May I know the reason for the Issue?

I am attaching the screenshot of the log below

![Screenshot from 2021-02-25 14-57-13](https://user-images.githubusercontent.com/48723743/109135547-32b0d880-777d-11eb-9edd-a2f0dd1643df.png)

Thanks in advance,
Darshan

**Comment by wang-xinyu** [comment]
Hi @Darshcg , I can only help you with the issue from this repo. For your own codes, I cannot help you to debug.

**Comment by Darshcg** [comment]
Thanks for your help @wang-xinyu.

**Comment by xn1997** [comment]
> Thanks for your help @wang-xinyu.

Hi, have you solved this problem? I alse need to implemented the Custom plugin for the Einsum operator in TensorRT, but I don't know how to do it.

**Comment by scuizhibin** [comment]
Hello, I also encountered a similar problem, how did you solve it?
