### ISSUE TITLE
Yolov4 csp large 

### ISSUE THREAD

**Issue by pepijnko** [wang-xinyu/tensorrtx#418]
Dear Wang-xinyu 

Is there a Tensorrtx Pytorch implementation of the Yolov4-P6 model? (C++)  
I have been looking but can't find it, maybe you know if someone has already implemented this?
Thank you in advance. 

-https://github.com/WongKinYiu/PyTorch_YOLOv4
-https://arxiv.org/abs/2011.08036

**Comment by wang-xinyu** [comment]
@pepijnko Hi,  no idea. You can implement it based on yolov4 in this repo.

**Comment by pepijnko** [comment]
@wang-xinyu 

Okay, thank you for your reaction! I really appreciate it. 
What is the best way, to begin implementing this? First, implementing the .cfg file?

**Comment by wang-xinyu** [comment]
@pepijnko I think you should go through the yolov4 in this repo, to read and understand the code. And then try to modify it.
