### ISSUE TITLE
执行 make 报错

### ISSUE THREAD

**Issue by qybing** [wang-xinyu/tensorrtx#42]
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_mish.cu.o
In file included from /opt/code/YOLO/tensorrtx/yolov4/mish.cu:5:0:
/opt/code/YOLO/tensorrtx/yolov4/mish.h:6:10: fatal error: NvInfer.h: 没有那个文件或目录
 #include "NvInfer.h"
          ^~~~~~~~~~~
compilation terminated.
CMake Error at myplugins_generated_mish.cu.o.Debug.cmake:219 (message):
  Error generating
  /opt/code/YOLO/tensorrtx/yolov4/build/CMakeFiles/myplugins.dir//./myplugins_generated_mish.cu.o

CMakeFiles/myplugins.dir/build.make:70: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_mish.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_mish.cu.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
tensorrt安装了吗

**Comment by qybing** [comment]
装了，版本为tensorrt==7.0.0.11

**Comment by qybing** [comment]
> tensorrt安装了吗

装了，版本为tensorrt==7.0.0.11

**Comment by wang-xinyu** [comment]
是安装的deb包吗？我安装之后在/usr/include/x86_64-linux-gnu/NvInfer.h

```
$ dpkg -L libnvinfer-dev 
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libnvinfer_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_compiler_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_executor_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_pattern_library_static.a
/usr/lib/x86_64-linux-gnu/libmyelin_pattern_runtime_static.a
/usr/include
/usr/include/x86_64-linux-gnu
/usr/include/x86_64-linux-gnu/NvInfer.h
/usr/include/x86_64-linux-gnu/NvInferRuntime.h
/usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h
/usr/include/x86_64-linux-gnu/NvInferVersion.h
/usr/include/x86_64-linux-gnu/NvUtils.h
/usr/share
/usr/share/doc
/usr/share/doc/libnvinfer-dev
/usr/share/doc/libnvinfer-dev/copyright
/usr/share/doc/libnvinfer-dev/changelog.Debian
/usr/lib/x86_64-linux-gnu/libmyelin.so
/usr/lib/x86_64-linux-gnu/libnvinfer.so
```

**Comment by qybing** [comment]
> dpkg -L libnvinfer-dev

我安装的是tar包，直接解压安装的，这里面又什么问题吗

**Comment by wang-xinyu** [comment]
没什么问题，解压安装就要自己找到头文件在哪，然后自己在cmake设置一下include路径
dpkg安装的是我说的这个目

**Comment by qybing** [comment]
大佬我问一下，这个怎么实现python的api来进行测试

**Comment by daodaoling** [comment]
I have the same problem.How did you solve the problem ?

**Comment by viwe-monai** [comment]
如果在build路径下cmake ..，然后make -j16，发现编译报错，缺少了什么文件，可以在build的上一级目录的CMakeLists.txt中，修改cuda、tensorRT、Opencv的路径，然后删除build文件夹生成的文件，重新cmake ..，然后make -j16
![image](https://github.com/user-attachments/assets/7519d79d-a61f-4400-b703-c858c77577f7)
