### ISSUE TITLE
terminate called after throwing an instance of 'pwgen::PwgenException' what(): Driver error

### ISSUE THREAD

**Issue by Darshcg** [wang-xinyu/tensorrtx#422]
Hi @wang-xinyu ,

During conversion from  TRT engine file I am getting an error as: terminate called after throwing an instance of 'pwgen::PwgenException' what(): Driver error. May I know the cause of this error?

Thanks,
Darshan

**Comment by wang-xinyu** [comment]
Hi @Darshcg , this error usually because of the environments not installed properly. The cuda driver, cuda, cudnn, and tensorrt. You need to double check them.

**Comment by Darshcg** [comment]
Hi @wang-xinyu,

Thank you very much for your reply.
I reinstalled cuda driver, cuda, cudnn, and tensorrt and it worked perfectly.

Thanks,
Darshan
