### ISSUE TITLE
nvidia-docker运行retina_r50 报错 INVALID_ARGUMENT: getPluginCreator could not find plugin Decode_TRT version 1

### ISSUE THREAD

**Issue by weixiu00** [wang-xinyu/tensorrtx#423]
环境
cuda 10.2
TensorRT-7.0.0.11
nvcr.io/nvidia/tensorrtserver:20.02-py3

报错信息
I0301 02:32:54.835756 1 metrics.cc:164] found 2 GPUs supporting NVML metrics
I0301 02:32:54.841361 1 metrics.cc:173]   GPU 0: GeForce RTX 2080 Ti
I0301 02:32:54.847105 1 metrics.cc:173]   GPU 1: GeForce RTX 2080 Ti
I0301 02:32:54.847262 1 server.cc:112] Initializing TensorRT Inference Server
E0301 02:32:55.140850 1 server.cc:139] failed to enable peer access for some device pairs
I0301 02:32:55.150514 1 server_status.cc:55] New status tracking for model 'retina_r50'
I0301 02:32:55.150636 1 model_repository_manager.cc:675] loading: retina_r50:1
E0301 02:32:59.168956 1 logging.cc:43] INVALID_ARGUMENT: getPluginCreator could not find plugin Decode_TRT version 1
E0301 02:32:59.169050 1 logging.cc:43] safeDeserializationUtils.cpp (293) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
E0301 02:32:59.169190 1 logging.cc:43] INVALID_STATE: std::exception
E0301 02:32:59.169357 1 logging.cc:43] INVALID_CONFIG: Deserialize the cuda engine failed.
E0301 02:32:59.178933 1 model_repository_manager.cc:832] failed to load 'retina_r50' version 1: Internal: unable to create TensorRT engine
error: creating server: INTERNAL - failed to load all models

**Comment by wang-xinyu** [comment]
Hi 是运行我的程序吗？还是你做了什么修改

**Comment by weixiu00** [comment]
> Hi 是运行我的程序吗？还是你做了什么修改

直接运行retina_r50程序没有问题，尝试用trtserver 加载运行plan文件 也就是retina_r50.engine时出现的错误信息，其他未做啥修改

不知道是不是因为用trtserver 运行retina_r50.engine文件时，要把libdecodeplugin.so也加载上才行？

**Comment by wang-xinyu** [comment]
需要加载libdecodeplugin.so

**Comment by weixiu00** [comment]
> 需要加载libdecodeplugin.so

试着加了--env LD_PRELOAD=/plugins/libdecodeplugin.so 不报错了，谢谢

**Comment by wang-xinyu** [comment]
OK, closing it.
