### ISSUE TITLE
Different resolution for YoloV5s

### ISSUE THREAD

**Issue by mfoglio** [wang-xinyu/tensorrtx#424]
I noticed that YoloV5s has a default resolution of 640x640 pixels, while the TensorRT implementation in this repository has a resolution of 608x608. How is it possible that it uses the same weights?
Thank you

**Comment by wang-xinyu** [comment]
Hi @mfoglio , weights not related to input resolution, but kernel size and channels. You should understand CNN first.

**Comment by mfoglio** [comment]
Oh yeah I got it, thanks. I just wanted to make sure they were the same model 🙂

**Comment by mfoglio** [comment]
Is there any particular reason in terms of performance to use 608x608 instead of 640x640?

**Comment by wang-xinyu** [comment]
There is no particular reason, just save as yolov3, to compare the inference latency.

**Comment by pedromoraesh** [comment]
> There is no particular reason, just the same as yolov3, to compare the inference latency.

@wang-xinyu there is a way to modify the input resolution in macros or another way? For example with my implementation, I need to use Yolov5s with a 960x960 input resolution.

**Comment by wang-xinyu** [comment]
@pedromoraesh refer to the `Config` in tensorrtx/yolov5/readme.  adapt width and height, and rebuild everything.
