### ISSUE TITLE
Does YOLOv5 PyTorch support deployment to NVIDIA TensorRT 7.2.1? 

### ISSUE THREAD

**Issue by vilmara** [wang-xinyu/tensorrtx#425]
Does YOLOv5 PyTorch support deployment to NVIDIA TensorRT 7.2.1? 

The docker file at `ultralytics/yolov5/Dockerfile` builds `FROM nvcr.io/nvidia/pytorch:20.12-py3 ` (with TensorRT 7.2.2). My deployment environment supports only TRT 7.2.1, and therefore I am getting the below error:

`E0302 07:27:28.937001 90 logging.cc:43] INVALID_CONFIG: The engine plan file is not compatible with this version of TensorRT, expecting library version 7.2.1 got 7.2.2, please rebuild.`

**Comment by wang-xinyu** [comment]
Hi, you need rebuild and serialize the model on the target platform.

**Comment by vilmara** [comment]
Hi @wang-xinyu, I had rebuilt and serialized the models on the target platform. However, I am getting unexpected performance when running the engines with trtexec vs DeepStream, and even when running BS=1 versus BS>1. Please see below:

TensorRT: 7.2.1
DeepStream: 5.1

**With trtexec and BS=1:** 
`$ LD_PRELOAD=build/libmyplugins.so /usr/src/tensorrt/bin/trtexec --loadEngine=yolov5s<precision>.engine`
Performance:
TRT-FP32:   179.7 qps
TRT-FP16:   396.9 qps
TRT-INT8 :  469.9 qps

**With DeepStream and BS=1:**
TRT-FP32:  109.1 FPS 
TRT-FP16:  91.6 FPS
TRT-INT8:  88.9 FPS

TRT-INT8 (built with BS=8) |
run with trtexec and BS=1 : 469.9 qps    | run with DS and  BS=1 : 88.9 FPS  
run with trtexec and BS=8:  753.3 qps    | run with DS and  BS=8 : 42.7 FPS 

Whats is the formula to convert qps to FPS?. What parameters do I need to set in the DeepsTream config files to fix the performance issues??

**Comment by wang-xinyu** [comment]
Hi, I don't know what is qps. And I never use trtexec and deepstream.
You can use this repo to test inference latency/FPS.

**Comment by maidmentdaniel** [comment]
@vilmara with regards to deepstream, I'm attempting to integrate at the moment, but which function did you specify in the field: ```parse-bbox-func-name```

**Comment by vilmara** [comment]
Hi @maidmentdaniel, I didn't use my own parse, I used `parse-bbox-func-name=NvDsInferParseCustomYoloV5`. You can build the plugin from `https://github.com/DanaHan/Yolov5-in-Deepstream-5.0` or `https://github.com/marcoslucianops/DeepStream-Yolo/tree/master/external/yolov5`. I am getting performance issues deploying with batch size > 1, do you mind sharing your results once you finish your deployment?

**Comment by maidmentdaniel** [comment]
Thanks, I will do so.
