### ISSUE TITLE
make error,please~~~~~~~~

### ISSUE THREAD

**Issue by mingyu6yang** [wang-xinyu/tensorrtx#427]
when i make yolov5 and retinaface ,i meet these problems.

[ 80%] Linking CXX executable yolov5
CMakeFiles/yolov5.dir/calibrator.cpp.o: In function `Int8EntropyCalibrator2::getBatch(void**, char const**, int)':
/home/aicvs/ssd2/mingyu/tensorrtx/yolov5/calibrator.cpp:52: undefined reference to `cv::dnn::experimental_dnn_v2::blobFromImages(std::vector<cv::Mat, std::allocator<cv::Mat> > const&, double, cv::Size_<int>, cv::Scalar_<double> const&, bool, bool)'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5.dir/build.make:160: recipe for target 'yolov5' failed
make[2]: *** [yolov5] Error 1
CMakeFiles/Makefile2:124: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

how to solve it?
please~~~~~~~~~

**Comment by wang-xinyu** [comment]
cv::dnn module not found, you need check your opencv.

**Comment by mingyu6yang** [comment]
i found solution,thanks!
cmakelist does not link the opencv-dnn,i link that.
just like this:
target_link_libraries(yolov5 ${OpenCV_LIBS} -lopencv_dnn)

**Comment by wang-xinyu** [comment]
ok, closing it.
