### ISSUE TITLE
后续会支持直接通过模型文件来构建engine，而不是通过手写构造每层网络算子的方式？

### ISSUE THREAD

**Issue by zjd1988** [wang-xinyu/tensorrtx#43]
你好，非常感谢分享，很好的参考资源，我看了两三个示例代码，发现都是构造每层的网络操作来搭建网络，后续会支持通过模型文件来构建engine吗？

**Comment by wang-xinyu** [comment]
这个repo的特点就是手动搭建网络。如果通过模型文件来构建，可以利用tensorrt的onnxparser，caffeparser等等。

这么做的原因，我再贴一下项目介绍

TensorRTx aims to implement popular deep learning networks with tensorrt network definition APIs. As we know, tensorrt has builtin parsers, including caffeparser, uffparser, onnxparser, etc. But when we use these parsers, we often run into some "unsupported operations or layers" problems, especially some state-of-the-art models are using new type of layers.

So why don't we just skip all parsers? We just use TensorRT network definition APIs to build the whole network, it's not so complicated.

**Comment by zjd1988** [comment]
@wang-xinyu  I get it, thanks for your reply!!!!

**Comment by zjd1988** [comment]
@wang-xinyu  要是能把网络构造的过程再封装一下就更好了（类似完成parser的工作），这样代码比较简洁也能进行复用，不用一个网络得写一遍构造过程。

**Comment by wang-xinyu** [comment]
网络定义的过程是可以封装的，比如resnet，就封装成了多个bottleneck block，
这个封装取决于pytorch的网络结构定义

如果想一步到位，拿到训练好的模型，直接转换到tensorrt模型，那就用parser，但是碰到问题基本没什么办法。

**Comment by zjd1988** [comment]
@wang-xinyu  我的意思是，用python脚本获取权重时，把网络的结构和网络算子的信息保存下来。这样的话，在用C++构建网络时，可以依靠这些信息构造统一的接口来构建网络。

**Comment by wang-xinyu** [comment]
嗯嗯 :thumbsup:  :thumbsup:

**Comment by zjd1988** [comment]
Hi @wang-xinyu  , 这个是我最近做的一个project https://github.com/zjd1988/tensorrt_wrapper_for_onnx，目前支持的网络有限。

**Comment by xiangyun-hz** [comment]
@zjd1988 https://github.com/zjd1988/tensorrt_wrapper_for_onnx 这个链接没了？我也想学习学习的，有没有类似的推荐？谢谢

**Comment by zjd1988** [comment]
@xiangyun-hz 代码是之前的公司在用了，就没再公开了，不过我觉得你可以看看onnx-tensorrt这个开源工程
