### ISSUE TITLE
Command ./yolov5 -s yolov5s.wts yolov5s.engine s

### ISSUE THREAD

**Issue by constantinfite** [wang-xinyu/tensorrtx#433]
Hi, 
I follow the tutorial of yolov5, I came to the command `make` and when I run the command `./yolov5 -s yolov5s.wts yolov5s.engine s`
It shows this error 

![oie_Iy4AZvxyR8Gz](https://user-images.githubusercontent.com/57963890/110094532-39060c80-7d9c-11eb-9bc5-d37fcd2b6606.png)

What did I do wrong ?

**Comment by wang-xinyu** [comment]
your local code is not updated. try git pull.

**Comment by constantinfite** [comment]
@wang-xinyu I just started from scratch. I clone the 2 repo
git clone -b v3.0 https://github.com/ultralytics/yolov5.git and git clone -b yolov5-v3.0 https://github.com/wang-xinyu/tensorrtx.git

and it shows the same error

**Comment by wang-xinyu** [comment]
for v3.0, check the readme here https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/yolov5

**Comment by constantinfite** [comment]
I succeeded to run on images (bus.jpg) but the images output don't have bounding boxes.
It displays the time to execute inference however

**Comment by wang-xinyu** [comment]
where did you get the .pt?

**Comment by constantinfite** [comment]
I clone the repo v3 of yolov5 and I download from this https://github.com/ultralytics/yolov5/releases/download/v2.0/yolov5s.pt

**Comment by wang-xinyu** [comment]
for 3.0, you need use 3.0 model. but you downloaded from 2.0 release?

**Comment by constantinfite** [comment]
It's the same for 2.0 and 3.0

**Comment by wang-xinyu** [comment]
git clone -b v3.0 https://github.com/ultralytics/yolov5.git and git clone -b yolov5-v3.0 https://github.com/wang-xinyu/tensorrtx.git
and https://github.com/ultralytics/yolov5/releases/download/v3.0/yolov5s.pt

this should work fine.
