### ISSUE TITLE
Compatibility with yolov5

### ISSUE THREAD

**Issue by constantinfite** [wang-xinyu/tensorrtx#435]
Does tensorRT v1 & v3.1 support custom model ?

**Comment by wang-xinyu** [comment]
No, you can adapt it according to the v4.0, i.e. the master branch.

**Comment by constantinfite** [comment]
ok thanks, but in the v3.1 you say that 
![image](https://user-images.githubusercontent.com/57963890/110234943-8b2a6780-7f2d-11eb-9eb3-384b39780853.png)

It's wrong so ?

**Comment by wang-xinyu** [comment]
@constantinfite what did you mean custom model? if only class_num is different, then all of four versions can support.

**Comment by constantinfite** [comment]
If I train yolov5 for a specific class, for example fish or shark.
Only the version 4 will support this model that's right ?

**Comment by wang-xinyu** [comment]
No, all can 

> If I train yolov5 for a specific class, for example fish or shark.
> Only the version 4 will support this model that's right ?



> If I train yolov5 for a specific class, for example fish or shark.
> Only the version 4 will support this model that's right ?

all can do

**Comment by constantinfite** [comment]
all version of TensorRT will support this new model that's what you are saying ?

**Comment by wang-xinyu** [comment]
> all version of TensorRT will support this new model that's what you are saying ?

YES，only need to adapt the CLASS_NUM in yololayer.h
