### ISSUE TITLE
按官方教程，yolov5s v3.1版本，float16量化后python_trt推理很慢，甚至比原版Pytorch还慢

### ISSUE THREAD

**Issue by simplew2011** [wang-xinyu/tensorrtx#436]
## Env

- GPU, e.g. V100, RTX2080
- OS, e.g. Ubuntu18.04
- Cuda 10.0，cudnn7.6
- TensorRT 7.0.0

## About this repo

- v3.1
- yolov5s

## Your problem
python_trt推理很慢，要超30ms，但make C++推理正常4ms

(tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5/build$ sudo ./yolov5 -d ../samples
[03/08/2021-16:39:48] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
5ms
4ms
3ms
3ms

(tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5$ python yolov5_trt.py
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
===> 2.0595476627349854
===> 0.03826165199279785
===> 0.030884742736816406
===> 0.03745245933532715
===> 0.03125166893005371
===> 0.033860206604003906
===> 0.031084060668945312
===> 0.03644537925720215

python版的时间记录添加在：
`
### yolov5_trt.py
def infer(self, input_image_path):

#######################################
t0 = time.time()
// Do image preprocess
input_image, image_raw, origin_h, origin_w = self.preprocess_image(
input_image_path
)
// Copy input image to host buffer
np.copyto(host_inputs[0], input_image.ravel())
// Transfer input data to the GPU.
cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream)
// Run inference.
context.execute_async(bindings=bindings, stream_handle=stream.handle)
// Transfer predictions back from the GPU.
cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
// Synchronize the stream
stream.synchronize()
// Remove any context from the top of the context stack, deactivating it.
self.cfx.pop()
// Here we use the first row of output in that batch_size = 1
output = host_outputs[0]
// Do postprocess
result_boxes, result_scores, result_classid = self.post_process(
output, origin_h, origin_w
)
#######################################
print("===>", time.time() - t0)
`

调整了下发现self.preprocess_image耗时在20ms以上，self.post_process在12ms左右，中间预测耗时4ms左右。
图像预处理耗时也太长了吧。

**Comment by wang-xinyu** [comment]
把issue格式调整好。。。。

**Comment by midasklr** [comment]
> ## Env
> * GPU, e.g. V100, RTX2080
> * OS, e.g. Ubuntu18.04
> * Cuda 10.0，cudnn7.6
> * TensorRT 7.0.0
> 
> ## About this repo
> * v3.1
> * yolov5s
> 
> ## Your problem
> python_trt推理很慢，要超30ms，但make C++推理正常4ms
> 
> (tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5/build$ sudo ./yolov5 -d ../samples
> [03/08/2021-16:39:48] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
> 5ms
> 4ms
> 3ms
> 3ms
> 
> (tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5$ python yolov5_trt.py
> [TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
> ===> 2.0595476627349854
> ===> 0.03826165199279785
> ===> 0.030884742736816406
> ===> 0.03745245933532715
> ===> 0.03125166893005371
> ===> 0.033860206604003906
> ===> 0.031084060668945312
> ===> 0.03644537925720215
> 
> python版的时间记录添加在：
> `
> 
> ### yolov5_trt.py
> def infer(self, input_image_path):
> 
> #######################################
> t0 = time.time()
> // Do image preprocess
> input_image, image_raw, origin_h, origin_w = self.preprocess_image(
> input_image_path
> )
> // Copy input image to host buffer
> np.copyto(host_inputs[0], input_image.ravel())
> // Transfer input data to the GPU.
> cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream)
> // Run inference.
> context.execute_async(bindings=bindings, stream_handle=stream.handle)
> // Transfer predictions back from the GPU.
> cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
> // Synchronize the stream
> stream.synchronize()
> // Remove any context from the top of the context stack, deactivating it.
> self.cfx.pop()
> // Here we use the first row of output in that batch_size = 1
> output = host_outputs[0]
> // Do postprocess
> result_boxes, result_scores, result_classid = self.post_process(
> output, origin_h, origin_w
> )
> #######################################
> print("===>", time.time() - t0)
> `
> 
> 调整了下发现self.preprocess_image耗时在20ms以上，self.post_process在12ms左右，中间预测耗时4ms左右。
> 图像预处理耗时也太长了吧。

可以在cuda上预处理，亲测预处理不超过1ms

**Comment by simplew2011** [comment]
> > ## Env
> > 
> > * GPU, e.g. V100, RTX2080
> > * OS, e.g. Ubuntu18.04
> > * Cuda 10.0，cudnn7.6
> > * TensorRT 7.0.0
> > 
> > ## About this repo
> > 
> > * v3.1
> > * yolov5s
> > 
> > ## Your problem
> > python_trt推理很慢，要超30ms，但make C++推理正常4ms
> > (tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5/build$ sudo ./yolov5 -d ../samples
> > [03/08/2021-16:39:48] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
> > 5ms
> > 4ms
> > 3ms
> > 3ms
> > (tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5$ python yolov5_trt.py
> > [TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
> > ===> 2.0595476627349854
> > ===> 0.03826165199279785
> > ===> 0.030884742736816406
> > ===> 0.03745245933532715
> > ===> 0.03125166893005371
> > ===> 0.033860206604003906
> > ===> 0.031084060668945312
> > ===> 0.03644537925720215
> > python版的时间记录添加在：
> > `
> > ### yolov5_trt.py
> > def infer(self, input_image_path):
> > #######################################
> > t0 = time.time()
> > // Do image preprocess
> > input_image, image_raw, origin_h, origin_w = self.preprocess_image(
> > input_image_path
> > )
> > // Copy input image to host buffer
> > np.copyto(host_inputs[0], input_image.ravel())
> > // Transfer input data to the GPU.
> > cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream)
> > // Run inference.
> > context.execute_async(bindings=bindings, stream_handle=stream.handle)
> > // Transfer predictions back from the GPU.
> > cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
> > // Synchronize the stream
> > stream.synchronize()
> > // Remove any context from the top of the context stack, deactivating it.
> > self.cfx.pop()
> > // Here we use the first row of output in that batch_size = 1
> > output = host_outputs[0]
> > // Do postprocess
> > result_boxes, result_scores, result_classid = self.post_process(
> > output, origin_h, origin_w
> > )
> > #######################################
> > print("===>", time.time() - t0)
> > `
> > 调整了下发现self.preprocess_image耗时在20ms以上，self.post_process在12ms左右，中间预测耗时4ms左右。
> > 图像预处理耗时也太长了吧。
> 
> 可以在cuda上预处理，亲测预处理不超过1ms

可否提供下实现代码

**Comment by midasklr** [comment]
> > > ## Env
> > > 
> > > * GPU, e.g. V100, RTX2080
> > > * OS, e.g. Ubuntu18.04
> > > * Cuda 10.0，cudnn7.6
> > > * TensorRT 7.0.0
> > > 
> > > ## About this repo
> > > 
> > > * v3.1
> > > * yolov5s
> > > 
> > > ## Your problem
> > > python_trt推理很慢，要超30ms，但make C++推理正常4ms
> > > (tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5/build$ sudo ./yolov5 -d ../samples
> > > [03/08/2021-16:39:48] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
> > > 5ms
> > > 4ms
> > > 3ms
> > > 3ms
> > > (tensorRT) ---:/mnt/wen/tensorrtx-yolov5-v3.1/yolov5$ python yolov5_trt.py
> > > [TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
> > > ===> 2.0595476627349854
> > > ===> 0.03826165199279785
> > > ===> 0.030884742736816406
> > > ===> 0.03745245933532715
> > > ===> 0.03125166893005371
> > > ===> 0.033860206604003906
> > > ===> 0.031084060668945312
> > > ===> 0.03644537925720215
> > > python版的时间记录添加在：
> > > `
> > > ### yolov5_trt.py
> > > def infer(self, input_image_path):
> > > #######################################
> > > t0 = time.time()
> > > // Do image preprocess
> > > input_image, image_raw, origin_h, origin_w = self.preprocess_image(
> > > input_image_path
> > > )
> > > // Copy input image to host buffer
> > > np.copyto(host_inputs[0], input_image.ravel())
> > > // Transfer input data to the GPU.
> > > cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream)
> > > // Run inference.
> > > context.execute_async(bindings=bindings, stream_handle=stream.handle)
> > > // Transfer predictions back from the GPU.
> > > cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
> > > // Synchronize the stream
> > > stream.synchronize()
> > > // Remove any context from the top of the context stack, deactivating it.
> > > self.cfx.pop()
> > > // Here we use the first row of output in that batch_size = 1
> > > output = host_outputs[0]
> > > // Do postprocess
> > > result_boxes, result_scores, result_classid = self.post_process(
> > > output, origin_h, origin_w
> > > )
> > > #######################################
> > > print("===>", time.time() - t0)
> > > `
> > > 调整了下发现self.preprocess_image耗时在20ms以上，self.post_process在12ms左右，中间预测耗时4ms左右。
> > > 图像预处理耗时也太长了吧。
> > 
> > 
> > 可以在cuda上预处理，亲测预处理不超过1ms
> 
> 可否提供下实现代码

参考https://github.com/CaoWGG/TensorRT-YOLOv4中给出的cuda resize处理
