### ISSUE TITLE
RetinaFace MobileNet run fail

### ISSUE THREAD

**Issue by yueyihua** [wang-xinyu/tensorrtx#438]
$ ./face-trt -f ../imgs/ultraface.jpg -m ../models
../imgs/ultraface.jpg
../models
Version: 1.0-alpha
INVALID_ARGUMENT: getPluginCreator could not find plugin Decode_TRT version 1
safeDeserializationUtils.cpp (323) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
INVALID_STATE: std::exception
INVALID_CONFIG: Deserialize the cuda engine failed.
face-trt: src/face_detect_retina.cpp:113: int face::face_detector::init(): Assertion `trtEngin_ != nullptr' failed.
Aborted (core dumped)

采用自己编译的程序，链接libdecodeplugin.so，运行出错，直接运行retina_mnet -d没有问题

**Comment by wang-xinyu** [comment]
参考下retinaface下面的cmakelists

**Comment by yueyihua** [comment]
@wang-xinyu  把decode.cu加到自己工程编译可以，目前在Jetson xavier NX跑出来一帧是1452.28 ms；采用retina_mnet跑出来也是1475306us。达不到实时性，可以改进吗？

**Comment by yueyihua** [comment]
嗯，只看推理时间，不看首帧，时间大概在4ms左右，这个速度是正常的吗

**Comment by wang-xinyu** [comment]
正常

**Comment by yueyihua** [comment]
请教下首帧应该怎么处理下呢？

**Comment by wang-xinyu** [comment]
为什么要处理？第一帧就是会慢

**Comment by yueyihua** [comment]
嗯
