### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by Snitte** [wang-xinyu/tensorrtx#439]
Im having several issues when trying to run tensorrtx on windows.
Also having issues with make not being a windows command, i have installed an addon to have make as a command, however no makefiles can be found when following either yolov5 tutorial or the getting_started.md 

I have converted my weights and have .wts .onnx  and torchscript files.
i have yolov5 functioning however i wish to speed up inference of my custom data set and is therefore reffering to this Git. 

Thanks in advance!

**Comment by Snitte** [comment]
The tutorial reffers to 
"dirent.h for windows, put into tensorrtx/include, download from https://github.com/tronkko/dirent"
However there is not include folder?

**Comment by wang-xinyu** [comment]
tensorrtx/include does not exist, just put into anywhere your compiler can find.

**Comment by Snitte** [comment]
When running cmake i get the error 
"CMake Error at CMakeLists.txt:52 (add_executable):
  Cannot find source file:

    ${PROJECT_SOURCE_DIR}/yolov5.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at CMakeLists.txt:52 (add_executable):
  No SOURCES given to target: yolov5"
