### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by daodaoling** [wang-xinyu/tensorrtx#44]
pengzhao@pengzhao:~/tensorrtx/yolov3/build$ make
[ 25%] Building NVCC (Device) object CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o
In file included from /home/pengzhao/tensorrtx/yolov3/yololayer.cu:1:0:
/home/pengzhao/tensorrtx/yolov3/yololayer.h:8:21: fatal error: NvInfer.h: No such file or directory
compilation terminated.
CMake Error at yololayer_generated_yololayer.cu.o.Debug.cmake:219 (message):
  Error generating
  /home/pengzhao/tensorrtx/yolov3/build/CMakeFiles/yololayer.dir//./yololayer_generated_yololayer.cu.o

CMakeFiles/yololayer.dir/build.make:63: recipe for target 'CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/yololayer.dir/all' failed
make[1]: *** [CMakeFiles/yololayer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by daodaoling** [comment]
Is there anybody can help me ?

**Comment by daodaoling** [comment]
I used the tar file to install tensorrt 7.0.0.11 . cuda 10.0  .I can import tensorrt in python3 correctly . My python version is python3.7.What is wrong with my make ?

**Comment by wang-xinyu** [comment]
NvInfer.h should inside the tar package, can you find it?

**Comment by daodaoling** [comment]
Thank you ! I hava solved it !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wang Xinyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午10:48
收件人:&nbsp;"wang-xinyu/tensorrtx"<tensorrtx@noreply.github.com&gt;;
抄送:&nbsp;"叨叨令"<1981415640@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wang-xinyu/tensorrtx] make failed (#44)





 
NvInfer.h should inside the tar package, can you find it?

**Comment by Jinjicheng** [comment]
i meet the same question, how to solve it?

**Comment by wang-xinyu** [comment]
> Thank you ! I hava solved it !
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Wang Xinyu"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月12日(星期五) 上午10:48 收件人:&nbsp;"wang-xinyu/tensorrtx"<tensorrtx@noreply.github.com&gt;; 抄送:&nbsp;"叨叨令"<1981415640@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [wang-xinyu/tensorrtx] make failed (#44) NvInfer.h should inside the tar package, can you find it? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ygfrancois** [comment]
> i meet the same question, how to solve it?

if you install tensorrt by .tar way, it is not enough to "Add the absolute path to the TensorRTlib directory to the environment variable LD_LIBRARY_PATH", you should also change the lib and include path in cmake list file like:
/home/ps/yangguang/opensource_lib/tensorrtx/yolov5/CMakeLists.txt

change the path below in () to your own tensorrt lib and include path
# tensorrt
include_directories(/usr/include/x86_64-linux-gnu/)
link_directories(/usr/lib/x86_64-linux-gnu/)

then try it again
