### ISSUE TITLE
yolov5 trt inference

### ISSUE THREAD

**Issue by henbucuoshanghai** [wang-xinyu/tensorrtx#440]
## Env
I useing the official YOLOv5 docker images, In the docker images,Cuda is 11.1    and  tensorrt version 7.2.2.3
- GPU,  one RTX2080  

I have got the yolov5s.wts and    'make'       successfuly. I want to use the tensorrtx/yolov5 to get the  .engine       

## Your problem
command ：   ./yolov5 -s yolov5s.wts yolov5s.engine s

Loading weights: yolov5s.wts
CUDA error 222 at  /tensorrtx/yolov5/yololayer.cu:37yolov5: tensorrtx/yolov5/yololayer.cu:37: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(int, int, int, int, const std::vector<Yolo::YoloKernel>&): Assertion `0' failed.
Aborted (core dumped)

11.1 is too high??cuda  is wrong?maybe lower?like 10.1?

**Comment by wang-xinyu** [comment]
where did you get the .pt,  you need download .pt from release tag.

**Comment by henbucuoshanghai** [comment]
Different versions of yolov5
Currently, we support yolov5 v1.0(yolov5s only), v2.0, v3.0, v3.1 and v4.0.

For yolov5 v4.0, download .pt from yolov5 release v4.0, git clone -b v4.0 https://github.com/ultralytics/yolov5.git and git clone https://github.com/wang-xinyu/tensorrtx.git.


I use the v4.0  and the pt is from v4.0..

**Comment by henbucuoshanghai** [comment]
i have run the lenet and googlenet   , successfuly!!  get the .engine and can be deserialized.
but the yolov5   has this error.............

**Comment by henbucuoshanghai** [comment]
I have run the yolov4 ,It has the same error  .I changed nothing about the repo.
help.. tks 


Loading weights: ../yolov4.wts
CUDA error 222 at /tensorrtx/yolov4/yololayer.cu:19yolov4:         /tensorrtx/yolov4/yololayer.cu:19: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(): Assertion `0' failed.
Aborted (core dumped)

**Comment by wang-xinyu** [comment]
@henbucuoshanghai you cuda is not properly installed.

**Comment by dubaochen** [comment]
@henbucuoshanghai Has the problem been solved？ I have the same problem.

**Comment by henbucuoshanghai** [comment]
no

**Comment by wang-xinyu** [comment]
yololayer.cu is writen in cuda, so you need to check your if nvcc is working properly.

**Comment by Yaoxingtian** [comment]
Anybody had solved this problem ? I meet it too, pls. help !!

**Comment by saladjay** [comment]
> Anybody had solved this problem ? I meet it too, pls. help !!

do you solve this problem?
