### ISSUE TITLE
Building of yolov5 model 

### ISSUE THREAD

**Issue by gigwegbe** [wang-xinyu/tensorrtx#442]
## Env

- GPU, e.g. 1050ti
- OS, e.g. Ubuntu18.04
- Cuda version 10.2
- TensorRT version 7.2.3

## About this repo

- which branch/tag/commit are you using? 
- which model? yolov5, v3.0

## Your problem

- what is your command? 
I followed the instruction in the [readme](https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/yolov5) and ran the command  `make`
- what's your output?
`
[ 40%] Built target myplugins
Scanning dependencies of target yolov5
[ 60%] Building CXX object CMakeFiles/yolov5.dir/yolov5.cpp.o
[ 80%] Linking CXX executable yolov5
/usr/bin/ld: warning: libcublas.so.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublasLt.so.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoGetHeuristic@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatrixLayoutDestroy@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulPreferenceCreate@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatrixLayoutCreate@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoCheck@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulPreferenceDestroy@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtGetProperty@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoConfigSetAttribute@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasGemmStridedBatchedEx@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmul@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasCreate_v2@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtDestroy@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoConfigGetAttribute@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulPreferenceSetAttribute@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLoggerConfigure@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatrixLayoutSetAttribute@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoInit@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasDestroy_v2@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasSgemmEx@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasGemmEx@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoCapGetAttribute@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasSetStream_v2@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasSetMathMode@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtCreate@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasGetProperty@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulDescCreate@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasSgemmStridedBatched@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulDescSetAttribute@libcublasLt.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasHgemmStridedBatched@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasGetMathMode@libcublas.so.11'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libmyelin.so.1: undefined reference to `cublasLtMatmulDescDestroy@libcublasLt.so.11'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5.dir/build.make:175: recipe for target 'yolov5' failed
make[2]: *** [yolov5] Error 1
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

 

`
- what output do you expect?
successful compilation

**Comment by wang-xinyu** [comment]
Hi, you are using cuda10.2, but you libs are linking cuda11. you can try reinstall cuda.

**Comment by gigwegbe** [comment]
Thanks for the swift response. Cuda 11.2 reinstalled and the compilation successful.

**Comment by gigwegbe** [comment]
I ran the command `make`
The output: 
/home/george/Documents/MLANDAI/vibes/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

/home/george/Documents/MLANDAI/vibes/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

Scanning dependencies of target myplugins
[ 40%] Linking CXX shared library libmyplugins.so
[ 40%] Built target myplugins
Scanning dependencies of target yolov5
[ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
[ 80%] Building CXX object CMakeFiles/yolov5.dir/yolov5.cpp.o
[100%] Linking CXX executable yolov5
[100%] Built target yolov5

However, when I ran the `sudo build/yolov5 -s`
The output: 
arguments not right!
./yolov5 -s [.wts] [.engine] [s/m/l/x or c gd gw]  // serialize model to plan file
./yolov5 -d [.engine] ../samples  // deserialize plan file and run inference

Question: 
What is the right arguments?

**Comment by gigwegbe** [comment]
Resolved the above issue. Got another one after training a custom model with one class.  
- Ran the command below:
./yolov5 -s
- The output: 
Loading weights: ../yolov5s.wts
[03/17/2021-21:10:29] [E] [TRT] (Unnamed Layer* 17) [Convolution]: kernel weights has count 0 but 2048 was expected
[03/17/2021-21:10:29] [E] [TRT] (Unnamed Layer* 17) [Convolution]: count of 0 weights in kernel, but kernel dimensions (1,1) with 64 input channels, 32 output channels and 1 groups were specified. Expected Weights count is 64 * 1*1 * 32 / 1 = 2048
[03/17/2021-21:10:29] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::484, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /media/george/DATA/nvidia_workspace/yolov5/vibes/tensorrtx/yolov5/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted (core dumped)

**Comment by wang-xinyu** [comment]
@gigwegbe Hi， can you go through tensorrtx/yolov5/readme again? For custom class_num.

**Comment by hdnh2006** [comment]
No matter what I do, I always get the following message:

```
sudo ./yolov5 -s [.wts] [.engine] [s/m/l/x/s6/m6/l6/x6 or c/c6 gd gw]  // serialize model to plan file
arguments not right!
./yolov5 -s [.wts] [.engine] [s/m/l/x/s6/m6/l6/x6 or c/c6 gd gw]  // serialize model to plan file
./yolov5 -d [.engine] ../samples  // deserialize plan file and run inference

```

No error is gotten before this. I also have tried `sudo ./yolov5 -s`, same error is gotten. Any help will be appreciated.

**Comment by wang-xinyu** [comment]
@hdnh2006 Can u open a new thread and use issue template? This was closed.
