### ISSUE TITLE
Does this repository support image downsampling and data augmentation from YOLOv5?

### ISSUE THREAD

**Issue by rocketsfallonrocketfalls** [wang-xinyu/tensorrtx#444]
Hi, 

In YOLOv5 from ultralytics', the implementation takes care of data augmentation and input resolution downsampling per se. Specifically data augmentation provide really good performance increase for me. 

Do I need to implement pre-processing for this repository or does it already support it while generating .wts file from the .pt file?

Thanks.

**Comment by wang-xinyu** [comment]
There is no data augmentation covered in this repo. We mainly care about the TensorRT implementation.

**Comment by rocketsfallonrocketfalls** [comment]
Hey @wang-xinyu , thanks for the lightning-fast reply. 

What about downsampling? 

Say I have an image set with a resolution of 4000x3000, but I trained a YOLOv5 model from ultralytics using resolution parameter with 416x320. 

Do I need to use a set of 416x320 images for inference, or will it downsample to what I want no matter which resolution I input to the project executable?

**Comment by wang-xinyu** [comment]
@rocketsfallonrocketfalls Sure, any shape images will be resized and padded to `INPUT_W` and `INPUT_H` before feed into network, just go through the source code.

**Comment by rocketsfallonrocketfalls** [comment]
Thank you very much for on point responses.
