### ISSUE TITLE
int8 for yolov5 v3.0

### ISSUE THREAD

**Issue by luhaijun** [wang-xinyu/tensorrtx#445]
您好：
感谢您伟大的代码，牛批！
我想问下如果想把v3.0的版本支持int8量化，需要修改啥

**Comment by wang-xinyu** [comment]
Hi @luhaijun, 主要需要calibrator.cpp 和 calibrator.h，还有yolov5.cpp中#elif defined(USE_INT8)部分的代码

**Comment by luhaijun** [comment]
谢谢发自我的荣耀手机-------- 原始邮件 --------发件人： Wang Xinyu ***@***.***>日期： 2021年3月18日周四 10:58收件人： wang-xinyu/tensorrtx ***@***.***>抄送： luhaijun ***@***.***>, Mention ***@***.***>主    题： Re: [wang-xinyu/tensorrtx] int8 for yolov5 v3.0 (#445)

Hi @luhaijun, 主要需要calibrator.cpp 和 calibrator.h，还有yolov5.cpp中#elif defined(USE_INT8)部分的代码
