### ISSUE TITLE
Yolov4 int8

### ISSUE THREAD

**Issue by maidmentdaniel** [wang-xinyu/tensorrtx#446]
Hi, I've been banging my head for a couple weeks trying to get int8 calibration working for yolov4. I stumbled onto your repo this morning and I noticed you've implemented int8 calibration for v5 and v3 but not v4. Is there a reason why? Would you be able to assist me in porting your calibration code to yolov4?

Thanks,

**Comment by maidmentdaniel** [comment]
Also, your work is clear and well done. It's been very nice to go through.

**Comment by wang-xinyu** [comment]
@maidmentdaniel  Hi, you can refer to v3 or v5 to implement v4 int8, it's easy.
mainly need calibrator.cpp and calibrator.h and `#elif defined (USE_INT8)` block.

**Comment by maidmentdaniel** [comment]
yeah, figured it out. Was quite easy. Thank you.

**Comment by JiweiMaster** [comment]
@maidmentdaniel Hi! Did you test the int8 mode of YOLOV4? After modifying it, I feel that the speed is not much faster
