### ISSUE TITLE
What are the main differences between the code in tensorrtx/yolov5 for YOLOv5 v2.0, YOLOv5 v4.0?

### ISSUE THREAD

**Issue by rocketsfallonrocketfalls** [wang-xinyu/tensorrtx#447]
Hey, 

I've edited the main code in tensorrtx/yolov5 that is for YOLOv5 v2.0  for my needs  and it works wonders(thanks for the repo!). 

But now I want to try YOLOv5 v4.0 with the edited version. 

I can still use the proper version of your repository for **serialization and gen_wts.py**. **But for deserialization**, can I still use the program with -d argument in the version of tensorrtx/yolov5 for YOLOv5 v2.0?

Thanks

**Comment by wang-xinyu** [comment]
For the master branch(yolov5 v4.0), the cmd args looks like

```
./yolov5 -d yolov5.engine ../samples
```

while for v2.0, the `yolov5.engine` was hard coded in yolov5.cpp.

Just try to understand the codes, and you can revise it yourself, it is easy.

**Comment by rocketsfallonrocketfalls** [comment]
Alright, thanks!
