### ISSUE TITLE
Detect multi classes

### ISSUE THREAD

**Issue by Doanhdz** [wang-xinyu/tensorrtx#448]
First thanks for your great work. I have a question: how can i modify your code to train with multi classes?

**Comment by wang-xinyu** [comment]
which model?

**Comment by Doanhdz** [comment]
Thanks for your response. I use restinafce with backbone mobilenetV1.

**Comment by wang-xinyu** [comment]
retinaface can only detect face. If you revise the model to train with multi-class, you need also adapt the model in retinaface_mnt.cpp accordingly.

**Comment by Doanhdz** [comment]
Thanks you, I will try.
