### ISSUE TITLE
Yolov5 cannot be compiled on a set resolution

### ISSUE THREAD

**Issue by orisaacs** [wang-xinyu/tensorrtx#450]
I'm attempting to run a tensorrt yolov5 model on 4k images (3840x2160) on the latest master branch, however I receive the following error on compiling the engine with this resolution:
![image](https://user-images.githubusercontent.com/20534598/111911662-29124c00-8a6f-11eb-9046-1c12cf843d77.png)
When using a height of 2170 the issue doesn't pop up, so it's likely to be related to downsampling ratios of the network.

Thanks in advance and keep up the good work.

**Comment by wang-xinyu** [comment]
w and h must be divisible by 32.

**Comment by orisaacs** [comment]
Thanks, I recommend to add an assertion/comment to prevent further questions on the subject.

**Comment by wang-xinyu** [comment]
Yes, you are right. But I'll recommend to understand how yolov5 works before using this repo.
