### ISSUE TITLE
trt yolov5 inference

### ISSUE THREAD

**Issue by sodargreen** [wang-xinyu/tensorrtx#451]
## Env

- GPU  Nano.
- OS Ubuntu16.04
- Cuda 10.2
- TensorRT 7.1.3

## About this repo

- which branch/tag/commit are you using? I have tried all the release version: 1.0/2.0/3.0 , etc
- which model? yolov5s

##  problem

- I don't have any problem while generating .wts from pytorch with .pt and building engine for yolov5, but when I run
- `sudo ./yolov5 -s yolov5s.wts yolov5s.engine s`
- the output is 
- `Loading weights: yolov5s.wts
[03/24/2021-16:58:04] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/dazhege/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion 'scale_1' failed.
Aborted`
plus, the pytorch version upgrade form 1.6 to 1.7 cause 1.6 can't generate .wts, I also got some warning information only when I generate .wts from yolov5s.pt(v1.0),here
`/.local/lib/python3.6/site-packages/torch/serialization.py:658: SourceChangeWarning: source code of class 'torch.nn.modules.upsampling.Upsample' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.`
what should I do ?

**Comment by wang-xinyu** [comment]
can you read here again? and follow it.
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

**Comment by sodargreen** [comment]
> can you read here again? and follow it.
> https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

thx so much

**Comment by UUUserna** [comment]
I have same problem, but I follow the tutorial given by @wang-xinyu :
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5
And I didn't got warning information when I generate .wts from my own best.pt.

my command is :     yolov5 -s ../yolov5_test1.wts yolov5_test1.engine s
my problem is :   [E] [TRT] Parameter check failed at: Network.cpp::nvinfer1::Network::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
Assertion failed: scale_1, file f:\yolov5\common.hpp, line 155

what should I do ? Thx

**Comment by wang-xinyu** [comment]
@UUUserna You can firstly make sure the official model can work. And then try your own model.

If there is a problem, you need to compare your own model with the official one to find the difference.

**Comment by UUUserna** [comment]
@wang-xinyu official model also can't work, but your previous version code can

**Comment by wang-xinyu** [comment]
> @wang-xinyu official model also can't work, but your previous version code can

pls open a new issue with template to describe your problem.

**Comment by sctrueew** [comment]
Hi,

I'm using [PolygonDetection](https://github.com/XinzeLee/PolygonObjectDetection)  in Tensort c++.

I could generate polygon_yolov5s_ucas.wts but when I want to make an engine I get this error.

[E] [TRT] 3: [network.cpp::nvinfer1::Network::addScale::735] Error Code 3: Internal Error (Parameter check failed at: network.cpp::nvinfer1::Network::addScale::735, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)

The model has 2 classes and size is 1024: I have set 
CLASS_NUM: 2
INPUT_H: 1024
INPUT_W: 1024

Thanks
