### ISSUE TITLE
unet speed

### ISSUE THREAD

**Issue by 1372072273** [wang-xinyu/tensorrtx#452]
我测试了unet ，用了同样的unet模型  FP16 256*256 batch_size 8 速度大概是120ms左右，显卡是P4000 不知道为什么达不到20ms

**Comment by wang-xinyu** [comment]
为什么应该达到20ms？

**Comment by 1372072273** [comment]
因为和给定的测试时间差的有点多，我检查了一下，转换用的都是tensorrtx的代码，不知道为什么差了这么多，我在用libtorch测得时间是35到40ms

**Comment by wang-xinyu** [comment]
给定的测试时间在哪里

**Comment by DogeZen** [comment]
你是不是只测试了一张图，sample文件夹多放几张图试试，第一张一般都会很慢，后面就快了
