### ISSUE TITLE
Different prediction results between tensorrtx and YOLO's detect.py

### ISSUE THREAD

**Issue by khushbuadav** [wang-xinyu/tensorrtx#453]
## Env

- GPU - Jetson Xavier NX
- OS - Ubuntu 18.04.5
- Cuda version - 10.2.89
- TensorRT version - latest (yolov5-v3.1)
- Yolov5 version - yolov5 v4.0
## About this repo

- Tensorrt - master branch 
- Model - I have trained yolov5s.pt on custom dataset

## Problem

I have trained **yolov5s.pt** on custom dataset. I am using best.pt from that training to detect objects from sample images.   
I came across this repo to improve the inference time. I was able to get the speed improvement, however, I got different detection results on the same images.

I have followed all the steps given on https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5 link. 
Did all the necessary changes in the repo:
``` diff
diff --git a/yolov5/yololayer.h b/yolov5/yololayer.h
index 9b91c1a..89185f7 100644
--- a/yolov5/yololayer.h
+++ b/yolov5/yololayer.h
@@ -16,7 +16,7 @@ namespace Yolo
         float anchors[CHECK_COUNT * 2];
     };
     static constexpr int MAX_OUTPUT_BBOX_COUNT = 1000;
-    static constexpr int CLASS_NUM = 80;
+    static constexpr int CLASS_NUM = 8;
     static constexpr int INPUT_H = 608;
     static constexpr int INPUT_W = 608;

diff --git a/yolov5/yolov5.cpp b/yolov5/yolov5.cpp
index 9c95206..4a543c1 100644
--- a/yolov5/yolov5.cpp
+++ b/yolov5/yolov5.cpp
@@ -6,10 +6,10 @@
 #include "utils.h"
 #include "calibrator.h"

-#define USE_FP16  // set USE_INT8 or USE_FP16 or USE_FP32
+#define USE_FP32  // set USE_INT8 or USE_FP16 or USE_FP32
 #define DEVICE 0  // GPU id
-#define NMS_THRESH 0.4
-#define CONF_THRESH 0.5
+#define NMS_THRESH 0.45
+#define CONF_THRESH 0.25
 #define BATCH_SIZE 1
```

**Image details** 
- Image1.jpg: 
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 2448x784, frames 3

- Image2.jpg: 
JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 2448x784, frames 3

**Inference and NMS settings:**  
```
NMS_THRESH = 0.45
CONF_THRESH = 0.25
CLASS_NUM = 8
```

As suggested by [@glen-jocher](https://github.com/glenn-jocher) [here](https://github.com/ultralytics/yolov5/issues/2572) I have used the same inference and NMS settings for both methods. To rule out size mismatch, I tried with two different image-size `608` and `640`. Still, I see the difference in the prediction result. 

The comparison between tensorrtx and yolov5 prediction using: 

**1. INPUT_H = 608 and INPUT_W = 608**

| Method | Image Name| lablel_1 | label_2 | label_3|  label_4 |  label_5 |  label_6|  label_7| label_8| Total 
|--------|--------|------|--------|------|------|------|--------|------|------|------|
| Tensorrtx | Image1.jpg |7 | 7 | 14 | 16 | 0 |0 |1 |0 | 45
| YOLOv5 | Image1.jpg |11 | 6 | 14 | 15 | 0 |0 |0 |0 | 45
| Tensorrtx | Image2.jpg |15 | 0 | 22 | 15 | 0 |1 |0 |0 |53
| YOLOv5 | Image2.jpg |18 | 0 | 22 | 11 | 0 |0 |0 |0 | 51

**2. INPUT_H = 640 and INPUT_W = 640**

| Method | Image Name| lablel_1 | label_2 | label_3|  label_4 |  label_5 |  label_6|  label_7| label_8| Total 
|--------|--------|------|--------|------|------|------|--------|------|------|------|
| Tensorrtx | Image1.jpg |1 | 0 | 2 | 34 | 6 |2 |5 |0 | 50
| YOLOv5 | Image1.jpg |12 | 3 | 11 | 15 | 3 |1 |0 |0 | 45
| Tensorrtx | Image2.jpg |8 | 0 | 2 | 23 | 6 |3 |2 |0 |44
| YOLOv5 | Image2.jpg |14 | 1 | 17 | 12 | 1 |0 |0 |0 | 45

Commands I ran for inference:
Tensorrtx: `sudo ./yolov5 -d yolov5_custom.engine /sample/images/`
Yolo Python: `python3.6 ./detect.py --source /sample/images/ --weights custom_best.pt --conf 0.25 --save-txt --img-size 608`

I did not expect such a vast difference in the inference between the two methods. Any idea, what might be the issue or what things i can try to narrow down to the problem?

**Comment by wang-xinyu** [comment]
- TensorRT version - latest (yolov5-v3.1)
- Yolov5 version - yolov5 v4.0

can you double check the version? and can you try follow here first to check the official models? https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

**Comment by khushbuadav** [comment]
Sorry @wang-xinyu for the misunderstanding. I had used the latest tensorRT version `git clone https://github.com/wang-xinyu/tensorrtx.git`

```
$ git log --oneline
a7f43a3 (HEAD -> master, origin/master, origin/HEAD) Update README.md
4b2ef40 tensorRT RefineDet (#443)
...
```

**Comment by wang-xinyu** [comment]
okay, so can you follow here first to check the official trained model?  https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

**Comment by khushbuadav** [comment]
@wang-xinyu , I am using a custom trained model on custom images. I followed the instructions here https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#how-to-run-yolov5s-as-example to generate `yolov5_custom.wts` and then `yolov5_custom.engine` file from the trained `.pt` file.

**Comment by wang-xinyu** [comment]
I know, if your custom model is different from the official one, it will not work properly. So you'd better try the official one first. And then compare your model with the official model.

**Comment by humamamouri** [comment]
@khushbuadav I'm facing the same problem where I've noticed that I get considerably fewer detections using the tensorrt engine. Have you understood what's happening?
