### ISSUE TITLE
Retina Face FP32

### ISSUE THREAD

**Issue by tune98** [wang-xinyu/tensorrtx#456]
Hello wang-zinyu, 
I followed your guideline to export FP32 engine R50 model. But model dosen't detect any face on worlds-largest-selfie.jpg
My result is below: 
![0_result](https://user-images.githubusercontent.com/70105577/112754651-3eefb600-9007-11eb-9349-d08c6a464001.jpg)

**Comment by wang-xinyu** [comment]
It will save another image file like `0_result.jpg`. did you check that?

**Comment by tune98** [comment]
I checked that. The picture above is 0_result.jpg. :(

**Comment by tune98** [comment]
I only modified #define USE_FP32 in Line 12, retina_r50.cpp. The result in terminal is below. 
![Screenshot from 2021-03-29 13-55-18](https://user-images.githubusercontent.com/70105577/112797989-6f326580-9096-11eb-9f8c-be6db001b021.png)

**Comment by wang-xinyu** [comment]
where did you get the .pt model?

**Comment by tune98** [comment]
I download pth model from https://github.com/biubug6/Pytorch_Retinaface. Then i followed your guildline to get retinaface.pth and retinaface.wts.

**Comment by wang-xinyu** [comment]
can you try the .wts from model zoo of this repo? and compare the content with your retinaface.wts.

**Comment by tune98** [comment]
I will try later and report the result to you.

**Comment by tune98** [comment]
I tried the .wts from model zoo of this repo. But nothing changed. :( 
![Screenshot from 2021-03-29 18-14-51](https://user-images.githubusercontent.com/70105577/112829120-dc57f200-90ba-11eb-9a64-32b911d0b28f.png)

**Comment by tune98** [comment]
Which Cuda, Cudnn version you use? 
My Environment: 
Cuda 11.0
Cudnn 8.0.5
TensorRT 7.1.3
OpenCV 3.4.12

**Comment by wang-xinyu** [comment]
you can find my Env in repo's readme.

**Comment by tune98** [comment]
Have you evaluted speed and accuracy model FP16 on WIDER FACE?

**Comment by tune98** [comment]
I've solved this problem. This is issue of my device. I will close this topic.
