### ISSUE TITLE
Yolov5 python batch inference

### ISSUE THREAD

**Issue by fColangelo** [wang-xinyu/tensorrtx#457]
## Env

- GPU: T4 
- OS: Ubuntu 20.04 (From Nvidia pytorch official docker image)
- Cuda version: 11.2
- TensorRT version: 7.2.3.4

## About this repo

- which branch/tag/commit are you using? Master
- which model? yolov5, retinaface? yolov5, release 4.0 (cloned according to instructions)

## Your problem

Hi and thanks for the wonderful repo.
I am trying to run batch inference with a standard yolov5s in python. I have verified that i can correctly do inference on a single image. However, I cannot seem to get batch inference to work. What I did:
* Compiled the model with appropriate BATCH_SIZE setting in yolov5.cpp
* Wrote a simple python code to perform batch inference based on the yolo5_trt.py example
* Verified that the model input is correct (B, C, H, W). 

The problem is: when i get to post-process output, detection for the first image appears to be ok (output[0] = 80, so I expect the next 80*6 elements to pertain to the first image, and it appears to be the case). After that however, all values in output are 0.0. The batch is composed of copies of the same image, so the detections should be there. Could you please provide any direction on how to solve this issue?
Thanks!

**Comment by wang-xinyu** [comment]
Hi, you may need to go through the c++ code to check how to do batch inference. Basically need following steps:

- prepare batch data
- copy batch data to GPU
- do batch inference
- copy batch result from GPU to CPU
- decode the batch result and draw on images

**Comment by fColangelo** [comment]
Hi and thank you for you answer. Concerning the basic steps:

* The batch data were prepared correctly (verfied that each batch element can be transformed back into an image)
* Copied the batch into the pre-allocated buffer ( np.copyto(host_inputs[0], image_batch.ravel()),  cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream))
* Did inference with  context.execute_async(bindings=bindings, stream_handle=stream.handle)
* Copied the data back (cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream), stream.synchronize(), output = host_outputs[0])
Decoding output however, I seem to obtain results only for the first image (Output contains the data for 80 boxes and just zeros afterward)
Are there specific instructions to perform batch inference in python, or is there something else wrong? 
I will study the C++ code, but am not really familiar with the language. Any pointer to a specific code section would be very helpful. 
Thanks!

**Comment by linye-boli** [comment]
> Hi and thank you for you answer. Concerning the basic steps:
> 
> * The batch data were prepared correctly (verfied that each batch element can be transformed back into an image)
> * Copied the batch into the pre-allocated buffer ( np.copyto(host_inputs[0], image_batch.ravel()),  cuda.memcpy_htod_async(cuda_inputs[0], host_inputs[0], stream))
> * Did inference with  context.execute_async(bindings=bindings, stream_handle=stream.handle)
> * Copied the data back (cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream), stream.synchronize(), output = host_outputs[0])
>   Decoding output however, I seem to obtain results only for the first image (Output contains the data for 80 boxes and just zeros afterward)
>   Are there specific instructions to perform batch inference in python, or is there something else wrong?
>   I will study the C++ code, but am not really familiar with the language. Any pointer to a specific code section would be very helpful.
>   Thanks!

same issue

**Comment by wang-xinyu** [comment]
yolov5 batch inference had already been addressed.
