### ISSUE TITLE
加载多个engine模型

### ISSUE THREAD

**Issue by botao1995** [wang-xinyu/tensorrtx#461]
你好，经过上次我成功的使用加锁的方式使用多线程调用了engine模型，但目前遇到了以下几点问题
1、在模型很多的情况下，如何实现模型的管理？(100来个模型，不同进程根据实际用户要求加载或卸载不同的模型)这点我在网上看到了nvidia triton，
2、如果要做yolov5的实时任务的话，本地NGC nvidia triton 性能是否有所延迟？triton与客户端通信是依赖grpc，http的
3，数据量来说的话确实庞大，生成一个模型也不是很好，若以上方法不能解决的话还有其他方案吗，

**Comment by linye-boli** [comment]
> 你好，经过上次我成功的使用加锁的方式使用多线程调用了engine模型，但目前遇到了以下几点问题
> 1、在模型很多的情况下，如何实现模型的管理？(100来个模型，不同进程根据实际用户要求加载或卸载不同的模型)这点我在网上看到了nvidia triton，
> 2、如果要做yolov5的实时任务的话，本地NGC nvidia triton 性能是否有所延迟？triton与客户端通信是依赖grpc，http的
> 3，数据量来说的话确实庞大，生成一个模型也不是很好，若以上方法不能解决的话还有其他方案吗，

请问成功调用了多个模型么？我现在做的任务是利用多个模型预测同一个数据，请问您有没有好的办法或者样例

**Comment by botao1995** [comment]
> > 你好，经过上次我成功的使用加锁的方式使用多线程调用了engine模型，但目前遇到了以下几点问题
> > 1、在模型很多的情况下，如何实现模型的管理？(100来个模型，不同进程根据实际用户要求加载或卸载不同的模型)这点我在网上看到了nvidia triton，
> > 2、如果要做yolov5的实时任务的话，本地NGC nvidia triton 性能是否有所延迟？triton与客户端通信是依赖grpc，http的
> > 3，数据量来说的话确实庞大，生成一个模型也不是很好，若以上方法不能解决的话还有其他方案吗，
> 
> 请问成功调用了多个模型么？我现在做的任务是利用多个模型预测同一个数据，请问您有没有好的办法或者样例

预测同一个数据应该没有必要

**Comment by linye-boli** [comment]
> > > 你好，经过上次我成功的使用加锁的方式使用多线程调用了engine模型，但目前遇到了以下几点问题
> > > 1、在模型很多的情况下，如何实现模型的管理？(100来个模型，不同进程根据实际用户要求加载或卸载不同的模型)这点我在网上看到了nvidia triton，
> > > 2、如果要做yolov5的实时任务的话，本地NGC nvidia triton 性能是否有所延迟？triton与客户端通信是依赖grpc，http的
> > > 3，数据量来说的话确实庞大，生成一个模型也不是很好，若以上方法不能解决的话还有其他方案吗，
> > 
> > 
> > 请问成功调用了多个模型么？我现在做的任务是利用多个模型预测同一个数据，请问您有没有好的办法或者样例
> 
> 预测同一个数据应该没有必要

您好，我的意思我有不同的四个模型，但是想要inference一个data，比如相同时进行目标检测和深度图计算，这两个任务分别用不同的tensorrt engine

**Comment by botao1995** [comment]
> > > > 你好，经过上次我成功的使用加锁的方式使用多线程调用了engine模型，但目前遇到了以下几点问题
> > > > 1、在模型很多的情况下，如何实现模型的管理？(100来个模型，不同进程根据实际用户要求加载或卸载不同的模型)这点我在网上看到了nvidia triton，
> > > > 2、如果要做yolov5的实时任务的话，本地NGC nvidia triton 性能是否有所延迟？triton与客户端通信是依赖grpc，http的
> > > > 3，数据量来说的话确实庞大，生成一个模型也不是很好，若以上方法不能解决的话还有其他方案吗，
> > > 
> > > 
> > > 请问成功调用了多个模型么？我现在做的任务是利用多个模型预测同一个数据，请问您有没有好的办法或者样例
> > 
> > 
> > 预测同一个数据应该没有必要
> 
> 您好，我的意思我有不同的四个模型，但是想要inference一个data，比如相同时进行目标检测和深度图计算，这两个任务分别用不同的tensorrt engine

不考虑延迟的情况或许nvidia triton能够解决你的问题

**Comment by loyneshunter** [comment]
> > > > 你好，经过上次我成功的使用加锁的方式使用多线程调用了engine模型，但目前遇到了以下几点问题
> > > > 1、在模型很多的情况下，如何实现模型的管理？(100来个模型，不同进程根据实际用户要求加载或卸载不同的模型)这点我在网上看到了nvidia triton，
> > > > 2、如果要做yolov5的实时任务的话，本地NGC nvidia triton 性能是否有所延迟？triton与客户端通信是依赖grpc，http的
> > > > 3，数据量来说的话确实庞大，生成一个模型也不是很好，若以上方法不能解决的话还有其他方案吗，
> > > 
> > > 
> > > 请问成功调用了多个模型么？我现在做的任务是利用多个模型预测同一个数据，请问您有没有好的办法或者样例
> > 
> > 
> > 预测同一个数据应该没有必要
> 
> 您好，我的意思我有不同的四个模型，但是想要inference一个data，比如相同时进行目标检测和深度图计算，这两个任务分别用不同的tensorrt engine

你好，你的问题解决了么？我也遇到了加载多个engine的问题。
