### ISSUE TITLE
concat multiple tensorrt yolov5 engine

### ISSUE THREAD

**Issue by linye-boli** [wang-xinyu/tensorrtx#462]
## Env

tensorrtx docker

## About this repo

- which branch/tag/commit are you using?
master
- which model? yolov5, retinaface?
multiple yolov5_l

## Your problem

I can inference yolov5 successfully by yolov5_trt.py. 
Now, I generate two yolov5 engines.
I wonder how can I inference same data for 2 different yolov5 engine in order.  
In order to save time, I don't want to copy data from cpu to gpu multiple times

**Comment by wang-xinyu** [comment]
You can copy your input data from cpu to gpu only once. And use the gpu data to inference using two models separately.
