### ISSUE TITLE
Yolov5 v4 no bounding box after conversion 

### ISSUE THREAD

**Issue by abhigoku10** [wang-xinyu/tensorrtx#465]
## Env

- GPU, GT Mx 130
- OS,  Ubuntu18.04
- Cuda version 11.1
- TensorRT version 7.2

## About this repo

model  yolov5 release v4.0, 

## Your problem

Hi when i follow the commands and run  
step1 :
make 
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

Scanning dependencies of target myplugins
[ 40%] Linking CXX shared library libmyplugins.so
[ 40%] Built target myplugins
Scanning dependencies of target yolov5
[ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
[ 80%] Building CXX object CMakeFiles/yolov5.dir/yolov5.cpp.o
[100%] Linking CXX executable yolov5
[100%] Built target yolov5

step2: 
sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
Loading weights: yolov5s.wts
Building engine, please wait for a while...
[04/07/2021-18:12:54] [W] [TRT] Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
Build engine successfully!

step3 : 
sudo ./yolov5 -d yolov5s.engine ../samples
189ms
51ms
but not able to get bounding boxes on the images and i then checked 
python3 yolov5_trt.py
i am not getting any predictions at all the prediction tensor is empty 
@wwqgtxx @rymzt  can you share ur insights on this 
THanks in adavance

**Comment by wang-xinyu** [comment]
where did you download yolov5s.pt?

**Comment by abhigoku10** [comment]
@wang-xinyu  https://github.com/ultralytics/yolov5/releases/tag/v4.0 for this location i have checked with s,l,m all give me same results

**Comment by wang-xinyu** [comment]
Can you try the .wts(yolov5s-v4.0) in Model Zoo of this repo?

**Comment by abhigoku10** [comment]
@wang-xinyu  i tried use the same weight in model zoom yet i am not able to see the bounding boxes for any of the models s/l/m of v4 and v3

**Comment by wang-xinyu** [comment]
It works fine on my side. Not sure if mx130 can work well. Can you try another GPU? or try TensorRT7.0.

**Comment by abhigoku10** [comment]
@wang-xinyu  i tried with other systems also but hear my observations 
1. I am to convert the model with the steps mentioned but i am not getting bounding box when i run thru command prompt , but the inference time is showing 32ms,33ms but no output is written 
2. I tried to run the trt model using yolo_trt.py here there is no predictions at all 
3. 
![image](https://user-images.githubusercontent.com/22094053/130113264-a8dd3156-84f7-417a-a4d5-3d21e8ad54c9.png)

and i get the following error 
  boxes = boxes[si, :]
RuntimeError: CUDA error: no kernel image is available for execution on the device
can you pls share your thoughts on this

**Comment by wang-xinyu** [comment]
@abhigoku10 refer to the readme for different yolov5 versions. and try official model first

**Comment by abhigoku10** [comment]
@wang-xinyu  i tried with s/m i am facing the same issue these version of the model ie v5,v4
