### ISSUE TITLE
Error : LNK2019

### ISSUE THREAD

**Issue by UUUserna** [wang-xinyu/tensorrtx#469]
##Env

- GPU : RTX1050
- OS : Win10
- Cuda version : 11.0
- Tensor RT version : 7.1.3.4

About this repo

- which model? yolov5
- refer to tutorials/run-on-windows

My problem

- After Cmake , rising Error when generate solution : 
错误	LNK2019	无法解析的外部符号 "private: char * __thiscall cv::String::allocate(unsigned int)"

**Comment by wang-xinyu** [comment]
Maybe your C++ compiler is too old? Does it support c++11?

**Comment by UUUserna** [comment]
now I used gcc 7.3.0 , but error still exist

**Comment by UUUserna** [comment]
Sorry I find the problem , my Path of opencv is vs15/bin , but I am using vs14 .  Thank you so much
