### ISSUE TITLE
Feature request: Retinaface AntiCov Batch inference

### ISSUE THREAD

**Issue by sealedtx** [wang-xinyu/tensorrtx#471]
- which branch/tag/commit are you using? **master**
- which model? **retinafaceAntiCov**

## Your problem
Thank you for this TRT implementation! Is it possible to add support for batch > 1?
https://github.com/wang-xinyu/tensorrtx/blob/12f7c1b8b103b1fba60daed15d6ce35c50b0319b/retinafaceAntiCov/retinafaceAntiCov.cpp#L27

**Comment by wang-xinyu** [comment]
Hi, you can refer to https://github.com/wang-xinyu/tensorrtx/blob/master/retinaface/ for multi-batch implementation. mainly need revise https://github.com/wang-xinyu/tensorrtx/blob/master/retinaface/decode.cu

**Comment by sealedtx** [comment]
@wang-xinyu thank you for response. I am not familiar with cuda, but I will try to revise the code.
Mainly I don't undestand difference in `forwardGpu` and in `CalDetection` and why it was written in such way in `retinafaceAntiCov` if there was batch support in previous version `retinaface`?

https://github.com/wang-xinyu/tensorrtx/blob/12f7c1b8b103b1fba60daed15d6ce35c50b0319b/retinaface/decode.cu#L110-L165
https://github.com/wang-xinyu/tensorrtx/blob/12f7c1b8b103b1fba60daed15d6ce35c50b0319b/retinafaceAntiCov/decode.cu#L110-L155

**Comment by wang-xinyu** [comment]
`retinaface` was updated to support multi-batch, but `retinafaceAntiCov` was not.
