### ISSUE TITLE
enable_language(CUDA) error

### ISSUE THREAD

**Issue by zzzyy1997** [wang-xinyu/tensorrtx#472]
## Env

- GPU, titan V.
- OS, Win10.
- Cuda version 11.2
- TensorRT version 7.2.3.4

## About this repo
- VS 2019
- which model? yolov5, retinaface? YOLO v5
- Cmake 3.20
- Opencv 4.5.2 

## Your problem
Cmkae problem 
Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2 (found version "11.2") 
    libraries: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/lib/x64/cudart.lib
    include path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/include
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:441 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:58 (__determine_compiler_id_test)
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineCUDACompiler.cmake:278 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:23 (enable_language)

**Comment by wang-xinyu** [comment]
It is a bit tricky to add CUDA nvcc to VS. You can refer to the windows tutorial in this repo, or google some other solutions.

**Comment by zzzyy1997** [comment]
Thank you for your reply. I will have a try and hope the problem can be solved

**Comment by zzzyy1997** [comment]
Dear sir 
    I download yolov5 v4.0 (official weight yolov5s.pt) and tensorrtx  followed the readme in  https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5 and success build.
   but when in cmd and cd `C:\Users\Administrator\Desktop\tensorrtx\yolov5\build\Debug`

get this error.
```
C:\Users\Administrator\Desktop\tensorrtx\yolov5\build\Debug>yolov5.exe -s
arguments not right!
./yolov5 -s [.wts] [.engine] [s/m/l/x or c gd gw]  // serialize model to plan file
./yolov5 -d [.engine] ../samples  // deserialize plan file and run inference
```
how can i fix it?

**Comment by wang-xinyu** [comment]
can you read the complete readme again

**Comment by zzzyy1997** [comment]
ok,fine

**Comment by qtw1998** [comment]
> can you read the complete readme again

meet the same with @zyrant 
![image](https://user-images.githubusercontent.com/34357479/131292530-9dc85f8d-f0b2-4996-9893-478482a48ee8.png)
