### ISSUE TITLE
Is CUDA_NVCC_PLAGS a typo?

### ISSUE THREAD

**Issue by irvingzhang0512** [wang-xinyu/tensorrtx#473]
Is CUDA_NVCC_PLAGS a typo? Maybe it should be `CUDA_NVCC_FLAGS`?

https://github.com/wang-xinyu/tensorrtx/blob/12f7c1b8b103b1fba60daed15d6ce35c50b0319b/unet/CMakeLists.txt#L11

**Comment by wang-xinyu** [comment]
Yes, can you raise a PR to fix it?
