### ISSUE TITLE
build_engine崩溃

### ISSUE THREAD

**Issue by sang16898** [wang-xinyu/tensorrtx#477]
## Env

- GPU, e.g. P4,
- OS, e.g. Win10, etc.
- Cuda version 11.1
- TensorRT 7.5

当运行build_engine的C3时候程序崩溃，看到别的工程使用bottleneckCSP。使用bottleneckCSP时，程序不会报错，但是效果和python比效果差。别的工程在https://github.com/kingqiuol/win10_yolov5_tensorRT

**Comment by wang-xinyu** [comment]
参考readme中不同版本的说明
