### ISSUE TITLE
how to return the results?

### ISSUE THREAD

**Issue by saikrishnadas** [wang-xinyu/tensorrtx#48]
Firstly, Thanks for the conversion. 
`sudo ./yolov4 -d`  just detects the object with bounding box but not with the result.
How do I get the result of what the object is with the bounding box or in the terminal ??

**Comment by wang-xinyu** [comment]
The number on the left top corner of bbox is class-id, 0~79. which is corresponding to the 80 classes in COCO,  https://github.com/ultralytics/yolov3/blob/master/data/coco.names

**Comment by saikrishnadas** [comment]
Great but I'm not that familiar with C++. 
Is it possible to get those as a return result in the terminal?
Where and which file should I edit for this to happen?

Thanks in advance

**Comment by wang-xinyu** [comment]
yolov4.cpp

**Comment by saikrishnadas** [comment]
May i know what changes should i make to track the coco.names instead of ids ?
