### ISSUE TITLE
TensorRT engine giving wrong/different output on deepstream

### ISSUE THREAD

**Issue by yousefis** [wang-xinyu/tensorrtx#480]
## Env

- GPU, Xavier NX
- OS,Ubuntu16.04
- Cuda version 10.2
- TensorRT version 7.3.1

## About this repo

- which branch/tag/commit are you using?  master
- which model? yolov5

## Your problem

I am deploying yolov5 engine on Xavier NX. I developed pre and post processing steps in cuda and seems everything is correct. However I get totally different and wrong results compare to using the engine in the trt library. I noticed that some others also have encountered this issue before on deepstream as well: https://forums.developer.nvidia.com/t/tensorrt-engine-giving-wrong-different-output-in-deepstream/139329. But I have not found any solution for that yet. I was wondering if this problem has already discussed and fixed?

**Comment by wang-xinyu** [comment]
I never deploy models in this repo to deepstream, maybe others can help you.

Can you change the title like `wrong output in deepstream`?

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/pull/485
This merged PR maybe fixed this issue. Can you try the latest master branch?
