### ISSUE TITLE
'no kernel image is available for execution on the device' for Quadro K620

### ISSUE THREAD

**Issue by Transigent** [wang-xinyu/tensorrtx#481]
## Env

- GPU  **RTX3070 (CC 8.6)  and Quadro K620 (CC 5.0)**
- OS **Win 10 Pro 20H2**
- Visual Studio 2017  v15.9.31
- Cuda version   **cuda_11.1.1_456.81_win10.exe**
- CUDNN version    **cudnn-11.2-windows-x64-v8.1.1.33.zip**  (It is supposed to be for 11.1 as well)
- TensorRT version     **TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.1.cudnn8.1.zip**

## About this repo

- which branch/tag/commit are you using?   **Latest Master branch as of 7th April 2021**
- which model?    **yolov5**  

## Your problem

I dont know if this is the right place to post this, please let me know if not. 

I am having trouble with generating a working engine from .wts file on a Quadro K620. I have successfully set DEVICE 0 which is an RTX 3070, and correctly generated the engine file and run inference with no problems on the SAMPLES folder.

However when I switch to the Quadro K620 which has compute capability 5.0 by setting DEVICE 1, the  engine builds normally, but when I run inference I get the message as follows for each image:
**[04/14/2021-22:28:31] [E] [TRT] C:\source\rtSafe\cuda\cudaPluginV2Runner.cpp (184) - Cuda Error in nvinfer1::rt::cuda::PluginV2Runner::execute: 209 (no kernel image is available for execution on the device)
[04/14/2021-22:28:31] [E] [TRT] FAILED_EXECUTION: Unknown exception**

Output .jpgs are saved but there are no detection rectangles. 

Anything I read about this message seemed to indicate that the cause was CC not supported but I believe it is. 

In the [CUDA wiki](https://en.wikipedia.org/wiki/CUDA) I note the following line:
**CUDA SDK 11.1 – 11.3 support for compute capability 3.5 – 8.6 (Kepler (in part), Maxwell, Pascal, Volta, Turing, Ampere).**
and down lower the K620 is specifically listed for CC 5.0.

In the CMakeLists.txt file I added the following line to include support for CC 5.0:
**set(CUDA_NVCC_FLAGS ${CUDA_NVCC_PLAGS};-std=c++11; -g; -G; -gencode; arch=compute_50;code=sm_50; arch=compute_52;code=sm_52; arch=compute_60;code=sm_60; arch=compute_61;code=sm_61; arch=compute_70;code=sm_70; arch=compute_75;code=sm_75; arch=compute_80;code=sm_80; arch=compute_86;code=sm_86;)**

Best I can tell TensorRT 7.2.3.4 still supports CC 5.0 GPUs but I could not find this stated explicitly.

I had previously had the K620 successfully working with CUDA 10.2 but since CC 8.6 was not supported I could not get the RTX 3070 to work. So I removed the 10.2 CUDA installation and started again by downloading CUDA 11.1 and associated libraries and following the Windows instructions again from scratch, to try and create a build that would work for CC 5.0 thru 8.6. I have not been successful.

Any tips on what I am doing wrong would be gratefully received.

**Comment by wang-xinyu** [comment]
You could firstly try the tensorrt official samples with K620, if there is a problem, you could ask at NVIDIA devtalk forum.

**Comment by Transigent** [comment]
Thanks very much will do
