### ISSUE TITLE
build retinaface get error in win10, pls help~

### ISSUE THREAD

**Issue by maokk** [wang-xinyu/tensorrtx#483]
## Env

- GPU, RTX2080
- OS, Win10
- Cuda version 10.2
- TensorRT version 7.2.3

## About this repo
 build retinaface under win10
changed cmake file follow the guide
like:
.....
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Ofast -D_MWAITXINTRIN_H_INCLUDED")

cuda_add_library(decodeplugin SHARED ${PROJECT_SOURCE_DIR}/decode.cu)
target_link_libraries(decodeplugin "nvinfer")

find_package(OpenCV)
include_directories(${OpenCV_INCLUDE_DIRS})
link_directories(${TRT_DIR}\\lib)

add_executable(retina_r50  ${PROJECT_SOURCE_DIR}/retina_r50.cpp)
target_link_libraries(retina_r50 "nvinfer")
#target_link_libraries(retina_r50 cudart)
target_link_libraries(retina_r50 decodeplugin)
target_link_libraries(retina_r50 ${OpenCV_LIBS})
target_link_libraries(retina_r50 Threads::Threads)

## Your problem

build error under vs2017, pls help thanks

-- | -- | -- | -- | -- | -- | --
错误 | LNK2019 | 无法解析的外部符号 "public: __cdecl nvinfer1::DecodePluginCreator::DecodePluginCreator(void)" (??0DecodePluginCreator@nvinfer1@@QEAA@XZ)，该符号在函数 "void __cdecl nvinfer1::`dynamic initializer for 'pluginRegistrarDecodePluginCreator''(void)" (??__EpluginRegistrarDecodePluginCreator@nvinfer1@@YAXXZ) 中被引用 | retina_r50 | C:\work_lib\tensorrtx\retinaface\build\retina_r50.obj | 1 |

**Comment by duoduo1018** [comment]
出现同样的问题，没有解决

**Comment by wang-xinyu** [comment]
seems libdecodeplugin.so not linked. can you refer to https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md for windows vs setup?

**Comment by duoduo1018** [comment]
> seems libdecodeplugin.so not linked. can you refer to https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md for windows vs setup?
感谢您的回复， 是参考您发的这个链接设置的，yolov5能够正常生成，   但retinaface出现上面的问题， 开发环境是 win10/cuda10.0 / cudnn7.6.5 / tensorrt7.0.0，
