### ISSUE TITLE
print class name against bounding box 

### ISSUE THREAD

**Issue by alifaruki** [wang-xinyu/tensorrtx#484]
Hi, i want to show class name against bounding boxes.
can i do it by modifying code?
or i have to do something else?

**Comment by freedenS** [comment]
you only need to build the map between class of network output and class name.
such as {0:"aeroplane", 1:"bicycle", 2:"bird"}

**Comment by alifaruki** [comment]
![Screenshot from 2021-04-17 16-11-41](https://user-images.githubusercontent.com/72023839/115111050-d6598080-9f97-11eb-9db0-73d9b8663e16.png)
![Screenshot from 2021-04-17 16-11-53](https://user-images.githubusercontent.com/72023839/115111055-dbb6cb00-9f97-11eb-86cd-27137d1f1dcf.png)




i am having these issues

**Comment by freedenS** [comment]
You haven't serialized your model correctly.
It looks like your yolov5s.wts and config are mismatched.
see https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#config for detail.

**Comment by alifaruki** [comment]
Thanks for ur help.
