### ISSUE TITLE
yolov5 trt giving wrong outputs.

### ISSUE THREAD

**Issue by alifaruki** [wang-xinyu/tensorrtx#489]
i trained yolov5s for rectangle image with w=1920 and h =1080,
created image for same image size. but my outputs are very wrong.
![_12000000495101_jpg rf b5ab11716a46bc158acb23ccbde410e2](https://user-images.githubusercontent.com/72023839/115161975-216bb480-a0ba-11eb-906a-6606f4abce28.jpg)

**Comment by wang-xinyu** [comment]
w and h must be divisible by 32. that is how yolo works.
