### ISSUE TITLE
Support for yolov5

### ISSUE THREAD

**Issue by makaveli10** [wang-xinyu/tensorrtx#49]
Hey, Thanks for the amazing work. I was wondering if [Ultralytics yolov5](https://github.com/ultralytics/yolov5) is on your list for a tensorrt implementation. I did not find any TRT impl for this anywhere.

**Comment by wang-xinyu** [comment]
Yes! I'm planning to implement Ultralytics yolov5, but I'm busy recently.
Also I'm waiting it to be more stable.

**Comment by makaveli10** [comment]
Great!
