### ISSUE TITLE
yolo-v5, speed 

### ISSUE THREAD

**Issue by pengfeidip** [wang-xinyu/tensorrtx#490]
## Env

- GPU, GTX 1060
- OS, Win10,
- Cuda version 10.2
- TensorRT version  7.1

## About this repo

- which branch/tag/commit are you using? **not sure**
- yolov5

## Your problem
**Is this speed within expectations?**
yolo-v5s，with input resolution 1024 × 1024， `context.execute()`    need **38.0973 ms** ,

**Comment by wang-xinyu** [comment]
You can compare it with pytorch result.

**Comment by pengfeidip** [comment]
Something wrong with my project.    Because inference time is **27ms** with **pytorch** on the same platform.
I will do some analysis and share the results here if any.

**Comment by pengfeidip** [comment]
yolo-v5s，with input resolution 1024 × 1024， batch-size=1
c++ TensorRT context.execute() need **38.0973 ms** , and pytorch need **27ms**

@wang-xinyu    This is a time consuming analysis of each layer of operations.

There seems to be no obvious mistake, except for the obvious time it takes to **Deconvolution**, 

Can you give me some advice?

---

layer (Unnamed Layer* 9) [Constant]  consuming 0.0058624 ms
layer (Unnamed Layer* 5) [Constant]  consuming 0.008224 ms
layer (Unnamed Layer* 266) [ElementWise]  consuming 0.0254944 ms
layer (Unnamed Layer* 174) [ElementWise]_output copy  consuming 0.02816 ms
layer (Unnamed Layer* 270) [ElementWise]  consuming 0.028912 ms
layer (Unnamed Layer* 261) [ElementWise] input reformatter 0  consuming 0.033168 ms
layer (Unnamed Layer* 181) [Convolution]_output copy  consuming 0.035328 ms
layer (Unnamed Layer* 98) [Convolution]_output copy  consuming 0.0356704 ms
layer (Unnamed Layer* 165) [Scale]  consuming 0.0398336 ms
layer (Unnamed Layer* 162) [ElementWise]  consuming 0.0401088 ms
layer (Unnamed Layer* 279) [Convolution]  consuming 0.0421952 ms
layer (Unnamed Layer* 280) [PluginV2]  consuming 0.042592 ms
layer (Unnamed Layer* 141) [ElementWise]  consuming 0.0458048 ms
layer (Unnamed Layer* 124) [ElementWise]  consuming 0.0477184 ms
layer (Unnamed Layer* 137) [ElementWise]  consuming 0.0478208 ms
layer (Unnamed Layer* 256) [ElementWise]  consuming 0.0478592 ms
layer (Unnamed Layer* 261) [ElementWise]  consuming 0.0488576 ms
layer (Unnamed Layer* 102) [ElementWise]  consuming 0.0495168 ms
layer (Unnamed Layer* 235) [Convolution]_output copy  consuming 0.0503808 ms
layer (Unnamed Layer* 260) [Activation]  consuming 0.0507168 ms
layer (Unnamed Layer* 239) [ElementWise]  consuming 0.0516096 ms
layer (Unnamed Layer* 97) [ElementWise]  consuming 0.0520256 ms
layer (Unnamed Layer* 201) [ElementWise]  consuming 0.0521216 ms
layer (Unnamed Layer* 161) [Activation]  consuming 0.0524064 ms
layer (Unnamed Layer* 262) [Convolution]_output copy  consuming 0.0528192 ms
layer (Unnamed Layer* 107) [ElementWise]  consuming 0.0530432 ms
layer (Unnamed Layer* 180) [ElementWise]  consuming 0.0539648 ms
layer (Unnamed Layer* 243) [ElementWise]  consuming 0.0541696 ms
layer (Unnamed Layer* 7) [Constant]  consuming 0.0548032 ms
layer (Unnamed Layer* 153) [ElementWise]  consuming 0.0549312 ms
layer (Unnamed Layer* 174) [ElementWise]  consuming 0.0550208 ms
layer (Unnamed Layer* 170) [ElementWise]  consuming 0.056368 ms
layer (Unnamed Layer* 158) [ElementWise]  consuming 0.0571328 ms
layer (Unnamed Layer* 157) [Activation]  consuming 0.0576352 ms
layer (Unnamed Layer* 120) [ElementWise]  consuming 0.0582848 ms
layer (Unnamed Layer* 273) [Scale]  consuming 0.0585824 ms
layer (Unnamed Layer* 260) [Activation] input reformatter 0  consuming 0.0595008 ms
layer (Unnamed Layer* 173) [Activation]  consuming 0.0595648 ms
layer (Unnamed Layer* 115) [ElementWise]  consuming 0.0597024 ms
layer (Unnamed Layer* 265) [Activation]  consuming 0.0597408 ms
layer (Unnamed Layer* 189) [ElementWise]  consuming 0.0604928 ms
layer (Unnamed Layer* 252) [Convolution]  consuming 0.060944 ms
layer (Unnamed Layer* 152) [Activation]  consuming 0.0610624 ms
layer (Unnamed Layer* 125) [ElementWise]  consuming 0.0612384 ms
layer (Unnamed Layer* 234) [ElementWise]  consuming 0.0612832 ms
layer (Unnamed Layer* 142) [Pooling]  consuming 0.0620192 ms
layer (Unnamed Layer* 175) [Deconvolution]_output copy  consuming 0.0631808 ms
layer (Unnamed Layer* 208) [Convolution]_output copy  consuming 0.063488 ms
layer (Unnamed Layer* 201) [ElementWise]_output copy  consuming 0.0643328 ms
layer (Unnamed Layer* 154) [Convolution]_output copy  consuming 0.0643584 ms
layer (Unnamed Layer* 229) [ElementWise]  consuming 0.0645888 ms
layer (Unnamed Layer* 274) [Activation]  consuming 0.0670624 ms
layer (Unnamed Layer* 128) [Scale]  consuming 0.0681632 ms
layer (Unnamed Layer* 140) [Activation]  consuming 0.0707616 ms
layer (Unnamed Layer* 117) [Convolution]  consuming 0.0713728 ms
layer (Unnamed Layer* 278) [ElementWise]  consuming 0.0716096 ms
layer (Unnamed Layer* 155) [Convolution]  consuming 0.0716992 ms
layer (Unnamed Layer* 116) [ElementWise]  consuming 0.0720864 ms
layer (Unnamed Layer* 3) [Slice]  consuming 0.072192 ms
layer (Unnamed Layer* 182) [Convolution]  consuming 0.0728064 ms
layer (Unnamed Layer* 54) [Convolution]_output copy  consuming 0.0734592 ms
layer (Unnamed Layer* 269) [Activation]  consuming 0.0755008 ms
layer (Unnamed Layer* 166) [Activation]  consuming 0.07552 ms
layer (Unnamed Layer* 108) [Convolution]  consuming 0.0759808 ms
layer (Unnamed Layer* 2) [Slice]  consuming 0.076832 ms
layer (Unnamed Layer* 244) [Convolution]  consuming 0.0774144 ms
layer (Unnamed Layer* 192) [Scale]  consuming 0.0781312 ms
layer (Unnamed Layer* 155) [Convolution] input reformatter 0  consuming 0.0785664 ms
layer (Unnamed Layer* 185) [ElementWise]  consuming 0.0794272 ms
layer (Unnamed Layer* 255) [Activation]  consuming 0.0797312 ms
layer (Unnamed Layer* 149) [ElementWise]  consuming 0.0798368 ms
layer (Unnamed Layer* 150) [Convolution] || (Unnamed Layer* 154) [Convolution] output reformatter 0  consuming 0.0807936 ms
layer (Unnamed Layer* 271) [Convolution]  consuming 0.0824672 ms
layer (Unnamed Layer* 111) [ElementWise]  consuming 0.0834048 ms
layer (Unnamed Layer* 99) [Convolution]  consuming 0.0847552 ms
layer (Unnamed Layer* 258) [Convolution] || (Unnamed Layer* 262) [Convolution] output reformatter 0  consuming 0.0858016 ms
layer (Unnamed Layer* 246) [Scale]  consuming 0.0858112 ms
layer (Unnamed Layer* 1) [Slice]  consuming 0.0858816 ms
layer (Unnamed Layer* 55) [Convolution]  consuming 0.0861344 ms
layer (Unnamed Layer* 106) [ElementWise]  consuming 0.0868 ms
layer (Unnamed Layer* 82) [Convolution]  consuming 0.087552 ms
layer (Unnamed Layer* 67) [ElementWise]  consuming 0.0882688 ms
layer (Unnamed Layer* 71) [ElementWise]  consuming 0.0884736 ms
layer (Unnamed Layer* 62) [ElementWise]  consuming 0.0886784 ms
layer (Unnamed Layer* 81) [ElementWise]  consuming 0.0888832 ms
layer (Unnamed Layer* 207) [ElementWise]  consuming 0.0898656 ms
layer (Unnamed Layer* 76) [ElementWise]  consuming 0.0899168 ms
layer (Unnamed Layer* 114) [Activation]  consuming 0.0902144 ms
layer (Unnamed Layer* 119) [Activation]  consuming 0.090624 ms
layer (Unnamed Layer* 188) [Activation]  consuming 0.0908576 ms
layer (Unnamed Layer* 148) [Activation]  consuming 0.0921536 ms
layer (Unnamed Layer* 163) [Convolution]  consuming 0.0928256 ms
layer (Unnamed Layer* 126) [Convolution]  consuming 0.0946144 ms
layer (Unnamed Layer* 263) [Convolution]  consuming 0.094896 ms
layer (Unnamed Layer* 73) [Convolution]  consuming 0.0956992 ms
layer (Unnamed Layer* 209) [Convolution]  consuming 0.0961184 ms
layer (Unnamed Layer* 93) [ElementWise]  consuming 0.0969184 ms
layer (Unnamed Layer* 238) [Activation]  consuming 0.0976896 ms
layer (Unnamed Layer* 63) [ElementWise]  consuming 0.0978048 ms
layer (Unnamed Layer* 105) [Activation]  consuming 0.0981344 ms
layer (Unnamed Layer* 197) [ElementWise]  consuming 0.0990016 ms
layer (Unnamed Layer* 212) [ElementWise]  consuming 0.0991232 ms
layer (Unnamed Layer* 72) [ElementWise]  consuming 0.10025 ms
layer (Unnamed Layer* 58) [ElementWise]  consuming 0.100502 ms
layer (Unnamed Layer* 277) [Activation]  consuming 0.101856 ms
layer (Unnamed Layer* 133) [ElementWise]  consuming 0.101965 ms
layer (Unnamed Layer* 233) [Activation]  consuming 0.1024 ms
layer (Unnamed Layer* 96) [Activation]  consuming 0.103213 ms
layer (Unnamed Layer* 236) [Convolution]  consuming 0.103478 ms
layer (Unnamed Layer* 110) [Activation]  consuming 0.103578 ms
layer (Unnamed Layer* 190) [Convolution]  consuming 0.106288 ms
layer (Unnamed Layer* 228) [Activation]  consuming 0.109258 ms
layer (Unnamed Layer* 184) [Activation]  consuming 0.110218 ms
layer (Unnamed Layer* 123) [Activation]  consuming 0.111206 ms
layer (Unnamed Layer* 216) [ElementWise]  consuming 0.112666 ms
layer (Unnamed Layer* 141) [ElementWise]_output copy  consuming 0.113315 ms
layer (Unnamed Layer* 138) [Convolution]  consuming 0.116019 ms
layer (Unnamed Layer* 225) [Convolution]  consuming 0.118534 ms
layer (Unnamed Layer* 28) [Convolution]_output copy  consuming 0.12032 ms
layer (Unnamed Layer* 251) [ElementWise]  consuming 0.122362 ms
layer (Unnamed Layer* 13) [Slice]  consuming 0.123699 ms
layer (Unnamed Layer* 12) [Slice]  consuming 0.124621 ms
layer (Unnamed Layer* 200) [Activation]  consuming 0.125094 ms
layer (Unnamed Layer* 247) [Activation]  consuming 0.125747 ms
layer (Unnamed Layer* 80) [ElementWise]  consuming 0.126118 ms
layer (Unnamed Layer* 101) [Activation]  consuming 0.126694 ms
layer (Unnamed Layer* 129) [Activation]  consuming 0.12759 ms
layer (Unnamed Layer* 136) [Activation]  consuming 0.128131 ms
layer (Unnamed Layer* 217) [Convolution]  consuming 0.129126 ms
layer (Unnamed Layer* 242) [Activation]  consuming 0.129168 ms
layer (Unnamed Layer* 64) [Convolution]  consuming 0.1328 ms
layer (Unnamed Layer* 202) [Deconvolution]_output copy  consuming 0.133325 ms
layer (Unnamed Layer* 193) [Activation]  consuming 0.133587 ms
layer (Unnamed Layer* 14) [Slice]  consuming 0.135987 ms
layer (Unnamed Layer* 84) [Scale]  consuming 0.142298 ms
layer (Unnamed Layer* 169) [Activation]  consuming 0.143488 ms
layer (Unnamed Layer* 219) [Scale]  consuming 0.146125 ms
layer (Unnamed Layer* 29) [Convolution]  consuming 0.150835 ms
layer (Unnamed Layer* 53) [ElementWise]  consuming 0.151357 ms
layer (Unnamed Layer* 179) [Activation]  consuming 0.164736 ms
layer (Unnamed Layer* 61) [Activation]  consuming 0.170378 ms
layer (Unnamed Layer* 49) [ElementWise]  consuming 0.170803 ms
layer (Unnamed Layer* 66) [Activation]  consuming 0.170803 ms
layer (Unnamed Layer* 132) [Activation]  consuming 0.171955 ms
layer (Unnamed Layer* 92) [Activation]  consuming 0.172032 ms
layer (Unnamed Layer* 36) [ElementWise]  consuming 0.172237 ms
layer (Unnamed Layer* 57) [Activation]  consuming 0.172733 ms
layer (Unnamed Layer* 11) [Slice]  consuming 0.175923 ms
layer (Unnamed Layer* 79) [Activation]  consuming 0.178522 ms
layer (Unnamed Layer* 37) [ElementWise]  consuming 0.178934 ms
layer (Unnamed Layer* 224) [ElementWise]  consuming 0.182522 ms
layer (Unnamed Layer* 196) [Activation]  consuming 0.185568 ms
layer (Unnamed Layer* 258) [Convolution] || (Unnamed Layer* 262) [Convolution]  consuming 0.187904 ms
layer (Unnamed Layer* 248) [Convolution]  consuming 0.190259 ms
layer (Unnamed Layer* 275) [Convolution]  consuming 0.191181 ms
layer (Unnamed Layer* 8) [ElementWise]  consuming 0.193443 ms
layer (Unnamed Layer* 32) [ElementWise]  consuming 0.194416 ms
layer (Unnamed Layer* 215) [Activation]  consuming 0.195251 ms
layer (Unnamed Layer* 206) [Activation]  consuming 0.196547 ms
layer (Unnamed Layer* 250) [Activation]  consuming 0.19809 ms
layer (Unnamed Layer* 211) [Activation]  consuming 0.204323 ms
layer (Unnamed Layer* 221) [Convolution]  consuming 0.204883 ms
layer (Unnamed Layer* 112) [Convolution]  consuming 0.20521 ms
layer (Unnamed Layer* 50) [Convolution] || (Unnamed Layer* 54) [Convolution]  consuming 0.20695 ms
layer (Unnamed Layer* 86) [Convolution]  consuming 0.207565 ms
layer (Unnamed Layer* 38) [Convolution]  consuming 0.208035 ms
layer (Unnamed Layer* 231) [Convolution] || (Unnamed Layer* 235) [Convolution]  consuming 0.208998 ms
layer (Unnamed Layer* 150) [Convolution] || (Unnamed Layer* 154) [Convolution]  consuming 0.209296 ms
layer (Unnamed Layer* 240) [Convolution]  consuming 0.210595 ms
layer (Unnamed Layer* 198) [Convolution]  consuming 0.213542 ms
layer (Unnamed Layer* 75) [Activation]  consuming 0.213552 ms
layer (Unnamed Layer* 70) [Activation]  consuming 0.213715 ms
layer (Unnamed Layer* 89) [ElementWise]  consuming 0.215002 ms
layer (Unnamed Layer* 130) [Convolution]  consuming 0.216986 ms
layer (Unnamed Layer* 103) [Convolution]  consuming 0.218259 ms
layer (Unnamed Layer* 52) [Activation]  consuming 0.22015 ms
layer (Unnamed Layer* 121) [Convolution]  consuming 0.227616 ms
layer (Unnamed Layer* 94) [Convolution] || (Unnamed Layer* 98) [Convolution]  consuming 0.228618 ms
layer (Unnamed Layer* 27) [ElementWise]  consuming 0.228781 ms
layer (Unnamed Layer* 143) [Pooling]  consuming 0.2304 ms
layer (Unnamed Layer* 85) [Activation]  consuming 0.231526 ms
layer (Unnamed Layer* 171) [Convolution]  consuming 0.233322 ms
layer (Unnamed Layer* 213) [Convolution]  consuming 0.234291 ms
layer (Unnamed Layer* 77) [Convolution]  consuming 0.235098 ms
layer (Unnamed Layer* 40) [Scale]  consuming 0.235213 ms
layer (Unnamed Layer* 194) [Convolution]  consuming 0.235974 ms
layer (Unnamed Layer* 159) [Convolution]  consuming 0.237318 ms
layer (Unnamed Layer* 68) [Convolution]  consuming 0.248314 ms
layer (Unnamed Layer* 6) [ElementWise]  consuming 0.248566 ms
layer (Unnamed Layer* 267) [Convolution]  consuming 0.249222 ms
layer (Unnamed Layer* 220) [Activation]  consuming 0.253971 ms
layer (Unnamed Layer* 10) [ElementWise]  consuming 0.257408 ms
layer (Unnamed Layer* 186) [Convolution]  consuming 0.266854 ms
layer (Unnamed Layer* 24) [Convolution] || (Unnamed Layer* 28) [Convolution]  consuming 0.289587 ms
layer (Unnamed Layer* 59) [Convolution]  consuming 0.320787 ms
layer (Unnamed Layer* 223) [Activation]  consuming 0.326861 ms
layer (Unnamed Layer* 35) [Activation]  consuming 0.334323 ms
layer (Unnamed Layer* 31) [Activation]  consuming 0.334544 ms
layer (Unnamed Layer* 167) [Convolution]  consuming 0.33559 ms
layer (Unnamed Layer* 146) [Convolution]  consuming 0.339507 ms
layer (Unnamed Layer* 88) [Activation]  consuming 0.344102 ms
layer (Unnamed Layer* 33) [Convolution]  consuming 0.34729 ms
layer (Unnamed Layer* 42) [Convolution]  consuming 0.356646 ms
layer (Unnamed Layer* 23) [ElementWise]  consuming 0.358093 ms
layer (Unnamed Layer* 0) [Shuffle]  consuming 0.361488 ms
layer (Unnamed Layer* 45) [ElementWise]  consuming 0.364442 ms
layer (Unnamed Layer* 202) [Deconvolution]  consuming 0.369971 ms
layer (Unnamed Layer* 204) [Convolution] || (Unnamed Layer* 208) [Convolution]  consuming 0.381235 ms
layer (Unnamed Layer* 26) [Activation]  consuming 0.388077 ms
layer (Unnamed Layer* 226) [Convolution]  consuming 0.394755 ms
layer (Unnamed Layer* 48) [Activation]  consuming 0.413638 ms
layer (Unnamed Layer* 253) [Convolution]  consuming 0.422445 ms
layer (Unnamed Layer* 144) [Pooling]  consuming 0.435958 ms
layer (Unnamed Layer* 41) [Activation]  consuming 0.466035 ms
layer (Unnamed Layer* 19) [ElementWise]  consuming 0.670413 ms
layer (Unnamed Layer* 44) [Activation]  consuming 0.69673 ms
layer (Unnamed Layer* 177) [Convolution] || (Unnamed Layer* 181) [Convolution]  consuming 0.710886 ms
layer (Unnamed Layer* 46) [Convolution]  consuming 0.728941 ms
layer (Unnamed Layer* 90) [Convolution]  consuming 0.736154 ms
layer (Unnamed Layer* 22) [Activation]  consuming 0.761139 ms
layer (Unnamed Layer* 20) [Convolution]  consuming 0.76329 ms
layer (Unnamed Layer* 134) [Convolution]  consuming 0.768893 ms
layer (Unnamed Layer* 16) [Convolution]  consuming 0.824832 ms
layer (Unnamed Layer* 18) [Activation]  consuming 1.31144 ms
layer (Unnamed Layer* 175) [Deconvolution]  consuming 4.71378 ms

**Comment by wang-xinyu** [comment]
Hi，no idea, did you test the c++ code?

**Comment by pengfeidip** [comment]
> Hi，no idea, did you test the c++ code?

This is c++ code

**Comment by wang-xinyu** [comment]
can you make sure the pytorch input is real 1024x1024? because it will do letterbox before feeding into model.

**Comment by pengfeidip** [comment]
> can you make sure the pytorch input is real 1024x1024? because it will do letterbox before feeding into model.

In  **detect.py** of yolov5_pytorch , get **torch.Size([1, 3, 1024, 1024])** from ` print(img.shape) `
```  python 
 # Inference
  t1 = time_synchronized()
  print(img.shape)
  pred = model(img, augment=opt.augment)[0]
  t3 = time_synchronized()
```  

---
Here is  executed command of pytorch
```python detect.py --weights ./runs/exp0/weights/best.pt --source ./bobbin_data --img-size 1024 --conf-thres 0.1 --iou-thres 0.5 --device 0  ```

Than get info
```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.1, device='0', img_size=1024, iou_thres=0.5, output='inference/output', save_txt=False, source='./bobbin_data', update=False, view_img=False, weights=['./runs/exp0/weights/best.pt'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1060 6GB', total_memory=6144MB)

Fusing layers...
Model Summary: 191 layers, 7.26588e+06 parameters, 0 gradients
image 1/4 D:\yolov5\bobbin_data\defect_2341-2_2_20200916165205_original_BMC_part_4.jpg: 1024x1024 9 breaks, 4 stains, 1 hollows, Done. (Inference 0.026s NMS 0.613 s)
image 2/4 D:\yolov5\bobbin_data\defect_2344-1_2_20200916165212_original_BMC_part_6.jpg: 1024x1024 14 breaks, 1 stains, Done. (Inference 0.027s NMS 0.002 s)
image 3/4 D:\yolov5\bobbin_data\defect_2345-2_2_20200916165214_original_JS_part_5.jpg: 1024x1024 9 breaks, 8 stains, 1 hollows, Done. (Inference 0.027s NMS 0.002 s)
image 4/4 D:\yolov5\bobbin_data\defect_2347-1_2_20200916165219_original_BMC_part_2.jpg: 1024x1024 10 breaks, 2 stains, 1 hollows, Done. (Inference 0.029s NMS 0.002 s)
Results saved to inference\output
Done. (11.131s)
```

**Comment by wang-xinyu** [comment]
OK,
two more things

1. does the pytorch including gpu-cpu and cpu-gpu memcpy time?
2. did you test tensorrt in a loop, because it may need warmup.

**Comment by pengfeidip** [comment]
> OK,
> two more things
> 
> 1. does the pytorch including gpu-cpu and cpu-gpu memcpy time?
> 2. did you test tensorrt in a loop, because it may need warmup.

1. pytorch , only inference time 
2. yes, with warmup.(like following outputs from 7 images  with and without  warmup)

**without warmup (each image only run 1 times with code `context.execute`)**
```
   context.execute38 ms
doInference 42ms

   context.execute35 ms
doInference 39ms

   context.execute35 ms
doInference 40ms

   context.execute34 ms
doInference 38ms

   context.execute33 ms
doInference 38ms

   context.execute34 ms
doInference 38ms

   context.execute34 ms
doInference 38ms
```

**with warmup (each image only run 10 times with code `context.execute`， then average the time)**
```
   context.execute31 ms
doInference 324ms

   context.execute30 ms
doInference 303ms

   context.execute29 ms
doInference 302ms

   context.execute30 ms
doInference 310ms

   context.execute31 ms
doInference 318ms

   context.execute31 ms
doInference 321ms

   context.execute30 ms
doInference 316ms

```

**Comment by wang-xinyu** [comment]
The latest commit is not using deconv but using resizelayer. So you can try the newest code.

**Comment by pengfeidip** [comment]
> The latest commit is not using deconv but using resizelayer. So you can try the newest code.


Assumeing without `deconv `, it will save 4 ms.  But total time  is not an improvement over the pytorch.

**Comment by pengfeidip** [comment]
@wang-xinyu  
我郁闷了。
根据这篇文章 [https://www.programmersought.com/article/73566872565/](https://www.programmersought.com/article/73566872565/)， 你的代码耗时确实是原始的pytorch的50%...

**Comment by wang-xinyu** [comment]
可能和显卡型号也有关系

**Comment by pengfeidip** [comment]
> 可能和显卡型号也有关系

只能这样理解了

**Comment by huyunlei** [comment]
@pengfeidip 笑了，说了半天英文，后面就是中文了，确实是50，但int8好像没有快多少

**Comment by pengfeidip** [comment]
> @pengfeidip 笑了，说了半天英文，后面就是中文了，确实是50，但int8好像没有快多少

原本想给国际友人提供方便的，后来装不下去了哈哈哈哈。我有以下问题，
1. 你验证了TensorRT和pytorch的耗时比是1:2是吗？是的话，你的具体的模型和使用的平台是什么呢？
2. int8没有快多少，那检测指标呢？你的batchsize是多少呢？分辨率是多少呢？显存消耗下降了多少呢？

**Comment by huyunlei** [comment]
> > @pengfeidip 笑了，说了半天英文，后面就是中文了，确实是50，但int8好像没有快多少
> 
> 原本想给国际友人提供方便的，后来装不下去了哈哈哈哈。我有以下问题，
> 
> 1. 你验证了TensorRT和pytorch的耗时比是1:2是吗？是的话，你的具体的模型和使用的平台是什么呢？
> 2. int8没有快多少，那检测指标呢？你的batchsize是多少呢？分辨率是多少呢？显存消耗下降了多少呢？

320*320 pytorch 26ms  tensorrt 15ms  int8 11 就大概  pytorch是电脑，tensorrt是英伟达NX

**Comment by siriusdemon** [comment]
Today is 8 Sep, 2021. I has compared two model, tensorRT-FP32 and Pytorch-FP32 in video detection using Python. For the same video, I got
```sh
# TensorRT
19.1 s ± 400 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

# Pytorch
14.2 s ± 517 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
I has checked the code and I has removed the useless memory copy from host to host because in my case, I have only one input. I got 
```
# TensorRT
15.1 s ± 400 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
I have removed this code 
```sh
np.copyto(host_inputs[0], batch_input_image.ravel())
```

**Comment by PlumedSerpent** [comment]
> 

请问这个每层耗时是怎么打印出来？
