### ISSUE TITLE
yolov5 trt inference

### ISSUE THREAD

**Issue by UUUserna** [wang-xinyu/tensorrtx#496]
## Env

- GPU,  RTX1050
- OS,  Win10
- Cuda version 11.0
- TensorRT version 7.1.3.4
- pytorch version 1.7.1
- openCV version 3.4

## About this repo

- which branch/tag/commit are you using?
  yolov5-v3.1
- which model?
  yolov5 v3.1

## Your problem

- what is your command?
sudo ./yolov5 -s ../yolov5s.wts yolov5s.engine s
- what's your output?
[E] [TRT] Parameter check failed at: Network.cpp::nvinfer1::Network::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
Assertion failed: scale_1, file f:\yolov5\common.hpp, line 155
- what output do you expect?
I followed tutorials
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5 and
https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md
whole process didn't occured error but a warning when Cmake generating:
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

**Comment by wang-xinyu** [comment]
Did you really follow https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5 ??

For v3.1, you need use branch yolov5-v3.1 of this repo. And follow your local readme.

Check if your local readme is same as the https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5.

The default is master branch on Github.

**Comment by UUUserna** [comment]
my Cmake and generate solution are followed your another tutorial : 
https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md
the rest I did follow your readme.md

**Comment by UUUserna** [comment]
and I used your previous tag code can run, command is :
yolov5 -s
yolov5 -d ../Samples

**Comment by wang-xinyu** [comment]
- For yolov5 v3.1, download .pt from [yolov5 release v3.1](https://github.com/ultralytics/yolov5/releases/tag/v3.1), `git clone -b v3.1 https://github.com/ultralytics/yolov5.git` and `git clone -b yolov5-v3.1 https://github.com/wang-xinyu/tensorrtx.git`. Then follow `how to run` at https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.1/yolov5

Because you were using tag yolov5-v3.1, so you need follow readme in tag yolov5-v3.1, not master.

Is that clear enough?

**Comment by UUUserna** [comment]
sorry, but this error occured in a new solution I use master code generated. so I should upgrade my yolo code to v4.0?

**Comment by luqihui** [comment]
> sorry, but this error occured in a new solution I use master code generated. so I should upgrade my yolo code to v4.0?
it's xiu!

**Comment by luqihui** [comment]
> sorry, but this error occured in a new solution I use master code generated. so I should upgrade my yolo code to v4.0?

Are you waiting for me?

**Comment by UUUserna** [comment]
@luqihui @luqihui @luqihui @luqihui
