### ISSUE TITLE
OSError: build/libmyplugins.so: undefined symbol: _ZN2cv6String10deallocateEv

### ISSUE THREAD

**Issue by makaveli10** [wang-xinyu/tensorrtx#497]
## Env

- GPU, RTX2080
- OS - Ubunbtu 18.04
- Cuda version - 11.0
- TensorRT version - 7.1.3.4

- which branch/tag/commit are you using?
master
- which model?
yolov5

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
`python yolov5_trt.py`
- what's your output?
Getting this error when trying to run python inference from engine built through c++ api
`OSError: build/libmyplugins.so: undefined symbol: _ZN2cv6String10deallocateEv`

**Comment by wang-xinyu** [comment]
Hi @makaveli10 , did you add anything to to yololayer.cu or .h?

**Comment by makaveli10** [comment]
Thanks @wang-xinyu . got it. Somehow i had an opencv import in yololayer.cu. Removed it now.
