### ISSUE TITLE
About the model Input Shape(HxW) question.

### ISSUE THREAD

**Issue by Zpadger** [wang-xinyu/tensorrtx#499]
你好，我看到在 “Speed Benchmark”这一栏用于比较各种模型的检测速度，其中“Input Shape(HxW)”给出了各种网络模型的输入图片尺寸。我看到YOLOv5系列模型的图片输入尺寸都是“608×608”，但是我在其他的专栏或者博客中还看到有人称网络的图片输入尺寸是“640×640”，请问具体怎么理解呢？还有就是在训练时候的参数“--img 640”是否与此有关呢？

**Comment by wang-xinyu** [comment]
因为之前yolov3用的是608，这里为了和yolov3对比速度所以用了608。
yolo的input只要是32的倍数就可以，你可以改成640自己测试。

**Comment by Zpadger** [comment]
哦哦好的，谢谢您的解答
