### ISSUE TITLE
How to run with different resolution

### ISSUE THREAD

**Issue by rulokat** [wang-xinyu/tensorrtx#5]
Hi,
Thanks for the repo, I have learned a lot from it. I would like to run yolov3-spp with different input dimensions. I have tried 608x608 but it didn't work out. I changed INPUT_H and INPUT_W both in yolov3-spp.cpp and YoloConfigs.h. Also, made the anchor heights same as anchor widths. However, the resulting images contain a lot of boxes that are not correct. I think I am doing something wrong. What should I do to make it work? Thanks in advance.

**Comment by wang-xinyu** [comment]
@rulokat thanks for your feedback! I have adapted the code, now you just need to modify 2 lines to use different dims, as follows.

https://github.com/wang-xinyu/tensorrtx/blob/eb202006bd3411e91994fa2f4a0c0f295c797968/yolov3-spp/yololayer.h#L18-L19

**Comment by rulokat** [comment]
Thanks for the reply, now it works perfectly. 

A little suggestion: createPReLUPlugin is deprecated, it creates problems on the newer versions of tensorrt. You can use the following lines instead of plugin:

    auto lr1 = network->addActivation(*bn1->getOutput(0), ActivationType::kLEAKY_RELU);
    assert(lr1);
    lr1->setAlpha(0.1f);

**Comment by wang-xinyu** [comment]
@rulokat that's right. But the tensorrt api version is 4.x in this repo.  No `ActivationType::kLEAKY_RELU` in this version.
Many 4.x APIs are deprecated in 7.x.

May in the future I will create a new branch to use 7.x.

**Comment by rulokat** [comment]
Ahh you are right. I didn't realize that. Anyway, thanks for the replies and the good work. I am closing the issue now.
