### ISSUE TITLE
Improvement on multi-stream or multi-gpu application

### ISSUE THREAD

**Issue by qiuyunzhe** [wang-xinyu/tensorrtx#50]
Thanks for your work. I would like to propose some improvements that might help with multi-stream or multi-processor implementation.

First, add `cudastream` argument when calling Cuda kernel.
For example, here
https://github.com/wang-xinyu/tensorrtx/blob/ff364db7f7f2e7f120474e48da29c97c8c2a5182/yolov4/mish.cu#L141
Since it doesn't declare which stream is going to be used, it would run on default stream instead of the Cuda stream you create in `doInference()` function. The better way to write it would be:
` mish_kernel<<<grid_size, block_size, 0, stream>>>(inputs[0], output, input_size_ * batchSize);`
The same with the `CalDetection` kernel in YOLO layers.

Second, copy the anchor information when initializing YOLO plugin instead of doing `cudamemcpy` each time for detection. 
https://github.com/wang-xinyu/tensorrtx/blob/ff364db7f7f2e7f120474e48da29c97c8c2a5182/yolov4/yololayer.cu#L181-L204
Maybe this improvement would not improve much speed-wise. But here the `cudaFree()` is a synchronized function, which would block all other thread in GPU. So to avoid using this function, it's better to put the anchor information in the device beforehand.

Third, use asynchronous functions instead of synchronous ones. For example, in the code above, `cudaMemset()` could change to `cudaMemsetAsync()`, `cudaMemcpy()` could change to `cudaMemcpyAsync()`.

All these suggestions might not be prominent when running inference on only one GPU and one thread. But it would improve a lot for multi-stream or multi-device situation. Besides, it would be more consistent with the logic of parallel computing.

Hope it helps!

**Comment by wang-xinyu** [comment]
@qiuyunzhe  Great! Thanks for your advice.

Preparing anchor info at the init phase is a good idea. Can you try it and submit a PR?

For multi-stream and Async processing, maybe not everyone need it. But I think we can write a tutorial like `How to implement asynchronous processing and multi-GPU processing`

Could you try it on your side and write a tutorial, put it in https://github.com/wang-xinyu/tensorrtx/tree/master/tutorials, and submit a PR?

**Comment by qiuyunzhe** [comment]
Sure, I'd love to.
