### ISSUE TITLE
DBNet模型量化错误Assertion `scale_1' failed

### ISSUE THREAD

**Issue by zhong-xin** [wang-xinyu/tensorrtx#501]
## Env

- GPU, TX2.
- OS, Ubuntu18.04.
- Cuda version:10.2
- TensorRT version:7.1.3

## About this repo

在对DBNet模型进行量化时出现如下错误，造成这个问题的原因可能是什么？@BaofengZan

## Your problem

fs@fs-desktop:~/DBNet.pytorch-master/models/build$ sudo ./dbnet -s
Loading weights: ../DB.wts
[04/23/2021-15:36:55] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
dbnet: /home/fs/DBNet.pytorch-master/models/common.hpp:94: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
已放弃

**Comment by BaofengZan** [comment]
量化后，搭建模型的一些参数可能就需要修改。比如
`    IActivationLayer* relu2 = basicBlock(network, weightMap, *pool1->getOutput(0), 64, 64, 1, "backbone.layer1.0.");`
里面的卷积核维度可能就需要修改。你要根据你量化后的模型，手动修改下 。

**Comment by zhong-xin** [comment]
> 量化后，搭建模型的一些参数可能就需要修改。比如
> ` IActivationLayer* relu2 = basicBlock(network, weightMap, *pool1->getOutput(0), 64, 64, 1, "backbone.layer1.0.");`
> 里面的卷积核维度可能就需要修改。你要根据你量化后的模型，手动修改下 。

问题已经解决，由于C++构建的推理模型与pytorch构建的模型结构存在差异，导致加载对应层的权重时出现错误。
