### ISSUE TITLE
tensorrt 编译存在问题 

### ISSUE THREAD

**Issue by sxj731533730** [wang-xinyu/tensorrtx#502]
ubuntu@ubuntu:~/tensorrtx/yolov5/build$ cmake ..
-- Configuring done
CMake Error at /usr/local/share/cmake-3.1/Modules/FindCUDA.cmake:1498 (add_library):
  Cannot find source file:

    tracker/tracePoint.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:24 (cuda_add_library)

CMake Warning at /usr/local/share/cmake-3.1/Modules/FindCUDA.cmake:1498 (add_library):
  Cannot generate a safe linker search path for target myplugins because
  files in some directories may conflict with libraries in implicit
  directories:

    link library [libcudart.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:24 (cuda_add_library)

CMake Warning at CMakeLists.txt:30 (add_executable):
  Cannot generate a safe linker search path for target yolov5 because files
  in some directories may conflict with libraries in implicit directories:

    link library [libcudart.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/ubuntu/tensorrtx/yolov5/build

-- Build files have been written to: /home/ubuntu/tensorrtx/yolov5/build
ubuntu@ubuntu:~/tensorrtx/yolov5/build$ make
[  0%] Built target myplugins
Linking CXX executable yolov5
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `nvinfer1::PluginRegistrar<nvinfer1::YoloPluginCreator>::~PluginRegistrar()':
/home/ubuntu/tensorrtx/yolov5/yololayer.h:108: undefined reference to `vtable for nvinfer1::YoloPluginCreator'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `_GLOBAL__sub_I__Z8get_rectRN2cv3MatEPf':
/usr/local/include/NvInferRuntimeCommon.h:1433: undefined reference to `nvinfer1::YoloPluginCreator::YoloPluginCreator()'
CMakeFiles/yolov5.dir/yolov5.cpp.o: In function `_GLOBAL__sub_I__Z8get_rectRN2cv3MatEPf':
/home/ubuntu/tensorrtx/yolov5/yololayer.h:108: undefined reference to `vtable for nvinfer1::YoloPluginCreator'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5.dir/build.make:127: recipe for target 'yolov5' failed
make[2]: *** [yolov5] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
Hi, you should make sure your cuda is installed properly, and adapt the cuda path in cmake accordingly.

**Comment by sxj731533730** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        thank you 
             i have solved my problem, thanks谢谢你    我已经解决了我的问题 再次谢谢你
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                sxj731533730
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年4月25日 11:01，Wang ***@***.***> 写道： 



Hi, you should make sure your cuda is installed properly, and adapt the cuda path in cmake accordingly.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dcdethan** [comment]
请问你是怎么解决的

**Comment by sunanlin13174** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } thank you       i have solved my problem, thanks谢谢你    我已经解决了我的问题 再次谢谢你 sxj731533730 ***@***.*** 签名由 网易邮箱大师 定制 在2021年4月25日 11:01，Wang ***@***.***> 写道： Hi, you should make sure your cuda is installed properly, and adapt the cuda path in cmake accordingly. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

同问啊，怎么解决的，哪里的问题呢？
