### ISSUE TITLE
yolo5l模型的推理结果和作者原版yolov5推理结果有差异

### ISSUE THREAD

**Issue by brucelee78** [wang-xinyu/tensorrtx#507]
## Env

- GPU, TITAN RTX & Xavier
- OS  Ubuntu18.04
- Cuda 10.2
- TensorRT 7.1.3.4

## About this repo

yolov5 v3.0版本
yolo5l

## 我的问题
用自己的数据集训练了` yolov5l` 模型，用的作者原版yolov5训练，训练期间改过anchor，修改的anchor如下图所示：

![0426_3](https://user-images.githubusercontent.com/48920529/116030527-54034780-a68e-11eb-95d9-2d90f566188a.png)
发现用作者原版的detect.py文件推理结果正确，而tensorrx这个C++推理有些问题，识别框很小，不能包含全部目标，已在`yolov5.cpp`中修改为了：
`#define NET l `

`yololayer.h`中修改为：
```
 static constexpr int CLASS_NUM = 80;
 static constexpr int INPUT_H = 608;
 static constexpr int INPUT_W = 608;
```

如下图所示：
![0426_1](https://user-images.githubusercontent.com/48920529/116030561-641b2700-a68e-11eb-9dd4-a704422a46ba.png)
上图为作者原版`yolov5-3.0`运行`python detect.py`的运行结果

![0426_2](https://user-images.githubusercontent.com/48920529/116030614-84e37c80-a68e-11eb-9c88-8da1a4332b8a.png)

上图为用tensorrx中的yolov5推理的结果

请大神帮忙看看是那个地方出了问题呢，感激不尽！

**Comment by wang-xinyu** [comment]
可以把你的模型和官方验证OK的模型 print出来逐层对比一下

**Comment by brucelee78** [comment]
> 可以把你的模型和官方验证OK的模型 print出来逐层对比一下

您说的是我训练的pt模型和官方yolo5l.pt模型结构进行print后进行逐层对比吗？

**Comment by wang-xinyu** [comment]
对，但是要先验证官方yolo5l.pt模型在tensorrtx结果正常
