### ISSUE TITLE
sudo ./yolov5 -s failed

### ISSUE THREAD

**Issue by TimGor1997** [wang-xinyu/tensorrtx#508]
## Env

- GPU, 3090
- OS, Ubuntu18.04
- Cuda version 11.1
- TensorRT version 7.2.3.4

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5

## Your problem

- what is your command?`sudo ./yolov5 -s`
- what's your output? yolov5: /home/asus/Tim/tensorrtx-master/yolov5/common.hpp:94: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file. please check if the .wts file path is right!!!!!!"' failed.

- what output do you expect?
how to solve this problem?

**Comment by woshichunge12** [comment]
I am in the same situation as you, have you solved this problem?

**Comment by Dave-Dush** [comment]
I faced the same issue. Did you fix it?

**Comment by Gannis246** [comment]
Maybe you can cope the .wts file into build. It works for me.
