### ISSUE TITLE
YOLOV5 TRT inferencing 

### ISSUE THREAD

**Issue by LIU-FAYANG** [wang-xinyu/tensorrtx#511]
## Env

- GPU, Xavier NX
- OS, Ubuntu18.04
- Cuda version 10.2
- TensorRT version 7.1.0
 
## About this repo

- which branch/tag/commit are you using? 
- which model? yolov5, retinaface? yolov5 5.0

## Your problem

- what is your command? 
sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
- what's your output?
sudo: ./yolov5: command not found

Hi, I've tried it on my PC and Jetson Nano, it works well. Now I'm testing it on Jetson Xavier. I've modified the CmakeList and build it successfully, but now there's problem in the inferencing step, do u have any suggestion on this?

**Comment by wang-xinyu** [comment]
can you paste the entire logs or screenshot?

**Comment by LIU-FAYANG** [comment]
![screenshot](https://user-images.githubusercontent.com/74730293/116220392-d6ffcd00-a776-11eb-9fcf-6c86ed2bb48b.png)
 Thanks a lot! 
I don't know why the make process cannot make it executable, such condition didn't happen why I tried it on PC and Nano.

**Comment by wang-xinyu** [comment]
you can skip `sudo` and try again.

**Comment by LIU-FAYANG** [comment]
It shows permission denied. 
Actually I'm a bit confused, does this make process linked to the original yolov5? Since I only have about 1 GB left on the Jetson Xavier, I didn't install the packages listed in the origional yolov5 and did the weights converion, so I just downloaded the  .wts file I generated on other model and copied it to tensorrtx/yolov5. Is it because of this? 
Thanks again for your kind help.

**Comment by wang-xinyu** [comment]
.wts is just plain text, so it's portable.

can you run `ll` in `build` and paste the result?

**Comment by LIU-FAYANG** [comment]
![screenshot_1](https://user-images.githubusercontent.com/74730293/116338060-5c31c300-a805-11eb-8a17-9d78652915db.png)
Sorry for late reply.

**Comment by wang-xinyu** [comment]
`ll` not `make ll`,

**Comment by LIU-FAYANG** [comment]
Sorry my bad,

aaeon@aaeon-desktop:/media/aaeon/3835-35381/test/tensorrtx/yolov5/build$ ll
total 66464
drwxr-xr-x 3 aaeon aaeon    32768 Apr 27 22:32 ./
drwxr-xr-x 3 aaeon aaeon    32768 Apr 27 04:42 ../
-rw-r--r-- 1 aaeon aaeon    23172 Apr 27 05:25 CMakeCache.txt
drwxr-xr-x 7 aaeon aaeon    32768 Apr 27 22:32 CMakeFiles/
-rw-r--r-- 1 aaeon aaeon     1671 Apr 27 05:25 cmake_install.cmake
-rw-r--r-- 1 aaeon aaeon   238432 Apr 27 05:25 libmyplugins.so
-rw-r--r-- 1 aaeon aaeon     6505 Apr 27 22:32 Makefile
-rw-r--r-- 1 aaeon aaeon  1873312 Apr 27 05:26 yolov5
-rw-r--r-- 1 aaeon aaeon 65675318 Apr 15 05:00 yolov5s.wts

By the way I just realize I wrongly indicated my OS, it's LXDE not Ubuntu. Is it the OS issue?

**Comment by wang-xinyu** [comment]
try these commands
```
sudo chmod +x yolov5
sudo ./yolov5 yolov5s.wts yolov5s.engine s
```

**Comment by LIU-FAYANG** [comment]
Yeah I tried this method and it didn't work.

**Comment by LIU-FAYANG** [comment]
Hi. I I've solved this issue. This issue happened since I did the opreated on the SD card I added on the Xavier. I tried to compile outside the SD card it worked.
Thanks again for ur kind help!
