### ISSUE TITLE
Yolov3 Ultralytics Master Branch

### ISSUE THREAD

**Issue by LeoCyclope** [wang-xinyu/tensorrtx#514]
Hi Guys,

First, thank you so much for this amazing Repo @wang-xinyu  :) 
I was wondering how to convert the yolov3 from the master branch of ultralytics?
The one which is not compatible with CFG and .weights but works with the YAML.

The script gen_wts.py in this repo for yolov3 is using the CFG.
I read the yolov3 here only works with the archive branch of Yolov3 Ultralytics.

In summary, how to convert to TensorRT the yolov3 from the Master branch of Ulytralitics now: https://github.com/ultralytics/yolov3 ?

Thanks in advance,

**Comment by wang-xinyu** [comment]
The yolov3 in this repo was built upon archive branch of https://github.com/ultralytics/yolov3. We welcome that anyone can upgrade the code to master branch of yolov3.

**Comment by LeoCyclope** [comment]
Thanks for your reply.
I am willing to give it a try but I might need some help.
Is there any way we can exchange directly to implement that?
I might have some questions that would speed things up.

Thanks in advance,

**Comment by wang-xinyu** [comment]
you can reach me through wechat or email, which you can find in the end of readme.

**Comment by vjsrinivas** [comment]
@wang-xinyu Is this something still being worked on? I have a model trained on the master branch that I don't want to retrain on the archive. I got the YOLOv3 master branch working in my fork (yolov3_ultra): https://github.com/vjsrinivas/tensorrtx/tree/master/yolov3_ultra

I need to clean the code up. It is a mix of the current yolov5 code and yolov3 code, but I would like to re-implement with most of the yolov5 functions. Once it's polished, I can put a PR in.

**Comment by wang-xinyu** [comment]
@vjsrinivas Sure,  welcome to open the PR.
