### ISSUE TITLE
Bounding box coordinates for accuracy measurement 

### ISSUE THREAD

**Issue by LIU-FAYANG** [wang-xinyu/tensorrtx#516]
Env

    GPU, Xavier NX
    OS, LXDE
    Cuda version 10.2
    TensorRT version 7.1.0

About this repo

    which branch/tag/commit are you using?
    which model? yolov5, retinaface? yolov5 5.0

Your problem

Hi, can I ask what should I do if I want to get the bounding box coordinates and convert it to yolo format to measure its accuracy?

**Comment by wang-xinyu** [comment]
you need look into the code and find where the coordinates are.

**Comment by LIU-FAYANG** [comment]
Hi, I've found the bounding box coordinates contained in common.hpp and yolov5.cpp, it's in cv:Rect datatype, which is like [408 x 666 from (750, 42)]( width x height from (top, left), i'd like to convert it to <top> <left> <width> <height> format, could you plz guide me on this? Also, I could not find the confidence level in your script, is it contained in somewhere?

**Comment by LIU-FAYANG** [comment]
Hi, I think I've figured it out, only need some minor changes the code in the inference section inside yolov5.cpp, thanks for your great work!
