### ISSUE TITLE
SUPPORT AlexeyAB???

### ISSUE THREAD

**Issue by KelvinHuang666** [wang-xinyu/tensorrtx#52]
I Had finished training with darknet(AlexeyAB github),got a model.weights(yolov3)
And I can get model.wts with your good job
But i cant using it with tensorrt
![AU DD$PIB)8K}5NCMQ(C%@C](https://user-images.githubusercontent.com/42311753/85000131-9877aa00-b184-11ea-89b8-cf7becb43e11.png)
whether I made someting wrong

**Comment by KelvinHuang666** [comment]
![AU DD$PIB)8K}5NCMQ(C%@C](https://user-images.githubusercontent.com/42311753/85000298-c6f58500-b184-11ea-89f6-9b508dd24eb5.png)

**Comment by wang-xinyu** [comment]
which .cfg are you using?   yolov3.cfg or yolov3-spp.cfg?

**Comment by KelvinHuang666** [comment]
我是修改了alexeyAB的cfg/yolov3.cfg文件进行训练，得到训练好的我需要的.weights文件。其实也就修改了类别，其他跟原作者的cfg文件保持一致。根据这个cfg文件跟weights文件可以在https://github.com/ultralytics/yolov3项目下将weights文件转成pt文件，根据您的项目下yolov3文件夹下的gen_wts.py可以将我的weights文件转成wts文件，但是tensorrt使用这个wts文件时报错，但是我想将已经转换的pt文件转成wts文件时报错
![image](https://user-images.githubusercontent.com/42311753/85086578-99a0e980-b20d-11ea-8f43-ce439c05b13c.png)

**Comment by wang-xinyu** [comment]
我这边的yolov3和yolov3-spp是分开的，另外yololayer.h里面的类别数CLASS_NUM，要改一下

**Comment by KelvinHuang666** [comment]
您的意思是我在yololayer.h修改自己的类别跟宽高以后，用我的cfg文件跟weights文件直接生成.wts文件就可以供tensorrt调用了是吗，十分感谢。

**Comment by wang-xinyu** [comment]
嗯啊，试试

**Comment by passion3394** [comment]
@wang-xinyu yolov3-spp.weights能通过gen_wts.py直接转换为.wts格式吗？

**Comment by wang-xinyu** [comment]
可以，但是需要用https://github.com/ultralytics/yolov3调用生成，他支持darknet的weights

**Comment by passion3394** [comment]
@wang-xinyu 谢谢您的指点。
