### ISSUE TITLE
tensorrt的dilation问题

### ISSUE THREAD

**Issue by jiaoyitao** [wang-xinyu/tensorrtx#520]
## Env

- Cuda version
- TensorRT version 7.0
- 大神，我最近将一个lightweight-human-pose项目用的修改的mobilenet网络的模型转成tensorrt，在这个网络的卷积层增加了dilation空洞卷积操作。转换过程采用两种方式：
- 1、pytorch->onnx->tensorrt
- 2、pytorch->wts->tensorrt
-1和2两种方式转换的tensorrt模型输出结果是一样的，但它们同pytorch模型输出的结果是不一样的，即转成tensorrt的结果是不对的。对比下tensorrt模型同pytorch模型的中间结果是很接近的，经过空洞卷积层后的输出结果是不对的。
想问下，大神转没转换过带空洞卷积的网路?tensorrt中卷积层的dilation跟pytorch中的dilation操作是不是有差别？

**Comment by wang-xinyu** [comment]
trt  conv的dilation设置了吗

**Comment by jiaoyitao** [comment]
> trt conv的dilation设置了吗

设置了啊。

**Comment by wang-xinyu** [comment]
你可以只搭一层conv，设置dilation，和pytorch对比，然后如果有问题去问nv论坛

**Comment by jiaoyitao** [comment]
好的，谢谢。
