### ISSUE TITLE
[Question] Yolov5 TRT mAP results

### ISSUE THREAD

**Issue by pedrombefore** [wang-xinyu/tensorrtx#522]
## Env

- GPU : Nvidia T4
- OS, e.g. Ubuntu18.04
- Cuda version 11.1
- TensorRT version 7.2

## About this repo

- which branch/tag/commit are you using? Master
- which model? yolov5

## Your problem

- what is your command? Python Inference

Hey,

I'm adapting the code to use the TensorRT inference inside test.py in the ultralytics official repo, to evaluate TensorRT performance under all quantization possibilities. 

I did keep the pre-processing and post-processing methods from your algorithm, except the NMS. Then I imported a TensorRT instance of Yolov5 TRT inside the original code and used the output pattern after post-processing [x1,y1,x2,y2,bbox_conf, cls_conf].
I reshaped the results to have an output as Torch, where we need cls_conf for all classes, then I set the other's class confidence to 0.01 where a result is:
- [BATCH_SIZE, MAX_OUTPUT_BBOX_COUNT, CLASS_NUM+5];
- where CLASS_NUM+5 = 85 -> x1,y1,x2,y2,bbox_conf, class1, class2, class3.... class80]

The results are pretty bad.

![image](https://user-images.githubusercontent.com/60433809/116905340-d8187a80-ac0c-11eb-8e2c-dcd981218e27.png)
![image](https://user-images.githubusercontent.com/60433809/116905376-e4043c80-ac0c-11eb-8f2e-17f4febb4d95.png)

In the Confusion Matrix, almost everything is being predicted as Background.

I have two questions:
1 - I adapted the code inside Yolov5.h, and instead of float conf;  // bbox_conf * cls_conf I put both conf in separated variables. Same for Yolov5.cu, to match detections with the object in Yolov5.h. Is there any loss from this? Why did you use both together?
2 - The number of BBOX (default for 1000) influence the results? 

PS: I used the same parameters as Ultralytics
- img_size = 640
- iou=0.65
- conf=0.001

**Comment by wang-xinyu** [comment]
Hi, 
1. I remember there has operations like `bbox_conf * cls_conf` in the post process of Ultralytics yolov5. Can you confirm it?
2. The 1000 is the max number of bbox. The bbox with conf < `IGNORE_THRESH` will be ignored.

**Comment by pedrombefore** [comment]
I did look at test.py and non-max suppression function from Ultralytics and yes, they do `bbox_conf * cls_conf` inside the NMS method.

I think the way is to increase the number of BBOX, running test.py with torch model sometimes give 25K bboxes.

Thanks for the tip, I think I put to much effort that made me blind to some parts in the original code.

**Comment by pedrombefore** [comment]
@wang-xinyu do you know all the object IDs that the network outputs? Seems they do not follow the 91 class pattern from the paper. I was reading the original Yolov5 and they have a method called `coco80_to_coco91_class`, when I try to generate mAP for example Person ID on TRT version is 0, original repo is 1.

**Comment by wang-xinyu** [comment]
The default class_num is 80 in yolov5 https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml

**Comment by LIU-FAYANG** [comment]
Hi, I tried to use this method https://github.com/rafaelpadilla/review_object_detection_metrics#ap50595 for accuracy test and the mAP(coco metric IOU = [0.5:0.95], fp32) turns out to be 0.31, which is even lower than the original fp16 mode mAP = 0.36. I tried to adjust the IGNORE_THRESH and MAX_bbox in yololayer.h and rerun the model, the accuracy didn't seem to change. Is there any other way I and try to improve the accuracy?
By the way @pedrombefore , have you solved your probelm? Could you share your accuracy test result?

Thanks a lot!
