### ISSUE TITLE
Error when trying to run 'make' on yolov5 

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [wang-xinyu/tensorrtx#523]
Hi everyone, I am trying to convert my yolov5s.pt model to tensorrt. I'm working on a Jetson Nano and with the NVIDIA L4T Pytorch docker container ([link](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch)). Everything woks fine until running the 'make' command I receive the following error message below.

Any help would be highly appreciated.

```
root@skymind:/yolov5/tensorrtx/yolov5/build# make
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
/yolov5/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

/yolov5/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

Scanning dependencies of target myplugins
[ 40%] Linking CXX shared library libmyplugins.so
[ 40%] Built target myplugins
Scanning dependencies of target yolov5
[ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
/yolov5/tensorrtx/yolov5/calibrator.cpp:4:10: fatal error: opencv2/dnn/dnn.hpp: No such file or directory
 #include <opencv2/dnn/dnn.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/yolov5.dir/build.make:62: recipe for target 'CMakeFiles/yolov5.dir/calibrator.cpp.o' failed
make[2]: *** [CMakeFiles/yolov5.dir/calibrator.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

P.S. I checked and I do have opencv 4.5.1 installed in the container.

**Comment by abuelgasimsaadeldin** [comment]
If there is a Dockerfile that I could build or docker image that works well with the tensorrt installation for yolov5 on the Jetson Nano with the JetPack version too. Thanks!

**Comment by maryamkhl** [comment]
> Hi everyone, I am trying to convert my yolov5s.pt model to tensorrt. I'm working on a Jetson Nano and with the NVIDIA L4T Pytorch docker container ([link](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch)). Everything woks fine until running the 'make' command I receive the following error message below.
> 
> Any help would be highly appreciated.
> 
> ```
> root@skymind:/yolov5/tensorrtx/yolov5/build# make
> [ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
> /yolov5/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?
> 
> /yolov5/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?
> 
> Scanning dependencies of target myplugins
> [ 40%] Linking CXX shared library libmyplugins.so
> [ 40%] Built target myplugins
> Scanning dependencies of target yolov5
> [ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
> /yolov5/tensorrtx/yolov5/calibrator.cpp:4:10: fatal error: opencv2/dnn/dnn.hpp: No such file or directory
>  #include <opencv2/dnn/dnn.hpp>
>           ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/yolov5.dir/build.make:62: recipe for target 'CMakeFiles/yolov5.dir/calibrator.cpp.o' failed
> make[2]: *** [CMakeFiles/yolov5.dir/calibrator.cpp.o] Error 1
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
> make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> P.S. I checked and I do have opencv 4.5.1 installed in the container.

it is my problem too,
please help

**Comment by maryamkhl** [comment]
> Hi everyone, I am trying to convert my yolov5s.pt model to tensorrt. I'm working on a Jetson Nano and with the NVIDIA L4T Pytorch docker container ([link](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch)). Everything woks fine until running the 'make' command I receive the following error message below.
> 
> Any help would be highly appreciated.
> 
> ```
> root@skymind:/yolov5/tensorrtx/yolov5/build# make
> [ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
> /yolov5/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?
> 
> /yolov5/tensorrtx/yolov5/yololayer.h(85): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int, const nvinfer1::Dims *, int, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?
> 
> Scanning dependencies of target myplugins
> [ 40%] Linking CXX shared library libmyplugins.so
> [ 40%] Built target myplugins
> Scanning dependencies of target yolov5
> [ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
> /yolov5/tensorrtx/yolov5/calibrator.cpp:4:10: fatal error: opencv2/dnn/dnn.hpp: No such file or directory
>  #include <opencv2/dnn/dnn.hpp>
>           ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/yolov5.dir/build.make:62: recipe for target 'CMakeFiles/yolov5.dir/calibrator.cpp.o' failed
> make[2]: *** [CMakeFiles/yolov5.dir/calibrator.cpp.o] Error 1
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
> make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> P.S. I checked and I do have opencv 4.5.1 installed in the container.

this is my problem too
help please

**Comment by wang-xinyu** [comment]
what did you use docker on nano? The jetpack with trt >=7.0 would work fine.

**Comment by abuelgasimsaadeldin** [comment]
@wang-xinyu, thank you this solved my issue.

**Comment by abuelgasimsaadeldin** [comment]
@wang-xinyu btw the reason for using docker is because JetPack 4.5 image does not come with PyTorch and Torchvision pre-installed and so I run the ```python3 gen_wts.py yolov5s.pt``` command in a container to build the .wts file then continue the rest of the commands on the just on the JetPack. Again Thanks!

**Comment by cwlinghk** [comment]
For those non jetpack users:

dnn.hpp comes with opencv contribute modules 

You have to build opencv from the beggining

**Comment by chh7411898** [comment]
你好。 ubuntu20.04  trt7  opencv4.5.1. 也出现了上面的问题 我在安装opencv cmake的时候写了-dwith_cuda.    应该是安装上了的 然后opencv中也有dnn.hpp 这个文件 ，还有别的办法可以解决这个问题吗
