### ISSUE TITLE
Error when trying to build Dockerfile

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [wang-xinyu/tensorrtx#525]
Hi guys, I received the following error when trying to build the Dockerfile on my Jetson Nano with JetPack4.5 installed. Anyone know the reason for this error or occurring or faced a similar error before? 

```
Step 4/9 : RUN rm /etc/apt/sources.list.d/timsc-ubuntu-opencv-3_3-bionic.list
 ---> Running in b98eaac85efb
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c rm /etc/apt/sources.list.d/timsc-ubuntu-opencv-3_3-bionic.list' returned a non-zero code: 1
```

**Comment by wang-xinyu** [comment]
You can try jetpack without docker, which already has opencv4 installed.

**Comment by abuelgasimsaadeldin** [comment]
@wang-xinyu, thanks allot! it worked and I was able to run the 'make' command using just the JetPack and without any docker.
