### ISSUE TITLE
Python and TensorRT have different results

### ISSUE THREAD

**Issue by hejun888** [wang-xinyu/tensorrtx#526]
你好，我用的是你们unet项目，然而分割结果有些不一样，左边是模型分割的结果，右边是转成tensorrt后的推理结果，想问下为何结果是不一致的，可能是什么原因造成的。谢谢
![K 756 DSUD@NFIE 3953%4S](https://user-images.githubusercontent.com/28728850/117246672-9e937980-ae6f-11eb-9ebc-22e8f74c79e7.png)

**Comment by wang-xinyu** [comment]
upsample可能不一样

**Comment by hejun888** [comment]
谢谢您的回复，模型在转换过程中没出现错误，如果不一样的话转换不就报错了吗，这点我不是明白。此外，您猜测upsample可能不一样，假如是upsample不一样，为何会出现这样的现象呢

**Comment by wang-xinyu** [comment]
upsample 有bilinear和nearest，这里用的deconvolution代替upsample, 和nearest等效。

**Comment by hejun888** [comment]
既然是等效，为何会对结果有影响呢，使得python结果和tensorrt的结果不一致呢

**Comment by wang-xinyu** [comment]
你的pytorch用的是bilinear还是convTranspose2d?

**Comment by hejun888** [comment]
用的是bilinear
![Uploading image.png…]()

**Comment by wang-xinyu** [comment]
> upsample 有bilinear和nearest，这里用的deconvolution代替upsample, 和nearest等效。

用的bilinear, 所以和这里的deconvolution是不等效的

**Comment by hejun888** [comment]
那将python中的upsample形式改为nearest可以吗，影响大吗

**Comment by wang-xinyu** [comment]
改完应该要重新训练吧

**Comment by hejun888** [comment]
是的，我是重新训练的

**Comment by hejun888** [comment]
确实是upsample的问题，感谢大佬，现在的问题是，模型的结果和tensorrt的结果有些地方不一样，想问一下这是什么原因导致的，怎么解决这种不一致的问题
![image](https://user-images.githubusercontent.com/28728850/117426655-b5f96200-af56-11eb-90ed-d055efc8ffdf.png)
左边是模型分割的结果，右边是tensorrt的分割结果

**Comment by wang-xinyu** [comment]
can you try the new PR https://github.com/wang-xinyu/tensorrtx/pull/530?

**Comment by hejun888** [comment]
好的

**Comment by missbook520** [comment]
您好，我用的unet序列化模型时报了如下的错误，请问有可能是什么原因呢？
代码没有更改，只是加了几个debug语句。
![Uploading 989eb14281cff127accccc198682cd5.jpg…]()

**Comment by missbook520** [comment]
您好，我用的unet序列化模型时报了如下的错误，请问有可能是什么原因呢？
代码没有更改，只是加了几个debug语句。
![989eb14281cff127accccc198682cd5](https://user-images.githubusercontent.com/48777650/117563298-70b06e00-b0d7-11eb-853d-cc61620529f7.jpg)

**Comment by wang-xinyu** [comment]
@YuzhouPeng  do you have any idea?

**Comment by YuzhouPeng** [comment]
channels do not fit, I found a bug in my code and I will fix that in few days.

**Comment by DogeZen** [comment]
我也遇到同样的问题了

**Comment by DogeZen** [comment]
> 确实是upsample的问题，感谢大佬，现在的问题是，模型的结果和tensorrt的结果有些地方不一样，想问一下这是什么原因导致的，怎么解决这种不一致的问题
> ![image](https://user-images.githubusercontent.com/28728850/117426655-b5f96200-af56-11eb-90ed-d055efc8ffdf.png)
> 左边是模型分割的结果，右边是tensorrt的分割结果

你好，我也遇到同样的问题了，目前我是把python的blinear改为nearest，然后c++改为PR[ #530](https://github.com/wang-xinyu/tensorrtx/pull/530)。
但是仍然预测对不上。请问您当时是改了哪些，最终解决了。

**Comment by hejun888** [comment]
我没改啊，就用他新的版本就行了

**Comment by DogeZen** [comment]
请问是改成PR [#530](https://github.com/wang-xinyu/tensorrtx/pull/530)了吗

**Comment by RookieAI** [comment]
> 你的pytorch用的是bilinear还是convTranspose2d?

我用的Pytorch-UNet v3.0，默认用的 convTransposed2d，结果也对不上
