### ISSUE TITLE
lstm

### ISSUE THREAD

**Issue by cqray1990** [wang-xinyu/tensorrtx#527]
## Env

- GPU, 2060
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version 7.0

about crnn

## Your problem

conv shape 1 512 1 -1
shape 1 512 -1
lstm input shape: 3 [1 -1 512]
[05/06/2021-21:53:10] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addRNNCommon::570, condition: maxSeqLen > 0
段错误 (核心已转储)

请问lstm不可以动态传入？

**Comment by wang-xinyu** [comment]
crnn这里是固定input，rnnlayer是否支持动态input，可以去看trt文档

**Comment by cqray1990** [comment]
@wang-xinyu 我他改成动态ｓｈａｐｅ，但是有问题，按照以前改的方式，再ｃｒｎｎ就不行了

**Comment by cqray1990** [comment]
@wang-xinyu 官方文档没些是否可以动态，只说传入参数的解释
