### ISSUE TITLE
[Question] Is there an option for video inferencing on this repo for the yolov5 model?

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [wang-xinyu/tensorrtx#529]
Hi @wang-xinyu, thank you for this amazing repo I finally got it to work on the sample images using my Jetson Nano and was wondering if there was an option for performing live video inferencing that I could test my model with using my webcam?

If there isn't I would love to adapt it somehow using opencv and therefore any guidance on how to do so and which scripts require modification would be highly appreciated. Thank you again!

**Comment by wang-xinyu** [comment]
You need add video reading function by yourself, adapt yolov5.cpp for cpp or yolov5_trt.py for python.
