### ISSUE TITLE
Yolov5 int8 low mAP

### ISSUE THREAD

**Issue by LIU-FAYANG** [wang-xinyu/tensorrtx#534]
## Env

- GPU NVIDIA Titan X
- OS,Ubuntu18.04
- Cuda 11.1
- TensorRT 7.2.3

## Your problem
Hi, thanks for your great work. 
I implemented yolov5 tensorrt under int8 and the mAP turns out to be quite low(around 0.125) based on coco evaluation metric IOU = [0.5 0.95]. Is this normal? I don't think using int8 can cause such accuracy loss.

**Comment by wang-xinyu** [comment]
Hi, I never test the mAP of int8.   For fp32/fp16, mAP will drop 0.02 in tensorrt, for example 0.40->0.38.

**Comment by adujardin** [comment]
I had the same issue with int8, it's probably due to the swish activation of yolov5, see https://github.com/NVIDIA/TensorRT/issues/1114

**Comment by LIU-FAYANG** [comment]
Thanks a lot for your comments, maybe this method would help to improve INT8 accuracy.
https://developer.nvidia.com/blog/improving-int8-accuracy-using-quantization-aware-training-and-the-transfer-learning-toolkit/

**Comment by fabiozappo** [comment]
Hi @wang-xinyu, thank you for your amazing work. I'm familiar with the Yolov5 repo but it is the first time using your repo to improve model performance on edge device. Before doing an export I would like to compare the mAP of fp32/16 tensorrt version against the original pytorch model. Can you tell me how to test map for my yolov5 custom model?

**Comment by wang-xinyu** [comment]
@fabiozappo you can check this pr https://github.com/wang-xinyu/tensorrtx/pull/573
