### ISSUE TITLE
hrnet:  make error

### ISSUE THREAD

**Issue by liweizhong666** [wang-xinyu/tensorrtx#536]
(tensorrt) zlw@prust-System-2:~/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/build$ make
[ 25%] Building CXX object CMakeFiles/hrnet_ocr.dir/hrnet_ocr.cpp.o
In file included from /home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/common.hpp:9:0,
                 from /home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/hrnet_ocr.cpp:7:
/home/zlw/Github/TensorRT-8.0.0.3/include/NvInfer.h:6051:101: warning: ‘IRNNv2Layer’ is deprecated [-Wdeprecated-declarations]
         ITensor& input, int32_t layerCount, int32_t hiddenSize, int32_t maxSeqLen, RNNOperation op) noexcept
                                                                                                     ^
/home/zlw/Github/TensorRT-8.0.0.3/include/NvInfer.h:3080:22: note: declared here
 class TRT_DEPRECATED IRNNv2Layer : public ILayer
                      ^
In file included from /home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/hrnet_ocr.cpp:7:0:
/home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/common.hpp: In function ‘nvinfer1::ILayer* netAddUpsampleBi(nvinfer1::INetworkDefinition*, nvinfer1::ITensor*, nvinfer1::Dims)’:
/home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/common.hpp:357:35: warning: ‘void nvinfer1::IResizeLayer::setAlignCorners(bool)’ is deprecated [-Wdeprecated-declarations]
     upSample->setAlignCorners(true); // tips!
                                   ^
In file included from /home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/common.hpp:9:0,
                 from /home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/hrnet_ocr.cpp:7:
/home/zlw/Github/TensorRT-8.0.0.3/include/NvInfer.h:4621:25: note: declared here
     TRT_DEPRECATED void setAlignCorners(bool alignCorners) noexcept
                         ^
In file included from /home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/hrnet_ocr.cpp:8:0:
/home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/logging.h: At global scope:
_**/home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/logging.h:239:10: **error: looser throw specifier for ‘virtual void Logger::log(nvinfer1::ILogger::Severity, const char*)’
     void log(Severity severity, const char* msg) override****_
          ^
compilation terminated due to -Wfatal-errors.
CMakeFiles/hrnet_ocr.dir/build.make:62: recipe for target 'CMakeFiles/hrnet_ocr.dir/hrnet_ocr.cpp.o' failed
make[2]: *** [CMakeFiles/hrnet_ocr.dir/hrnet_ocr.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hrnet_ocr.dir/all' failed
make[1]: *** [CMakeFiles/hrnet_ocr.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by liweizhong666** [comment]
How to solve this problem?
I made the same mistake after changing the UNET model
@upczww @wang-xinyu 
thanks.

**Comment by liweizhong666** [comment]
Resolved, version issue

**Comment by fjremnav** [comment]
@upczww 

  I got the same error. Please help

Thanks,

**Comment by upczww** [comment]
What's your TensorRT version?
> @upczww 
> 
> 
> 
>   I got the same error. Please help
> 
> 
> 
> Thanks,
> 
>

**Comment by fjremnav** [comment]
@upczww 

  7.0

Thanks,

**Comment by upczww** [comment]
7.x works, please check your env.
> @upczww 
> 
> 
> 
>   7.0
> 
> 
> 
> Thanks,

**Comment by fjremnav** [comment]
@upczww 

It works on 7.x.
However, I got an error for w18_small. It works ok for w48
./hrnet -s hrnet_w18_small.wks hrnet_w18_small.engine small

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

**Comment by upczww** [comment]
w18_small is not supported now.
> @upczww 
> 
> 
> 
> It works on 7.x.
> 
> However, I got an error for w18_small. It works ok for w48
> 
> ./hrnet -s hrnet_w18_small.wks hrnet_w18_small.engine small
> 
> 
> 
> terminate called after throwing an instance of 'std::invalid_argument'
> 
>   what():  stoi
> 
> Aborted (core dumped)
> 
> 
> 
> 
> 
>

**Comment by fjremnav** [comment]
@upczww 

Does w18 support in the current code?
Do you plan to support small in the near future?

Thanks,

**Comment by fjremnav** [comment]
@upczww 

   DO you know where to download w18 and w18 pretrained model so I can try out w18 with your code?

Thanks,

**Comment by upczww** [comment]
https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/pytorch-v1.1

> @upczww 
> 
> 
> 
>    DO you know where to download w18 and w18 pretrained model so I can try out w18 with your code?
> 
> 
> 
> Thanks,

**Comment by fjremnav** [comment]
Thanks for feedbacks. 
I don't see w18 configuration in cityscapes.
It has small_w18 only

Thanks,

**Comment by fjremnav** [comment]
@upczww 

    Can you help?

Thanks,
