### ISSUE TITLE
yolov5_trt.py very slow inference results

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [wang-xinyu/tensorrtx#537]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc. **Jetson Nano with JetPack 4.5**
- OS, e.g. Ubuntu16.04, Win10, etc.  **Ubuntu 18.04**
- Cuda version **10.2**
- TensorRT version **7.1.3**

## About this repo

- which branch/tag/commit are you using? **Master**
- which model? yolov5, retinaface? **YOLOv5**

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s` **python3 yolov5_trt.py**
- what's your output? **Process takes very long and really slow inference time**
- what output do you expect? **Faster inference time**

Hi @wang-xinyu I am facing this problem with the **yolov5_trt.py** script, where after simply running the script using the command **python3 yolov5_trt.py** the Jetson Nano freezes and becomes really laggy then after around 15mints the process ends and inference results saved to output folder. 

The output from running the command is shown below:

```
skymind@skymind:~/yolov5-tensorrt/tensorrtx/yolov5$ python3 yolov5_trt.py
bingding: data (3, 640, 640)
bingding: prob (6001, 1, 1)
batch size is 1
warm_up->(640, 640, 3), time->299.49ms
warm_up->(640, 640, 3), time->111.87ms
warm_up->(640, 640, 3), time->94.74ms
warm_up->(640, 640, 3), time->95.13ms
warm_up->(640, 640, 3), time->78.47ms
warm_up->(640, 640, 3), time->76.78ms
warm_up->(640, 640, 3), time->76.92ms
warm_up->(640, 640, 3), time->76.73ms
warm_up->(640, 640, 3), time->76.47ms
warm_up->(640, 640, 3), time->76.64ms
input->['samples/3.jpeg'], time->75.92ms, saving into output/
input->['samples/3.jpg'], time->322498.13ms, saving into output/
input->['samples/zidane.jpg'], time->3201.35ms, saving into output/
input->['samples/bus.jpg'], time->1612.77ms, saving into output/
input->['samples/2.jpg'], time->3225.97ms, saving into output/
input->['samples/1.jpg'], time->4718.21ms, saving into output/
```
Any reasons as to why it is very slow and any suggestions that could help me to improve the inference time?

**Comment by wang-xinyu** [comment]
seems torchvison.nms takes too long time.
did you check .cpp i.e. the ./yolov5?

**Comment by abuelgasimsaadeldin** [comment]
Hi @wang-xinyu, thank you for the prompt reply. Yes I have tried out ./yolov5 and it is allot quicker. This is the output achieved for the same images:

```
skymind@skymind:~/yolov5-tensorrt/tensorrtx/yolov5/build$ sudo ./yolov5 -d yolov5s.engine ../samples
442ms
129ms
83ms
77ms
77ms
80ms
```

**Comment by wang-xinyu** [comment]
So probably torchvision.nms is very slow on nano. you can try replace it with other nms implementations.

**Comment by wang-xinyu** [comment]
@abuelgasimsaadeldin you can use numpy to implement nms by yourself.
