### ISSUE TITLE
Input-size image in retinaface

### ISSUE THREAD

**Issue by Doanhdz** [wang-xinyu/tensorrtx#538]
First thanks for your great repo. I have final project in my university about face detection. I use your repo retinaface tensorrt in my project. When I change the INPUT_H and INPUT_W in file decode.h to 960, 1280 (default: 480, 640), the result was very bad.
So can you show me how can I modify your code to apply with other size of input image. Thanks you.

**Comment by wang-xinyu** [comment]
did you rebuild everything after changing input size?

**Comment by gouravvemula0** [comment]
I too have same issue when changing the INPUT_W and INPUT_H size, tired rebuilding everything but didn't get correct output

**Comment by Doanhdz** [comment]
Thanks for your reply. 
> did you rebuild everything after changing input size?
Yes after I change the input size, I have run "make" to run make file again, but the result didn't change. The output image showed a lot of boxes.

**Comment by wang-xinyu** [comment]
Also need to change input_w and h in retinaface_trt.py if using py.

**Comment by Doanhdz** [comment]
I use C++, after I change the input size, I have run "make" to run make file again, but the result didn't change. The output image showed a lot of boxes.

**Comment by gouravvemula0** [comment]
delete all the files in build and rebuild. It worked for me
