### ISSUE TITLE
yolov5 TensorRT Implementation

### ISSUE THREAD

**Issue by suryandl** [wang-xinyu/tensorrtx#54]
Hey, thanks for the amazing work. So, I tried converting onnx model to TensorRT for yolov5 but the numerical results don't verify. 
So I was hoping to see a c++ TensorRT implementation from you that would really help. Or maybe you can give some pointers on what changes to make in yolov4.
 Thanks in advance.

**Comment by jinfagang** [comment]
Someone already implemented it.
![image](https://user-images.githubusercontent.com/21303438/85188693-3d0c0000-b2db-11ea-9ba4-f6113179d966.png)

https://zhuanlan.zhihu.com/p/149398749

**Comment by suryandl** [comment]
@jinfagang Hey thanks for sharing wonderful work, but I could not find the code for yolov5 tensorrt implementation. It would be great if you can direct me there? 
Thanks!!

**Comment by jinfagang** [comment]
@suryandl follow the link

**Comment by suryandl** [comment]
@jinfagang I am on [this](http://manaai.cn/aisolution_detail.html?id=4) and I dont see any link which points me to the code. And most of it is in Chinese which is kind of difficult to understand. THanks

**Comment by jinfagang** [comment]
@suryandl add me wechat, I guide u, jintianiloveu

**Comment by makaveli10** [comment]
@jinfagang well too bad I am not wechat and I don't have a friend who can verify my account!!

**Comment by suryandl** [comment]
@jinfagang Well too bad! I am not on wechat and nor do I have a friend who an verify my account! But I would love to see the code! Thanks

**Comment by jinfagang** [comment]
@suryandl  I have telegram

**Comment by suryandl** [comment]
Can you reach out to username -> makaveli_10

**Comment by ausk** [comment]
> @jinfagang I am on [this](http://manaai.cn/aisolution_detail.html?id=4) and I dont see any link which points me to the code. xxx THanks
I know it not a fake news. But I  also can't find the code on MANAAI...

**Comment by PiyalGeorge** [comment]
Hi @jinfagang , I was able to get tensorrt model by following this [repo](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5) . Also i was able to get the output when tried with images. But Is there a way i implement with a usb camera input? I dont have much knowledge in cpp, If it was python it was easy. Could you help me on this?

**Comment by abhigoku10** [comment]
@PiyalGeorge  can you share the environment which you used to obtain the output for the images in the mentioned repo since i tried i am not getting any bounding boxes yet all the process are executing completely

**Comment by PiyalGeorge** [comment]
@abhigoku10 , It was on Nvidia Jetson Nano. I tried 'yolov5s'. 
Jetson Jetpack version : 4.3
TensorRT version : 6.0.1.10
Framework - Pytorch 1.4.0

**Note** that, i did this on august - september 2020, at that time i used **yolov5 v1.0**
