### ISSUE TITLE
tensorrt的retinaface 结合arcface识别视频的准确率和insighface库的差别很大

### ISSUE THREAD

**Issue by microyybar** [wang-xinyu/tensorrtx#541]
同样的人脸库和同样的测试视频（共2644帧，基本每帧都有目标）识别视频中的一个人，使用retinaface检测，arcface获取特征向量。
都选择相同的模型，分别用tensorrt版和insightface的mxnet版测试。其他参数都一样，比如检测尺寸都设定为640，480
使用insightface可以识别出1996帧，tensorrt只识别出632帧。
请问这是怎么回事呢？

**Comment by wang-xinyu** [comment]
做一些底层比较，比如单独对比检测，单独对比提特征

**Comment by magicwifi** [comment]
R100的好一些，我们之后争取提交一个r100的pr
