### ISSUE TITLE
generate TensorRT engine file

### ISSUE THREAD

**Issue by liweizhong666** [wang-xinyu/tensorrtx#542]
set name out
[05/12/2021-17:01:50] [E] [TRT] safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
[05/12/2021-17:01:50] [E] [TRT] safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 1 (Could not initialize cudnn, please check cudnn installation.)
build success!
hrnet_ocr: /home/zlw/Github/tensorrtx/hrnet/hrnet-semantic-segmentation/hrnet_ocr.cpp:517: void APIToModel(unsigned int, nvinfer1::IHostMemory**, std::__cxx11::string, int): Assertion `engine != nullptr' failed.

What's the problem? Is it because of my own cudnn installation

**Comment by wang-xinyu** [comment]
cudnn and trt versions must match.

you can try docker.

**Comment by liweizhong666** [comment]
trt ： 7.2.1&nbsp;
What version of cudnn should I use





Sincerely,
Liwei Zhong


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-xinyu/tensorrtx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 下午5:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-xinyu/tensorrtx] generate TensorRT engine file (#542)





 
cudnn and trt versions must match.
 
you can try docker.

**Comment by wang-xinyu** [comment]
trt package usually includes cudnn .so inside. you probably have another cudnn in your OS. which is not compatible with your trt.

so try a clean environments or use docker.

**Comment by liweizhong666** [comment]
I use the miniconda in linux os, but i not root





Sincerely,
Liwei Zhong


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-xinyu/tensorrtx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 晚上6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-xinyu/tensorrtx] generate TensorRT engine file (#542)





 
trt package usually includes cudnn .so inside. you probably have another cudnn in your OS. which is not compatible with your trt.
 
so try a clean environments or use docker.
