### ISSUE TITLE
sudo ./yolov5 -s yolov5s.wts yolov5.engine c 0.17 0.25   -----error

### ISSUE THREAD

**Issue by zhaoxiaolong2020** [wang-xinyu/tensorrtx#543]
## Env

- GPU,RTX2060
-  Ubuntu18.04,
- Cuda version 10.2
- TensorRT 7.2.3.4

## About this repo

- tensorrtx latested version 
- yolov5-v5.0 version

## Your problem

- what is your command?
 `sudo ./yolov5 -s yolov5s.wts yolov5.engine c 0.17 0.25 `

- what's your output?
[05/13/2021-10:32:25] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addResize::930, condition: input.getDimensions().nbDims > 0
yolov5: /home/zxl/mywork/01-tensorrtx/yolov5/yolov5.cpp:65: nvinfer1::ICudaEngine* build_engine(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType, float&, float&, std::__cxx11::string&): Assertion `upsample11' failed.

- what output do you expect?
could you help find what is the error ? and how to solve

**Comment by wang-xinyu** [comment]
can you double check if 0.17 0.25 are right params of your model?
