### ISSUE TITLE
hrnet seg_result

### ISSUE THREAD

**Issue by liweizhong666** [wang-xinyu/tensorrtx#544]
The segmentation result is all black false color image. What is the reason?

The following prompt appears in the test. Is it an error? Does this cause segmentation result error?
1.jpg
[05/13/2021-10:44:53] [F] [TRT] Assertion failed: cublasStatus == CUBLAS_STATUS_SUCCESS
../rtSafe/cublas/cublasLtWrapper.cpp:279
Aborting...
[05/13/2021-10:44:53] [E] [TRT] FAILED_EXECUTION: std::exception
infer time: 57ms

**Comment by wang-xinyu** [comment]
It's still the environments error. again you should use docker!

**Comment by liweizhong666** [comment]
So what's the problem, CUDA version? Cudnn version?
The virtual environment I use is also clean.
