### ISSUE TITLE
NameError: name 'Darknet' is not defined

### ISSUE THREAD

**Issue by xinsuinizhuan** [wang-xinyu/tensorrtx#548]
(yolo3) E:\git_item\yolov3-master>python gen_wts.py yolov4.weights
Traceback (most recent call last):
  File "gen_wts.py", line 6, in <module>
    model = Darknet('cfg/yolov4.cfg', (608, 608))
NameError: name 'Darknet' is not defined

**Comment by wang-xinyu** [comment]
Refer to readme, it's using archive branch of yolov3.

**Comment by xinsuinizhuan** [comment]
> 
> 
> Refer to readme, it's using archive branch of yolov3.

yes, i use the archive branch of yolov3
![图片](https://user-images.githubusercontent.com/40679769/118432843-403a8680-b70c-11eb-99b3-468d797e1066.png)
but ,still tip

**Comment by wang-xinyu** [comment]
Darknet is defined in https://github.com/ultralytics/yolov3/blob/archive/models.py#L225.

**Comment by xinsuinizhuan** [comment]
> 
> 
> Darknet is defined in https://github.com/ultralytics/yolov3/blob/archive/models.py#L225.

it should use the tensorrtx_yolov5_v4\yolov4\gen_wts.py, when use the tensorrtx_yolov5_v5\yolov4\gen_wts.py, it not work.
