### ISSUE TITLE
Single Class Yolov5 - NUM_CLASS in yololayer.h doesn't accept anything but 3

### ISSUE THREAD

**Issue by deepconsc** [wang-xinyu/tensorrtx#549]
## Env

- GPU -  V100
- OS -  Ubuntu18.04
- Cuda version - 10.0
- TensorRT version - 7

## About this repo

- which branch/tag/commit are you using? - yolov5 - (v4 branch)
- which model? yolov5, retinaface? - yolov5 (v4 branch)

## Problem

While trying to convert single-class custom trained yolo, the NUM_CLASS in yololayer.h doesn't accept anything but 3. 
Firstly I thought it was because of ['background', '__ignore__', 'someclass'], but we see that in segmentation models (mainly).  Plus, it holds 80 on COCO, which is exact amount of classes COCO has. 

Any ideas?

**Comment by wang-xinyu** [comment]
You can check the last 3 conv layers of yolov5, the channels should be `3 * (Yolo::CLASS_NUM + 5)`

**Comment by deepconsc** [comment]
Thanks for your response! 
Would you advice exporting single-class yolo with CLASS_NUM=3 var or maybe you have better workaround in your mind?!

**Comment by wang-xinyu** [comment]
I mean you should check the last 3 conv layers of your yolov5 model, if the channels is 3 * (3 + 5), i.e. 24.
Then you must set class_num=3 in yololayer.h.
