### ISSUE TITLE
Inference output all 0 – yolov3-spp single class

### ISSUE THREAD

**Issue by prathik-naidu** [wang-xinyu/tensorrtx#55]
Hi,

I setup a yolov3-spp-1cls.cfg (detecting people) and was able to successfully generate the tensor RT engine (also referenced #7) but the inference is not detecting anything. Noticed that the output from the inference stored in the `prob` variable contains all zeros. 

Any reason why this might be happening? Not sure if it has something to do with the creating the engine (although I didn't get any errors). I also made sure to change `yololayer.h` with to `CLASSNUM = 1` and my desired `INPUT_H`/`INPUT_W`.

Thanks for the great work on this repo!

**Comment by wang-xinyu** [comment]
what's the INPUT_H / INPUT_W are you using?

**Comment by prathik-naidu** [comment]
I'm using INPUT_H = 256, INPUT_W = 416

**Comment by wang-xinyu** [comment]
That should work fine.  Can you try clean the `build` directory and rebuild from scratch?

**Comment by prathik-naidu** [comment]
I tried that but the the output from `doInference` is still all zeros. I'm running this on the images in the samples folder and the data array that reads those images also seems to be stored correctly.

**Comment by wang-xinyu** [comment]
There must be something wrong.
Did you modify yolov3-spp-1cls.cfg? or somewhere different from the default setup?

**Comment by prathik-naidu** [comment]
I didn't modify the `yolov3-spp-1cls.cfg`. The only main difference in what i'm doing seems to be the .pt file that I'm using for `get_wts.py` and adjusting the input image size to 256x416. I'm also using everything from the ultralytics repo and didn't modify any of that code either. Those weights should be fine because I've used them before so not sure what else could be the reason for this?

Has the yolov3 1cls worked with tensorrtx before?

**Comment by wang-xinyu** [comment]
did you modify `gen_wts.py`, and set `cfg/yolov3-spp-1cls.cfg`?

**Comment by wang-xinyu** [comment]
Yes, I tried yolov3-1cls before, which works fine.

**Comment by prathik-naidu** [comment]
yup I'm using the `yolov3-spp-1cls.cfg` in `gen_wts.py`. I can try getting some new weights but I don't think that's the issue. Let me know if you have any other ideas – the only made changes to the image size, the number of classes (modified in the .h) and using my own weights.

**Comment by wang-xinyu** [comment]
What about you detect these two images in pytorch using this weights?  How many objects can be detected?

The yololayer in this yolov3-spp tensorrt only outputs `confidence > 0.1`.

**Comment by prathik-naidu** [comment]
I'm able to output the expected bounding boxes for these images (for example 2 objects are detected in `zidane.jpg`), so the weights seem to be fine. I was looking at the preprocessing code in the cpp file to make sure it matches the preprocessing that I had on the pytorch side. I use the `letterbox(...)` method from ultralytics, convert BGR -> RGB, and HWC -> CHW (numpy functions). I then change the dtype to either float16 for float32 and scale down to 0-1 range. 

Seems like you used the similar logic from the `letterbox(...)` box (which is what I use) and also do the BGR -> RGB change as well after calling `preprocess_img`. Another explanation is that the model weights may not have been deserialized properly but it seems like you're just using the standard tensorRT functions for this. lmk if you have any thoughts

**Comment by wang-xinyu** [comment]
No idea...
If you can share your weights, or whatever weights of yolov3-spp-1cls. I can try it on my side.

**Comment by prathik-naidu** [comment]
Here is a link to the weights I'm using for yolov3-spp-1cls: https://www.dropbox.com/s/ro0xybgld9uvsim/yolov3-spp-1cls-weights.pt?dl=0

Also, I'm running this on an RTX 2080 Ti with cuda 10.2, tensorRT 7.0.0-1, and pytorch 1.4.0

Let me know if it works for you. Thanks for the help!

**Comment by wang-xinyu** [comment]
are your using the latest commit of ultralytics/yolov3?

I just tried this command:

```
python detect.py --cfg cfg/yolov3-spp-1cls.cfg --weights weights/yolov3-spp-1cls-weights.pt 
```

Nothing detected in bus.jpg and zidane.jpg.

**Comment by prathik-naidu** [comment]
Ended writing another workaround so closing this issue. Thanks for all the help!

**Comment by jasdeep06** [comment]
@prathik-naidu I am facing the same issue.Can you shed some light on how you solved it?I too have single class model working alright when I run detect.py from ultralytics repo.But here all probs are 0 and no detection takes place.
