### ISSUE TITLE
In yolov5_trt.py torch.tensor not moving in cuda. Script freezes.

### ISSUE THREAD

**Issue by Iljanikolaev** [wang-xinyu/tensorrtx#550]
## Env

- GPU, Jetson Nano
- OS, e.g. Ubuntu16.04

## About this repo

- which branch/tag/commit are you using?
- The last commit
- which model? yolov5, retinaface?
- Custom yolov5s

## Your problem
 In yolov5_trt.py torch.tensor not moving in cuda(line 296). Script freezes.
https://github.com/wang-xinyu/tensorrtx/blob/48666070823d0da10baec26412bc119c37f6c87c/yolov5/yolov5_trt.py#L296
If using  without cuda(): pred = torch.Tensor(pred) - all working.
I want to understand what the problem is. I think you need to make friends with pycuda and pytorch.
Can anyone help?

**Comment by wang-xinyu** [comment]
It is not recommended to use torch on nano. You can use the c++ code, or revise .py.
