### ISSUE TITLE
how to infer a video or camera  in tensorrtx/yolov5?

### ISSUE THREAD

**Issue by zhaoxiaolong2020** [wang-xinyu/tensorrtx#552]
this project can infer images ,but how to infer a video or camera  in tensorrtx/yolov5?  thansk a lot

**Comment by Alex-Beh** [comment]
Hi, I managed to run the yolov5 with an usb camera. You can see the code [here](https://github.com/Alex-Beh/tensorrtx/blob/c1220241f80aa9db8411c724905e6e695416f3e9/yolov5/video_inteference_yolov5.cpp).

**Comment by zhaoxiaolong2020** [comment]
> 
> 
> Hi, I managed to run the yolov5 with an usb camera. You can see the code [here](https://github.com/Alex-Beh/tensorrtx/blob/c1220241f80aa9db8411c724905e6e695416f3e9/yolov5/video_inteference_yolov5.cpp).

thanks!  Alex-Beh! got it!

**Comment by xinhappy1** [comment]
> 你能告诉我如何使用 video_inteference_yolov5.cpp 吗？
> 
> 我不知道如何使用 cpp 文件。如何使用它对 USB 摄像头进行推理？请帮我

hi, do you know how to inference on a video now? Can you tell me how to do it?

**Comment by wang-xinyu** [comment]
You can use opencv VideoCapture to read frame from video.
