### ISSUE TITLE
mobilenetv3 build tensorrt enginer issues 

### ISSUE THREAD

**Issue by SokPhanith** [wang-xinyu/tensorrtx#553]
## Env

- GPU, Nano
- Jetpak 4.5
- Cuda 10.2
- TensorRT 7.1

## About this repo
mobilenetv3 

## Your problem
I try convert mobilenetv3 to mobilenetv3.engine but got some issue like this.
./mobilenetv3 -s large
large
Loading weights: ../mbv3_large.wts
len 16
len 0
[05/20/2021-02:31:40] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
mobilenetv3: /home/phanith/tensorrtx/mobilenet/mobilenetv3/mobilenet_v3.cpp:108: nvinfer1::IScaleLayer* addBatchNorm(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted (core dumped)

1. python3 mobilenetv3.py 
import torch
from torch import nn
from torch.nn import functional as F
import torchvision

def main():
    print('cuda device count: ', torch.cuda.device_count())
    net = torchvision.models.mobilenet_v3_large(pretrained=True)
    #net.fc = nn.Linear(512, 2)
    net = net.eval()
    net = net.to('cuda:0')
    print(net)
    tmp = torch.ones(1, 3, 224, 224).to('cuda:0')
    out = net(tmp)
    print('mobilenet out:', out.shape)
    torch.save(net, "mobilenetv3.pth")

if __name__ == '__main__':
    main()

2. python3 inference.py
import torch
from torch import nn
import torchvision
import os
import struct
from torchsummary import summary

def main():
    print('cuda device count: ', torch.cuda.device_count())
    net = torch.load('mobilenetv3.pth')
    net = net.to('cuda:0')
    net = net.eval()
    print('model: ', net)
    #print('state dict: ', net.state_dict().keys())
    tmp = torch.ones(1, 3, 224, 224).to('cuda:0')
    print('input: ', tmp)
    out = net(tmp)

    print('output:', out)

    summary(net, (3, 224, 224))
    #return
    f = open("mbv3_large.wts", 'w')
    f.write("{}\n".format(len(net.state_dict().keys())))
    for k,v in net.state_dict().items():
        print('key: ', k)
        print('value: ', v.shape)
        vr = v.reshape(-1).cpu().numpy()
        f.write("{} {}".format(k, len(vr)))
        for vv in vr:
            f.write(" ")
            f.write(struct.pack(">f", float(vv)).hex())
        f.write("\n")

if __name__ == '__main__':
    main()

3. ./mobilenetv3 -s large

**Comment by wang-xinyu** [comment]
@aditya-dl could you assist?

**Comment by aditya-dl** [comment]
I will look into this.

**Comment by aditya-dl** [comment]
@SokPhanith The model is not compatible with the torchvision models, rather it is based on the PyTorch repository mentioned in the README. I am working to export the torchvision mobilenetv3 model.

**Comment by SokPhanith** [comment]
@aditya-dl Thank you so much. It's working now

**Comment by aditya-dl** [comment]
@aditya-dl No problem. Let me know if you face any problem.
