### ISSUE TITLE
cudnn error when using yolov5

### ISSUE THREAD

**Issue by ShanQiong** [wang-xinyu/tensorrtx#555]
hi, thanks for your great works;
my yolov5 model is from yolov5-v4.0 
when the input size is 960x960, it generate .engine  from .wts file correctly, and the inferencing works;
when the input size is 960(width)x640(or 544)(height), it generate .engine correctly, but the inferencing meet error, as follow

cudnn error in configure: 7 CUDNN_STATUS_MAPPING_ERROR;

after google, I don't find a solution to fixed it, is any suggestion to fixed this problem, thanks

**Comment by spacewalk01** [comment]
Hi did you solve the problem? i am getting the same error when running yolov5
