### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by bkhti4** [wang-xinyu/tensorrtx#557]
I am getting the same error for yolov5 of any type. It seems if I use .weights (yolov4, yolov3) to .wts conversion it works fine but if I use .pt to .wts then the engine throws the Floating point error.
Can anyone check into it.

System settings:
- GPU, e.g. RTX 3070
- OS, e.g. Ubuntu20.04.
- Cuda version 11.2
- TensorRT version 8.0.0.3

To recreate for Tensorrt 8 use the [https://github.com/wang-xinyu/tensorrtx/pull/540](https://github.com/wang-xinyu/tensorrtx/pull/540), since it is working atleast for yolov5, yolov4, yolov3.

The commands are exactly same as mentioned in the [yolov5 README.md](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#how-to-run-yolov5s-as-example). 
Once you run the deserializer the command prompt simply show **'Floating point exception'**.

This error does not appear if I run the yolov3 or yolov4.

**Comment by wang-xinyu** [comment]
pls paste your step one by one and also the error logs.
