### ISSUE TITLE
sudo ./yolov4 -s fails 

### ISSUE THREAD

**Issue by saikrishnadas** [wang-xinyu/tensorrtx#56]
@wang-xinyu 
I did train a custom yolov4 darknet model.

I successfully converted the weight to yolov4.wts with change in input shape and class in yololayer.sh.

Now while i used  ` sudo ./yolov4 -s` i get a error.

Error log:
```
agrima@agrima-desktop:~/Documents/yolov4-trt/tensorrtx/yolov4$ sudo ./yolov4 -s Loading weights: ../yolov4.wts
yolov4: /home/agrima/Documents/yolov4-trt/tensorrtx/yolov4/yolov4.cpp:147: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file."' failed.
Aborted
```

**Comment by wang-xinyu** [comment]
Did you put `yolov4.wts` at the right path?

**Comment by elicse** [comment]
It seems you did not set the path of the kDIRECTORIES variable correctly.
