### ISSUE TITLE
Why is tx2 inference retinaface so slow, nearly 400ms 

### ISSUE THREAD

**Issue by panmengjia** [wang-xinyu/tensorrtx#564]
## Env

- GPU： TX2
- OS： Ubuntu18.04
- Cuda version： 10.2
- TensorRT： 5

## About this repo

- using branch : trt4
- model : retinaface
- using fp16 inference

## Your problem

***When I use tx2 to inference  the retinaface model, the average time is nearly 400ms; But inferencing time on Xavier nx is only 33ms .The picture size is 1600*898 . I have modified retina_rt50.cpp to make sure to use fp16 inference. modified as followed:***
```
#include "NvInfer.h"
#include "NvInferPlugin.h"
#include "cuda_runtime_api.h"
#include "common.h"
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <vector>
#include <chrono>
#include "plugin_factory.h"
#include "decode.h"
#include <opencv2/opencv.hpp>

#define USE_FP16  // comment out this if want to use FP32
#define DEVICE 0  // GPU id

// stuff we know about the network and the input/output blobs
static const int INPUT_H = decodeplugin::INPUT_H;  // H, W must be able to  be divided by 32.
static const int INPUT_W = decodeplugin::INPUT_W;;
static const int OUTPUT_SIZE = (INPUT_H / 8 * INPUT_W / 8 + INPUT_H / 16 * INPUT_W / 16 + INPUT_H / 32 * INPUT_W / 32) * 2  * 15 + 1;
const char* INPUT_BLOB_NAME = "data";
const char* OUTPUT_BLOB_NAME = "prob";
```
***How to solve this problem ？***

**Comment by makaveli10** [comment]
@panmengjia you can try reducing the image size.

**Comment by panmengjia** [comment]
Yes，It may be that tx2's inferencing  ability is too weak .thanks!
@makaveli10
