### ISSUE TITLE
Yolov5 dimensions?

### ISSUE THREAD

**Issue by mbufi** [wang-xinyu/tensorrtx#57]
Hello, thank you for the awesome implementations! 

Can one provide any time of dimensions for the yolov5 tensorRT engine or does it only work for 608x608? 

Thank you!

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#config

You can set input dims in `yololayer.h`, it should work with any size divisible by 32,  like 320, 416,  608, 640, etc.

**Comment by mbufi** [comment]
And these are the anchor boxes correct? If we calculated different ones for our dataset, should we also update these?

```
    static constexpr YoloKernel yolo1 = {
        INPUT_W / 32,
        INPUT_H / 32,
        {116,90,  156,198,  373,326}
    };
    static constexpr YoloKernel yolo2 = {
        INPUT_W / 16,
        INPUT_H / 16,
        {30,61,  62,45,  59,119}
    };
    static constexpr YoloKernel yolo3 = {
        INPUT_W / 8,
        INPUT_H / 8,
        {10,13,  16,30,  33,23}
    };
```

**Comment by wang-xinyu** [comment]
Usually, don't need to modify  the default anchors. That depends on your own setup.

**Comment by mbufi** [comment]
Correct. Okay thank you.
