### ISSUE TITLE
the dimension of trt output in yolov5?

### ISSUE THREAD

**Issue by henbucuoshanghai** [wang-xinyu/tensorrtx#570]
in yolov5_trt.py and yolov5.cpp
the output of the cuda dimension is boxes?
why?  the dimension is ?

https://github.com/wang-xinyu/tensorrtx/blob/668d89bbd5319c00be9f648d3db8f61689417d2d/yolov5/yolov5_trt.py#L167

**Comment by wang-xinyu** [comment]
Yes, you can check yololayer.cu to understand what the output is.
