### ISSUE TITLE
Same wts file but different inference results  in 2080Ti and jetson xviar 

### ISSUE THREAD

**Issue by Youjiangbaba** [wang-xinyu/tensorrtx#575]
Net: resnext50
Input: 1x1x224x224
Output:67

I use the same wts file deployed  in 2080ti and nvidia jetson xvivar, but got different results, not quantified with f16 or int8.
The errors about %5（avg(outputs) = 50  ）.

**Comment by wang-xinyu** [comment]
You can try input a `ones(1x1x224x224)` tensor to both and compare the output.

**Comment by Youjiangbaba** [comment]
There are also errors, but the error is very small, the maximum is only 0.45.(<1%)
