### ISSUE TITLE
How to load two diffrent models in one thread?

### ISSUE THREAD

**Issue by kaiven11** [wang-xinyu/tensorrtx#579]
## Env

- GPU, e.g. V100.
- OS, e.g. Ubuntu18.04,
- Cuda 10.2
- TensorRT 7.0.0.1

## About this repo

- yolov5 3.0
- custom model 

## Your problem

I want to load a yolov3 model and a yolov5 model  one thread,  Are there a sample code ?
![image](https://user-images.githubusercontent.com/25794106/121174900-06811980-c88d-11eb-9b81-ae7336595ffc.png)

when I load two engine,  report the above error.

**Comment by wang-xinyu** [comment]
Probably the plugin class name have conflicts.
But if you rename yololayerplugin, you need to debug it.
