### ISSUE TITLE
Unsupported fields ['max_delta'] when convert yolov4 from darknet

### ISSUE THREAD

**Issue by ausk** [wang-xinyu/tensorrtx#58]
When convert yolov4 form darknet format, it complains:

```
  File "/mnt/git/darknet/Yolov3/utils/parse_config.py", line 49, in parse_model_cfg
    assert not any(u), "Unsupported fields %s in %s. See https://github.com/ultralytics/yolov3/issues/631" % (u, path)
AssertionError: Unsupported fields ['max_delta'] in /mnt/bak/git/darknet/data/cfg/yolov4.cfg. See https://github.com/ultralytics/yolov3/issues/631
```

The `max_delta` in [yolo] section (yolov4.cfg) is not in supported list of ` parse_config.py(ultralytics )`.

Have you encounter such an issue, how to solve it?

**Comment by wang-xinyu** [comment]
you can try comment out the Unsupported fields in .cfg

**Comment by ausk** [comment]
Yes, it runs when comment out the `max_delta`.
Alternative way is to add `if "max_delta" in line: continue` in  `parse_config.py`.

```
def parse_model_cfg(path):
    # ... 
    for line in lines:
        # add this line
        if "max_delta" in line: continue
```
