### ISSUE TITLE
make fails after cmake in ../build for yolov5

### ISSUE THREAD

**Issue by tuananhroman** [wang-xinyu/tensorrtx#580]
## Env

- GPU: 
Geforce GTX 860M
- OS: 
Ubuntu18.04
- Cuda 11.0
- TensorRT version 8.0.0

## About this repo

- which branch/tag/commit are you using? 
master branch
- which model? 
yolov5s.pt

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
`make`
- what's your output?
![image](https://user-images.githubusercontent.com/35111381/121211623-ec3f3f80-c87c-11eb-842c-ecb3b38f4345.png)
![image](https://user-images.githubusercontent.com/35111381/121211675-f6613e00-c87c-11eb-8410-fa6418e33640.png)

- what output do you expect?

Would be grateful if somebody could give me a hint how to proceed in my case!

**Comment by wang-xinyu** [comment]
8.0 is not supported for now, refer to https://github.com/wang-xinyu/tensorrtx/pull/540 temporarily.
