### ISSUE TITLE
有多个输出的时候 怎么确定输出对应元素？

### ISSUE THREAD

**Issue by henbucuoshanghai** [wang-xinyu/tensorrtx#581]
if engine.binding_is_input(binding):
                        self.input_w = engine.get_binding_shape(binding)[-1]
                        self.input_h = engine.get_binding_shape(binding)[-2]
                        host_inputs.append(host_mem)
                        cuda_inputs.append(cuda_mem)
                    else:
                        host_outputs.append(host_mem)
                        <span class="pl-s1">cuda_outputs</span>.<span class="pl-en">append</span>(<span class="pl-s1">cuda_mem</span>)

yolo5.py里面   如果有多个输出，输出的时候怎样一一对应呢？求助 tks

**Comment by wang-xinyu** [comment]
binding name, binding type, binding shape，都可以作为output id判别依据

**Comment by henbucuoshanghai** [comment]
# Transfer input data  to the gpu
                # Run inference.
                context.execute_async(batch_size=self.batch_size, bindings=bindings, stream_handle=stream.handle)
                # Transfer predictions back from the GPU.
                cuda.memcpy_dtoh_async(host_outputs[0], cuda_outputs[0], stream)
                # Synchronize the stream
                stream.synchronize()
你好这是yolov5.py里面的    输出环节           请问cuda_outputs[0]就是最后运行完的结果？为什么有[0] ，如果三个输出，则[1],[2]均同样的句子？不懂       多谢多谢

**Comment by wang-xinyu** [comment]
自己试一下就知道

**Comment by henbucuoshanghai** [comment]
trtx项目里那个项目是多输出的？多谢多谢

**Comment by wang-xinyu** [comment]
refinedet
