### ISSUE TITLE
根据实际效果，只输出2层，这个应该如何处理

### ISSUE THREAD

**Issue by tonyskypc** [wang-xinyu/tensorrtx#582]
我们尝试将32倍下采样的一层输出去掉，只保留det0和det1，请问如何调整里面的网络结果，非常感谢。

**Comment by wang-xinyu** [comment]
需要看懂代码修改，主要是网络搭建的最后几层，还有plugin的调整

**Comment by tonyskypc** [comment]
已经将最后几层进行修改了，还是不行，能否帮我们详细看看，相关访求发到您 的163邮箱了，谢谢。

**Comment by tonyskypc** [comment]
> 需要看懂代码修改，主要是网络搭建的最后几层，还有plugin的调整

**Comment by wang-xinyu** [comment]
@tonyskypc did not rcv any email, you can add my wechat to discuss your requirments.

**Comment by tonyskypc** [comment]
没有找到您 的任何微信号可以加，您方便发给给我吗？37598989@qq.com

**Comment by wang-xinyu** [comment]
At the end of tensorrtx/readme
