### ISSUE TITLE
YOLOV5trt python inference on video

### ISSUE THREAD

**Issue by LIU-FAYANG** [wang-xinyu/tensorrtx#583]
Hi, could you guide me a bit on how to modify the python code to inference on a video, just a few steps of guidance would be great, thanks for your kind help! :)

**Comment by wang-xinyu** [comment]
You can try opencv videocapture.

**Comment by LIU-FAYANG** [comment]
Thanks for your help, I'm trying it. 
I have a question here, in ur work you read the frame using cv.imread() in the get_raw_image function and it returns a generator and pass to the inferthread. If I read the frame from cv.videocapture.read() it would return a numpy nd array, if that's the case, what should I change in the inferthread to make it work? I'm a bit confused right now, thanks for your help!

**Comment by wang-xinyu** [comment]
You can get each frame using videocapture, a frame is cvmat, which is equal to a cvmat returned by imread.

**Comment by LIU-FAYANG** [comment]
hi, I made some changes in the main and infer module and I'm a bit confused right now, some error like this showed up: 
Exception in thread Thread-1167:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "yolov5_trt_videov1.py", line 326, in run
    batch_image_raw, use_time, result_boxes, result_scores, result_classid = self.yolov5_wrapper.infer(self.single_frame)
  File "yolov5_trt_videov1.py", line 171, in infer
    output[1 * 6001: (1 + 1) * 6001], origin_h, origin_w
  File "yolov5_trt_videov1.py", line 292, in post_process
    num = int(output[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

Can I ask the meaning of output[i * 6001: (i + 1) * 6001], origin_h, origin_w
in your original work? I could not figure the meaning of 6001.
Also, can I post the full code here so you can take a look?
Thanks a lot!

**Comment by LIU-FAYANG** [comment]
Hi, I just check the latest post by the guy who is also working on video inference and the 6001 is the output size. I think it works now, I can extract the bounding box from the inference code and deploy on another application, thanks for your great work!

**Comment by ahhhxxx** [comment]
> Hi, could you guide me a bit on how to modify the python code to inference on a video, just a few steps of guidance would be great, thanks for your kind help! :)

Hello, can I add you on QQ? I also need video detection

**Comment by doubiydd** [comment]
I need video detection too and can you pls teach me how to do it ?@LIU-FAYANG @ahhhxxx
