### ISSUE TITLE
TRT engine always returns zero detections (yolov5s)

### ISSUE THREAD

**Issue by tuananhroman** [wang-xinyu/tensorrtx#584]
## Env

- GPU:
Geforce GTX 860M
- OS:
Ubuntu 18.04 
- Cuda version
CUDA 11.0
- TensorRT version
8.0.0

## About this repo

- which branch/tag/commit are you using?
[#540](https://github.com/wang-xinyu/tensorrtx/pull/540)
- which model? yolov5, retinaface?
Yolov5s (V5)
## Your problem
After successfully building the directory and serializing the respective model, I tried to infer the sample pictures using `./yolov5` and also the python script. Unfortunately, in both ways, no detections are being made. When running the python script in a debugger, it seems that `host_output[0]` is always a zero ndarray.
Does one of you have any suggestions as of what could be the reason?

Thanks a lot in advance!

- what is your command? e.g. `sudo ./yolov5 -s`
`sudo ./yolov5 -d yolov5s.engine ../samples` / `python yolov5_trt.py`
- what's your output?
![Python script](https://user-images.githubusercontent.com/35111381/121331498-383ec280-c917-11eb-8141-89761444d090.png)
![Serializing the model](https://user-images.githubusercontent.com/35111381/121331607-51477380-c917-11eb-84d8-30a26b5dd3ba.png)
- what output do you expect?

**Comment by wang-xinyu** [comment]
are u using the official yolov5-v5 model?

**Comment by tuananhroman** [comment]
Hey wang, thanks for the fast reply. Yes, I downloaded the model from [ultralytics release page](https://github.com/ultralytics/yolov5/releases/tag/v5.0).

**Comment by wang-xinyu** [comment]
Im not sure 8.0 can work well, you should try tensorrt 7.x.

**Comment by tuananhroman** [comment]
Oh I think i found the reason why. In the Yolov5TRT function preprocess_image() the cv2 method 'cv2.copyMakeBorder' is called on the image. Unfortunately, the operation returns a zero array there instead of the padded image. 
I'm currently using OpenCV 4.5.2. which should be fine I suppose?

**Comment by myBestLove** [comment]
I met the same problem, I use the yolov5 v5 - yolov5m.wts, and convert to engine successfully. but result is None, I check the input and output of cuda memory , input is true, but output is 0.0000, I check the numclass and input size, and others config, I can't find any idea.
My envi is window10, cuda 11.0, tensorrt 7.x,  cudnn is 7.6，

**Comment by myBestLove** [comment]
OK, I find the reason is cuda version , I change the cuda version to 10.2, it works.   but I still don't know why different cuda version cause this error.

**Comment by wang-xinyu** [comment]
tensorrt depends on cuda, when you download tensorrt, did you see there are different packages for different cuda?
