### ISSUE TITLE
windows平台生成的lenet engine有问题

### ISSUE THREAD

**Issue by JHshen0124** [wang-xinyu/tensorrtx#585]
Serialization Error in nvinfer1::rt::CoreReadArchive::verifyHeader: 0 (Length in header does not match remaining archive length)有这个错误，其他网络还没有尝试

**Comment by wang-xinyu** [comment]
did you follow readme https://github.com/wang-xinyu/tensorrtx/tree/master/lenet strictly?

**Comment by JHshen0124** [comment]
yes，it works on linux but not works on windows

**Comment by wang-xinyu** [comment]
Maybe your tensorrt environments not right. You can try tensorrt official samples first.

**Comment by JHshen0124** [comment]
I succeed to load engine with retina. But still failed with lenet

**Comment by JHshen0124** [comment]
Solved.When use ofstream to write engine file ，we need to use std::ios::binary | std::ios::out mode

**Comment by wang-xinyu** [comment]
@JHshen0124 thx for the feedback, can you help raise a pr to fix it?
