### ISSUE TITLE
What is 6001 stands for in this line?

### ISSUE THREAD

**Issue by alpacino98** [wang-xinyu/tensorrtx#587]
https://github.com/wang-xinyu/tensorrtx/blob/668d89bbd5319c00be9f648d3db8f61689417d2d/yolov5/yolov5_trt.py#L171

I am trying to write my own inference code from yolov5_trt.py for video processing. But i could not understand what 6001 stands for, it would be super if you can tell me.

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/668d89bbd5319c00be9f648d3db8f61689417d2d/yolov5/yolov5.cpp#L20

The definition of OUTPUT_SIZE.
