### ISSUE TITLE
Yolov5 engine already supporting dynamic batch size?

### ISSUE THREAD

**Issue by tuananhroman** [wang-xinyu/tensorrtx#588]
Hey everybody,

I'm currently working on a panorama live tracking application and was intending to speed up the inference with TRT.
As I'm quite new to TRT and this repo, I wanted to ask if the engines generated with `sudo ./yolov5` are already capable of infering on arbitrary batch sizes by using `context.execute_async_v2`. If not, what needs to be modified to facilitate it?

Thanks a lot!

**Comment by wang-xinyu** [comment]
refer to https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#config
you can set batch size.
After building, it can support batchsize >= 1 and <= `BATCHSIZE`

**Comment by luvwinnie** [comment]
@wang-xinyu It seems like when using in DeepStream it can't use different batch size.
Have you ever tried to create the engine with explicit batch size network definition?
```
IBuilder::createNetworkV2(1U <<
        static_cast<int>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH))
```

https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-601/tensorrt-developer-guide/index.html#work_dynamic_shapes

**Comment by wang-xinyu** [comment]
Yes, but using explicit batch does not make speed faster, so I did not commit it.
For deepstream, I have no idea, never use it.

**Comment by luvwinnie** [comment]
@wang-xinyu Thank you! I wish to test it with explicit batch in deepstream, can you show me some guide how to build the tensorrt engine with explicit batch?

**Comment by wang-xinyu** [comment]
Besides the line you posted above, you also need to adapt yololayer plugin to use dims4 rather than dims3.

**Comment by luvwinnie** [comment]
@wang-xinyu Thank you! I would like to try to modify it!
