### ISSUE TITLE
./yolov5s -s Fails

### ISSUE THREAD

**Issue by makaveli10** [wang-xinyu/tensorrtx#59]
Cannot load weights I have yolov5s.wts in the root folder and building from the build folder. This is weird and should not happen.

    root@0da1a0f1cdeb:/home/build# ls ..
    CMakeLists.txt  build       gen_wts.py  utils.h       yololayer.h  yolov5s.wts
    README.md       common.hpp  logging.h   yololayer.cu  yolov5s.cpp

    root@0da1a0f1cdeb:/home/build# ./yolov5s -s
    Loading weights: ../yolov5s.wts
    [06/23/2020-06:50:46] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 
    0 ? (shift.values != nullptr) : (shift.values == nullptr)
    yolov5s: /home/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, 
    std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion 
    `scale_1' failed.
    Aborted (core dumped)

**Comment by wang-xinyu** [comment]
seems your `yolov5s.wts` not right.

how did you generate `yolov5s.wts`?

**Comment by makaveli10** [comment]
I used the README and created and environ using ultralytics/yolov5 requirements

**Comment by wang-xinyu** [comment]
My `yolov5s.wts`, the first lines are
```
320
model.0.conv.conv.weight 3456  3d2b6000 3d022000 3d7a0000 3c33......
model.0.conv.bn.weight 32  401e0000 3f50a000 4002c000
```
how about yours?

**Comment by makaveli10** [comment]
370
    model.0.conv.conv.weight 3456  bd074000 3cf26000 3d2bc000 ...
    model.0.conv.bn.weight 32  4016c000 3f93c000 3fd80000 3f1a4000 3f69c000 3f7b2000

Do you mind sharing your .wts file. I dont think this is platform specific

**Comment by wang-xinyu** [comment]
when did you download the yolov5s.pt?   can you try the latest model in ultralytics/yolov5 google drive ?

**Comment by makaveli10** [comment]
I downloaded like an hour ago I'll try again. I used there download.sh script to download the model

**Comment by wang-xinyu** [comment]
I downloaded from browser, this link https://drive.google.com/drive/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J

**Comment by makaveli10** [comment]
Yeah I just generated the weights again after downloading yolov5s.pt from the above link but I did not find any diff in the first two lines:

    370
    model.0.conv.conv.weight 3456  bd074000 3cf26000 3d2bc000 bbbac000 .....
    model.0.conv.bn.weight 32  4016c000 3f93c000 3fd80000 3f1a4000 3f69c000....

**Comment by wang-xinyu** [comment]
Yours has 370 weights, mine only 320.
what's your pytorch version.

**Comment by makaveli10** [comment]
1.5.1

**Comment by makaveli10** [comment]
What PyTorch version did you use to generate .wts?

**Comment by makaveli10** [comment]
I just now tried with torch==1.4.0 gives me the exact same result weight file with 370 weights

**Comment by wang-xinyu** [comment]
I just downloaded from above link, the yolov5s.pt 15.2MB

The one I used was downloaded on 21 June, which is 14.3MB!!!!

I will try the new one.

**Comment by makaveli10** [comment]
Yes please! Meanwhile can you share your current .wts file.

**Comment by ausk** [comment]
U yolov5 just update the model cofig file (xxx.yml).

**Comment by makaveli10** [comment]
@ausk @wang-xinyu so obviously there yolov5s.pt has also changed

**Comment by wang-xinyu** [comment]
@makaveli10 
 Sharing the .wts is meaningless, I can share the old yolov5s.pt.

https://drive.google.com/file/d/1gr1MnHdVi9_kG0XQJMShhkA1_rfoDA7z/view?usp=sharing

can you try it?

**Comment by makaveli10** [comment]
Okay! I will try with this

**Comment by ausk** [comment]
Old works, while the new failed, the md5:
Old: acef356c653b6b425837d58a9ad56744 
New:  010ef084e4abb8851013a7ac20905374

**Comment by f3rm4rf3r** [comment]
> @makaveli10
> Sharing the .wts is meaningless, I can share the old yolov5s.pt.
> 
> https://drive.google.com/file/d/1gr1MnHdVi9_kG0XQJMShhkA1_rfoDA7z/view?usp=sharing
> 
> can you try it?

Same issue here. I think the problem as @ausk is pointing is that the model changed since few days ago. Could you share the link with me too? @wang-xinyu 
Thanks!

**Comment by wang-xinyu** [comment]
The structure already updated. Using the new yolov5s structure.

please check the new commit
https://github.com/wang-xinyu/tensorrtx/commit/6fd39395ac6966f04ed58b1f4003e784193c3bdc

**Comment by f3rm4rf3r** [comment]
Thanks @wang-xinyu I just saw your commit. I will have a go and report.

**Comment by f3rm4rf3r** [comment]
> The structure already updated. Using the new yolov5s structure.
> 
> please check the new commit
> [6fd3939](https://github.com/wang-xinyu/tensorrtx/commit/6fd39395ac6966f04ed58b1f4003e784193c3bdc)

Seems to be running now!
```bash
root@7fa579fb4b92:/workspace/experiments/demo/removeme/tensorrtx/yolov5/build# ./yolov5s -s
Loading weights: ../yolov5s.wts
conv14 ----
conv18 ----
conv22 ----
Building engine, please wait for a while...
Build engine successfully!
foo@bar:/tensorrtx/yolov5/build# ./yolov5s -d ../samples/
[06/23/2020-13:29:58] [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
11ms
```
Inference image displays correct classes. 

How do you think we should stop this happening if the yolov5 author keeps updating the model? I guess caching the model somewhere is not legal due to copyright issue... Maybe we should add an MD5/SHA1 weigths checksum stage to the README file? (at least the people will know that the model couldn't not work since it could differ from [yolov5s.cpp](https://github.com/wang-xinyu/tensorrtx/blob/master/yolov5/yolov5s.cpp) current implementation.

Thank you anyway.

**Comment by wang-xinyu** [comment]
@f3rm4rf3r yes, you are right, I will update the README, and copy the yolov5s.pt in my google drive.

**Comment by makaveli10** [comment]
> @f3rm4rf3r yes, you are right, I will update the README, and copy the yolov5s.pt in my google drive.

@wang-xinyu yes right. They are updating the repo currently alot.

**Comment by f3rm4rf3r** [comment]
> @f3rm4rf3r yes, you are right, I will update the README, and copy the yolov5s.pt in my google drive.

@wang-xinyu I have seen your README update [here](https://github.com/wang-xinyu/tensorrtx/commit/0504551c0b7d0bac5f998eda349810ba410715de#diff-8e9f0b1f010e76f2167fca3a3c7ad274) however the google drive doesn't seem to be public (it is asking me to `request access`). Would you mind making that file public?

Thanks!

**Comment by wang-xinyu** [comment]
@f3rm4rf3r updated

**Comment by f3rm4rf3r** [comment]
I guess we should be able to close this issue, isn't it?
@wang-xinyu @makaveli10

**Comment by bulingda** [comment]
> Yours has 370 weights, mine only 320.
> what's your pytorch version.

@wang-xinyu 我对比了自己训练的模型导出的.wts文件里的weights和我在官网下载的可以正常运行的模型导出的.wts文件里的weights，都是658.并且使用机器将我的代码中的网络和2.0版本的网络进行了对比。除了类别之外，没有任何不同。请问您还有什么建议可以帮我修复这个bug吗？以下是我的错误提示信息：
Loading weights: ../yolov5l.wts
[09/15/2020-16:31:28] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5l: /usr/local/anaconda/yolov5_2.0-TensorRt-master/yolov5l/common.hpp:263: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::string, float): Assertion `scale_1' failed.
已放弃(吐核)

**Comment by wang-xinyu** [comment]
658是weights的总个数，应该是layer的名字不一样，需要对一下layer的名字，wts每一行的第一个字段

或者还是对pytorch的模型，两个模型print出来，对每个layer的名字

**Comment by bulingda** [comment]
> 658是weights的总个数，应该是layer的名字不一样，需要对一下layer的名字，wts每一行的第一个字段
> 
> 或者还是对pytorch的模型，两个模型print出来，对每个layer的名字
![1600226760(1)](https://user-images.githubusercontent.com/55130106/93288857-73d8b000-f80f-11ea-8f2a-40067f6d3dc1.png)
@wang-xinyu 我发现了两个模型的不同，但是在代码中还是没有找到区别在哪里，不知道该在哪里修改。请问这样该怎么办呢？

**Comment by wang-xinyu** [comment]
yolov5l.pt文件是包含模型结构信息的，不需要（common.py,experimental.py,yolo.py,yolov5l.yaml）

把模型加载进来，然后print model，看每层的定义。然后和c++代码的网络结构定义代码做比较。

**Comment by PareshKamble** [comment]
Dear @wang-xinyu,
While running `sudo ./yolov5s -s`, I am facing the same issue as above. 
I tried using **yolov5s.pt** from the drive link you gave above and also used code from the same commit 6fd3939.
But, the issue still persist.
Can you please suggest a solution for the same?

I am working with:
Ubuntu 18.04
CUDA 10.2
cuDNN 7.6.5
python 3.6
pytorch 1.7.1

The complete error is:
```
[E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5s: /home/DeepStream/tensorrtx/yolov5/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted (core dumped)
```

Can you please help me sort out this issue?
Thanking you in anticipation!
