### ISSUE TITLE
yolov5，make failed，help help help

### ISSUE THREAD

**Issue by Dream-decade** [wang-xinyu/tensorrtx#594]
[ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
/home/excellence/cpc/tensorrtx-master/yolov5/calibrator.cpp:4:10: fatal error: opencv2/dnn/dnn.hpp: No such file or directory
 #include <opencv2/dnn/dnn.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/yolov5.dir/build.make:62: recipe for target 'CMakeFiles/yolov5.dir/calibrator.cpp.o' failed
make[2]: *** [CMakeFiles/yolov5.dir/calibrator.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
your opencv does not have dnn module, you need to use opencv3.3+ with dnn module

**Comment by Dream-decade** [comment]
> your opencv does not have dnn module, you need to use opencv3.3+ with dnn module

Thanks. Is it opencv-python? Its version is 4.5, but it still reports an error

**Comment by wang-xinyu** [comment]
libopencv, cpp

**Comment by Dream-decade** [comment]
> libopencv, cpp

Sorry, I'm a beginner.I didn't understand. Could you tell me in detail what I should do?Thanks

**Comment by wang-xinyu** [comment]
You can install opencv using apt-get, which you can refer to https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/install.md.

Or build opencv from source, need to find a build tutorial online.

**Comment by Dreamdecade** [comment]
yeap，i get it，thanks

**Comment by Dream-decade** [comment]
yeap，i get it，thanks
