### ISSUE TITLE
yolov5s int8GPU利用率非常高99%，一个模型把gpu算力吃光了

### ISSUE THREAD

**Issue by Pudge-tao** [wang-xinyu/tensorrtx#595]
## Env

- GPU, e.g. tesla T4
- OS, e.g. centos7
- Cuda 10.2
- TensorRT 7.1.3.4

## About this repo
yolov5s

## Your problem
量化后的yolov5s int8模型gpu占用率非常高
![屏幕截图 2021-06-16 104515](https://user-images.githubusercontent.com/49672927/122150286-fa4e1b00-ce8f-11eb-8f4a-7cc2fae65486.jpg)

**Comment by wang-xinyu** [comment]
应该在1000MB以内，可能是环境里其他程序导致的

**Comment by Pudge-tao** [comment]
> 应该在1000MB以内，可能是环境里其他程序导致的

我在自己的程序中加载了yolov5s.engine，还有其他的显存申请，所以显存占用比较大，问题是GPU compute基本用满了

**Comment by wang-xinyu** [comment]
compute用满了很正常，不要高估T4的能力。。可以整理整理问题去nv论坛问问

**Comment by Pudge-tao** [comment]
> compute用满了很正常，不要高估T4的能力。。可以整理整理问题去nv论坛问问

好的，我去nv看看吧
