### ISSUE TITLE
Support for TensorRT v8

### ISSUE THREAD

**Issue by priteshgohil** [wang-xinyu/tensorrtx#597]
## Env

- OS: Ubuntu16.04, Win10, etc.
- Cuda: 11.3
- TensorRT: v8

## About this repo

- latest master branch
- yolov5

## Your problem

- what is your command? - make
- what's your output? - Error exactly similar to  #258

**Comment by wang-xinyu** [comment]
refer to https://github.com/wang-xinyu/tensorrtx/pull/540

**Comment by priteshgohil** [comment]
Thanks
