### ISSUE TITLE
使用yolov5 v4版本的x l 模型，使用训练好的模型，python预测，效果挺好，但是转换engine后,使用tensorrt推理，检测目标丢失很严重

### ISSUE THREAD

**Issue by xinsuinizhuan** [wang-xinyu/tensorrtx#598]
这是python预测：
![图片](https://user-images.githubusercontent.com/40679769/122702576-45966e00-d282-11eb-8270-ffd71013aee6.png)
则是16位模式转换后，tensorrt预测：
![图片](https://user-images.githubusercontent.com/40679769/122702606-56df7a80-d282-11eb-82e5-488ba1d25078.png)
这是32位模式转换后，tensorrt预测：
![_3](https://user-images.githubusercontent.com/40679769/122702816-c9505a80-d282-11eb-9398-16e2f67fa512.jpg)
x模型和l模型都是试过，都一样，怎么排查和解决？

**Comment by wang-xinyu** [comment]
try official models first, then go to your own models.

**Comment by xinsuinizhuan** [comment]
官方的x模型，未修改任何，只修改了输入尺寸变为了1536*1536和我的类别2，我这个是识别小目标，官网的都是大目标，官方的跑过，大目标正常。

**Comment by kundebuxing** [comment]
你的训练图片尺寸是多少

**Comment by xinsuinizhuan** [comment]
> 
> 
> 你的训练图片尺寸是多少

训练尺寸，我试过2种：
1、224*224的小图，模型输入为640*640，即为我把224的小图，resize到640，进行模型输入。
2、1536*1536的大图，模型输入也是1536*1536.

都是这种现象。
