### ISSUE TITLE
Building rcnn CUDA 11

### ISSUE THREAD

**Issue by Dorozhko-Anton** [wang-xinyu/tensorrtx#599]
## Env

GeForce RTX 3070
Ubuntu  20.04
CUDA 11.2
TensorRT 7.2.2

Docker basic image: nvcr.io/nvidia/tritonserver:21.03-py3

## About this repo

- which branch/tag/commit are you using?  `Master`
- which model? yolov5, retinaface?    `Rcnn`

## Your problem

I had to modify c++11 to c++14 in CmakeLists.txt then

when I try to build rcnn 
```
cd rcnn
mkdir build
cmake ..
make
```
I have 
```
thrust/system/cuda/detail/cub/device/device_radix_sort.h not found
```

How should I proceed to build rcnn for CUDA 11 ?

**Comment by freedenS** [comment]
see #521

**Comment by Dorozhko-Anton** [comment]
Modifications to the code and cmake are described in #521
