### ISSUE TITLE
Not much change in FPS

### ISSUE THREAD

**Issue by athus1990** [wang-xinyu/tensorrtx#6]
Hello!
Thank you for the wonderful work! I would like to contribute to this project.
I noticed something strange on the yolov3-spp.cfg . I used the original pytorch repo to train and model. In normal python inference time I am getting ~33FPS on a 512x512 image.
So I used you repo to convert the weights and run using tenosrRT. However the FPS is still pretty much the same.
1. Isnt' tensorrt supposed to boost the inference time? 
2. Secondly , Maybe I need to convert the precision to FP16 before inferencing. How should I do that?

**Comment by wang-xinyu** [comment]
@athus1990 thanks for your interest!   

Did you change the Input shape in yololayer.h to 512x512?

And for FP16, set this macro will be FP16,   while comment out it will be FP32.

https://github.com/wang-xinyu/tensorrtx/blob/f92af02afd5530163c65af9c435cebc3bd3a3ab2/yolov3-spp/yolov3-spp.cpp#L16

**Comment by wang-xinyu** [comment]
BTW, what GPU you are using? Some old GPU not support FP16.

**Comment by athus1990** [comment]
Hi @wang-xinyu ,
Thanks for the quick reply. Yes I changed that over there changed the filter sizes as well as I had custom classes.(num_classes+5)*3 in all yolo layers.
I also have lesser classes than yours (80 vs 10 (mine)).

I am using  Quadro RTX 6000. Ill try running on FP16 to check if it becomes faster.

**Comment by athus1990** [comment]
To Give you an idea , this is the output of the original yolov3 repo( ultralytics/yolov3.)..Inferencing on a 512x512 video/Image.

![remmina_GPUSERV_50 243 163 70_2020421-14728 377445](https://user-images.githubusercontent.com/7275643/79816631-b1fda080-8351-11ea-9a33-17ba05378f41.png)


This are the ternsorrtx outputs (only showing ms). The detections are properly working! But just the FPS is slow.

![remmina_GPUSERV_50 243 163 70_2020421-1481 970157](https://user-images.githubusercontent.com/7275643/79816691-d0639c00-8351-11ea-8332-ec8dee527a1e.png)

**Comment by wang-xinyu** [comment]
@athus1990

**Comment by wang-xinyu** [comment]
@athus1990 

1.  the input shape in yololayer.h, is that 320x512 or 512x512,  you can try 320x512.

2. It includes NMS time in .cpp,   does it includes NMS time in python, or just model forward time?

**Comment by athus1990** [comment]
Yes. The original python repo does include the nms time while printing the inference time(0.028s)..

**Comment by wang-xinyu** [comment]
I modify the input shape to 320x512, and got following latency on GTX1080.

<img width="807" alt="WX20200421-103056@2x" src="https://user-images.githubusercontent.com/15235574/79818801-39cbc500-83bb-11ea-8c20-5139cd951b5f.png">

Are you also including image preprocessing time?

**Comment by wang-xinyu** [comment]
And are you using the latest commit of this repo?

**Comment by athus1990** [comment]
Yes I was including image processing time. I am sorry.
Closing the issue.
