### ISSUE TITLE
yolov4无法加速

### ISSUE THREAD

**Issue by xgyyao** [wang-xinyu/tensorrtx#60]
大佬你好，我在使用./yolov4 -s 后报
[W] [TRT] Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
但模型仍可生成

在使用./yolov4 -d  ../../yolov3-spp/samples后报
[W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
测试的五张图片推理速度分别为：
91ms
51ms
63ms
59ms
74ms
我的环境为：cuda 10.0 ubuntu18.04 显卡1080ti

**Comment by wang-xinyu** [comment]
inputsize  和  batchsize是多少

**Comment by xgyyao** [comment]
inputsize是默认的608x608，batchsize是1。同样的代码和图片我在2080ti上测试平均每张大概13ms。

**Comment by wang-xinyu** [comment]
测延时的位置，有修改吗？
我的1080，大概28ms

**Comment by xgyyao** [comment]
查了下确实是之前测延时的地方修改了，多谢了！测下来平均一张25ms
