### ISSUE TITLE
Parameter check failed at: Network.cpp::nvinfer1::Network::addResize::930, condition: input.getDimensions().nbDims > 0

### ISSUE THREAD

**Issue by lunkyguy** [wang-xinyu/tensorrtx#601]
## Env

- GPU, RTX2060.
- OS, Win10.
- Cuda version 11.1
- TensorRT version TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.1.cudnn8.1

## About this repo

- which branch master
- which model? yolov5

## Your problem

- what is your command?  .\yolov5.exe -s .\yolov5x.wts yolov5x.engine s
- what's your output? [E] [TRT] Parameter check failed at: Network.cpp::nvinfer1::Network::addResize::930, condition: input.getDimensions().nbDims > 0
- what output do you expect?

**Comment by wang-xinyu** [comment]
If using yolov5-x, the last argument should be `x` not `s`.
