### ISSUE TITLE
arcface-r100算出的特征值不准

### ISSUE THREAD

**Issue by sang16898** [wang-xinyu/tensorrtx#604]
集成完代码，由于无法下载joey0.ppm,joey1.ppm这两个文件。使用https://convertio.co/，把jpg图片转换为ppm格式图片。但是不相似的图片比对得分很高，相似的得分也不低，给出的得分完全是混乱的。

**Comment by wang-xinyu** [comment]
@ybw108 could you take a look?  linking to https://github.com/wang-xinyu/tensorrtx/pull/545

**Comment by irvingzhang0512** [comment]
建议定量对比 #559

**Comment by ybw108** [comment]
我这边测试了一下，对于同一张图片，tensorrt版本的模型输出结果和mxnet版本[LResNet100E-IR,ArcFace@ms1m-refine-v2](https://github.com/deepinsight/insightface/wiki/Model-Zoo#31-lresnet100e-irarcfacems1m-refine-v2)基本一致：

    mxnet
   -0.08242133，-0.16276829，-0.19908786，0.1327742，0.07386892，0.20920953，0.07552349，0.09261446，-0.05126235，-0.25519624
    tensorrt
    -0.0824215，-0.162768，-0.199088，0.132774，0.0738688，0.20921，0.0755237，0.092614，-0.0512628，-0.255196

说明mxnet→tensorrt engine的过程应该没有出现问题，建议再检查一下你的输入图片还有推理代码，或者用mxnet版本的模型跑一下出现问题的图片，看看得出的相似度是否正常，大致确定一下可能出现问题的位置。

**Comment by wang-xinyu** [comment]
closing it.
