### ISSUE TITLE
Yolov5 problem with batched NMS, post-processing whole batch together gives a lot extra bounding boxes on moving objects

### ISSUE THREAD

**Issue by timothylimyl** [wang-xinyu/tensorrtx#605]
Hi there,

I was wondering whether has anyone tried batch NMS on the post-processing step for YoloV5? To do so, you will need to delete the variable `num_boxes` that is given:

```My Code

    n_idx = list(range(0,self.batch_size*6001,6001)) #index of num_boxes
    output = np.array(output)
    mask = np.ones_like(output,dtype=bool)
    mask[n_idx] = False
    output = output[mask] # delete away num_boxes

    pred = np.reshape(output, (-1, 6)) 

```

Then the variable `pred` will be in shape [self.batch_size*1000 , 6].  Then it is basically the same steps as given by the author but just using the `torchvision.ops.batched_nms` instead.  The image category ids can be set up as such:

```
        #get category split (THIS CAN BE A MACRO, it is constant according to MAX_BBOX_COUNT in yololayer):
        idxs = torch.arange(9, device=boxes.device)
        idxs = idxs[:, None].expand(9, 1000).flatten()

       .
       . 
       .

        indices = torchvision.ops.batched_nms(boxes, scores, idxs, iou_threshold=IOU_THRESHOLD)

```

However, the resulting bounding boxes always have problems for cases when the objects are moving in the video stream. It works fine when the objects are static.... this really puzzles me. In motion, the bounding boxes accumulate on the past frames. I can confirm this is not an inference speed issue as I have tried basically 0.1FPS and see the bounding boxes still accumulates to the next frame on some occasion (100% during movement and never when objects are static in video stream)

**Comment by wang-xinyu** [comment]
It is totally unnecessary to use nms plugin,  as the output num of bboxes is very small, only couple of hundreds, so nms is fast enough.

**Comment by timothylimyl** [comment]
Thanks for the reply.

Yeah, but the output num of bboxes grows as your batch grows. Also, I am keeping everything in GPU as I am doing some further post-processing that is much faster if I keep it on GPU all the way through.
