### ISSUE TITLE
The segmentation effect seems to not good after using tensorrt, why?

### ISSUE THREAD

**Issue by snowyseaons** [wang-xinyu/tensorrtx#607]
I tried hrnet and the inference is faster now, 40ms per image. But there are so many spots detected, which makes the result not ideal. However the result of inference without tensorrt is really good. I have to cut the image with multi pieces, the effect is much better but the inference speed is far slower. How can I deal this?

**Comment by wang-xinyu** [comment]
pls follow the issue template to re-describe your issue.

**Comment by snowyseaons** [comment]
The model I used is hrnet. https://github.com/HRNet/HRNet-Semantic-Segmentation

Inference without trt, the result is like this.
![IMG_20210703_000524](https://user-images.githubusercontent.com/43413834/124301490-89606180-db25-11eb-977e-380f310155e9.jpg)
Inference with trtx, the result is like this. https://github.com/wang-xinyu/tensorrtx/tree/master/hrnet/hrnet-semantic-segmentation

![IMG_20210703_000554](https://user-images.githubusercontent.com/43413834/124301504-8d8c7f00-db25-11eb-8f88-e643fa983e79.jpg)
There are many unnecessary spots which marked with purple lines. Sorry, I have no enough examples now. That's about it.  If necessary, I'll find more images next Mondy.

**Comment by snowyseaons** [comment]
The model I used is hrnet. https://github.com/HRNet/HRNet-Semantic-Segmentation

Inference without trt, the result is like this.
![IMG_20210703_002508](https://user-images.githubusercontent.com/43413834/124303851-8d41b300-db28-11eb-84c2-bb255047cde0.jpg)

Inference with trtx, the result is like this. https://github.com/wang-xinyu/tensorrtx/tree/master/hrnet/hrnet-semantic-segmentation
![IMG_20210703_000554](https://user-images.githubusercontent.com/43413834/124303888-992d7500-db28-11eb-9fc9-6e23fc34f900.jpg)
There are many unnecessary spots which marked with purple lines. 
Sorry, I have no enough examples now. That's about it. If necessary, I'll find more images next Mondy.

**Comment by wang-xinyu** [comment]
@upczww can you take a look?

**Comment by upczww** [comment]
Change all "upsample" op in source code to mode='bilinear', align_corners=True
