### ISSUE TITLE
同一个模型在不同显卡上消耗显存不同

### ISSUE THREAD

**Issue by pengfeidip** [wang-xinyu/tensorrtx#609]
## Env

- **GPU,** 060  2070  3060
- **OS**, Win10 
- **Cuda version** 11.1
- **TensorRT version**  7.2.34

## About this repo

- which model? yolov5s v3.0

## Your problem

同一个模型(yolov5s， 608×320) ，同版本TensorRT 以及 win10。  1060系列卡上消耗350M显存，2070显卡上消耗接近700M显存，3060消耗接近一个G。有人知道为什么吗..

我猜测是和显卡架构有关的

**Comment by wang-xinyu** [comment]
和显卡有关系，所以tensorrt模型在不同显卡之间是不通用的

**Comment by pengfeidip** [comment]
> 和显卡有关系，所以tensorrt模型在不同显卡之间是不通用的

好吧，只能这样了
