### ISSUE TITLE
预处理时默认为等比例缩放，直接resize时预处理问题

### ISSUE THREAD

**Issue by huaze555** [wang-xinyu/tensorrtx#61]
作者你好，非常感谢开源这么优秀的代码。我在使用时有个问题，请帮忙解决下～

我用darknet训练时，选择的是将原图直接resize到608*608.  所以当用你的代码做inference时，会出错框的不准等问题，因为你的代码预处理部分是选择等比例缩放再加灰边的形式。能不能提供一份预处理是直接resize的代码段呢，这样才能正确地解析yolo的输出。非常感谢！

**Comment by wang-xinyu** [comment]
这里是letterbox的方式，   直接resize这个自己改吧，，，

**Comment by huaze555** [comment]
@qiuyunzhe ok，已解决
