### ISSUE TITLE
请问一下推理的数据路径在哪？

### ISSUE THREAD

**Issue by amirxu** [wang-xinyu/tensorrtx#610]
## Env

- GPU, Xavier NX
- OS, Ubuntu16.04
- Cuda 10.2

## Your problem
您好，我遇到这个问题，resnet、mobilenet等模型转为engine文件后，如何推理自己的图片？
`sudo ./vgg -d`运行这个命令后自动推理了，我并不知道也找不到他推理的数据在哪，如何推理自己指定的数据？希望您能指导一下，谢谢啦！

**Comment by wang-xinyu** [comment]
For a simple image inferencing, you can check https://github.com/wang-xinyu/tensorrtx/blob/master/arcface/arcface-r50.cpp#L373.

Basically, it needs to read image, resize, convert to float and normalize, etc.
