### ISSUE TITLE
what happens....

### ISSUE THREAD

**Issue by woshichunge12** [wang-xinyu/tensorrtx#613]
40%] Built target myplugins
[ 60%] Building CXX object CMakeFiles/yolov5.dir/calibrator.cpp.o
[ 80%] Building CXX object CMakeFiles/yolov5.dir/yolov5.cpp.o
[100%] Linking CXX executable yolov5
CMakeFiles/yolov5.dir/calibrator.cpp.o：在函数‘Int8EntropyCalibrator2::getBatch(void**, char const**, int)’中：
/home/guchengchun/tensorrtx/yolov5/calibrator.cpp:52：对‘cv::dnn::experimental_dnn_v4::blobFromImages(cv::_InputArray const&, double, cv::Size_<int>, cv::Scalar_<double> const&, bool, bool)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5.dir/build.make:163: recipe for target 'yolov5' failed
make[2]: *** [yolov5] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**please help,thanks a lot...**

**Comment by wang-xinyu** [comment]
your opencv does not have dnn module.
