### ISSUE TITLE
arcface sample program - changing floating type casting makes similarity score increase

### ISSUE THREAD

**Issue by tri-bao** [wang-xinyu/tensorrtx#614]
hi
I tried to run arcface-r100.cpp on jetson nano. I noticed that, if changing lines 404-406 and 421-423

from 

```cpp
        data[i] = ((float)img.at<cv::Vec3b>(i)[2] - 127.5) * 0.0078125;
        data[i + INPUT_H * INPUT_W] = ((float)img.at<cv::Vec3b>(i)[1] - 127.5) * 0.0078125;
        data[i + 2 * INPUT_H * INPUT_W] = ((float)img.at<cv::Vec3b>(i)[0] - 127.5) * 0.0078125;
```

to

```cpp
        data[i] = (float)img.at<cv::Vec3b>(i)[2] - 127.5f * 0.0078125f;
        data[i + INPUT_H * INPUT_W] = (float)img.at<cv::Vec3b>(i)[1] - 127.5f * 0.0078125f;
        data[i + 2 * INPUT_H * INPUT_W] = (float)img.at<cv::Vec3b>(i)[0] - 127.5f * 0.0078125f;
```
The similarity score between `joey0.ppm` and `joey1.ppm` increased from `0.631183` to `0.881155`

Anybody has any idea?

**Comment by ybw108** [comment]
I run inference part of arcface-r100.cpp on NVIDIA RTX 2080ti.

        data[i] = ((float)img.at<cv::Vec3b>(i)[2] - 127.5) * 0.0078125;
        data[i + INPUT_H * INPUT_W] = ((float)img.at<cv::Vec3b>(i)[1] - 127.5) * 0.0078125;
        data[i + 2 * INPUT_H * INPUT_W] = ((float)img.at<cv::Vec3b>(i)[0] - 127.5) * 0.0078125;
similarity: 0.632514

        data[i] = ((float)img.at<cv::Vec3b>(i)[2] - 127.5f) * 0.0078125f;
        data[i + INPUT_H * INPUT_W] = ((float)img.at<cv::Vec3b>(i)[1] - 127.5f) * 0.0078125f;
        data[i + 2 * INPUT_H * INPUT_W] = ((float)img.at<cv::Vec3b>(i)[0] - 127.5f) * 0.0078125f;
similarity:  0.632514

        data[i] = (float)img.at<cv::Vec3b>(i)[2] - 127.5f * 0.0078125f;
        data[i + INPUT_H * INPUT_W] = (float)img.at<cv::Vec3b>(i)[1] - 127.5f * 0.0078125f;
        data[i + 2 * INPUT_H * INPUT_W] = (float)img.at<cv::Vec3b>(i)[0] - 127.5f * 0.0078125f;
similarity: 0.881857
It seems changing floating type didn't cause similarity score increase. You lose a parentheses between `(float)...` and `...127.5`, and this is the reason of result difference.

**Comment by tri-bao** [comment]
I see it. Thanks
