### ISSUE TITLE
RetinaFaceAntiCov的cov2.zip模型从哪里下载

### ISSUE THREAD

**Issue by sang16898** [wang-xinyu/tensorrtx#615]
https://github.com/deepinsight/insightface/tree/master/RetinaFaceAntiCov已经无法打开，不知道cov2.zip从哪里下载

**Comment by wang-xinyu** [comment]
https://github.com/deepinsight/insightface/tree/master/detection/retinaface_anticov

Their dir changed.

**Comment by wang-xinyu** [comment]
closing it
