### ISSUE TITLE
在jetson nano 运行， 没有改动代码。测试的时间为什么很慢呢？是不是需要更加jetson nano 改一下参数在运行？

### ISSUE THREAD

**Issue by ahhhxxx** [wang-xinyu/tensorrtx#617]
在jetson nano 运行， 没有改动代码。
结果 两张图片分别是334ms，132ms。
sudo ./yolov5 -d yolov5s.engine ../sample、s
334ms
132ms
测试的时间为什么很慢呢？是不是需要更加jetson nano 改一下参数在运行？

**Comment by wang-xinyu** [comment]
试下更多图片，可能还在预热
