### ISSUE TITLE
How to combine detection results(yolov5-v5) and sort/deepsort?

### ISSUE THREAD

**Issue by kundebuxing** [wang-xinyu/tensorrtx#624]
I've got great results from tensorrt-yolov5.
Can you give me some tips about combining detection with tracking? Thanks!

**Comment by wang-xinyu** [comment]
Afaik, sort is not using DL model, so you can use opencv to implement it. For deepsort, there is a simple feature model, which can be accelerated by using trt.
But we do not have them in this repo currently, you can check other repos on github.

**Comment by kundebuxing** [comment]
> Afaik, sort is not using DL model, so you can use opencv to implement it. For deepsort, there is a simple feature model, which can be accelerated by using trt.
> But we do not have them in this repo currently, you can check other repos on github.

thanks for your reply :)
so after accelerate deepsort and I‘ve got deepsort.engine, can i use deepsort.engine and yolov5s.engine at the same time？

**Comment by wang-xinyu** [comment]
Yes, it is possible to use two trt engine at the same time.

**Comment by kundebuxing** [comment]
> Yes, it is possible to use two trt engine at the same time.

thanks for your kindly help~ I will try that

**Comment by axxx-xxxa** [comment]
> > Yes, it is possible to use two trt engine at the same time.
> 
> thanks for your kindly help~ I will try that

请问流程跑通了么有呀
