### ISSUE TITLE
USE_FP16 didnt work

### ISSUE THREAD

**Issue by KhubbatulinMark** [wang-xinyu/tensorrtx#625]
## Env

- GPU, e.g. T4
- OS, e.g. Ubuntu18.04
- Cuda version  11.3
- TensorRT version 7.2.3

## About this repo
- I use https://github.com/ultralytics/yolov5 yolov5m6 model

## Your problem

- The model translates to FP32, but if you convert FP16. It is still in FP32. 
- I forcibly changed the flag in the file yolov5.cpp.  config.set_flag(trt.BuilderFlag.FP16) -> config.set_flag(trt.BuilderFlag.STRICT_TYPES).  The model is converted, but still shows that it is in FP32.
- What am I doing wrong? Or is engine.get_binding_dtype not an indicator of model translation to FP16?

![image](https://user-images.githubusercontent.com/40608788/125286310-58054400-e324-11eb-9cb6-998a0ba85957.png)

**Comment by wang-xinyu** [comment]
For trt fp16, it is using fp32 weights to build the model. So you do not need to convert weights to fp16 in pytorch.

And also, trt will convert network output value from fp16 to fp32 automatically for you.

**Comment by KhubbatulinMark** [comment]
I'm sorry, you must have misunderstood me. The model does not convert to FP16.  I select FP16 in yolov5.cpp. But engine still FP32.

**Comment by wang-xinyu** [comment]
How did you know it is fp32?

**Comment by KhubbatulinMark** [comment]
I load engine and get engine.get_binding_dtype param get output and input in float 32. And I convert with FP32 flag. Inference was same

**Comment by wang-xinyu** [comment]
Did you compare inference latency and engine file size?

As I said, trt will convert network output value from fp16 to fp32 automatically for you. So the input and output tensor are FP32, but the model inside are using fp16.

**Comment by KhubbatulinMark** [comment]
Now I looked at both the time and the size. they are indeed different.   Batch size 10, 1280x1280 FP16 200ms, FP21 620ms.  But the buffer size is still FP32(.  Is it possible to change the buffer to FP16?  I would like to save memory.

**Comment by wang-xinyu** [comment]
No idea. I never tried that.
