### ISSUE TITLE
BATCH_SIZE=8 inference not much faster than 8 runs at BATCH_SIZE = 1

### ISSUE THREAD

**Issue by Transigent** [wang-xinyu/tensorrtx#627]
## Env

- GPU  **RTX3070 and Quadro K620**
- OS, **Windows 10 Pro 21H1**
- Cuda version  **cuda_11.1.1_456.81 and cudnn-11.2-windows-x64-v8.1.1.33**
- TensorRT version  **7.2.3.4**

## About this repo

- which branch/tag/commit are you using?    **Master**
- which model?  **yolov5-v4.0**

## Your problem

I have had success using the sample code with BATCH_SIZE set to the default (1), on an RTX3070 I have consistently been getting 17ms inference time (compute capability 8.6, 5888 CUDA cores ) and on a Quadro K620 (compute capability 5.0,  384 CUDA cores) I am getting around 199ms. This is pretty impressive.

I did some reading about TensorRT and according to the documentation "A batch of inputs identical in shape and size can be computed on different layers of the neural network in parallel", which suggests that a batch might take a similar time as a single inference if inference in the GPU is done in parallel. 

I tested this by setting BATCH_SIZE = 8. I regenerated the engine file and ran again. But in this case inference was taking 100ms for the RTX3070 and 1447ms for the K620. 

Is this result expected? The K620 takes nearly the same time to do one BATCH_SIZE=8 as doing 8 separate BATCH_SIZE=1 inference runs, while the RTX3070 took about 6 times longer as long to do a batch of 8.

Is there any way to optimize this? Thanks for the great library.

**Comment by wang-xinyu** [comment]
This is normal, I got similar results on batchsize>1. Maybe u can try tensorrt samples and check with nvidia.

**Comment by Transigent** [comment]
Thanks for the feedback. I'll see what I can find out.

**Comment by watertianyi** [comment]
> 谢谢您的反馈。我会看看能找到什么。
@wang-xinyu @Transigent 
Hello, have you solved the batchsize problem mentioned above? The author said to find it in the tensorrt example. You can refer to that example.
