### ISSUE TITLE
请问yolov5转int8，需要自己准备calib.table吗

### ISSUE THREAD

**Issue by William-Jianyuan** [wang-xinyu/tensorrtx#628]

**Comment by wang-xinyu** [comment]
calib.table是自己生成的，参考readme中int8部分进行操作

**Comment by Lenan22** [comment]
Please refer to our open source quantization tool ppq, the quantization result is better than the quantization tool that comes with tensorrt, almost the same as the float32 model. https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md
