### ISSUE TITLE
使用引擎进行推理的时候报错

### ISSUE THREAD

**Issue by kekekahuatian** [wang-xinyu/tensorrtx#629]
## Env

- GPU 980ti
- OS, Win10, etc.
- Cuda 10.2，cudnn7.6
- TensorRT 7.0.0.11

## About this repo

- 使用的是master分支
- yolov5s.pt

## Your problem

- 使用`yolov5.exe -s yolov5s.wts yolov5s.engine s`可以正常输出engine 
![image](https://user-images.githubusercontent.com/44888861/125736096-1c655c0b-12f1-4e41-a789-4727522514cf.png)
- 接下来使用生成的engine文件进行推理时会报错`yolov5.exe -d yolov5s.engine  D:\foodData\Images`
![image](https://user-images.githubusercontent.com/44888861/125736202-39f4f0d5-c8f1-40ad-801c-407347124d05.png)
- 使用我自己训练的模型也是一样修改了检测类别等参数后可以正常生成engine文件，但是也会在推理时报错。

**Comment by wang-xinyu** [comment]
-d的时候不应该出现loading weights，你改了代码？

**Comment by kekekahuatian** [comment]
> -d的时候不应该出现loading weights，你改了代码？

 没有呀

**Comment by wang-xinyu** [comment]
不可能，，，，D:/vsProject/yolov5/yolov5s.wts怎么来的

**Comment by kekekahuatian** [comment]
![image](https://user-images.githubusercontent.com/44888861/125740626-ca6b63eb-ff6a-4220-977e-d79121cd44c8.png)
会不会是因为我在`main()`里面把wts的路径写死了（捂脸）

**Comment by wang-xinyu** [comment]
恢复代码重试一下

**Comment by kekekahuatian** [comment]
还真是因为我在main里面吧路径写死了，万分感谢

**Comment by wang-xinyu** [comment]
closing it
