### ISSUE TITLE
Assertion `scale_1' failed.

### ISSUE THREAD

**Issue by lzhhh6161** [wang-xinyu/tensorrtx#631]
## Env

- Ubuntu18.04.
- Cuda 10.2
- TensorRT 7.0

## About this repo
YOLOV5

## Your problem
- what is your command? e.g. `sudo ./yolov5 -s`
 sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
- what's your output?
[07/18/2021-11:01:32] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/lzh/公共的/tensorrtx/tensorrtx-master/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.

**Comment by wang-xinyu** [comment]
check this out https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5
