### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

### ISSUE THREAD

**Issue by lzhhh6161** [wang-xinyu/tensorrtx#632]
## Env

Ubuntu18.04。
CUDA 10.2
TensorRT 7.0

## About this repo

YOLOV5

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
 python yolov5_trt.py
- what's your output?
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +150, GPU +0, now: CPU 214, GPU 494 (MiB)
[TensorRT] INFO: Loaded engine size: 35 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 250 MiB, GPU 494 MiB
[TensorRT] ERROR: 1: [stdArchiveReader.cpp::StdArchiveReader::34] Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 89)
[TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::76] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "yolov5_trt.py", line 373, in <module>
    yolov5_wrapper = YoLov5TRT(engine_file_path)
  File "yolov5_trt.py", line 88, in __init__
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.

**Comment by wang-xinyu** [comment]
.Version tag does not match. Note: Current Version: 43, Serialized Engine Version: 89


which means you were running `yolov5 -s` and `python yolov5_trt.py` under different versions of Tensorrt or CUDA or GPU.

**Comment by TAOSHss** [comment]
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (259) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
