### ISSUE TITLE
How to define a shared weight layer?

### ISSUE THREAD

**Issue by ahangchen** [wang-xinyu/tensorrtx#633]
## Env

- GPU, Xavier NX, etc.
- OS, Ubuntu18.04, etc.
- Cuda 10.2
- TensorRT 7.1.3

## About this repo

- master
- custom model

## Your problem

- Problem: I want to define a model in tensorRT cpp api. The torch model defined like this:

```python
class SharedWeightModel(nn.Module):
    def __init__(self):
        super(SharedWeightModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 1, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(1, 1, kernel_size=3, padding=1)

    def forward(self, img1, img2):
        feature1 = self.conv1(img1)
        feature2 = self.conv1(img2)
        y = feature1 - feature2
        for i in range(5):
            y = self.conv2(y)
        return y
```
There are two problems:
-  Notice that conv1 is used twice to extract features for img1 and img2. Is there any way to share the weights of conv1 for these two extraction? Do we need to define addConvolution twice? Will this occupies double memory of the weights of conv1? 
- There is a loop containing conv2. If we can not share the weights of conv2, we need to define addconvolution five times. I search the document and find there is an [addLoop](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#define-loops) function, but it seems that convolution is not supported in loop. Any ideas?

**Comment by wang-xinyu** [comment]
Did u go through the getting started tutorial?

**Comment by wang-xinyu** [comment]
You can do it like this. `conv1.weight` and `conv1.bias` can be reused.
```
   IConvolutionLayer* feature1 = network->addConvolutionNd(*data1, 6, DimsHW{5, 5}, weightMap["conv1.weight"], weightMap["conv1.bias"]);

   IConvolutionLayer* feature2 = network->addConvolutionNd(*data2, 6, DimsHW{5, 5}, weightMap["conv1.weight"], weightMap["conv1.bias"]);
```

You can also use loop while defining layers.

**Comment by ahangchen** [comment]
Thank you for your reply.  I will try it out.
