### ISSUE TITLE
error when convering yolov3

### ISSUE THREAD

**Issue by jadeblank** [wang-xinyu/tensorrtx#634]
when runing sudo ./yolov3 -s

got

Loading weights: ../yolov3.wts
[01/05/2021-18:53:08] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov3: /media/nvidia/disk11/tensorrtx/yolov3/yolov3.cpp:170: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted

**Comment by wang-xinyu** [comment]
.wts is not right. You need follow the readme carefully.

And pls use issue template.
