### ISSUE TITLE
dbnet make failed , help!

### ISSUE THREAD

**Issue by praymich** [wang-xinyu/tensorrtx#635]
## Env
- aarch64 system
- Cuda 10
- TensorRT 5

## About this repo

- build dbnet

## Your problem

- error happened when i use ''build''
- In file included from /home/nvidia/tensorRT_test/tensorrtx-master/dbnet/dbnet.cpp:4:0:
/home/nvidia/tensorRT_test/tensorrtx-master/dbnet/logging.h:20:10: fatal error: NvInferRuntimeCommon.h: No such file or directory
 #include "NvInferRuntimeCommon.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/dbnet.dir/build.make:62: recipe for target 'CMakeFiles/dbnet.dir/dbnet.cpp.o' failed
make[2]: *** [CMakeFiles/dbnet.dir/dbnet.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dbnet.dir/all' failed
make[1]: *** [CMakeFiles/dbnet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
nvidia@nvidia-desktop:~/tensorRT_test/tensorrtx-master/dbnet/build$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sun_Sep_30_21:09:22_CDT_2018
Cuda compilation tools, release 10.0, V10.0.166
nvidia@nvidia-desktop:~/tensorRT_test/tensorrtx-master/dbnet/build$ nvidia
-bash: nvidia: command not found
nvidia@nvidia-desktop:~/tensorRT_test/tensorrtx-master/dbnet/build$

**Comment by wang-xinyu** [comment]
trt 5 is not supported.

**Comment by praymich** [comment]
thanks , is that work on docker? i use TX2 device and its tensorRT version is 5.
moreover,could u consider more new text recognizion model , such as deeptext or crnn(transformer).

**Comment by wang-xinyu** [comment]
Docker is also with trt 7.   For trt 5, you can check `trt4` branch of this repo, but I think dbnet is not in that branch.

For new models, you can implement it by using same methods as this repo. And we welcome your PR.

**Comment by ML-Mr-J** [comment]
trt 7 has the same problem...

**Comment by ML-Mr-J** [comment]
trt 7 has the same problem...

**Comment by ML-Mr-J** [comment]
trt 7 has the same problem...
![image](https://user-images.githubusercontent.com/40787239/126638132-65919e8f-5d11-42cc-99a0-1ab7b7111970.png)

**Comment by wang-xinyu** [comment]
@ML-Mr-J You need change trt path in CMakeLists.

**Comment by ML-Mr-J** [comment]
> CMakeLists

got it! thanks a lot.
