### ISSUE TITLE
你好，我在运行dbnet 编译完推理的时候有这个错误

### ISSUE THREAD

**Issue by praymich** [wang-xinyu/tensorrtx#638]
## Env
- Cuda 10.2
- TensorRT 7

## About this repo
- dbnet

## Your problem
hello ,when i make complete dbnet , i run "sudo ./dbnet -s",it occured as follows,
"[07/22/2021-14:29:49] [E] [TRT] CUDA initialization failure with error 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Segmentation fault"
how can i slove this?

**Comment by wang-xinyu** [comment]
seems your  CUDA and TRT environment is not right.

**Comment by praymich** [comment]
do you have the container recommend that i can pull from docker hub ？ i pulled the tensorrt 7 and CUDA 10.2 version ，it seems matching . should i install trt 7.1 and cuda 10.2？

**Comment by wang-xinyu** [comment]
You can try the dockerfile in this repo.

**Comment by praymich** [comment]
thanks , i tried dockerfile in the repo , but it still have the same question like before .
i think whether i change the result treatment in the predict.py that cause the reason , it that influence?
i  also used mobilenetv3 backbone in dbnet

**Comment by wang-xinyu** [comment]
Try the default code first.

**Comment by ML-Mr-J** [comment]
> thanks , i tried dockerfile in the repo , but it still have the same question like before .
> i think whether i change the result treatment in the predict.py that cause the reason , it that influence?
> i also used mobilenetv3 backbone in dbnet

你好，在trt 7.2.1.6   cuda 10.2下  make会出现你之间的错误，问题你是怎么解决的...

**Comment by praymich** [comment]
@wang-xinyu thanks, i solved this problem ,but i met new problem now ,it happens when i input "sudo ./dbnet -s" , it gets "Loading weights: ./DBNet.wts
[07/23/2021-10:38:55] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
dbnet: /tensorrtx/dbnet/common.hpp:94: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted"
i saw some same problem in yolov5 like others , but the have readme ,dbnet have not ,did you know how to solve this .

**Comment by praymich** [comment]
@ML-Mr-J 是那个cuda初始化失败的错误吗，因为我以前是改过predict.py的代码，我把他还原了，然后启动镜像的时候，添加了这个参数 --gpus all，就没有报这个错误了

**Comment by wang-xinyu** [comment]
@praymich Your .wts is not correct.   You need to check the readme very carefully for generating .wts

**Comment by praymich** [comment]
@wang-xinyu 十分感谢，终于跑通了，我觉得问题是出在backbone上面吗？因为我看cpp里面有构建模型一块的代码，现在还有个问题就是说我看tensorRT一般是以来gpu来跑的，但是运行程序的时候，没有看到显存占用，是cpu跑的代码吗

**Comment by ML-Mr-J** [comment]
> @ML-Mr-J 是那个cuda初始化失败的错误吗，因为我以前是改过predict.py的代码，我把他还原了，然后启动镜像的时候，添加了这个参数 --gpus all，就没有报这个错误了

是没有在cmakelist里添加相应环境..   尴尬...

**Comment by ML-Mr-J** [comment]
> @praymich Your .wts is not correct. You need to check the readme very carefully for generating .wts

Thanks for your work，while backbone resnet is supported, does dcn_resnet work well?

**Comment by wang-xinyu** [comment]
@BaofengZan what backbone do we support for dbnet?

**Comment by ttssky** [comment]
> > @praymich Your .wts is not correct. You need to check the readme very carefully for generating .wts
> 
> Thanks for your work，while backbone resnet is supported, does dcn_resnet work well?



> > @ML-Mr-J 是那个cuda初始化失败的错误吗，因为我以前是改过predict.py的代码，我把他还原了，然后启动镜像的时候，添加了这个参数 --gpus all，就没有报这个错误了
> 
> 是没有在cmakelist里添加相应环境.. 尴尬...

不愧是你，son
