### ISSUE TITLE
rcnn部分RPN的anchors疑问

### ISSUE THREAD

**Issue by ousinkou** [wang-xinyu/tensorrtx#639]
在detectron2里面，一张图片生成了 `h*w*15`个anchors，其中h,w分别是feature的高、宽。
但为什么这儿GenerateAnchors只有最原始的15个，然后在后面RpnDecodePlugin也没找到相应代码，
很是疑惑。求解答。

**Comment by wang-xinyu** [comment]
@freedenS pls take a look.

**Comment by freedenS** [comment]
GenerateAnchors等同于https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/anchor_generator.py#177 生成的是偏移，对不同位置（h*w）来说偏移都是一样的。
https://github.com/wang-xinyu/tensorrtx/blob/master/rcnn/RpnDecode.cu#96 x,y就是位置，d是偏移，x1,x2,y1,y2就是锚框坐标。
detectron2是提前把所有的锚框坐标算好，而rcnn这里是只计算最后保留的，减少了一部分计算量。

**Comment by ousinkou** [comment]
Thank you very much, I got it.
