### ISSUE TITLE
Minimal TRT inference speed difference between YOLOv5m6 and YOLOv5s6.

### ISSUE THREAD

**Issue by stef-devisscher** [wang-xinyu/tensorrtx#641]
## Env

- GPU: GTX 3080
- OS: Ubuntu18.04

## About this repo
I am using the YOLOv5m, YOLOv5s6 and YOLOv5m6 models.

## Your problem
Not sure if questions about just YOLOv5 TRT are also answered here, but I'm quite stuck on this. I was able to create a good performing detection model with transfer learning from YOLOv5m6. The issue is that this model was too slow on inference. For this reason I transfer learned the YOLOv5s6 model and performance is also good enough, however, even with this model, the TRT inference is too slow. The weird part is that looking at how much smaller the YOLOv5s6 model is compared to YOLOv5m6, the inference speed in TRT should also be significantly faster. However I get the following results:

**YOLOv5s6**: 23.4135FPS -> 5.0825s for 119 images
**YOLOv5m6**: 22.3340FPS -> 5.3282s for 119 images

and for comparison the YOLOv5m model on the same dataset:

**YOLOv5l**: 75.8793FPS -> 1.5683s for 119 images

and as you can see, there is nearly no difference between YOLOv5s6 and YOLOv5m6, but the YOLOv5l is significantly faster, while in all documentation I can find, the speed difference between YOLOv5l and YOLOv5s6 should be way smaller than between YOLOv5s6 and YOLOv5m6. 

I am almost certain I am doing something wrong, but all the file sizes of the TRT models confirm that I am not accidentally using the wrong model. 

My question is what the cause of this could be and how I could get the higher inference speed in TRT?

**Comment by wang-xinyu** [comment]
Did compare yolov5s and yolov5m in this repo?
