### ISSUE TITLE
Can not convert yolov5x6 

### ISSUE THREAD

**Issue by nguyenviettuan96** [wang-xinyu/tensorrtx#642]
## Env

- GPU: NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2 
- TensorRT: 7.2.1.6

## About this repo
I use model pretrained yolov5x6 on my custom data, after follow these steps until doing command: sudo ./yolov5 -s last.wts yolov5.engine c 1.33 1.25, I get the error

## Your problem

Hyp I set in:
yolov5.ccp
num_classes: 9
yololayer.h
batch_size:1
input_h:640
input_w:640
![Screenshot from 2021-07-23 10-11-20](https://user-images.githubusercontent.com/76817143/126733999-e5ac4075-9207-4d5b-8004-eec2c0ef5513.png)
Please tell me what I'm doing wrong. Thank you

**Comment by wang-xinyu** [comment]
```
 sudo ./yolov5 -s last.wts yolov5.engine c6 1.33 1.25
```
or 
```
 sudo ./yolov5 -s last.wts yolov5.engine x6
```

**Comment by nguyenviettuan96** [comment]
But That is also not work
![Screenshot from 2021-07-23 12-14-05](https://user-images.githubusercontent.com/76817143/126740050-eac684d8-3599-4845-b963-8ba318f23476.png)

**Comment by nguyenviettuan96** [comment]
That's done the problem is that I trained model with wrong custom hyp.yaml so I change with scratch hyp

**Comment by nguyenviettuan96** [comment]
Thank 

> ```
>  sudo ./yolov5 -s last.wts yolov5.engine c6 1.33 1.25
> ```
> 
> or
> 
> ```
>  sudo ./yolov5 -s last.wts yolov5.engine x6
> ```

Thank you
