### ISSUE TITLE
同样的CMakeLists，vs2017编译通过，19怎么都过了不

### ISSUE THREAD

**Issue by ycdhqzhiai** [wang-xinyu/tensorrtx#646]
## Env

- GPU: RTX3060
- OS: Win10
- Cuda version: 11.3
- TensorRT version: 8.1

## About this repo

- which branch/tag/commit are you using?
- master
- which model? yolov5
## Your problem
RT

![image](https://user-images.githubusercontent.com/12273405/126963374-10d44f7c-3ac3-48cd-844d-0b1b90c94aa5.png)

**Comment by ycdhqzhiai** [comment]
参考了[run_on_windows](https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md)

**Comment by heiybb** [comment]
Exactly the same error on VS2019 with 
cuda_11.3.0_465.89_win10
cudnn-11.3-windows-x64-v8.2.1.32
TensorRT-8.0.3.4.Windows10.x86_64.cuda-11.3.cudnn8.2
'enqueue' function being told that "member function declared with 'override' does not override a base calss member"

**Comment by wang-xinyu** [comment]
You guys need to figure out it by yourself. I'm also planning to remove everything related to windows in this repo.
