### ISSUE TITLE
YOLOv5s trt model run on the same two graphics card RTX3090, one of cards has half inference speed

### ISSUE THREAD

**Issue by rongrong9005** [wang-xinyu/tensorrtx#647]
- RTX 3090
- Win10
- Cuda 11.0
- TensorRT 7

I serialize the yolov5s tenosrrt model on two identical computers and run the same program, but why is the inference speed of one of the computers is half slow?

**Comment by zxm97** [comment]
> * RTX 3090
> * Win10
> * Cuda 11.0
> * TensorRT 7
> 
> I serialize the yolov5s tenosrrt model on two identical computers and run the same program, but why is the inference speed of one of the computers is half slow?


I serialize the yolov5s tensorrt model on two windows 10 computers (one with GTX1660 6G/cuda10.2/cudnn8.2 and another one with RTX3060 12G/cuda11.5/cudnn8.3) and run the same number of processes. But the 3060 computer is slower and the GPU memory usage per process is about 1GB (400+MB on 1660 computer).
