### ISSUE TITLE
yolov5 converter script killed

### ISSUE THREAD

**Issue by ZAYEC77** [wang-xinyu/tensorrtx#650]
## Env

- GPU, RTX3070
- OS, Ubuntu 20.04
- CUDA: 11.4
- TensorRT 8.0.1

## About this repo

- which branch/tag/commit are you using? -- master
- which model? - yolov5

## Your problem

- what is your command? -  `./yolov5 -s <.wts> <.engine> s`
- what's your output? - Killed
- what output do you expect? - generate TRT engine file

Got huge tone of warnings during the build:
![image](https://user-images.githubusercontent.com/4509483/127229289-dbb4e32f-d356-44d1-8591-d180e86bee1e.png)

and when run `./yolov5 -s <.wts> <.engine> s`
got just:
```
Loading weights: yolov5s.wts
Killed
```

And I really don't have any ideas how to debug it

**Comment by dmytrokarpovych** [comment]
I tried to use TensorRT docker image: https://ngc.nvidia.com/catalog/containers/nvidia:tensorrt
running options:
```
sudo docker run -it --rm \
  --net=host \
  --ipc=host \
  --oom-kill-disable \
  --memory="6g" \
  --memory-swap="20g" \
  --runtime nvidia \
...
```

So, it was killed not by OOM I guess

**Comment by wang-xinyu** [comment]
warnings do not matter.
Killed means memory not enough.

**Comment by dmytrokarpovych** [comment]
> warnings do not matter.
> Killed means memory not enough.

Thanks for response 
I tried to reboot system and changed version of trt to 7.2.2 and it works now
