### ISSUE TITLE
DBnet  building engine error

### ISSUE THREAD

**Issue by neverstoplearn** [wang-xinyu/tensorrtx#654]
## Env

- GPU,  1050Ti
- OS,  ubuntu18.04
- Cuda version 11.1
- TensorRT version 7.2.3.4

## About this repo

 DBNet

## Your problem
(base) zhengxin@zhengxin:~/tensorrtx/dbnet/build$ sudo ./dbnet -s
[sudo] zhengxin 的密码： 
Loading weights: ./DBNet2.wts
Building engine, please wait for a while...
[07/29/2021-22:38:57] [F] [TRT] Assertion failed: !empty()
../builder/intInterval.cpp:20
Aborting...
[07/29/2021-22:38:58] [E] [TRT] ../builder/intInterval.cpp (20) - Assertion Error in min: 0 (!empty())
Build engine successfully!
dbnet: /home/zhengxin/tensorrtx/dbnet/dbnet.cpp:759: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
已放弃

**Comment by wang-xinyu** [comment]
@BaofengZan pls help take a look.

**Comment by neverstoplearn** [comment]
> @BaofengZan pls help take a look.

定位到.wts文件某行存在乱码情况。

**Comment by neverstoplearn** [comment]
> > @BaofengZan pls help take a look.
> 
> 定位到.wts文件某行存在乱码情况。

x-special/nautilus-clipboard
copy
file:///home/zhengxin/%E5%9B%BE%E7%89%87/20.png
