### ISSUE TITLE
resnet/mobilenetv2模型trt结果和pytorch结果对不上

### ISSUE THREAD

**Issue by deep-practice** [wang-xinyu/tensorrtx#655]
## Env

- GPU:RTX2080Ti
- OS:Ubuntu16.04
- Cuda version:10.1
- TensorRT version:7.0.0.11

## About this repo

- which branch/tag/commit are you using?
- yolov5-3.1
- which model? yolov5, retinaface?
resnet,mobilenetv2
## Your problem
trt output is different from pytroch output

trt:
index:0,prob:0.99734
index:2,prob:0.99838
index:1,prob:0.806916
index:0,prob:0.972682
index:8,prob:0.999126
index:4,prob:0.933807
index:0,prob:0.994681
index:0,prob:0.827
index:2,prob:0.834848
index:0,prob:0.993576
index:2,prob:0.999243
index:3,prob:0.989723
index:3,prob:0.993553
index:1,prob:0.999804
index:2,prob:0.999754
index:2,prob:0.946523
index:0,prob:0.934907
index:0,prob:0.991092
index:1,prob:1

pytorch:
index: 0 ,prob: 0.96484375
index: 2 ,prob: 0.9970703125
index: 1 ,prob: 0.986328125
index: 1 ,prob: 0.8408203125
index: 8 ,prob: 0.96826171875
index: 3 ,prob: 0.658203125
index: 0 ,prob: 0.9833984375
index: 0 ,prob: 0.93603515625
index: 0 ,prob: 0.927734375
index: 0 ,prob: 0.97509765625
index: 2 ,prob: 0.99658203125
index: 3 ,prob: 0.87939453125
index: 3 ,prob: 0.9462890625
index: 1 ,prob: 0.9873046875
index: 2 ,prob: 0.97705078125
index: 0 ,prob: 0.59619140625
index: 1 ,prob: 0.53125
index: 0 ,prob: 0.93798828125
index: 1 ,prob: 1.0

**Comment by deep-practice** [comment]
pytorch preprocess:
transform = transforms.Compose([
        transforms.Resize((256,192)),
        transforms.ToTensor(),
        transforms.Normalize(
            [0.485, 0.456, 0.406],
            [0.229, 0.224, 0.225])])
RGB format

trt preprocess:
static float data[1 * 3 * INPUT_H * INPUT_W];
    cv::Mat img = cv::imread(img_path); // BGR
    cv::Mat pr_img;
    cv::resize(img, pr_img, cv::Size(INPUT_W, INPUT_H));
    cv:cvtColor(pr_img,pr_img,cv::COLOR_BGR2RGB);
    int i = 0;
    for (int row = 0; row < INPUT_H; ++row) {
            uchar* uc_pixel = pr_img.data + row * pr_img.step;
            for (int col = 0; col < INPUT_W; ++col) {
                    data[0 * 3 * INPUT_H * INPUT_W + i] = ((float)uc_pixel[2] / 255.0 - 0.485) / 0.229; // R-0.485
                    data[0 * 3 * INPUT_H * INPUT_W + i + INPUT_H * INPUT_W] = ((float)uc_pixel[1] / 255.0 - 0.456) / 0.224;
                    data[0 * 3 * INPUT_H * INPUT_W + i + 2 * INPUT_H * INPUT_W] = ((float)uc_pixel[0] / 255.0 - 0.406) / 0.225;
                    uc_pixel += 3;
                    ++i;
                }
    }

**Comment by wang-xinyu** [comment]
Did you try input a ones tensor(all 1.0) and compare?

**Comment by deep-practice** [comment]
After I remove the resize op,the outputs are the same...
