### ISSUE TITLE
dbent build engine error

### ISSUE THREAD

**Issue by neverstoplearn** [wang-xinyu/tensorrtx#658]
## Env

- GPU, RTX1050ti
- OS, ubuntu18.04
- Cuda version 11.1
- TensorRT version  7.2.3.4

## About this repo

- which branch/tag/commit are you using?
- which model? dbent

## Your problem

- what is your command? `sudo ./dbnet -s`
- what's your output?
- sudo ./dbnet -s
Loading weights: ./DBNet2.wts
1 24  -1 -1 
1 24  -1 -1 
1 24  -1 -1 
1 24  -1 -1 
1 96  -1 -1 
1 96  -1 -1 
Building engine, please wait for a while...
[07/31/2021-09:47:18] [W] [TRT] TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[07/31/2021-09:47:18] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.3.0 but loaded cuBLAS/cuBLAS LT 11.2.1
[07/31/2021-09:47:38] [F] [TRT] Assertion failed: validateInputsCutensor(src, dst)
../rtSafe/cuda/cutensorReformat.cpp:227
Aborting...
[07/31/2021-09:47:38] [E] [TRT] ../rtSafe/cuda/cutensorReformat.cpp (227) - Assertion Error in executeCutensor: 0 (validateInputsCutensor(src, dst))
Build engine successfully!
dbnet: /home/zhengxin/tensorrtx/dbnet/dbnet.cpp:868: void APIToModel(unsigned int, nvinfer1::IHostMemory**): Assertion `engine != nullptr' failed.
已放弃
- what output do you expect?
成功构建dbent engine

定位到错误出现在：
` ITensor* inputTensors[] = { p2->getOutput(0), p3_up_p2->getOutput(0), p4_up_p2->getOutput(0),    p5_up_p2->getOutput(0) };
    IConcatenationLayer* neck_cat = network->addConcatenation(inputTensors, 4);
    Dims neck_cat2dim = neck_cat->getOutput(0)->getDimensions();
    std::cout << neck_cat2dim.d[0]  << " " << neck_cat2dim.d[1]  << "  "  << neck_cat2dim.d[2] << " " << neck_cat2dim.d[3]  << " " << std::endl;
    ILayer* neck_out = convBnLeaky(network, weightMap, *neck_cat->getOutput(0), 96, 3, 1, 1, "neck.conv.0", ".1");  // smooth
    assert(neck_out);`
通过注释，在neck_cat前可以成功构建dbnet engine，通过打印维度发现neck_cat,neck_out正常，请问如何解决错误？有可行的思路吗？谢谢！！！

**Comment by wang-xinyu** [comment]
@BaofengZan pls take a look.

**Comment by neverstoplearn** [comment]
> @BaofengZan pls take a look.

这个项目的dbnet原始backbone 是resnet18，我更改了backbone为mobilenet v3，并且把neck的inner_channel更改为96，重新按照项目指定的Python代码训练了模型并导出wts文件，重新构建了mobilenet v3，但是这个错误不知道是哪里出了问题，麻烦指教一下，谢谢。
