### ISSUE TITLE
yolov4生成wts时，报错Segmentation fault？

### ISSUE THREAD

**Issue by diffgg** [wang-xinyu/tensorrtx#66]
我的环境是jetson tx2，jetpack4.3，pytorch 1.4.0，系统自带的python 3.6  
运行python3 gen_wts.py yolov4.weights会报错：Segmentation fault (core dumped)  
在目前的issue里好像也只有我这样，请问这是哪里出了问题？

**Comment by PengchengWang** [comment]
wts生成不一定要在tx2上做，可以在其他地方转换好直接copy过来。我以前tx2也报了很多错误，最后花了一天时间把tx2升级到最先版本cuda10.2，TRT7.1，什么问题都没了。
