### ISSUE TITLE
Pytorch_Retinaface python3 detect.py --save_model err

### ISSUE THREAD

**Issue by HBProlove** [wang-xinyu/tensorrtx#663]
## Env

- GPU: Xavier NX
- OS,: Ubuntu18.04.
 - NVIDIA Jetson Xavier NX (Developer Kit Version)
   * Jetpack 4.5.1 [L4T 32.5.1]
   * NV Power Mode: MODE_15W_6CORE - Type: 2
   * jetson_stats.service: active
 - Libraries:
   * CUDA: 10.2.89
   * cuDNN: 8.0.0.180
   * TensorRT: 7.1.3.0
   * Visionworks: 1.6.0.501
   * OpenCV: 4.1.1 compiled CUDA: NO
   * VPI: ii libnvvpi1 1.0.15 arm64 NVIDIA Vision Programming Interface library
   * Vulkan: 1.2.70

## About this repo

- which branch/tag/commit are you using?
   master
commit beda45c3665f48a20dc2fba5a8e91032100c50c4 (HEAD -> master, origin/master, origin/HEAD)
Merge: 00563fe b984b4b
Author: Wang Xinyu <wangxinyu_es@163.com>
Date:   Thu May 14 20:59:07 2020 +0800
       Merge pull request #1 from biubug6/master    
       Update README.md
- which model? yolov5, retinaface?
retinaface
## Your problem
a411@a411-nx:~/RetinaFace_trt_proj/Pytorch_Retinaface$ python3 detect.py --save_model
Loading pretrained model from ./weights/Resnet50_Final.pth
remove prefix 'module.'
Missing keys:456
Unused checkpoint keys:267
Used keys:0
Traceback (most recent call last):
  File "detect.py", line 76, in <module>
    net = load_model(net, args.trained_model, args.cpu)
  File "detect.py", line 62, in load_model
    check_keys(model, pretrained_dict)
  File "detect.py", line 40, in check_keys
    assert len(used_pretrained_keys) > 0, 'load NONE from pretrained checkpoint'
AssertionError: load NONE from pretrained checkpoint

**Comment by wang-xinyu** [comment]
Did you follow here strictly https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface#run?
