### ISSUE TITLE
ERROR: 6: The engine plan file is not compatible with this version of TensorRT, expecting library version 8.0.0 got 8.0.1, please rebuild.

### ISSUE THREAD

**Issue by umairjavaid** [wang-xinyu/tensorrtx#664]
Getting the above error. I really do not want to install previous version of tensor RT as installation is a hectic process. Is there a work around this?

- GPU, e.g. gtx 1660
- OS,  Ubuntu18.04, 
- Cuda 11.3
- TensorRT 8.0.1.6

## About this repo

- which model? yolov5 m

**Comment by umairjavaid** [comment]
I used use your code to make the engine file with tensorRT 8.0.1.6. However, it is giving me this error.

**Comment by wang-xinyu** [comment]
The error message is very obvious.

**Comment by umairjavaid** [comment]
It is working in the c++ code but getting this error in python

**Comment by wang-xinyu** [comment]
It means your tensorrt version in python is not same as c++.
