### ISSUE TITLE
Evaluation TensorRT C++ - ground truth images INPUT_H / INPUT_W

### ISSUE THREAD

**Issue by Ignasinou** [wang-xinyu/tensorrtx#665]
Hi, first of all thanks for your amazing work!

## Env

- GPU RTX2070
- OS Win10
- Cuda version 11.1
- TensorRT version 7.2.1.6

## About this repo

- which branch/tag/commit are you using? Master
- which model? yolov5, retinaface? Yolov5

## Your problem
I am trying to run an evaluation of a yolov5-l model. 

First, I created the engine (INPUT_H/INPUT_W 320 x 320) and changed the number of classes to 3. Once the engine was created correctly, I ran the inference and the predictions were as expected (see the images).

After that, I added the ground truth (GT) bboxes to get the evaluation. It turns out that the ground truth images are not correctly scaled. The GT bboxes follow the same format as yolov5 (x_center, y_center, w, h), so, before adding them to each image, I first multiply them by INPUT_H and INPUT_W:

 
```
float xcenter = std::stof(gtBoxLineSplit[1]) * INPUT_W;  
float ycenter = std::stof(gtBoxLineSplit[2]) * INPUT_H; 
float w = std::stof(gtBoxLineSplit[3]) * INPUT_W;  
float h = std::stof(gtBoxLineSplit[4]) * INPUT_H;  
```

And then I've added them to the output image (as is done with predicates):

```
float bbox_gt[4] = { gt_txt_proc[jjj][1] ,gt_txt_proc[jjj][2] ,gt_txt_proc[jjj][3] ,gt_txt_proc[jjj][4] };    
cv::Rect r = get_rect(img, bbox_gt);    
cv::rectangle(img, r, cv::Scalar(120, 120, 120), 2);    
cv::putText(img, std::to_string((int)gt_txt_proc[jjj][0]), cv::Point(r.x, r.y - 1), cv::FONT_HERSHEY_PLAIN, 1.2, cv::Scalar(0xFF, 100, 0xFF), 2);    
```
As you can see, the height (and y-centre, I guess) are not scaled correctly but the widths are correct. After a while, I found that by changing the INPUT_W to 640 the GT looked as expected, (see the following image) but then, (as expected) no prediction is shown.

**Comment by wang-xinyu** [comment]
You can refer to https://github.com/wang-xinyu/tensorrtx/pull/573 for evaluation.
