### ISSUE TITLE
make 报错    /yolov5/common.hpp:8:30: fatal error: opencv2/opencv.hpp: 没有那个文件或目录

### ISSUE THREAD

**Issue by cendelian** [wang-xinyu/tensorrtx#67]
执行 make 报错如下：
/yolov5/common.hpp:8:30: fatal error: opencv2/opencv.hpp: 没有那个文件或目录

请问是需要安装opencv2？ c版？python版？

**Comment by wang-xinyu** [comment]
我用的是opencv3.3，c++版

**Comment by cendelian** [comment]
> 我用的是opencv3.3，c++版

谢谢，如果安装最新版opencv 4.3是否可行？向下兼容吗？

**Comment by wang-xinyu** [comment]
可以试试，不一定

**Comment by wangtianlong1994** [comment]
@cendelian 您好 请问您怎么解决了这个问题？我安装了opencv 3.4 同样出现了这个问题

**Comment by 108356037** [comment]
ubuntu 環境下可以試試這個：
sudo apt-get install libopencv-dev

**Comment by Mon-Rain** [comment]
我使用的opencv4.5.0，遇到了同样的问题，所属环境是ubuntu，cmake过程中opencv路径没有问题。

**Comment by Mon-Rain** [comment]
> 我使用的opencv4.5.0，遇到了同样的问题，所属环境是ubuntu，cmake过程中opencv路径没有问题。

我想我已经解决了，主要问题是include文件夹中的结构是include/opencv4/opencv2，我把opencv2 cp到了父路径，解决了问题
