### ISSUE TITLE
Does tensorrtx support yolov5s only, now?

### ISSUE THREAD

**Issue by BruceWang1996** [wang-xinyu/tensorrtx#670]

**Comment by wang-xinyu** [comment]
yolov5-v1.0, only support s
v2.0 - v5.0, support all

**Comment by qtw1998** [comment]
> yolov5-v1.0, only support s
> v2.0 - v5.0, support all

v5.0 the latest yolov5 from U大
还是出现了这个问题
`arguments not right!`
