### ISSUE TITLE
The command '/bin/sh -c python gen_wts.py yolov5s.pt' returned a non-zero code: 2

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [wang-xinyu/tensorrtx#683]
below is the docker code 
where i am trying to generates weights using 
RUN python gen_wts.py yolov5s.pt 
but getting error file not found 
The command '/bin/sh -c python gen_wts.py yolov5s.pt' returned a non-zero code: 2

# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Start FROM Nvidia PyTorch image https://ngc.nvidia.com/catalog/containers/nvidia:pytorch
FROM nvcr.io/nvidia/pytorch:21.05-py3

# Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx

# Install python dependencies
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip uninstall -y nvidia-tensorboard nvidia-tensorboard-plugin-dlprof
RUN pip install --no-cache -r requirements.txt coremltools onnx gsutil notebook
RUN pip install --no-cache -U torch torchvision numpy
#RUN pip install --no-cache torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy contents
COPY . /usr/src/app

# Set environment variables
ENV HOME=/usr/src/app

# download weights and run export.py for onxx
RUN echo $"ONNX export started......................................."
RUN wget https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt
RUN python export.py --weights yolov5s.pt --img 640 --batch-size 1 
RUN echo $"ONNX export finished and file generated successfully......"

# program for tensorrt
# generate .wts from pytorch with .pt, or download .wts from model zoo
RUN echo $"generattion of weights from .pt has been started............"
RUN git clone -b v5.0 https://github.com/ultralytics/yolov5.git
RUN git clone https://github.com/wang-xinyu/tensorrtx.git 
RUN cd yolov5
RUN wget https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt
RUN cd ..
RUN cp tensorrtx/yolov5/gen_wts.py yolov5/
RUN cd yolov5
RUN python gen_wts.py yolov5s.pt
RUN echo $"yolo weights are generated..................................."

# build tensorrtx/yolov5 and run
RUN cd ~/tensorrtx/yolov5
RUN mkdir build
RUN cd build
RUN cp ~/yolov5/yolov5s.wts ~/tensorrtx/yolov5/build/
RUN cmake ..
RUN make
RUN apt-get install sudo
RUN sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
RUN sudo ./yolov5 -d yolov5s.engine ../samples

**Comment by wang-xinyu** [comment]
Pls read tensorrtx/yolov5/readme

**Comment by shubhamgajbhiye1994** [comment]
yeah! done. Issue resolve
