### ISSUE TITLE
Yolo v4 tiny

### ISSUE THREAD

**Issue by lthbk5919** [wang-xinyu/tensorrtx#69]
When you release Yolo v4 tiny on tensorrtx

**Comment by alexanderfrey** [comment]
Also very much interested in this !

**Comment by tjuskyzhang** [comment]
I have made a yolov4-tiny-tensorrt project based on this project
https://github.com/tjuskyzhang/yolov4-tiny-tensorrt

**Comment by wang-xinyu** [comment]
@tjuskyzhang excellent!

**Comment by cosama** [comment]
I tried https://github.com/tjuskyzhang/yolov4-tiny-tensorrt to make work but it didn't create any bboxes/detections (https://github.com/tjuskyzhang/yolov4-tiny-tensorrt/issues/5). Anybody used that repo successfully? Hints would be welcome.

**Comment by cosama** [comment]
By using the pt file from https://github.com/WongKinYiu/PyTorch_YOLOv4/tree/master I managed to run yolov4-tiny successfully with that repo now. Thanks @tjuskyzhang for helping.
