### ISSUE TITLE
Run tensorrtx on tx2

### ISSUE THREAD

**Issue by DoveJH** [wang-xinyu/tensorrtx#693]
## Env

- GPU, TX2.
- OS, Ubuntu18.04.
- Cuda 10.2

## About this repo

yolov5

## Your problem
 I use this model on tx2, input size is 640*512, batch size is 1. The infereance time is 33ms. Is it normal?

**Comment by wang-xinyu** [comment]
No idea, never test it on TX2.

**Comment by ismet-dagli** [comment]
Which yolov5 version are you referring to?
