### ISSUE TITLE
Can I use TTA ?

### ISSUE THREAD

**Issue by Yangr116** [wang-xinyu/tensorrtx#694]
Thanks for your nice work!
mmmm, I would like to know whether I can use TTA in inference when I use TensorRT improving speeds.

**Comment by wang-xinyu** [comment]
What is TTA?

**Comment by Yangr116** [comment]
> What is TTA?
thanks for your reply, TTA is test time augmentation, like filp, multi-scale test, and so on.

**Comment by wang-xinyu** [comment]
Oh, you can treat TTA as preprocess before feeding data into the tensorrt engine. Or you can add tensorrt layers to implement TTA.

**Comment by Yangr116** [comment]
Thanks for your quick reply, I will try later.
