### ISSUE TITLE
I want to learn tensorrt

### ISSUE THREAD

**Issue by umairjavaid** [wang-xinyu/tensorrtx#695]
I am very impressed by your work! 
I was wondering, how did you learn so much about tensorrt? Did you follow any tutorials or blogs? 
I want to learn tensorrt as well, but the documentation provided by nvidia is so daunting, could you share some other resources, if there are any. I would be highly obliged.

**Comment by wang-xinyu** [comment]
Mostly I was learning from tensorrt docs and API docs. Probably if good at c++, it would be faster to learn.
