### ISSUE TITLE
loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file. please check if the .wts file path is right!!!!!!"' failed.

### ISSUE THREAD

**Issue by qtw1998** [wang-xinyu/tensorrtx#696]
## Env

- GPU,NANO
- OS, Ubuntu18.04
- Cuda version 10.2.89
- TensorRT version 7.1.3.0

## About this repo
z3@Nano:~/setup/tensorrtx/yolov5/build$ sudo ./yolov5 -s 
Loading weights: ../yolov5s.wts
yolov5: /home/z3/setup/tensorrtx/yolov5/common.hpp:128: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `input.is_open() && "Unable to load weight file. please check if the .wts file path is right!!!!!!"' failed.
Aborted
OR

z3@Nano:~/setup/tensorrtx/yolov5/build$ sudo ./yolov5 -s ../yolov5s.wts ../yolov5.engine s
arguments not right!
./yolov5 -s  // serialize model to plan file
./yolov5 -d ../samples  // deserialize plan file and run inference

DOWNLOADED FROM THE V5.0 OFFICIAL REPO
## Your problem
![image](https://user-images.githubusercontent.com/34357479/131297388-48258e03-1ac1-48db-bfa9-f84a824b0556.png)

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
git pull the latest code

**Comment by qtw1998** [comment]
> git pull the latest code

yep thx bro

**Comment by zhangwx1019** [comment]
> git pull the latest code

why
