### ISSUE TITLE
Unable to load yolo5s engine file in python inference script

### ISSUE THREAD

**Issue by thasin96** [wang-xinyu/tensorrtx#697]
## Env

- GPU, Nano
- OS Ubuntu18.04
- Cuda version 10.2
- TensorRT version 7.1

## About this repo

- Latest
- which model? yolov5 small

## problem

- what is your command? e.g. `python3 yolov5_trt.py`
- what's your output?
I am not getting any output. The engine deserialization freezes my machine
- what output do you expect?
I expect the same result from cpp (yolov5 inside build folder)

I am able to successfully convert wts file to engine. I am able to perform inference using yolov5 cpp plugin. But, when I try to do the same behaviour using python script (yolov5_trt.py), my machine freezes. I have identified that deserializing the engine file is the issue. I am using 4Gb nano device. I have checked memory level, RAM and SWAP memory are fully occupied. 

Could you help me how to load yolov5s engine file?

**Comment by wang-xinyu** [comment]
It's not recommended to run .py in nano.

But still, you can try remove torchvision.nms.

**Comment by thasin96** [comment]
yeah, I have read other threads related to this on your issues page. But, somehow, I need python to load the engine. 
Actually, `trt.runtime(TRT_LOGGER)` consumes the whole memory. Is this expected.

**Comment by wang-xinyu** [comment]
It's abnormal, probably bugs pf tensorrt python. You can try the newest jetpack.

**Comment by thasin96** [comment]
okay cool. i will check.

**Comment by thasin96** [comment]
@wang-xinyu  - It's basically torchvision problem. torchvision and trt is exploding my RAM. I have written nms implementation in np and now it's working perfectly. thakns for your response.
