### ISSUE TITLE
Python wrapper support

### ISSUE THREAD

**Issue by rose-jinyang** [wang-xinyu/tensorrtx#70]
Hello
How are you?
Thanks for contributing this project.
Of course, I think that this project is an implementation using TensorRT C++ API.
But there are also many people who use Python rather than C++.
Could u provide python wrapper in this project too?
Specially, I need a python wrapper for yolov5.
Thanks.

**Comment by wang-xinyu** [comment]
currently no python wrapper. maybe add it in the future

**Comment by duchengyao** [comment]
+1
