### ISSUE TITLE
YOLOV3 tiny fault

### ISSUE THREAD

**Issue by qtw1998** [wang-xinyu/tensorrtx#701]
## Env

- GPU, Nano.
- OS,Ubuntu18.04,
- Cuda 10.2
- TensorRT 7.1.3

## About this repo
Already downloaded from GoogleDrive as instructions.
![image](https://user-images.githubusercontent.com/34357479/131465729-bc9fa1f4-5d51-4468-804d-f06bd0200273.png)

Then already copied gen_wts.py and run.
get bellow outcomings as bellow:

## Your problem
![image](https://user-images.githubusercontent.com/34357479/131465608-a9feed18-d657-4bd6-8862-689d45665914.png)

**Comment by wang-xinyu** [comment]
You need to download .pt from archive branch, rather than google drive.
