### ISSUE TITLE
关于yolov5的推理结果

### ISSUE THREAD

**Issue by RedFree** [wang-xinyu/tensorrtx#706]
## Env

- GPU, RTX2080ti
- OS,  Ubuntu18.04,
- Cuda 11.1
- TensorRT 8.1.1

## About this repo

- master branch
- yolov5s model

模型推理之后结果不正确：如下图
![选区_631](https://user-images.githubusercontent.com/5827427/131833005-17862367-af22-420f-978d-69e86ced5cc9.png)

请问这个有可能是什么原因呢

**Comment by RedFree** [comment]
@wang-xinyu 我按照yolov5/readme这个方法反复尝试了好几次，结果依然跟图上的结果一样，而且每次结果的框都不一样，这个会不会跟我的环境有关系呢。

**Comment by RedFree** [comment]
@wang-xinyu 我按照yolov5/readme这个方法反复尝试了好几次，结果依然跟图上的结果一样，而且每次结果的框都不一样，这个会不会跟我的环境有关系呢。

**Comment by wang-xinyu** [comment]
Are you using the official model? or your own trained model?

**Comment by RedFree** [comment]
我用的是官方的yolov5s.pt的模型，下载地址：
https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt
然后tensorrtx用的是master分支
使用我自己训练的模型结果也是这种情况，但是该模型在其他环境都可以正常推理，结果也是正确的。
我的环境：
OS： ubuntu 18.04
cuda: 11.1
cudnn: 8.2.1.32
tensorrt: TensorRT-8.0.1.6.Linux.x86_64-gnu.cuda-11.3.cudnn8.2

**Comment by wang-xinyu** [comment]
No idea, I also tried trt8.0.1 before, it was working well. Try cleaning everything and start from scratch.

**Comment by RedFree** [comment]
好的，我再试试，感谢！

**Comment by siriusdemon** [comment]
我试了 m 模型，是可以的呢。
