### ISSUE TITLE
inference performance different from python code result

### ISSUE THREAD

**Issue by zhenglh33** [wang-xinyu/tensorrtx#708]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc. jetson xavier
- OS, e.g. Ubuntu16.04, Win10, etc. ubuntu 18.04
- Cuda version 10.2
- TensorRT version 7.1.3

## About this repo

- which branch/tag/commit are you using? master
- which model? yolov5
## Your problem
The inference result of tensorrt is different from using python code when they are using converted model,
I checked the preprocessing should be the same

I tried to output the bbox number during running nms function, there is restriction in for loop

`void nms(std::vector<Yolo::Detection>& res, float *output, float conf_thresh, float nms_thresh = 0.5) {
    int det_size = sizeof(Yolo::Detection) / sizeof(float);
    std::map<float, std::vector<Yolo::Detection>> m;
    for (int i = 0; i < output[0] && i < Yolo::MAX_OUTPUT_BBOX_COUNT; i++)`

so why set output[0] and what does output[0] stands for? (in common.hpp)

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
ouput[0] stands for how many number of bboxes in the output.

**Comment by zhenglh33** [comment]
is this the output of original yolov5s (python) or you added it in constructing yolo in yolov5.cpp?

**Comment by wang-xinyu** [comment]
You can check the yololayer plugin.

**Comment by zhenglh33** [comment]
I checked, it seems like the difference only happens to our own retrained model
before I converted .wts file to engine file, I only changed CLASS_NUM, anything I missed?

**Comment by wang-xinyu** [comment]
Do you mean ./yolov5 works well, while yolov5_trt.py cannot output any bbox? Can you give an example with images?

**Comment by zhenglh33** [comment]
I used detect.py from ultralyrics.  For official model we downloaded, the output is the same, same bbox and same confidence. But for our own model, the confidence is different
![5627](https://user-images.githubusercontent.com/68574563/131977662-1ac053bc-39ba-45ed-a449-302e39b0fe65.jpg)
pretrained python
![_5627](https://user-images.githubusercontent.com/68574563/131977774-188dae08-b8aa-4958-8969-34ef15dff5fc.jpg)
pretrained tensorrt


retrained model -- python
![5627](https://user-images.githubusercontent.com/68574563/131977929-b7d964f1-59af-476d-b998-fa4309011954.jpg)

tensorrt
![_5627](https://user-images.githubusercontent.com/68574563/131977969-e7de579c-61a7-4ea8-8f34-fce1f1249e7d.jpg)

**Comment by wang-xinyu** [comment]
Let's say model0 works well, model1 missed some objects.

What you can do is to compare model0 with model1 layer by layer, to check the difference.

**Comment by wang-xinyu** [comment]
But this seems not the model issue, you can check more images.

The mAP in tensorrt will drop 0.02.

**Comment by wang-xinyu** [comment]
Refer to https://github.com/wang-xinyu/tensorrtx/pull/573

**Comment by zhenglh33** [comment]
Thanks for the advise and the link.
We will try to find out what caused our retrained model performed differently on python and tensorrt

**Comment by zhenglh33** [comment]
Hi, I checked with my colleague, the model is not changed, he only changed the class number. The structure of network seems not to be changed during training

For tensorrtx side, I also changed class number, but the output of tensorrt and pytorch are differentaccording to previous images. I checked hyper-parameters, we used default model to do the training

I want to ask which part I missed when do the conversion? I only changed CLASS_NUM, and used `sudo ./yolov5 -s best.wts retrained_b1.engine s` to convert model

**Comment by zhenglh33** [comment]
only difference might be the yolov5 model, the official model I used to do the testing is v5.0, 

would this affect the output if I just used most updated commit of this repo to convert the previous version of yolov5, let's say v3.1?

**Comment by wang-xinyu** [comment]
master branch is for 5.0, refer to the version related section in readme.

**Comment by aHodor-z** [comment]
@zhenglh33 
Hello, I would like to ask which function is the confidence added to Tensorrt, and how should I add it? Thank you

**Comment by zhenglh33** [comment]
> @zhenglh33
> Hello, I would like to ask which function is the confidence added to Tensorrt, and how should I add it? Thank you

I added at the cv::putText function, `std::to_string((int)res[j].class_id)` changes to `std::to_string((int)res[j].class_id) + ", " + std::to_string((float)res[j].conf)`

**Comment by aHodor-z** [comment]
@zhenglh33 
Thanks a lot !!!!

**Comment by zhenglh33** [comment]
For our current situation, 
pytorch + official model  = tensorrt + official model, their outputs are exactly same,
pytorch + retrained > tensorrt + retrained, in which I only changed the CLASS_NUM,

I also checked, tensorrt for v5.0 branch + retrained model = tensorrt for v4.0 branch + retrained model, so it should not be version's problem, because I checked the code, the model we used for training >= v4.0

does anyone have any ideas about this

**Comment by zhenglh33** [comment]
We found out the problem, the retrained model is saved during training, which contained more things. We used model that finished whole training, the result from tensorrt is the same as python

**Comment by NOBUGW** [comment]
> We found out the problem, the retrained model is saved during training, which contained more things. We used model that finished whole training, the result from tensorrt is the same as python

请问在训练期间保存的模型与完成的整个训练的有什么区别？在yolov5-6.0我没有发现区别呢？
What is the difference between the model saved during the training and the whole training? I didn't find any difference in yolov5-6.0？
