### ISSUE TITLE
Input shapes question

### ISSUE THREAD

**Issue by ViktorYastrebov** [wang-xinyu/tensorrtx#709]
I would like to ask you about changing the INPUT_W/INPUT_H values. Ultralitics prepared the different models with 1280x1280 input shapes. Will it work just change the INPUT_W/INPUT_H or it has dependencies on some layer?

**Comment by wang-xinyu** [comment]
You need to check whether the model you were saying is same as the yolov5s/m/l/x.

**Comment by ViktorYastrebov** [comment]
I meant to say about Yolov5s6/Yolov5m6/Yolov5l6 etc.

**Comment by wang-xinyu** [comment]
Can you just give it a try before asking?

**Comment by ViktorYastrebov** [comment]
Ok. Sorry. I will
