### ISSUE TITLE
Does it support yolov5l, yolov5x network?

### ISSUE THREAD

**Issue by ou525** [wang-xinyu/tensorrtx#71]

**Comment by wang-xinyu** [comment]
currently no.  I maybe add it next month.

**Comment by ou525** [comment]
Ok, I originally planned to change it based on yolov5s, but I'm not familiar with the network structure, I didn't succeed, look forward to your implementation

**Comment by winself** [comment]
@wang-xinyu hello,thank you for your contribution. 
bty,  when it support yolov5l, yolov5x network? 
looking forward to  your reply .

**Comment by wangtianlong1994** [comment]
Thank you for your work,Looking forward to the new yolov5。

**Comment by AIpakchoi** [comment]
@winself , I finished the work, the following implementation on my Github supports the yolov5s,yolov5m,yolov5l and yolov5x
https://github.com/AIpakchoi/yolov5_tensorrt

**Comment by AIpakchoi** [comment]
@wang-xinyu 
I finished the work, the following implementation on my Github supports the yolov5s,yolov5m,yolov5l and yolov5x
https://github.com/AIpakchoi/yolov5_tensorrt

**Comment by AIpakchoi** [comment]
@wang-xinyu 非常谢谢大佬的代码，最近在部署用，急着用就自己改了yolov5m,yolov5l and yolov5x。

**Comment by wang-xinyu** [comment]
@AIpakchoi 强！
