### ISSUE TITLE
TRT8 on Windows

### ISSUE THREAD

**Issue by adventurousbanana** [wang-xinyu/tensorrtx#711]
## Env

- GPU: gtx 1080ti
- OS: Win10,
- Cuda version: 11.3.1
- TensorRT version: 8.0.3.4

## About this repo

- which branch/tag/commit are you using: latest (master)
- which model: yolov5s (v4.0)

## Your problem
-  cmake error and cannot build solution

I can use CMake to configure the project (with Visual Studio 15 2017), but when I generate, I receive this error:
![image](https://user-images.githubusercontent.com/90185427/132267019-53dc2781-3b42-4b62-b7dd-51d869c25b10.png)

So then, when I try to build the solution in visual studio, I get these errors:
![image](https://user-images.githubusercontent.com/90185427/132267189-d3fde73e-ff74-4f95-9524-1c9381bfeddc.png)

Any help would be greatly appreciated.

**Comment by wang-xinyu** [comment]
Cmake CUDA not configured properly.

check the windows tutorial in this repo.

**Comment by adventurousbanana** [comment]
Thanks for the response. The [run_on_windows.md](https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md) is what I have been referencing. It appears that the project can be configured with cmake just fine: 
![Screenshot 2021-09-07 201805](https://user-images.githubusercontent.com/90185427/132406601-df68e408-1ecb-4ee6-afbc-8555d48eb92f.png)

When I generate it, however, I get the warning that "CUDA_ARCHITECTURES is empty for target "yolov5."

**Comment by wang-xinyu** [comment]
warning can be ignored.

**Comment by adventurousbanana** [comment]
> warning can be ignored.

I understand, but regardless, the solution will not build in Visual Studio when following the [run_on_windows.md](https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md).

**Comment by wang-xinyu** [comment]
You need to find which warning or error results in solution not built.

tutorial is just for reference.

BTW, 4.0 cannot work with trt8.0, use latest commit instead.

**Comment by adventurousbanana** [comment]
Yes, I'm using the latest commit from the master branch/

**Comment by zchao520** [comment]
I found the same problem as you. Have you solved it?

**Comment by adventurousbanana** [comment]
> I found the same problem as you. Have you solved it?

No, despite what the README says, it does not work on Windows or there are many errors that would need to be fixed.

**Comment by adventurousbanana** [comment]
> You need to find which warning or error results in solution not built.
> 
> tutorial is just for reference.
> 
> BTW, 4.0 cannot work with trt8.0, use latest commit instead.

It doesn't work regardless.

**Comment by wang-xinyu** [comment]
Hi, I'm planning to remove everything related to Windows in this repo, you need to migrate to Windows by yourself.

**Comment by zeyad-mansour** [comment]
> Hi, I'm planning to remove everything related to Windows in this repo, you need to migrate to Windows by yourself.

That would be appropriate.

**Comment by heiybb** [comment]
> ## Env
> * GPU: gtx 1080ti
> * OS: Win10,
> * Cuda version: 11.3.1
> * TensorRT version: 8.0.3.4
> 
> ## About this repo
> * which branch/tag/commit are you using: latest (master)
> * which model: yolov5s (v4.0)
> 
> ## Your problem
> * cmake error and cannot build solution
> 
> I can use CMake to configure the project (with Visual Studio 15 2017), but when I generate, I receive this error:
> ![image](https://user-images.githubusercontent.com/90185427/132267019-53dc2781-3b42-4b62-b7dd-51d869c25b10.png)
> 
> So then, when I try to build the solution in visual studio, I get these errors:
> ![image](https://user-images.githubusercontent.com/90185427/132267189-d3fde73e-ff74-4f95-9524-1c9381bfeddc.png)
> 
> Any help would be greatly appreciated.

Are you using the VS2019?
If so, change the Platform Toolset from 2019 to 2018(v141) then you should be able to have a successful build.
Properties->General->Platform Toolset
