### ISSUE TITLE
Custom YOLOv5 Model Infers With Zero Tensor

### ISSUE THREAD

**Issue by Jacobsolawetz** [wang-xinyu/tensorrtx#712]
## Env

- GPU K80
- OS Ubuntu16.04
- Cuda 10.1
- TensorRT 6.0.1.5

## About this repo

- which branch/tag/commit are you using?
-
master - f7d224f9e4fb8ed30eb75f89063a2baef932aebb

- which model? yolov5, retinaface?

yolov5

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`

sudo ./yolov5 -s and python yolov5_trt.py

- what's your output?

Correct conversion and inference on COCO model, but on a custom model a zero tensor is returned for output = host_outputs[0]

- what output do you expect?

Custom model inference

Note: the YOLOv5 model we train for custom models is on hash `9368453` which is yolov5-v2. We edited the `yolov5.cpp` to reflect this architecture. We used the most recent tensorrtx to get the python bindings, rather than the v2 branch. The perplexing part of this bug is that the COCO model conversion and inference works well, while the custom model does not. We did change custom model params in `yololayer.h`

**Comment by Jacobsolawetz** [comment]
Update: This bug also manifests on training and converting the most recent yolov5-v5 pytorch model, with num_classes=2 and 416x416 resolution

**Comment by wang-xinyu** [comment]
You need to adapt createEngine() also.

**Comment by Jacobsolawetz** [comment]
Do you mean `build_engine` in `yolov5.cpp`? https://github.com/wang-xinyu/tensorrtx/blob/f7d224f9e4fb8ed30eb75f89063a2baef932aebb/yolov5/yolov5.cpp#L38

We edited this to reflect YOLOv5-v2, changing c3 layers to bottleneckCSP and related changes

**Comment by Jacobsolawetz** [comment]
I can confirm that training the custom model on YOLOv5-v5 with the most recent tensorrtx works - so this really is only an issue because we are trying to reach back to YOLOv5-v2 (we have many other dependencies around this). 

Would you have any other advice for getting the python bindings on YOLOv5-v2? Maybe we are trying to go about it in the wrong way?

**Comment by Jacobsolawetz** [comment]
We had left the SiLU activation function in the conv block instead of Leaky ReLU - reverting those fixed inference

Logging here in case anyone else runs into this

**Comment by wang-xinyu** [comment]
right, build_engine()
