### ISSUE TITLE
Segmentation core dumped - TensorRT

### ISSUE THREAD

**Issue by Dave0995** [wang-xinyu/tensorrtx#714]
## Env

- AGX Xavier.
- Ubuntu 18.04.
- Cuda 10.2
- TensorRT 7.0

## About this repo

- Master - commit: a7f43a304dafb3e1477154451a7d6b895901496b
- Yolov5.

## Your problem

i'm using gRPC to deploy yolov5 using tensorRT in a Jetson AGX Xavier. when the client call for the inference in the server, the comunication stop and the socket closed by segmentation fault core dumped error. Debuging the code, i found that all happens when the execution context is created in this line:

`self.cfx = cuda.Device(0).make_context()`

The weird thing is, when i use the inference engine isolated, the segmentation fault core dumped never happens.

Maybe, would you tell me if this error is new or already happened?

Thanks for your help!!!

**Comment by wang-xinyu** [comment]
I think the context should be made only once, not made each time you call inference.
