### ISSUE TITLE
Issue in OpenCV installation - The repository 'http://ppa.launchpad.net/timsc/opencv-3.3/ubuntu bionic Release' does not have a Release file.

### ISSUE THREAD

**Issue by RoboDel2020** [wang-xinyu/tensorrtx#716]
## Env
- OS, e.g. Ubuntu16.04,
- Cuda version: 10.0
- TensorRT version: 7.0

When I run "sudo add-apt-repository ppa:timsc/opencv-3.3" to install opencv, I receive this output:

ubuntu@ip-172-71-6-27:/$ sudo add-apt-repository ppa:timsc/opencv-3.3
 Based on https://launchpad.net/~sbadia/+archive/ubuntu/opencv

Compiled with ffmpeg enabled for video decoding.

Note: this repository does not include opencv_contrib which covers SIFT, SURF, etc.

Other versions and notes available here: http://www.kinatomic.com/k/opencv-ubuntu-ppa-repository.php

Due to a packaging bug, please install using: sudo apt install libopencv-dev libopencv-shape-dev libopencv-dnn-dev
 More info: https://launchpad.net/~timsc/+archive/ubuntu/opencv-3.3
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Get:1 file:/var/cuda-repo-10-0-local-10.0.130-410.48  InRelease
Ign:1 file:/var/cuda-repo-10-0-local-10.0.130-410.48  InRelease                
Get:2 file:/var/nv-tensorrt-repo-cuda10.0-trt7.0.0.11-ga-20191216  InRelease   
Ign:2 file:/var/nv-tensorrt-repo-cuda10.0-trt7.0.0.11-ga-20191216  InRelease   
Get:3 file:/var/cuda-repo-10-0-local-10.0.130-410.48  Release [574 B]          
Hit:4 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease          
Get:3 file:/var/cuda-repo-10-0-local-10.0.130-410.48  Release [574 B]          
Get:5 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 file:/var/nv-tensorrt-repo-cuda10.0-trt7.0.0.11-ga-20191216  Release [574 B]
Get:6 file:/var/nv-tensorrt-repo-cuda10.0-trt7.0.0.11-ga-20191216  Release [574 B]
Get:7 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Hit:9 https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64  InRelease
Get:10 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64  InRelease [1481 B]
Hit:11 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease     
Hit:12 https://apt.repos.neuron.amazonaws.com bionic InRelease                 
Hit:13 http://ppa.launchpad.net/timsc/opencv-3.3/ubuntu xenial InRelease
Hit:15 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu bionic InRelease       
Ign:17 http://ppa.launchpad.net/timsc/opencv-3.3/ubuntu bionic InRelease    
Err:18 http://ppa.launchpad.net/timsc/opencv-3.3/ubuntu bionic Release       
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/timsc/opencv-3.3/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

What can cause this issue?

**Comment by Deep-learning999** [comment]
OS, e.g. Ubuntu18.04,
Cuda version: .11.1
TensorRT version: 7.2.2.3

I have a similar error, can you provide a way to install opencv that can run Ubuntu 18.04

**Comment by Deep-learning999** [comment]
@wang-xinyu

**Comment by wang-xinyu** [comment]
What's the opencv version if use apt install libopencv directly in 18.04?

**Comment by Deep-learning999** [comment]
> What's the opencv version if use apt install libopencv directly in 18.04?

opencv3.4.1

**Comment by wang-xinyu** [comment]
So just install it,   it's not mandatory to use 3.3.
