### ISSUE TITLE
[Discussion] TensorRT Batching Speed scales poorly (tested YoloV5 repo) 

### ISSUE THREAD

**Issue by timothylimyl** [wang-xinyu/tensorrtx#718]
## Env

- GPU GTX1080 and GTX2080
- Ubuntu 18
- Cuda version: 11.1
- TensorRT version: 7.2.3.4

All batch testing is done over at least 20 iterations.

#### FP 16
```
Batch size 1: 1ms
Batch size 2: 2ms
Batch size 4: 4ms
Batch size 8: 8ms
Batch size 9: 9ms
```
#### FP 32
```
Batch size 1: 3ms
Batch size 2: 5ms
Batch size 4: 9ms
Batch size 8: 17-18ms
Batch size 9: 19-20ms
```

#### FP16 and FP32 (Nearly similar)
```
Batch size 1: 3-4ms
Batch size 2: 5ms-6ms
Batch size 4: 10ms
Batch size 6: 15-16ms
Batch size 8: 20-21ms
Batch size 9: 20-21ms
```

---
Observations

1. Batching is scaling exactly linearly (FP16). Theoretically, batching speed should not scale linearly due to parallel operations.

**Are there potentially anything we need to take care of to ensure proper batching operations in TensorRT?**

2. 1080 has no support for FP16, FP16 and FP32 speed is roughly the same.  You will get this error:

```
Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
```

Good idea to check CUDA compute capability of your respective GPU to see whether is FP16 supported in TensorRT.

3. The speed up in FP16 is ~2x of FP32 on GTX2080 that has support for FP16.

**Comment by wang-xinyu** [comment]
Cool, very meaningful observations.

For batching issue, can you check with NVIDIA team?

**Comment by Deep-learning999** [comment]
@timothylimyl  Can opencv install 4.0+

**Comment by timothylimyl** [comment]
@wang-xinyu , will do so, I think expectation wise it should not scale as such. please keep this thread open for now, I am curious on whether are any others facing the same issue.

@Deep-learning999 opencv has no effects on the inference speed of the model.

**Comment by dangnh0611** [comment]
Hi, any update? My tests with Yolov5-m, FP16 and batchsize in {1, 4, 8, 16} shows linearly increasing processing time too.

**Comment by timothylimyl** [comment]
Hi @wang-xinyu, seems like GPU utilisation maintains the same despite the batch size number. Do you think this could be a side effect of the way you create the TensorRT engine (not ONNX but through .wts)?  Can you check whether do you face the same issue (GPU utilisation remains the same for any batch size indicating that the inference is not batched)?

**Comment by wang-xinyu** [comment]
I don't think ONNX and API will result in different GPU utilization.  You can try ONNX though.
For batch inference, we have the same observation as yours.

**Comment by timothylimyl** [comment]
Hmm ok, I will further investigate. I do not think that it should be this way, my GPU utilisation was only at 15% so there is definitely a lot more room for usage.
