### ISSUE TITLE
An Issue when building TensorRT engine.

### ISSUE THREAD

**Issue by rose-jinyang** [wang-xinyu/tensorrtx#72]
Hello
How are you?
I've trained a yolov5 model whose input size is 640 * 640.
I've got wts file from this model.
I've compiled yolov5 sub-project.
When building a TensorRT engine with yolov5s executable, I met the following isssue.

![image](https://user-images.githubusercontent.com/47862419/86125473-4c771e80-bb0f-11ea-9231-556e5aa20f82.png)

I've found that the input size is 608 in yololayer.h

![image](https://user-images.githubusercontent.com/47862419/86125541-6ca6dd80-bb0f-11ea-9044-60aa82becd77.png)

please let me know whether this is because the input size is different.
Thanks.

**Comment by rose-jinyang** [comment]
Hi
I forgot that the number of labels in my model is 1.
Is this the reason?

**Comment by wang-xinyu** [comment]
CLASS_NUM in yololayer.h should be set to 1.

**Comment by rose-jinyang** [comment]
Thanks for your regard.
