### ISSUE TITLE
Bug in YoloV5Layer implementation

### ISSUE THREAD

**Issue by Armassarion** [wang-xinyu/tensorrtx#720]
In the enqueue method of the yolo layer implementation, you should use cudaMemsetAsync or the result might be wrong with big batch size of parallel processing.

**Comment by wang-xinyu** [comment]
@Armassarion Hi, why is that? Can you explain a bit more?

**Comment by Armassarion** [comment]
The current implementation, considering the main, is correct.
But if you use multiple TRT inference context (`engine->createExecutionContext()`) and different cudaStream with each, you'll potentially face a race condition on this part `CUDA_CHECK(cudaMemset(output + idx * outputElem, 0, sizeof(float)));` as it may memset the value at the wrong time (parallel read/write without lock).

To fix that (without impacting the current implementation), I suggest to use `CUDA_CHECK(cudaMemsetAsync(output + idx * outputElem, 0, sizeof(float), stream));`

**Comment by wang-xinyu** [comment]
OK, got it, so it will cause issue when launching multiple context.

Can you raise a PR to fix it?

**Comment by Armassarion** [comment]
I need to be able to push a branch to this repo to do a PR. I think I don't have this right

**Comment by wang-xinyu** [comment]
You can fork it firstly and then commit to that and then PR.

**Comment by Armassarion** [comment]
Sorry, I didn't really know how github works.
It's done :)

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/pull/733

**Comment by wang-xinyu** [comment]
linking to https://github.com/wang-xinyu/tensorrtx/issues/720
