### ISSUE TITLE
make yolov5 error

### ISSUE THREAD

**Issue by Deep-learning999** [wang-xinyu/tensorrtx#721]
## Env

- GPU, e.g.  RTX2080, 
- OS, e.g. Ubuntu18.04, 
- Cuda version 11.1
- TensorRT version 7.2.3

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

!rm -r TensorRTX/yolov5/build
!mkdir TensorRTX/yolov5/build
!cp detector/yolov5/yolov5s.wts TensorRTX/yolov5/build
%cd TensorRTX/yolov5/build
!cmake ..
!make
!sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
%cd ..
%cd ..

output:

/hy-nas/59/AlphaPose/TensorRTX/yolov5/build
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda (found version "11.1") 
CMake Error at /usr/share/OpenCV/OpenCVModules.cmake:192 (message):
  The imported target "opencv_shape" references the file

     "/usr/lib/x86_64-linux-gnu/libopencv_shape.so.3.4.1"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/share/OpenCV/OpenCVModules.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/share/OpenCV/OpenCVConfig.cmake:112 (include)
  CMakeLists.txt:36 (find_package)

CMake Warning (dev) in /usr/share/OpenCV/OpenCVModules.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script

    /usr/share/OpenCV/OpenCVModules.cmake

  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  /usr/share/OpenCV/OpenCVConfig.cmake:112 (include)include)
  CMakeLists.txt:36 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "AlphaPose/TensorRTX/yolov5/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
sudo: ./yolov5: command not found

**Comment by wang-xinyu** [comment]
You need to figure out OpenCV installation before building this.

**Comment by Deep-learning999** [comment]
> You need to figure out OpenCV installation before building this.

OS, e.g. Ubuntu18.04,
Cuda version: .11.1
TensorRT version: 7.2.2.3

Issue in OpenCV installation - The repository 'http://ppa.launchpad.net/timsc/opencv-3.3/ubuntu bionic Release' does not have a Release file

I have a similar error, can you provide a way to install opencv that can run Ubuntu 18.04

**Comment by huimingYU** [comment]
OS Ubuntu20.04
GPU:RTX3080
Cuda Version 11.0
TensorRT version :7.2.16
model :yolov5

When I execute the make operation as the README.md, the following problems occur：

/usr/include/opencv2/core/async.hpp:35:17: error: expected ‘;’ at end of member declaration
   35 |     ~AsyncArray() CV_NOEXCEPT;
      |                 ^
      |                  ;
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/yolov5.dir/build.make:63: CMakeFiles/yolov5.dir/calibrator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/yolov5.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
