### ISSUE TITLE
ufld result error

### ISSUE THREAD

**Issue by yueyihua** [wang-xinyu/tensorrtx#722]
## Env

- GPU, Xavier NX
- OS, Ubuntu18.04
- Cuda 10.02
- TensorRT 7

## About this repo

- which branch? master
- which model? ufld

## Your problem

- what is your command? 
  python3 pth2onnx.py (tusimple_18.pth)
  trtexec --onnx=lane.onnx --saveEngine=lane_det.engine --fp16
  ./lane_det -d  ../images
- what's your output?
  
![image](https://user-images.githubusercontent.com/10558846/133041748-dc698db3-fd4d-43dd-b7c0-8a57f6b4397c.png)

- what output do you expect?

**Comment by wang-xinyu** [comment]
check the readme of ufld in this repo, your steps are incorrect.
