### ISSUE TITLE
Error while building engine for custom model

### ISSUE THREAD

**Issue by Usama1002** [wang-xinyu/tensorrtx#723]
Hi, I am trying to build engine, but getting the following error.

> CUDA error 222 at /home/dnadrone38/src/tensorrtx/yolov5/yololayer.cu:37yolov5: /home/dnadrone38/src/tensorrtx/yolov5/yololayer.cu:37: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(int, int, int, int, const std::vector<Yolo::YoloKernel>&): Assertion `0' failed

I have followed the instructions to make changes for the custom model carefully, but still can't make sense of this error.

Please help me to understand what is going on here.

Thanks,

**Comment by wang-xinyu** [comment]
You need to go throught yololayer plugin, this is an error occurred in that.

**Comment by Usama1002** [comment]
The only issue was using 'sudo'. Try running without 'sudo'.
Thanks!
