### ISSUE TITLE
Maskrcnn R50 C4, no mask appended

### ISSUE THREAD

**Issue by ciderpark** [wang-xinyu/tensorrtx#726]
## Env

- GPU, RTX2060
- OS, Ubuntu18.04
- Cuda 10.2
- TensorRT 7.1.3.4

## About this repo

branch: master
model: mrcnn

## Your problem

command: sudo ./rcnn -d mask_c4_3x_fp16.engine ../samples m
The bbox outputs look good, but no mask is appended on the instances. I have checked the output: mask_h in rcnn.cpp, it's all zero. I also upgraded the cuda toolkit to the latest patch, but nothing has been changed.

**Comment by wang-xinyu** [comment]
@freedenS Please assist.

**Comment by freedenS** [comment]
thanks for your report, i'll take a look

**Comment by ciderpark** [comment]
> 
> 
> thanks for your report, i'll take a look

thanks

**Comment by ciderpark** [comment]
> 
> 
> thanks for your report, i'll take a look

Oh, my ...
It's all my fault, I serialized the mrcnn with arg -m instead of m, the serialized model is frcnn.
Sorry to bother you, & thanks again.
