### ISSUE TITLE
Yolov5s interference prediction box class name instead of class id

### ISSUE THREAD

**Issue by enesklf** [wang-xinyu/tensorrtx#727]
## Env

- GTX1650
- Ubuntu 18.04
- Cuda 10.2
- TensorRT 7.2

## About this repo

I'm using yolov5s

## Your problem

When doing interfenece with yolov5s.engine, prediction bbox has class id on it. I want to change it to class name. For example, it says "0" but i want it to say "Person" on top of the rectangle. What changes should I make on which file?

**Comment by Alex-Beh** [comment]
@enesklf Hi, you can define your classes like [this](https://github.com/Alex-Beh/tensorrtx/blob/1025dba98057b85d08118f4f074c4edfa488c87f/yolov5/video_inteference_yolov5.cpp#L25) and get your class in your prediction like [this](https://github.com/Alex-Beh/tensorrtx/blob/1025dba98057b85d08118f4f074c4edfa488c87f/yolov5/video_inteference_yolov5.cpp#L164).

**Comment by enesklf** [comment]
Thank you so much! I got it working with your instructions. Also, can you please tell me how to use your video_inteference_yolov5.cpp script.
