### ISSUE TITLE
Support for yolov5s-ghost.yaml

### ISSUE THREAD

**Issue by fabiozappo** [wang-xinyu/tensorrtx#728]
Hi @wwqgtxx 

I succesfully used your repo with yolov5s on my nvidia-jetson nano.
Image size is set to 640 and inference speed is much better than original yolov5, however I would like to reduce number of parameters in order to not use all the gpu memory. One option of course is to use a smaller model or to use a lower image size, however also this new model [yolov5s-ghost](https://github.com/ultralytics/yolov5/pull/4412) seems a valid option.

I was curious and then I tried to generate the engine with:

`./yolov5 -s yolov5s-ghost.wts yolov5s-ghost.engine c 0.33 0.50
`

but without success. Am I doing something wrong?

**Comment by wang-xinyu** [comment]
Probably setting 0.33 and 0.50 is not enough.

You should go through the code and do changes accordingly. Check `build_engine()`.

**Comment by Lixinixn115** [comment]
Hello, I have modified the backbone network of yolov5 to mobilenet. What files should be modified in the corresponding tensorrt? Attempted to modify common.hpp and yolov5.cpp but still can't generate engine. Look forward to your reply!
