### ISSUE TITLE
read yolov5s.engine error!  The command '/bin/sh -c sudo ./yolov5 -d yolov5s.engine ../samples' returned a non-zero code: 255 

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [wang-xinyu/tensorrtx#729]
Step 34/34 : RUN sudo ./yolov5 -d yolov5s.engine ../samples
 ---> Running in 85291e322fde
read yolov5s.engine error!
The command '/bin/sh -c sudo ./yolov5 -d yolov5s.engine ../samples' returned a non-zero code: 255

I am unable to understand error, but when I checked on web it is suggesting like memory error,
Can you please suggest @wang-xinyu

**Comment by wang-xinyu** [comment]
You cannot make others understand the error with only a error code...
