### ISSUE TITLE
hi 请教大佬这个编译问题要怎么解决

### ISSUE THREAD

**Issue by 1senlin** [wang-xinyu/tensorrtx#73]
/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(56): error: not a class or struct name

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(64): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(69): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(71): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(73): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(75): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(77): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(79): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(81): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(83): error: identifier "PluginTensorDesc" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(83): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(87): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(89): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(91): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(93): error: identifier "IPluginV2IOExt" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(93): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(95): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(97): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(99): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(101): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(103): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(105): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(108): error: identifier "PluginTensorDesc" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(108): error: identifier "PluginTensorDesc" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(108): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(110): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(84): error: name followed by "::" must be a class or namespace name

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(134): error: identifier "IPluginV2IOExt" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(134): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::createPlugin"

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(134): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(136): error: identifier "IPluginV2IOExt" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(136): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::deserializePlugin"

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.h(136): error: member function declared with "override" does not override a base class member

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.cu(110): error: identifier "PluginTensorDesc" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.cu(110): error: identifier "PluginTensorDesc" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.cu(138): error: identifier "IPluginV2IOExt" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.cu(254): error: identifier "IPluginV2IOExt" is undefined

/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yololayer.cu(261): error: identifier "IPluginV2IOExt" is undefined

38 errors detected in the compilation of "/tmp/tmpxft_0000902d_00000000-6_yololayer.cpp1.ii".
CMake Error at yololayer_generated_yololayer.cu.o.Debug.cmake:279 (message):
  Error generating file
  /apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/build/CMakeFiles/yololayer.dir//./yololayer_generated_yololayer.cu.o

make[2]: *** [CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o] Error 1
make[1]: *** [CMakeFiles/yololayer.dir/all] Error 2
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
tensorrt装了吗，什么版本，

**Comment by 1senlin** [comment]
tensorrt5.0的

**Comment by 1senlin** [comment]
> tensorrt装了吗，什么版本，

装了tensorrt5.0的

**Comment by wang-xinyu** [comment]
我用的7.0，有一些API定义可能不一样

**Comment by yishunzhijian** [comment]
请问你用tensorrt5.0编译成功了吗？

**Comment by wang-xinyu** [comment]
请用6和7，   5需要自己修改调整api
