### ISSUE TITLE
retinafaceAntiCov fail to run with retinaface_trt.py

### ISSUE THREAD

**Issue by ttducqt** [wang-xinyu/tensorrtx#731]
## Env
- GPU, 1650
- OS, 20.04
- Cuda version 11.2
- TensorRT version 7.2
- Python 3.8

Sorry for not good at TensorRT
I try to use retinaface_trt.py from retinaface/ to run with retinafaceAntiCov.engine, but it cant work, please help. 

Edited these line:
PLUGIN_LIBRARY = 'libmyplugins.so'
engine_file_path = 'retinafaceAntiCov.engine'

Output: (error)
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin Decode_TRT version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.

Thanks for reading

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/f7d224f9e4fb8ed30eb75f89063a2baef932aebb/retinaface/decode.h#L117
Check this line, which helps find plugin.

**Comment by ttducqt** [comment]
After adding the line bellow into decode.h and re-make
REGISTER_TENSORRT_PLUGIN(DecodePluginCreator);

This is the new error
-->self._handle = _dlopen(self._name, mode)
OSError: build/libmyplugins.so: undefined symbol: getPluginRegistry

**Comment by wang-xinyu** [comment]
Check the required .h files
and required linking libs in cmake

**Comment by ttducqt** [comment]
I have ported cpp to .py successfully. May i pull request ?

**Comment by wang-xinyu** [comment]
@ttducqt Sure, raise a PR, we can review it together.
