### ISSUE TITLE
Mask-RCNN FPN implementation question

### ISSUE THREAD

**Issue by ciderpark** [wang-xinyu/tensorrtx#734]
Hi, I'm trying to implement the Mask-RCNN FPN model. Here are the questions:
After FPNs and five RPNs, there are several operators, like CollectRpnProposals, DistributeFpnProposals and BatchPermutation which are implemented in caffe2. Should I implement them in plugins? If yes, any suggestions?

**Comment by wang-xinyu** [comment]
@freedenS Please help.

**Comment by freedenS** [comment]
in my opinion, you don't need to implement these ops.
you just need to implement fpn layer and merge assign_box_to_level into RoiAlign plugin.

**Comment by nsalimi** [comment]
@freedenS is possible for your to implement this to the repo?

**Comment by freedenS** [comment]
sorry, this part of code belongs to my company.

**Comment by ciderpark** [comment]
> 
> 
> in my opinion, you don't need to implement these ops.
> you just need to implement fpn layer and merge assign_box_to_level into RoiAlign plugin.

Got that, thanks.

**Comment by nsalimi** [comment]
@ciderpark have you had any progress with this?

**Comment by ciderpark** [comment]
> @ciderpark have you had any progress with this?

I have completed it, following the "merge assign_box_to_level into RoiAlign plugin" suggestion.

**Comment by nsalimi** [comment]
@ciderpark So you also got the model running with predictions?  Can you share the implementation of it?

**Comment by ciderpark** [comment]
> 
> 
> @ciderpark So you also got the model running with predictions? Can you share the implementation of it?

Yes. Sorry, this part of code also belongs to my company.
