### ISSUE TITLE
/usr/bin/ld: 找不到 -lnvinfer

### ISSUE THREAD

**Issue by ihongxx** [wang-xinyu/tensorrtx#735]
- GPU : RTX2060
- OS : Ubuntu 20.04.2 LTS
- Cuda: 11.1
- TensorRT : 7.2.3.4（tar）
- gcc version 7.5.0
- gcc version 7.5.0

(torch1.7_yolov5) hxx@hxx-System-Product-Name:/home/data/PycharmProjects/yolov5_tensorRT/tensorrtx/yolov5/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda-11.1 (found version "11.1") 
-- Found OpenCV: /usr (found version "4.2.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/data/PycharmProjects/yolov5_tensorRT/tensorrtx/yolov5/build

(torch1.7_yolov5) hxx@hxx-System-Product-Name:/home/data/PycharmProjects/yolov5_tensorRT/tensorrtx/yolov5/build$ make
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
/home/data/PycharmProjects/yolov5_tensorRT/tensorrtx/yolov5/yololayer.h(86): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

/home/data/PycharmProjects/yolov5_tensorRT/tensorrtx/yolov5/yololayer.h(86): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const bool *, const bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::YoloLayerPlugin::configurePlugin" -- virtual function override intended?

Scanning dependencies of target myplugins
[ 40%] Linking CXX shared library libmyplugins.so
/usr/bin/ld: 找不到 -lnvinfer
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/myplugins.dir/build.make:79：libmyplugins.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:105：CMakeFiles/myplugins.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

CMakeList.txt中加入了：
include_directories(***/TensorRT-7.2.3.4/include)
link_directories(***/TensorRT-7.2.3.4/lib)

**Comment by wang-xinyu** [comment]
add the tensorrt lib dir to $LD_LIBRARY_PATH

**Comment by ihongxx** [comment]
I have added trt path in environment variables：

export TRT_PATH=/TensorRT-7.2.3.4
export PATH=$PATH:$TRT_PATH/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRT_PATH/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRT_PATH/targets/x86_64-linux-gnu/lib

/usr/bin/ld: 找不到 -lnvinfer

**Comment by ihongxx** [comment]
已解决，需要将以下内容添加到CMakeList.txt中
include_directories(/home/data/PycharmProjects/TensorRT-7.2.3.4/include/)
link_directories(/home/data/PycharmProjects/TensorRT-7.2.3.4/lib/)

添加的位置需要放在以下内容前，我的错误是因为将上面内容直接放在CMakeList.txt最后了
cuda_add_library(myplugins SHARED ${PROJECT_SOURCE_DIR}/yololayer.cu)
target_link_libraries(myplugins nvinfer cudart)
