### ISSUE TITLE
arguments not right!

### ISSUE THREAD

**Issue by XiaoJiNu** [wang-xinyu/tensorrtx#736]
## Env

- GPU, 3090
- OS, Win10, 
- Cuda version 11.1
- TensorRT version  TensorRT-8.0.3.4.Windows10.x86_64.cuda-11.3.cudnn8.2

## About this repo

- which branch/tag/commit are you using?
  - I use the newest version which was downloaded by git clone git://github.com/wang-xinyu/tensorrtx.git
- which model? yolov5, retinaface?
  - yolov5
 
## Your problem
I have compiled successfully as figure 1 shown but when I run yolov5.exe -s there appears **arguments not right!**

![image](https://user-images.githubusercontent.com/30587645/134757626-79bf3cc9-d97e-43be-b690-6ff24a6c0535.png)
                                                                                                figure 1

![image](https://user-images.githubusercontent.com/30587645/134757472-7a530c5f-0c6f-446f-b63b-3a635d058d94.png)
                                                                                                  figure 2

**Comment by wang-xinyu** [comment]
Arguments not right means arguments not right..
Check the readme.
