### ISSUE TITLE
yolov5转tensorrt后mAP下降 

### ISSUE THREAD

**Issue by wangxihuiok** [wang-xinyu/tensorrtx#737]
YOLOv5s 官方pytorch代码给出的mAP为36.7%，该模型转换为trt（fp32）后的mAP下降为34.47%，经测试其他yolov5模型也有2%左右的mAP下降，请问mAP下降的原因是什么？如何修改才能得到官方的mAP值？

**Comment by wang-xinyu** [comment]
It is normal to have 2% drop of mAP. Refer to here https://github.com/wang-xinyu/tensorrtx/pull/573

**Comment by paranoidai** [comment]
> It is normal to have 2% drop of mAP. Refer to here #573

是代码有bug吧？
yolov5_trt.py 的
https://github.com/wang-xinyu/tensorrtx/blob/9fefbed77f2f8166cacc9d4063102072f501e653/yolov5/yolov5_trt.py#L154
这一行开始，从显存取结果只取了index为0的，对应yolo的结果是只取了stride为8的？

**Comment by wang-xinyu** [comment]
@paranoidai  No, check yololayer plugin code.
