### ISSUE TITLE
How to convert the .pth model file of arcface-toch training into tensorrt.

### ISSUE THREAD

**Issue by create-li** [wang-xinyu/tensorrtx#739]
In the project, only the mxnet model is provided to be converted into tenorrt. How to convert arcface torch using tenrrtx project

**Comment by wang-xinyu** [comment]
Not supported. You can refer to arcface-mxnet in this repo to implement arcface-pytorch by yourself.

**Comment by create-li** [comment]
Thanks，Is there a tutorial for generating wts format?  Is there a tutorial for generating WTS format? Does this project support CUDA 10.0 and tensorrt 6.0 ？

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/getting_started.md#the-wts-content-format
Check this tutorial for wts format, and refer to any gen_wts.py for generating wts.

I never tested with 6.0, you can try though.

**Comment by create-li** [comment]
Thank you very much

**Comment by create-li** [comment]
thank you
