### ISSUE TITLE
求大佬指点error: invalid initialization of reference of type ‘Yolo::Detection&’ from expression of type ‘const Yolo::Detection’

### ISSUE THREAD

**Issue by 1senlin** [wang-xinyu/tensorrtx#74]
error: invalid initialization of reference of type ‘Yolo::Detection&’ from expression of type ‘const Yolo::Detection’
环境解决了 又遇到这个问题 求大佬指点

**Comment by wang-xinyu** [comment]
有改代码吗？

**Comment by 1senlin** [comment]
> 有改代码吗？

没有改代码 就是make的时候报的错 我再贴详细点 麻烦大佬看下
p/yolov3-spp.cpp:7:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Tp = Yolo::Detection; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Size = long int; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<Yolo::Detection*, std::vector<Yolo::Detection> >; _Compare = bool (*)(Yolo::Detection&, Yolo::Detection&)]’
/apsarapangu/disk3/senlin.csl/tensorrtx/yolov3-spp/yolov3-spp.cpp:121:48:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: invalid initialization of reference of type ‘Yolo::Detection&’ from expression of type ‘const Yolo::Detection’
    while (__comp(*__first, __pivot))
                                   ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/yolov3-spp.dir/yolov3-spp.cpp.o] Error 1
make[1]: *** [CMakeFiles/yolov3-spp.dir/all] Error 2
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
看着像gcc版本的问题，是ubuntu16.04吗

**Comment by 1senlin** [comment]
> 看着像gcc版本的问题，是ubuntu16.04吗

cent os

**Comment by wang-xinyu** [comment]
有可能是gcc版本问题，ubuntu16.04是gcc 5.4.0，自己看看怎么解决吧。。。

**Comment by 1senlin** [comment]
> 有可能是gcc版本问题，ubuntu16.04是gcc 5.4.0，自己看看怎么解决吧。。。

换成gcc5.4.0 了ok的 然后会报/usr/bin/ld: cannot find -lnvinfer
collect2: error: ld returned 1 exit status
make[2]: *** [yolov3-spp] Error 1
make[1]: *** [CMakeFiles/yolov3-spp.dir/all] Error 2
make: *** [all] Error 2

但是bashrc 环境变量 和到tensorrt lib目录下 ln-s libnvinfer.so.7.0.0 libnvinfer.so. 还是不行

**Comment by Stephenfang51** [comment]
> > 有可能是gcc版本问题，ubuntu16.04是gcc 5.4.0，自己看看怎么解决吧。。。
> 
> 换成gcc5.4.0 了ok的 然后会报/usr/bin/ld: cannot find -lnvinfer
> collect2: error: ld returned 1 exit status
> make[2]: *** [yolov3-spp] Error 1
> make[1]: *** [CMakeFiles/yolov3-spp.dir/all] Error 2
> make: *** [all] Error 2
> 
> 但是bashrc 环境变量 和到tensorrt lib目录下 ln-s libnvinfer.so.7.0.0 libnvinfer.so. 还是不行

同样的问题， 看着项目感觉不错， 但其实在安装的部分还是很多坑

**Comment by wang-xinyu** [comment]
@Stephenfang51 跟我一样的环境，也有问题？

**Comment by zloss** [comment]
我修改common.hpp中的cmp函数，然后编译就通过了，你也可以试一下。
// 原来的cmp
bool cmp(Yolo::Detection& a, Yolo::Detection& b) {
    return a.conf > b.conf;
}
// 修改后的cmp
bool cmp(const Yolo::Detection& a, const Yolo::Detection& b) {
    return a.conf > b.conf;
}

**Comment by zloss** [comment]
我在编译yolov5的时候也遇到了同样的问题，不过修改了cmp函数，然后编译就通过了，你可以试一下
Yolov5的话cmp函数在common.hpp中，yolov4的话在yolov4.cpp中
// 原来的cmp
bool cmp(Yolo::Detection& a, Yolo::Detection& b) {
    return a.conf > b.conf;
}
// 需改后的cmp
bool cmp(const Yolo::Detection& a,const Yolo::Detection& b) {
    return a.conf > b.conf;
}

**Comment by wang-xinyu** [comment]
@zloss 是centos吗？
