### ISSUE TITLE
Resnet50 inference result seems like not right?

### ISSUE THREAD

**Issue by swordnosword** [wang-xinyu/tensorrtx#742]
## Env

- GPU, RTX3070
- OS, Ubuntu18.04
- Cuda version, 11.1
- TensorRT version, 7.2.3

## About this repo

- branch: master
- model: resnet50

## Your problem
I modify your source code in main function to inference on coco val images, as following:
`int main()
{
    // create a model using the API directly and serialize it to a stream
    char* trtModelStream{ nullptr };
    size_t size{ 0 };
    std::string engine_file = "/media/xy/data/workspace/resnet_deploy/resnet/build/resnet50.engine";
    cv::Mat image = cv::imread("/media/xy/data/datasets/others/hen.jpg");

    std::ifstream file(engine_file, std::ios::binary);
    if (file.good()) {
        file.seekg(0, file.end);
        size = file.tellg();
        file.seekg(0, file.beg);
        trtModelStream = new char[size];
        assert(trtModelStream);
        file.read(trtModelStream, size);
        file.close();
    }

    // Subtract mean from image
    static float data[3 * INPUT_H * INPUT_W];
    cv::Mat image_pro;
    cv::resize(image, image_pro, cv::Size(INPUT_H, INPUT_W));
    for (int i = 0; i < 3 * INPUT_H * INPUT_W; i++)
        data[i] = static_cast<float>(*(image_pro.data + i));
    ;

    IRuntime* runtime = createInferRuntime(gLogger);
    assert(runtime != nullptr);
    ICudaEngine* engine = runtime->deserializeCudaEngine(trtModelStream, size, nullptr);
    assert(engine != nullptr);
    IExecutionContext* context = engine->createExecutionContext();
    assert(context != nullptr);
    delete[] trtModelStream;

    // Run inference
    static float prob[OUTPUT_SIZE];
    for (int i = 0; i < 100; i++) {
        auto start = std::chrono::system_clock::now();
        doInference(*context, data, prob, 1);
        std::unordered_map<float, int> prob_index;
        for (int j = 0; j < OUTPUT_SIZE; ++j) {
            prob_index[prob[j]] = j;
        }
        std::sort(prob, prob + OUTPUT_SIZE, [](int x, int y) { return x > y; });
        for (int a = 0; a < 10; ++a) {
            int label = prob_index[prob[a]];
            std::cout << "topk label: " << label << std::endl;
            std::cout << "topk prob: " << prob[a] << std::endl;
        }
        auto end = std::chrono::system_clock::now();
        std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;
    }

    // Destroy the engine
    context->destroy();
    engine->destroy();
    runtime->destroy();

    // Print histogram of the output distribution
    std::cout << "\nOutput:\n\n";
    for (unsigned int i = 0; i < 10; i++) {
        std::cout << prob[i] << ", ";
    }
    std::cout << std::endl;
    for (unsigned int i = 0; i < 10; i++) {
        std::cout << prob[OUTPUT_SIZE - 10 + i] << ", ";
    }
    std::cout << std::endl;

    return 0;
}`

## output
`[09/28/2021-12:13:55] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.3.0 but loaded cuBLAS/cuBLAS LT 11.2.1
[09/28/2021-12:13:55] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.3.0 but loaded cuBLAS/cuBLAS LT 11.2.1
topk label: 818
topk label: 920
topk label: 968
topk label: 862
topk label: 819
topk label: 530
topk label: 437
topk label: 779
topk label: 555
topk label: 731
409ms

Output:
1393.94, 1009.94, 930.881, 920.683, 914.259, 905.434, 864.636, 861.872, 843.776, 832.948, 
-639.849, -645.013, -652.712, -663.874, -664.02, -668.858, -679.027, -702.735, -724.648, -788.095,  `

## what I want:
I input one image of bear, but the result is spotlight, do you have any idea about this. Or can you please test your inferce code on coco val datasets to see the result?

**Comment by wang-xinyu** [comment]
Seems preprocessing is missed.

**Comment by swordnosword** [comment]
OK, I have fixed this problem, thanks for your advice. @wang-xinyu

**Comment by dongdengwei** [comment]
I also have encountered this problem, how can I solve this?

**Comment by sctrueew** [comment]
@wang-xinyu Hi,

I used this code for inferring an image but the prob is not correct:


const auto OUTPUT_SIZE = global_params.num_classes;
	// Run inference
	float* prob = new float[OUTPUT_SIZE];
	for (int i = 0; i < 1; i++) {
		auto start = std::chrono::system_clock::now();
		doInference(*context, data, prob, 1, global_params);
		std::unordered_map<float, int> prob_index;
		for (int j = 0; j < OUTPUT_SIZE; ++j) {
			prob_index[prob[j]] = j;
		}
		std::sort(prob, prob + OUTPUT_SIZE, [](int x, int y) { return x > y; });
		for (int a = 0; a < 5; ++a) {
			int label = prob_index[prob[a]];
			std::cout << "topk label: " << classes[label] << std::endl;
			std::cout << "topk prob: " << prob[a] << std::endl;
		}
		auto end = std::chrono::system_clock::now();
		std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << "ms" << std::endl;
	}

### Result:

topk label: 388 giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca
**topk prob: 8.92626**
topk label: 294 brown bear, bruin, Ursus arctos
**topk prob: 3.7125**
topk label: 296 ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus
**topk prob: 3.29639**
topk label: 387 lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens
**topk prob: 3.90335**
topk label: 362 badger
**topk prob: 2.43562**

### The prob is not a percentage
