### ISSUE TITLE
yolov5 tensorrt fp32 model resulted big map loss

### ISSUE THREAD

**Issue by rui-shen-afk** [wang-xinyu/tensorrtx#743]
I used the master branch of this repo to quantize my yolov5m6 model, and tested the mAP. 

AP of most classes had a reasonable drop under 5% after converting the pytorch pt file to wts file, and finally to tensorrt **fp32** engine file. 

**However one class, the smallest one compared to others, had an unusual drop in AP for about 20%.** 

The accuracy performances of fp32 and fp16 model are almost identical, and int8 quantization adds additional 5 - 10% drop in AP as anticipated. 

So how would one explain such difference between the a tensorrt **fp32** model and a pytorch model? Usually they produce almost identical results.

I used the yolov5 official repo to calculate mAP and set the same NMS_THRESH and CONF_THRESH in tensorrtx accordingly.

Any advice is highly appreciated!

-  Xavier NX
- Ubuntu18.04
- Cuda 10.2
- TensorRT 7.1.3

**Comment by wang-xinyu** [comment]
refer to https://github.com/wang-xinyu/tensorrtx/pull/573
Normally, fp32/fp16 will have 2% drop for mAP.

**Comment by ahong007007** [comment]
@rui-shen-afk Can you share your code? The code for calculating MAP after yolov5 turns Tensor trt?
Thank you!
