### ISSUE TITLE
yolov5 error: ISO C++ forbids declaration of ‘setPrecison’ with no type [-fpermissive]

### ISSUE THREAD

**Issue by Albert337** [wang-xinyu/tensorrtx#746]
when i try to compile the yolov5 project,i meet the eroor 
` error: ISO C++ forbids declaration of ‘setPrecison’ with no type [-fpermissive]
 Int8EntropyCalibrator2::setPrecison (int batchsize, int input_w, int input_h, const char* img_dir, const char* calib_table_name, const char* input_blob_name, bool read_cache)
                                                                                                                                                                              ^
compilation terminated due to -Wfatal-errors.
CMakeFiles/yolov5.dir/build.make:81: recipe for target 'CMakeFiles/yolov5.dir/calibrator.cpp.o' failed
make[2]: *** [CMakeFiles/yolov5.dir/calibrator.cpp.o] Error 1
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
`
but i cannot solve it,is there any suggestions?thanks!

**Comment by wang-xinyu** [comment]
Follow the issue template.
