### ISSUE TITLE
哪位有yolov5转trt后的计算MAP的代码？

### ISSUE THREAD

**Issue by woshituobaye** [wang-xinyu/tensorrtx#750]
看了那个coco的计算MAP的代码  需要预测结果的标签txt。在yolov5_trt.py里面没有生成标签txt的代码。因此没法直接用。

**Comment by ahhhxxx** [comment]
大佬你有代码吗 我听说有人带 但是他没有给我

**Comment by ahhhxxx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ahhhxxx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
