### ISSUE TITLE
Problem with converting to .engine

### ISSUE THREAD

**Issue by Adblu** [wang-xinyu/tensorrtx#752]
## Env
XavierNX.
Ubuntu18.04
- Cuda version 10.2
- TensorRT version 7.1.3-1+cuda10.2

## About this repo
- which model? yolov5m taken from [here](https://github.com/enazoe/yolo-tensorrt/blob/master/yolov5_tutorial.md) yolov5m-v3.0

When running:
```
sudo ./yolov5 -s yolov5mv2.wts yolov5mv2.engine m
```
I'm getting
```
yolov5/common.hpp:99: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `count > 0 && "Invalid weight map file."' failed.
```

What might be wrong ??

**Comment by wang-xinyu** [comment]
Can you check the readme of yolov5 in this repo? And see where to get the yolov5 model.
