### ISSUE TITLE
INT8 calibration for yolov5 lowers accuracy significantly

### ISSUE THREAD

**Issue by kbegiedza** [wang-xinyu/tensorrtx#753]
## Env

- Ubuntu 20.04.3 LTS
- Driver Version: 470.57.02
- CUDA Version: 11.4
- TensorRT: 7.2.2-1
## About this repo

- which branch/tag/commit are you using?
`master`

- which model? yolov5, retinaface?
`yolov5m`

## Your problem

I've created my `*.engine` from previously trained `*.pt`.
For `INT8` I've used ~10% of dataset to calibrate model.

Model converted with `FP16` precision outputs correct classes with high accuracy, but 
model with `INT8` had very poor accuracy (detections with probability < `0.1`).

**Comment by wang-xinyu** [comment]
AFAIK, tensorrt has bad int8 performance on layers like SiLU.

You can try old version like tensorrt7.0.
Or try another model with only RELU as activation.

**Comment by Lenan22** [comment]
Please refer to our open source quantization tool ppq, the quantization result is better than the quantization tool that comes with tensorrt, almost the same as the float32 model. https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md
