### ISSUE TITLE
run yolov5 build error

### ISSUE THREAD

**Issue by Deep-learning999** [wang-xinyu/tensorrtx#754]
%cd TensorRTX/yolov5/build

!sudo cmake ..
!sudo make
#sudo ./yolov5 -s [.wts] [.engine] [s/m/l/x/s6/m6/l6/x6 or c/c6 gd gw]  // serialize model to plan file
#sudo ./yolov5 -d [.engine] [image folder]  // deserialize and run inference, the images in [image folder] will be processed.
#For example yolov5s
!sudo ./yolov5 -s AlphaPose/detector/yolov5/yolov5s.wts AlphaPose/detector/yolov5/yolov5s.engine s
#sudo ./yolov5 -d yolov5s.engine ../samples
#// For example Custom model with depth_multiple=0.17, width_multiple=0.25 in yolov5.yaml
#sudo ./yolov5 -s yolov5_custom.wts yolov5.engine c 0.17 0.25
#sudo ./yolov5 -d yolov5.engine ../samples
%cd ..
%cd ..

rm: invalid option -- 'y'
Try 'rm --help' for more information.
TensorRTX/yolov5/build
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda (found version "11.1") 
-- Found OpenCV: /usr/local (found version "4.5.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: TensorRTX/yolov5/build
[ 20%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
In file included from TensorRTX/yolov5/yololayer.cu:4:0:
TensorRTX/yolov5/yololayer.h:6:10: fatal error: NvInfer.h: No such file or directory
 #include <NvInfer.h>
          ^~~~~~~~~~~
compilation terminated.
CMake Error at myplugins_generated_yololayer.cu.o.Debug.cmake:219 (message):
  Error generating
TensorRTX/yolov5/build/CMakeFiles/myplugins.dir//./myplugins_generated_yololayer.cu.o

CMakeFiles/myplugins.dir/build.make:63: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
sudo: ./yolov5: command not found TensorRTX

**Comment by Deep-learning999** [comment]
The above has been solved, and a new problem has appeared 

lease wait for a while...
Build engine successfully!
could not open plan output file

**Comment by Deep-learning999** [comment]
Already resolved

**Comment by sicarioakki** [comment]
> Can share how to resolve the issue of "Nvinfer" not found? Thanks

I resolved this by simply reinstalling Tensorrt. Hope that helps.

**Comment by viwe-monai** [comment]
如果在build路径下cmake ..，然后make -j16，发现编译报错，缺少了什么文件，可以在build的上一级目录的CMakeLists.txt中，修改cuda、tensorRT、Opencv的路径，然后删除build文件夹生成的文件，重新cmake ..，然后make -j16
![image](https://github.com/user-attachments/assets/e7038e5c-9c6e-4840-ba95-91c46b2f35a5)
