### ISSUE TITLE
no improvement using the .engine file for maskrcnn

### ISSUE THREAD

**Issue by andreeatulbure** [wang-xinyu/tensorrtx#755]
- Xavier AGX
- Ubuntu 18.04
- Cuda 10.2.89
- TensorRT 7.1.0.16

I am using the master branch and converted my maskrcnn to trt model. I managed to do that successfully, but unfortunately I have no speedup and run currently at 2fps. Did you by any chance test the .engine files which you get by running the example from the rcnn folder on a Jetson and did you manage to get a speedup? I tried to use also your yolov5 conversion code and that worked well and I managed to get a nice speedup, running currently at 25 fps

Thanks

**Comment by wang-xinyu** [comment]
Hi, refer to https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn#latency tested with 2080Ti,
AGX will be much slower than 2080ti.
cc: @freedenS

**Comment by andreeatulbure** [comment]
Thanks for your fast reply! I see that maskrcnn  with fp16 (what I am using currently) runs at about 20fps on a 2080ti. I am aware that on the jetson it will be slower, but 2fps is I think too slow. I saw other github repos in which they reported about 10fps for the jetson running maskrcnn with TRT. This is what I expected as well and don‘t know where it went wrong

**Comment by freedenS** [comment]
you'd better to chose faster model(such as yolo, nanodet) if you want a real time model on jetson.
there is a huge gap between jetson and 2080ti.
this version of maskrcnn is resnet50-C4 which is about 4x slower than fpn.

**Comment by andreeatulbure** [comment]
Do you mean that in the trt implementation the resnet fpn is 4 times slower then the resnet c4 maskrcnn? @freedenS

**Comment by freedenS** [comment]
resnet50-fpn is about 30ms with 2080ti

**Comment by andreeatulbure** [comment]
With fp32?

**Comment by freedenS** [comment]
yep
