### ISSUE TITLE
create mask rcnn tensorRT engine error!

### ISSUE THREAD

**Issue by jcyhcs** [wang-xinyu/tensorrtx#757]
hi,professor:
i use rcnn to create mask-rcnn tensorRT engine , with command: ./rcnn -s faster.wts mask.engine m, then i got error:
rcnn/MaskRcnnInferencePlugin.h:57: nvinfer1::MaskRcnnInferencePlugin::MaskRcnnInferencePlugin(int, int, int): Assertion `num_classes > 0' failed.
Aborted (core dumped)
oh, please help me!

**Comment by wang-xinyu** [comment]
I think you got the wrong .wts file, pls follow the readme and try again.
cc: @freedenS
