### ISSUE TITLE
generate unet wts file error!

### ISSUE THREAD

**Issue by jcyhcs** [wang-xinyu/tensorrtx#760]
hi,professor:
i use your gen_wts.py to generate unet wts file, but i got error:
 >>python3 gen_wts.py
Traceback (most recent call last):
  File "gen_wts.py", line 36, in <module>
    main()
  File "gen_wts.py", line 11, in main
    net = net.to('cuda:0')
AttributeError: 'collections.OrderedDict' object has no attribute 'to'

i'm not good at python, so please help me!  
torch                   1.9.0
torchsummary            1.5.1
torchvision             0.10.0

ubuntu 18.04 | x86-64

**Comment by wang-xinyu** [comment]
Try older torch, like 1.3.
