### ISSUE TITLE
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCompilerId.cmake:412 (message):   No CUDA toolset found.

### ISSUE THREAD

**Issue by python1806huqiugen** [wang-xinyu/tensorrtx#768]

**Comment by dota2015** [comment]
从C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\extras\visual_studio_integration\MSBuildExtensions
拷贝文件
CUDA 11.4.props 
CUDA 11.4.targets
CUDA 11.4.xml
Nvda.Build.CudaTasks.v11.4.dll到
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations
