### ISSUE TITLE
yolov5-v6 tensorrt model output incorrect result

### ISSUE THREAD

**Issue by hariag** [wang-xinyu/tensorrtx#769]
## pytorch output:
![zidane](https://user-images.githubusercontent.com/2148771/137840073-2c1ee25a-0f7d-489a-b536-99bd1fafe710.jpg)

## command  line
```


./yolov5 -s ../yolov5s.wts yolov5s.engine s
./yolov5 -d yolov5s.engine ../test/
```

![_zidane](https://user-images.githubusercontent.com/2148771/137841456-edf3821e-e7ab-4adc-860e-872367bcf222.jpg)

## issue
class  tie  lost, confidence of object not stable.

perhaps due to missing "output" node.

**Comment by wang-xinyu** [comment]
We are not using onnx in this repo. You can check the code if interested.
