### ISSUE TITLE
Scaling missing for yolo layers

### ISSUE THREAD

**Issue by JoeCool90** [wang-xinyu/tensorrtx#77]
Hi, I think the scaling is missing from the yolo layers.  For example, in yolov4 cfg there is this line: scale_x_y = 1.2 but I don't see it in the code anywhere.

Sorry if I missed it.

**Comment by wang-xinyu** [comment]
What does the `scale_x_y` means?

**Comment by JoeCool90** [comment]
Hi, sorry for the delay.  See the yolo v4 code here: [https://github.com/AlexeyAB/darknet/blob/2fca3c399b722934d24b9b86963215fc40ac6bcd/src/yolo_layer.c#L914](https://github.com/AlexeyAB/darknet/blob/2fca3c399b722934d24b9b86963215fc40ac6bcd/src/yolo_layer.c#L914)

**Comment by wang-xinyu** [comment]
@JoeCool90 I was using https://github.com/ultralytics/yolov3 to load yolov4 model and run.
It seems not using the `scale_x_y` in yololayer.

**Comment by JoeCool90** [comment]
Ah, looking back it appears it wasn't in yolo3.

The link I posted is the reference for yolo4 where it has been introduced.
