### ISSUE TITLE
yolov5-v6 tensorrt error

### ISSUE THREAD

**Issue by bobo0810** [wang-xinyu/tensorrtx#771]
## Env

- GPU : RTX 2080Ti
- OS : Ubuntu20.04
- Cuda version : 11.2
- TensorRT version : 7.2.2-1+cuda11.1

## About this repo

The original yolov5s.pt successfully converted tensorrt, but an error occurred after the modification.

## My problem
|     | yololayer.h  | make | ./yolov5 -s |
|  ----  | ----  |----  |----  |
| Original  |  |  ![](https://user-images.githubusercontent.com/26057879/137865467-fe95dbef-8d97-48b2-af86-2ea990950b71.png)| ![](https://user-images.githubusercontent.com/26057879/137865806-ff4f4065-7016-40d2-89a7-b4904b9a38f9.png)| 
| Modify  | CLASS_NUM 80->2    <br>  INPUT_H/W 640->512| ![](https://user-images.githubusercontent.com/26057879/137865647-73f046fc-32ac-46f3-a388-baef00409b34.png) |![](https://user-images.githubusercontent.com/26057879/137865999-5ee0a570-9396-4688-a051-f1540d35c974.png)| 

An error occurred in the process after the modification. What is the reason? Thanks~ @wang-xinyu

**Comment by bobo0810** [comment]
> Can you clean the `build` folder and re-try?

After several attempts, the engine file can be generated normally. However, the inference result is incorrect

./yolov5 -d 
 - ![](https://user-images.githubusercontent.com/26057879/137874092-608fb730-9bef-42eb-84ff-c72d82d0c968.png)

 python yolov5_trt.py
- The inference result is empty

**Comment by wang-xinyu** [comment]
Did you rebuild everything after changing input size?

**Comment by aboy2018** [comment]
I guess that *.wts is wrong.because "fc->fields[1].length" is 0

**Comment by aboy2018** [comment]
> Did you rebuild everything after changing input size?

yes, I rm build' files ,but error still here

**Comment by aboy2018** [comment]
我训练采用的是是yolov5 v6.0版本，tensorrt是最新分支

**Comment by wang-xinyu** [comment]
Do not use master branch of pytorch yolov5, use its release tag, 

and also compare your own model with the official one layer by layer.

**Comment by aboy2018** [comment]
> print(model) and compare,
> 
> It's meaningless to compare onnx.

我发现自己训练的模型生成的wts没有model.24.anchor_grid这一层，应该怎么解决呢，是要在训练过程中保存模型添加这个信息吗，这个信息怎么添加呢

**Comment by wang-xinyu** [comment]
@aboy2018  Can you figure out why the official model has `model.24.anchor_grid` ?

**Comment by aboy2018** [comment]
这个问题，我解决了，是因为开源模型中有model.24.anchor_grid这一层，而自己训练的模型中没有保存这层参数，只需要在gen_wts.py文件中人为添加这一层的参数即可

**Comment by ajkdrag** [comment]
> > > What did you modify in order to bypass this error?
> > 
> > 
> > https://github.com/bei91/yolov5-onnx-tensorrt/blob/master/demo/Processor.py
> 
> Could you expand a little bit? Im more interested in how the .engine file was built without the CUDA assertion error.

Just comment the cuda_check line in .cu

**Comment by aboy2018** [comment]
> > 这个问题，我解决了，是因为开源模型中有model.24.anchor_grid这一层，而自己训练的模型中没有保存这层参数，只需要在gen_wts.py文件中人为添加这一层的参数即可
> 
> Is the inference result correct after the repair? In my experiment, there were a lot of error boxes in the results, which were different from the Pytorch results.

Do you change anchor value? It should be change array value.

**Comment by aboy2018** [comment]
> > Do you change anchor value? It should be change array value.
> 
> I just changed the number of categories and resolution.

I don't konw it. Maybe my method is wrong. Only way is watching yolov5 source code.

**Comment by aboy2018** [comment]
> > Do you change anchor value? It should be change array value.
> 
> I just changed the number of categories and resolution.
yolov5.cpp ICudaEngine* build_engine function.

**Comment by ajkdrag** [comment]
> Can you find a way to include anchor related info in the .pt file? Why do the official .pt files contain such info?

I have made a PR to fix this issue. This requires the user to provide the "official .pt model" as well along with their .pt file. Tested on Triton.

**Comment by ajkdrag** [comment]
> I have used the new gen wts that is in the pull and with a small edit it fixed my problem Thankyou so much!

Can you mentione the edit you needed so that it can help others as well in case.

**Comment by xrstokes** [comment]
> > I have used the new gen wts that is in the pull and with a small edit it fixed my problem Thankyou so much!
> 
> Can you mention the edit you needed so that it can help others as well in case.

I put a note in the review. I had to change line 38 
from "with wts_file.open(mode = w+) as f:"
to with "open(wts_file, 'w') as f:"

https://github.com/wang-xinyu/tensorrtx/pull/774/files

**Comment by prasheelBB8** [comment]
>  ![image](https://user-images.githubusercontent.com/26057879/137874092-608fb730-9bef-42eb-84ff-c72d82d0c968.png)

@wang-xinyu Isn't this error due the code in the destructor part of the _yololayer.cu_ file? i.e shouldn't [L52](https://github.com/wang-xinyu/tensorrtx/blob/4686140d25543048207973d006dc8a4305b00f19/yolov5/yololayer.cu#L52) be commented if cudaFree has already cleared the cuda memory. And yet, outside the for loop cudaFreeHost is trying to free it again though it doesn't exist? Hence the "_Assertion '0' failed_"?
```
    YoloLayerPlugin::~YoloLayerPlugin()
    {
        for (int ii = 0; ii < mKernelCount; ii++)
        {
            CUDA_CHECK(cudaFree(mAnchor[ii]));
        }
      //  CUDA_CHECK(cudaFreeHost(mAnchor));
    }
```
I referred the documentation [here](http://horacio9573.no-ip.org/cuda/group__CUDART__MEMORY_gedaeb2708ad3f74d5b417ee1874ec84a.html) and thought either of the two functions should be called, _cudaFreeHost_ or _cudaFree_. Please let me know if I am incorrect. Also, after commenting the line, I did check for any memory leaks if that was an issue, but cuda-memcheck doesn't show any errors,
```cuda-memcheck sudo ./yolov5 -s yolov5s.wts yolov5s.engine s```

But one thing is, even though we pass the engine build, there are **no inferences on our test dataset**.
_Note: This change didn't effect performance of the builtin _yolov5s.pt_ model, i.e bounding boxes still show up from the compiled _yolov5s.engine_ file. Just our custom .engine doesn't work at all_

Please let us know next steps!!
