### ISSUE TITLE
Do you have tersorrt so in arm64  

### ISSUE THREAD

**Issue by aboy2018** [wang-xinyu/tensorrtx#773]
串场了，您好，不过还是想问一下您有xaiver，arm平台,cuda10.0的tensorrt7.0或者6.0的依赖库吗？谢谢

**Comment by wang-xinyu** [comment]
Tensorrt for jetson is included in the jetpack. Afaik, NVIDIA did not provide separate link to download it.

**Comment by aboy2018** [comment]
thank you
