### ISSUE TITLE
大佬，YOLOv5增加了新的head PANet，什么时候更新下代码啊？

### ISSUE THREAD

**Issue by Wulingtian** [wang-xinyu/tensorrtx#78]
June 22, 2020: PANet updates: new heads, reduced parameters, faster inference and improved mAP

**Comment by wang-xinyu** [comment]
23 June, 我更新过一次

**Comment by wang-xinyu** [comment]
refer to https://github.com/wang-xinyu/tensorrtx/commit/6fd39395ac6966f04ed58b1f4003e784193c3bdc
