### ISSUE TITLE
sudo ./yolov4 -s command not found

### ISSUE THREAD

**Issue by saikrishnadas** [wang-xinyu/tensorrtx#79]
Everything works fine till make

But running `sudo ./yolov4 -s`  gives me an error.

Error log :
`sudo: ./yolov4 : command not found`

@wang-xinyu

**Comment by wang-xinyu** [comment]
after make,    it should generate an executable file `yolov4`

**Comment by saikrishnadas** [comment]
@wang-xinyu 
Yes, the yolov4 file  is generated , but stillcthis error occurs
