### ISSUE TITLE
Building engine error . I have changed num_cls in yololayer.h and remake in build folder . It's shows something like CUDA error when running ' ./yolov5 -s best.wts best.engine s' . But the unchanged yolov5s works fine.

### ISSUE THREAD

**Issue by axxx-xxxa** [wang-xinyu/tensorrtx#794]
## Env

jetson AGX xavier
cuda10.2
TensorRT8.-

## About this repo

yolov5s (num_cls = 4)

## Your problem

 ./yolov5 -s best.wts best.engine s
Loading weights: best.wts
Building engine, please wait for a while...
[11/01/2021-17:00:03] [W] [TRT] Detected invalid timing cache, setup a local cache instead
CUDA error 1 at /home/xavier/tensorrt/tensorrtx-yolov5-v5.0/yolov5_my/yololayer.cu:52yolov5: /home/xavier/tensorrt/tensorrtx-yolov5-v5.0/yolov5_my/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed.
Aborted (core dumped)

**Comment by axxx-xxxa** [comment]
Im weak in c++ and cuda, thk for help

**Comment by axxx-xxxa** [comment]
Im weak in c++ and cuda, thk for help

**Comment by axxx-xxxa** [comment]
Im weak in c++ and cuda, thk for help

**Comment by wang-xinyu** [comment]
Are you using the newest gen_wts.py?

**Comment by axxx-xxxa** [comment]
> Are you using the newest gen_wts.py?

works fine now! thks.  maybe the env error . I used gen_wts.py in windows and generated engine file in jetson. these two step in jetson both its ok now.

**Comment by axxx-xxxa** [comment]
> Are you using the newest gen_wts.py?

By the way, what should i do if i wanna use the engine file to inference video(or rtsp) in c++ ?

**Comment by doubiydd** [comment]
> > Are you using the newest gen_wts.py?
> 
> By the way, what should i do if i wanna use the engine file to inference video(or rtsp) in c++ ?

I have the same problem.
