### ISSUE TITLE
win10 yolov5 6.0编译bug

### ISSUE THREAD

**Issue by Monday-Leo** [wang-xinyu/tensorrtx#797]
VS2017 CUDA10.2 cudnn 7.6.5 TensorRT-7.0.0.11
编译6.0版本死活通不过，主要问题出在下图
![9 ~QP% (GCM{@0QH)G`FU79](https://user-images.githubusercontent.com/53975909/139906672-af660bb4-5b25-4be4-9102-19f8a3a52e57.png)

同等环境下，选择4.0版本，编译一次过，希望修复一下。

**Comment by yyyaiyowei0604** [comment]
我也是编译不过 出现同样的问题

**Comment by heiybb** [comment]
add `add_definitions(-DAPI_EXPORTS) `
below the line `add_definitions(-std=c++11)`
in your CMakeLists.txt

**Comment by 7chosen** [comment]
我也是make不过，楼主现在解决了吗?
