### ISSUE TITLE
yolov5-n在int8  量化 转tensorrt 报错

### ISSUE THREAD

**Issue by woshituobaye** [wang-xinyu/tensorrtx#798]
用的是yolov5n   不int8量化的时候可以转。设置 了USE_INT8` in yolov5.cpp   在build中cmake  make 后  序列化失败。

sudo ./yolov5 -s yolov5n-best.wts yolov5n-best.engine n 

Loading weights: yolov5n-best.wts
Your platform support int8: true
Building engine, please wait for a while...
reading calib cache: int8calib.table
[11/03/2021-16:11:58] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1
[11/03/2021-16:12:00] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1
[11/03/2021-16:12:00] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1
[11/03/2021-16:12:00] [E] [TRT] 1: Unexpected exception _Map_base::at
Build engine successfully!
yolov5: /home/dashu/下载/tensorrtx-int8/yolov5/yolov5.cpp:243: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::string&): Assertion `engine != nullptr' failed.
已放弃

**Comment by woshituobaye** [comment]
cuda=11.3  pytorch=1.10

**Comment by Lenan22** [comment]
> 用的是yolov5n 不int8量化的时候可以转。设置 了USE_INT8` in yolov5.cpp 在build中cmake make 后 序列化失败。
> 
> sudo ./yolov5 -s yolov5n-best.wts yolov5n-best.engine n
> 
> Loading weights: yolov5n-best.wts Your platform support int8: true Building engine, please wait for a while... reading calib cache: int8calib.table [11/03/2021-16:11:58] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1 [11/03/2021-16:12:00] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1 [11/03/2021-16:12:00] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1 [11/03/2021-16:12:00] [E] [TRT] 1: Unexpected exception _Map_base::at Build engine successfully! yolov5: /home/dashu/下载/tensorrtx-int8/yolov5/yolov5.cpp:243: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::string&): Assertion `engine != nullptr' failed. 已放弃

Please refer to our open source quantization tool ppq, the quantization result is better than the quantization tool that comes with tensorrt, almost the same as the float32 model. https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md

**Comment by KevinZhanggg** [comment]
@woshituobaye 你好，我也遇到同样的问题， 请问你怎么解决的？ 感谢

**Comment by geokuk** [comment]
> @woshituobaye 你好，我也遇到同样的问题， 请问你怎么解决的？ 感谢

要在model.cpp里修改你自己的calibration数据的路径
