### ISSUE TITLE
yolov5n model  use int8 Quantization     have  error

### ISSUE THREAD

**Issue by woshituobaye** [wang-xinyu/tensorrtx#799]
pytorch=1.10  cuda=11.3   tensorrt=8.2.0.6 ubuntu=20.04

sudo ./yolov5 -s yolov5n-best.wts yolov5n-best.engine n 

Loading weights: yolov5n-best.wts
Your platform support int8: true
Building engine, please wait for a while...
reading calib cache: int8calib.table
[11/03/2021-16:29:15] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1
[11/03/2021-16:29:17] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1
[11/03/2021-16:29:17] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1
[11/03/2021-16:29:17] [E] [TRT] 1: Unexpected exception _Map_base::at
Build engine successfully!
yolov5: /home/dashu/下载/tensorrtx-int8/yolov5/yolov5.cpp:243: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::string&): Assertion `engine != nullptr' failed.
已放弃

**Comment by woshituobaye** [comment]
我懂了 没有把数据集文件夹 改名为coco_calib

**Comment by henbucuoshanghai** [comment]
yolov5n model on 4G NVIDIA JETSON NANO,the fps is?   img is 640*640

**Comment by henbucuoshanghai** [comment]
30fps?

**Comment by Lenan22** [comment]
> pytorch=1.10 cuda=11.3 tensorrt=8.2.0.6 ubuntu=20.04
> 
> sudo ./yolov5 -s yolov5n-best.wts yolov5n-best.engine n
> 
> Loading weights: yolov5n-best.wts Your platform support int8: true Building engine, please wait for a while... reading calib cache: int8calib.table [11/03/2021-16:29:15] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1 [11/03/2021-16:29:17] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1 [11/03/2021-16:29:17] [W] [TRT] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.1 but loaded cuBLAS/cuBLAS LT 11.5.1 [11/03/2021-16:29:17] [E] [TRT] 1: Unexpected exception _Map_base::at Build engine successfully! yolov5: /home/dashu/下载/tensorrtx-int8/yolov5/yolov5.cpp:243: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::string&): Assertion `engine != nullptr' failed. 已放弃

Please refer to our open source quantization tool ppq, the quantization result is better than the quantization tool that comes with tensorrt, almost the same as the float32 model. https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md
