### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by JimmyLauren** [wang-xinyu/tensorrtx#8]
Hi, thanks a lot for your excellent work. I've been able to repreduce this work on ubuntu16.04. But i wonder what i have to do to repreduce this repo on Windows?

**Comment by wang-xinyu** [comment]
@JimmyLauren ,  this repo only works on ubuntu.   For Windows,  you need to install cuda, cudnn, tensorrt, etc, on Windows,   and adapt the codes a little bit yourself. I think it won't need too many changes.

**Comment by JimmyLauren** [comment]
Glad to receive your response. thanks for your suggestion.

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/run_on_windows.md

A windows totorial has beed added.
