### ISSUE TITLE
大佬，我在Windows平台下编译的时候，遇到了错误

### ISSUE THREAD

**Issue by Wulingtian** [wang-xinyu/tensorrtx#80]
运行cmake ..得到如下信息：
D:\BaiduNetdiskDownload\yolov5_material\tensorrtx-master\yolov5\build>cmake .
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.14393.
embed_platform off
-- Configuring done
-- Generating done
-- Build files have been written to: D:/BaiduNetdiskDownload/yolov5_material/tensorrtx-master/yolov5/build
运行make得到如下错误：
D:\BaiduNetdiskDownload\yolov5_material\tensorrtx-master\yolov5\build>make
make: *** No targets specified and no makefile found.  Stop.

**Comment by wang-xinyu** [comment]
`cmake ..`

not 

`cmake .`
