### ISSUE TITLE
执行模型序列化时出现错误

### ISSUE THREAD

**Issue by ChenXinShuo1998** [wang-xinyu/tensorrtx#800]
[11/04/2021-21:28:52] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::494, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/chenxinshuo/PycharmProjects/tensorrtx-master/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::string, float): Assertion `scale_1' failed.

**Comment by sunhuisunhui** [comment]
请问解决了吗，有什么解决方法

**Comment by wang-xinyu** [comment]
Mostly such issue is caused by version mismatch.
Check here
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5
