### ISSUE TITLE
yolov5-6.0在windows上编译报错无法解析的符号

### ISSUE THREAD

**Issue by futureflsl** [wang-xinyu/tensorrtx#801]
VS2019 CUDA10.2 cudnn 7.6.5 TensorRT-7.0.0.11
编译6.0版本死活通不过，主要问题出在下
无法解析的外部符号 "void __cdecl preprocess_kernel_img(unsigned char *,int,int,float *,int,int,struct CUstream_st *)" (?preprocess_kernel_img@@YAXPEAEHHPEAMHHPEAUCUstream_st@@@Z)，函数 main 中引用了该符号	yolov5	C:\Users\Administrator\Desktop\tensorrtx-windows\yolov5\build\yolov5.obj	1	
开始和https://github.com/wang-xinyu/tensorrtx/issues/797 
问题一样，加入add_definitions(-DAPI_EXPORTS)就变成这个报错

**Comment by futureflsl** [comment]
> VS2019 CUDA10.2 cudnn 7.6.5 TensorRT-7.0.0.11 编译6.0版本死活通不过，主要问题出在下 无法解析的外部符号 "void __cdecl preprocess_kernel_img(unsigned char *,int,int,float *,int,int,struct CUstream_st *)" (?preprocess_kernel_img@@YAXPEAEHHPEAMHHPEAUCUstream_st@@@z)，函数 main 中引用了该符号 yolov5 C:\Users\Administrator\Desktop\tensorrtx-windows\yolov5\build\yolov5.obj 1 开始和#797 问题一样，加入add_definitions(-DAPI_EXPORTS)就变成这个报错

I sovled it.I add
add_executabe(yolov5 preprocess.cu preprocess.h)

**Comment by raychiu0202** [comment]
> > VS2019 CUDA10.2 cudnn 7.6.5 TensorRT-7.0.0.11 编译6.0版本死活通不过，主要问题出在下 无法解析的外部符号 "void __cdecl preprocess_kernel_img(unsigned char *,int,int,float *,int,int,struct CUstream_st *)" (?preprocess_kernel_img@@YAXPEAEHHPEAMHHPEAUCUstream_st@@@z)，函数 main 中引用了该符号 yolov5 C:\Users\Administrator\Desktop\tensorrtx-windows\yolov5\build\yolov5.obj 1 开始和#797 问题一样，加入add_definitions(-DAPI_EXPORTS)就变成这个报错
> 
> I sovled it.I add add_executabe(yolov5 preprocess.cu preprocess.h)

en~~It didn't work

**Comment by raychiu0202** [comment]
> > > VS2019 CUDA10.2 cudnn 7.6.5 TensorRT-7.0.0.11 编译6.0版本死活通不过，主要问题出在下 无法解析的外部符号 "void __cdecl preprocess_kernel_img(unsigned char *,int,int,float *,int,int,struct CUstream_st *)" (?preprocess_kernel_img@@YAXPEAEHHPEAMHHPEAUCUstream_st@@@z)，函数 main 中引用了该符号 yolov5 C:\Users\Administrator\Desktop\tensorrtx-windows\yolov5\build\yolov5.obj 1 开始和#797 问题一样，加入add_definitions(-DAPI_EXPORTS)就变成这个报错
> > 
> > 
> > I sovled it.I add add_executabe(yolov5 preprocess.cu preprocess.h)
> 
> en~~It didn't work

I'm wrong. It works

**Comment by tianyang820** [comment]
@raychiu0202 Hi. How did you solve it?

**Comment by raychiu0202** [comment]
> 
我记得是按照上边那个兄弟的方式处理的，配置一下yolov5 preprocess.cu preprocess.h这两个文件就可以了

**Comment by raychiu0202** [comment]
> @raychiu0202 Hi. How did you solve it?

我记得是按照上边那个futureflsl兄弟方式处理的，配置一下yolov5 preprocess.cu preprocess.h这两个文件就可以了。

**Comment by hzhangxwow** [comment]
>need to added in the previous line like this

**Comment by Ryan-Y25** [comment]
> > need to added in the previous line like this
> > add_executable(yolov5 ${PROJECT_SOURCE_DIR}/yolov5.cpp ${PROJECT_SOURCE_DIR}/yololayer.cu ${PROJECT_SOURCE_DIR}/yololayer.h yolov5 ${PROJECT_SOURCE_DIR}/preprocess.cu ${PROJECT_SOURCE_DIR}/preprocess.h)   #4

This way works!
