### ISSUE TITLE
Yolov5s.engine cannot be generated！！！！！

### ISSUE THREAD

**Issue by Havehandssook** [wang-xinyu/tensorrtx#807]
![QQ截图20211109015202](https://user-images.githubusercontent.com/74224500/140793749-c3770b06-43b7-41af-9db5-1772a4807074.jpg)

Is it the yoloV5 version that doesn't match?
May I ask why I made this mistake?Hope to get everyone's help!

**Comment by ScilenceForest** [comment]
是不是因为中文路径？

**Comment by Havehandssook** [comment]
> 是不是因为中文路径？

![QQ截图20211109065735](https://user-images.githubusercontent.com/74224500/140876811-3a9188d7-5104-4e93-b35c-f71ad239c003.jpg)

The same question.....

**Comment by Havehandssook** [comment]
这个问题 我解决了  我更换了yolov5s.pt  可能之前的版本不匹配

**Comment by Havehandssook** [comment]
This problem I solved when I replaced yolov5s.pt maybe the previous version didn't match.......
But I have a new problem this warning doesn't affect anything but I want to eliminate it！
![Uploading QQ截图20211109192731.jpg…]()
