### ISSUE TITLE
build/libmyplugins.so

### ISSUE THREAD

**Issue by dota2015** [wang-xinyu/tensorrtx#809]
## Env

- GPU,RTX3060 Laptop
- OS, Win10
- Cuda version,11.4
- TensorRT version,TensorRT-8.2.0.6

## About this repo
tensorrtx-yolov5-v5.0

## Your problem

I have sucess run yolov5.exe -s yolov5s.wts yolov5s.engine s and yolov5.exe -d yolov5s.engine samples.
It Iworks ok.
But when I run yolov5_trt.py, can't find "build/libmyplugins.so".How to get the file?

**Comment by dota2015** [comment]
I have solved the problem. Thank you

**Comment by dota2015** [comment]
I have solved the problem. Thank you

**Comment by NaveedAI** [comment]
may is ask how you solved it?

**Comment by dota2015** [comment]
> 

在yolov5_trt.py中使用c++工程生成的yolov5.dll

**Comment by uaing** [comment]
您好  问下能说明下如何生成的yolov5.dll文件么，我生成的使用CDLL导入一直报错，不知道什么问题

**Comment by zxm97** [comment]
> 您好 问下能说明下如何生成的yolov5.dll文件么，我生成的使用CDLL导入一直报错，不知道什么问题

ctypes.CDLL(PLUGIN_LIBRARY)  -----> ctypes.WinDLL(PLUGIN_LIBRARY)

**Comment by zxm97** [comment]
> 您好 问下能说明下如何生成的yolov5.dll文件么，我生成的使用CDLL导入一直报错，不知道什么问题
libmyplugins.so -----> myplugins.dll
ctypes.CDLL(PLUGIN_LIBRARY) -----> ctypes.WinDLL(PLUGIN_LIBRARY)
