### ISSUE TITLE
How to implement this for camera input?

### ISSUE THREAD

**Issue by PiyalGeorge** [wang-xinyu/tensorrtx#81]

**Comment by wang-xinyu** [comment]
@PiyalGeorge Hi,   It is not difficult to process camera video using OpenCV. You need to learn some opencv c++ basics.

**Comment by berkantay** [comment]
Hello I implemented the video stream using opencv and fed it to the ```preprocess_img(frame)```.  But after the first frame I get segmentation fault and core dumped errors. Probably during the live video stream data buffer is overflows and throws memory errors. How should I overcome this?

**Comment by simaiden** [comment]
> Hello I implemented the video stream using opencv and fed it to the `preprocess_img(frame)`. But after the first frame I get segmentation fault and core dumped errors. Probably during the live video stream data buffer is overflows and throws memory errors. How should I overcome this?
> 
> I think some custom functions for flatting image array should be added for video streams. To feed it to the flatten layer.

Did you get any solution?
