### ISSUE TITLE
./yolov5 -s  Parameter check failed at: ../builder/Network.cpp::addScale::488, condition: shift.count > 0 

### ISSUE THREAD

**Issue by fire717** [wang-xinyu/tensorrtx#810]
## Env

- GPU, Xavier NX
- OS, Ubuntu18.04.
- Cuda 10.2
- TensorRT 7.1.0

## About this repo

- which branch/tag/commit are you using?
I follow the README, `git clone https://github.com/wang-xinyu/tensorrtx.git, so it should be master branch`

- which model? yolov5, retinaface?
yolov5, also like README `git clone -b v5.0 https://github.com/ultralytics/yolov5.git`

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
`sudo ./yolov5 -s ../../../models/yolov5s.wts ../../../models/yolov5s.engine s`
- what's your output?
`Loading weights: ../../../models/yolov5s.wts
[11/10/2021-09:39:54] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::488, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /mnt/workshop/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted`

- what output do you expect?
`Build sucessful.`

### Other Info
I just follow the README step, and I can sucessfully transfer the wts to engine in my ubuntu PC, so the wts file should be right.
However when it comes to NX, same file, same shell line, wrong output.

**Comment by fire717** [comment]
same problem： #https://github.com/wang-xinyu/tensorrtx/issues/571

**Comment by fire717** [comment]
And my yolov5s.wts fist line is 362
I see here https://github.com/wang-xinyu/tensorrtx/issues/59 u said is 370, but I just download the yolov5s.pt from the origin v5.0 release page.

**Comment by wang-xinyu** [comment]
git clone -b yolov5-v5.0 https://github.com/wang-xinyu/tensorrtx.git

**Comment by fire717** [comment]
> git clone -b yolov5-v5.0 https://github.com/wang-xinyu/tensorrtx.git

It works now, thx!
(And I suggest that add ` -b yolov5-vX.X` in `How to Run, yolov5s as example`)

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5#different-versions-of-yolov5

Already put there. How to be more clear?

**Comment by fire717** [comment]
I mean At  https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v5.0/yolov5#how-to-run-yolov5s-as-example

step1

Now is :
git clone -b v5.0 https://github.com/ultralytics/yolov5.git
git clone https://github.com/wang-xinyu/tensorrtx.git

New could be more clear:
git clone -b v5.0 https://github.com/ultralytics/yolov5.git
git clone -b yolov5-v5.0 https://github.com/wang-xinyu/tensorrtx.git

I said cause yolov5 u add -b and tensorrtx not, so it is a litte midleading , maybe it's why there are many other people meet same issue 😅 like [issue571](https://github.com/wang-xinyu/tensorrtx/issues/571)

And if u think its ok, then its okay.
Nice work anyway.

**Comment by wang-xinyu** [comment]
Always refer to the latest readme first. https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5 .
There is no `git clone https://github.com/wang-xinyu/tensorrtx.git` in  newest `how to run`

For the yolov5-v5.0 tag, which is a tag, not branch. cannot be updated anymore.  We'll only update and maintain the latest version.

**Comment by fire717** [comment]
Got it! Thx for sharing.
