### ISSUE TITLE
win10 yolov5 6.0生成engine失败

### ISSUE THREAD

**Issue by Monday-Leo** [wang-xinyu/tensorrtx#812]
VS2017 CUDA10.2 cudnn 7.6.5 TensorRT-7.0.0.11
生成engine如下图：
![R~HVE`24}_D{{$OX{M}JMK3](https://user-images.githubusercontent.com/53975909/141131841-3091e3f9-37a0-46c2-9f5e-5d49c4912385.png)
请问该如何解决，是自己训练的模型，已经修改下面参数
    static constexpr int CLASS_NUM = 42;
    static constexpr int INPUT_H = 416; 
    static constexpr int INPUT_W = 416;

使用官方模型，不修改类别数和图像大小，输出engine成功

**Comment by lhy823436493** [comment]
当我重新训练模型，修改输入为【640，640】后，依旧报错，仍然没有解决

**Comment by lhy823436493** [comment]
@wang-xinyu

**Comment by wang-xinyu** [comment]
Hi, I'll not check any Windows issue.

**Comment by lhy823436493** [comment]
Sorry,who should I ask for help? I don't know why the errors appear. I've already changed CLASS_NUM because I use custom model and I haven't solved the problem yet!

**Comment by lhy823436493** [comment]
Surprisingly, this error did not occur when exporting the custom model with YoloV5 4.0, and the model predicted successfully, but 6.0 did not export the engine correctly, I wonder if it is a bug？

**Comment by lhy823436493** [comment]
@wang-xinyu  I need some help!!
When I successfully run the yolov5s 4.0, the results are not quite accurate. When I use pytorch to test the raw model ,the Map is so good,over 95%(figure 1).But when I use tensorrt engine which is exported through FP32, the Map is only around 25%(figure 2) Why is that?
I test the Map through https://github.com/Cartucho/mAP
![mAP](https://user-images.githubusercontent.com/53975909/141682504-08e80978-0317-4cf5-ad81-ed0ad50a213f.png)
![mAP](https://user-images.githubusercontent.com/53975909/141682510-c8393a06-ffb8-47db-8f5d-e2eb69944de2.png)

**Comment by lhy823436493** [comment]
I'am so sorry.The reason why Map differs so much is my python inference has a bug and I find it today. I do the inference with the correct version and now the results are quite good.Thank you for your good work! ! !
![mAP](https://user-images.githubusercontent.com/53975909/141713957-19c03240-6393-440c-81a4-ecbecde3f7fb.png)
