### ISSUE TITLE
运行yolov5_try.py报错

### ISSUE THREAD

**Issue by wuyuwangqingtian** [wang-xinyu/tensorrtx#815]
您好，我运行您的yolov5_try.py文件时报错，但是我解决不了，您可以看看吗？谢谢
![报错2](https://user-images.githubusercontent.com/68488908/141604041-cc52b49f-4f46-47ae-b414-fa81ceb528f5.jpg)

**Comment by wang-xinyu** [comment]
version tag mismatch,

tensorrt c++ and py, must be the same version.
