### ISSUE TITLE
tensorrtx for python in other yolo versions.

### ISSUE THREAD

**Issue by DuongTran1708** [wang-xinyu/tensorrtx#818]
## Env

- GPU: TitanX, Jetson Xavier NX
- OS : Ubuntu20.04, Ubuntu 18.04
- Cuda : version 11.0, version 10.2
- TensorRT version 8.0.5 (JetPack 4.6) 

## About this repo

- Branch: master
- Commit: 5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7
- Model: yolov5, scaled-yolov4, yolov4

## Your problem

- In yolov5, you have the "yolov5_trt.py" for running on python. Do you have any version for other yolo family in your github?
- Can I use "yolov5_trt.py" to run other yolo family?

Thank for your reading.

**Comment by wang-xinyu** [comment]
You can refer to yolov5_trt.py to implement .py for other yolo models by yourself..
