### ISSUE TITLE
YOLOv5-6.0 Assertion failed: Unsupported SM.

### ISSUE THREAD

**Issue by shekarneo** [wang-xinyu/tensorrtx#819]
## Env

- GPU, RTX3080
- OS,  Docker Ubuntu18.04
- Cuda version: 10.2
- TensorRT version: 7.0

## About this repo

- which branch/tag/commit are you using? master
- which model? yolov5

## Your problem

- what is your command? e.g. `./yolov5 -s yolov5s.wts yolov5s.engine s`
- what's your output?
 Loading weights: yolov5s.wts
Building engine, please wait for a while...
[11/15/2021-17:37:28] [W] [TRT] Half2 support requested on hardware without native FP16 support, performance will be negatively affected.

[11/15/2021-17:51:03] [F] [TRT] Assertion failed: Unsupported SM.
../rtSafe/cuda/caskUtils.cpp:80
Aborting...

[11/15/2021-17:51:03] [E] [TRT] ../rtSafe/cuda/caskUtils.cpp (80) - Assertion Error in trtSmToCask: 0 (Unsupported SM.)
Build engine successfully!
yolov5: /home/neo/tensorrtx/yolov5/yolov5.cpp:243: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::__cxx11::string&): Assertion `engine != nullptr' failed.
Aborted (core dumped)

- what output do you expect?
yolov5s.engine

**Comment by wang-xinyu** [comment]
Does 3080 work with cuda10.2? I'm not sure. You can try cuda11

**Comment by shekarneo** [comment]
i tried with cuda 11.3 and it worked, but in deepstream-5.0 deserialization error appeared

**Comment by wang-xinyu** [comment]
We don't have any demo for deepsteam in this repo, pls figure it out by yourself.

**Comment by ylyenjoy** [comment]
I ran into the same problem，Have you solved the problem yet?

**Comment by shekarneo** [comment]
try to use onnx-file not converted trt engine file.

**Comment by doubiydd** [comment]
3080 can't work with cuda10.2,you have better update the version.
