### ISSUE TITLE
Drop in performance after converting models into .weight to Tensorrt

### ISSUE THREAD

**Issue by akashAD98** [wang-xinyu/tensorrtx#820]
I have converted the yolov4-mish model into onnx then tensorrt & I'm getting too many false predictions .compaired to the original darknet weight. May I know what are the possible ways to solve this problem? how can we reduce False prediction?

reference issue
https://github.com/jkjung-avt/tensorrt_demos/issues/473
https://github.com/jkjung-avt/tensorrt_demos/issues/315

**Comment by wang-xinyu** [comment]
TensorRTx does not use any ONNX.
This is the wrong place to discuss your issue.
