### ISSUE TITLE
latency of the mask-RCNN FPN

### ISSUE THREAD

**Issue by huisai** [wang-xinyu/tensorrtx#821]
## About this repo
- which model? RCNN, FPN

Can you share the latency of the mask-RCNN FPN of your implementation? or how much faster is FPN than C4?
 my FPN implementation seems not improved much  compared  to  [C4](https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn#latency)

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn#latency

**Comment by huisai** [comment]
@wang-xinyu Thanks for your reply.
https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn#latency  shows C4 version performance only，do you have the performance information for the FPN version? because I want to check out  how much faster is FPN than C4

**Comment by wang-xinyu** [comment]
No, we don't.
