### ISSUE TITLE
YoloV5 synchronization issue

### ISSUE THREAD

**Issue by mfoglio** [wang-xinyu/tensorrtx#823]
Hello, I am having issues when running the YoloV5 model in a dedicated cuda streams.
I opened a discussion on the cupy repository because I believe the problem was caused by cupy. After discussing with a TensorRT Nvidia developer we reached the conclusion that either there is an error in the function `CalDetection` in your Yolo V5 implementation, or TensorRT 7 is bugged. In fact, it seems that the TensorRT is not waiting for that function to complete its execution, therefore copying random data from the GPU as model output.
Do you have any suggestion on what to do here? The code I used to build the model on TensorRT7 is not running with TensorRT 8. Do the current implementation support TensorRT 8?
More information about the bug here: https://github.com/cupy/cupy/issues/6104

**Comment by wang-xinyu** [comment]
We do support tensorrt8, many people had already verified.
