### ISSUE TITLE
YOLOv5 v6.0转换m模型时make失败

### ISSUE THREAD

**Issue by Bishilan** [wang-xinyu/tensorrtx#826]
打扰了，我在yolov5 v6.0转换m模型的时候，make报错。如下图1.。而我从其他版的tensorrt/yolov5/路径下的yolov5.cpp进行替换v6.0的的yolov5.cpp后，居然make成功，但执行./yolov5 -s yolov5m.wts yolov5m.engine m时再次报错，如下图。问题比较多，辛苦作者回复一下！！！下载的版本都是使用指令git clone -b v6.0 https://github.com/ultralytics/yolov5.git 和 git clone https://github.com/wang-xinyu/tensorrtx.git下的两个包，整个过程也确保是按步骤走的。不明白是什么原因造成的错误
![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/94827452/142833308-4e89206d-3bdb-4419-9dea-a1921e872be3.JPEG)

![webwxgetmsgimg](https://user-images.githubusercontent.com/94827452/142833358-57599851-6e58-4441-bb41-af75d1ba6ec0.JPEG)

**Comment by hititan** [comment]
我也是这种情况，请作者核对一下，并请修正
