### ISSUE TITLE
Cannot convert to int8 in Jetson TX2

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [wang-xinyu/tensorrtx#831]
## Env

- GPU: TX2
- OS, Ubuntu18.04
- Cuda version: 10.2
- TensorRT version: 8.0.1.6

## About this repo

- which branch/tag/commit are you using?: master
- which model? yolov5

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s best.wts best.engine s`
- what's your output?:

```
Your platform support int8: false
yolov5: /sd_card/repos/convert_tensorrt/tensorrtx_int8/yolov5/yolov5.cpp:106: nvinfer1::ICudaEngine* build_engine(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType, float&, float&, std::__cxx11::string&): Assertion `builder->platformHasFastInt8()' failed.
Aborted
nvidia@nv
```
- what output do you expect?

Is it possible to convert model with int8 in Jetson TX2? Am I doing something wrong or it is just a limitation?

**Comment by wang-xinyu** [comment]
TX2 does not support int8

**Comment by JNaranjo-Alcazar** [comment]
Okey! Thanks for the quick reply 😄
