### ISSUE TITLE
MobileNetv3 changing batchsize results in failed export.

### ISSUE THREAD

**Issue by Sumered** [wang-xinyu/tensorrtx#833]
## Env

- OS: Ubuntu 18.04
- Cuda version: 11.4
- TensorRT version: 21.03

## About this repo

- which branch/tag/commit are you using? master
- which model? mobilenetv3

## Your problem

- what is your command? ./mobilenetv3 -s large and ./mobile -s small
- what's your output?
```
large
Loading weights: ../mbv3_large.wts
len 16
len 16
len 16
len 64
len 64
len 24
len 72
len 72
len 24
len 72
len 72
len 40
len 120
len 120
len 40
len 120
len 120
len 40
len 240
len 240
len 80
len 200
len 200
len 80
len 184
len 184
len 80
len 184
len 184
len 80
len 480
len 480
len 112
len 672
len 672
len 112
len 672
len 672
len 160
len 672
len 672
len 160
len 960
len 960
len 160
len 960
set name out
[12/01/2021-10:26:30] [E] [TRT] (Unnamed Layer* 33) [Fully Connected]: bias weights has count 18 but 144 was expected
[12/01/2021-10:26:30] [E] [TRT] Could not compute dimensions for (Unnamed Layer* 33) [Fully Connected]_output, because the network is not valid.
[12/01/2021-10:26:30] [E] [TRT] Network validation failed.
build out
```
- what output do you expect? Correct finish of build

Hi, during exporting mobilenetv3 I noticed that changing batchsize here
https://github.com/wang-xinyu/tensorrtx/blob/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7/mobilenet/mobilenetv3/mobilenet_v3.cpp#L27
Results in error during exporting from wts to engine. It seems that batchsize is used during creating seLayer in lines 142 and 144:
https://github.com/wang-xinyu/tensorrtx/blob/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7/mobilenet/mobilenetv3/mobilenet_v3.cpp#L137-L154
I dont know why number of bias weights should be dependent of batch size. It would be really helpfull if You explained this to me.
Also I noticed that no matter what batch size I set, the config of engine would still have batch size of size 1 because batchsize is hardcoded here:
https://github.com/wang-xinyu/tensorrtx/blob/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7/mobilenet/mobilenetv3/mobilenet_v3.cpp#L444

**Comment by wang-xinyu** [comment]
I think only BS=1 is supported and verified.    No idea why BS is showing up in FC layer's param.

**Comment by Sumered** [comment]
So I tried a few things, first of all it seems that changing BS to something different than 1, deleting this BS term in seLayer code and changing APIToModel call so it uses BS instead of hardcoded 1, makes it possible to export .engine with BatchSize higher than 1. I also noticed that there is another bug in using OutputSize.
Here we can set output size to what we want:
https://github.com/wang-xinyu/tensorrtx/blob/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7/mobilenet/mobilenetv3/mobilenet_v3.cpp#L26
But in both of those places:
https://github.com/wang-xinyu/tensorrtx/blob/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7/mobilenet/mobilenetv3/mobilenet_v3.cpp#L278
https://github.com/wang-xinyu/tensorrtx/blob/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7/mobilenet/mobilenetv3/mobilenet_v3.cpp#L341
This output size is completely disregarded. In both of those lines 1000 should be changed to OUTPUT_SIZE. Changing this also makes it possible to export .engine with different output size than 1000.

**Comment by wang-xinyu** [comment]
@Sumered Right, agree, thanks for pointing out.

The mnetv3 in this repo is old, which is from an unofficial pytorch implementation.

I'd like to update it with the model in torchvision.

We already got a PR, https://github.com/wang-xinyu/tensorrtx/pull/825,  but it's not using the model of torchvision directly.

If someone is interested in implementing mobilenetv3 from torchvision,  just like mobilenetv2, resnet, etc.   Pls let me know. I'd like to merge PR related to that.
