### ISSUE TITLE
6.0版本 tensorrt和yolov5m.pt  结果对不上

### ISSUE THREAD

**Issue by mickey-cool** [wang-xinyu/tensorrtx#835]
自己的图片训练的模型，tensorrt engine推理结果和yolov5结果不一致。阈值一样， 同样的图片 通过tensorrt 推理的结果有漏检，yolov5m.pt推理就没有漏检，请问应该是什么问题？怎么排查？

**Comment by wang-xinyu** [comment]
try official model first

**Comment by bigbigxing823** [comment]
> 自己的图片训练的模型，tensorrt engine推理结果和yolov5结果不一致。阈值一样， 同样的图片 通过tensorrt 推理的结果有漏检，yolov5m.pt推理就没有漏检，请问应该是什么问题？怎么排查？

找到问题了吗，后面怎么解决的呢
