### ISSUE TITLE
yolov5 -d yolov5s.engine ../samples error:read_files_in_dir failed

### ISSUE THREAD

**Issue by doubiydd** [wang-xinyu/tensorrtx#836]
## Env

- GPU, RTX3090
- OS,  Win10,
- Cuda 11.1
- TensorRT version 7.2.1.6

## About this repo

 yolov5 v4.0

## Your problem

when using yolov5 -d yolov5s.engine ../samples error occured:read_files_in_dir failed
![image](https://user-images.githubusercontent.com/48237899/144381202-249a40d8-2705-424b-ba9d-ede77f1e085e.png)
@wang-xinyu 

I have downloaded the dirent.h and put it in the tensorrtx-yolov5-v4.0 folder.

**Comment by doubiydd** [comment]
I have solved the problem.

**Comment by sunce4t** [comment]
> I have solved the problem.

Hello! I meet the same problem. Could you tell me how to solve it. i really need help.

**Comment by doubiydd** [comment]
You can try ./samples ranther than ../samples maybe...It's too long time you know...It should be the wrong path I guess.

**Comment by doubiydd** [comment]
> 

You can try ./samples ranther than ../samples maybe...It's too long time you know...It should be the wrong path I guess.

**Comment by sunce4t** [comment]
> You can try ./samples ranther than ../samples maybe...It's too long time you know...It should be the wrong path I guess.

thank you! It seems that I wrote the wrong path. I have already solved the problem. Thanks!
