### ISSUE TITLE
yolov5n INT8 not faster than FP16

### ISSUE THREAD

**Issue by Jacobsolawetz** [wang-xinyu/tensorrtx#838]
## Env

- Jetson Xavier NX

## About this repo

- which branch/tag/commit are you using? lastest 
- which model? yolov5, retinaface? yolov5

## Your problem

I converted a custom single class yolov5n model under INT8 and FP16 and saw the same inference FPS ~17 (includes NMS), measured across 1000 sequential infers

**Comment by Jacobsolawetz** [comment]
I am mostly curious if this is expected or if you expect user error on my behalf

**Comment by wang-xinyu** [comment]
It depends on the GPU internal cores,  some GPU do have better performance for FP16 than INT8.
