### ISSUE TITLE
v6版本的.wts转.engine 报错，请帮助查看

### ISSUE THREAD

**Issue by hititan** [wang-xinyu/tensorrtx#839]
## Env

- GPU：Jetson Xavier TX2 NX
- OS：Ubuntu18.04
- Cuda version 10.2
- TensorRT version 8

## About this repo

git clone -b v6.0 https://github.com/ultralytics/yolov5.git 
git clone https://github.com/wang-xinyu/tensorrtx.git

sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
使用yolov5_v6官网的yolov5s.pt 转 .wts 再转 .engine 成功

使用自定义训练后的best.pt 转 .wts ，修改 tensorrtx/yolov5/yololayer.h的CLASS_NUM跟自定义训练一致。再转 .engine 报错，如下
![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/11833228/144708717-f55f8788-cd1b-45b2-ba07-3a2582917725.jpg)
 请问如何解决？给作者你添麻烦了，实在抱歉，请给与指点
@wang-xinyu 请你帮忙

**Comment by wang-xinyu** [comment]
1. 确保用最新的gen_wts.py
2. 对比自定义模型和官方模型的区别

**Comment by hititan** [comment]
> 

感谢你的回复，
1：确保用最新的gen_wts.py           ----已经确保是最新gen_wts.py
2: 对比自定义模型和官方模型的区别   -----自定义模型已经在yololayer.h 的CLASS_NUM进行了修改。还是报上面的错误。

**Comment by litao-zhx** [comment]
我也遇到了同样的问题，您解决了吗

**Comment by wang-xinyu** [comment]
进一步对比，模型结构

**Comment by litao-zhx** [comment]
应该是对应的，否则官方的模型我也转化不了，但一换成我的模型就报了个cuda的错误，类别信息也改成了我的
