### ISSUE TITLE
是否支持 LResNet100E-IR？

### ISSUE THREAD

**Issue by wu-ruijie** [wang-xinyu/tensorrtx#84]
你好，请问是否支持 LResNet100E-IR模型转换呢？谢谢！

**Comment by wang-xinyu** [comment]
不支持，没用过

**Comment by wu-ruijie** [comment]
这个是ArcFace人脸识别的一个模型，不过你支持的是 LResNet50E-IR，准确率有些低，我想支持 LResNet100E-IR，不过看起来在arcface-r50.cpp里面createEngine只添加了 LResNet50E-IR的层，要支持 LResNet100E-IR，是否修改createEngine就可以了呢？非常感谢！

**Comment by wang-xinyu** [comment]
是的，修改createEngine函数，定义LResNet100E-IR网络

**Comment by wu-ruijie** [comment]
非常感谢！目前只能支持BATCH_SIZE=1情况，请问有计划支持BATCH_SIZE>1的情况吗？

**Comment by wang-xinyu** [comment]
这里arcface好像是可以BATCH_SIZE>1的

**Comment by Talgin** [comment]
Hi @wu-ruijie 

Have you tried to change createEngine to support LResNet100E-IR? What was the result? 
I read the code and LResNet100E-IR's symbol.json file and it seems to me that there is a little difference between LResNet50E-IR and LResNet100E-IR. Sorry, I do not have much experience so, maybe it is silly question: Do we have to change something? 

Thank you! :)

**Comment by jiagh2010** [comment]
@wu-ruijie  @Talgin    LResNet100E-IR ， Is this a success？how to do？

**Comment by Talgin** [comment]
Hi, @jiagh2010, 
I tested it on r100 and it was OK. Try it yourself by changing to r100.

**Comment by jiagh2010** [comment]
Can you provide a model, please?  @Talgin    The results of my transformation are still wrong and inconsistent

**Comment by ashuezy** [comment]
@Talgin Can you guide how to change for R100 ?
