### ISSUE TITLE
2块2060显卡，cudaSetDevice(0)识别正常，但是cudaSetDevice(1)后没法识别到任务物体，什么问题？

### ISSUE THREAD

**Issue by xinsuinizhuan** [wang-xinyu/tensorrtx#840]
- GPU, RTX2060*2
- OS Win10
- Cuda 11.0
- TensorRT version 8.2

2块2060显卡，cudaSetDevice(0)识别正常，但是cudaSetDevice(1)后没法识别到任务物体，请问什么问题，怎么解决？

**Comment by m-wei** [comment]
me too!!!!!!!!!!
