### ISSUE TITLE
DBNet build errors

### ISSUE THREAD

**Issue by DCC-lzhy** [wang-xinyu/tensorrtx#841]
## Env

- GPU, RTX2080TI
- OS, Win10
- Cuda 11.1
- TensorRT version 7.2.2.3

## About this repo

- which branch/tag/commit are you using? dbnet
- which model? resnet50

## Your problem

Loading weights: E:\Deploy\DBNet\DBNet\DBNet.pytorch-2\DBNet.wts
Building engine, please wait for a while...
[12/03/2021-18:06:06] [E] [TRT] (Unnamed Layer* 73) [ElementWise]: broadcast dimensions must be non-negative
[12/03/2021-18:06:06] [E] [TRT] Builder failed while analyzing shapes.

**Comment by DCC-lzhy** [comment]
I change addDeconvolutionNd to resize(tensorrt), in torch nn.ConvTranspose2d to nn.Upsample

```
    Weights deconvwts1{ DataType::kFLOAT, deval, 64 * 2 * 2 };
    IDeconvolutionLayer* p4_1 = network->addDeconvolutionNd(*p5->getOutput(0), 64, DimsHW{ 2, 2 }, deconvwts1, emptywts);
    p4_1->setStrideNd(DimsHW{ 2, 2 });
    p4_1->setNbGroups(64);
    weightMap["deconv1"] = deconvwts1;

    IElementWiseLayer* p4_add = network->addElementWise(*p4_1->getOutput(0), *c4_1->getOutput(0), ElementWiseOperation::kSUM);
```
to
```

    auto p4_1 = network->addResize(*p5->getOutput(0));
    assert(p4_1);
    p4_1->setResizeMode(ResizeMode::kNEAREST);
    p4_1->setOutputDimensions(c4_1->getOutput(0)->getDimensions());

    Dims p4_1_dim = p4_1->getOutput(0)->getDimensions();
    Dims c4_1_dim = c4_1->getOutput(0)->getDimensions();

    IElementWiseLayer* p4_add = network->addElementWise(*p4_1->getOutput(0), *c4_1->getOutput(0), ElementWiseOperation::kSUM);
```

**Comment by wang-xinyu** [comment]
Is the error due to your changes?

**Comment by DCC-lzhy** [comment]
in [](https://github.com/BaofengZan/DBNet.pytorch), 本repo为了可以使用tensorRT加速，将反卷积操作全部改为upsample.
但是这个报错说的是广播的维度必须是非负，这个前面设置的宽高都是-1，是这个原因吗

**Comment by wang-xinyu** [comment]
@BaofengZan Could you take a look?

**Comment by BaofengZan** [comment]
@DCC-lzhy   resize的动态尺寸写法有些区别 ，请参考https://github.com/wang-xinyu/tensorrtx/blob/d9bdd7e59f19fe1fcc33de64e61ab54345f3e31c/psenet/psenet.cpp#L78

**Comment by DCC-lzhy** [comment]
多谢
