### ISSUE TITLE
如何导出量化表呢？

### ISSUE THREAD

**Issue by weizh588** [wang-xinyu/tensorrtx#845]
最后只有一个engine，没用量化表么？ 如何导出呢？

**Comment by freedenS** [comment]
量化表是指int8量化相关的数据么？
int8量化会生成calib文件，里面记录的是各层的激活scale数据
至于权重，这个无法导出，不过权重值是固定的，确定了对称或非对称量化后是可以自己计算出来的

**Comment by Lenan22** [comment]
> 最后只有一个engine，没用量化表么？ 如何导出呢？

Please refer to our open source quantization tool ppq, the quantization result is better than the quantization tool that comes with tensorrt, almost the same as the float32 model. https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md
