### ISSUE TITLE
TypeError: pybind11::init() factory function returned nullptr

### ISSUE THREAD

**Issue by pangshengwei** [wang-xinyu/tensorrtx#847]
Am getting this error `TypeError: pybind11::init() factory function returned nullptr)`  at the `trt.Runtime(TRT_LOGGER)` when running yolov5_trt.py with an engine that i've built successfully using `make` and have tested it is able to make inference using command line. Anyone knows what might be the issue?

Environment:
- TensorRT==6.01
- CUDA==10.2
- CUDNN==7.6.5

![WhatsApp Image 2021-12-13 at 3 53 33 PM](https://user-images.githubusercontent.com/19318871/146664381-aa624f05-114e-45dd-a027-57ed3f3e99eb.jpeg)

![image](https://user-images.githubusercontent.com/19318871/145514812-f389f76c-1de1-45f7-9617-8d2883bfe99e.png)

![image](https://user-images.githubusercontent.com/19318871/145514844-a52026fb-de85-4c04-8bcb-e7da9ef9d43a.png)

![image](https://user-images.githubusercontent.com/19318871/145515950-156592ef-2c57-409f-84be-c7c19b390de3.png)

**Comment by wang-xinyu** [comment]
Seems the CUDA was not properly install in your python environment.

**Comment by pangshengwei** [comment]
hm but i am able to perform training ultralytics yolov5 pytorch using gpu and cuda...what makes you say it is not properly installed? I suspect it might be incompatible tensorrt version...

**Comment by wang-xinyu** [comment]
You can try to pip install the tensorrt .whl from tar package of tensorrt rather than the one from apt-install.

**Comment by pangshengwei** [comment]
Update: Fixed by using this TensorRT Image `nvcr.io/nvidia/tensorrt:21.02-py3`
