### ISSUE TITLE
Yolov5 export with dynamic input H, W?

### ISSUE THREAD

**Issue by Michelvl92** [wang-xinyu/tensorrtx#849]
Is it possible to export a yolov5 with dynamic input H, W? In the same trend as you can define the batch size which is between min and maximum?

**Comment by wang-xinyu** [comment]
Hi, you can refer to yolov3-spp in this repo for dynamic input shape.

**Comment by Michelvl92** [comment]
@wang-xinyu would be nice if this could be implemented... if anyone has time.
