### ISSUE TITLE
Engines giving conflicting output when deployed

### ISSUE THREAD

**Issue by makaveli10** [wang-xinyu/tensorrtx#85]
Hi @wang-xinyu , Thanks for sharing this work with us. So, I am getting correct output when tested yolov5 out in TensorRT container. But gives no detections when deployed.

I think the problem is that the kernels in plugin layer should use the same incoming cuda stream which it receives in the call to “enqueue”. This will ensure in-order execution of all the kernels in the entire network. Currently the outputs are conflicting when deployed, particularly referring to this method line no 215[CalDetection<<<...]

    void YoloLayerPlugin::forwardGpu(const float *const * inputs, float* output, cudaStream_t stream, int batchSize) {

            int outputElem = 1 + MAX_OUTPUT_BBOX_COUNT * sizeof(Detection) / sizeof(float);

            for(int idx = 0 ; idx < batchSize; ++idx) {
                CUDA_CHECK(cudaMemset(output + idx*outputElem, 0, sizeof(float)));
            }
            int numElem = 0;
            for (unsigned int i = 0; i < mYoloKernel.size(); ++i)
            {
                const auto& yolo = mYoloKernel[i];
                numElem = yolo.width*yolo.height*batchSize;
                if (numElem < mThreadCount)
                    mThreadCount = numElem;
                CalDetection<<< (yolo.width*yolo.height*batchSize + mThreadCount - 1) / mThreadCount, mThreadCount>>>
                    (inputs[i], output, numElem, yolo.width, yolo.height, (float *)mAnchor[i], mClassCount, outputElem);
            }

    }

**Comment by wang-xinyu** [comment]
The cuda kernel works fine. There must be somewhere wrong from your side.

**Comment by makaveli10** [comment]
@wang-xinyu Alright thanks!
