### ISSUE TITLE
关于crnn的推理时间问题

### ISSUE THREAD

**Issue by husiluanxiang** [wang-xinyu/tensorrtx#851]
## Env

- GPU, e.g. RTX 3070
- OS, e.g. Ubuntu20.04.
- Cuda 11.2
- TensorRT 8.0.1.6

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

-你好 我用的crnn的网络进行推理 但是推理一张图片需要103ms
![image](https://user-images.githubusercontent.com/38007233/146108809-2149d014-1c78-45b3-9c6b-a1f591fc3b59.png)
这个时间是不是不正常，因为同样的模型我在windows下转成onnx,使用 opencv进行部署，计算使用的是CPU却只需要77ms，请问这种情况是应为tensorRT版本导致的吗？？

**Comment by wang-xinyu** [comment]
Need to warmup, try more images, or use loop.

**Comment by husiluanxiang** [comment]
有类似的例子可以借鉴的吗

**Comment by husiluanxiang** [comment]
好了已经解决了，第一次时间应该都用在模型加载上了，采用循环就解决了，谢谢
