### ISSUE TITLE
fatal error: opencv2/dnn/dnn.hpp: 没有那个文件或目录  #include <opencv2/dnn/dnn.hpp>

### ISSUE THREAD

**Issue by ollehhello** [wang-xinyu/tensorrtx#853]
## Env

- GPU, e.g.  RTX3080 etc.
- OS, e.g. Ubuntu18.04 etc.
- Cuda version 11.1
- TensorRT version 7.2.3.4
- yolov5
##issue
/home/pray/mmdet/tensorrtx/yolov5/calibrator.cpp:4:10: fatal error: opencv2/dnn/dnn.hpp: 没有那个文件或目录
 #include <opencv2/dnn/dnn.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/yolov5.dir/build.make:507: recipe for target 'CMakeFiles/yolov5.dir/calibrator.cpp.o' failed
make[2]: *** [CMakeFiles/yolov5.dir/calibrator.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ollehhello** [comment]
Please help, thank you all

**Comment by wang-xinyu** [comment]
you need to install dnn module of opencv

**Comment by ollehhello** [comment]
> you need to install dnn module of opencv

thank you
