### ISSUE TITLE
yolov5无法在nano上编m模型

### ISSUE THREAD

**Issue by guyiyifeurach** [wang-xinyu/tensorrtx#854]
如题。
背景：已经能在nano上编译运行用自己程序训练出的yolov5s模型，设置了最大功率和gpu频率，每张图片640*640推理花费85ms左右。（有办法再提高些吗？）
后面有要求，需要继续提高精度，就想用yolov5m模型试试，训练后，pt模型确实提高了精度，但是在将wts文件转成engine时失败了，报错：
![image](https://user-images.githubusercontent.com/32059046/146698148-eee74157-fbba-43ac-b0e9-e1614e8a989f.png)
搜了一些回答，说可能是因为官方的yolov5m模型跟此repo下的yolov5m模型不一致导致的，查了版本，发现用的是v5.0的版本模型，两者是一致的，md5sum下来，结果也是一样的。
![image](https://user-images.githubusercontent.com/32059046/146698508-ff16cddf-b7c9-493a-9241-f3f74737b26e.png)

![image](https://user-images.githubusercontent.com/32059046/146698477-03a165df-9ee0-4c38-9fbe-94b75676ce56.png)

谁可以救救我吗？不胜感激！

**Comment by wang-xinyu** [comment]
your command is?

**Comment by guyiyifeurach** [comment]
我把parse_args跳过去了，但是正常给gd gw赋值0.67 0.75了，然后在生成engine时挂了。

**Comment by guyiyifeurach** [comment]
用的最新的commit，上个月的，还有其他可能的原因吗？ @wang-xinyu
