### ISSUE TITLE
为什么会出现yolov5使用tensorrt后速度却变慢的情况

### ISSUE THREAD

**Issue by Wyhanc** [wang-xinyu/tensorrtx#856]
## Env

- TX2
- Ubuntu 18.04
- Cuda 10.2
- TensorRT 7.1.3.0

## About this repo

- tag v5.0
- yolov5-5.0

## Your problem

使用的是自己训练的头部检测权重，对sample文件下的两张图片进行测试。
运行yolov5的detect.py，处理时间为103ms和66ms。
运行生成的engine，处理时间分别为281ms和148ms。

想请问一下这是什么情况，为什么速度反倒下降了。

**Comment by mengmeng0320** [comment]
你好，我也有出现类似的问题，请问解决了吗？

**Comment by wang-xinyu** [comment]
try more images,  gpu needs to warmup

**Comment by juzigithub** [comment]
可以从以下方向排查：训练环境和部署环境显卡是否一致？编译和部署的cuda环境是否匹配？

**Comment by Gaojun211** [comment]
@Wyhanc  请问你最后排查出是哪的问题了吗？我这也出现了类似问题
