### ISSUE TITLE
Dimensions error using custom weights based on hyperparameter training

### ISSUE THREAD

**Issue by Snitte** [wang-xinyu/tensorrtx#857]
Yolov5 custom model with hyper parameters

when trying to generate an engine using ultralytics evolve and hyper parameters to create the weight file giving me dimension issues 
I use a hyp.yaml when training, then i generate a .wts file using the provided .py 
However when trying to generate an engine i receive "Error Code 4: Internal Error (Could not compute dimensions for (Unnamed Layer* 0) [Convolution]_output, because the network is not valid.)"
Is there any way to know what dimensions my weights are using to know what to input?

**Comment by wang-xinyu** [comment]
No idea, I can only make sure the official model work.

**Comment by Snitte** [comment]
Is there any way to find the dimensions of a weight file?

**Comment by wang-xinyu** [comment]
you need to check params like kernel size, padding, etc,  not input dims,    weights has nothing to do with input dims

**Comment by Snitte** [comment]
I found that removing anchors from the hyper parameters fixed my issue
