### ISSUE TITLE
Why is there no acceleration effect when using tensorrt

### ISSUE THREAD

**Issue by mengmeng0320** [wang-xinyu/tensorrtx#858]
## Env

- GPU：V100
- OS：Ubuntu18.04
- Cuda 11.0
- TensorRT 

## About this repo

- master
- yolov5x6

## Your problem

- Use yolov5x6 to predict time spent and use tensorrt yolov5x6 Engine takes about the same time
- use yolov5x6 to predict directly ， one picture takes 30ms 
- use yolov5x6.engine to predict，one picture also takes 30+ms

Although both are fp16, I wonder if tensorrt will be faster？

**Comment by wang-xinyu** [comment]
Did you try loop or try more images?

**Comment by mengmeng0320** [comment]
> Did you try loop or try more images?

嗯，我试了两百多张图片，后期的速度还是没有特别大的提升

**Comment by wang-xinyu** [comment]
Then compare the codes more specifically,
- input tensor size
- gpu2cpu memcpy
- inference
- cpu2gpu memcpy
- compare the gpu/cpu memory, no just latency

And for V100, probably pytorch is good enough.

**Comment by mengmeng0320** [comment]
> * gpu2cpu memcpy

**Comment by mengmeng0320** [comment]
> Then compare the codes more specifically,
> 
> * input tensor size
> * gpu2cpu memcpy
> * inference
> * cpu2gpu memcpy
> * compare the gpu/cpu memory, no just latency
> 
> And for V100, probably pytorch is good enough.

ok，Thanks
