### ISSUE TITLE
tensorrtx vs onnx-trtengine

### ISSUE THREAD

**Issue by shunfan-shao** [wang-xinyu/tensorrtx#859]
## Env

Nvidia Jetson TX2

## About this repo

- master
- yolov5

## Your problem

We were facing a similar problem and found your repo on GitHub. This is really impressing. Meanwhile while we were experimenting with your code, we also had some question about your approach, and hope you could share more details with us.

- In model yolov5, one of our member mentions that your model graph might be different from the official yolov5 model. I was wondering for your constructed graph, were you strictly following the original model or could it be possible that you might have modify some layers?
- We were also experimenting with another approach. We first convert models to onnx, and then use TensorRT library to convert the model. I was wondering if there is any difference between the two approaches? eg: will they generate different model graph? will they have different performance or results?
- Is there any comparison between TensorRT vs original model? For us, yolov5 was originated with PyTorch. Will there be any data to support that TensorRT is actually run faster than the original one?

Thanks a lot for your effort. If anyone is familiar with the problem, feel free to leave any comments!

**Comment by wang-xinyu** [comment]
- the final yololayer plugin might be slightly different. but does not affect the result much.
- In most cases, onnx2trt will have same results, or no much difference.  Why we don't use onnx is explained in the readme
- For comparison, you'd better do it yourself,  because it depends on your device.

**Comment by youngjae-avikus** [comment]
@wang-xinyu 

Do you still agree? Do you think there's a difference in speed?

**Comment by wang-xinyu** [comment]
@youngjae-avikus 
Agree on what? Can you be more specific?
