### ISSUE TITLE
关于转换为tensorrt engine之后float32和float16显存占用变化不大？

### ISSUE THREAD

**Issue by lzmisscc** [wang-xinyu/tensorrtx#860]
## Env

- GPU, 3090
- OS, Ubuntu18.04
- Cuda version 11.2
- TensorRT version 8.2.1

## About this repo

- which branch/tag/commit are you using?
- other
- which model?
-  other

## Your problem

为什么通过转换为Tensorrt Engine之后float32和float16的显存占用并没有下降？

**Comment by wang-xinyu** [comment]
FOr this , you need to reach NVIDIA

**Comment by shunfan-shao** [comment]
有一种可能是weight仍然用的是float32，只是在计算的时候用fp16的数据类型。可能需要把input weights也变成fp16才行？

**Comment by lzmisscc** [comment]
> FOr this , you need to reach NVIDIA

Thanks

**Comment by lzmisscc** [comment]
> 有一种可能是weight仍然用的是float32，只是在计算的时候用fp16的数据类型。可能需要把input weights也变成fp16才行？

有可能中间计算的时候有的转为了float32，但是tensorrt里面的具体操作还是不太清楚。去nvidia的刚放问问看。thanks
