### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by baidingyuan** [wang-xinyu/tensorrtx#862]
## Env

- GPU:gtx 1060.
- OS:Ubuntu18.04x86.
- Cuda version:10.2
- TensorRT version:7.1.3

## About this repo

- which branch/tag/commit are you using?
the default one  6.0? i think
- which model? yolov5, retinaface?:
yolov5 5.0 x

## Your problem

- what is your command? 
-make
- what's your output?
 (venv) nvidia@nvidia:~/code/trtyolo/tensorrtx-master/yolov5/build$ sudo make
[sudo] password for nvidia: 
[ 16%] Building NVCC (Device) object CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o
In file included from /home/nvidia/code/trtyolo/tensorrtx-master/yolov5/yololayer.cu:4:0:
/home/nvidia/code/trtyolo/tensorrtx-master/yolov5/yololayer.h:6:10: fatal error: NvInfer.h: No such file or directory
 #include <NvInfer.h>
          ^~~~~~~~~~~
compilation terminated.
CMake Error at myplugins_generated_yololayer.cu.o.Debug.cmake:220 (message):
  Error generating
  /home/nvidia/code/trtyolo/tensorrtx-master/yolov5/build/CMakeFiles/myplugins.dir//./myplugins_generated_yololayer.cu.o

CMakeFiles/myplugins.dir/build.make:75: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

- what output do you expect?
i have successfully used on my jetson agx, so i know the correct output, the output on the ubuntux86 is not correct

**Comment by wang-xinyu** [comment]
the .h of tensorrt is not found.      you need update cmake file accordingly

**Comment by baidingyuan** [comment]
> the .h of tensorrt is not found. you need update cmake file accordingly

thanks,but i have updated the cmake version ,still got the same error ,my cmake version is 3.22.1.  could you explain it more specifically? thanks again

**Comment by baidingyuan** [comment]
> 



> the .h of tensorrt is not found. you need update cmake file accordingly

我又看了一下issue里面类似的问题，发现我的tensorrt也是tar版本安装的，是需要修改cmakelists.txt并在里面添加tensorrt的头文件和so路径的，但是我不知道具体在哪里添加，请指导一下。
