### ISSUE TITLE
Why not provide CUDA implementation of NMS method in yolov5 model? 

### ISSUE THREAD

**Issue by zjhellofss** [wang-xinyu/tensorrtx#864]
作者您好，我想知道您是否有计划提供yolov5后处理nms方法的cuda实现。如果您有这个计划的话，我可以做这件事情。

Hi, great wishes on Christmas day! Why not provide CUDA implementation of NMS post processing method in yolov5 model? If you have this plan, I can implement it.

**Comment by wang-xinyu** [comment]
The number of ouput bboxes from yololayer plugin is very little,  so CUDA NMS is not necessary. 
But you can try and compare.
