### ISSUE TITLE
如何知道yolov5,yololayer.cu   forwardGpu  input  数据是什么

### ISSUE THREAD

**Issue by Programmerwyl** [wang-xinyu/tensorrtx#868]
环境：windows 10

问题：
1. void YoloLayerPlugin::forwardGpu(const float* const* inputs, float *output, cudaStream_t stream, int batchSize)
inputs 如何打印，里面存放的数据顺序是什么

在debug的时候，老是显示，无法获取内存 input[0][0]

2. 为什么 通过如下的方式，可以获得对应的数据
 idx + k * info_len_i * total_grid + 4 * total_grid

在pytorch  中 det 0是 1，3，80，80，85，这个地方是如何对应上的

**Comment by wang-xinyu** [comment]
You can mark the layer before yololayer as output layer. and print it.
