### ISSUE TITLE
yolov4

### ISSUE THREAD

**Issue by mingwz** [wang-xinyu/tensorrtx#869]
- jeston Nano（4G）, 
- Cuda 10.2
- TensorRT 8.0.1.6
-
作者，你好：
        上面的环境是jeston本身就配好的，我在进行make时遇到了这样的错误：

/home/zmw/tensorrtx/yolov4/mish.h(31): error: member function declared with "override" does not override a base class member

/home/zmw/tensorrtx/yolov4/mish.h(31): warning: function "nvinfer1::IPluginV2::enqueue(int32_t, const void *const *, void *const *, void *, cudaStream_t)" is hidden by "nvinfer1::MishPlugin::enqueue" -- virtual function override intended?

/home/zmw/tensorrtx/yolov4/mish.h(62): warning: function "nvinfer1::IPluginV2Ext::configurePlugin(const nvinfer1::Dims *, int32_t, const nvinfer1::Dims *, int32_t, const nvinfer1::DataType *, const nvinfer1::DataType *, const __nv_bool *, const __nv_bool *, nvinfer1::PluginFormat, int32_t)" is hidden by "nvinfer1::MishPlugin::configurePlugin" -- virtual function override intended?

/home/zmw/tensorrtx/yolov4/mish.h(64): error: exception specification for virtual function "nvinfer1::MishPlugin::detachFromContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::detachFromContext"

/home/zmw/tensorrtx/yolov4/mish.h(62): error: exception specification for virtual function "nvinfer1::MishPlugin::configurePlugin" is incompatible with that of overridden function "nvinfer1::IPluginV2IOExt::configurePlugin(const nvinfer1::PluginTensorDesc *, int32_t, const nvinfer1::PluginTensorDesc *, int32_t)"

/home/zmw/tensorrtx/yolov4/mish.h(29): error: exception specification for virtual function "nvinfer1::MishPlugin::getWorkspaceSize" is incompatible with that of overridden function "nvinfer1::IPluginV2::getWorkspaceSize"

/home/zmw/tensorrtx/yolov4/mish.h(27): error: exception specification for virtual function "nvinfer1::MishPlugin::terminate" is incompatible with that of overridden function "nvinfer1::IPluginV2::terminate"

/home/zmw/tensorrtx/yolov4/mish.h(25): error: exception specification for virtual function "nvinfer1::MishPlugin::initialize" is incompatible with that of overridden function "nvinfer1::IPluginV2::initialize"

/home/zmw/tensorrtx/yolov4/mish.h(23): error: exception specification for virtual function "nvinfer1::MishPlugin::getOutputDimensions" is incompatible with that of overridden function "nvinfer1::IPluginV2::getOutputDimensions"

/home/zmw/tensorrtx/yolov4/mish.h(88): error: exception specification for virtual function "nvinfer1::MishPluginCreator::deserializePlugin" is incompatible with that of overridden function "nvinfer1::IPluginCreator::deserializePlugin"

/home/zmw/tensorrtx/yolov4/mish.h(80): error: exception specification for virtual function "nvinfer1::MishPluginCreator::getPluginName" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginName"

/home/zmw/tensorrtx/yolov4/mish.cu(107): error: object of abstract class type "nvinfer1::MishPlugin" is not allowed:
            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider

/home/zmw/tensorrtx/yolov4/mish.cu(181): error: object of abstract class type "nvinfer1::MishPlugin" is not allowed:
            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider

/home/zmw/tensorrtx/yolov4/mish.cu(190): error: object of abstract class type "nvinfer1::MishPlugin" is not allowed:
            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider

32 errors detected in the compilation of "/tmp/tmpxft_00001fe9_00000000-6_mish.cpp1.ii".
CMake Error at myplugins_generated_mish.cu.o.Debug.cmake:279 (message):
  Error generating file
  /home/zmw/tensorrtx/yolov4/build/CMakeFiles/myplugins.dir//./myplugins_generated_mish.cu.o

CMakeFiles/myplugins.dir/build.make:70: recipe for target 'CMakeFiles/myplugins.dir/myplugins_generated_mish.cu.o' failed
make[2]: *** [CMakeFiles/myplugins.dir/myplugins_generated_mish.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myplugins.dir/all' failed
make[1]: *** [CMakeFiles/myplugins.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
[CMakeLists.txt](https://github.com/wang-xinyu/tensorrtx/files/7799090/CMakeLists.txt)

不知道是我的环境太新了，还是我的CMakeLists.txt文件中路径写错了

**Comment by wang-xinyu** [comment]
it's using trt7 api,  for trt8 api migration, you can refer to yolov5

**Comment by mingwz** [comment]
对，就是版本问题，我把版本降下来后，仿照你给的cmakelixt.txt,就可以了.
