### ISSUE TITLE
make failed in yolov4

### ISSUE THREAD

**Issue by chenhaoCSDN** [wang-xinyu/tensorrtx#87]
/usr/local/TensorRT-7.0.0.11/include/NvInferPluginUtils.h:250:23: note: declared here
 struct TRT_DEPRECATED RegionParameters
                       ^~~~~~~~~~~~~~~~
[100%] Linking CXX executable yolov4
/usr/bin/ld: 找不到 -lnvinfer
collect2: error: ld returned 1 exit status
CMakeFiles/yolov4.dir/build.make:137: recipe for target 'yolov4' failed
make[2]: *** [yolov4] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov4.dir/all' failed
make[1]: *** [CMakeFiles/yolov4.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
我是安装的trt7.0,用的tar安装的，大佬帮忙看下呗。感谢

**Comment by wang-xinyu** [comment]
tar安装的不是系统目录，需要改cmake指定路径，或者给放到系统目录

**Comment by chenhaoCSDN** [comment]
谢谢，已解决
