### ISSUE TITLE
batch 为2时，第一张图，识别是不对的，第二张识别对的，什么问题？

### ISSUE THREAD

**Issue by xinsuinizhuan** [wang-xinyu/tensorrtx#870]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
did you rebuild and re-serialize engine?

**Comment by xinsuinizhuan** [comment]
我的步骤：
1、官网的yolov5s.pt模型，生成wts文件
2、修改batch为2，使用wts，生成engine文件
3、使用生成的engine文件，同时输出2张图像推理。
训练生成yolov5s.pt时，也需要设置batch为2吗？我直接使用的官网的

**Comment by xinsuinizhuan** [comment]
重新生成engine的是，设置了batch后，我看只有这里：builder->setMaxBatchSize(maxBatchSize);
推理的时候，感觉是这里，第一张图像被压缩和覆盖了：
 float* buffer_idx = (float*)buffers[inputIndex];
        for (int b = 0; b < fcount; b++) {
            cv::Mat img = cv::imread(img_dir + "/" + file_names[f - fcount + 1 + b]);
            if (img.empty()) continue;
            imgs_buffer[b] = img;
            size_t  size_image = img.cols * img.rows * 3;
            size_t  size_image_dst = INPUT_H * INPUT_W * 3;
            //copy data to pinned memory
            memcpy(img_host,img.data,size_image);
            //copy data to device memory
            CUDA_CHECK(cudaMemcpyAsync(img_device,img_host,size_image,cudaMemcpyHostToDevice,stream));
            preprocess_kernel_img(img_device, img.cols, img.rows, buffer_idx, INPUT_W, INPUT_H, stream);       
            buffer_idx += size_image_dst;
        }

**Comment by liuqi123123** [comment]
我试了batchsize为2，没出现什么问题。你试试当batchsize=4,8时有没问题

**Comment by xinsuinizhuan** [comment]
> 

![图片](https://user-images.githubusercontent.com/40679769/148316269-6503c00b-7fcc-4d23-bd69-f0e9ec48cab0.png)
这是识别的2张图，第一张有问题，第二张正常

**Comment by liuqi123123** [comment]
我截你的第一张图，复制4份，然后设置batchsize=2,跑出来是正常的。
你首先确定图像是小于3000*3000的，然后换个batchsize（3，4，8等等）试试，看有没问题

**Comment by xinsuinizhuan** [comment]
> 我截你的第一张图，复制4份，然后设置batchsize=2,跑出来是正常的。 你首先确定图像是小于3000*3000的，然后换个batchsize（3，4，8等等）试试，看有没问题

我发现，当我图像尺寸一样大小时是正常的，但是，当我2张图像尺寸大小不一样时，是不对的

**Comment by xinsuinizhuan** [comment]
batch = 4:
我同一张图像4次放入识别，正常：
![图片](https://user-images.githubusercontent.com/40679769/148318126-75360a26-c235-41a7-b8ae-5f1ea748fc77.png)
不同四张图像放入，就最后一张正常，前面三张都是乱的：
![图片](https://user-images.githubusercontent.com/40679769/148318299-69fb9f05-a976-45f4-97b0-09070818b1e3.png)

**Comment by liuqi123123** [comment]
我这边不同的图片也是正确的。你重新生成引擎了吧？

**Comment by xinsuinizhuan** [comment]
> 

您指定重新生成引擎是指什么？
batch=4后，我重新生成了engine了

**Comment by liuqi123123** [comment]
总结一下，你的情况是： 只有batchsize=1的时候，输出才是正确的，试过的其他batchszie都是错的？

**Comment by xinsuinizhuan** [comment]
> 3000*3000

MAX_IMAGE_INPUT_SIZE_THRESH 我设置的是8000*8000，四张图总大小加起来，都小于这个尺寸

**Comment by xinsuinizhuan** [comment]
> 总结一下，你的情况是： 只有batchsize=1的时候，输出才是正确的，试过的其他batchszie都是错的？

我现在的情况是：
batchsize=1的时候，输出是正常的；
batchsize=2的时候，2张同样图，识别正常，2张不同尺寸图，就最后一张正常，第一张识别不正常；
batchsize=4的时候，4张同样图，识别正常，4张不同尺寸图，就最后一张正常，前三张都识别不正常；

**Comment by xinsuinizhuan** [comment]
> 总结一下，你的情况是： 只有batchsize=1的时候，输出才是正确的，试过的其他batchszie都是错的？

咋样，大佬，有没有思路？您那都是正常的吗？

**Comment by liuqi123123** [comment]
我这边的输出都是正常的。不过我的代码是刚加cuda预处理后的版本。最新版本的代码我还没尝试。等到下周我忙完了再帮你看看吧

**Comment by xinsuinizhuan** [comment]
> 
好的。感谢大佬，可否加个微信？

**Comment by xinsuinizhuan** [comment]
> 我这边的输出都是正常的。不过我的代码是刚加cuda预处理后的版本。最新版本的代码我还没尝试。等到下周我忙完了再帮你看看吧

好的。感谢大佬，可否加个微信？

**Comment by liuqi123123** [comment]
有啥事就在这上面说吧，或者群里问就行

**Comment by xinsuinizhuan** [comment]
> 有啥事就在这上面说吧，或者群里问就行

How about this issues?

**Comment by liuqi123123** [comment]
我试过了最新代码。 batchsize = 3后也没问题。你是否按照以下步骤来的：
1.在yolov5.cpp中 将#define BATCH_SIZE 改为5后，保存文件。
2.重新make
3.执行./yolov5 -s yolov5s.wts yolov5s.engine s  生成新的引擎
4.执行./yolov5 -d yolov5s.engine ../samples  推理图片

**Comment by xinsuinizhuan** [comment]
> 我试过了最新代码。 batchsize = 3后也没问题。你是否按照以下步骤来的： 1.在yolov5.cpp中 将#define BATCH_SIZE 改为5后，保存文件。 2.重新make 3.执行./yolov5 -s yolov5s.wts yolov5s.engine s 生成新的引擎 4.执行./yolov5 -d yolov5s.engine ../samples 推理图片

您确认可以吗？
我使用最新的代码，刚刚跑了一遍，使用yolov5s的模型导出的wts，然后导出的batch=4的模型，
都是最新的源码，里面设置的 BATCH_SIZE =4，推理
同一个文件夹下，放同一张图复制4份：
![图片](https://user-images.githubusercontent.com/40679769/150110581-32379f13-126e-45b3-94cf-cb9bba44d94c.png)
结果是对的：
![图片](https://user-images.githubusercontent.com/40679769/150110655-ae5a2e27-8fff-4ff8-a1dc-afb4940efc2a.png)
 但是，同一个文件下，放不同的四张图：
![图片](https://user-images.githubusercontent.com/40679769/150110745-fe5f3522-8855-4b7d-81ef-6317570853f3.png)
推理结果都是乱的：
![图片](https://user-images.githubusercontent.com/40679769/150110858-afddfc9e-1b4f-41cd-b9f0-195a63bc4120.png)
就最后一张是正确的，前三张都是不对的

**Comment by xinsuinizhuan** [comment]
> 我试过了最新代码。 batchsize = 3后也没问题。你是否按照以下步骤来的： 1.在yolov5.cpp中 将#define BATCH_SIZE 改为5后，保存文件。 2.重新make 3.执行./yolov5 -s yolov5s.wts yolov5s.engine s 生成新的引擎 4.执行./yolov5 -d yolov5s.engine ../samples 推理图片

[tensorrt_yolov5.zip](https://github.com/wang-xinyu/tensorrtx/files/7896187/tensorrt_yolov5.zip)
这是推理代码，您看看

**Comment by xinsuinizhuan** [comment]
最新代码里面，我把数据拷贝换成v5版本里面的Data拷贝模式，可以。所以新版本里面的数据拷贝，从host到device有问题

**Comment by liuqi123123** [comment]
你解决了就好。具体是哪里的代码除了问题，能分享下吗？

**Comment by xinsuinizhuan** [comment]
> 你解决了就好。具体是哪里的代码除了问题，能分享下吗？

其实，我没有解决掉问题。现在的图像数据拷贝是直接cuda拷贝，我感觉是高效的，直接再cuda里面，可以减少cpu图像预处理和cpu gpu来回传图，但是感觉这里host到device的数据拷贝有问题，数据排列不对：
![图片](https://user-images.githubusercontent.com/40679769/150265893-c41f8d91-f90a-4e98-b2ae-dfa375e1a085.png)
具体问题是什么，还不知道，烦请帮忙看一下。

而yolov5v5版本里面数据预处理和拷贝是这样的，都是在cpu内部处理，比较低效：
![图片](https://user-images.githubusercontent.com/40679769/150266095-897ef038-e314-4967-8a98-cf8143fb4307.png)

**Comment by xinsuinizhuan** [comment]
> 你解决了就好。具体是哪里的代码除了问题，能分享下吗？

原来yolov5v5版本里面的，数据拷贝方式，可以正常batch推理，不论图像大小一样不一样。但是最新版的里面，只有四张图一样的时候，才是对的，四张图不一样和尺寸不一样，推理结果都不对。

**Comment by liuqi123123** [comment]
你是什么硬件平台？我看看此问题会不会和平台相关

**Comment by xinsuinizhuan** [comment]
> 你是什么硬件平台？我看看此问题会不会和平台相关

windows10
VS019
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:35_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28845127_0

**Comment by xinsuinizhuan** [comment]
> 你是什么硬件平台？我看看此问题会不会和平台相关

请问有结果吗？

**Comment by wang-xinyu** [comment]
@xinsuinizhuan Cannot reproduce your issue.  I tried batch=4, the output images are fine.
Please use the default code without any changes to test.

cc: @liuqi123123

**Comment by xinsuinizhuan** [comment]
> @xinsuinizhuan Cannot reproduce your issue. I tried batch=4, the output images are fine. Please use the default code without any changes to test.
> 
> cc: @liuqi123123

默认代码：
![图片](https://user-images.githubusercontent.com/40679769/152902043-6852bf1c-9329-4e3f-b196-203580edeaf2.png)
由于编译不过，修改了一点点：
direct目录包含更换为“”
![图片](https://user-images.githubusercontent.com/40679769/152902080-c8f4c96a-dbd5-4d48-8d08-c5bc3f3bae71.png)
去掉API
![图片](https://user-images.githubusercontent.com/40679769/152902114-dbd30cdd-a1ec-426b-ae73-0e73c0168d46.png)
batch改为4
![图片](https://user-images.githubusercontent.com/40679769/152902183-193fcae3-6e1d-4f53-a0bf-cdca58267cd8.png)
就改了这三个地方
推理命令：
-d yolov5s.engine ./testimg
推理结果：
![图片](https://user-images.githubusercontent.com/40679769/152902464-e970d811-808d-41bf-a538-e9639c107317.png)
依然是第一张对的，后面三张都不对

**Comment by tms2003** [comment]
我也遇到这个问题。只要batchsize>1 就有问题。但最后一个图却是对的。开始以为我的程序问题，最后才发现是tensorrtx的问题。

**Comment by xinsuinizhuan** [comment]
> 我也遇到这个问题。只要batchsize>1 就有问题。但最后一个图却是对的。开始以为我的程序问题，最后才发现是tensorrtx的问题。

最后解决了吗？是tensorrtx的问题？哪个版本的问题吗？

**Comment by ForBetterDl** [comment]
我也遇到这个问题，假设四张图片的名字是1，2，3，4，我进行batch预处理操作后，把float的图像重新存下来，发现buffers中存的四幅图是2，3，4，4.所以只有最后一幅图是正确的，第一张图被覆盖掉了。2，3两幅图的结果是下一个图的检测结果。原因不明。

**Comment by xinsuinizhuan** [comment]
> 

对的，我也是这个情况，但是作者这边一直没有复现，所有也最后没有解决掉。

**Comment by ForBetterDl** [comment]
后来通过其他方法解决了。

**Comment by xinsuinizhuan** [comment]
> 后来通过其他方法解决了。

怎么解决的？

**Comment by karenyun** [comment]
Hi, @xinsuinizhuan ,
I think maybe I find the problem.

You can try to modify the `line 397` in yolov5.cpp to `CUDA_CHECK(cudaMemcpy(img_device,img_host,size_image*sizeof(float),cudaMemcpyHostToDevice));`.

**Comment by sl3120** [comment]
> 你是什么硬件平台？我看看此问题会不会和平台相关

我也遇见了相似的问题，我把batch size设置成16之后，有一部分图片结果是正确的，另外一部分绘制的是其他图片的识别结果，感觉有错乱，我在另外一个设备上测试的是正常的。

错误的设备的环境如下：
RTX2080 + Windows 10 + cuda 10.2 + TensorRT-7.0.0.11 + 驱动版本472.12/465/512都有错。

正确的设备的环境如下：
GTX1650 + Windows 10 + cuda 10.2 + TensorRT-7.0.0.11 + 驱动版本472.19

**Comment by xinsuinizhuan** [comment]
> 这个问题有进展吗。。。我是利用yolov5官方的v6.1 的export.py转的engine，直接利用这里的repo编译，出来的图没有结果，没有bbox

直接转的貌似不行，需要利用作者的genwts.py生成wts，再转engine

**Comment by dao027** [comment]
> > 这个问题有进展吗。。。我是利用yolov5官方的v6.1 的export.py转的engine，直接利用这里的repo编译，出来的图没有结果，没有bbox
> 
> 直接转的貌似不行，需要利用作者的genwts.py生成wts，再转engine

收到~非常感谢回复

**Comment by xuhuanzy** [comment]
一样的问题, 请问现在有解决的方案吗?
目测又是window环境导致的问题, 作者是linux环境肯定没有问题的.

**Comment by RookieAI** [comment]
我也是同样的问题，源代码除了batchsize其他都没改，windows平台加RTX2080Ti

**Comment by wang-xinyu** [comment]
@RookieAI Did you rebuild everything after changing batchsize?

**Comment by RookieAI** [comment]
> @RookieAI Did you rebuild everything after changing batchsize?

yes, only modify #define BATCH_SIZE 1 => #define BATCH_SIZE 2, then rebuild, and cmd run YOLOv5TRT-6.2.exe -s yolov5.wts yolov5s.engine s and YOLOv5TRT-6.2.exe -d yolov5s.engine ./samples. I got the correct result with zidane.jpg and wrong with bus.jpg

**Comment by wang-xinyu** [comment]
Can you try ubuntu? or other linux? I doubt it's a bug in windows tensorrt.

**Comment by RookieAI** [comment]
> Can you try ubuntu? or other linux? I doubt it's a bug in windows tensorrt.

OK. I will try, thank you!

**Comment by hch-baobei** [comment]
I am working on ubuntu and the model inference results are having problems after changing batch_size. (All h dimensions in [xywh] are 0). I re-build after each change

**Comment by wang-xinyu** [comment]
Hey guys, we have found the bug, and fixed in this commit -> https://github.com/wang-xinyu/tensorrtx/commit/aac418e1f0d1a04179ac864a3525af424239825d
