### ISSUE TITLE
Assertion 'fc->nbFields == 2' failed

### ISSUE THREAD

**Issue by hygxy** [wang-xinyu/tensorrtx#871]
## Env

- GPU, Xavier NX,
- OS, Ubuntu18.04
- Cuda version, cuda 10.2
- TensorRT version 8.0.1.6

## About this repo

- which branch/tag/commit are you using? Yolov5-4.0(with [Fix Yolov5 for TensorRT 8 support](https://github.com/wang-xinyu/tensorrtx/pull/540/commits/92eef6353726abba5cbdf4b056377a1e34abd487) added)
- which model? yolov5s

## Your problem
```
yolov5: ~/tensorrtx/yolov5/yololayer.cu:289: virtual nvinfer1::IPluginV2IOExt* nvinfer1::YoloPluginCreator::createPlugin(const char*, const nvinfer1::PluginFieldCollection*): Assertion `fc->nbFields == 2' failed.
Aborted
```

- what is your command? `sudo ./yolov5 -s yolov5s.wts yolov5s.engine s`
- what's your output?
 `yolov5: ~/tensorrtx/yolov5/yololayer.cu:289: virtual nvinfer1::IPluginV2IOExt* nvinfer1::YoloPluginCreator::createPlugin(const char*, const nvinfer1::PluginFieldCollection*): Assertion 'fc->nbFields == 2' failed.
Aborted`
- what output do you expect?
 yolov5s executes successfully

**Comment by wang-xinyu** [comment]
make sure you are using yolov5-4.0 pytorch model
