### ISSUE TITLE
Arcface subcenter support?

### ISSUE THREAD

**Issue by Alex18947** [wang-xinyu/tensorrtx#878]
Hi, I downloaded the [Arcface subcenter](https://github.com/deepinsight/insightface/tree/master/recognition/subcenter_arcface) pretrained model from the original repo and tried to test the r100-arcface-msfdrop75 model.

I adapted arcface-r100.cpp basically just to reflect some minor changes to the names of the layers and successfully generated the WTS file. While doing inference, however, all image pairs have the similarity of 1 :). Obviously, I am still missing something on my way from Arcface to Arface subcenter, maybe some image format changes or whatever. What further steps am I missing?

**Comment by wang-xinyu** [comment]
@ybw108 Any suggestions?

**Comment by qqwya** [comment]
请问arcface的trt版本是哪个版本
