### ISSUE TITLE
sudo ./yolov4 -s failed

### ISSUE THREAD

**Issue by chenhaoCSDN** [wang-xinyu/tensorrtx#88]
sudo ./yolov4 -s
./yolov4: error while loading shared libraries: libcublas.so.10.0: cannot open shared object file: No such file or directory
这是不是由于配置的路径不对导致的，我改修改哪里？感谢大佬

**Comment by wang-xinyu** [comment]
cublas是cuda的，如果是tar安装的，要看cuda的lib路径，改cmake

**Comment by chenhaoCSDN** [comment]
> cublas是cuda的，如果是tar安装的，要看cuda的lib路径，改cmake

cmake_minimum_required(VERSION 2.6)

project(yolov4)

add_definitions(-std=c++11)

option(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE Debug)

find_package(CUDA REQUIRED)

set(CUDA_NVCC_PLAGS ${CUDA_NVCC_PLAGS};-std=c++11;-g;-G;-gencode;arch=compute_30;code=sm_30)

include_directories(${PROJECT_SOURCE_DIR}/include)
if (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
    message("embed_platform on")
    include_directories(/usr/local/cuda/targets/aarch64-linux/include)
    link_directories(/usr/local/cuda/targets/aarch64-linux/lib)
else()
    message("embed_platform off")
    include_directories(/usr/local/cuda/include)
    include_directories(/usr/local/TensorRT-7.0.0.11/include)
    link_directories(/usr/local/TensorRT-7.0.0.11/lib)
    link_directories(/usr/local/cuda/lib64)
endif()


set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Ofast -Wfatal-errors -D_MWAITXINTRIN_H_INCLUDED")

cuda_add_library(myplugins SHARED ${PROJECT_SOURCE_DIR}/yololayer.cu ${PROJECT_SOURCE_DIR}/mish.cu)

find_package(OpenCV)
include_directories(OpenCV_INCLUDE_DIRS)

add_executable(yolov4 ${PROJECT_SOURCE_DIR}/yolov4.cpp)
target_link_libraries(yolov4 nvinfer)
target_link_libraries(yolov4 cudart)
target_link_libraries(yolov4 myplugins)
target_link_libraries(yolov4 ${OpenCV_LIBS})

add_definitions(-O2 -pthread)
已经改了，

**Comment by wang-xinyu** [comment]
`ldd yolov4`

能看到有没有链接上

**Comment by chenhaoCSDN** [comment]
> ldd yolov4

	libcublas.so.10.0 => /usr/local/cuda-10.0/lib64/libcublas.so.10.0 (0x00007fa448dc3000)
关于cuda的都是链接的这里

**Comment by wang-xinyu** [comment]
试试不加sudo呢

**Comment by chenhaoCSDN** [comment]
> 试试不加sudo呢
已经成功了，谢谢您，同时感谢您出色的工作
