### ISSUE TITLE
yolov3：支持输出框里对象对应的label吗/支持转换为JNI吗

### ISSUE THREAD

**Issue by Ruizzzzzz** [wang-xinyu/tensorrtx#880]
## About this repo

- which branch/tag/commit are you using? master
- which model? yolov3

## Your problem

- 请问，项目支持输出框里对象对应的label嘛
- 请问，项目支持转换为native的形式嘛，可以使得Java通过JNI调用，从而在大规模分布式系统中使用

**Comment by wang-xinyu** [comment]
NO
NO

**Comment by Ruizzzzzz** [comment]
是的，问题已经解决了，忘记关闭issue了，谢谢。
