### ISSUE TITLE
UNet Serialization Error

### ISSUE THREAD

**Issue by barryyan0121** [wang-xinyu/tensorrtx#881]
## Env

- GPU: MX250
- OS: Win10
- Cuda: 10.2 
- TensorRT 8
- CMake 3.20.5
- OpenCV 4.5.3 (OpenVino Version)

## About this repo

- which branch/tag/commit are you using?
(https://github.com/wang-xinyu/tensorrtx/commit/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7)

- which model? 
Pytorch-UNet (https://github.com/milesial/Pytorch-UNet/commit/e1a69e7c6ce18edd47271b01e4aabc03b436753d)
All Default Parameters 
`--amp==True`

## Your problem

- what is your command? 
`unet.exe -s`
- what's your output?
```
Loading weights: ../../unet.wts
set name out
Building engine, please wait for a while...
[01/14/2022-14:03:40] [E] [TRT] 10: [optimizer.cpp::nvinfer1::builder::`anonymous-namespace'::LeafCNode::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node (Unnamed Layer* 34) [Deconvolution] + (Unnamed Layer* 35) [Padding].)
Build engine successfully!
```
- what output do you expect?
```
Loading weights: ../../unet.wts
set name out
Building engine, please wait for a while...
Build engine successfully!
```

Does it have something to do with network size? I also changed second parameter to 2 in
https://github.com/wang-xinyu/tensorrtx/blob/5f1b048a29e2fcd9eb85b780c89b90a4f052a3b7/unet/unet.cpp#L124 
because `n_classes = 2`.

**Comment by wang-xinyu** [comment]
try default pretrained model first
