### ISSUE TITLE
YOLOv5s6模型转engine,失败了？

### ISSUE THREAD

**Issue by xinsuinizhuan** [wang-xinyu/tensorrtx#882]
模型参数，S模型，类型FP_32，类型个数80，转换的时候，崩溃，失败了？

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/150314548-a8c324ae-dd35-44b8-a7d9-aa9dc86db0bb.png)

**Comment by xinsuinizhuan** [comment]
是否 6模型的时候，需要开启is_p6 = true?

**Comment by xinsuinizhuan** [comment]
已经解决。抱歉，打扰，关闭即可。

**Comment by philtell** [comment]
> 

怎么解决的？

**Comment by godyenchang** [comment]
# Env

- Cuda:11.3.0
- TensorRT:8.2.2.1
- OpenCV:4.5.5
- cudnn:8.2.1

# Your problem
我在執行`sudo ./yolov5 -s yolov5s.wts yolov5s.engine s`這個指令的時候顯示了下面的錯誤,要如何解決它？
是不是跟你一樣的問題？


```
Loading weights: yolov5s.wts
[01/27/2022-01:17:43] [E] [TRT] 3: [network.cpp::addScale::737] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/network .cpp::addScale::737, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
)
yolov5: /home/es7111/Desktop/ubuntu/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
```

**Comment by fdh0** [comment]
> 已经解决。抱歉，打扰，关闭即可。

how u solve it? please

**Comment by shandafu** [comment]
> # Env
> * Cuda:11.3.0
> * TensorRT:8.2.2.1
> * OpenCV:4.5.5
> * cudnn:8.2.1
> 
> # Your problem
> 我在執行`sudo ./yolov5 -s yolov5s.wts yolov5s.engine s`這個指令的時候顯示了下面的錯誤,要如何解決它？ 是不是跟你一樣的問題？
> 
> ```
> Loading weights: yolov5s.wts
> [01/27/2022-01:17:43] [E] [TRT] 3: [network.cpp::addScale::737] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/network .cpp::addScale::737, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
> )
> yolov5: /home/es7111/Desktop/ubuntu/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
> ```

我也遇到相同的问题，请问解决了吗？
