### ISSUE TITLE
How to return the result mapping into coco.names or any.names 

### ISSUE THREAD

**Issue by saikrishnadas** [wang-xinyu/tensorrtx#89]
May i know what changes should i make to track the coco.names instead of ids ?

@wang-xinyu 

Sry, I not that familiar with c++

**Comment by wang-xinyu** [comment]
The id is corresponding to https://github.com/ultralytics/yolov3/blob/master/data/coco.names.
From 0 to 79.
You can add a vector or array or whatever in cpp to define coco.names.  And find the names using the id.

**Comment by saikrishnadas** [comment]
@wang-xinyu 

May I know the name of the variable that is used to get the id ?

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/5d879b5886895bdf7f052e708794261679cd10db/yolov3-spp/yolov3-spp.cpp#L563


class_id
