### ISSUE TITLE
 yolov5轉engine 失敗

### ISSUE THREAD

**Issue by godyenchang** [wang-xinyu/tensorrtx#891]
# Env

- Cuda:11.3.0
- TensorRT:8.2.2.1
- OpenCV:4.5.5
- cudnn:8.2.1

# About this repo
YOLOv5 v5.0
# Your problem
我在執行`sudo ./yolov5 -s yolov5s.wts yolov5s.engine s`這個指令的時候顯示了下面的錯誤,要如何解決它？
前面幾個步驟執行都是正確的,到這邊才出錯

```
Loading weights: yolov5s.wts
[01/27/2022-01:17:43] [E] [TRT] 3: [network.cpp::addScale::737] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/network .cpp::addScale::737, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
)
yolov5: /home/es7111/Desktop/ubuntu/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
```

**Comment by wang-xinyu** [comment]
Pls follow readme and try official model first.

**Comment by Yaoxingtian** [comment]
> 

hi, i meet this problem too. 
have you solved it ?

**Comment by xiaoleitongxue** [comment]
我和你遇到了相同的问题，我通过匹配版本解决了这一问题，必须保证tensorrtx, yolov5, yolov5s.pt这三者的版本一致。
我的环境如下图
![image](https://github.com/wang-xinyu/tensorrtx/assets/37171564/4d081fbe-a049-4a24-a714-d0dc6cc97c75)
我使用的yolov5 版本是7.0，使用的tensortx版本是tensorrtx-yolov5-v7.0， 模型文件的版本也是7.0
