### ISSUE TITLE
/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed.

### ISSUE THREAD

**Issue by StawEndl** [wang-xinyu/tensorrtx#896]
sorry, i got a problem.

aaeon@aaeon-desktop:~/Public/tensorrtx_v5.0/yolov5/build$ sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
[sudo] password for aaeon:
Loading weights: yolov5s.wts
Building engine, please wait for a while...
Build engine successfully!
CUDA error 1 at /home/aaeon/Public/tensorrtx_v5.0/yolov5/yololayer.cu:52yolov5: /home/aaeon/Public/tensorrtx_v5.0/yolov5/yololayer.cu:52: virtual nvinfer1::YoloLayerPlugin::~YoloLayerPlugin(): Assertion `0' failed.

if you can give me some tips, i will be appreciate.

**Comment by Monday-Leo** [comment]
I have the same error.Have you solved it?

**Comment by Monday-Leo** [comment]
I solve it! Just use the latest gen_wts.py to convert the .pt to .wts. You can get the correct result.
