### ISSUE TITLE
Doubt about post_process

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [wang-xinyu/tensorrtx#898]
## About this repo

yolov5

## Your problem

I have a doubt about the code, when post-processing, why 6000 positions are passed, i.e. why is the `i` multiplied by 6001?

```
for i in range(self.batch_size):
            result_boxes, result_scores, result_classid = self.post_process(
                output[i * 6001: (i + 1) * 6001], batch_origin_h[i], batch_origin_w[i]
            )
```

Thanks a lot!

**Comment by wang-xinyu** [comment]
maybe check the yololayer plugin, 6001 is the output size of the plugin
