### ISSUE TITLE
RetinaFace different dimensions error

### ISSUE THREAD

**Issue by adityalohia29** [wang-xinyu/tensorrtx#9]
Hi, 

Thank you for your excellent work. This has really helped me in understand how to work with TensorRT. 

I was trying to re-create the RetinaFace model with different dimensions as I have noticed that there is no limitation to how big or small the image has to be. I tried changing the INPUT_H and INPUT_W in the decode.h file, however, when serializing the model it throws an error of mismatch dimensions. 

> ERROR: (Unnamed Layer* 182) [ElementWise]: elementwise inputs must have same dimensions or follow broadcast rules (input dimensions were [256,53,53] and [256,54,54]).

Can you please guide me on what I can do to solve this?

**Comment by wang-xinyu** [comment]
@adityalohia29 what's the input shape you were using?   please be noted that the input h and w must be able to be divided by 32.

**Comment by adityalohia29** [comment]
Thanks for the help. I just checked and one of my input size is not divisible by 32. One more question, is there a way by which we can make the input size dynamic? What I mean is without having to recreate the engine, will the accuracy drop if we change the input shape while we are passing the image to the network?

**Comment by wang-xinyu** [comment]
For dynamic input shape, you can refer to https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes.   

 But this property was supported from maybe tensorrt6.0,  I am not sure.

**Comment by aditya-droid** [comment]
Yeah, I am using TensorRT 7 so I think that is supported. Thanks for the help.

**Comment by adityalohia29** [comment]
Thanks. I am using TensorRT 7 so I don't think this will be a problem to implement.
