### ISSUE TITLE
make failed，please help!!!

### ISSUE THREAD

**Issue by caikw0602** [wang-xinyu/tensorrtx#90]
jetbot@jetbot:~/tensorrtx/yolov3-spp/build$ make
embed_platform on
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jetbot/tensorrtx/yolov3-spp/build
[ 25%] Building NVCC (Device) object CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o
/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(57): error: not a class or struct name

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(65): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(70): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(72): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(74): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(76): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(78): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(80): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(82): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(84): error: identifier "PluginTensorDesc" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(84): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(88): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(90): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(92): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(94): error: identifier "IPluginV2IOExt" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(94): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(96): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(98): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(100): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(102): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(104): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(106): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(109): error: identifier "PluginTensorDesc" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(109): error: identifier "PluginTensorDesc" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(109): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(111): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(85): error: name followed by "::" must be a class or namespace name

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(135): error: identifier "IPluginV2IOExt" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(135): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::createPlugin"

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(135): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(137): error: identifier "IPluginV2IOExt" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(137): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::deserializePlugin"

/home/jetbot/tensorrtx/yolov3-spp/yololayer.h(137): error: member function declared with "override" does not override a base class member

/home/jetbot/tensorrtx/yolov3-spp/yololayer.cu(99): error: identifier "PluginTensorDesc" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.cu(99): error: identifier "PluginTensorDesc" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.cu(127): error: identifier "IPluginV2IOExt" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.cu(243): error: identifier "IPluginV2IOExt" is undefined

/home/jetbot/tensorrtx/yolov3-spp/yololayer.cu(250): error: identifier "IPluginV2IOExt" is undefined

38 errors detected in the compilation of "/tmp/tmpxft_00004806_00000000-6_yololayer.cpp1.ii".
CMake Error at yololayer_generated_yololayer.cu.o.Debug.cmake:279 (message):
  Error generating file
  /home/jetbot/tensorrtx/yolov3-spp/build/CMakeFiles/yololayer.dir//./yololayer_generated_yololayer.cu.o

CMakeFiles/yololayer.dir/build.make:336: recipe for target 'CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/yololayer.dir/yololayer_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yololayer.dir/all' failed
make[1]: *** [CMakeFiles/yololayer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang-xinyu** [comment]
This is using tensorrt7.0,  you tensorrt version may not right.

**Comment by cwlinghk** [comment]
any hints on how to migrate to tensorrt 8? thanks

**Comment by wang-xinyu** [comment]
Yolov5 and Yolov3 in this repo support 8.x.
You can refer to those 2.
