### ISSUE TITLE
Yolov5: Engine creation from .wts file takes long time (approximately 45 minutes)

### ISSUE THREAD

**Issue by rgkannan676** [wang-xinyu/tensorrtx#900]
## Env

- GPU : 2080 Ti
- OS : Win10
- Cuda version : CUDA_v11.1
- TensorRT version : TensorRT-7.2.3.4

## About this repo
- which model? yolov5s

## Your problem

- what is your command? yolov5 -s [.wts] [.engine]
- The engine creation from a .wts file takes more than 45 minutes for Yolov5 s model. Can you please advise what is the reason for this delay and  how to reduce the time needed for engine creation?

**Comment by wang-xinyu** [comment]
Seems it's slow in windows, which is a common issue.
