### ISSUE TITLE
The .engine takes too much time to detect

### ISSUE THREAD

**Issue by saikrishnadas** [wang-xinyu/tensorrtx#91]
Hey, 
I had a issue that makes my model not effective. So, This .engine created from your repo, works or detects slow on the first image and faster on second image onwards.
First image take around(~1700ms) and 2nd image onwards (~60ms)(Used as batch of images in sample files). Im aware that it need to load the weight but when i create api call to run this, as my api call sends in one image and detects that image. so, it takes so much time to detect the images!
Any solution or suggestions ?
@wang-xinyu

**Comment by saikrishnadas** [comment]
any update on this @wang-xinyu ?

**Comment by wang-xinyu** [comment]
I don't get it. The deserializing process and first image will take a bit long time.  But it will be normal from second image.      You can adapt it so that it only initialize once.

**Comment by saikrishnadas** [comment]
Yeah exactly, but when I make a api out of it, each api call makes deserializing process again.
How do I initialize it once?

**Comment by wang-xinyu** [comment]
If you deserializing it every time.  of course it will cost much time.
You need understand the code and adapt it.
