### ISSUE TITLE
Polygon Detection

### ISSUE THREAD

**Issue by sctrueew** [wang-xinyu/tensorrtx#911]
Hi,

I'm using [PolygonDetection](https://github.com/XinzeLee/PolygonObjectDetection)  in Tensort c++.

I could generate polygon_yolov5s_ucas.wts but when I want to make an engine I get this error.

[E] [TRT] 3: [network.cpp::nvinfer1::Network::addScale::735] Error Code 3: Internal Error (Parameter check failed at: network.cpp::nvinfer1::Network::addScale::735, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)

The model has 2 classes and size is 1024: I have set 
CLASS_NUM: 2
INPUT_H: 1024
INPUT_W: 1024

Thanks

_Originally posted by @sctrueew in https://github.com/wang-xinyu/tensorrtx/issues/451#issuecomment-1040074303_

**Comment by wang-xinyu** [comment]
We don't support any variants, you need to change code accordingly.

**Comment by ONNONS** [comment]
hello
i removed the P5 layer from yolov5 nano version to make it lighter.
if this happens, will if not be supported by tensorrtx ?

< error code >
* yolov5/yolov5.cpp:63: nvinfer1::ICudaEngine* build_engine(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType, float&, float&, std::__cxx11::string&): Assertion `upsample11' failed.

*yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted
