### ISSUE TITLE
rcnn on windows

### ISSUE THREAD

**Issue by sctrueew** [wang-xinyu/tensorrtx#913]
Hi,

I have a problem with the building of rcnn (detectron2) on Windows. I get an error:
`
Error	LNK1181	cannot open input file 'Release\myplugins.lib'	rcnn	\tensorrtx\rcnn\b\LINK	1	
`
Myplugins.lib isn't in the path, but it built successfully

OpenCV: 4.5.4
TensorRT: TensorRT-7.2.3.4
CUDA: 11.2

**Comment by rgkannan676** [comment]
@sctrueew , Hi any update on this issue? I am also facing same issue.

LNK1181	cannot open input file 'Release\myplugins.lib'	rcnn
LNK1181	cannot open input file 'C:\Users\tensorrtx\rcnn\build\CMakeFiles\myplugins.dir\Release\myplugins_generated_BatchedNms.cu.obj'	myplugins

Thanks

**Comment by rgkannan676** [comment]
@freedenS . Hi can you please tell what are the steps to make and build RCNN in windows.  I am trying to make using Cmake and build using visual studio 2019.

**Comment by rgkannan676** [comment]
I made teh changes - https://github.com/wang-xinyu/tensorrtx/pull/521#issuecomment-865013195 for cuda 11.1.

**Comment by rgkannan676** [comment]
E0864	DeviceRadixSortPolicy is not a template	myplugins	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include\cub\device\dispatch\dispatch_radix_sort.cuh	824

**Comment by sctrueew** [comment]
@rgkannan676 Hi,

I couldn't build it. I got this error 
`invalid numeric argument '/Wfatal-errors'`

TensorRt: 7.2
Cuda: 10.2
Os: Win 10

**Comment by rgkannan676** [comment]
Hi @freedenS , Is it possible to build in windows? Can you please confirm? Thank you.

**Comment by freedenS** [comment]
to build rcnn in windows:
1. open a project with cuda
2. add rcnn .h .hpp .cpp .cu
3. set trt/opencv include and directory
4. add "--extended-lambda" in CUDA C/C++ -> Command Line -> Other options
5. replace linux function in dirent.h with corresponding win function

**Comment by freedenS** [comment]
> @rgkannan676 Hi,
> 
> I couldn't build it. I got this error `invalid numeric argument '/Wfatal-errors'`
> 
> TensorRt: 7.2 Cuda: 10.2 Os: Win 10

if you use cuda 10.2, you should assure it is updated. https://github.com/NVIDIA/TensorRT/issues/1151

**Comment by rgkannan676** [comment]
> to build rcnn in windows:
> 
> 1. open a project with cuda in vs
> 2. add rcnn .h .hpp .cpp .cu
> 3. set trt/opencv include and directory
> 4. add "--extended-lambda" in CUDA C/C++ -> Command Line -> Other options
> 5. replace linux function in dirent.h with corresponding win function

Hi @freedenS , Thank you for the reply. This resolved my issues and was able to build the .exe file.

**Comment by sctrueew** [comment]
@rgkannan676 Hi,

I created a empty project and all .hpp .cpp .cu

1. TensorRT-7.2.3.4.Windows10.x86_64.cuda-11.0.cudnn8.1
2. opencv_4_5_4_cuda_11_2
3. CUDA v11.2
4. VS 2019

I  added --extended-lambda to the Additional options but I get this errors
![image](https://user-images.githubusercontent.com/5433346/157826209-a247b414-b2f4-443d-ad21-35c94b7d2c9e.png)

Could you please some help?

**Comment by rgkannan676** [comment]
Try to add the libraries. 

Linker -> All Options -> Additional Dependencies.  Add the following libraries.
```
cudart_static.lib
nvinfer.lib
cudart.lib
nvinfer_plugin.lib
cudadevrt.lib
cublas.lib
cublasLt.lib
```

**Comment by rgkannan676** [comment]
Have you converted .cu files Item Type as "CUDA C/C++" ? You can see this option in the "Properties" of the files.

**Comment by rgkannan676** [comment]
Also have you added CUDA 11.2 as dependency?  Build Dependencies -> Build Customizations and select CUDA 11.2

**Comment by rgkannan676** [comment]
once you add CUDA 11.2 dependency, "--extended-lambda " need to be added to CUDA C/C++ -> Command Line -> Additional Options.

**Comment by sctrueew** [comment]
I set
![image](https://user-images.githubusercontent.com/5433346/157827632-cb6a801f-bed7-48bc-b7d0-697d81fdb0ab.png)

and have

opencv_world454.lib
nvinfer.lib
cudart.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib\x64\cudart.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
cudart_static.lib
nvinfer_plugin.lib
cudadevrt.lib
cublas.lib
cublasLt.lib

but it wan't solved

**Comment by sctrueew** [comment]
@rgkannan676 Have you any idea?

**Comment by rgkannan676** [comment]
Have you set 

- C/C++ -> All Options -> Additional Include Directories  with following ? (Change path according to your env). You can add the tensorRT include path also. I am not adding since I copied it to CUDA folder.
```

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include
C:\OpenCV\include

```

- Linker -> All Options -> Additional Library directories. Add following.  You can add your tensorRT lib path also.

```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64
```

- Build the project in Release configuration.

![image](https://user-images.githubusercontent.com/29349268/157832460-8dc89d6c-d0dd-4522-ae8b-5e8a17ee71ad.png)

**Comment by sctrueew** [comment]
Yes exactly, I set 
![image](https://user-images.githubusercontent.com/5433346/157833354-d96c32d2-8e46-449f-b17f-8942a9c5862f.png)

and

![image](https://user-images.githubusercontent.com/5433346/157833409-00e47971-a6f2-4e75-964b-ca7a44be0eb0.png)

![image](https://user-images.githubusercontent.com/5433346/157833621-13d58db2-f349-468d-a2fd-4e29733b5e1b.png)

also I have changed [https://github.com/wang-xinyu/tensorrtx/pull/521#issuecomment-865013195](https://github.com/wang-xinyu/tensorrtx/pull/521#issuecomment-865013195)

**Comment by rgkannan676** [comment]
above are the changes I made. One more thing, Have you checked 'CUDA_PATH' in Environment Variables? Is it pointing to 11.2? If not set it to 11.2 and restart.

**Comment by sctrueew** [comment]
> above are the changes I made. One more thing, Have you checked 'CUDA_PATH' in Environment Variables? Is it pointing to 11.2? If not, set it to 11.2 and restart.

 I've set everything up, but I don't know what the problem is?
Could you please share your project or send it to me?

**Comment by sctrueew** [comment]
@rgkannan676 
With the configs, I almost built all the projects in this repo except rcnn. Can you tell me what's wrong?

**Comment by sctrueew** [comment]
> could you show your compiling log?

@freedenS Hi,

![image](https://user-images.githubusercontent.com/5433346/157845705-f7cac4bb-4cc3-4cb4-ba95-3449c6c04095.png)

**Comment by freedenS** [comment]
not this, just like this
<img width="652" alt="1" src="https://user-images.githubusercontent.com/26213470/157846947-ee27cdcc-8721-4270-803f-5ac9cfd1145a.png">

**Comment by sctrueew** [comment]
> > could you show your compiling log?
> 
> @freedenS Hi,
> 
> ![image](https://user-images.githubusercontent.com/5433346/157845705-f7cac4bb-4cc3-4cb4-ba95-3449c6c04095.png) [log.txt](https://github.com/wang-xinyu/tensorrtx/files/8231039/log.txt)

I've added the log.

**Comment by rgkannan676** [comment]
Hi @sctrueew , Sorry, not able to share project due to privacy issue. One more check, have you set the Item Type property?

![image](https://user-images.githubusercontent.com/29349268/157851080-8625d16e-2222-4d32-95cf-ef50e4ee5f05.png)

**Comment by sctrueew** [comment]
> Hi @sctrueew , Sorry, not able to share project due to privacy issue. One more check, have you set the Item Type property?
> 
> ![image](https://user-images.githubusercontent.com/29349268/157851080-8625d16e-2222-4d32-95cf-ef50e4ee5f05.png)

No problem, yes I checked again and the Item type was set for all *.cu files
![image](https://user-images.githubusercontent.com/5433346/157852289-7a90bb30-3fbc-4d9b-8b89-cd76c7431da5.png)

**Comment by freedenS** [comment]
1>D:\Projects\yolov5\tensorrtx\rcnn\MaskRcnnInferencePlugin.h(37): error : expected a ";"
it seems like you are not same with master

**Comment by sctrueew** [comment]
> 1>D:\Projects\yolov5\tensorrtx\rcnn\MaskRcnnInferencePlugin.h(37): error : expected a ";" it seems like you are not same with master

I've cloned again and built it.
[log1.txt](https://github.com/wang-xinyu/tensorrtx/files/8231278/log1.txt)

**Comment by rgkannan676** [comment]
FYI, I created a new solution -> new project-> copied all .cpp, .h, .cu files in the git  repo to new project folder and added it to project. Replaced the contents in the main function with rcnn.cpp, along with the changes mentioned above.

**Comment by sctrueew** [comment]
> FYI, I created a new solution -> new project-> copied all .cpp, .h, .cu files in the git repo to new project folder and added it to project. Replaced the contents in the main function with rcnn.cpp, along with the changes mentioned above.

Once again, I followed the steps step by step.

![image](https://user-images.githubusercontent.com/5433346/157857937-a01f8aa6-3fe8-457f-a991-fa6c82a657a1.png)

**Comment by freedenS** [comment]
you'd better use trt7, such as 7.2.1 described in README, it looks like trt8 has changed that api. i'm not sure.

**Comment by sctrueew** [comment]
@freedenS @rgkannan676 Thank you for the tips, finally, I've built it with Tr 7.2.3

**Comment by sctrueew** [comment]
@freedenS Hi,

I've trained a model with `mask_rcnn_R_50_FPN_3x` and convert the .pth to .wts. I have 1 class and I changed NUM_CLASSES = 1 in gen_wts.py. I could generate the faster.wts successfully, I change in rcnn side lines:

1. NUM_CLASSES = 1
2. BACKBONE_RESNETTYPE R50
3. STRIDE_IN_1X1 true

but I'm facing this error when I run rcnn -s faster.wts faster.engine m:

> `Loading weights: faster.wts
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> Building engine, please wait for a while...
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: kernel weights has count 0 but 9408 was expected
> [03/11/2022-18:22:33] [E] [TRT] (Unnamed Layer* 6) [Convolution]: count of 0 weights in kernel, but kernel dimensions (7,7) with 3 input channels, 64 output channels and 1 groups were specified. Expected Weights count is 3 * 7*7 * 64 / 1 = 9408
> [03/11/2022-18:22:33] [E] [TRT] Could not compute dimensions for (Unnamed Layer* 6) [Convolution]_output, because the network is not valid.
> [03/11/2022-18:22:33] [E] [TRT] Network validation failed.
> Build engine successfully!`

**Comment by freedenS** [comment]
whis's the size of faster.wts?
it shows the weight value has not loaded correctly

**Comment by sctrueew** [comment]
> what's the size of faster.wts? it shows the weight value has not loaded correctly

faster.wts size is ~390 mb

I'm using mask_rcnn_R_50_FPN_3x. Does it support FPN? or I should use C4?

**Comment by freedenS** [comment]
> > what's the size of faster.wts? it shows the weight value has not loaded correctly
> 
> faster.wts size is ~390 mb
> 
> I'm using mask_rcnn_R_50_FPN_3x. Does it support FPN? or I should use C4?

it doesn't support FPN, you can only use C4

**Comment by rgkannan676** [comment]
Hi @freedenS , One more doubt, can you please tell how to change the image height and width . I have an image of shape 600x875. And I change the IMAGE_HEIGHT, IMAGE_WIDTH  accordingly. But still the output is of dimension INPUT_H = 480x INPUT_W = 640;  

Can you please suggest what need to be changed? I tried changing INPUT_H  and INPUT_W but it doesn't give any output. Can you please advise. Thank you.
