### ISSUE TITLE
yolov5 nano

### ISSUE THREAD

**Issue by ONNONS** [wang-xinyu/tensorrtx#917]
## Env

- GPU, Nano,
- OS, e.g. Ubuntu18.04,
- Cuda version 10.2
- TensorRT version 8.0

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

Is yolov5 nano not supported?

i succeeded in generating wts, but not succeeding in engine file
maybe it's a tensorrt version issue?

**Comment by henningscale** [comment]
I have the same issue

**Comment by wang-xinyu** [comment]
more detail please.
