### ISSUE TITLE
canot convert yolov5s.wts to yolov5s.engine ?

### ISSUE THREAD

**Issue by Yaoxingtian** [wang-xinyu/tensorrtx#923]
## Env

- GPU,: gtx1650
- OS, e.g. Ubuntu 20.04
- Cuda 11.0
- TensorRT 8.0

## About this repo
- which model? 
 yolov5 - 5.0

## Your problem

- what is your command? 
sudo ./yolov5 -s yolov5s.wts yolov5s.engine s

- what's your output?
Loading weights: yolov5s.wts
CUDA error 222 at /home/yao/Documents/tensorrtx-master/yolov5/yololayer.cu:37yolov5: /home/yao/Documents/tensorrtx-master/yolov5/yololayer.cu:37: nvinfer1::YoloLayerPlugin::YoloLayerPlugin(int, int, int, int, const std::vector<Yolo::YoloKernel>&): Assertion `0' failed.

- what output do you expect?
 normal

**Comment by wang-xinyu** [comment]
cuda error,  means your environments are not right

**Comment by Yaoxingtian** [comment]
> cuda error, means your environments are not right

could you advice the  right cuda version ? thanks!

**Comment by thunder95** [comment]
same issue, and no problem with my cuda enviroment.
