### ISSUE TITLE
How to convert tph-yolov5 weights to tensorrtx?

### ISSUE THREAD

**Issue by RoyCopter** [wang-xinyu/tensorrtx#924]
Hey,
I want to convert the weights of the[ tph-yolov5](https://github.com/cv516Buaa/tph-yolov5) to engine and then use the model with it. 

how can I do that?

**Comment by wang-xinyu** [comment]
That will require code changes,   you can dive into our code first

**Comment by RoyCopter** [comment]
> That will require code changes, you can dive into our code first
@wang-xinyu 
Thanks for the replay! 

can you be a more specific? what exactly do I have to change? I will dive into the yolov5 code. what else do I have to check?

**Comment by wang-xinyu** [comment]
you need yo re-define the network structure for tph-yolov5 in our code

**Comment by xjock** [comment]
already fixed?

**Comment by anacolg** [comment]
I meet the same problem and I can`t solve it ,are you already fixed?
