### ISSUE TITLE
Slow performance in Jetson Xavier NX (Yolov5)

### ISSUE THREAD

**Issue by RoyCopter** [wang-xinyu/tensorrtx#925]
Hey, I am getting very slow fps using your guide for the yolov5.

around 74ms per image using yolov5m.engine and around 34ms using the yolov5s.engine. 
If I resize the image before to to (640,640) I get a little big better performance (54ms for yolov5m and 23 for yolov5s), but I was sure it will be faster..

how can I fix that? thanks!

**Comment by kleinar** [comment]
@RoyCopter I have the same problem, the inference time is 48ms. Were you able to find out what's wrong?
