### ISSUE TITLE
Can you add tutorials (In English) to create tensorrtx for new models?

### ISSUE THREAD

**Issue by RoyCopter** [wang-xinyu/tensorrtx#926]
Hey can you post more tutorials to build the tensorrtx for our models?

I think tutorial that will explain what you did for the yolov5 will be great! 

anyway thanks for your great repository!

**Comment by wang-xinyu** [comment]
https://github.com/wang-xinyu/tensorrtx/blob/master/tutorials/getting_started.md

You can check this
