### ISSUE TITLE
Different result between pytorch and TensorRT

### ISSUE THREAD

**Issue by sunzhuojun** [wang-xinyu/tensorrtx#928]
## Env

- GPU  RTX 1080ti
- OS, Ubuntu18.04
- Cuda 10.2
- TensorRT 8.0.3.1

## About this repo

- branch master
- model efficientnet 

## Your problem

 I used default as followed 
```
python gen_wts.py
./efficientnet -s ../efficientnet-b3.wts ./efficientnet-b3.engine b3
./efficientnet -d efficientnet-b3.engine b3
```
and get 20 outputs:
```
 -0.703588, -0.0731193, -0.302973, -0.0822509, 0.00295858, -0.0773187, -0.689594, -0.636345, -0.714602, 0.0539521, 0.65422, 0.198752, 0.164274, -0.00710363, 0.156993, -0.380668, 0.672134, -0.326662, 0.279835, -0.0746763, 
```
I also the the repo https://github.com/lukemelas/EfficientNet-PyTorch
```
import json
from PIL import Image
import torch
from torchvision import transforms

from efficientnet_pytorch import EfficientNet
model = EfficientNet.from_pretrained('efficientnet-b3')

# Preprocess image
# tfms = transforms.Compose([transforms.Resize(224), transforms.ToTensor(),
#     transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),])
# img = tfms(Image.open('img.jpg')).unsqueeze(0)
img = torch.ones([1, 3, 224, 224])
img = img * 0.1
print(img.shape) # torch.Size([1, 3, 224, 224])

# Load ImageNet class names
labels_map = json.load(open('labels_map.txt'))
labels_map = [labels_map[str(i)] for i in range(1000)]

# Classify
model.eval()
with torch.no_grad():
    outputs = model(img)

print(outputs.shape)
print(outputs[:,:20])
```
and get 20 outputs
```
-0.5933, -0.0525, -0.5565, -0.2481, -0.3245,  0.0063, -1.0454, -0.7213, -0.7873, -0.0169,  0.7548,  0.1409, -0.0077, -0.1597,  0.2287, -0.4962, 0.5767, -0.4054,  0.1774, -0.2127
```

why the outputs are diff?

**Comment by wang-xinyu** [comment]
@upczww can you please suggest on this?

**Comment by yunxicdq** [comment]
这个问题我也遇到了，目前测试发现同一批图片，pytorch和tensorrt的输出不一样，

**Comment by wangkang1022** [comment]
我也遇到了同样问题

**Comment by wangkang1022** [comment]
我也遇到了同样问题。

**Comment by wangkang1022** [comment]
我也遇到了同样问题。我在yolov5 3.0上训练了自己的数据集，根据https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/成功在Jetson上生成引擎。但在测试时发现，转tensoorrt后运行的结果和未转之前相差较大。未转之前的置信度是0.43，使用引擎推理的结果只有0.15.                                                                                                                                                                                           请问是我哪里参数设置不对嘛，还是什么原因。

**Comment by peymanrostami** [comment]
> 我也遇到了同样问题。我在yolov5 3.0上训练了自己的数据集，根据[https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/成功在Jetson上生成引擎。但在测试时发现，转tensoorrt后运行的结果和未转之前相差较大。未转之前的置信度是0.43，使用引擎推理的结果只有0.15](https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/%E6%88%90%E5%8A%9F%E5%9C%A8Jetson%E4%B8%8A%E7%94%9F%E6%88%90%E5%BC%95%E6%93%8E%E3%80%82%E4%BD%86%E5%9C%A8%E6%B5%8B%E8%AF%95%E6%97%B6%E5%8F%91%E7%8E%B0%EF%BC%8C%E8%BD%ACtensoorrt%E5%90%8E%E8%BF%90%E8%A1%8C%E7%9A%84%E7%BB%93%E6%9E%9C%E5%92%8C%E6%9C%AA%E8%BD%AC%E4%B9%8B%E5%89%8D%E7%9B%B8%E5%B7%AE%E8%BE%83%E5%A4%A7%E3%80%82%E6%9C%AA%E8%BD%AC%E4%B9%8B%E5%89%8D%E7%9A%84%E7%BD%AE%E4%BF%A1%E5%BA%A6%E6%98%AF0.43%EF%BC%8C%E4%BD%BF%E7%94%A8%E5%BC%95%E6%93%8E%E6%8E%A8%E7%90%86%E7%9A%84%E7%BB%93%E6%9E%9C%E5%8F%AA%E6%9C%890.15). 请问是我哪里参数设置不对嘛，还是什么原因。

have you solved it yet? I also have the same problem. would appreciate if you could help

**Comment by wangkang1022** [comment]
> > 我也遇到了同样问题。我在yolov5 3.0上训练了自己的数据集，根据[https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/成功在Jetson上生成引擎。但在测试时发现，转tensoorrt后运行的结果和未转之前相差较大。未转之前的置信度是0.43，使用引擎推理的结果只有0.15](https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/%E6%88%90%E5%8A%9F%E5%9C%A8Jetson%E4%B8%8A%E7%94%9F%E6%88%90%E5%BC%95%E6%93%8E%E3%80%82%E4%BD%86%E5%9C%A8%E6%B5%8B%E8%AF%95%E6%97%B6%E5%8F%91%E7%8E%B0%EF%BC%8C%E8%BD%ACtensoorrt%E5%90%8E%E8%BF%90%E8%A1%8C%E7%9A%84%E7%BB%93%E6%9E%9C%E5%92%8C%E6%9C%AA%E8%BD%AC%E4%B9%8B%E5%89%8D%E7%9B%B8%E5%B7%AE%E8%BE%83%E5%A4%A7%E3%80%82%E6%9C%AA%E8%BD%AC%E4%B9%8B%E5%89%8D%E7%9A%84%E7%BD%AE%E4%BF%A1%E5%BA%A6%E6%98%AF0.43%EF%BC%8C%E4%BD%BF%E7%94%A8%E5%BC%95%E6%93%8E%E6%8E%A8%E7%90%86%E7%9A%84%E7%BB%93%E6%9E%9C%E5%8F%AA%E6%9C%890.15). 请问是我哪里参数设置不对嘛，还是什么原因。
> 
> have you solved it yet? I also have the same problem. would appreciate if you could help me?

我目前还未解决，调节了CHECK_COUNT，IGNORE_THRESH等参数，结果几乎没有改变。
