### ISSUE TITLE
About using tensorrt create LPRNet network

### ISSUE THREAD

**Issue by yunxicdq** [wang-xinyu/tensorrtx#930]
float *deval = reinterpret_cast<float *>(malloc(sizeof(float) * 64 * 4 * 18));
    for (int i = 0; i < 64 * 4 * 18; i++) {
        deval[i] = 2.0;
    }
    Weights deconvwts11{DataType::kFLOAT, deval, 64 * 4 * 18};
    IConstantLayer *d = network->addConstant(Dims4{1, 64, 4, 18}, deconvwts11);
    IElementWiseLayer *f_pow = network->addElementWise(*f0->getOutput(0), *d->getOutput(0), ElementWiseOperation::kPOW);
    Dims pf0 = f0->getOutput(0)->getDimensions();
    Dims pD = d->getOutput(0)->getDimensions();
    Dims pf_pow = f_pow->getOutput(0)->getDimensions();

    auto f_mean = network->addReduce(*f_pow->getOutput(0), ReduceOperation::kAVG, 0XF, true);
    Dims pf_mean = f_mean->getOutput(0)->getDimensions();
    IElementWiseLayer *f_div = network->addElementWise(*f0->getOutput(0), *f_mean->getOutput(0),
                                                       ElementWiseOperation::kDIV);

    Dims pf_div = f_div->getOutput(0)->getDimensions();
    float *deval2 = reinterpret_cast<float *>(malloc(sizeof(float) * 1 * 128 * 4 * 18));
    for (int i = 0; i < 128 * 4 * 18 * 1; i++) {
        deval2[i] = 2.0;
    }
    Weights deconvwts22{DataType::kFLOAT, deval2, 128 * 4 * 18 * 1};
    IConstantLayer *d2 = network->addConstant(Dims4{1, 128, 4, 18}, deconvwts22);
    IElementWiseLayer *f_pow2 = network->addElementWise(*f1->getOutput(0), *d2->getOutput(0),
                                                        ElementWiseOperation::kPOW);
    auto f_mean2 = network->addReduce(*f_pow2->getOutput(0), ReduceOperation::kAVG, 0XF, true);
    IElementWiseLayer *f_div2 = network->addElementWise(*f1->getOutput(0), *f_mean2->getOutput(0),
                                                        ElementWiseOperation::kDIV);

    float *deval3 = reinterpret_cast<float *>(malloc(sizeof(float) * 256 * 4 * 18 * 1));
    for (int i = 0; i < 256 * 4 * 18 * 1; i++) {
        deval3[i] = 2.0;
    }
    Weights deconvwts33{DataType::kFLOAT, deval3, 256 * 4 * 18 * 1};
    IConstantLayer *d3 = network->addConstant(Dims4{1, 256, 4, 18}, deconvwts33);
    IElementWiseLayer *f_pow3 = network->addElementWise(*f2->getOutput(0), *d3->getOutput(0),
                                                        ElementWiseOperation::kPOW);
    auto f_mean3 = network->addReduce(*f_pow3->getOutput(0), ReduceOperation::kAVG, 0XF, true);
    IElementWiseLayer *f_div3 = network->addElementWise(*f2->getOutput(0), *f_mean3->getOutput(0),
                                                        ElementWiseOperation::kDIV);

    float *deval4 = reinterpret_cast<float *>(malloc(sizeof(float) * 68 * 4 * 18 * 1));
    for (int i = 0; i < 68 * 4 * 18 * 1; i++) {
        deval4[i] = 2.0;
    }
    Weights deconvwts44{DataType::kFLOAT, deval4, 68 * 4 * 18 * 1};
    IConstantLayer *d4 = network->addConstant(Dims4{1, 68, 4, 18}, deconvwts44);
    IElementWiseLayer *f_pow4 = network->addElementWise(*backbone->getOutput(0), *d4->getOutput(0),
                                                        ElementWiseOperation::kPOW);
    auto f_mean4 = network->addReduce(*f_pow4->getOutput(0), ReduceOperation::kAVG, 0XF, true);
    IElementWiseLayer *f_div4 = network->addElementWise(*backbone->getOutput(0), *f_mean4->getOutput(0),
                                                        ElementWiseOperation::kDIV);

    ITensor *inputTensors[] = {f_div->getOutput(0), f_div2->getOutput(0), f_div3->getOutput(0), f_div4->getOutput(0)};

    auto f_divdims = f_div->getOutput(0)->getDimensions();
    auto f_div2dims = f_div2->getOutput(0)->getDimensions();
    auto f_div3dims = f_div3->getOutput(0)->getDimensions();
    auto backbonedims = backbone->getOutput(0)->getDimensions();
    auto cat = network->addConcatenation(inputTensors, 4);
    Dims pcat = cat->getOutput(0)->getDimensions();

这段代码里面的“64 * 4 * 18”实在是没看明白怎么来的，而且看Python版的lprnet模型创建也没找到答案，大佬方便给讲解下以上贴的这段代码的由来和含义吗？感激不尽！！

**Comment by wang-xinyu** [comment]
@chgit0214 @magicwifi can you please suggest?
