### ISSUE TITLE
Hi，请问后续会不会更新maskrcnn的部署呢？

### ISSUE THREAD

**Issue by Mrwangxin1998** [wang-xinyu/tensorrtx#937]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by wang-xinyu** [comment]
We already have maskrcnn:
https://github.com/wang-xinyu/tensorrtx/tree/master/rcnn
