### ISSUE TITLE
HI,问下昨天更新得Swin-T 我下载了链接里面得SwinT得预训练模型，进行.wts生成得时候出现错误 

### ISSUE THREAD

**Issue by QIANXUNZDL123** [wang-xinyu/tensorrtx#938]
![image](https://user-images.githubusercontent.com/46549527/158524275-e60fbac1-cfa7-4452-a159-57332f439517.png)

预训练模型:swin_tiny_c24_patch4_window8_256.pth

报错，，这个是不是不能用预训练模型进行转换，还是要自己训练得模型？？

**Comment by wang-xinyu** [comment]
seems your .pth only contains weights, no network structure,

can you try to use torch.save() and then use this torch.load()?

**Comment by wang-xinyu** [comment]
cc: @wdhao

**Comment by QIANXUNZDL123** [comment]
> 是的，我并没有自己去训练模型，使用得是下面的两个Swin-T预训练模型，均是报同样的错误，所以想看下是否是要自己训练出来的模型，再进行wts的生成。
![image](https://user-images.githubusercontent.com/46549527/158538323-1778990c-2d1b-41fb-8642-6ed734b86ab9.png)
![image](https://user-images.githubusercontent.com/46549527/158538450-a27c5df0-39da-457c-a1ad-44d85ca0f202.png)
