### ISSUE TITLE
Mask RCNN : What factor decides the INPUT_H and INPUT_W values ?

### ISSUE THREAD

**Issue by rgkannan676** [wang-xinyu/tensorrtx#941]
Hi @freedenS , Thank you for your work.  

I have a doubt. Can you please explain how the factors like INPUT_H , INPUT_W , MIN_SIZE, MAX_SIZE, IMAGE_HEIGHT and IMAGE_WIDTH values are decided. I tried to change some values like the IMAGE_HEIGHT and IMAGE_WIDTH and didn't found any differences. When I use any values other than 480 and 640 for INPUT_H and INPUT_W respectively, I don't get any detections.

I went through he config files in detectron2 but was not able to find this values.  

I was only able to find  below values in Base-RCNN-C4.yaml.
```
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
```
and nothing much in mask_rcnn_R_1010_C4_3x.yaml. 

Can you please explain how you got the values. Thanks.

**Comment by rgkannan676** [comment]
Hi @freedenS , I have images of size 606x875 (WxH).
There are 2 set of variables INPUT_W x INPUT_H  and IMAGE_WIDTH x IMAGE_HEIGHT.  Can you please suggest which variable set should I change according to my image width and height. 

Please advise. Thank you.

**Comment by freedenS** [comment]
the preprocess is similar to detectron2
INPUT_H and INPUT_W are real size of image
IMAGE_HEIGHT and IMAGE_WIDTH are the size after preprocess, they are used for crop when decoding
MIN_SIZE, MAX_SIZE refer to https://github.com/facebookresearch/detectron2/blob/main/detectron2/config/defaults.py#L63

**Comment by rgkannan676** [comment]
Hi @freedenS, Thank you for your response. 

So I will assign 
```
INPUT_W = 606; 
INPUT_H = 875;
```
I will keep the below values as mentioned in https://github.com/facebookresearch/detectron2/blob/main/detectron2/config/defaults.py#L63
```
float MIN_SIZE = 800.0;
float MAX_SIZE = 1333.0;
```
But how to find  "IMAGE_HEIGHT and IMAGE_WIDTH are the size after preprocess".  You kept the values 
```
int IMAGE_HEIGHT = 800;
int IMAGE_WIDTH = 1333;
```
for the demo.jpg. So shall I keep the same value?  I am not sure where to find these values in Detectron2 , can you please advise. Thank you.

**Comment by rgkannan676** [comment]
In my case image width > height. Will this cause any issues?

**Comment by freedenS** [comment]
IMAGE_HEIGHT and IMAGE_WIDTH will be reassign in preprocess, they are not const type

**Comment by rgkannan676** [comment]
@freedenS oh ok understood. Thank you.
