### ISSUE TITLE
yolov5-v6.1转tensorrt

### ISSUE THREAD

**Issue by yangl720** [wang-xinyu/tensorrtx#942]
[E] [TRT] Parameter check failed at: ../builder/Network.cpp::addConvolutionNd::488, condition: kernelWeights.values != nullptr
yolov5: /home/yolov5_v6.1/tensorrtx/yolov5/common.hpp:163: nvinfer1::ILayer* convBlock(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, int, int, int, int, std::__cxx11::string): Assertion `conv1' failed.
Aborted (core dumped)

**Comment by z13228604287** [comment]
yolov5-v6.1 Please when will the author update!
