### ISSUE TITLE
引擎生成失败

### ISSUE THREAD

**Issue by wangkang1022** [wang-xinyu/tensorrtx#948]
## Env

- GPU,  TX2
- OS,  Ubuntu16.04
- Cuda version 10.2
- TensorRT version 7.1

## About this repo
https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v5.0

- which model? yolov5, retinaface?
yolov5-v5.0
## Your problem

- 我用yolov5-v5.0训练自己数据集，但我使用了预训练，预训练模型是在yolov5-3.0上训练得来的。
- 我按照https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v5.0来生成引擎，在进行到“sudo ./yolov5 -s yolov5s.wts yolov5s.engine s”时，生成引擎失败。
- 请问是什么原因，还有就是当我使用yolov5-3.0来训练自己数据集（同样使用预训练）得到.pt文件，并用作者对应3.0版本进行操作，可以生成引擎，但精度不是很理想。

**Comment by yunxicdq** [comment]
楼主生成engine失败是报的什么问题呢？我今天用jetson tx2 环境运行，也是生成engine这步出错，我的错误是：
![image](https://user-images.githubusercontent.com/101306803/160776041-793137c5-0f15-446d-b9a8-11b13f0fd9b0.png)
我的jetson tx2环境具体是：
Ubuntu18.04
jetpack4.5.1（tensorrt7.1.3_cuda10.2）

**Comment by wang-xinyu** [comment]
pls try the official model first and check the accuracy

**Comment by wangkang1022** [comment]
> 

你好，你用的什么模型，yolov5吗。你要记得版本对应，例如yolov5的v1.0 v2.0 v3.0 v6.0等
