### ISSUE TITLE
yolov5 negative X,Y cordinates from detections

### ISSUE THREAD

**Issue by sudapure** [wang-xinyu/tensorrtx#95]
I am using Yolov5 implementation to predict bounding boxes, but the detection returns some values as negative integers , but the `cv::rectangle` function draws correct rectangles on to images, so it's kind of puzzling why there are negative or even long values in the detection coordinates, here `get_rect` function returns x,y,width,height, here i modified `get_rect` function to return int instead  `cv::Rect`

    std::vector<uint> rr = get_rect(img, res[j].bbox); 

later converted it into opencv understandable format:

    cv::Rect r = cv::Rect(rr[0],rr[1],rr[2],rr[3]);

when print following values of `Rect r` some values are ambiguous,

    r.x = 398
    r.y = 1431655936
    r.width = 22
    r.height = -1431655867

As can be seen values of y coordinate and height are completely out of the canvas, so any reasons for this.

Also , i made sure that the input image dimensions , infering dimensions , and output image rendering dimensions all are same, Also `cv::rectangle` function correctly drawing all the rectangles with there respective object locations.

**Comment by wang-xinyu** [comment]
Did you notice that the input resizing method is `letterbox`? refer to `preprocess_img()` in `common.hpp`.   Would that influence your get_rect() implementation?

**Comment by sudapure** [comment]
@wang-xinyu , yes am aware of that, but that method internally resizing the image to be fit for inferencing, however that really doesn't matter because final bounding boxes returned after post -processing drawned correctly on the image, but when i dumped it to json file, there are several bounding boxes with ambiguous int values, while same values rendered by `cv:rect` function doesn't produced any side effects.

**Comment by wang-xinyu** [comment]
No idea. Hope you can debug and solve it.
