### ISSUE TITLE
About tensorrt-yolov5 in jetson tx2 env

### ISSUE THREAD

**Issue by yunxicdq** [wang-xinyu/tensorrtx#950]
The tensorrt-yolov5 run normal in Ubuntu x86_64 framework， it run exception in jetson tx2 ，which is Ubuntu aarch64  framework。
The question is as follows：
![image](https://user-images.githubusercontent.com/101306803/160774877-3fa8ac0c-86aa-4cc9-a483-85786a04ffc5.png)
Can you give me some suggests，thanks very much！ @[wang-xinyu](https://github.com/wang-xinyu)
My jetson tx2 env is as follows:
Ubuntu18.04
jetpack4.5.1（tensorrt7.1.3_cuda10.2）
using yolov5 5.0

**Comment by wang-xinyu** [comment]
The model version doesn't match with the code.
You can try to use the exact same code and .wts as your x86

**Comment by ckugel** [comment]
> The model version doesn't match with the code. You can try to use the exact same code and .wts as your x86

I have the same issue what do you mean by .wts as your x86?

**Comment by wang-xinyu** [comment]
The .wts generated in x86 can also be used in jetson,   .wts is just text file.
