### ISSUE TITLE
windows环境retinaface编译错误

### ISSUE THREAD

**Issue by Monday-Leo** [wang-xinyu/tensorrtx#954]
- GPU,GTX1650
- OS, Win10
- Cuda version 10.2
- TensorRT version 8.2.1

retinaface

编译报错缺少decodeplugin.lib，cuda10.2和tensorrt lib文件夹中都没有decodeplugin.lib，如果删去就会报错，请问该怎么解决？

**Comment by wsxst** [comment]
是作者自己写的项目编译得到的静态库 @Monday-Leo

**Comment by Monday-Leo** [comment]
单独编译decode.cu也可以通过，但是没有生成decodeplugin.lib，请问这个静态库该怎么生成呢？

**Comment by Monday-Leo** [comment]
![EGVX`UJ_RAZ6QDLUO6 KA88](https://user-images.githubusercontent.com/53975909/165688873-89cd3393-2036-4e09-8bde-09fee8d09e2c.png)
感谢，已经生成decodeplugin.lib，又有新的报错，这是什么原因？

**Comment by Monday-Leo** [comment]
感谢！已经解决！
