### ISSUE TITLE
rcnn jetson nano  cmaker error

### ISSUE THREAD

**Issue by aodeluo** [wang-xinyu/tensorrtx#955]
## Env

- Nano
- JetPack 4.6.1
- Cuda version 10.2
- TensorRT version 8.2.1
## Your problem

 when make rcnn in jetson nano,the error come
![image](https://user-images.githubusercontent.com/40424000/161309402-d32db7c5-1e99-46f0-89e8-f810b0a5ee2b.png)

**Comment by bismarckkk** [comment]
Hello, I also got error when I build rcnn model on TensorRT8. 
But this is no error detail in your image. I can't know is it a same problem. 
Maybe you can try use Tensorrt7 or do same thing like #698 and #540.

**Comment by Mrwangxin1998** [comment]
> Hello, I also got error when I build rcnn model on TensorRT8. But this is no error detail in your image. I can't know is it a same problem. Maybe you can try use Tensorrt7 or do same thing like #698 and #540.

hi，can you inference rcnn on jetson nano？I have a problem that I can build engine but get  a error in inference........
![image](https://user-images.githubusercontent.com/48117937/162573726-e027620a-ab11-4077-a908-767984523871.png)

**Comment by bismarckkk** [comment]
> > Hello, I also got error when I build rcnn model on TensorRT8. But this is no error detail in your image. I can't know is it a same problem. Maybe you can try use Tensorrt7 or do same thing like #698 and #540.
> 
> hi，can you inference rcnn on jetson nano？I have a problem that I can build engine but get  a error in inference........
> ![image](https://user-images.githubusercontent.com/48117937/162573726-e027620a-ab11-4077-a908-767984523871.png)
> 

you should search variable 'max_thread' in rcnn folder. There are about 3 same name variable in these files. It default be 1024. Editing it 512 can fix cuda error 701.
(https://forums.developer.nvidia.com/t/error-too-many-resources-requested-for-launch/13350)
BTW, you may also meet "killed" when build engine. In my test, Only R34 and R18 model can run on jetson nano. if you want to use R50, you should close gui and use command line for more memory.
If you got CUDA error: the launch timed out and was terminated, you should try as below.(https://forums.developer.nvidia.com/t/jetson-nano-runtimeerror-cuda-error-the-launch-timed-out-and-was-terminated/198530)
```bash
$ sudo -s 
$ echo N > /sys/kernel/debug/gpu.0/timeouts_enabled
```
