### ISSUE TITLE
yolov5: /home/air/yolo5_trt/tensorrtx/yolov5/yolov5.cpp:63: nvinfer1::ICudaEngine* build_engine(unsigned int, nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*, nvinfer1::DataType, float&, float&, std::__cxx11::string&): Assertion `upsample11' failed. Aborted

### ISSUE THREAD

**Issue by wxthu** [wang-xinyu/tensorrtx#958]
when  i run 
sudo **./yolov5 -s yolov5x.wts  yolov5x.engine s**

![image](https://user-images.githubusercontent.com/73052387/161430105-078a5dd9-a3c5-413e-bab8-fd24be5bfad5.png)
I was very confused

**Comment by wang-xinyu** [comment]
for model x,
./yolov5 -s yolov5x.wts yolov5x.engine x

**Comment by wxthu** [comment]
> for model x, ./yolov5 -s yolov5x.wts yolov5x.engine x

Thanks， it seems that converting wts file to tensorrt engine takes long long time for **yolov5x** model  and my computer even was stuck .... Is that correct or normal?

**Comment by wxthu** [comment]
![image](https://user-images.githubusercontent.com/73052387/161903526-1fa92e50-8921-4547-9f41-cbf786024834.png)
stuck for long long time。。。。

**Comment by 1025888636** [comment]
hey,the same problem i met,did you solved it?

**Comment by 1025888636** [comment]
> 

i solved it，its because my model trained by yolov5x.pt，but sudo ./yolov5 -s yolov5x.wts yolov5x.engine s，it should sudo ./yolov5 -s yolov5x.wts yolov5x.engine x
