### ISSUE TITLE
Low landmark accuracy for retinaface (mnet) after conversion to tensorrt

### ISSUE THREAD

**Issue by peymanrostami** [wang-xinyu/tensorrtx#959]
## Env

- GPU, 1080ti
- OS, Ubuntu18.04
- Cuda version=11.4
- TensorRT version=8.2

- which model?  retinaface

I am trying to run retinaface (mobilenet) using your repository at https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface  following exactly what was described in it (downloaded the weight from https://drive.google.com/drive/folders/1oZRSG0ZegbVkVwUd8wUIQx8W7yfZ_ki1  as advised). I can successfully build and run the tensorrt engine of retinaface (mobilenet) not changing anything in the configurations pre-set in the code after cloning the repo. 

 However, when comparing the results obtained via the tensorrt with the original pytorch implementation in https://github.com/wang-xinyu/Pytorch_Retinaface (by running detect.py), I notice that the outputs of the tensorrt engine (particularly, the location of the landmarks) have lower accuracy compared to the original pytorch weights; Here is an example:

 output of pytorch weight of retinaface (mobilenet) from https://github.com/biubug6/Pytorch_Retinaface: ![test](https://user-images.githubusercontent.com/30995371/161479953-335bd7a2-33b4-44c3-9a7e-672fe9abbec5.jpg) 

output of tensorrt engine of retinaface (mobilenet) following the instructions on https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface ![0_result](https://user-images.githubusercontent.com/30995371/161480352-4ed7af81-a1b6-4780-93c7-d293040c7ab3.jpg)

 when comparing the two, I notice the accuracy of key-points have decreased. Could you kindly provide some help on that?

**Comment by wang-xinyu** [comment]
did you compare with same input shape?

**Comment by peymanrostami** [comment]
> 
Dear wang xinyu
Thanks alot for your fast reply.

Yes. 
The input shape in your code (found in line 16 and 17 in  decode.h) is INPUT_H = 480, INPUT_W = 640. 
The input shape in pytorch code is preset in [here](https://github.com/wang-xinyu/Pytorch_Retinaface/blob/beda45c3665f48a20dc2fba5a8e91032100c50c4/genwts.py#L16) as height=384, width=640. But, before making the wts file, I edit it to become height=480, width=640 ( to become same as in your code). there is also an Image_size parameter in   [here](https://github.com/wang-xinyu/Pytorch_Retinaface/blob/beda45c3665f48a20dc2fba5a8e91032100c50c4/data/config.py#L16) which is already set to 640

here are the two outputs in this scenario:

1- the output of pytorch with height=480, width=640:

![test](https://user-images.githubusercontent.com/30995371/161903329-e1bc5383-7963-4964-93ce-8299c3994a20.jpg)


2- the output of retinaface mobilenet with INPUT_H = 480, INPUT_W = 640:

![0_result](https://user-images.githubusercontent.com/30995371/161903487-6bb96689-55f8-4026-86ce-78235098db4e.jpg)


but again, the issue persists.

**Comment by peymanrostami** [comment]
Any Ideas on how this can be solved?

**Comment by wsxst** [comment]
maybe replace interpolate with deconv? I just guess. I also encounter this problem, have you fixed it? @peymanrostami thx!

**Comment by peymanrostami** [comment]
> maybe replace interpolate with deconv? I just guess. I also encounter this problem, have you fixed it? @peymanrostami thx!

I haven't solved it yet (have you?), but I will try your suggestion.
thank you

**Comment by peymanrostami** [comment]
> maybe replace interpolate with deconv? I just guess. I also encounter this problem, have you fixed it? @peymanrostami thx!

and one more thing, 
I could not find any interpolate layer being used in the code.

**Comment by peymanrostami** [comment]
> maybe replace interpolate with deconv? I just guess. I also encounter this problem, have you fixed it? @peymanrostami thx!

Hi there.
any suggestions yet?

**Comment by wang-xinyu** [comment]
You guys can check the output tensor's value, compare it with the tensor of pytorch.
