### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by yishunzhijian** [wang-xinyu/tensorrtx#96]
你好，请问TensorRT 5.0可以运行yolov4的程序嘛？或者是需要更改程序的哪写部分才可以运行

**Comment by wang-xinyu** [comment]
6 有人试过可以，5可能不行，编译一下试试，看看报什么错，有些api可能不支持

**Comment by yishunzhijian** [comment]
> 6 有人试过可以，5可能不行，编译一下试试，看看报什么错，有些api可能不支持

我的配置是cuda 10.0 ，cudnn 7.4.2 ，tensorflow 1.14.0
我试着安装TensorRT 7.0，把cudnn升到7.6.5，但是yolov4就运行不了了，我看cuda 10.0和7.6.5也是匹配的，不知道什么原因

**Comment by yishunzhijian** [comment]
> > 6 有人试过可以，5可能不行，编译一下试试，看看报什么错，有些api可能不支持
> 
> 我的配置是cuda 10.0 ，cudnn 7.4.2 ，tensorflow 1.14.0
> 我试着安装TensorRT 7.0，把cudnn升到7.6.5，但是yolov4就运行不了了，我看cuda 10.0和7.6.5也是匹配的，不知道什么原因。我想问cudnn版本必须得是7.6.5嘛

**Comment by wang-xinyu** [comment]
我这边是7.6.5，  tensorrt  的DEB local repo packages里面好像有cudnn

tensorrt c++的环境最好不要和conda  python环境在一起，最好分开配置

**Comment by yishunzhijian** [comment]
> 我这边是7.6.5， tensorrt 的DEB local repo packages里面好像有cudnn
> 
> tensorrt c++的环境最好不要和conda python环境在一起，最好分开配置

不用管cudnn，直接装 tensorrt 的DEB local repo packages，是这个意思吗

**Comment by wang-xinyu** [comment]
应该是

**Comment by yishunzhijian** [comment]
> 应该是
你的tensorflow版本是多少呀？和这个有关系吗

**Comment by wang-xinyu** [comment]
我没装tf
