### ISSUE TITLE
Make Failed，Please help

### ISSUE THREAD

**Issue by LRJrj** [wang-xinyu/tensorrtx#960]
## Env

- GPU, RTX1060
- OS, Win10
- Cuda v11.1
- TensorRT version 8.2

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

E:\WorkRepository\Work\YoloV5\trt-4.0\tensorrtx-yolov5-v4.0\yolov5\yololayer.h(54): error : member function declared with "override" does not override a base class member
E:/WorkRepository/Work/YoloV5/trt-4.0/tensorrtx-yolov5-v4.0/yolov5/yololayer.cu(175): error : object of abstract class type "nvinfer1::YoloLayerPlugin" is not allowed:
2>            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider
>E:/WorkRepository/Work/YoloV5/trt-4.0/tensorrtx-yolov5-v4.0/yolov5/yololayer.cu(319): error : object of abstract class type "nvinfer1::YoloLayerPlugin" is not allowed:
2>            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider
E:/WorkRepository/Work/YoloV5/trt-4.0/tensorrtx-yolov5-v4.0/yolov5/yololayer.cu(328): error : object of abstract class type "nvinfer1::YoloLayerPlugin" is not allowed:
2>            pure virtual function "nvinfer1::IPluginV2::enqueue" has no overrider

CUDACOMPILE : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
2>yololayer.cu
2>D:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.1.targets(785,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "D:\Program Files\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"E:\WorkRepository\Work\YoloV5\trt-4.0\tensorrtx-yolov5-v4.0\yolov5\include" -I"E:\WorkRepository\Work\YoloV5\trt-4.0\TensorRT-8.0.1.6\include" -I"E:\OpenCV Version\opencv4.5.0\build\include" -I"E:\WorkRepository\Work\YoloV5\trt-4.0" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"     --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -std=c++11 -Xcompiler="/EHsc -Zi -Ob0" -g   -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -DWIN32 -D_WINDOWS -D_MWAITXINTRIN_H_INCLUDED -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W3 /nologo /Od /Fdyolov5.dir\Debug\vc142.pdb /FS /Zi /RTC1 /MDd /GR" -o yolov5.dir\Debug\yololayer.obj "E:\WorkRepository\Work\YoloV5\trt-4.0\tensorrtx-yolov5-v4.0\yolov5\yololayer.cu"”已退出，返回代码为 1。
2>已完成生成项目“yolov5.vcxproj”的操作 - 失败。

**Comment by ysesst93013** [comment]
Hi Do yolu fix it ?
