### ISSUE TITLE
多卡训练的wts生成engine会偶发报错

### ISSUE THREAD

**Issue by TinkingLoeng** [wang-xinyu/tensorrtx#964]
使用官方的YOLOv5n生成engine成功
![image](https://user-images.githubusercontent.com/28384596/162393972-55116f37-5324-4a6d-b5d8-ba50137f9b59.png)

使用自己训练的YOLOv5n生成engine失败（类别数已做修改）
![image](https://user-images.githubusercontent.com/28384596/162393876-98d94456-dec1-4c6b-9a5f-d053f9a434b0.png)

紧接着通过多次重复实验，发现YOLOV5n v6.0版本的代码，在将多卡训练得到的wts转成engine时会偶发失败，报错如上图。但同样的参数在单卡训练得到的wts基础上进行转换则可成功转成engine
![7358af12882132f0ba47a009e2493fe](https://user-images.githubusercontent.com/28384596/162694281-09b707d3-8289-438c-848f-aab4a9c21ff5.png)

**Comment by wang-xinyu** [comment]
@TinkingLoeng Maybe there is some difference between the .pt models.  You need to look into it.
