### ISSUE TITLE
rcnn on jetson nano issue

### ISSUE THREAD

**Issue by Mrwangxin1998** [wang-xinyu/tensorrtx#965]
## Env

- jetson nano B01
- ubuntu 18.04
- Cuda 10.2
- jetson-inference

## About this repo

构建engine   successfully，但是推理是遇到错误，错误如下：

![image](https://user-images.githubusercontent.com/48117937/162561720-49e035a9-55c3-4833-a515-72e5d016d652.png)

这个错误请问该如何解决？请问在jetson nano上的编译过程和ubuntu上一样么？

**Comment by bismarckkk** [comment]
你好，这个问题已经在#955 回复过了
修复该错误需要修改数个.cu文件中的max_thread变量，具体请看上述issue中的回复
