### ISSUE TITLE
请问我对YOLOv5结构做了一些调整比如加了注意力模块，Ghost卷积这种，是不是没有办法用这个repo了

### ISSUE THREAD

**Issue by 15050188022** [wang-xinyu/tensorrtx#966]
如题

**Comment by Lixinixn115** [comment]
请问您更改网络结构后tensorrt加速成功了吗？

**Comment by JimmyW-11** [comment]
> 如题

应该是不行的，另外问问老哥有啥解决方案么了？

**Comment by Hahahdamowang** [comment]
同问

**Comment by qiuchun** [comment]
可以修改yoov5.cpp里面的网络结构，然后重新编译一下的话，能不能推理呢，有大佬试过这个方法么？我就是在yolov5中增加了检测层和其他的注意力机制，就没法部署

**Comment by wang-xinyu** [comment]
If you modified the network structure, you need to modify the createEngine() function accordingly. Because the network definitions are hard coded in the cpp file.
