### ISSUE TITLE
使用GTX940M可以转换模型，推理无结果，其他型号的GPU可以

### ISSUE THREAD

**Issue by lqsweet** [wang-xinyu/tensorrtx#969]
## Env

- GPU, e.g. GTX940M, etc.
- OS, e.g,Win10, etc.
- Cuda 11.1
- TensorRT 8.0,1

## About this repo

master
yolov5-6.0

## Your problem

使用GTX940M可以转换模型，推理无结果，其他型号的GPU可以

**Comment by hijkzzz** [comment]
这卡TRT官方估计都不维护了
