### ISSUE TITLE
yolov5 cmake ..  fail , it is done, but a now problem when run make cmd

### ISSUE THREAD

**Issue by laomaup** [wang-xinyu/tensorrtx#970]
## Env

- GPU RTX1080Ti,
-  Ubuntu18.04
- Cuda version 10.2
- TensorRT  7.0.0

## About this repo

- yolov5
- yolov5s

## Your problem

- what is your command? e.g. `cmake ..`

cmake ..
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "opencv_calib3d" includes non-existent path

    "/usr/include/opencv"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

是什么问题，opencv没有编译安装好么，怎么解决，谢谢

**Comment by laomaup** [comment]
tensorrtx-master/yolov5/preprocess.cu:2:10: fatal error: opencv2/opencv.hpp: 没有那个文件或目录
 #include <opencv2/opencv.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at yolov5_generated_preprocess.cu.o.Debug.cmake:222 (message):
  Error generating
  /data/disk1/laoma/tensorrtx-master/yolov5/build/CMakeFiles/yolov5.dir//./yolov5_generated_preprocess.cu.o


CMakeFiles/yolov5.dir/build.make:511: recipe for target 'CMakeFiles/yolov5.dir/yolov5_generated_preprocess.cu.o' failed
make[2]: *** [CMakeFiles/yolov5.dir/yolov5_generated_preprocess.cu.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by evg-cv** [comment]
Hi @laomaup 
How are you?
So did you fix this problem?
