### ISSUE TITLE
使用官方yolov5s.pt转engine正常，自己训练后转engine失败

### ISSUE THREAD

**Issue by thekeyrz** [wang-xinyu/tensorrtx#971]
@wang-xinyu 麻烦帮忙看看

Loading weights: /project/train/models/exp/weights/best.wts
[E] [TRT] (Unnamed Layer* 214) [Convolution]: kernel weights has count 4608 but 32640 was expected
[E] [TRT] (Unnamed Layer* 214) [Convolution]: count of 4608 weights in kernel, but kernel dimensions (1,1) with 128 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 128 * 1*1 * 255 / 1 = 32640
[E] [TRT] (Unnamed Layer* 214) [Convolution]: kernel weights has count 4608 but 32640 was expected
[E] [TRT] (Unnamed Layer* 214) [Convolution]: count of 4608 weights in kernel, but kernel dimensions (1,1) with 128 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 128 * 1*1 * 255 / 1 = 32640
[E] [TRT] (Unnamed Layer* 214) [Convolution]: kernel weights has count 4608 but 32640 was expected
[E] [TRT] (Unnamed Layer* 214) [Convolution]: count of 4608 weights in kernel, but kernel dimensions (1,1) with 128 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 128 * 1*1 * 255 / 1 = 32640
[E] [TRT] (Unnamed Layer* 214) [Convolution]: kernel weights has count 4608 but 32640 was expected
[E] [TRT] (Unnamed Layer* 214) [Convolution]: count of 4608 weights in kernel, but kernel dimensions (1,1) with 128 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 128 * 1*1 * 255 / 1 = 32640
[04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] Building engine, please wait for a while...
[E] [TRT] (Unnamed Layer* 214) [Convolution]: kernel weights has count 4608 but 32640 was expected
[E] [TRT] (Unnamed Layer* 214) [Convolution]: count of 4608 weights in kernel, but kernel dimensions (1,1) with 128 input channels, 255 output channels and 1 groups were specified. Expected Weights count is 128 * 1*1 * 255 / 1 = 32640
[E] [TRT] Could not compute dimensions for (Unnamed Layer* 214) [Convolution]_output, because the network is not valid.
[E] [TRT] Network validation failed.
[04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] [04/13/2022-13:42:46] Build engine successfully!
yolov5: /project/library/tensorrtx/yolov5/yolov5.cpp:245: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::__cxx11::string&): Assertion `engine != nullptr' failed.
Aborted

**Comment by sicarioakki** [comment]
Were you able to solve this issue?

**Comment by xunfeng2zkj** [comment]
你自己训练的模型应该要修改类别

**Comment by danielzhangau** [comment]
I got the same issue. The office model are able to convert to engine file without any problems. But once I converted my custom trained model, the errors occurs.
@wang-xinyu
