### ISSUE TITLE
set the macro `USE_INT8` in yolov5.cpp  build engine error

### ISSUE THREAD

**Issue by weironggege** [wang-xinyu/tensorrtx#972]
## Env

- GPU 1080ti
- OS, ubuntu 18.04
- Cuda 10.2
- TensorRT 7.0.0.11

## About this repo

- yolov5s.wtx

## Your problem

- set the macro `USE_INT8` in yolov5.cpp then make
- it can build target yolov5
- but then run command: sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
- error occur
[W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles  terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
How i can solve the problem? please help

**Comment by laomaup** [comment]
do not forget step1, Prepare calibration images.....

**Comment by weironggege** [comment]
> 

I get...Thanks

**Comment by weironggege** [comment]
> ## Env
> * GPU 1080ti
> * OS, ubuntu 18.04
> * Cuda 10.2
> * TensorRT 7.0.0.11
> 
> ## About this repo
> * yolov5s.wtx
> 
> ## Your problem
> * set the macro `USE_INT8` in yolov5.cpp then make
> * it can build target yolov5
> * but then run command: sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
> * error occur
>   [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles  terminate called after throwing an instance of 'std::out_of_range'
>   what():  _Map_base::at
>   Aborted (core dumped)
>   How i can solve the problem? please help



> do not forget step1, Prepare calibration images.....

I get.....Thanks

**Comment by Lenan22** [comment]
> ## Env
> * GPU 1080ti
> * OS, ubuntu 18.04
> * Cuda 10.2
> * TensorRT 7.0.0.11
> 
> ## About this repo
> * yolov5s.wtx
> 
> ## Your problem
> * set the macro `USE_INT8` in yolov5.cpp then make
> * it can build target yolov5
> * but then run command: sudo ./yolov5 -s yolov5s.wts yolov5s.engine s
> * error occur
>   [W] [TRT] Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles  terminate called after throwing an instance of 'std::out_of_range'
>   what():  _Map_base::at
>   Aborted (core dumped)
>   How i can solve the problem? please help
Please refer to our open source quantization tool ppq, the quantization result is better than the quantization tool that comes with tensorrt, almost the same as the float32 model. https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md
