### ISSUE TITLE
转换后比原始模型准确率低很多，很多目标检测不到了，并且加速效果不明显，yolov5l转换后

### ISSUE THREAD

**Issue by laomaup** [wang-xinyu/tensorrtx#973]
## Env

- GPU, GTX1080Ti
- Ubuntu18.04
- Cuda 10.2
- TensorRT 7.0.0

## About this repo
转换后比原始模型准确率低很多，很多目标检测不到了。并且加速效果不明显，对比如下：
src yolov5l
C99019683_11-07-50-429276_12.jpg: 544x640 2 persons, 1 nomask, Done. (0.023s)
bus.jpg: 640x480 4 persons, 2 nomasks, Done. (0.023s)
test_00000500.jpg: 640x480 1 person, 1 mask, Done. (0.017s)
test_00000642.jpg: 640x544 3 persons, 1 mask, 3 nomasks, Done. (0.032s)
zidane.jpg: 384x640 2 nomasks, Done. (0.018s)

trt yolov5l
C99019683_11-07-50-429276_12.jpg'], time->18.63ms, saving into output/
zidane.jpg'], time->17.61ms, saving into output/
bus.jpg'], time->18.62ms, saving into output/
test_00000642.jpg'], time->17.42ms, saving into output/

**Comment by stwrd** [comment]
我也发现了同样的现象，有些目标检测不到，同时置信度相差较大，正在定位问题

**Comment by younglalala** [comment]
同问

**Comment by laomaup** [comment]
可能是置信度/IOU设置问题，调以下参效果好了

**Comment by stwrd** [comment]
和置信度关系应该不大，我用多组图片对比过，有的置信度高有的置信度低。问题我没有在跟了，业务时间比较急，换了onnx to engine的方式，现在结果一致了。

**Comment by wusheng816** [comment]
同问，跪求解决方案！！！

**Comment by xiaoche-24** [comment]
> 和置信度关系应该不大，我用多组图片对比过，有的置信度高有的置信度低。问题我没有在跟了，业务时间比较急，换了onnx to engine的方式，现在结果一致了。

老哥，问一下你的onnx to engine是采用的这个代码库的代码推理的嘛？我yolov5 wts to engine推理正常，onnx to engine推理没有框，请问需要修改哪里吗
