### ISSUE TITLE
int8转换问题，能转成，但检测不到目标

### ISSUE THREAD

**Issue by laomaup** [wang-xinyu/tensorrtx#974]
## Env

- GPU,RTX1080Ti.
- Ubuntu18.04
- Cuda 10.2
- TensorRT 7.0.0

## About this repo

yolov5l/yolov5m/yolov5s

## Your problem
yolov5l 使用int8，make/转换都可以，推理时间明显减少，10ms即可，但是检测不到目标，阈值设置很低了都不行。
yolov5s/yolov5m,make/转换都可以，推理时间没有明显变化，有的甚至增加了，但是能检测到目标。
还在找问题

**Comment by Ziming-Zhang** [comment]
你好，请问你的问题解决了吗，我这边也是发现int8推理结果明显不对，conf也下降了好多

**Comment by hijkzzz** [comment]
建议升级到TRT8的最新版，如果还有问题就去TRT github提issue

**Comment by 1786022701** [comment]
你好，你的问题解决了吗？我使用yolov5m、yolov5l推理时间比FP16增加了好多，可以检测到目标，yolov5s时间减少，可以检测到目标。

**Comment by Lenan22** [comment]
> ## Env
> ## Env
> * GPU,RTX1080Ti.
> * Ubuntu18.04
> * Cuda 10.2
> * TensorRT 7.0.0
> 
> ## About this repo
> yolov5l/yolov5m/yolov5s
> 
> ## Your problem
> yolov5l 使用int8，make/转换都可以，推理时间明显减少，10ms即可，但是检测不到目标，阈值设置很低了都不行。 yolov5s/yolov5m,make/转换都可以，推理时间没有明显变化，有的甚至增加了，但是能检测到目标。 还在找问题

tensorrt自带的量化算法比较简陋，难以解决一些模型的精度下降问题, 请参考我们的开源量化工具ppq，可以协助解决tensorrt的量化问题，https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md，有量化的精度推理问题欢迎在我们的社区提问

**Comment by Lenan22** [comment]
> ## Env
> ## Env
> * GPU,RTX1080Ti.
> * Ubuntu18.04
> * Cuda 10.2
> * TensorRT 7.0.0
> 
> ## About this repo
> yolov5l/yolov5m/yolov5s
> 
> ## Your problem
> yolov5l 使用int8，make/转换都可以，推理时间明显减少，10ms即可，但是检测不到目标，阈值设置很低了都不行。 yolov5s/yolov5m,make/转换都可以，推理时间没有明显变化，有的甚至增加了，但是能检测到目标。 还在找问题

tensorrt自带的量化算法比较简陋，难以解决一些模型的精度下降问题, 请参考我们的开源量化工具ppq，可以协助解决tensorrt的量化问题，有量化的精度推理问题欢迎在我们的社区提问，我们可协助帮你解决，https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md，

**Comment by Lenan22** [comment]
> ## Env
> ## Env
> * GPU,RTX1080Ti.
> * Ubuntu18.04
> * Cuda 10.2
> * TensorRT 7.0.0
> 
> ## About this repo
> yolov5l/yolov5m/yolov5s
> 
> ## Your problem
> yolov5l 使用int8，make/转换都可以，推理时间明显减少，10ms即可，但是检测不到目标，阈值设置很低了都不行。 yolov5s/yolov5m,make/转换都可以，推理时间没有明显变化，有的甚至增加了，但是能检测到目标。 还在找问题

tensorrt自带的量化算法比较简陋，难以解决一些模型的精度下降问题, 请参考我们的开源量化工具ppq，可以协助解决tensorrt的量化问题，有量化的精度推理问题欢迎在我们的社区提问，我们可协助帮你解决。 https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md

**Comment by Lenan22** [comment]
> 你好，请问你的问题解决了吗，我这边也是发现int8推理结果明显不对，conf也下降了好多
tensorrt自带的量化算法比较简陋，难以解决一些模型的精度下降问题, 请参考我们的开源量化工具ppq，可以协助解决tensorrt的量化问题，有量化的精度推理问题欢迎在我们的社区提问，我们可协助帮你解决。 https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md

**Comment by Lenan22** [comment]
> 你好，请问你的问题解决了吗，我这边也是发现int8推理结果明显不对，conf也下降了好多

tensorrt自带的量化算法比较简陋，难以解决一些模型的精度下降问题, 请参考我们的开源量化工具ppq，可以协助解决tensorrt的量化问题，有量化的精度推理问题欢迎在我们的社区提问，我们可协助帮你解决。 https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md
