### ISSUE TITLE
yolov5 v6.0版本

### ISSUE THREAD

**Issue by lyc728** [wang-xinyu/tensorrtx#977]
无法进行推理，使用代码无法得到推理结果，保存的图是原图

**Comment by Wangwang99999** [comment]
I found the reason, but don't know how to fix it.
There is no 'model.24.anchor_grid' in trained model with yolov5-6.0, but it do exist in pretrained models, and exist in yolov5-5.0 trained models.

**Comment by dao027** [comment]
> I found the reason, but don't know how to fix it. There is no 'model.24.anchor_grid' in trained model with yolov5-6.0, but it do exist in pretrained models, and exist in yolov5-5.0 trained models.

i got the same problem, yolov5s v6.1 , using official way to convert model:
python export.py --weights xxx.pt --include engine onnx --imgsz 640 --device 0 --batch-size 4

after compile and using:
./yolov5 -d ../test/xxx.engine ../samples

i got no result(no bbox) on output images

**Comment by wang-xinyu** [comment]
Guys, you need to find out why the trained model doesn't contain anchor info.

**Comment by dao027** [comment]
> Guys, you need to find out why the trained model doesn't contain anchor info.

roger, i will check this

**Comment by hua1024** [comment]
@dao027 Hei，I have the same problem , can you solved it?

**Comment by dao027** [comment]
> 

negative,  cant use engine file from yolov5 official convertion, u need to convert pth model to engine by way in this repo
