### ISSUE TITLE
resnet.cpp的data是不是必须要将3*224*224展开成一维数组

### ISSUE THREAD

**Issue by TinkingLoeng** [wang-xinyu/tensorrtx#978]
请问resnet.cpp的data是不是必须要将3*224*224展开成一维数组
请问怎么将图片转成这种所需的data数组
![image](https://user-images.githubusercontent.com/28384596/163962188-e8156a45-4ec0-41c1-ad8a-9a3b0848401b.png)

**Comment by TinkingLoeng** [comment]
done

**Comment by jinqi2376** [comment]
@TinkingLoeng 你好～麻烦请问一下你是怎么搞定这个问题的，我搞不明白图片输入通过什么通道顺序展开成一维数组～
