### ISSUE TITLE
请教yolov3-spp的问题，输入尺寸大于等于864就会报段错误

### ISSUE THREAD

**Issue by clw5180** [wang-xinyu/tensorrtx#98]
如果在yololayer.h中修改输入尺寸大于等于864，在清理完build，cmake..，make后，执行 sudo ./yolov3-spp -s的时候直接就会报Segmentation fault；小于这个尺寸比如416，608,640之类都没问题。
另外我是2080Ti，显存应该不是问题；非常感谢大佬指教！

**Comment by wang-xinyu** [comment]
感谢反馈. I just fixed it. please refer to this commit https://github.com/wang-xinyu/tensorrtx/commit/2db3f47e066478e15989f1b0395c4282dac5e44d

**Comment by clw5180** [comment]
> 感谢反馈. I just fixed it. please refer to this commit [2db3f47](https://github.com/wang-xinyu/tensorrtx/commit/2db3f47e066478e15989f1b0395c4282dac5e44d)

感谢大佬！请教下为什么加个static就可以了，这个和尺寸大小还有关系么？

**Comment by wang-xinyu** [comment]
那个是input数组，input太大的话，如果不是static，就栈溢出了
