### ISSUE TITLE
retinaface改车牌识别后使用tensorrt推理出现问题

### ISSUE THREAD

**Issue by hello3281** [wang-xinyu/tensorrtx#980]
我使用retinaface修改后做车牌识别，我通过指引生成了.engine，在推理的过程中出现了问题，代码仅修改成了四个关键点，但是推理结果似乎问题很大，我是不是还漏掉了什么
![0_result](https://user-images.githubusercontent.com/91302837/163991824-8ecedf92-4f0a-434d-8a60-468a70ce887b.jpg)

**Comment by zhouyuchong** [comment]
@hello3281 你好，请问找到原因了吗，我也遇到了同样的问题。:confused:
