### ISSUE TITLE
yolov5.cpp:245: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&, float&, float&, std::__cxx11::string&): Assertion `engine != nullptr' failed. 已放弃

### ISSUE THREAD

**Issue by Lixinixn115** [wang-xinyu/tensorrtx#982]
yolov5    v5.0
use: jetson tx2
train: gtx 2070

Before, I used yolov5s.pt successfully added tensorrt. Recently, I trained my own data and reported this error in the title when using tensorrt to accelerate the generation of engine.       "sudo ./yolov5 -s ../yolov5s.wts yolov5s.engine s"

There are one class in my data. I had chage the CLASS_NUM in yololayer.h, then "make", but it didn't work. 
Looking forward to reply.

**Comment by Lixinixn115** [comment]
I have salved this problem, thankyou.

**Comment by goodworth1** [comment]
> I have salved this problem, thankyou.

how to solve this problem? Tell me please!

**Comment by Lixinixn115** [comment]
when generate "".wts file, I forgot to change the path of "".pt file in gen_wts.py

**Comment by Lixinixn115** [comment]
when generate"".wts file, i forgot to change the path of "".pt file in gen_wts.py




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月8日(星期天) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [wang-xinyu/tensorrtx] yolov5.cpp:245: void APIToModel(unsigned int, nvinfer1::IHostMemory**, bool&amp;, float&amp;, float&amp;, std::__cxx11::string&amp;): Assertion `engine != nullptr&#39; failed. 已放弃 (Issue #982)





  
I have salved this problem, thankyou.
  
how to solve this problem? Tell me please!

**Comment by Lixinixn115** [comment]
gen_wts.py:     In the eighth line, change the path of "best.pt" to your own "  .pt" path

import torch
import struct
from utils.torch_utils import select_device

# Initialize
device = select_device('cpu')
# Load model
model = torch.load('best.pt', map_location=device)['model'].float()  # load to FP32
model.to(device).eval()

f = open('yolov5s.wts', 'w')
f.write('{}\n'.format(len(model.state_dict().keys())))
for k, v in model.state_dict().items():
    vr = v.reshape(-1).cpu().numpy()
    f.write('{} {} '.format(k, len(vr)))
    for vv in vr:
        f.write(' ')
        f.write(struct.pack('>f',float(vv)).hex())
    f.write('\n')

**Comment by Taikonaut-llk** [comment]
I can't solve it by your method
