### ISSUE TITLE
yolov3的gen_wts.py中load_darknet_weights报错，一直找不到这个函数

### ISSUE THREAD

**Issue by ReLesEason** [wang-xinyu/tensorrtx#991]
## Env

- GPU, e.g. V100, RTX2080, TX2, Xavier NX, Nano, etc.
- OS, e.g. Ubuntu16.04, Win10, etc.
- Cuda version
- TensorRT version

## About this repo

- which branch/tag/commit are you using?
- which model? yolov5, retinaface?

## Your problem

- what is your command? e.g. `sudo ./yolov5 -s`
- what's your output?
- what output do you expect?

**Comment by ReLesEason** [comment]
还有Darknet，我导入from darknet import Darknet后，运行会提示参事个数不对

**Comment by wang-xinyu** [comment]
Hi,  check the readme,   are you using the archive branch of yolov3?
