### ISSUE TITLE
make error   CMakeFiles/yolov5.dir/build.make:147: recipe for target 'yolov5' failed

### ISSUE THREAD

**Issue by W8ming** [wang-xinyu/tensorrtx#992]
[100%] Linking CXX executable yolov5
/usr/bin/ld: warning: libnvrtc.so.10.2, needed by /home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.10, needed by /home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublasLt.so.10, needed by /home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1, not found (try using -rpath or -rpath-link)
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasGetProperty@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcGetProgramLogSize@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcGetPTXSize@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatrixLayoutDestroy@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcDestroyProgram@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcGetPTX@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtGetProperty@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasHgemmStridedBatched@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcCreateProgram@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcCompileProgram@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulDescCreate@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcGetProgramLog@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoConfigSetAttribute@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasDestroy_v2@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoGetHeuristic@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasSgemmEx@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasGemmStridedBatchedEx@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmul@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasCreate_v2@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtDestroy@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasGemmEx@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcVersion@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoInit@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulDescDestroy@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatrixLayoutSetAttribute@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasSgemmStridedBatched@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulDescSetAttribute@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasSetStream_v2@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libnvinfer.so: undefined reference to `nvrtcGetErrorString@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoConfigGetAttribute@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulPreferenceSetAttribute@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLoggerConfigure@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulPreferenceCreate@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatrixLayoutCreate@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulAlgoCheck@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtMatmulPreferenceDestroy@libcublasLt.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasSetMathMode@libcublas.so.10'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `nvrtcGetLoweredName@libnvrtc.so.10.2'
/home/zy/download/TensorRT-7.2.2.3/lib/libmyelin.so.1: undefined reference to `cublasLtCreate@libcublasLt.so.10'
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5.dir/build.make:147: recipe for target 'yolov5' failed
make[2]: *** [yolov5] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/yolov5.dir/all' failed
make[1]: *** [CMakeFiles/yolov5.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

please help!

**Comment by W8ming** [comment]
cmake .. 
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0")
-- Found OpenCV: /usr/local (found version "4.5.1")
-- Configuring done
-- Generating done

**Comment by lkcl0928** [comment]
respect，did you fix this problem and I have the same problem。

**Comment by wang-xinyu** [comment]
You have installed cuda10.0,  but you tensorrt depends on cuda10.2.

You need to install proper version of cuda&tensorrt.
