### ISSUE TITLE
Tensorrt doInference一帧推理时间不稳定

### ISSUE THREAD

**Issue by zhuimeng2080** [wang-xinyu/tensorrtx#993]
请教大佬，如题，是单GPU显卡， doInference一帧推理的时候有时是40ms, 有时候是150ms,有时候是80ms, 一般是什么原因？

**Comment by wang-xinyu** [comment]
did you try to test it in loop?

**Comment by tang662019** [comment]
> did you try to test it in loop?

大佬，我也遇到这个问题，循环跑图片推理时间固定10ms左右，但是通过以下语句：
cv::imshow("img", img);
cv::waitKey(1000);
让测试图片之间停顿1秒，这种情况下时间就不稳定了，基本是>70ms，测试了时间开销在于以下语句：
CUDA_CHECK(cudaMemcpyAsync(output, d0_buffers[1], batchSize * OUTPUT_SIZE * sizeof(float), cudaMemcpyDeviceToHost, d0_stream));
 cudaStreamSynchronize(d0_stream);

请问这是否与tensorRT框架实现有关？

**Comment by hnothing2016** [comment]
> > did you try to test it in loop?
> > @
> > 大佬，我也遇到这个问题，循环跑图片推理时间固定10ms左右，但是通过以下语句：
> > cv::imshow("img", img);
> > cv::waitKey(1000);
> > 让测试图片之间停顿1秒，这种情况下时间就不稳定了，基本是>70ms，测试了时间开销在于以下语句：
> > CUDA_CHECK(cudaMemcpyAsync(output, d0_buffers[1], batchSize * OUTPUT_SIZE * sizeof(float), cudaMemcpyDeviceToHost, d0_stream));
> > cudaStreamSynchronize(d0_stream);
> 
> 请问这是否与tensorRT框架实现有关？

我现在也是这个问题，这样都不能真的用于生产，，，
