### ISSUE TITLE
yolov5s-6.0 P6转换后检测异常问题

### ISSUE THREAD

**Issue by WuxinrongY** [wang-xinyu/tensorrtx#997]
作者，您好，我在VisDrone数据集训练了yolov5-6.0-s6模型，并根据指导转换成功。
但是，还有2个问题需要请教：
1. P6模型输入为1280*1280，是否需要修改netlayer.h中INPUT_W和INPUT_H？
2. 我在修改后，转换模型成功，但是用1280的size检测图片是，结果为空，改为640检测时，检测结果正确，这个问题您有什么想法吗？

**Comment by wang-xinyu** [comment]
did you rebuild the trt model after changing W&H?

**Comment by WuxinrongY** [comment]
Sorry, I deal with it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wang-xinyu/tensorrtx] yolov5s-6.0 P6转换后检测异常问题 (Issue #997)





 
did you rebuild the trt model after changing W&amp;H?

**Comment by WuxinrongY** [comment]
Sorry, I deal with it thought rebuild.
"make" and "cmake" did not solve the problem, so I deleted "build" folder, and rebuild project.
Thanks for your reply!

**Comment by WuxinrongY** [comment]
"make"&nbsp;and "cmake" did not solve the problem, so I&nbsp;deleted "build" folder, and rebuild project.
Thanks for your reply!




------------------ 原始邮件 ------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wang-xinyu/tensorrtx] yolov5s-6.0 P6转换后检测异常问题 (Issue #997)





 
did you rebuild the trt model after changing W&amp;H?
